### ISSUE TITLE
Introduce Site Kit's own Google_Client implementation

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1003]
## Feature Description

Over time, a few improvements have been made to the `Google_Proxy_Client` class that actually do not only apply to the proxy, but improve behavior of Site Kit overall. Such modifications however are currently only taking effect with the proxy in use, but not e.g. during local development.

Let's introduce a `Google_Site_Kit_Client` class that contains this functionality.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a `Google_Site_Kit_Client` class that extends `Google_Client` with the following features:
    * It should allow providing a `token_exception_callback` so that Site Kit can handle an exception thrown while refreshing an access token on the fly, and inform the user about it.
    * When fetching a token fails with an error response, that error should be thrown as exception. `Google_Client` only does this for failing requests, but there is no awareness of the actual error response otherwise. The exception thrown from this should be a `Google_OAuth_Exception`, with the `error` parameter as message.
* The `Google_Proxy_Client` class should be renamed to `Google_Site_Kit_Proxy_Client` and extend `Google_Site_Kit_Client`. The functionality now in `Google_Site_Kit_Client` should be removed.
* `OAuth_Client::get_client()` should instantiate a `Google_Site_Kit_Client` at all times.
* `Module` and its sub-classes should rely on `Google_Site_Kit_Client` instances.

## Implementation Brief

* Merge #981.

## Changelog entry

* Introduce Site Kit-specific `Google_Client` implementation and use that throughout the codebase.

**Comment by aaemnnosttv** [comment]
## QA

Due to the more technical under-the-hood nature of this issue, I will match AC to the related implementation that meets it. 

> There should be a `Google_Site_Kit_Client` class that extends `Google_Client`

✅ https://github.com/google/site-kit-wp/blob/e9601e4c7ad92c6709ae3ef17c8a12ee3861e39e/includes/Core/Authentication/Clients/Google_Site_Kit_Client.php#L30

> It should allow providing a `token_exception_callback` so that Site Kit can handle an exception thrown while refreshing an access token on the fly, and inform the user about it.

✅ https://github.com/google/site-kit-wp/blob/e9601e4c7ad92c6709ae3ef17c8a12ee3861e39e/includes/Core/Authentication/Clients/Google_Site_Kit_Client.php#L47-L66
https://github.com/google/site-kit-wp/blob/e9601e4c7ad92c6709ae3ef17c8a12ee3861e39e/includes/Core/Authentication/Clients/Google_Site_Kit_Client.php#L105-L117

> When fetching a token fails with an error response, that error should be thrown as exception. `Google_Client` only does this for failing requests, but there is no awareness of the actual error response otherwise. The exception thrown from this should be a `Google_OAuth_Exception`, with the error parameter as message.

✅ https://github.com/google/site-kit-wp/blob/e9601e4c7ad92c6709ae3ef17c8a12ee3861e39e/includes/Core/Authentication/Clients/Google_Site_Kit_Client.php#L203-L232

> The `Google_Proxy_Client` class should be renamed to `Google_Site_Kit_Proxy_Client` and extend `Google_Site_Kit_Client`

✅ https://github.com/google/site-kit-wp/blob/e9601e4c7ad92c6709ae3ef17c8a12ee3861e39e/includes/Core/Authentication/Clients/Google_Site_Kit_Proxy_Client.php#L25-L29

> `OAuth_Client::get_client()` should instantiate a `Google_Site_Kit_Client` at all times.

✅ https://github.com/google/site-kit-wp/blob/e9601e4c7ad92c6709ae3ef17c8a12ee3861e39e/includes/Core/Authentication/Clients/OAuth_Client.php#L178-L191

> `Module` and its sub-classes should rely on `Google_Site_Kit_Client` instances.

✅ https://github.com/google/site-kit-wp/blob/e9601e4c7ad92c6709ae3ef17c8a12ee3861e39e/includes/Core/Modules/Module.php#L570-L581

Plugin authentication and functionality continues to work the same as before.

Moving to Approval.
