### ISSUE TITLE
Fix conflicting messages when user has insufficient scopes 

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#1042]
## Feature Description

When the user has insufficient scopes to display a specific module, we show conflicting messages to them: "Issue accessing data" and at the dame time "$MODULE is connected" and "gathering data". Here's how this looks for Analytics: 

<img width="1153" alt="Screenshot 2020-01-15 at 15 26 35" src="https://user-images.githubusercontent.com/13304791/72441809-9790b580-37ab-11ea-8f53-02508311fb37.png">

Let's fix this. 
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
For cases where the user doesn't have sufficient scopes to display stats from a specific module:
* Replace "$MODULE is connected" with "$MODULE is not connected": 
<img width="203" alt="Screenshot 2020-01-15 at 15 29 14" src="https://user-images.githubusercontent.com/13304791/72441943-de7eab00-37ab-11ea-8754-89a95efe7812.png">
* Replace "$MODULE gathering data" message with the following: heading "Setup incomplete", body: "Insufficient permissions. Resume module setup to fix this."  

## Implementation Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
Seems like the "gathering data" message has been updated to "complete Analytics activation". Still, we do a weird thing -- showing the All Traffic section title but nothing in the actual contents. 

![site-kit-ga-no-scopes](https://user-images.githubusercontent.com/13304791/114409233-869b4380-9baa-11eb-966f-81223dfebe3d.png)

**Comment by felixarntz** [comment]
@marrrmarrr As previously assumed, the main problem here (empty "Your Traffic" section) is fixed with the widget-based version of the dashboard, which will start to roll out in 1.31.0 (see screenshot below).

![Screen Shot 2021-04-13 at 11 27 52 AM](https://user-images.githubusercontent.com/3531426/114602386-666f9100-9c4b-11eb-9141-043aec9b627c.png)

The other points for improving the activation CTA and error message are still relevant (as seen above), but they are technically correct, and as discussed this should be scoped as upcoming UX work rather than through this issue.
