### ISSUE TITLE
Adjust verbiage from 'Cancel' to 'Back' where user is presented an expected error message

### ISSUE THREAD

**Issue by cole10up** [google/site-kit-wp#1045]
## Bug Description

While testing https://github.com/google/site-kit-wp/issues/433 I noticed during the error flow the verbiage on the lower call to action is labeled 'Cancel' although the user's action was already canceled due to an error.

![image](https://user-images.githubusercontent.com/57115907/72454222-52519100-3775-11ea-923b-9a45f6903003.png)

## Steps to reproduce

1. Adjust tag manager permissions after placing snipped on FE
2. Run through Tag Manager service setup

Notice the expected error occurs and the user is presented a cancel button

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Cancel" link in the footer of the module set up wrapper (`ModuleSetup`) should use alternate text content in the case where the user is blocked from proceeding (such as when there is an existing tag that the user does not have access to)
* In this case, the link should have the text content "Back"
* This should be implemented via a new piece of centralized infrastructure that _could_ be used for every module. However, for now it should only be implemented specifically for the AdSense module, when an ad blocker is active and therefore prevents the setup.

## Implementation Brief

* Using `assets/js/googlesitekit/data/utils.js`,
	* Update `createValidationSelector`, add a second parameter which is an object with `negate : false` as default value, which indicates whether to negate the boolean result or not.
		* Instead of returning `true` or `false`, return the appopriate boolean value based on `negate`.
* Using `assets/js/googlesitekit/modules/create-module-store.js`,
	* Update `createModuleStore`:
		* to add another key, `validateIsSetupBlocked` for any options which is a function to validate whether module setup is terminally blocked from continuing.
		* If `requiresSetup` is `true` and `validateIsSetupBlocked` is defined, call `createValidationSelector`, with `negate: true` and add the results to the list of selectors. They should be:
			* `isSetupBlocked` for the safe selector
			* `__dangerousIsSetupBlocked` for the unsafe one.

* All those changes above can be viewed in the following branch: `poc/1045-is-setup-blocked`

*  Using `assets/js/modules/adsense/datastore/base.js`,
	* When creating the module store, i.e when calling `Modules.createModuleStore`, define `validateIsSetupBlocked` in the options object and using the `adsense` data store.
		* check if there is an ad blocker active via the `isAdBlockerActive` selector. If this is the case, throw an error.
* Create `assets/js/components/setup/ModuleSetupFooter.js` which renders the same markup within `googlesitekit-setup__footer` in `assets/js/components/setup/ModuleSetup.js` with the following changes:
	* It accepts the `module` prop.
	* Use `Grid`, `Row` and `Cell` for the grid layout.
	* Query whether the setup is blocked via the `isSetupBlocked` selector. The module store name can be obtained via `module.storeName` and since not all modules have this selector defined, it can be queried as such:
	```js
	const isSetupBlocked = useSelect( ( select ) =>
		select( module.storeName )?.isSetupBlocked?.()
	)
	```
	* If the selector returns `true`, display `Back`, else display `Cancel` as it is currently.
* Update `assets/js/components/setup/ModuleSetup.js`:
	* to use `ModuleSetupFooter`.
	* to use `Grid`, `Row` and `Cell` for the grid layout.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes

* 

## QA Brief
* Disconnect AdSense module.
* Enable your AdBlocker and proceed to setup AdSense module.
* Instead of displaying "Cancel", the verbiage should be "Back" when the AdSense AdBlocker error is displayed.
* Disable your AdBlocker, the link should be: "Cancel"

## Changelog entry

* Update the cancel button on the module setup form to have a `Back` label when the setup process can't proceed.

**Comment by danielgent** [comment]
Hey @tofumatt :wave: 

I'd be happy to chat about this, but now I've realized that the P0s are priority, I'll leave these P2s until after I've written IBs for all the P0s  :smile: 

It's the classic React child-component-controlling-a-parent situation.  

The problem with lifting the state up into the data stores is how will we know that the text should be `cancel` again?  When `ModuleSetup` mounts again?  Should each `SetupMain` inner component dispatch an action to reset the text to Cancel? 
That is a bit tricky

The inner `SetupMain` already tells the parent `ModuleSetup` when it has completed with `finishSetup` so thus I thought I'd continue the same pattern with a `failSetup` callback prop.  `ModuleSetup` needs to know if the inner component is done, failed, or in progress. 

An alternative (which is probably cleaner) is to move the bottom button bar from `ModuleSetup` into the child `SetupMain`

Happy to chat about this though and see if we come up with a better idea :+1:

**Comment by danielgent** [comment]
Hey @tofumatt 

I changed my demo PR to read and write to `CORE_UI`

I'm gonna change the IB now


I'd confused myself because this *is not* an SPA! So the redux state gets reset when changing pages

I'd thought that the "Back" button text would get stuck for future module setups! (Which it doesn't of course, as the video shows)

https://user-images.githubusercontent.com/8496063/129910384-aa4671c7-c894-4378-acb1-93dccb366c3c.mp4


Just to note though that the flow hasn't really changed, the inner component does a side-effect which changes the outer component, but now we're using Redux so it's acceptable I suppose

**Comment by aaemnnosttv** [comment]
The current IB is a bit too specific to handling the existing tag case which is not the only case in which a user can be blocked from completing the module setup, but also will no longer be blocking in the future.

I would prefer to see a more generic solution, perhaps by extending the module's store with a selector like `isSetupBlocked`. This could be created by `createModuleStore` and take a function which would allow this to be configured per-module as needed. Alternatively, we could use `CORE_UI` to store this value and set it from the module as needed rather than rolling a new selector for this.

Thoughts @felixarntz @tofumatt ?

**Comment by felixarntz** [comment]
@aaemnnosttv I like the idea of an `isSetupBlocked` selector with a function to control its value. 👍

**Comment by aaemnnosttv** [comment]
@felixarntz @tofumatt – I discussed this issue with @johnPhillips today and it seems that the effort involved here may be a bit premature. I think that a `isSetupBlocked` selector could be valuable but it seems a bit overkill to add it at this point – plus additional changes to the core module store since we need to select this from a shared module setup component – only to change the wording of the cancel link here. I created a [POC branch](https://github.com/google/site-kit-wp/compare/poc/1045-is-setup-blocked) to show how this could work (just the selector, not hooked up into `ModuleSetup`), which isn't a huge lift, but only implements the logic for GTM.

Just think we may want to reconsider this if only to use in this one place, which seems quite minor.

Thoughts?

**Comment by felixarntz** [comment]
@aaemnnosttv Hmm, is it really overkill? I see how it may feel so since the goal of this issue is to only change the button label, but whether a module setup is blocked is something that in principle can be relevant for any module, so I think integrating the implementation into "core" makes sense. Right now we already have a need for it in GA and GTM, and you could argue a similar change would make sense in AdSense for the cases when the user is in a scenario where they just have to wait for AdSense review etc.

**Comment by aaemnnosttv** [comment]
@felixarntz I think the selector makes sense, my concern was about it only being used for this. If we can foresee other uses then that's fine with me 👍

**Comment by aaemnnosttv** [comment]
@eclarke1 – the IB needs to be rewritten as we got off track after the initial review here but it can be done by anyone, using https://github.com/google/site-kit-wp/compare/poc/1045-is-setup-blocked as a starting point.

**Comment by aaemnnosttv** [comment]
Thanks @asvinb – the IB is just about there, the main thing missing is that `validateIsSetupBlocked` should also be defined for Analytics and AdSense as well as this issue applies to all modules where the user can become blocked from completing setup.

The conditions for this vary a bit from module to module so the easiest way to find out is to look and see when some kind of `*Error` component is rendered in the various `Setup` components as the `viewComponent`.

So for GTM, the `ExistingTagError` is the only error case. Analytics has similar cases, but also an `ExistingGTMPropertyError`.

Maybe @felixarntz can advise on the conditions for AdSense but the easiest one is for a detected adblocker – there are probably a few others though.
![image](https://user-images.githubusercontent.com/1621608/147140460-810ffbc2-5d07-4fe1-80c7-424776aec738.png)

**Comment by asvinb** [comment]
@aaemnnosttv I've updated the IB to include Analytics and AdSense. However for AdSense, there can be multiple checks depending on the account status. We will potentially end up duplicating a lot of the code we have in `assets/js/modules/adsense/components/setup/SetupMain.js` to `assets/js/modules/adsense/datastore/base.js`. For instance `determineAccountStatus` is dependent of lots of `useSelect` calls. If you're fine with duplicating the code, I'll update the IB to cater for that. Let me know what you think.

**Comment by aaemnnosttv** [comment]
Thanks @asvinb – regarding AdSense, I'll defer to @felixarntz 🙂

**Comment by felixarntz** [comment]
@asvinb @aaemnnosttv Given that we'll work on the simplification of the existing tag detection (epic #4448) very soon, I'm not sure this is worth working on at this point, since several of the blocking conditions will go away, which would simplify the implementation here accordingly.

I suggest we push this back to _Backlog_ and add it to that epic, to have a reminder that we should do it as part of that?

cc @eclarke1 @FlicHollis to remove from the upcoming sprint

**Comment by aaemnnosttv** [comment]
@felixarntz alternatively we could simplify the logic for AdSense specifically here to only cover the adblocker and leave the remaining part for the backlog in a new issue? Most of this is still actionable now 🙂

**Comment by felixarntz** [comment]
@aaemnnosttv Good point that we can probably still move parts of this forward already. However, I think the only module-specific integration that we should cover in here for now is the AdSense setup part of having an ad blocker, as that will remain relevant in the future. The Tag Manager and Analytics cases where the setup is currently blocked will be drastically simplified, and therefore it's not worth covering that here just to remove it again later. The AdSense setup flow itself will change quite a bit too.

I've therefore added a third point to the ACs that clarify that the actual implementation of that new API infrastructure should only be done for the ad blocker part of AdSense as part of this issue. @asvinb If that sounds good, can you please update the IB accordingly and remove all the parts regarding Tag Manager and Analytics? Other than that, this should be good to go.

**Comment by asvinb** [comment]
Thanks @felixarntz @aaemnnosttv . IB updated!

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When AdBlocker is enabled the text link is "Back"
- When AdBlocker is disabled, the link text says "Cancel"

![image](https://user-images.githubusercontent.com/73545194/150777501-6b535420-2a45-4a12-a580-f2f1fdb5521a.png)
