### ISSUE TITLE
Mirror minimum PHP requirement of WordPress core

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1050]
## Feature Description

WordPress core somewhat recently raised its minimum required version of PHP from 5.2 to 5.6 in v5.2.

https://make.wordpress.org/core/handbook/contribute/php-compatibility-and-wordpress-versions/

As WordPress core raises its minimum supported version of PHP, tooling in the WP ecosystem is following core in raising their required versions as well.

Site Kit currently requires PHP 5.4 or higher. This conflicts with the required PHP versions of some packages that we rely on via Composer, such as [PHP Scoper](https://packagist.org/packages/humbug/php-scoper) and even [VIP PHPCS Rules](https://packagist.org/packages/automattic/vipwpcs) which require PHP 7.2 and 5.6 respectively.

PHP 5.6 has been EOL for just over a year now and PHP 7.2 is the lowest version of PHP which will no longer be supported as of December. https://www.php.net/supported-versions.php.

One way to not stay too far behind would be to adopt a policy of following the minimum PHP requirement of WordPress core after X number of major releases. That is, if X were 1, and the minimum PHP version changed in WP 5.2, then we would bump ours to match when 5.3 was released. This kind of policy would let users know when to expect Site Kit's minimum to change and prepare accordingly.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
The requirements bump to PHP 5.6 has already been covered via #547

While in a perfect world it would be great to define a policy for PHP version support, I'm not sure we can enforce a policy at this point. Maybe we could always say to follow what WordPress core does in terms of PHP requirements, but since it's acting unpredictably in that regard, I'd rather review this on a case-by-case basis whenever WordPress updates its requirements.
