### ISSUE TITLE
Setup not working

### ISSUE THREAD

**Issue by bellirafael** [google/site-kit-wp#1074]
When starting the setup I allow all access and when it finishes it goes back to the setup start screen again.
I already checked the https site addresses and reset and installed the plugin

**Comment by artemkolotilkin** [comment]
I'm having the same issue. Trying to see if it's a known issue and there is a recommend way to fix it.

**Comment by MauriceArikoglu** [comment]
Also broken for me.
The Console on https://sitekit.withgoogle.com/site-management/setup/ shows a 400 Bad Request error and informs about a missing "nonce" parameter while trying to complete the last step:

> Set up Search Console
> 
> We'll add mysite.com to Search Console so you can see how people find your site on Search.
> 

Clicking Add Site results in aforementioned error in the console. Website does not change after it stops loading.

_______
I don't have any plugins aside from SiteKit installed. WP 5.3.2, SiteKit 1.2.0, PHP 7.3, HTTPS enabled (+HTTPS redirect)
The website is using German Umlauts, but due to IDA this should not be an issue I suppose.

**Comment by jamesozzie** [comment]
@bellirafael @artemkolotilkin @MauriceArikoglu Thanks for reporting. We have moved Site Kit support to the WordPress support forum. You can open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we can assist. Please add as much relevant information to your support topic as is needed to assist with your issue.
