### ISSUE TITLE
SiteGround staging environment and helper plugin

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1152]
This is a marker for continued discussion and investigation on [the staging environment helper plugin](https://sitekit.withgoogle.com/documentation/using-site-kit-on-a-staging-environment/) and SiteGround's staging environment setup. 

Currently there are limitations in their environment that aren't compatible with the way the helper plugin works. The _Custom Site URL_  is dynamically changed from the production site to the staging site URL via "a special webserver module that replaces it [the URL] once it is requested by a client" , which prevents the plugin from working. More about this from SiteGround support (modified original domain name to example.com): 

> The reason the URL "cannot" be changed is because of how our staging tool is set to work. In simple terms, it masks any URL that is "example.com" with the staging URL "staging3.example.com".
> 
> If you look in the database itself, the record is saved as "https://example.com" but displayed as "staging3.example.com" due to the configuration and functionality of the staging. Basically it saves it as the correct value but displays it with the staging3 one.

Additionally: 

> WordPress knows the domain is staging3 due to the IP masking that occurs on the server level. For example, when you visit, the site via the staging3 url, it sends the request to the Apache web server and in the backend, it simulates the request as if the request came in for example.com.

Related support topic: https://wordpress.org/support/topic/sitekit-not-working-with-staging-site/

**Comment by jamesozzie** [comment]
I tested this today and the issue remains. Some additional insights below:
- By default a staging site on Siteground is http, resulting in the below when clicking on the "Get oAuth Credentials"
![image](https://user-images.githubusercontent.com/41326532/113865918-98dd4200-97a4-11eb-998e-fc692a255100.png)

When changing the request to include https I was able to proceed. I changed to the below format - which included https in the URL:
`https://developers.google.com/web/site-kit?sitename=My%20WordPress&siteurl=https%3A%2F%2Fstaging9.sgsite.mysite.com`

After inputting the newly created credentials and proceeding with SK setup I then encountered the below"

![image](https://user-images.githubusercontent.com/41326532/113866850-b65edb80-97a5-11eb-852b-64175ad40963.png)

In order to proceed, or as a workaround I navigated to that project in Google Cloud Platform and under "Credentials > OAuth 2.0 Client IDs > Edit" I added in the http callback and encountered the message  below:

![image](https://user-images.githubusercontent.com/41326532/113867988-1a35d400-97a7-11eb-8cac-721a506ac074.png)

I then went back to the app details (OAuth consent screen > Edit App > Change to testing. ). I then revisited the callback URLs and added both https and https. I then went back and changed the app status to production. 

After performing the above workaround I was able to proceed with displaying live site data on a SG staging site. 

Changing pipeline to backlog for an engineer review.

**Comment by felixarntz** [comment]
Potentially, an option here would be to introduce a filter for the `home_url()` value that is sent to this external configuration page, so that a hosting provider like SiteGround could include a mini must-use plugin or so to fix it. An open question we have to figure out first is whether such a filter would also apply to areas in Site Kit itself (where we e.g. use the `home_url()` for certain communication with the authentication proxy as well), or whether it should be added to the Site Kit developer settings plugin specifically.

cc @aaemnnosttv

**Comment by tofumatt** [comment]
Looks like we _do_ support filtering the `home_url()`: https://github.com/google/site-kit-wp/blob/de09a10c23b15d090ed2207693f6ac9e1bb67f7e/includes/Context.php#L170

I think that should cover the needed functionality here, as it would allow users to set the canonical URL for the site 🤔 

I think that should cover the use-case here, so I'm closing this as fixed 🙂
