### ISSUE TITLE
Enhance core/site store with isSetupComplete information and more granular selectors

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1173]
This is a follow-up to #999 (and #1000, although rather decoupled from that).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `core/site/data/connection` REST route should include `setupCompleted` in responses.
* The `core/site` store should have granular selectors that return specific information from the existing `getConnection`:
    * `isConnected`
    * `isResettable`
    * `isSetupCompleted`

## Implementation Brief

* Move `Permissions::is_setup_complete()` to `Authentication::is_setup_completed()` and make it public.
* Modify `Authentication::get_rest_routes()` so that `core/site/data/connection` includes `setupCompleted`, via `Authentication::is_setup_completed()`.
* Add the three individual selectors to `core/site` store, ensure they call `Data.select( 'core/site' ).getConnection()`, and return the respective property or `undefined` if not set.

## QA Brief

* 

## Changelog entry

* Add more granular selectors to the `core/site` datastore.

**Comment by tofumatt** [comment]
The approach here is correct but incomplete.

The issue with the approach here is that calling the selectors alone from another selector won't trigger the asynchronous action. Each selector (`isConnected()`, `isResettable()`, etc.) needs to have a resolver that triggers the `*getConnection()` resolver. This isn't too much boilerplate or effort, and still works fine.

So we'll need to add "create a resolver for each selector added that relies on `getConnection`" to the IB.

I've created a proof-of-concept PR with the `isConnected` selector, resolver, and tests. Feel free to use it as a basis for the IB, as I wanted to illustrate what's needed to make the resolver actually trigger. It's here: #1219.

-----

Additionally, I'd rather we return `null` or `undefined` if data is not available, not `false`. False implies we know about the state or that the data is set, but that it's not true. In the case of `isConnected` or `isResettable`, there is a subtle difference in terms of knowing it _can't be reset_ vs _we don't know if it can be reset_. In UI terms we would likely render that the same way: not showing or blanking out a "Reset" button. But the unknown state being marked as `false` rather than `null` would mean we could **never show a loading state** for that button, because we wouldn't know if `false` meant "Loading" or "cannot reset".

So I think the point about selectors should read:

> Add the three individual selectors to `core/site` store, ensure they call they have resolvers that trigger the `*getConnection()` resolver, and return the respective property or `null` if not set.

**Comment by tofumatt** [comment]
Oh, one other note: if we're adding discrete selectors for these bits of data, I'd argue we should mark `getConnection()` as `@private`. There's no reason to expose it to the public if we have better, more discrete selectors that don't expose the entire, complex object to developers.

**Comment by felixarntz** [comment]
@tofumatt 
> The issue with the approach here is that calling the selectors alone from another selector won't trigger the asynchronous action. Each selector (`isConnected()`, `isResettable()`, etc.) needs to have a resolver that triggers the `*getConnection()` resolver. This isn't too much boilerplate or effort, and still works fine.

Okay cool. Are there any potential side effects from this? Like if a component calls `isConnected` and `isResettable` right next to each other, it's not going to issue the request from the resolver twice right? That's what I'd want to avoid (this may be a noob store question 🙂).

> Additionally, I'd rather we return `null` or `undefined` if data is not available, not `false`. False implies we know about the state or that the data is set, but that it's not true. In the case of `isConnected` or `isResettable`, there is a subtle difference in terms of knowing it _can't be reset_ vs _we don't know if it can be reset_. In UI terms we would likely render that the same way: not showing or blanking out a "Reset" button. But the unknown state being marked as `false` rather than `null` would mean we could **never show a loading state** for that button, because we wouldn't know if `false` meant "Loading" or "cannot reset".

That kind of makes sense, but should a component need to cater for that? Like what would a component (e.g. one that conditionally shows a setup screen) do if the value of `isConnected` was null/undefined? Also, what about more specifically selectors that typically returns objects/arrays where returning null/undefined could easily cause actual errors if the component expects an object/array? I'd just like to better understand what your thoughts are about how to deal with this overall. And then, if we decide to go with that, what's better and more generally applicable, null or undefined? We should pick one. (This is a general question that also ties in with our guidelines, so let's define that here (and adjust existing datastores if we decide on something different than what's currently in place).)

**Comment by tofumatt** [comment]
> Okay cool. Are there any potential side effects from this? Like if a component calls isConnected and isResettable right next to each other, it's not going to issue the request from the resolver twice right? That's what I'd want to avoid (this may be a noob store question 🙂).

Not at all a noob question! 😄If we were using a vanilla `redux-saga` setup, we'd have to declare how we want subsequent async handlers to behave. It's a bit more manual (but flexible) in vanilla setups.

The way `@wordpress/data` uses resolvers is that they are a first-time-called side effect: https://developer.wordpress.org/block-editor/packages/packages-data/#resolvers. Some of our existing resolver tests already check for this behaviour: https://github.com/google/site-kit-wp/blob/develop/assets/js/googlesitekit/datastore/site/connection.test.js#L99

We make sure `fetch()` is only called once, even though the selector that triggers the resolver (`getConnection()`) is called several times there before it fulfills.

So TL;DR is: `@wordpress/data` manages selectors for us and we can call the selector many times but only have it use the resolver once. 👍

----

For `isConnected`, the answer is straightforward: if `isConnected` is `false`, it means we do not have a connection for this site + user combo to Site Kit. We should show a "Start setup" screen, from what I understand. If it's `null`/`undefined`, we show a "loading" screen, because we're still fetching info.

On that particular—very low-level and fundamental—selector we may rarely encounter a difference between `false` and `null`/`undefined`, but I think it's good to set a pattern we'll use for other selectors going forward. Equating `false` with "unknown" limits our state's usefulness in displaying fine-grained UIs in the future and it's easy to implement a `null`/`undefined` value as the fallback, so it's worth doing.

If the return value would be an object or array I would still expect `null`/`undefined` as the "unknown" value. If we, for instance, return an empty array for a selector that returns an array whilst fetching, how do we know if the API returned a zero-length array or hasn't fetched yet? A great example of this would be notifications: if we fetch notifications from the server on page load, we would get an array with a length of between `0`-`X` from the API. We should treat an unfetched selector value differently than a fetched but empty one. `null`/`undefined` lets us do that.

----

Personally I prefer `undefined`, because strictly speaking it represents an unfetched value better than `null`. Null is a set, but empty, value. Undefined means we don't know it yet. That can be an ambiguous value on generic JS objects, but as a return value of selectors it's quite clear, because functions are always called. There's no risk of calling an undefined function and getting `undefined` as a return value (JS will `TypeError` instead) like there is accessing an undefined property directly on a store's `state`.

So `undefined` can represent—consistently—an "unknown"/"unresolved" state when returned by selectors. We can save `null` for what it means.

This'll mean updating the existing `core/site` store to use `undefined` in a few places over `null`, but was something I planned to bring up in the future anyway, so good to discuss now 😄

**Comment by felixarntz** [comment]
@tofumatt 
> So TL;DR is: `@wordpress/data` manages selectors for us and we can call the selector many times but only have it use the resolver once. 👍

Perfect, and good to know, thanks!

> If the return value would be an object or array I would still expect `null/undefined` as the "unknown" value. If we, for instance, return an empty array for a selector that returns an array whilst fetching, how do we know if the API returned a zero-length array or hasn't fetched yet?

I see the reason why we would do that, I'm just wondering about the trade-offs in the code we need to write. Every component using these selectors would need to include logic to check for the `undefined` value, particularly in the case of objects/arrays where a simple `! value` wouldn't do it. It wouldn't be great if every component needed to support a loading state - I guess we would put these checks in the most top-level components and render a loader instead of "actual" child components then? Yet, what would the implementation in the child components look like then? Just if `typeof value == 'undefined'` return early and do nothing?

**Comment by tofumatt** [comment]
> Every component using these selectors would need to include logic to check for the undefined value, particularly in the case of objects/arrays where a simple `! value` wouldn't do it.

My experience is that this is exactly the right thing to do—the more explicit we are with checking types and not making the assumption that `false`-y equals "empty" is good. Though for things like arrays or objects, you _could_ check for `! value`, because an empty array is still truthy:
<img width="122" alt="Screenshot 2020-03-05 at 20 01 49" src="https://user-images.githubusercontent.com/90871/76020884-2c966c00-5f1c-11ea-9874-e1d5d29ef31e.png">

But I wouldn't; the explicit check for `undefined` in code will make components clearer to understand. My experience is that it's not much extra code to write and is very straightforward. The trade-off is a bit more code/boilerplate but drastically more control over component UI, insight into state, testability, and reduced bugs from typecasting.

> It wouldn't be great if every component needed to support a loading state

I think it makes for a more tailored and graceful UI—rather than a giant screen showing a big "loading" screen, individual components can handle loading states as they please. This makes them portable and easily composable. That said: components that we don't want to support a loading state can simply return `null` when there is no data.

> I guess we would put these checks in the most top-level components and render a loader instead of "actual" child components then? Yet, what would the implementation in the child components look like then? Just if typeof value == 'undefined' return early and do nothing?

We _can_ do that and even elect not to render the children at all if the data isn't loaded yet. "Top-level" components can request a bunch of data and show loading screens until the data is available if desired. But I don't think we should, because I think components that need the data would be much lower-down in the component tree, and those lower-in-tree components should be requesting their data directly with selectors.

This means components that need the data request it with a selector directly, rather than a parent component needing to request it only to render a loader if it isn't available. Components should use selectors as low-down in the tree as possible, so supporting loading states in components is the best call.

**Comment by felixarntz** [comment]
@tofumatt Thanks for these explanations, those all seem sound to me. Let's go with `undefined` as initial value for store properties that need to be fetched first. I'd say we should still explicitly "define" them within `INITIAL_STATE` though (as `undefined`), to make clear what properties there can be - even though it would also work without that explicit definition.

**Comment by felixarntz** [comment]
@tofumatt IB ready for re-review. Let's prioritize execution for this for the coming release too, shouldn't be too much anyway.

**Comment by tofumatt** [comment]
> I'd say we should still explicitly "define" them within INITIAL_STATE though (as undefined), to make clear what properties there can be - even though it would also work without that explicit definition.

Yes, absolutely! I should have mentioned that but I agree. Our `initialState` should always serve as at least an outline of our store's shape, so have the main keys initialised as `undefined` explicitly is 👍 from me.

IB looks good, thanks for the detailed convo on this one!

IB ✅

**Comment by felixarntz** [comment]
I split out the follow-up work into #1236. That part is more critical to be completed than the additional selectors. I'll move this issue here out of the release, let's just try to at least start work on it in Sprint 18.

**Comment by tofumatt** [comment]
If this is reviewed and merged today we can probably change the sprint to Sprint 19, but no biggie if not 😅

**Comment by cole10up** [comment]
**Tested**

Installed latest develop SK activated and connected all services.

Confirmed functionality, disconnected all services and reconnected.

No issues on my end. Passed QA ✅
