### ISSUE TITLE
Introduce notification functionality to core/user store

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1177]
## Feature Description

This is a follow-up to #1175. It's also related to #1174 and #1176, although these could even be worked on at the same time (except maybe because of annoying merge conflicts).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `core/user` store should have an additional selector `getNotifications`:
    * Contrary to the `getNotifications()` of `core/site` (see #1174), this should not issue an API request for now (as there are no server-side user notifications yet). This should only look at JS notifications.
    * See #1110 / #1170 for typical properties to expect on notifications (probably doesn't matter much for implementation of this, but fyi).
* The `core/user` store should have actions `addNotification( notification )` and `removeNotification( id )`:
    * Both of these should only work client-side for now (just like the selector here).
    * All `notification` objects must include `id`, so that they can be removed using that.

## Implementation Brief

* Add the actions, selectors, etc. from  `createNotificationsStore( 'core', 'user', 'notifications', { server: false } )` to the existing `core/user` datastore.
* Integrate the revised client/server-only notification store from the WIP PR at #1330

## QA Brief

* 

## Changelog entry

* Add notifications functionality to `core/user` store.

**Comment by tofumatt** [comment]
Had a think about this, and rather than adding similar selections/actions/state to the `core/user` store as what we expose in `createNotificationsStore`, I think the best option is to add two additional options to `createNotificationsStore`'s `options` argument: `client` and `server`. Both would be enabled by-default, but toggling either off would allow for modules to opt-out of either server or client notifications.

The code changes would be extremely minimal. We'd initialise `INITIAL_STATE` like so:

```js
const INITIAL_STATE = {
		serverNotifications: server ? undefined : null,
		// Initialize clientNotifications as undefined rather than an empty
		// object so we can know if a client notification was added and then
		// removed from state.
		clientNotifications: client ? undefined : null,
		isFetchingNotifications: false,
	};
```

and only enable the `getNotifications` resolver if `server` is `true`. That way, we can add a notifications store to `core/user` by using: `createNotificationsStore( 'core', 'user', 'notifications', { server: false } )` and not have to write any new selectors. We'll need a few new tests to cover the new options, but it'll be much more extensible and DRY. 😄

**Comment by felixarntz** [comment]
@tofumatt I really like this idea. I hadn't thought about a precise approach, but using `createNotificationsStore` was definitely a goal here, so 👍 

IB ✅

**Comment by aaemnnosttv** [comment]
## QA ✅ 

`core/user` store has notifications store added, with server-side notifications disabled. This is verifiable by seeing that the `getNotifications` selector has no resolver and no requests are triggered.

![image](https://user-images.githubusercontent.com/1621608/82546781-5e08f600-9b61-11ea-93df-a730ec7c666d.png)
