### ISSUE TITLE
1.3.0 Migration does not migrate tracking opt-in properly

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1186]
## Bug Description

In #913 we changed the anonymous user tracking preference from a global setting to a per-user setting. In the migration for v1.3, we limited the migration from setting to user preference to only sites that had a single authenticated user with Site Kit. For users who have yet to upgrade to 1.3+, this setting should be migrated for all users who had authenticated with Site Kit.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Users who upgrade from a pre 1.3 version of Site Kit should have the tracking opt-in migrated from the global setting

## Implementation Brief

Update `\Google\Site_Kit\Core\Util\Migration_1_3_0`
* Change `get_only_authenticated_user` to `get_authenticated_users` which returns a maximum of ~~`500`~~ `20` user IDs as a safe upper boundary
* Update `migrate_tracking_opt_in` to iterate over each user ID
* Remove the call to delete the global option

## QA Brief

1. Set up a site with Site Kit v1.2
1. Opt into tracking
1. Set up Site Kit with first user
1. Connect a second user with Site Kit
1. Upgrade Site Kit to 1.4
1. Ensure tracking is opted in for both users

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
Let's set the user query limit to 20, then IB ✅ 

Let's make sure we have test coverage to ensure that the user query returns only users with token set.

**Comment by cole10up** [comment]
**Testing scenario 1** opt in from settings

Installed SK 1.0.2
![image](https://user-images.githubusercontent.com/57115907/75604052-abf1ee80-5a89-11ea-8c5c-7a28b809621a.png)

Confirmed 1st user is opted into anonymous tracking
![image](https://user-images.githubusercontent.com/57115907/75604085-ebb8d600-5a89-11ea-8689-23e1ae8b81d4.png)

Confirmed 2nd user is opted into anonymous tracking
![image](https://user-images.githubusercontent.com/57115907/75604038-87961200-5a89-11ea-8012-73a3f8389ea1.png)

Upgraded to 1.0.4
![image](https://user-images.githubusercontent.com/57115907/75604139-9a5d1680-5a8a-11ea-8775-60b739688dd8.png)

Checked 1st user's opt in status
![image](https://user-images.githubusercontent.com/57115907/75604157-c4aed400-5a8a-11ea-83f7-97841c949e03.png)

This is not fixed in latest production 1.0.4 setting opt in status from settings.

**Scenario 2** Testing opt in from setup

Confirmed 1st user is opted into anonymous tracking
![image](https://user-images.githubusercontent.com/57115907/75604241-84038a80-5a8b-11ea-9e63-d0b73d0a05b9.png)

Confirmed 2nd user is opted into anonymous tracking
![image](https://user-images.githubusercontent.com/57115907/75604313-1ad04700-5a8c-11ea-800b-0137e859d148.png)

Checked opt in status after upgrade:
![image](https://user-images.githubusercontent.com/57115907/75604352-769ad000-5a8c-11ea-990e-c3e2b7f877d0.png)

**This does not pass QA**

**Comment by aaemnnosttv** [comment]
@cole10up I gave this another test and found it worked as expected for me. You also used different version numbers although I'm guessing this was a simple typo.

**The process I followed for testing:**
* Fresh site
* Install [Site Kit v1.2.0](https://downloads.wordpress.org/plugin/google-site-kit.1.2.0.zip)
* Opt into tracking
* Set up Site Kit with first user until you get to Site Kit dashboard (go through OAuth, approve, etc)
* Create a second admin user
    * Set up Site Kit with first user until you get to Site Kit dashboard with new user
* Create a third admin user
    * Don't set up Site Kit with this user
* Upgrade Site Kit to latest (1.4.0) via normal update (`wp-admin/update-core.php`)
* Ensure User 1 is opted in
* Ensure User 2 is opted in
* Ensure User 3 is NOT opted in

Can you test again using this procedure?

**Comment by cole10up** [comment]
**Retested**

Installed 1.2.0, added 3 users:
![image](https://user-images.githubusercontent.com/57115907/75709948-87a83480-5c78-11ea-802b-2b1fd9d26f41.png)

![image](https://user-images.githubusercontent.com/57115907/75709926-7bbc7280-5c78-11ea-930d-6e4edd75e323.png)


Setup SK with tracking opted in on User 1
![image](https://user-images.githubusercontent.com/57115907/75707998-cb993a80-5c74-11ea-8156-73ce83f8cfab.png)

Setup SK with tracking opted in on User 2
![image](https://user-images.githubusercontent.com/57115907/75708095-fe433300-5c74-11ea-8e7b-b7e0d2cd5d8b.png)

Setup SK with tracking **opted out** on User 3
![image](https://user-images.githubusercontent.com/57115907/75709900-6e9f8380-5c78-11ea-9489-3fea85fc75ee.png)

As user 2, navigated to plugins page to update
![image](https://user-images.githubusercontent.com/57115907/75708124-0e5b1280-5c75-11ea-9cc6-60fa7f2d8d57.png)

Clicked update now to 1.4.0
![image](https://user-images.githubusercontent.com/57115907/75708173-2d59a480-5c75-11ea-88be-c3f50cd7b3a3.png)

Navigated to Settings page:
![image](https://user-images.githubusercontent.com/57115907/75708204-3b0f2a00-5c75-11ea-80b9-65df4c176fe6.png)

**Looks good**

Logging in as User 1 and checking settings
![image](https://user-images.githubusercontent.com/57115907/75708304-6c87f580-5c75-11ea-8900-cefc2a26ad15.png)

Logged in as User 2 and checked settings
![image](https://user-images.githubusercontent.com/57115907/75709529-afe36380-5c77-11ea-8482-ee380936b937.png)

Logged in as User 3 and checked settings
![image](https://user-images.githubusercontent.com/57115907/75710031-a73f5d00-5c78-11ea-91fd-2a4cacd678e7.png)

Settings look to be retained for opt in and opt out.

I must have had something cached? I'll keep an eye on this going forward.

Passed QA ✅
