### ISSUE TITLE
Generate beta and production builds using GH Actions/CI

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#1196]
## Feature Description

Now that #1172 is available to build us ZIP files on the plugin based on what's in the repo, we should be using it to generate both beta/testing builds (eg from `develop`) and also production builds (from `master` and/or from tagged releases). This alleviates the need for someone (usually @felixarntz) to manually create testing ZIP files and reduces the chance that a locally-built ZIP could have a problem.

#1172 already generates plugin ZIPs from `develop`, but if we included tagged releases (or just `master`) we could always use CI builds. 🂡

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* ~~Create ZIP files from the `master` branch using a GitHub Action by adding `master` to the branches in `.github/workflows/build-pr.yml`~~  
Done in #1201 
* Create ZIP files from a tag when a new release/tag is added
* Rename `build-pr` action to `build-zip` as it'll cover both PRs and releases

## Implementation Brief

* Rename workflow and job of same name from `build-pr` to `build-zips` (including references)
* Add `tags: [ '**' ]` to `on.push` to trigger workflow for all tag pushes  
This will push zip files to `{wiki}/refs/tags/{tag}`  
See https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

## QA Brief

The following release is made available at:
* http://github.com/google/site-kit-wp/wiki/refs/tags/n.e.x.t/google-site-kit.zip
* http://github.com/google/site-kit-wp/wiki/refs/tags/n.e.x.t/google-site-kit-dev.zip
> Where `n.e.x.t` is the tag name

## Changelog entry

*

**Comment by felixarntz** [comment]
@tofumatt That sounds great! I agree on renaming the action, updated the ACs.

One question: So would we then build a ZIP on any push to `master`? With the current storing mechanism using the Wiki (which we should keep for this too), where would such a file end up? This applies to `develop` as well, which is already in place now if I'm not mistaken.

What we'd want to have is files for the following (for each entry, both `dev` and `production` build):
* latest `develop`
* each latest PR
* latest `master`
* each tag generated

The latter two should be made available through this issue.

**Comment by aaemnnosttv** [comment]
Builds for pushes to `master` are now included as of #849.

+1 for adding builds for each tag 👍 

> With the current storing mechanism using the Wiki (which we should keep for this too), where would such a file end up? This applies to develop as well, which is already in place now if I'm not mistaken.

* https://github.com/google/site-kit-wp/wiki/refs/heads/develop/google-site-kit.zip
* https://github.com/google/site-kit-wp/wiki/refs/heads/develop/google-site-kit-dev.zip
And as soon as this is merged to master, we'll also have:
* https://github.com/google/site-kit-wp/wiki/refs/heads/master/google-site-kit.zip
* https://github.com/google/site-kit-wp/wiki/refs/heads/master/google-site-kit-dev.zip

Keep in mind that both zips are available for download from the artifacts of the Actions run as well.
E.g.
https://github.com/google/site-kit-wp/actions/runs/49047476
![image](https://user-images.githubusercontent.com/1621608/75870651-f4a40180-5e13-11ea-8087-f266a17ccdf3.png)

We can't use these artifacts for "dist" URLs (i.e. instead of wiki) however since they only last for 90 days, and the URLs do not follow the same kind of format which only need a branch or PR #.

**Comment by felixarntz** [comment]
@aaemnnosttv @tofumatt 
Actually I'm wondering about the need for this change now. `master` is important, but having builds for the tags would be more like "nice to have". Having a build for the latest `master` is already sufficient to take away the work from me to build the release ZIP locally. We are currently only creating tags right before deploying to .org basically, so that wouldn't really affect the release ZIP process.

But generally, IB ✅

**Comment by aaemnnosttv** [comment]
You could say builds for `master` would be like RCs if it hadn't been tagged yet. Builds for tags should be uploaded to the GitHub release IMO - I don't think there's much value in adding those to the wiki.

**Comment by aaemnnosttv** [comment]
@felixarntz I updated the IB here to outline a new job to upload the built artifact zips to the GitHub release on tag rather than the wiki - which isn't necessary I think.

**Comment by aaemnnosttv** [comment]
@ryanwelcher per our convo with @felixarntz yesterday, let's upload these zips to the wiki as originally planned and not mess with GitHub releases for now. I'll update the AC/IB.

**Comment by aaemnnosttv** [comment]
## QA ✅ 

Tested this on a personal fork to make sure that the same actions are triggered on new tags.

Moving to Approval.
