### ISSUE TITLE
UI option to disable admin bar integration

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1204]
## Feature Description

Suggested from a [support topic](https://wordpress.org/support/topic/new-admin-bar-menu-item/), having a UI option to disable the below admin bar integration could be helpful for users:

<img width="1156" alt="Site Kit admin bar integration" src="https://user-images.githubusercontent.com/8108643/75813496-ea670200-5d44-11ea-82f0-90786fcb4406.png">

Currently, the filter below can disable it:

`add_filter( 'googlesitekit_show_admin_bar_menu', '__return_false', 1000 );
`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@ernee Since this is a very specific request and our philosophy is to keep our UI simple and focused, we've decided to not add a control for this to the plugin. However, we understand the thinking behind this request. I've prepared a one-line plugin (basically having the line you added in the description) that we can share with people who would like to disable the admin bar integration: https://drive.google.com/file/d/1DllaeDuc6NIkmX5y5LU7LX4gW_aYbAlP/view?usp=sharing

cc @marrrmarrr
