### ISSUE TITLE
New data handler for Analytics `provision` requests

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#1212]
## Feature Description

New endpoint for Analytics `create-account-ticket` POST:
 * Accepts all the fields from the "New Account" screen
 * Queries the provisioning API to start the account creation process.
 * Redirects the user to the TOS on success

### Details

* The endpoint uses the client to call the [createAccountTicket](https://developers.google.com/analytics/devguides/config/provisioning/v3/reference/provisioning/createAccountTicket) method via the proxy service (TBD, likely: https://sitekit.withgoogle.com/provisioning/analytics), passing all form data plus a `redirectUri` for post TOS handling. (The proxy issues the actual provisioning request and handles the redirect substitution after the TOS is completed).
* The service returns an error or an account ticket (with an id) on success
* The plugin stores the `account_ticket_id` in the user's meta, for a later check
* The handler returns the id and the plugin redirects the user to accept the Google Analytics [Terms of Service] `https://analytics.google.com/analytics/web/?provisioningSignup=false#management/TermsOfService/?api.accountTicketId={account_ticket_id}` using the account ticket id.

**Technical considerations**

Once the user completes the TOS form, they are redirected to the site via the service/proxy to the `redirectUri` we pass in the provision request, eg `"{siteURL}?gatoscallback=1"`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a `POST:create-account-ticket` datapoint in the `Analytics` module which receives and validates `accountName`, `propertyName`, `profileName`, and `timezone` parameters (see #1211). 
* The website URL for the property should be set based on the reference site URL.
* The datapoint should issue a POST request to [GA's `createAccountTicket` endpoint](https://developers.google.com/analytics/devguides/config/provisioning/v3/reference/provisioning/createAccountTicket) via `https://sitekit.withgoogle.com/analytics/provisioning/createAccountTicket`, which requires `site_id`, `site_secret`, and the same data provided to the original GA endpoint within an `account_ticket_resource` property. 
* The `redirect_uri` within `account_ticket_resource` should point to the site URL followed by `?gatoscallback=1` (similar like the OAuth redirect URI is created) --> it must exactly match the one from #1254. 
* Before returning, store  the account ticket ID from the response.

## Implementation Brief

*  In `includes/modules/Analytics.php::create_data_request` add a new case for `POST:create-account-ticket`, this handler should:
- Validate `accountName`, `propertyName`, `profileName`, and `timezone` parameters (details: see #1211) 
- Set up a custom Analytics client with the base url set to the proxy URL in the `setup_services` method, add an entry:
`'analyticsprovisioning' => new Google_Service_Analytics( $client, $google_proxy->url() )`
- Add a new `AccountTicket` class that extends `Google_Service_Analytics_AccountTicket` and adds two public parameters: `site_id` and `site_secret` (plus the related setter/getter methods).
- Add a new class `Provisioning` in `includes/Modules/Analytics` (namespace: `Google\Site_Kit\Modules\Analytics`) It extends `\Google\Site_Kit_Dependencies\Google_Service_Resource`. It will:
  - Have a single public method `createAccountTicket` that takes our `AccountTicket` object.
- Note: _Site id and secret are returned from `Credentials::get()` as `oauth2_client_id` and `oauth2_client_secret`._
* The required setup information (account, property and view names plus redirect URI) are passed as an `AccountTicket` object, which is what the proxy expects.
* The `redirectUri ` within `AccountTicket` should point to the site URL - no trailing slash - followed by `?gatoscallback=1` (it must exactly match the one from #1254). Otherwise provisioning should fail.
* Add a new method `get_provisioning_redirect_uri` in `Analytics.php` to construct this URL.
* The response (if successful) will include a `Google_Service_Analytics_AccountTicket` object including an `id` field for the account ticket resource. Store the `id`:
* Add a new key for ANALYTICS_PROVISIONING_ACCOUNT_TICKET_ID
* Store `id` in a transient: `set_transient( ANALYTICS_PROVISIONING_ACCOUNT_TICKET_ID . '::' . get_current_user_id(), $account_ticket_id, 15 * MINUTE_IN_SECONDS);` 
* Return the account ticket id (or error code) to the client to handle the redirect.

## QA Brief

* 

## Changelog entry

* Add `create-account-ticket` datapoint for `Analytics` module that creates a new Analytics account ticket using the Provisioning API.

**Comment by felixarntz** [comment]
@adamsilverstein IB mostly sounds good, a few issues however:
* The datapoint should be `POST:create-account-ticket`.
* We cannot use the PHP client's `createAccountTicket` method as is. We can (and should) use the PHP client's objects for all the request body parts, but we need to construct this request ourself, since
    * it's against our proxy, not against the Google API
    * it's using a different API signature (the IB is completely missing e.g. the `site_id` and `site_secret` part)

A nice solution would be to implement our own version of `Google_Service_Analytics_Resource_Provisioning`, maybe in `includes/Modules/Analytics`, accept the additional parameters in `createAccountTicket` and modify the URL to point to our route.

**Comment by adamsilverstein** [comment]
Right! Thanks for the feedback, I'll update the IB.

**Comment by adamsilverstein** [comment]
@felixarntz Updated IB:
* Added a new class to handle the `createAccountTicket` call, please review my proposed class naming.
* Now takes site id/secret and POSTs to the site kit service url.
* Cleaned up the language a bit.

**Comment by felixarntz** [comment]
IB ✅ 

Let's see whether we can extend the `Google_Service_Analytics_Resource_Provisioning` and inject our own variant into the main `Google_Service_Analytics` instance after creating it, as discussed yesterday.

**Comment by adamsilverstein** [comment]
> Let's see whether we can extend the Google_Service_Analytics_Resource_Provisioning and inject our own variant into the main Google_Service_Analytics instance after creating it, as discussed yesterday.

@felixarntz I have a POC with this working and have adjusted the IB accordingly.

**Comment by aaemnnosttv** [comment]
## QA ❌ 

The account ticket ID constant is defined in the namespace scope rather than as a class constant as I would expect.

https://github.com/google/site-kit-wp/blob/edf04178a755e8bd53d7462f82859ab1714db2ac/includes/Modules/Analytics.php#L55-L60

Perhaps this was intended but the usage indicates that was in intention as well.

https://github.com/google/site-kit-wp/blob/edf04178a755e8bd53d7462f82859ab1714db2ac/includes/Modules/Analytics.php#L1107

Here `$self` is an undefined variable, but even if it were `self::` it would still fail because the constant is not defined within the class.

**Comment by adamsilverstein** [comment]
> The account ticket ID constant is defined in the namespace scope rather than as a class constant as I would expect.

Good catch! Moving to the class, that is a mistake.

**Comment by adamsilverstein** [comment]
@aaemnnosttv Moved that (and addressed your previous feedback) in https://github.com/google/site-kit-wp/pull/1365.

**Comment by tofumatt** [comment]
Whoops, saw @aaemnnosttv previously QA'd this one and likely has more context, so unassigning myself and assigning him 😅

**Comment by aaemnnosttv** [comment]
## QA ⚠️ 

One thing concerns me here that I don't has been addressed yet or not, but how does work for users who are not using the proxy?

If this feature is limited to those using the proxy we should make sure it is only shown/available accordingly. 

However, is it not possible that someone could have access to this new invite-only API with their own credentials?

---

Nothing technically wrong that I can see here in regards to the AC, but a few details the I would raise in code review:

* The `POST:create-account-ticket` data handler should be moved in the switch to comply with the current alpha-sort in place there. See https://github.com/google/site-kit-wp/issues/949
* Regarding the addition to `setup_services`, I think it would be a bit cleaner and more consistent to move the `$analytics_provisioning_service` definition outside of that method.  
https://github.com/google/site-kit-wp/blob/ebc230b9f0d795d3a641bdda1cb2c74cec9af9de/includes/Modules/Analytics.php#L1327-L1351

Ideally I think this would work the same as the others there where it might look like this:
```php
return array(
	'analytics'             => new Google_Service_Analytics( $client ),
	'analyticsreporting'    => new Google_Service_AnalyticsReporting( $client ),
	'analyticsprovisioning' => new Google_Proxy_Service_AnalyticsProvisioning( $client, $google_proxy->url() ),
);
```
and the rest of the definition would exist in the constructor of the `Google_Proxy_Service_AnalyticsProvisioning` class which would extend `Google_Service_Analytics`.

Not sure if this warrants a new dedicated issue or not since it's in a feature branch anyways. @felixarntz ?
cc: @adamsilverstein

**Comment by adamsilverstein** [comment]
@aaemnnosttv Thanks for the feedback, a few answers inline:

> One thing concerns me here that I don't has been addressed yet or not, but how does work for users who are not using the proxy?

Using this feature currently requires the proxy.

> However, is it not possible that someone could have access to this new invite-only API with their own credentials?

very unlikely - the GCP App the user is using must be whitelisted and this is a manual process. This feature is intended for large scale integrations like site kit, not for individual users.

> The POST:create-account-ticket data handler should be moved in the switch to comply with the current alpha-sort in place there

Will do, thanks for pointing this out.

> Regarding the addition to setup_services, I think it would be a bit cleaner and more consistent to move the $analytics_provisioning_service definition outside of that method.

I will give that a try.

**Comment by felixarntz** [comment]
We'll mainly account for that this requires the proxy by showing the legacy account creation component as part of #1211 if the site is not using the proxy. Let's add a check for `OAuth_Client::using_proxy()` here in `POST:create-account-ticket` and if not return an error, just to set expectations right if something was calling this endpoint in such a setup.

@adamsilverstein Can you address the above and the other minor changes @aaemnnosttv pointed out in a follow-up PR against this?

**Comment by adamsilverstein** [comment]
> and the rest of the definition would exist in the constructor of the Google_Proxy_Service_AnalyticsProvisioning class which would extend Google_Service_Analytics.

Added in https://github.com/google/site-kit-wp/pull/1512/commits/cf0ef59dacc8271b53c35b815cded3fd34d3c954

**Comment by adamsilverstein** [comment]
> Let's add a check for OAuth_Client::using_proxy() here in POST:create-account-ticket and if not return an error

Added in https://github.com/google/site-kit-wp/pull/1512/commits/966579c0beb039460813c7a5b62c2da30a29da46

**Comment by adamsilverstein** [comment]
> The POST:create-account-ticket data handler should be moved in the switch to comply with the current alpha-sort in place there. See #949

Moved in https://github.com/google/site-kit-wp/pull/1512/commits/e18de5591f51cf477a953d47e0319af33f7f88c4

**Comment by ShahAaron** [comment]
Pulled develop
Ran JS and PHP Unit tests - passed
Ran e2e tests - passed
Ran Visual Regression - passed

QA ✅
