### ISSUE TITLE
Webpack bundles not extracting common dependencies properly

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1222]
## Bug Description

The JS bundles generated for each entrypoint in Webpack are unnecessarily bundling many common vendor dependencies in the entrypoint bundle rather than extracting to a vendor chunk.

Report as of 302118a1c61f8c0353e7765b613882010b1b014f using [`webpack-bundle-analyzer`](https://github.com/webpack-contrib/webpack-bundle-analyzer):

[report.html.txt](https://github.com/google/site-kit-wp/files/4293858/report.html.txt)  
> Rename extension to `.html` to view

* Modules such as `lodash` are being included in every bundle.
* React, React DOM, material components are included in bundles that don't use them such as `googlesitekit-api` and `googlesitekit-data`
* Lodash appears to be included more than once in some bundles

## Screenshots

**Report overview**
![image](https://user-images.githubusercontent.com/1621608/75999629-2fd52c00-5f0b-11ea-8b3a-82049abf522c.png)
**API closeup**
![image](https://user-images.githubusercontent.com/1621608/76000111-e3d6b700-5f0b-11ea-9ea4-e820cdf8433f.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Don't include/bundle React and React DOM in entrypoints like `googlesitekit-api` or `googlesitekit-data`. No new JSR entrypoints should contain React.
* Don't include `lodash` multiple times in bundles.
* Consolidate `node_modules` files into a common chunk, if easily done.

## Implementation Brief

* Use the `splitChunks` plugin without a runtime chunk and manually enqueue the vendor bundle
* Merge #1344

## QA Brief

* Run `npx webpack -p --json > stats.json`
* Edit the resulting JSON file to remove the lines at the top starting with `webpackbar`
* Run `npx webpack-bundle-analyzer -m static stats.json`
* In the bundle analyzer view/report, inspect the various entrypoints/bundles to ensure the AC has been met

## Changelog entry

* Optimize JavaScript dependency loading, decreasing the chance of conflicts and reducing the plugin size.

**Comment by tofumatt** [comment]
I spent a lot of time checking this out and it's not as straightforward as [using `splitChunks` in webpack](https://webpack.js.org/plugins/split-chunks-plugin/). Because of how we manage assets and separate each app into its own entrypoint, adding webpack's chunk management causes the page to fail to load.

I've tried several—too many—`splitChunks` options, included both a single `runTimeChunk` and embedded ones, etc., and have none been able to get Site Kit to load while also getting webpack bundles to share code.

I'll revisit this later, but I'm going to leave it alone for now as it seems like an issue with our approach to dependency management and may require heavier refactoring and more time than we have right now to dedicate to it.

**Comment by tofumatt** [comment]
It's likely that this issue is going to block us from using React hooks and is causing issues with multiple copies of libraries being run on the page needlessly, so I'm going to investigate this further as it seems to be blocking #1101, or at least requiring some not-so-nice hacks to get things working.

**Comment by tofumatt** [comment]
Note for Eng QA: certain duplicate modules will likely still exist from the output, likely because specific versions are being required by some of our dependencies and they aren't matching. We aren't doing anything to combine those modules now—I'd say we should do that as a separate issue and with caution, because changing a library's dependencies from underneath it is dangerous 😄

But for now you should see things like `react-dom` only output in one bundle—the same goes for any  "top-level" dependencies. There might still be multiple `lodash` deps in there, but that's okay and best saved for another issue.

**Comment by ryanwelcher** [comment]
Everything looks good to me. AC criteria pass with the exception of a few instances of `lodash` as mentioned in @tofumatt's note above. 
Approved ✅
