### ISSUE TITLE
Enhance anonymous usage tracking label

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1238]
## Feature Description

The wording used for the anonymous usage tracking checkbox label is a bit off. It's also missing a period at the end.

Currently

> Help us improve the Site Kit plugin by allowing tracking of anonymous usage stats. All data are treated in accordance with [Google Privacy Policy](#)

Suggested
* Help us improve Site Kit by sharing anonymous usage data. All collected data is treated in accordance with the [Google Privacy Policy](#).

![image](https://user-images.githubusercontent.com/1621608/76291999-fa3b9480-62b6-11ea-95f9-017a7f6a4a98.png)

Perhaps split on two lines?
![image](https://user-images.githubusercontent.com/1621608/76291782-771a3e80-62b6-11ea-9ce4-d805f4799fbf.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Update Tracking notification text to:
_Help us improve Site Kit by sharing anonymous usage data._ 
_All collected data are treated in accordance with the Google Privacy Policy._
* Break out the second sentence onto a new line.

## Implementation Brief

Reset Site Kit to see the above screen

Using `/assets/js/components/OptIn.js`
* update text as per AC
* take current `createInterpolateElement` and place that inside a `<span>`
* split out first sentence into another `<span>`
* put a line-break `<br/>` in between these two spans

Using `/assets/sass/components/global/_googlesitekit-opt-in.scss`
* For the rule `.googlesitekit-opt-in .mdc-form-field label` increase the `line-height` a bit to match the screenshots above

## QA Brief

* Reset Site Kit 
* Observe that text has changed as per AC

## Changelog entry

* Update the wording used for the anonymous usage tracking checkbox label

**Comment by tofumatt** [comment]
The contents referenced are rendered inside a `<label>` tag, so we shouldn't be adding `<p>` elements inside it—labels are inline elements and shouldn't contain block-levels inside them.

<img width="751" alt="Screenshot 2021-04-27 at 13 39 07" src="https://user-images.githubusercontent.com/90871/116242579-f3dbd680-a75d-11eb-8880-92d5ae66112c.png">

It'd be best to use something like a line break or two `<span>` tags to render the lines as "visually block-level" rather than putting `<p>` tags inside a `<label>`. Arguably they aren't separate paragraphs semantically anyway 🙂 

Let's tweak the IB to not use blocks inside inline elements.

**Comment by danielgent** [comment]
I've just noticed that the Admin settings panel has the same text on it.  I'll update that as part of this ticket :+1: 

![same text](https://user-images.githubusercontent.com/8496063/119550805-23035900-bd99-11eb-817a-c733615de330.png)

**Comment by Hazlitte** [comment]
**QA ✅**
