### ISSUE TITLE
AMP validation error for script with _gaUserPrefs

### ISSUE THREAD

**Issue by westonruter** [google/site-kit-wp#1251]
## Bug Description

I just updated to Site Kit 1.5.0 and I got an AMP validation error on the frontend for a `script` containing:

```js
window["_gaUserPrefs"] = { ioo : function() { return true; } }
```

## Steps to reproduce

1. Activate Transitional or Standard mode in the AMP plugin.
2. Access an AMP page.
3. Notice an AMP validation error reported in the admin bar.

## Screenshots

![image](https://user-images.githubusercontent.com/134745/76590062-5960fb00-64a9-11ea-9865-e78d9071436f.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GA opt out script must not be output in AMP context

## Implementation Brief

* Add guard in `Analytics::print_tracking_opt_out()` to return early if in AMP context
* Restore guard in `Analytics::print_amp_gtag()` if `is_tracking_disabled()`  
https://github.com/google/site-kit-wp/pull/1234/files#diff-82cb88ae0faf21fb5e86f13d2458e589L377-L380
* Fix JS render target hiding in JS-enabled AMP contexts by adjusting the selector used
* Merge #1252 

## QA Brief

* 

## Changelog entry

* Ensure tracking opt-out mechanism works consistently between both Analytics and Tag Manager in AMP, and fix regression with Site Kit admin bar menu no longer expanding on AMP pages.

**Comment by westonruter** [comment]
The Site Kit admin menu item also doesn't do anything when I hover over it.

**Comment by felixarntz** [comment]
@westonruter @aaemnnosttv I'm currently trying to figure out what the proper way of opting out of GA tracking would be in AMP. While the current implementation brief (only output `amp-analytics` tag accordingly) would resolve the violation, it would still result in us not addressing what this change was actually supposed to address (#944).

The current PR looks good in case there's nothing else we can do here for now, but I'm currently talking to someone who has more context on the functionality, so I'd like to wait until next week before moving forward with the fix.

**Comment by felixarntz** [comment]
@westonruter @aaemnnosttv I actually just discovered something:
* https://github.com/ampproject/amphtml/pull/21362/files#diff-cb0347b1135d05dae7b0c034bca78900R412 introduces a general way to opt out of `amp-analytics` tracking based on a specific element being in the page.
* The default configuration for `type="googleanalytics"` sets this to `__gaOptOutExtension` (see https://github.com/ampproject/amphtml/blob/b0aff1b9a59d3ca8f10a6ebe4d6eaeda8c826e61/extensions/amp-analytics/0.1/vendors/googleanalytics.json#L65).
* We use `type="gtag"` though which doesn't appear to set a value for it out of the box (see https://github.com/ampproject/amphtml/blob/b0aff1b9a59d3ca8f10a6ebe4d6eaeda8c826e61/extensions/amp-analytics/0.1/vendors/gtag.json).

I suggest to try the following:
* Continue placing our `amp-analytics` unconditionally.
* Add an `"optoutElementId": "__gaOptOutExtension"` (let's stick to that convention, assuming that Tag Manager would also support that) to its configuration (via our PHP associative array).
* In `Analytics::print_tracking_opt_out()`, if AMP, print a `<meta id="__gaOptOutExtension">` (is this technically valid HTML, a meta with only an id?) instead of the `script` tag.

Let's change the PR to that and do some testing whether it works (we should be able to do that with the GA live tracking capabilities).

**Comment by aaemnnosttv** [comment]
> if AMP, print a `<meta id="__gaOptOutExtension">` (is this technically valid HTML, a meta with only an id?) instead of the `script` tag.

It is not, apparently.

![image](https://user-images.githubusercontent.com/1621608/76754327-9d464f80-678a-11ea-9ded-413123228746.png)

I opted instead to use an empty `script[type="text/plain"]` which is [valid HTML](https://user-images.githubusercontent.com/1621608/76754628-2198d280-678b-11ea-9cb9-4ec6f6c85f6f.png) and [valid in AMP](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/?format=websites#html-tags) 👍

**Comment by aaemnnosttv** [comment]
Unfortunately, the AMP plugin currently reports 2/3 valid script types as invalid and removes them 😞 
It's now using `application/ld+json` which is the only one it doesn't complain about.

Opened a new issue for this here https://github.com/ampproject/amp-wp/issues/4392

**Comment by westonruter** [comment]
These script types are allowed only when they are used on the context of other AMP components. You can't add an application/json script anywhere. It had to be inside of an amp-analytics component, for example.

**Comment by felixarntz** [comment]
I've QAd this via reviewing and testing #1252. ✅
