### ISSUE TITLE
Move module features list to setup_info

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1263]
## Feature Description

Currently the base `Module::prepare_info_for_js` method is overridden by all modules (with the exception of AdSense), just to add the `provides` key which is a list of translatable feature descriptions.

Each module already needs to implement the `setup_info` method, which populates `Module->info`, the basis of the data passed to JS. We should move the list of provided features to this setup method and pass it similar to other data instead of via `prepare_info_for_js`.

This would allow us to remove the method from the following module classes:
* Analytics
* Optimize
* PageSpeed Insights
* Tag Manager

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
This piece of information was intentionally left out from the base info because it should be phased out in the future in PHP. It's only used in JavaScript, and we have module-specific JS code to deal with that. Especially since this information is purely UX-focused, it should be moved to JS in the long term, which we'll get to - then we can remove it from PHP completely.

Closing this one for now.
