### ISSUE TITLE
Introduce standalone mode for Site Kit admin screens

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1281]
## Feature Description

There should be a technical way to make any Site Kit admin screen display in a "stand-alone" mode, where all the WordPress UI (admin bar, admin menu, admin footer text) is not displayed. This should be controllable by a query parameter that can be included (e.g. `googlesitekit-standalone=1`).

It would be perfect if we could accomplish that through actual PHP changes where we wouldn't run the relevant WordPress code even. Since WP Admin is quite inflexible in many ways though, this may require too much of working around core limitations, so if that's the case, using CSS to hide things would be an acceptable trade-off solution (I assume we will need some CSS fixes either way). Let's do some research and nail down the approach to use in the implementation brief.

Most Site Kit screens should already be technically standalone, as in decoupled from any WordPress UI, so I'd assume not rendering/hiding WordPress UI based on the parameter is all that this entails.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If a query parameter `googlesitekit-standalone=1` is present, the following UI should not be rendered/visible:
    * WordPress admin bar
    * WordPress admin menu
    * WordPress admin footer text
* As such, the Site Kit screen part of the UI should cover the whole screen, e.g. with the white bar at the top expanding towards the top, left, and right edge.
* This should either be implemented by highjacking WordPress UI in PHP or including some CSS that will hide these areas. The implementation should be generic to work for any Site Kit screen.

## Implementation Brief

* Hide the admin top menu bar and menu sidebar with CSS. Rather than hijacking the output content via PHP, we can easily hide these elements with CSS.
* Merge #1366, which already hides the content with CSS.

## QA Brief

* 

## Changelog entry

* Introduce standalone UI mode for plugin admin screens.

**Comment by tofumatt** [comment]
WordPress already offers users the ability to all-but-hide its chrome/UI using the "collapse menu" option on desktop screens:

![Screen Recording 2020-04-13 at 16 46 56](https://user-images.githubusercontent.com/90871/79135592-8275f380-7da7-11ea-9041-c53de45363b9.gif)

Actually removing those links entirely—either with CSS or some sort of PHP hook—presents three immediate problems to me:

### Fragility
Selecting those items with CSS might break in the future or require some odd CSS hacks. Not the end of the world though.

### Usability.
If the user is on a page with all of the WordPress chrome removed, they loose the site info for the site they're using, their current WordPress user (both site name and user name are in the top-most admin bar). They also lose all navigation links to get to different parts of their site quickly, forcing us to implement our own, simplistic, "Return to WordPress" link in the UI, which is both less flexible and sort of awkward (Site Kit is, after all, a _part_ of WordPress).

### Security
Removing all of the WordPress chrome from Site Kit's pages seems like an invite to introduce an easy-to-implement phishing UI for Site Kit, because there will be an official UI that removes all WordPress Chrome—leading to sites re-implementing our UI to phish user data.

-----

I don't think we should implement this issue 😄

**Comment by felixarntz** [comment]
@tofumatt This feature is not intended to be used directly in Site Kit, we would never hide WordPress UI like that anywhere. There are however integrations with other platforms for which we'll need this to provide a solid user flow.

**Comment by tofumatt** [comment]
Noted! In that case; I've updated the IB and mentioned the PR that already handles this issue. 👍

**Comment by felixarntz** [comment]
IB ✅

**Comment by ShahAaron** [comment]
**Tested**

Installed latest develop, navigated to SK screen. Add query parameter (`googlesitekit-standalone=1`) to the url:

Pages tested:

- Dashboard
- Search Console
- Analytics
- Settings
- Developer Settings

All passed:

- WordPress admin bar - invisible
- WordPress admin menu - invisible
- WordPress admin footer text - invisible
- SK screen covers full page

Passed QA ✅
