### ISSUE TITLE
Compatibility with headless WordPress environments

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1347]
A [user in the support forums ](https://wordpress.org/support/topic/problems-with-headless-wordpress/) encounters the following error when attempting to verify their site in a headless WordPress environment:

> The necessary verification token could not be found on your site.

The user tried using both the plugin's setup process and with the [staging environment/ Dev settings plugin ](https://sitekit.withgoogle.com/documentation/using-site-kit-on-a-staging-environment/) to get their data from the main site (_https://example.com_) to the headless WordPress instance (_https://cms.example.com_). The main website is already verified in Search Console via DNS, but their attempt still results in the error. 

The user additionally noticed the following when using the Dev settings plugin:

- Initially received OAuth credentials, proceeded through setup, but the callback goes to _https://example.com_ instead of _https://cms.example.com_ .
- Following attempts lead to the above verification token error when trying to verify the site.  The user noticed Site Kit's xhr uses the correct _https://example.com_, but the response (status code 500) is a completely different URL _http://www.example.com_ (protocol and subdomain are incorrect). 

Other details:

- Both headless WordPress and the main site are hosted on AWS. WordPress is behind a firewall. 
- A custom WordPress plugin exports article data (not using the wp-json API) to a custom application in the cloud that renders the main website (like a static site generator). 
- User wants to know if there is an alternate way to proceed with verification. 
- We additionally inquired about how the service connections work in this setup. 

See topic for more details: https://wordpress.org/support/topic/problems-with-headless-wordpress/

**Comment by aaemnnosttv** [comment]
The plugin does not fully support a headless setup at the moment.

The site verification step in particular that Site Kit helps facilitate, will not work in a headless setup be cause it relies on WordPress serving the request so it can render the necessary HTML file or meta tag.

As for Site Verification specifically, this can be done manually, without using Site Kit at all (e.g. DNS, or by manually deploying the necessary file/meta tag to the headless app). To verify your user manually, the user can use https://www.google.com/webmasters/verification/home and click the button to "Add a Property".

Since the user is using their own GCP credentials, it may allow them to complete the set up.

Generally speaking though, the plugin does not even support using different domains for wp-admin and the frontend (headless or not) but this may not apply to this user in particular since they're using their own credentials.

**Comment by felixarntz** [comment]
@ernee Indeed, headless setups are not supported, specifically because such setups defeat one of the purposes of Site Kit, which is to make Google service integration, tag management etc. seamless. But on a headless site, placing something in the frontend like we do is impossible.

The user can still use Site Kit still for monitoring, and would have to manually place all the tags they need (e.g. Analytics, AdSense, etc.). In order to do so, they need to use the Dev Settings plugin like they already do. The missing part is that they need to manually verify the WordPress instance site (_https://cms.example.com_) too in order for the verification step to succeed.

Support for this kind of setup would become slightly better once the authentication service supports development sites properly, but fully supporting headless WordPress isn't something currently prioritized.

**Comment by rodrigo-arias** [comment]
@felixarntz It’s a shame that, with the growing number of headless sites, there isn’t a way to set up this great plugin. Would it be possible to configure the plugin to allow users to view metrics, even if an alert indicates that script integration needs to be handled manually? Even with limited support, using the plugin for metrics could still be very valuable in headless environments.
