### ISSUE TITLE
Provide clarity on the single URL page

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#138]
## Feature Description

Details on the single URL page are a bit unclear. Add in additional labels as outlined in screen shot below to provided needed clarity.

<img width="516" alt="826331f9e2c7b3c2b448bf75ae88c8dc" src="https://user-images.githubusercontent.com/28811945/60741287-731b6d00-9f2e-11e9-9798-f5e2d1c0abc4.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All sections should be named clearly to mark they're for the specific page
* Whenever there's not enough data to display, show clear informational message (instead of "gathering data") 
* Where possible, source links to external products should link to pre-filtered view. 
* Session duration metric should be replaced by Bounce rate 
* Date range selectors should be added for all sections except the topmost section which has just the page title and URL. 

## Implementation Brief

* Update copy in titles to reflect the data refers to a single page rather than the site in `assets/js/components/dashboard-details/dashboard-details-app.js`, `assets/js/modules/search-console/dashboard-details/dashboard-details-widget-keyword-table.js` and `assets/js/modules/analytics/dashboard-details/dashboard-details-widget-top-acquisition-sources.js`.
* New ticket to display clear informational messages instead of "gathering data". #314 
* Update external source link hrefs to direct to filtered view when possible.
* Change module displaying data for average session duration to update to bounce rate - pull data from `overview.averageBounceRate` in place of `overview.averageSessionDuration` values in `assets/js/modules/analytics/dashboard/dashboard-widget-top-level.js`. Be sure to update the arrow to be green when small rather than the default. (Since bounce rate goal is low and a high bounce rate is considered bad/red)
* Add data range selectors `<DateRangeSelector/>` for each section.

## Changelog entry

*

**Comment by circlecube** [comment]
Here is some aggregated comments/notes from the old related ticket (18596445)

> - In the "traffic sources" section, we show the columns, even when data is still gathering
> - "Top search queries *for your site*" should be "top search queries *for this page*"
> - The search queries section is empty, but doesn't explain why (data gathering)
> - In the current version, we've got "average session duration" instead of "page views" in the top section -- that would need to have the correct measuring units.
> - Let's add a name for that section as well (search funnel)
> - In "search queries" section, we can just say "for this page" instead of including the full name of the page (some pages have really long titles)
> - If the "search queries" section is empty, we should show "data not yet available" or similar message.

**Comment by circlecube** [comment]
@marrrmarrr We have some updates on this and are ready for feedback since a lot has changed in the meantime. Here is a screenshot of the updates from the above comp (excluding adding the bounce rate):
![googlekitlocal 10uplabs com_wp-admin_admin php_page=googlesitekit-dashboard permaLink=https%3A%2F%2Fnomaderwhere com%2F pageTitle=Home](https://user-images.githubusercontent.com/698049/60826226-65a6f280-a17b-11e9-99b6-6e7b9a0f8f2c.png)


We're also looking for clarification or direction in adding the bounce rate metric to this page. Where do you intend it to be added? It could be on it's own but seems better to include with the other stats. Do you mean for it to replace another metric in the search funnel box? Perhaps clicks or session duration?

**Comment by marrrmarrr** [comment]
@circlecube thanks for sharing the updated screenshot. 
A few comments:
1) For the section titles, let's capitalise only the first word (e.g. "Top Search Queries For This Page" --> "Top search queries for this page") 
2) Let's replace "average session duration" with "bounce rate" 
3) Where would the "source" links point to in this case? To the general subreport showing stats for the entire site? 
4) Where does the "See full stats in Analytics" link point to? 
5) For the case where there is not enough information for queries to show, can we distinguish based on API responses whether that is because of the site recently having been verified (no SC aggregated data yet for the whole site), or not enough data for queries purely for this page (because of e.g. privacy threshold reasons)? If we can distinguish between these, let's show a more informative message in the latter case, e.g. "No query stats available yet for this page"

**Comment by circlecube** [comment]
@marrrmarrr 
1. Understood
2. Will do.
3. The source links are linking to the analytics and search console sites. These are already in place in the (beta) released versions of the plugin.
4. Same as above, this link goes to the google analytics site. The fact that the links are external is indicated with the icon following the text.
5. Will look into if this can be distinguished based on the response, @adamsilverstein do you know tihs?

**Comment by circlecube** [comment]
Status Update: I've got answers to the questions above, working with Adam on 5 and on replacing the "average session duration" module with "bounce rate". Will provide a further status update after that.

**Comment by lilybonney** [comment]
Noting (per our team discussion earlier today) that @circlecube will be confirming answers to the remaining questions (per his update above) today, and will then assign the ticket to Mariya for her to write the Acceptance Criteria.

**Comment by circlecube** [comment]
Looking at this again I misspoke earlier regarding your question on 3.

1. ✅
2. ✅
3. Your assumption is correct. The source links link to the general subreports, the main analytics page and the main search console pages within the wordpress admin.
4. For clarification, this link is external. As is the Source: Analytics link in the footer of the "How people found this site" box (as is indicated with the icons).
5. After some discussion with @adamsilverstein, this should be doable (likely more as a task for a back end engineer). We will have to dig deeper to test if the API response includes that data, but if not we can still set a flag on initially receiving any data from search console api, then the error message may update accordingly to be more informative.

**Comment by marrrmarrr** [comment]
Thanks for the clarifications @circlecube. 
(1)-(3) SGTM
On (4), for the Search Console source link which can be customised with parameters, let's update so they take the user to the correct filtered view (I don't think that's possible with Analytics since we don't know the property ID parameter). 
For example, here's the filtered view for queries leading to a specific page: 
https://search.google.com/search-console/performance/search-analytics?resource_id=INSERT-SITE-URL&breakdown=query&page=!INSERT-PAGE-URL
On (5), let's spin up a separate issue (type enhancement) for this.

**Comment by circlecube** [comment]
@marrrmarrr Acceptance criteria seems to be missing details. Specifically regarding the Bounce Rate addition and maybe adding the date range selectors too.

**Comment by felixarntz** [comment]
> New ticket to display clear informational messages instead of "gathering data".

This should not be part of the implementation brief, but should be clarified in advance. @marrrmarrr Are you okay with removing the acceptance criteria item 2 from here, since it appears to be covered in a separate issue (#314)?

> Change module displaying data for average session duration to update to bounce rate - pull data from `overview.averageBounceRate` in place of `overview.averageSessionDuration` values in `assets/js/modules/analytics/dashboard/dashboard-widget-top-level.js`.

@circlecube Can you clarify how this relates to the requested changes? When looking at the code, I can't find where this file is used on the `dashboard-details` view, it appears to be only used in the regular `dashboard`.

**Comment by circlecube** [comment]
@felixarntz This file is in relation to the request to update from the average session time to the bounce rate. Correct me if I'm wrong, but this analytics module is brought into the search funnel widget listed on the detail page. At line 220 in that file (`assets/js/modules/analytics/dashboard/dashboard-widget-top-level.js`) is a template conditional clause that looks for the permaLink value (which only exists for the detail page), it's just below the comment that mentions the block is displayed for the general view and the average time on page for detail views.

**Comment by felixarntz** [comment]
This is now split into and fully covered by a few issues with updated requirements: #460 #461 #464 #467 

Closing this one.
