### ISSUE TITLE
Build and deploy storybook static files to GitHub pages for develop and master

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1459]
## Feature Description

We should make Storybook available on google.github.io/site-kit-wp.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When pushing to `develop` or `master`, Storybook static files should be built and written to the `gh-pages` branch.
* In the `gh-pages` branch, a folder should be added per branch (e.g. so that the URLs will end up like `https://google.github.io/site-kit-wp/storybook/develop` and `https://google.github.io/site-kit-wp/storybook/master`).
* This must **not** happen for pull-requests.

## Implementation Brief

There is an easy-to-use Travis-CI integration for deploying to GitHub pages (which e.g. the Web Stories plugin is using: https://github.com/google/web-stories-wp/blob/d181a4ea75cff53db730920fb41c41e2624a0c96/.travis.yml#L130-L141). However, that appears not to support deploying only partial content - you can specify a `local_dir`, but not a `remote_dir`. Hence, using a GitHub action workflow makes more sense. A lot of the necessary code can be taken from the existing `build-pr.yml` workflow.

* Add `npm run build:storybook` command that stores storybook in a `storybook-static` folder (ignore that folder in git).
* Add `build-storybook.yml` workflow that runs `npm run build:storybook`, then uploads the files as artifacts, then downloads it and integrates them into the `gh-pages` branch (in a `storybook/{$branch_name}` folder) and commits.
* Merge #1457.

## QA Brief

* 

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
This looks good to me @felixarntz - my only question is around the use of GitHub pages for the repo. You probably thought about this but it seems unlikely that Storybook is the only thing we might want to build like this to make available on the web in the future (e.g. API documentation).

* Idea 1: deploy the files to a sub-directory of the pages repo, so it would use `google.github.io/site-kit-wp/storybook` as a base URL instead
* Idea 2: Not use GitHub Pages at all. Netlify might be a really nice fit here and wouldn't even require any custom GitHub actions. Basically, we'd connect the repo to a new (free) site on Netlify and configure the build command and target directory to use for public files. It also has a feature called ["Deploy Previews"](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/) which handle the branch/PR use-case really nicely.
> Every time you open a pull request, or push new changes to a branch, Netlify automatically builds a preview with a unique URL. Like a staging environment for every PR or branch, previews are perfect for testing and collaboration.

More information about what's possible with this here:
https://www.netlify.com/blog/2017/11/16/get-full-control-over-your-deployed-branches/

Otherwise, this looks just fine for what you have outlined using GitHub pages 👌

**Comment by felixarntz** [comment]
@aaemnnosttv I like your suggestion to use a subdirectory for `storybook`. I'll update the IB (and PR). In terms of Netlify, I'd rather rely on GH Pages for now since that certainly works and is a thing we already have anyway, rather than adding another piece to our stack (may also be complicated because of `google` org requirements).

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ✅

I like this! Thanks to @aaemnnosttv for pointing out namespacing of the URL to storybook, because I can see this being useful for other stuff going forward 😄

https://google.github.io/site-kit-wp/storybook/develop works and points to storybook, and importantly, https://google.github.io/site-kit-wp/storybook/enhancement/1443-optimize-local-scripts (another branch that _shouldn't_ have storybook builds) doesn't have a URL, so I'd say we're good!

**Comment by aaemnnosttv** [comment]
**QA ❌** 

Currently no static assets are rendering in the build due to moving the files into a subdirectory; Storybook seems to assume that it's running relative to the root rather than `/storybook`.

**Comment by aaemnnosttv** [comment]
@felixarntz the main fix has been merged. I opened a follow-up PR as a simplification for your consideration, but otherwise this is good to go 👍

**Comment by felixarntz** [comment]
QA ✅ 

See https://google.github.io/site-kit-wp/storybook/develop/ and https://google.github.io/site-kit-wp/storybook/master/, all working correctly now with images and icons.
