### ISSUE TITLE
Fix Analytics store bug with empty array API responses

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1470]
## Bug Description

The properties and profiles parts of the `modules/analytics` datastore currently rely on the response items to key them in the datastore state. This isn't really necessary because the individual array items in a single response will _always_ apply to the same account ID / property ID because of how the API works. Furthermore, relying on the response results in a bug when an empty array is returned - in this case there's no item to look at, so the datastore's state property will not be filled, leaving the state in the same way it would have been if the data had not been loaded yet at all.

This is a follow-up to #1269, hence high priority to also have in the coming release.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `receiveProperties` and `receiveProfiles` (plus their reducer cases) in the `modules/analytics` datastore must not rely on response items to determine the key in the datastore state, but instead rely on the original parameter that the data was requested with, to ensure this also works for empty arrays where there's nothing to look at.

## Implementation Brief

* Instead of using `groupBy` based on response items, add an additional object with the respective parameter to the `receive...` signature (`receiveProperties( properties, { accountID } )` and `receiveProfiles( profiles, { propertyID } )`), and rely on that value in the reducer for the key.
* Nesting in a parameters object is strictly not necessary here, but makes sense to prepare for #1288, which will do that throughout, internally.
* A similar fix was recently done in the AdSense refactoring PR (only difference is that there it was for something called clients, which is almost similar to Analytics properties), so basically we need to do exactly the same here: https://github.com/google/site-kit-wp/pull/1410/commits/637da8414b701980cfa85beba0bf2ba9471e8f63
* All calls to these two `receive...` functions need to be updated to still work, including Jest tests and Storybook. Having to pass the parameter makes this more explicit, but a lot of other code already does that, and it's necessary here too (see AdSense Storybook example: https://github.com/google/site-kit-wp/pull/1410/commits/2ef371b4deb2fe2b4079f0389faab7f654246160)

## QA Brief

* 

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz there are a few exceptions where this bug is not 100% fixable just by passing along params.

@ShahAaron brought it to my attention that there are two cases where we run into the same problem:
* `fetchAccountsPropertiesProfiles`
* `fetchPropertiesProfiles`

In these actions, the main action lacks the parameter(s) needed to pass to the secondary receive calls.
* `fetchAccountsPropertiesProfiles` lacks `accountID` to pass for `receiveProperties` and lacks `propertyID` to pass for `receiveProfiles`
* `fetchPropertiesProfiles` lacks the `propertyID` to pass for `receiveProfiles`

This leaves us in the same situation where we can only infer the parent from the response, but doesn't solve the problem for empty responses, and we're forced to skip the `receive` call for empty responses.

The solution here I think is to pass the `accountID` and `propertyID` back from the datapoint handlers which are used for the secondary requests. That would solve 2 of the 3 cases:
* Receiving empty properties for an account in `fetchAccountsPropertiesProfiles`
* Receiving empty profiles for a property in `fetchPropertiesProfiles`

It would not however solve receiving empty profiles for an account with no properties in `fetchAccountsPropertiesProfiles`.

What do you think?

**Comment by felixarntz** [comment]
@aaemnnosttv @ShahAaron Good catch!

For all of these cases, I think we should skip the calls to `receiveProperties` and `receiveProfiles` entirely if the respective arrays are empty. These calls are only used to populate data in a single request, but they are auxiliary for performance and not essential for the functionality.

Not calling them if not possible is perfectly fine, as the selector for e.g. `getProperties` or `getProfiles` would handle making the request itself then - that's just a minor trade-off I think.

I think we shouldn't bend our APIs to better support these very particular and strange "aggregate" fetchers. Usually if an empty array is returned from one of them, the respective list wasn't even attempted to be fetched, which is another reason to simply skip.

For the regular cases that there are array elements in there, we should look up the respective `accountId` / `propertyId` from the first element and pass that to `receiveProperties` / `receiveProfiles`.

**Comment by felixarntz** [comment]
QA ⚠️ 

Tested this by manually enforcing empty properties and profiles arrays to be returned, from `accounts-properties-profiles`, `properties-profiles` and `profiles`. All worked as expected: In the "bulk" datapoints, if one of the sub-arrays was empty, the respective list would not be populated in the datastore, instead relying on a separate request to `properties-profiles` or `profiles` respectively. If that response then is empty, it's populated in the datastore as expected. So functionality-wise this is all good 👍 

A few occurrences in Storybook though for `receiveProperties` and `receiveProfiles` were not adjusted, resulting in JS errors for these Storybook components. This has already been adjusted now via #1513.

**Comment by felixarntz** [comment]
QA ✅ 

After #1513 being merged, Storybook now works as expected too.
