### ISSUE TITLE
Logos not rendering on IE11

### ISSUE THREAD

**Issue by cole10up** [google/site-kit-wp#1475]
## Bug Description

Module logos and Global Site Kit logo isnt rendering on IE11

## Steps to reproduce

**Pre-condition:** On IE11 
1. Install the attached zip
[google-site-kit.v1.7.1.develop@d404b8ba9a (2).zip](https://github.com/google/site-kit-wp/files/4562727/google-site-kit.v1.7.1.develop%40d404b8ba9a.2.zip)
2. Activate the plugin
Notice SK logo isn't rendering both on plugins page and dashboard
![image](https://user-images.githubusercontent.com/57115907/80787066-45955500-8b3a-11ea-8e70-f367e984b097.png)
![image](https://user-images.githubusercontent.com/57115907/80787101-5e056f80-8b3a-11ea-9223-c18494a716c0.png)

3. Complete setup
Notice SK logo and module logos for Adsense, Analytics and Search Console aren't rendering
![image](https://user-images.githubusercontent.com/57115907/80787181-a91f8280-8b3a-11ea-93fe-3389bd4a8db9.png)

4. Click Settings
Notice SK logo is missing and module logos for Adsense, Analytics, Search Console, Optimize and Tag Manager are missing
![image](https://user-images.githubusercontent.com/57115907/80787316-0e737380-8b3b-11ea-829f-dc59b6e7628b.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@cole10up @wpdarren I believe this is already fixed, can you please confirm? If this is no longer an issue, let's close it 👍

**Comment by wpdarren** [comment]
@aaemnnosttv in IE11 on Windows 10, the screen is blank when going to all of the Site Kit pages. 

![image](https://user-images.githubusercontent.com/73545194/113570131-5271d100-9646-11eb-9edd-175fc688d3bf.png)

When looking at the console there are 2 warnings and 1 error. 

![image](https://user-images.githubusercontent.com/73545194/113570495-0a9f7980-9647-11eb-8134-89d4a4af0ab9.png)

Should we close ticket but create a new one for IE11, or, considering Microsoft doesn't support IE11 is this worth our time?

**Comment by aaemnnosttv** [comment]
Thanks @wpdarren.

Taking a closer look, it seems like there may be problems in WP itself as well 
![image](https://user-images.githubusercontent.com/1621608/113814227-fb6d1880-9779-11eb-8006-c75d74b4b325.png)
This seems to be due to an arrow function in the polyfill which IE doesn't support 😄 

You're right that none of our React apps are rendering though. This appears to be due to the same issue - an arrow function in our vendor bundle: 
![image](https://user-images.githubusercontent.com/1621608/113814733-c4e3cd80-977a-11eb-9f83-d01b06d5fb92.png)

This is likely because node modules are assumed to be pre-built so it's common (and much more performant) for bundlers to exclude node_modules from transpilation. Because this is in our vendor bundle, it breaks all our apps on IE11 as it's loaded everywhere.

Regarding support for IE11 in general, [conversation is starting in core to drop support for it](https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/). Also, there is a very prominent warning about using IE 11 right on the dashboard (likely only in newer WP though). 
![image](https://user-images.githubusercontent.com/1621608/113815459-d8436880-977b-11eb-91b3-5f4e81a9a3f0.png)


Looking at the support forum, there seem to actually be zero posts about IE 11 so our user base must not be using it or we should have seen this pop up many times by now.

Let's discuss! @felixarntz @marrrmarrr

**Comment by felixarntz** [comment]
After reviewing browser support, it was decided to explicitly drop support for IE, especially since it is reaching EOL.
