### ISSUE TITLE
Preload REST API datapoints for core/site and core/user stores

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1478]
## Feature Description

The `core/site` and `core/user` stores fetch certain crucial data through API calls. This data should preferably be available on pageload since it is essential, and a lot of that data would in the legacy code have been on the `googlesitekit` global too, which is a good indicator that it should be preloaded.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Preload data for `core/site/data/connection`.
* Preload data for `core/user/data/authentication`.

## Implementation Brief

* Add `googlesitekit_apifetch_preload_paths` filter in `Authentication::register` method that preloads the two routes from the ACs.

## QA Brief

* 

## Changelog entry

* Preload REST API datapoints for `core/site` and `core/user` datastores to avoid firing these extra requests.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## QA ❌ 

This issue introduces an unexpected bug as a result of preloading `core/user/data/authentication` which causes new scopes to not be requested when activating a new module.

This is because after the new module is activated (via REST request), `refreshAuthentication` is called which in turn calls `core/user/data/authentication` to check if new scopes are required. Since this is cached from the initial page load where the new module was not active yet, the user ends up on the setup screen with reauth errors because the necessary scopes weren't granted.

https://github.com/google/site-kit-wp/blob/1d33653e2f5fb620676abe4623a709fe038f891d/assets/js/components/analytics-inactive-cta.js#L46-L51

https://github.com/google/site-kit-wp/blob/1d33653e2f5fb620676abe4623a709fe038f891d/assets/js/util/refresh-authentication.js#L26-L30

The solution here is to simply ensure that the request to `core/user/data/authentication` is always made in `refreshAuthentication` by adding a cache-busting parameter.

**Comment by felixarntz** [comment]
@aaemnnosttv Does the preloading middleware persist for all requests to that endpoint? Can we make it so that it only relies on the preload data the first time?

We'll need to make sure that we can force-refetch this information specifically for `core/user/data/authentication` - having to pass an extra parameter always is a bit unintuitive.

**Comment by aaemnnosttv** [comment]
> Does the preloading middleware persist for all requests to that endpoint? Can we make it so that it only relies on the preload data the first time?
>
> We'll need to make sure that we can force-refetch this information specifically for core/user/data/authentication - having to pass an extra parameter always is a bit unintuitive.

Yeah, it is persistent for all requests to the preloaded URL.

We could perhaps create our own version of it which has alternate behavior since the middleware itself is only ~25 lines. However, only serving the preloaded response once and ensuring that the request is always made are not the same thing.

If we were to create an alternate middleware, I think the only change we would want to make is allowing for an option to bypass the preloaded response cache (the middleware receives the object of options passed to `apiFetch`). As a side-effect, we could also update the cache for that request with the response.

Alternatively, another option (which is perhaps the simplest of all) would be to expose the same endpoint with a POST method since these aren't subject to caching (either by preloading middleware or our own request cache). I think this is probably the best way to go here as it's the most straightforward and "refresh auth" sounds like a command which better fits a POST request and saves you from remembering to use a parameter for cache-busting.

**Comment by felixarntz** [comment]
@aaemnnosttv Hmm, I think the part that bugs me most about this is that we already have a caching layer. Mostly that should be responsible for avoiding API requests when we already have a result. Maybe we can update the `googlesitekit-api` module to just always append the `timestamp` query parameter for `GET` requests when `useCache` is `false`? It's a bit hacky, but I think that should work. For requests where we need to refresh authentication, we'd surely need to set `useCache` to `false` anyway.

**Comment by cole10up** [comment]
**Tested**

Ran a series of regression tests around data and pageloads. Installed SK 1.8.0 production ready zip. Activated SK and added all modules. Confirmed pageloads across the board without error for each module.

Notice the following page error for Analytics:
![image](https://user-images.githubusercontent.com/57115907/81258205-ffcd0680-8fe9-11ea-874f-d643b653ea82.png)

Notice the following page error for Adsense:
![image](https://user-images.githubusercontent.com/57115907/81258258-212df280-8fea-11ea-9f4e-8173cd49f3f5.png)

Site: hellogoodbye.today

This is consistently reproducible. 

Sending to Execution for validation - @aaemnnosttv

**Comment by aaemnnosttv** [comment]
@cole10up I was not able to reproduce this on my end and was able to successfully set up Analytics and AdSense without any errors or warnings.

I think this warning may happen if you somehow authenticate with a different Google user for Analytics then you do with AdSense. This is not easy to do anymore with the login hint we have in the oauth flow. Alternatively, if you change your site's reference URL between module setups, that may also be a factor.

@felixarntz one thing I noticed when trying to reproduce this is that the `adsenseLinked` setting in Analytics seems to always be false, even after AdSense is successfully set up and Analytics' `GET:report` is called with AdSense metrics. Everything seems to be working fine but this bit seems potentially off.

**Comment by felixarntz** [comment]
@aaemnnosttv Is `adsenseLinked` still `false` despite the `GET:report` response being successful and the AdSense `setupComplete` being `true`?

**Comment by aaemnnosttv** [comment]
@felixarntz that's what it looked like to me, yes. I'll give it another try and see if I see the same thing. Would be great if you could test this on your end as well.

**Comment by aaemnnosttv** [comment]
@felixarntz I'm not sure if this is directly responsible for the warning that @cole10up was seeing (I have seen this too before but I don't recall recently or why this happens).

I created https://github.com/google/site-kit-wp/issues/1524 regarding the `adsenseLinked` bug.

**Comment by felixarntz** [comment]
@aaemnnosttv @cole10up The API error itself is expected to happen if the AdSense account or site is maybe not fully configured yet, so I think that is okay. Whenever this error _does not_ happen, `adsenseLinked` is set to `true` (after fixing it in #1524 FWIW), to indicate that Analytics has now recognized AdSense being properly configured for the site.
