### ISSUE TITLE
Adsense prolonged pending status (no code snippet)

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1494]
## Bug Description

Users have reported being in an unusual pending state after connecting to Adsense. 

- No toggle to insert the Adsense code in the settings with a message that says Site Kit has placed its code, and to check the module page:

<img width="1031" alt="Adsense pending state" src="https://user-images.githubusercontent.com/8108643/81003567-ee280b00-8dff-11ea-81fb-3af51e0b13d7.png">

- Adsense code not inserted on the site.

- Adsense module page has this messaging:  

> Let’s get your site ready for ads
> 
> After you’ve finished setting up your account, we’ll let you know when your site is ready to show ads. This usually takes less than a day, but it can sometimes take a bit longer.
> 
> Go to your AdSense account to check on your site’s status or to complete setting up.

- Messaging in their Adsense account varies.  Some have instructions to insert Site Kit's code on the site. One user reported seeing this message: 

> Please excuse the inconvenience, but at the moment we cannot process your request. We have put the problem in the hands of our engineers, who are already working to solve it.) 

- Users with existing and new Adsense accounts have experienced this. 

related support topics:
https://wordpress.org/support/topic/adsense-horror-in-site-kit/
https://wordpress.org/support/topic/keep-getting-the-almost-ready-message-in-site-kit-when-trying-to-connect-adsense/
https://wordpress.org/support/topic/ve-a-tu-cuenta-de-adsense-para-comprobar-el-estado-de-tu-sitio-o-para-completar/
https://wordpress.org/support/topic/adsense-setup-process-doesnt-move-forward/

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

* Fix bug where having a graylisted AdSense account would prevent the AdSense code from being placed.

**Comment by felixarntz** [comment]
This issue is fixed via the AdSense module setup refactoring #1014, being included in 1.9.0. The problem in the original codebase was that, for accounts that were graylisted, that account status was determined before obtaining and saving the AdSense client ID - and without that, the snippet cannot be rendered.

See this part of the previous codebase: https://github.com/google/site-kit-wp/blob/1.8.1/assets/js/modules/adsense/util/index.js#L332:
* If account is graylisted, that is saved as `ads-display-pending` account status.
* Right below, in the `else` clause (thus not run), only there the logic would retrieve and save the client ID.
* Because only the pending account status, but no client ID is saved, the snippet would not be printed in this case.
