### ISSUE TITLE
Add a generic, "core/forms" store for forms

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#1510]
Issue #1211 required some forms that didn't warrant creating a bunch of actions, selectors, etc. for their data, but we shouldn't be using `useState` to manage form data because it requires passing around state from components and negates a lot of the wins we get from using a Redux-backed datastore.

We talked about this on a call today, and we should have a generic, `'core/forms'` data store with a very basic API for getting/setting state across forms in the app.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new file, `assets/js/googlesitekit/datastore/forms`, that registers a new form data store, under `'core/forms'`.
* It should provide a single selector: `getValue( formName, key )`
* It should provide a single action: `setValues( formName, { key: value } )` where the second argument is a map of keys to set and their respective values.

## Implementation Brief

* Create a new datastore in `assets/js/googlesitekit/datastore/forms` that registers a new form data store, under `'core/forms'`.
* Create a `assets/js/googlesitekit-forms.js` that registers the `core/forms` store on the default registry.
* Add a `googlesitekit-forms` asset in `Assets.php`, similar to `googlesitekit-api`, `googlesitekit-data`, etc. that would load the `core/form` datastore into the default registry.
* Add a selector: `getValue( formName, key )`. This should return the value stored in the `state[ formName ][ key]`; `undefined` if the `formName` or `key` doesn't exist.
* Add an action: `setValues( formName, { key: value } )` where the second argument is a map of keys to set and their respective values. If the specified `formName` doesn't exist; it should be created.

## QA Brief

* Since this is an engineering-only feature for now, specific QA isn't really needed.

## Changelog entry

* Introduce `core/forms` datastore to manage form state.

**Comment by tofumatt** [comment]
Flagging this as a 7 estimate, but for what it's worth it's closer to 3-4 hours than 7 and doesn't require much specialised QA. 😄

**Comment by felixarntz** [comment]
@tofumatt 
Maybe we should have `setValues( formName, { key: value } )` and `setValue( formName, key, value )`? The latter could technically call the former. I just think your current suggestion is a bit confusing using a singular "value" in the name but accepting multiple. I think it should use the plural, and having the other one would be more of a convenience thing if we need it.

Regarding where to put this, I think we should align it with `core/site` and `core/user`. This is a standalone store and not "merged" with other functionality like we have with `core/modules` and `core/widgets`, so I'd say it should be in `assets/js/googlesitekit/datastore/forms`. We should also register a PHP asset for it rather than bake it into `googlesitekit.data` right away I think, similar like with the other ones. _If_ we decide to bundle it into `googlesitekit.data` as some kind of default store that you always get, then it should be within `assets/js/googlesitekit/data` instead - I'm not a fan of this though as it would be kind of an arbitrary choice to do that here, like why is this store more justified to be bundled into `googlesitekit.data` than others. I know you're not a fan of this, but I think we should register an asset with it like for `core/site` and `core/user`.

**Comment by tofumatt** [comment]
Sounds good; I've updated the IB with your suggestions, with one exception: I don't think the extra `setValue` function provides any extra value. The functionality from `setValue( 'foo', 'bar' )` is already present in `setValues({ foo: 'bar' })`, but the latter is more extensible if one wants to add more items.

I don't think there's much benefit in having the single-variable one, especially if we're the only ones using this API for now. But it's an extra API to maintain without much benefit, so I'd prefer not to add it. (It is easy, but it's also not super-useful in my opinion.)

**Comment by felixarntz** [comment]
IB ✅

**Comment by ShahAaron** [comment]
@tofumatt should this be named `assets/js/googlesitekit-forms.js` or `assets/js/googlesitekit-datastore-forms.js similar to the way `user` and `site` are named?

**Comment by tofumatt** [comment]
I suppose `assets/js/googlesitekit-datastore-forms.js ` is more inline with what we do—that seems fine to me.

**Comment by felixarntz** [comment]
Good question @ShahAaron, let's use `assets/js/googlesitekit-datastore-forms.js` - thanks for catching that!

**Comment by tofumatt** [comment]
Code review ✅. Assigning to @aaemnnosttv to merge.

**Comment by ryanwelcher** [comment]
Looks good to me! QA ✅
