### ISSUE TITLE
Avoid extra click after granting OAuth scopes for a certain action

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1610]
## Feature Description

Follow-up to #1566: As the outcome there, after a user has returned from OAuth after granting the additional permissions, they end up on the screen they originally were on. However, at the moment they still have to re-trigger the same action (e.g. click on "Configure Analytics" if they had selected "Setup new property"), which isn't a great user experience.

For Analytics account provisioning, this experience is already in place because it was implemented there specifically. We should now look into how we can implement this with a more general approach, similar to how the `PermissionsModal` and permissions scope error handling itself is not coupled to any specific module or screen.

Since re-triggering the exact action is tied to the specific component that e.g. holds the button to click, it's unlikely that we can fully "automate" this without requiring any extra code per case. However, let's look for a solution that scales as much as possible, e.g. set a flag in the datastore automatically that the component could react on, re-triggering the action previously attempted (which resulted in the permissions modal and redirect).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `core/user` store should have a new selector `hasScope( scope )` which checks whether `getGrantedScopes()` includes the scope checked for.
* The specific `has*Scope()` selectors on `modules/analytics` should be removed and their usage should be replaced with calling the above `hasScope( scope )`.

## Implementation Brief

* Add a new `hasScope( scope: string )` registry selector to `assets/js/googlesitekit/datastore/user/authentication.js`
	- Returns `({boolean|undefined})` based on whether or not granted scopes are loaded yet  
	If loaded, returns `grantedScopes.includes( scope )`
	- Add Jest tests for selector behavior, similar to other selectors
* Refactor [Analytics-specific scope selectors](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/datastore/permissions.js) with new `hasScope` using scope constants
* Remove `assets/js/modules/analytics/datastore/permissions.js` and inclusion in combined store

## QA Brief

* 

## Changelog entry

* Add `hasScope( scope )` selector to `core/user` store, which allows checking whether the user has explicitly granted access to the respective scope.

**Comment by aaemnnosttv** [comment]
@felixarntz this issue is a bit difficult to define as-is as the current AC is already met with the use-cases we need it for.

I talked this through a bit with @tofumatt to see if there are any potential abstractions that make sense right now and there doesn't seem to be much room for enhancement as it is. It may be a bit early to try to create an abstraction here as we have so few instances of it in the codebase. It would probably be a good idea to wait on this until we have a few more actions like this to better inform a potential refactoring here.

One thing we identified as a win for reducing the amount of code necessary to implement this would be adding a generic `hasScope` selector to the `core/user` store. This could then be used in combination with a scope constant rather than adding a new selector for each scope we want to check for. We feel adding this selector would make the current approach a bit more scalable, but apart from that we find it is already simple and effective as well as declarative and requires almost no additional code to implement in new stores, apart from including the snapshot store (although we could perhaps just move this to `commonStore`?).

Thoughts @felixarntz @tofumatt ?

**Comment by felixarntz** [comment]
@aaemnnosttv I like the idea of a general `hasScope` selector on `core/user`, let's do that and then removed the more specific selectors on `modules/analytics`.

Regarding the snapshot store, I'd wanna hold off adding that to `commonStore` since right now we intentionally only use it for certain stores. For example if we just added it to `core/user`, we'd end up having the scope error and scopes data from before persisting, which wouldn't be right - so this would require a bit more thought.

**Comment by tofumatt** [comment]
IB ✅

**Comment by ShahAaron** [comment]
Tested

Pulled branch and setup locally. Insured site functions as expected.
All tests run locally

- New `hasScope( scope: string )` registry selector added to `core/user` datastore in `assets/js/googlesitekit/datastore/user/authentication.js` - confirmed
- returns `({boolean|undefined})` based on if granted scopes have been loaded - confirmed
- Jest test added for `hasScope` selector
- `assets/js/modules/analytics/datastore/permissions.js` removed and associated test - confirmed
- `hasScope` replaces `hasProvisioningScope` and `hasEditScope` with scope constants in analytics

QA passed ✅
