### ISSUE TITLE
Optimize: AMP Experiment UI Improvements 

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1628]
## Feature Description

 When configuring Optimize on a site with [the AMP plugin](https://wordpress.org/plugins/amp/), the option to add an AMP experiment is available via text entry of the JSON format configuration instructed [in the documentation](https://developers.google.com/optimize/devguides/amp-experiments):

<img width="748" alt="Optimize AMP Experiment" src="https://user-images.githubusercontent.com/8108643/83531153-7225ef00-a4a1-11ea-945b-a264f9437fde.png">
The documentation requires the user to construct their own JSON components from various items 
in their Optimize experience. This may be a difficult and error-prone user experience for non-technical users. A more user-friendly configuration option would be worth considering. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
We should explore what we can reasonably do here: The main issue is that handling Optimize experiments in AMP is currently an entirely manual process. You'll have to set them up in Optimize UI, but then also you have to manually copy/paste the reference data over to your site (that's what would currently go in the `ampExperimentJSON` setting). Whenever you stop an Optimize experiment in the UI, you will once again have to do the same in the plugin too, removing these references from the site manually.

There is actually an API endpoint in Analytics (which is a requirement for Optimize anyway) which would allow us to get the experiments ourselves: https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/experiments/list

We could use that to build the `ampExperimentJSON` ourselves. However, people may already have their own `ampExperimentJSON` instances in place or may want to make adjustments, so it may be worth just introducing a button like "Fetch experiments" that would make the request, build JSON on the client and then add it to the field. This way the user could still adjust it. The downside is either way they would need to re-fetch when they've made changes to their Optimize configuration. We could think about continuously polling the API over time even from the server, but this would drastically increase the scope of this issue - especially because Optimize would not be the only module where this would be useful.

**Comment by adamsilverstein** [comment]
I tried implementing an experiment with AMP without much luck. Even with everything set up, I never saw live activity being reported in Optimize, or the variations I specified running. Disabling AMP, the experiment worked as expected.

According to the instructions, in addition to the amp-experiment JSON snippet, I need to add an `amp-analytics` snippet, and Site Kit doesn't seem to handle that. See https://developers.google.com/optimize/devguides/amp-experiments#amp-experiment:

```html
<amp-analytics id='analytics1' type='googleanalytics'>
<script type='application/json'>
{
  "vars": {
    "account": "gaPropertyID"
  },
  "requests": {
     "experiment": "${pageview}&xid=${xid}&xvar=${xvar}"
  },
  "triggers": {
    "trackPageview": {
      "on": "visible",
      "request": "experiment",
       "vars": {
         "xid": "gaExperimentID",
         "xvar": "VARIANT(experimentName)"
       }
    }
  }
}
</script>
</amp-analytics>
```

We already have the value for gaPropertyID and we can get gaExperimentID, and experimentName from the API.

**Comment by adamsilverstein** [comment]
@felixarntz This issue came up recently in Newspack and I would like to prioritize addressing. Can we move this to IB for the next sprint?

**Comment by adamsilverstein** [comment]
Quick update I was able to get an experiment working eventually, but the process was far from straightforward. We should be able to build the required JSON and analytics config automatically from the API responses.

**Comment by aaemnnosttv** [comment]
Closing per #6466
