### ISSUE TITLE
Search Console - Inconsistant data between SC web UI and Site Kit dashboard

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1635]
## Bug Description

As reported in the [WordPress support forums](https://wordpress.org/support/topic/inconstant-data/#post-12932561) metrics using the same reporting periods don't match, showing significant differences between the SC web UI and  Site Kit dashboard. 

![image](https://user-images.githubusercontent.com/41326532/83661283-ca521380-a5bd-11ea-9e8d-23160051b63f.png)

Replicated in support on site with medium traffic. 
![image](https://user-images.githubusercontent.com/41326532/83659963-2025bc00-a5bc-11ea-989d-ee6cf945d4aa.png)

Another example in support on site with minimal traffic:

![image](https://user-images.githubusercontent.com/41326532/83661177-aabaeb00-a5bd-11ea-904a-825cdcb43aee.png)

## Additional Context

 - Reproduced in support, happy to share login for site as per screenshots
 - Original support topic: https://wordpress.org/support/topic/inconstant-data/#post-12932561
 - In the original support topic the descrepencies are significant, while in the reproducable reports the differences are slight
- Site Health info provided for review if needed
- Confirmed correct URL type property used
 - Plugin Version 1.9
 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
Unfortunately, after some debugging, it looks like this is something we cannot address:
* [We currently use an offset of 3 days for querying SC data.](https://github.com/google/site-kit-wp/blob/1.9.0/includes/Modules/Search_Console.php#L195)
* When testing today (2020-06-09), this means we request data until (including) 2020-06-07. I changed this value to 1, so that we actually request until 2020-06-09. However, the response still only includes data until 2020-06-07, so our original value of 3 there is still all we can do.
* Note that Search Console itself flags data from yesterday, 2020-06-08, as "fresh data" when hovering over it (it doesn't have _any_ data for today, 2020-06-09, yet), and it explains "usually replaced with final data within a few days". So I assume the Search Console API only exposes data that is no longer considered "fresh data".

I suggest to close this issue since we cannot fix it, and explain to the user that this is the most up to date information that Search Console provides through its API.

**Comment by jamesozzie** [comment]
Very useful to know going forward. Closing as it's more service/API related, with user notified.
