### ISSUE TITLE
AMP plugin comaptibility: Notice: is_amp_endpoint was called incorrectly

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1650]
## Bug Description

A [user in the support forums](https://wordpress.org/support/topic/issue-with-amp-plugin/) reported getting the following error when using the [AMP plugin](https://wordpress.org/plugins/amp/) and installing Site Kit on the wp-login page:

`Notice: is_amp_endpoint was called incorrectly. is_amp_endpoint() was called before the parse_query hook was called. Please see Debugging in WordPress for more information. (This message was added in version 0.4.2.) in /home/paiddbname/public_html/wp-includes/functions.php on line 5167`

After deleting Site Kit the error goes away. 

[Site Health Info
](https://wordpress.org/support/topic/issue-with-amp-plugin/#post-12913396)
## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All the general logic in the `Assets` class should only be run if potentially relevant for Site Kit usage (i.e. if `current_user_can( Permissions::AUTHENTICATE )`) - otherwise it does nothing for Site Kit and could just introduce unintended side effects or performance or security leaks.
* Only the registration of Site Kit assets should continue happen everywhere.

## Implementation Brief

* In `Plugin`, move `Assets` instantiation into the `init` action so that the current user is set up already at this point. Also move the `Activation` instantiation in there since it relies on the `Assets` instance - that's fine since the hooks that it adds to all happen later anyway.
* In `Assets::register`, bail right after adding the asset registration action if `! current_user_can( Permissions::AUTHENTICATE )`.
* Move the call to `add_amp_dev_mode_attributes` out of `register_assets` and instead move it into the `Assets::register` method as well so that it only happens when relevant for Site Kit.
* Merge #1659.

## QA Brief

* 

## Changelog entry

* Do not run Site Kit assets logic when not applicable for the current user, avoiding unnecessary checks e.g. on the login screen.

**Comment by westonruter** [comment]
Note how AMP plugin v1.5.3 implements `is_amp_endpoint()`: https://github.com/ampproject/amp-wp/blob/1.5.3/includes/amp-helper-functions.php#L569-L571

So it should short-circuit for `wp-login.php`. 

Take note that the logic has been revised in 1.6-alpha: https://github.com/ampproject/amp-wp/pull/4574

See https://github.com/ampproject/amp-wp/blob/4743ae5881f05faf518c525005e3409137637b35/includes/amp-helper-functions.php#L611-L614

In both cases, however, I'm confused why the the `parse_query` warning is being emitted since the `is_admin()` or `wp-login.php` check would have been done up front.

**Comment by felixarntz** [comment]
I'm not sure exactly why the user saw this notice, since the AMP plugin should cover for it (and the user appears to have the correct versions via their Site Health information).

However, this points at somewhat of a concern, which is that we preferably shouldn't even need to check for `Context::is_amp()` on login screens. At the moment, this happens in the `Assets` class, in order to make some "core polyfills" and our additional dependency logic work. Since all of this is only relevant though if the user is allowed to authenticate Site Kit, it should arguably not even be run otherwise, just like we're now no longer enqueueing the "minimal admin script" otherwise.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed AMP plugin and latest SK installed multiple modules.

Adjusted AMP settings from:

Standard, Transitional and Reader

![image](https://user-images.githubusercontent.com/57115907/84862138-79173a80-b027-11ea-8340-1119f2ea8ad8.png)

Navigated to wp-login
![image](https://user-images.githubusercontent.com/57115907/84862195-921feb80-b027-11ea-9592-f53e089eaad3.png)

Logged in successfully, and was able to log out properly each time. Unable to reproduce.

Passed QA ✅
