### ISSUE TITLE
Analytics Setup error: value is required.

### ISSUE THREAD

**Issue by phamquyhai** [google/site-kit-wp#1674]
## Bug Description

When first setup Analytics
get error

```
Site Kit encountered an error
value is required.


    in SetupMain
    in InnerComponent
    in WithFilters(BaseComponent)
    in div
    in div
    in div
    in section
    in div
    in div
    in div
    in div
    in SetupWrapper
    in Suspense
    in GoogleSitekitModule
    in RestoreSnapshots
    in ErrorHandler
    in Root
```

## Steps to reproduce

1. Settings
2. Analytics
3. Click 'continue module setup'
4. Get error: `value is required.`

## Screenshots

<img width="1253" alt="Screen Shot 2020-06-15 at 11 03 22" src="https://user-images.githubusercontent.com/1430683/84617026-f17ede00-aef7-11ea-859c-8442e005a8a2.png">

**Comment by jamesozzie** [comment]
@KaKaVip So we can troubleshoot this issue further can you provide the following information:
1. Your [Site Health information](https://i.imgur.com/Rtkmsba.png)
2. Any [console errors](https://imgur.com/KyLAzgH) that appear on the screen with the error

**Comment by felixarntz** [comment]
@tofumatt Could you have a look at this? Since we have the component where it occurs, _may_ be straightforward to see what's going wrong here.

**Comment by ernee** [comment]
similar error seen in #1651

**Comment by KaKaVip** [comment]
@jamesozzie 

1. My Site Health information
```
`
### wp-core ###

version: 5.4.2
site_language: vi
user_language: vi
timezone: Asia/Ho_Chi_Minh
permalink: /%postname%-%post_id%/
https_status: true
user_registration: 1
default_comment_status: open
multisite: false
user_count: 36
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /usr/local/lsws/deji.vn/html
wordpress_size: loading...
uploads_path: /usr/local/lsws/deji.vn/html/wp-content/uploads
uploads_size: loading...
themes_path: /usr/local/lsws/deji.vn/html/wp-content/themes
themes_size: loading...
plugins_path: /usr/local/lsws/deji.vn/html/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Flatsome Child (flatsome-child)
version: 3.0
author: UX Themes
author_website: (undefined)
parent_theme: Flatsome (flatsome)
theme_features: post-thumbnails, woocommerce, yoast-seo-breadcrumbs, title-tag, automatic-feed-links, customize-selective-refresh-widgets, sensei, html5, menus, post-formats, wc-product-gallery-zoom, wc-product-gallery-lightbox, widgets
theme_path: /usr/local/lsws/deji.vn/html/wp-content/themes/flatsome-child

### wp-parent-theme ###

name: Flatsome (flatsome)
version: 3.11.3
author: UX-Themes
author_website: http://www.uxthemes.com/
theme_path: /usr/local/lsws/deji.vn/html/wp-content/themes/flatsome

### wp-themes-inactive (4) ###

Twenty Nineteen: version: 1.6, author: Nhóm Phát Triển WordPress
Twenty Seventeen: version: 2.2, author: Nhóm Phát Triển WordPress (latest version: 2.3)
Twenty Sixteen: version: 2.1, author: Nhóm Phát Triển WordPress
Twenty Twenty: version: 1.4, author: Nhóm Phát Triển WordPress

### wp-plugins-active (31) ###

Additional Variation Images Gallery for WooCommerce: version: 1.1.41, author: Emran Ahmed
Booster Plus for WooCommerce: version: 5.0.0, author: Pluggabl LLC
Contact Form 7: version: 5.1.9, author: Takayuki Miyoshi
Facebook for WooCommerce: version: 1.11.4, author: Facebook
iThemes Security Pro: version: 5.5.8, author: iThemes
LiteSpeed Cache: version: 3.2.2, author: LiteSpeed Technologies
Loco Translate: version: 2.4.0, author: Tim Whitlock
Mailgun: version: 1.7.1, author: Mailgun
Nextend Social Login: version: 3.0.24, author: Nextendweb
Permalink Manager Pro: version: 2.2.8.6, author: Maciej Bis
reSmush.it Image Optimizer: version: 0.3.7, author: reSmush.it
Site Kit by Google: version: 1.9.0, author: Google
UpdraftPlus - Backup/Restore: version: 1.16.25, author: UpdraftPlus.Com, DavidAnderson
Variation Swatches for WooCommerce: version: 1.0.82, author: Emran Ahmed
Webcraftic Disable Admin Notices Individually: version: 1.1.1, author: Webcraftic <wordpress.webraftic@gmail.com>
WooCommerce: version: 4.2.0, author: Automattic
WooCommerce Admin: version: 1.2.4, author: WooCommerce
WooCommerce Alepay Gateway: version: 1.0, author: Cuongntk
WooCommerce Blocks: version: 2.7.0, author: Automattic
WooCommerce Email Customizer: version: 3.23, author: cxThemes (latest version: 3.33)
WooCommerce Google Analytics Integration: version: 1.4.22, author: WooCommerce
WooCommerce PayPal Checkout Gateway: version: 2.0.2, author: WooCommerce
WooCommerce Product Add-ons: version: 3.0.10, author: WooCommerce (latest version: 3.0.34)
Woocommerce Vietnam Checkout: version: 1.0.7, author: Le Van Toan
WooCommerce VTC Gateway: version: 2.0, author: toanld
WooSidebars: version: 1.4.5, author: WooCommerce
YITH WooCommerce Wishlist: version: 3.0.11, author: YITH
Yoast SEO: News: version: 12.4.1, author: Team Yoast
Yoast SEO: Video: version: 13.1, author: Team Yoast
Yoast SEO: WooCommerce: version: 13.2, author: Team Yoast
Yoast SEO Premium: version: 14.3, author: Team Yoast

### wp-plugins-inactive (1) ###

Easy Theme and Plugin Upgrades: version: 2.0.1, author: Chris Jean

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Không có sẵn
imagemagick_version: Không có sẵn
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 4.18.0-80.11.2.el8_0.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 7.3.12 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 300
memory_limit: 256M
max_input_time: 300
upload_max_size: 20M
php_post_max_size: 8M
curl_version: 7.61.1 OpenSSL/1.1.1
suhosin: false
imagick_availability: false
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.3.11-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /usr/local/lsws/deji.vn/html/wp-content
WP_PLUGIN_DIR: /usr/local/lsws/deji.vn/html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### google-site-kit ###

version: 1.9.0
php_version: 7.3.12
wp_version: 5.4.2
reference_url: https://deji.vn
amp_mode: no
site_status: connected-site
user_status: authenticated
active_modules: site-verification, search-console, analytics, pagespeed-insights
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
search_console_property: https://deji.vn/
analytics_account_id: none
analytics_property_id: none
analytics_profile_id: none
analytics_use_snippet: yes

`
```

2. console errors 
![Screen Shot 2020-06-16 at 09 17 21](https://user-images.githubusercontent.com/1430683/84724406-4e3ecf00-afb2-11ea-8bc1-08fa136727c8.png)

**Comment by ahegyes** [comment]
I've been having the exact same error for the past month or so. I'll paste the Site Health info here in case it will be useful to debug the issue: 

`
### wp-core ###

version: 5.4.2
site_language: de_DE
user_language: de_DE
timezone: Europe/Berlin
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 70
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /www/reparaturenprofisde_141/public
wordpress_size: 181,66 MB (190483547 bytes)
uploads_path: /www/reparaturenprofisde_141/public/wp-content/uploads
uploads_size: 366,32 MB (384116219 bytes)
themes_path: /www/reparaturenprofisde_141/public/wp-content/themes
themes_size: 3,73 MB (3915186 bytes)
plugins_path: /www/reparaturenprofisde_141/public/wp-content/plugins
plugins_size: 337,37 MB (353758575 bytes)
database_size: 532,00 MB (557842432 bytes)
total_size: 1,39 GB (1490115959 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: GeneratePress Child (generatepress_child)
version: 0.1
author: Tom Usborne
author_website: https://tomusborne.com
parent_theme: GeneratePress (generatepress)
theme_features: post-thumbnails, automatic-feed-links, post-formats, woocommerce, title-tag, html5, customize-selective-refresh-widgets, align-wide, responsive-embeds, custom-logo, menus, editor-style, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, editor-color-palette, widgets
theme_path: /www/reparaturenprofisde_141/public/wp-content/themes/generatepress_child

### wp-parent-theme ###

name: GeneratePress (generatepress)
version: 2.4.2
author: Tom Usborne
author_website: https://tomusborne.com
theme_path: /www/reparaturenprofisde_141/public/wp-content/themes/generatepress

### wp-themes-inactive (1) ###

Twenty Twenty: version: 1.4, author: WordPress-Team

### wp-mu-plugins (2) ###

DWS Custom Extensions: version: 2.2.3, author: Deep Web Solutions GmbH
Kinsta Must-use Plugins: version: 2.3.1, author: Kinsta Team

### wp-plugins-active (85) ###

AAM Plus Package: version: 5.4.2, author: Vasyl Martyniuk <vasyl@vasyltech.com>
Accordions by PickPlugins: version: 2.2.24, author: PickPlugins
Advanced Access Manager: version: 6.5.4, author: Vasyl Martyniuk <vasyl@vasyltech.com>
Advanced Custom Fields: ACF Code Field: version: 1.8, author: Peter Tasker
Advanced Custom Fields PRO: version: 5.8.12, author: Elliot Condon
Angell EYE Updater: version: 2.0.10, author: Angell EYE
Antispam Bee: version: 2.9.2, author: pluginkollektiv
Archived Post Status: version: 0.3.7, author: Frankie Jarrett
Business Reviews Bundle: version: 1.5.9, author: RichPlugins <support@richplugins.com>
Buttonizer - Smart Floating Action Button (Premium): version: 2.1.4, author: Buttonizer
Central Color Palette: version: 1.14.7, author: Daniel Menzies
CheckoutWC: version: 3.6.1, author: Objectiv (latest version: 3.6.2)
Code Snippets: version: 2.14.0, author: Code Snippets Pro
Complianz Privacy Suite (GDPR/CCPA) premium: version: 4.6.6, author: RogierLankhorst, Complianz
Ele Custom Skin: version: 2.2.2, author: Dudaster.com
Ele Custom Skin Pro: version: 2.1.0, author: Dudaster.com
Elementor: version: 2.9.12, author: Elementor.com
Elementor Pro: version: 2.10.2, author: Elementor.com
Enable Media Replace: version: 3.4.0, author: ShortPixel
Error Log Monitor Pro: version: 1.7.1, author: Janis Elsts
Essential Addons for Elementor: version: 4.0.3, author: WPDeveloper
Essential Addons for Elementor - Pro: version: 4.0.1, author: WPDeveloper
Express Login For WordPress: version: 1.4.1, author: StoreApps
FacetWP: version: 3.5.4, author: FacetWP, LLC (latest version: 3.5.6)
FacetWP - Elementor: version: 1.4, author: FacetWP, LLC
Follow-Up Emails: version: 4.9.0, author: WooCommerce (latest version: 4.9.2)
Font Awesome: version: 4.0.0-rc20, author: Font Awesome
Freshchat: version: 2.3.3, author: Freshchat
GenerateBlocks: version: 1.0.2, author: Tom Usborne
Germanized for WooCommerce: version: 3.1.9, author: vendidero
Germanized for WooCommerce Pro: version: 2.1.1, author: vendidero
GP Premium: version: 1.10.0, author: Tom Usborne
Gravity Forms: version: 2.4.18, author: Gravity Forms
GravityWP - CSS Selector: version: 1.0.1, author: GravityWP
Hotjar: version: 1.0.7, author: Hotjar
Intuitive Custom Post Order: version: 3.1.2, author: hijiri
Loco Translate: version: 2.4.0, author: Tim Whitlock
Login Designer: version: 1.2.4, author: Rich Tabor
MonsterInsights - Dimensions Addon: version: 1.3.0, author: MonsterInsights Team
MonsterInsights - eCommerce Addon: version: 7.3.5, author: MonsterInsights Team
MonsterInsights - EU Compliance: version: 1.1.0, author: MonsterInsights Team
MonsterInsights - Forms Tracking Addon: version: 1.5.0, author: MonsterInsights Team
MonsterInsights - Page Insights Addon: version: 1.3.0, author: MonsterInsights Team
MonsterInsights Pro: version: 7.10.5, author: MonsterInsights
Open External Links in a New Window: version: 1.4, author: WebFactory Ltd
PayPal for WooCommerce: version: 2.2.5, author: Angell EYE
PayPal IPN for WordPress: version: 2.1.5, author: Angell EYE
Perfmatters: version: 1.5.6, author: forgemedia
Pixel Caffeine: version: 2.1.3, author: AdEspresso
Pods - Custom Content Types and Fields: version: 2.7.20.1, author: Pods Framework Team
Popup Maker: version: 1.10.2, author: Popup Maker
Popup Maker - Remote Content: version: 1.1.4, author: WP Popup Maker
Real Category Management: version: 3.2.17, author: devowl.io
Redirection: version: 4.8, author: John Godley
Regenerate Thumbnails Advanced: version: 2.3.0, author: ShortPixel
SendCloud | Smart Shipping Service: version: 1.1.2, author: SendCloud B.V.
Shariff Wrapper: version: 4.6.5, author: Jan-Peter Lambeck & 3UU
Shop as Client for WooCommerce: version: 1.6.3, author: Webdados
Shop as Client for WooCommerce - PRO add-on: version: 1.6.3, author: Webdados
ShortPixel Image Optimizer: version: 4.19.2, author: ShortPixel
Simple Banner: version: 2.4.7, author: Ryan Petersen
Site Kit by Google: version: 1.9.0, author: Google
The SEO Framework: version: 4.0.7, author: The SEO Framework Team
The SEO Framework - Extension Manager: version: 2.4.0, author: The SEO Framework Team
User Switching: version: 1.5.4, author: John Blackbourn & contributors
Vendidero Helper: version: 1.3.0, author: Vendidero
Warranties and Returns for WooCommerce: version: 5.0.5, author: 7VX LLC, USA CA
WooCommerce: version: 4.0.1, author: Automattic (latest version: 4.2.0)
WooCommerce Admin Custom Order Fields: version: 1.13.3, author: SkyVerge (latest version: 1.13.4)
WooCommerce Checkout Field Editor: version: 1.5.31, author: WooCommerce (latest version: 1.5.34)
WooCommerce Composite Products: version: 6.2.2, author: SomewhereWarm (latest version: 7.0.2)
WooCommerce Freshdesk: version: 1.1.22, author: Automattic (latest version: 1.1.25)
WooCommerce Product Bundles: version: 6.2.3, author: SomewhereWarm (latest version: 6.2.5)
WooCommerce Sequential Order Numbers Pro: version: 1.15.2, author: SkyVerge (latest version: 1.15.3)
WooCommerce Stripe Gateway: version: 4.4.0, author: WooCommerce
WooCommerce Twilio SMS Notifications: version: 1.14.3, author: SkyVerge (latest version: 1.14.4)
WooRechnung: version: 2.0.15, author: Zweischneider GmbH & Co. KG
WordPress Backup & Security Plugin - BlogVault: version: 4.31, author: Backup by BlogVault
WP Activity Log: version: 4.1.0, author: WP White Security
WP Consent API: version: 1.0.1, author: RogierLankhorst
WP Crontrol: version: 1.8.5, author: John Blackbourn & crontributors
WP Mail Logging: version: 1.9.6, author: MailPoet
WP Mail SMTP: version: 2.1.1, author: WPForms
WP Real Media Library: version: 4.6.1, author: devowl.io GmbH
WP Rocket: version: 3.6.0.3, author: WP Media

### wp-plugins-inactive (1) ###

WP Sheet Editor - WooCommerce Products (Premium): version: 1.2.0, author: WP Sheet Editor

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1673
imagemagick_version: ImageMagick 6.8.9-9 Q16 x86_64 2018-09-28 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 236 GB
	imagick::RESOURCETYPE_DISK: 1.844674407371E+19
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 236 GB
	imagick::RESOURCETYPE_MEMORY: 118 GB
	imagick::RESOURCETYPE_THREAD: 12
gd_version: 2.2.5
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.3.0-1018-gcp x86_64
httpd_software: nginx/1.17.5
php_version: 7.4.0 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 300
memory_limit: 512M
max_input_time: 300
upload_max_size: 128M
php_post_max_size: 128M
curl_version: 7.47.0 OpenSSL/1.0.2g
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.4.6-MariaDB-1:10.4.6+maria~xenial
client_version: mysqlnd 7.4.0

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /www/reparaturenprofisde_141/public/wp-content
WP_PLUGIN_DIR: /www/reparaturenprofisde_141/public/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### google-site-kit ###

version: 1.9.0
php_version: 7.4.0
wp_version: 5.4.2
reference_url: https://www.reparaturen-profis.de
amp_mode: no
site_status: connected-site
user_status: authenticated
active_modules: site-verification, search-console, analytics, pagespeed-insights
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
search_console_property: sc-domain:reparaturen-profis.de
analytics_account_id: none
analytics_property_id: none
analytics_profile_id: none
analytics_use_snippet: yes

### wp_mail_smtp ###

version: 2.1.1
license_key_type: lite
debug: Keine Debug-Hinweise gefunden.

### pods ###

pods-server-software: nginx/1.17.5
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36 Edg/83.0.478.45
pods-session-save-path: /var/lib/php/sessions
pods-session-save-path-exists: No
pods-session-save-path-writable: No
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 69,857M
pods-memory-current-usage-real: 34,000M
pods-network-wide: No
pods-install-location: /www/reparaturenprofisde_141/public/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`

It might be worth mentioning that, in my case at least, it worked, then after a while I removed the Analytics integration, and now I can't reactivate it because of this error.

**Comment by jamesozzie** [comment]
Another reported issue: https://wordpress.org/support/topic/site-kit-encountered-an-error-4

**Comment by cole10up** [comment]
**Tested**

Ran through a series of tests setting up Analytics with latest develop build. Both with a clean site and a site with many many plugins. Unable to reproduce.

![image](https://user-images.githubusercontent.com/57115907/88142715-d7958280-cbaa-11ea-9a76-50a284c38c4b.png)

Sending back to L0 to confirm with members that this is still persistent.

**Comment by ahegyes** [comment]
I can confirm that the latest update, 1.12.0, fixed the problem (for me, at least) :)

**Comment by jamesozzie** [comment]
@phamquyhai Just following up with you on this issue. Can you confirm everything is working as expected form your side?

**Comment by phamquyhai** [comment]
@jamesozzie yes, This bug has been fixed
