### ISSUE TITLE
Show daily graph of page views per specific single URL view

### ISSUE THREAD

**Issue by djovanov** [google/site-kit-wp#1712]
## Feature Description

Hello,

It is great if the plugin have a feature like Monster Insight to show the last 30 days (or can chose less or more) google analytics page views graph on each post and on the wordpress post list. Like this : https://www.monsterinsights.com/addon/page-insights/

Thanks

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The single URL view should contain a daily graph of (Analytics) page views.

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
This issue bundles multiple requests which should rather be treated separately:
* Showing Site Kit metrics in the WordPress posts list is currently being tracked via #296.
* A daily chart for Analytics data per day (for the entire site) is already available on the "Analytics" module page which can be accessed from the Site Kit admin menu.
* There is no daily chart available right now on a per-post (or rather per-URL) level. I'll refocus this issue on that point, since for the other two items work has already been done or is being done elsewhere.

**Comment by tofumatt** [comment]
We don't currently have a daily view planned for date _ranges_, but I think this issue is looking for a daily graph of page views.

This issue predates redesigns of the dashboard, where we _do_ now show daily user counts:

https://github.com/google/site-kit-wp/assets/90871/2da83d1b-c47f-4b00-ac37-4cacc625aa31

We don't have plans to add page views for this chart though, so I'm going to close this issue as it's not currently something on our roadmap. 🙂
