### ISSUE TITLE
Analytics traffic sources chart and table should match Analytics-> acquisition -> overview

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1719]
## Bug Description

Related to https://github.com/google/site-kit-wp/issues/1554.

As reported in WordPress support forums CPC traffic is listed twice in the Analytics dashboard

Site Kit dashboard
![image](https://user-images.githubusercontent.com/41326532/86009694-6aab2480-ba12-11ea-92e6-37f54a70e785.png)

Analytics dashboard
![image](https://user-images.githubusercontent.com/41326532/86108114-abf70f00-baba-11ea-99d8-a209282b6934.png)

In one instance the CPC is capitalized. 

## Additional Context

 - Original Support Topic: https://wordpress.org/support/topic/sitekit-is-reporting-results-by-splits
 - Site URL and Site Health info shared via form
 - Unable to reproduce in support at present (with no sites available using cost per click traffic)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Site Kit Dashboard "All Traffic - How people found your site." chart and table should show the exact same entries (labels and values) as the chart displayed on the Analytics Acquisition Overview page.
* The Site Kit Analytics page's "Top acquisition sources over the last [X] days" chart should show the exact same entries (labels and values) as the chart displayed on the Analytics Acquisition Overview page.
* The chart label for the chart on the analytics page should read "Top acquisition channels over the last [X] days". [Channels](https://support.google.com/analytics/answer/6010097?hl=en&ref_topic=6010089) has a very specific meaning in Analytics vs "sources". Channels are groupings of sources like "Social" vs individual sources like "twitter" or "github".

#### Summary
We need to make two main changes to make the _chart and table shown in Site Kit exactly match_ the chart and table shown in Analytics->Acquisition->Overview:
* Change the dimension to channelGrouping to get the right data.
* Change to the Users vs. Sessions datapoint to match what Analytics shows by default in it's chart.
* Change plugin language to call this traffic "channels" vs "sources" throughout.

#### Details
* Adjust keys (2) in **`tests/e2e/specs/modules/analytics/fixtures/module-page.js`** from `ga:medium` to `ga:channelGrouping`.

* Ensure All traffic tables use the Users vs. Session data point (and relabel):
   * In **`assets/js/modules/analytics/dashboard/dashboard-alltraffic-widget-top-acquisition-sources-table.js:L58`** change 
`const totalSessions = data[ 0 ].data.totals[ 0 ].values[ 0 ];` to 
`const totalUsers = data[ 0 ].data.totals[ 0 ].values[ 1 ];`
and at L61 change
`const percent = ( row.metrics[ 0 ].values[ 0 ] / totalSessions * 100 );` to
`const percent = ( row.metrics[ 0 ].values[ 1 ] / totalUsers * 100 );`
   * Change the headers used for Top Acquisition Sources table  table:
In **`assets/js/modules/analytics/dashboard/dashboard-widget-top-acquisition-sources-table.js:L56`** change
```php
title: __( 'Medium', 'google-site-kit' ),
tooltip: __( 'Medium refers to where your traffic originated from', 'google-site-kit' ),
```
to
```php
title: __( 'Channel', 'google-site-kit' ),
tooltip: __( 'Channel refers to where your traffic originated from', 'google-site-kit' ),
```
   * Change the Top Acquisition Sources table percent calculation to use Users vs Sessions, matching chart.
At L78, change
`const totalSessions = data[ 0 ].data.totals[ 0 ].values[ 0 ];` to
`const totalUsers = data[ 0 ].data.totals[ 0 ].values[ 1 ];`

and @ L81 change
`const percent = ( row.metrics[ 0 ].values[ 0 ] / totalSessions * 100 );` to
`const percent = ( row.metrics[ 0 ].values[ 1 ] / totalUsers * 100 );`
   * Show all rows on the Top Acquisition Sources table even below 1%.
remove:
```php
// Exclude sources below 1%.
if ( 1 > percent ) {
	return false;
}
```

* Adjust the title for the Analytics Dashboard widget:
   * In **`assets/js/modules/analytics/dashboard/dashboard-widget.js:L231`** change
`title={ sprintf( __( 'Top acquisition sources over the last %s', 'google-site-kit' ), dateRange ) }` to
`title={ sprintf( __( 'Top acquisition channels over the last %s', 'google-site-kit' ), dateRange ) }`

* Ensure the chart calculations use the User datapoint (vs. Sessions):
   * In **`assets/js/modules/analytics/util/index.js:L48`** change
`const totalSessions = data.totals[ 0 ].values[ 0 ];` to
`const totalUsers = data.totals[ 0 ].values[ 1 ];`
   * At L54 change
```php 
const sessions = row.metrics[ 0 ].values[ 0 ];
const percent = ( sessions / totalSessions );

```
to
```php
const users = row.metrics[ 0 ].values[ 1 ];
const percent = ( users / totalUsers );
```
   * Don't exclude channels below 1%, remove
```php
// Exclude sources below 1%.
if ( 1 > ( percent * 100 ) ) {
	return false;
}

```
   * Remove the special handling for "direct" source. L57 change
`const source = row.dimensions[ 0 ].replace( /\(none\)/gi, 'direct' );` to 
`const source = row.dimensions[ 0 ];`
   * Change the data dimension, @ L407 change
`dimensions: 'ga:medium',` to
`dimensions: 'ga:channelGrouping',`
   * Adjust function comment for `trafficSourcesReportDataDefaults` to `Default data object for making Analytics traffic channels report requests.`

* Update the Analytics "provides" array, in **`includes/Modules/Analytics.php:L191`** change
`__( 'Top acquisition sources', 'google-site-kit' ),` to
`__( 'Top acquisition channels', 'google-site-kit' ),`

* Update the storybook story. In **`stories/module-analytics.stories.js:L239`** change
`title={ __( 'Top acquisition sources over the last 28 days', 'google-site-kit' ) }` to
`title={ __( 'Top acquisition channels over the last 28 days', 'google-site-kit' ) }`

* Adjust the wording used as the default for the Dialog component. In `assets/js/components/dialog.js:L48` change
`__( 'Top acquisition sources', 'google-site-kit' ),` to
`__( 'Top acquisition channels', 'google-site-kit' ),`

Note after the story update, reference images will need to be reviewed and accepted. `npm run test:visualtest` then `npm run test:visualapprove`
 

## QA Brief

* For QA we should review the issues reported in https://github.com/google/site-kit-wp/issues/1554 and verify these are also fixed by this change.

## Changelog entry

* Display correct labels for Analytics top acquisition channels by relying on `ga:channelGrouping` dimension.

**Comment by jamesozzie** [comment]
Along with the primary issue of double CPC entries the referral & social traffic seems combined in this dashboard (as with #1554)

**Comment by adamsilverstein** [comment]
@jamesozzie Thanks for reporting this issue and your assistance debugging it.

Reviewing your data and the requests we make to display this graph in Site Kit, I realized that we are using a different dimension than the dimension used to create the graph in Analytics (Under Acquisition->Overview).

Site Kit currently uses the `ga:medium` dimension.

Reviewing the Analytics UI in your screenshot, I noticed the chart is labeled "Top Channels"

Researching a bit further I discovered that switching to the `ga:channelGrouping` dimension yields the correct results (and "Channel" names) - exactly matching what I see in Site Kit and Analytics. 

Note: I tested altering Site Kit's query and noticed the [API response](https://gist.github.com/adamsilverstein/672e06450ab14952d32b4f09611cbc9a) includes three columns of data for each row of data: `Sessions`, `Users` and `New Users` - the 2nd value is the correct one to use for the chart (`Users`).

In addition to changing the data the chart shows, we should change the title for the chart: currently it reads "Top acquisition sources over the last {X} days.". "Top Channels over..." would better match what we show.

_Fixing this will also fix https://github.com/google/site-kit-wp/issues/1554 as they are closely related._

**Comment by felixarntz** [comment]
@adamsilverstein Sounds good, that's a great find! Can you add ACs and IB for this one based on the above?

I'll close #1554 as a duplicate.

**Comment by felixarntz** [comment]
@adamsilverstein The IB is very close to the code changes, so it's a bit hard to digest as is - for the future, no need to be as precise describing changes in specific lines etc... E.g. it's really hard to understand what changing `data[ 0 ].data.totals[ 0 ].values[ 0 ]` to `data[ 0 ].data.totals[ 0 ].values[ 1 ]` will do, what these values are, and why it's needed - better to approach more colloquially and explain a bit more instead.

Overall it looks on track though - would be great if you could take the PR on this as well since it seems like you already have the code pretty much figured out exactly 😄 

A few specific things:
* You mentioned `title={ sprintf( __( 'Top acquisition sources over the last %s', 'google-site-kit' ), dateRange ) }` should be changed, but afaict the changed value is the same?
* Let's adjust user-facing wording as little as possible. For example "Channel refers to the traffic source" should stay closer to the current wording, i.e. "Channel refers to where your traffic originated from".
* You mention "Ensure All traffic tables use the Users vs. Session data point (and relabel):" When you say datapoint you don't mean the API request has to be changed, or does it have to? If we need to change API requests, we should check this doesn't affect publisher wins (which rely on specific API requests to be made).

No need to update the entire IB to simplify, but would be great if you could explain a bit more the overall approach. Like e.g. why do we need to switch from sessions to users to fix this? That's not quite clear to me yet.

**Comment by adamsilverstein** [comment]
@felixarntz thanks for the review. I'll leave off the line number specifics in future IBs. On to some specific answers:

>A few specific things:

> You mentioned title={ sprintf( __( 'Top acquisition sources over the last %s', 'google-site-kit' ), dateRange ) } should be changed, but afaict the changed value is the same?

Corrected, this should say "channels" - the main reason to change these is that in Analytics "source" and "channel" are quite different, and this chart/table shows channels. By using the same word's as Analytics, we reduce confusion when users go between Site Kit and Analytics.

> Let's adjust user-facing wording as little as possible. For example "Channel refers to the traffic source" should stay closer to the current wording, i.e. "Channel refers to where your traffic originated from".

Good suggestion, agree we should minimize changes.


> You mention "Ensure All traffic tables use the Users vs. Session data point (and relabel):" When you say datapoint you don't mean the API request has to be changed, or does it have to? If we need to change API requests, we should check this doesn't affect publisher wins (which rely on specific API requests to be made).

We do not need to change our api request, we already request [three datapoints](https://github.com/google/site-kit-wp/blob/ea7879139d0e982377c425d6bfd513031074abbe/assets/js/modules/analytics/util/index.js#L411-L434) - Sessions, Users and New Users. The changes here are for the chart data (and the table "percent" column to use "Users" vs "Sessions" which is the column we use now. 

Here is the reasoning:

We are trying to match the chart (and table) shown in Analytics under Acquisition->Overview. Why that chart/data? Because it is the only chart analytics shows for traffic sources in it's UI. For my personal site, the last 28 this looks like this:

![image](https://user-images.githubusercontent.com/2676022/87822892-8cd4dd00-c82f-11ea-8bbd-4ec31c0e3488.png)

The numbers in this chart (the percentages) by default reflect the User column below (although users can click on the "New Users" and "Sessions" headers to change the chart data). In our data calls, the User column is the 2nd datapoint of each row. To make sure this is right, I verified these numbers in my testing for the IB and the API responses for the user column exactly match what I see in analytics.

>  Like e.g. why do we need to switch from sessions to users to fix this? 

Sorry should have made this clearer: essentially because Analytics uses Users by default and we want the chart users see in Site Kit to match.

**Comment by adamsilverstein** [comment]
@felixarntz I added a summary at the top of the IB to summarize the changes.

**Comment by felixarntz** [comment]
@adamsilverstein Thanks for clarifying!

> We do not need to change our api request, we already request [three datapoints](https://github.com/google/site-kit-wp/blob/ea7879139d0e982377c425d6bfd513031074abbe/assets/js/modules/analytics/util/index.js#L411-L434) - Sessions, Users and New Users. The changes here are for the chart data (and the table "percent" column to use "Users" vs "Sessions" which is the column we use now.

You're saying though that we'll need to change `ga:medium` to `ga:channelGrouping`, so that's where we need to change the API request. Looking at publisher wins, it looks like this request is not used though, so we should be good here.

IB ✅

**Comment by cole10up** [comment]
**Tested**

Confirmed though https://github.com/google/site-kit-wp/issues/1554 that we now are correctly splitting referral and social

Analytics:
![image](https://user-images.githubusercontent.com/57115907/88629284-e7f2a500-d063-11ea-8bda-84a347a5d91e.png)

SK:
![image](https://user-images.githubusercontent.com/57115907/88629318-f3de6700-d063-11ea-9e2c-0385a89f6526.png)

This is a match - Passed QA ✅
