### ISSUE TITLE
YouTube Integration

### ISSUE THREAD

**Issue by abazeed** [google/site-kit-wp#1720]
## Feature Description

Integrating YouTube into your plugin will be a great addition. Current plugins that allow users to upload videos directly to YouTube are buggy and poor of features.

It would be beneficial to allow users to:

- Upload videos directly to YouTube channels.
- Edit video details after uploading the video to YouTube.
- Control the thumbnail image of the video.
- Embed YouTube videos properly using a shortcode or a valid YouTube URL.
- Have a YouTube tab in the Media section where you can browse your channel videos and edit/upload videos from there.
- Integrate Google Analytics with YouTube videos to track the impressions and play metrics on the website.

Many ideas could be considered here, and more features could be added over time.

### What problems this feature solves

The main problems that this feature will solve are:

- Avoid the need to give editors direct access to the YouTube channels to upload and edit videos.
- Avoid using 3rd party plugins that request access to your Google account and YouTube channel. Google is a trusted party, and I would grant it the required access with my eyes closed.
- Manage YouTube assets naturally in WordPress and handle them like other media types (upload, edit, insert, ...).

### Who needs this feature

This feature is almost needed by all websites, especially the ones that rely on video content, like the news websites. Most websites have a YouTube channel, and the ones that are based on WordPress will find this feature very handy.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
Thanks for this feature request.

While Site Kit offers access to various Google services, it has the focus of guiding content creators to success, primarily based on metrics and insights and other recommendations. Integrating YouTube rather falls outside of this area, and while I agree some of the proposed changes would be beneficial, they would be better implemented separately from Site Kit since they would not benefit from the infrastructure Site Kit offers.

In addition, some of the problems outlined would remain even if YouTube upload was managed in WordPress, for example users would per definition still need to have access to the relevant YouTube account and upload permissions, otherwise WordPress wouldn't be able to upload the videos either. This leads to the second problem which is that, even with Google being 1st party in relation to YouTube, the WordPress site would not be as it still lies outside of Google's infrastructure.
