### ISSUE TITLE
Make profile data retrieval more reliable

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1731]
## Bug Description

After signing in with Google, specifically right after Site Kit obtains an access token for a user, the user's Google profile data is fetched via the People API. The email address and photo are then stored in WordPress, and they are used in various places, e.g. the user dropdown on the top right of all Site Kit screens.

There can be occasional cases where this API request fails temporarily, for example due to quotas being exceeded etc. While we're investigating how to make this more reliable, we should implement a mechanism in Site Kit that retries such failed requests.

At the moment we don't have anything like that, the request just silently fails. And it should still silently fail (it shouldn't cause a user-facing error during setup), but it should retry periodically. The profile data wasn't as crucial so far (since the user dropdown would just fall back to showing WordPress user data), but now with deep links to Google frontends making use of the email address (parts of the AdSense and Analytics module already have these, others will be covered by #1456) profile data is becoming a lot more relevant.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If fetching Google profile data for a user after getting a new access token fails, the request to fetch this data and store it should be retried periodically:
    * For the very first one, it should be retried quickly, after only 2 minutes.
    * If that one failed too, it should be retried every 30 minutes.
* As soon as the request succeeds, it should no longer be retried.
* The request to retry should (of course) only be attempted if the user is actually authenticated (i.e. not if they e.g. disconnected in the meantime).

## Implementation Brief

* In `OAuth_Client::refresh_profile_data()`:
    * Add optional method parameter `$retry_after = 0`.
    * In the `catch` clause, if `$retry_after` is greater than 0, schedule a `googlesitekit_cron_refresh_profile_data` event, providing the `$user_id` from the `User_Options` instance as an argument, for `time() + $retry_after` using [`wp_schedule_single_event`](https://developer.wordpress.org/reference/functions/wp_schedule_single_event/). 
    * Make method public.
* In `OAuth_Client::authorize_user()`:
    * Pass parameter value `2 * MINUTE_IN_SECONDS` to the `refresh_profile_data` call.
* Introduce public method `Authentication::cron_refresh_profile_data( $user_id )` and hook into onto the cron action `googlesitekit_cron_refresh_profile_data`:
    * Switch the `User_Options` instance user to the user identified by `$user_id`, storing the original user in a variable.
    * Bail early if the user is not authenticated.
    * Otherwise call `OAuth_Client::refresh_profile_data( 30 * MINUTE_IN_SECONDS )`.
    * In either case, restore the original user in `User_Options` (this shouldn't be necessary since the cron request will likely terminate after, and the current user is probably 0, but a good practice to clean up after ourselves).

## QA Brief

* 

## Changelog entry

* Improve Google profile data lookup to retry periodically if it temporarily fails.

**Comment by aaemnnosttv** [comment]
The IB looks good and should work.

One alternative that I would propose for consideration would be to use a scheduled event/cron to do the refreshing rather than checking for this on every `admin_init`. One benefit of this approach would be that we wouldn't need to store the retry time as that is already a requirement for a scheduled event.

It could work something like this:
* If fetching profile data fails when authorizing the user, schedule a `refresh_profile_data` event, providing the `$user_id` as an argument for `time() + 2 * MINUTE_IN_SECONDS` using [`wp_schedule_single_event`](https://developer.wordpress.org/reference/functions/wp_schedule_single_event/).   
* In the refresh job handler, it would instantiate `Authentication` with a fresh `User_Options` set to the given user's ID to not affect other instances using `User_Options` by calling `switch_user` on a the shared primary instance
* It would then call `OAuth_Client::refresh_profile_data()`  
As an alternative to changing method visibility, `refresh_profile_data` could stay private and be hooked onto an action using a closure and which the refresh job handler would fire
* In the handler, after `refresh_profile_data` is called:
    * If `! Profile->has()` it would reschedule the same event for `time() + 30 * MINUTE_IN_SECONDS` with the same args
    * If `Profile->has()` it would finish without scheduling another event

All of the same checks for user permission and authenticated status would still be used, but we wouldn't need to add an additional user option for retry time or add a `should_refresh_profile_data` method. The job handler could get its own class and would likely only have a `register` method (perhaps also a `handle`).

Like I said, I think the original IB here will work as well and the above is just an alternative for consideration which is a bit of a tradeoff, but offers a bit more encapsulation and requires less public code to be exposed.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> * If fetching profile data fails when authorizing the user, schedule a `refresh_profile_data` event, providing the `$user_id` as an argument for `time() + 2 * MINUTE_IN_SECONDS` using [`wp_schedule_single_event`](https://developer.wordpress.org/reference/functions/wp_schedule_single_event/).

👍  That sounds like a cleaner approach, I didn't have `wp_schedule_single_event` in mind - a regular cron event would be unsuitable, but this should work well!

> * In the refresh job handler, it would instantiate `Authentication` with a fresh `User_Options` set to the given user's ID to not affect other instances using `User_Options` by calling `switch_user` on a the shared primary instance

I don't think this should be an issue? As far as I'm aware WP cron runs in isolation from the main request, it's just (by default) triggered through a user-initiated request.

I'll update the IB.

**Comment by aaemnnosttv** [comment]
> I don't think this should be an issue? As far as I'm aware WP cron runs in isolation from the main request, it's just (by default) triggered through a user-initiated request.

It's not so much about contamination with the main process as that wouldn't be possible but between crons if/when we add another.

I suppose we don't need to use separate dependencies for these kinds of handlers as long as we always set the user ID in them.

**Comment by aaemnnosttv** [comment]
@felixarntz there was one reference to the old IB that I removed but otherwise looks great.

![image](https://user-images.githubusercontent.com/1621608/86890298-c3ab4480-c105-11ea-920c-7c45a8491a84.png)

This still needs an estimate so I'll add that, but IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed latest SiteKit develop zip.

Ran a series of tests around token expirations during auth flow. Unable to reproduce the issue.

Regressing profile connecting and disconnecting functioned properly

Passed QA ✅
