### ISSUE TITLE
Data error in search console

### ISSUE THREAD

**Issue by flexzydonald** [google/site-kit-wp#1741]
Permissions issue accessing data
This account does not have access to the requested data.

User does not have sufficient permission for site 'https://nigeriaschoolnews.com.ng/'. See also: https://support.google.com/webmasters/answer/2451999. I just started seeing this recently, what does it mean and how can it be fixed?

![9224624A-A4F8-401D-A4A2-77B7C7E2777C](https://user-images.githubusercontent.com/67808636/86500173-38d5ed00-bd87-11ea-8539-2e67c7d7079e.png)

**Comment by jamesozzie** [comment]
@flexzydonald Thanks for getting in touch. Initial support requests can be submitted using the plugins WordPress support forum. 

If you open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there while providing your [Site Health information](https://i.imgur.com/Rtkmsba.png) we can try and determine the root cause in your case, while revisiting this GitHub issue if necessary. 

If you happen to see any console errors similar to the below please also check your hosting control panel for any Firewall restrictions and include such information in the support topic. 
![image](https://user-images.githubusercontent.com/41326532/86782098-99e71480-c056-11ea-8818-fbaed32e0dd4.png)
