### ISSUE TITLE
Couldn't create project

### ISSUE THREAD

**Issue by laith81233** [google/site-kit-wp#1756]
I am facing this problem
Couldn't create project

field [project_id] has issue [project_id contains invalid characters]

How can it be solved ?

I use
WordPress the latest version
And hosting fromfastcomet
url : https://tectaw.com/

**Comment by jamesozzie** [comment]
@laith81233 Thanks for getting in touch. Initial support requests can be submitted using the plugins WordPress support forum.

Please open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) while providing your [Site Health information](https://i.imgur.com/Rtkmsba.png). We can try and determine the root cause in your case, while revisiting this GitHub issue if necessary. You can share your Site Health information privately if preferred using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/).
