### ISSUE TITLE
Site kit stopped working

### ISSUE THREAD

**Issue by enderax** [google/site-kit-wp#1757]
## Bug Description

After updating to 1.11.1 version, Site Kit has stopped working. When I click Site Kit on the left side of Wordpress panel, I only see blank screen. Disabling it then enabling didn't help. 

## Steps to reproduce

1. Go to Plugins and update Site kit to 1.11.1
2. Click on Site Kit on the left side of Wordpress panel
3. See blank screen. 
4. Open Developer tools console if you want to see errors

## Screenshots

<img width="1073" alt="Site Kit by Google Analytics ‹ GezEnder — WordPress 2020-07-10 12-45-11(1)" src="https://user-images.githubusercontent.com/9071412/87141961-7d441a00-c2ac-11ea-987f-17e2e6741911.png">
<img width="1268" alt="Site Kit by Google Analytics ‹ GezEnder — WordPress 2020-07-10 12-44-37" src="https://user-images.githubusercontent.com/9071412/87141974-8208ce00-c2ac-11ea-8a85-ac0ca9152a6f.png">

## Additional Context

 - PHP Version: 7.0.33
 - WP Version: 5.4.2
 - OS: Ubuntu
 - Browser: Chrome latest
 - Plugin Version [e.g. 22] : 1.11.1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@enderax It looks like you've encountered the same issue as described in a [related GitHub issue, #1054](https://github.com/google/site-kit-wp/issues/1054). Please try clear your browsers cache and purge your CDN if active.

If that fails to resolve the issue feel free to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there while providing your [Site Health information](https://i.imgur.com/Rtkmsba.png). We can try and determine the root cause in your case, while revisiting this GitHub issue if necessary.
