### ISSUE TITLE
Update @material packages to their latest versions

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1771]
## Feature Description

All `@material/*` dependencies should be updated to their latest versions. Apparently there have been several changes in their behavior, so this should be tested with care.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All `@material/*` dependencies should be updated to their latest versions.
* There should be no errors or visual regressions on Site Kit UI.

## Implementation Brief

 

- Install the latest versions of all @material/* packages. For e.g @material/button should be updated from 2.3.0 to 7.0.0
- Run `npm run test:visualtest` to check for any visual regressions.
- In case regressions have been introduced, update the plugin's [CSS](https://github.com/google/site-kit-wp/tree/develop/assets/sass) to fix them.

## QA Brief

 

- There should not be any visual regressions
- VRT should pass.

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@asvinb The IB looks good for the most part and this issue will hopefully be fairly straightforward, but we need to be fairly thorough to check for potential regressions in _behavior_ as well; not just visual/stylistic changes.

It might be a good idea to add one big story for rendering all the material components (and adding it as a backstop scenario) as the first step here to help test this and then compare before/after side-by-side.

Especially since some of these upgrades (if not all) will span multiple major versions, we should note any relevant breaking changes referenced in the changelogs (perhaps in a `<details>` tag). I think including this information on this issue here would be good to do ahead of time as it will help inform the amount of effort as well as where extra attention is needed.

**Comment by aaemnnosttv** [comment]
> don't existing Backstop scenarios not cater for all material components? I'am just thinking about why we need to have one big story with all the material components instead of leaving them how they are right now and let Backstop test everything?

That's a good question and generally speaking, yes Backstop should cover that, but the truth is we may have blindspots in our coverage since refactored components haven't been added to the VRT suite and some of the legacy scenarios have been removed.

So to your point, I think we need to do a little bit of research here to see _if_ there are any components that are not currently covered by our backstop scenarios, and if not those should be added before upgrading. Can you spend some time to look into this as part of the IB?

> Also, when you say we need to test the "behaviour" as well, will the existing backstop scenarios handle that? If not, we'll need to define the behaviour of each component and the write scenarios for each of them.

No, Backstop only covers visual regression; no behavior. For this, we should have pretty good coverage with Jest + E2E so I'm less worried in missing something there. I don't think we should go crazy unit testing 3rd party components that we use so my point was more about making sure we consider all the implications of upgrading the components. The IB can defer to the existing tests in this regard, but even though there's no additions/removals of test coverage, I think it's important to document the thought process around it.

**Comment by felixarntz** [comment]
Moving this to _Stalled_ for now; let's revisit later when we have some extra capacity, since this doesn't seem as trivial as we first thought.

**Comment by felixarntz** [comment]
Closing this as invalid now, since it's not worth working on given our upcoming migration to Material 3 (and the `@material/web` package).
