### ISSUE TITLE
Update focus-trap-react to the latest version and fix compatibility issues

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#1798]
## Feature Description

After upgrading focus-trap-react to the latest version, we faced with compatibility issue mentioned here: https://github.com/google/site-kit-wp/pull/1735#issuecomment-657717422. We need to update it to the latest version and fix that error.

![87339271-0aa69900-c54f-11ea-89fc-70b321c29b99](https://user-images.githubusercontent.com/873049/87703422-83059800-c7a3-11ea-8f69-7e3f3dd35a09.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The version of `focus-trap-react` package used in the plugin should be upgraded to the latest major version (10.0 as of writing, but might be higher in the future)
* Any errors encountered after the upgrade should be fixed.
  * It seems like the existing error mentioned in the screenshot here is from trying to focus-trap inside an element that is conditionally rendered or similar; this behaviour should be changed so the error is not encountered.

## Implementation Brief
* Update the `focus-trap-react` package to the latest version. (10.0.0 at the time of writing)
* Using `assets/js/components/Dialog.js`,
	* Add the `focusTrapOptions` prop to `FocusTrap` with the value set to the following object:
	```js
	{
		tabbableOptions: {
			displayCheck: 'legacy-full',
		},
	}
	```
	* Refer to https://github.com/focus-trap/tabbable/pull/764

## QA Brief
* Check that all modal dialogs render correctly, without any JS errors. For e.g for dashboard sharing settings, resetting SiteKit, asking for additional permissions, etc

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by mohitwp** [comment]
QA Update ✅ 

- Verified on develop environment.
- Verified dashboard sharing settings modal.
- TwG modal for additional permissions.
- GA4 Modal for additional permissions.
- Disconnect and Reset Site Kit Modal.
- All modals are rendering without any JS error.

**Note** : I've noticed that user role having view permission is not able to see widgets on dashboard and getting console error. Admin role user able to access widgets under view only dashboard.
This issue is related to https://github.com/google/site-kit-wp/issues/5772 https://github.com/google/site-kit-wp/issues/5772#issuecomment-1266890649 and will get resolve in related PR.
