### ISSUE TITLE
Improve error message for insufficient Google service permissions

### ISSUE THREAD

**Issue by ThierryA** [google/site-kit-wp#1824]
## Feature Description

The current message displayed in a module for which a user doesn't have access to the given Google Service isn't really informative. We should clearly explain why it is as such and ideally give clear instruction on how to gain access (for example, who to reach out to which #1714 would make possible)

Current examples:
![Screenshot 2020-07-27 at 10 41 33](https://user-images.githubusercontent.com/3531426/88575108-336f6980-cff8-11ea-9054-c99cc130656e.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Error messages for missing permissions errors being returned from Google APIs (`error.data.reason` is `'insufficientPermissions'`) should inform the user on how to possibly resolve the issue:
     * If the current user can `list_users` (WordPress capability), the message should include the username of the module owner (see #1743) as point of reference.
    * Otherwise, it should instead refer to just "an administrator".
* Messages:
_Heading: Insufficient permissions in {moduleName}_
_Description: Your Google account does not have sufficient permissions for this {moduleName} account/property/view, so you won't be able to see stats from it on the Site Kit dashboard. This service was originally connected by {user} — you can contact them for more information._
    * `{moduleName}`: The module name (e.g. _Search Console_, _Analytics_)
    * `{user}`: Either _the administrator "xyz"_ (with username of module owner) or _an administrator_
    * To get the specific entity type, the error message should be inspected (they are not translated, so this is acceptable). The following specific entities should be supported:
        * For Search Console "this site" --> "this Search Console property"
        * For Analytics, "this account" / "this property" / "this profile" --> "this Analytics account/property/view"
        * Otherwise, the first sentence of the message should be altered to _Your Google account does not have sufficient permissions to access {moduleName} data._

## Implementation Brief

* Create an `isInsufficientPermissionsError(error)` function that checks `errorObj?.data?.reason === 'insufficientPermissions'`.
* Create an `getInsufficientPermissionsErrorDescription(error, moduleName)` function used to check an `errorObj` object (like the one found in https://github.com/google/site-kit-wp/blob/develop/assets/js/components/notifications/data-error.js#L49 or https://github.com/google/site-kit-wp/blob/517becda04242fc42b4a207bc9458b48 8f05cbe2/assets/js/components/StoreErrorNotice.js#L33) for `isInsufficientPermissionsError(errorObj)`. If it matches, return a modified error with an updated message:
* Use the contents of `errorObj?.message` to determine the entity type:
  * If it matches `/account/`, `/property/`, or `/view/`, for Analytics, use the correct string for the entity type. (eg "this Analytics account", "this Analytics view", etc.).
  * If it matches `/this site/`, use "this Search Console property" as the error message
  * If no match was found, use the message "_Your Google account does not have sufficient permissions to access {moduleName} data._"

#### For "old" code:
* Check `isInsufficientPermissionsError(error)` and, if true, use  `getInsufficientPermissionsErrorDescription(errorObj, moduleName)` in https://github.com/google/site-kit-wp/blob/develop/assets/js/components/notifications/data-error.js#L49 and display an alternate title/error message (see the "heading" and "description" mentioned in the AC).

#### For "new" code that is using the data store:
* Check `isInsufficientPermissionsError(error)` and, if true, use `getInsufficientPermissionsErrorDescription(error, moduleName)` in `StoreErrorNotice` and change the error displayed to match the one in the AC.
* In order to check for the `list_users` capability in JS, we'll want to add `list_users` to the capabilities map created in the [`Permissions` PHP class on the `googlesitekit_user_data` filter](https://github.com/google/site-kit-wp/blob/517becda04242fc42b4a207bc9458b488f05cbe2/includes/Core/Permissions/Permissions.php#L161-L181). Then use `select( 'core/user' ).hasCapability( 'list_users' )` to check if we can show the admin's info (using `getOwnerID()` from #1743).

**Note: do not use an approach like `"this {moduleName} {entityType}"` as it creates translation issues. Use a unique string for each error, leaving only the module name to be interpolated.** (See: https://github.com/google/site-kit-wp/issues/1824#issuecomment-682091334), eg: 

```js
__( 'Your Google account does not have sufficient permissions for this %1$s property, so you won't be able to see stats from it on the Site Kit dashboard. This service was originally connected by %s — you can contact them for more information' )
```

where `%1$s` is the module name and `%2$s` is the user account, if available.

## QA Brief

1. Use a Site Kit install with a Google Account that is authorised to use the site. Activate all modules.
2. Have a second WordPress user (with the `admin` role) sign into Site Kit with a separate Google Account that does _not_ have access to the first account's Google Services
3. Observer specific errors mentioned above, including the first user (owner)'s info in the error message
4. ~Repeat steps 2 + 3 with a non-admin user, and observe a generic error message because they can't list user info.~

## Changelog entry

* For API errors about missing Google service permissions, clarify based on module ownership who to contact for more information.

**Comment by felixarntz** [comment]
@tofumatt I think we should expand the IB to also cover our refactored codebase. Otherwise we'll need to "re-fix" this once everything has been migrated away from the old APIs:
* We could build the same logic into the `StoreErrorNotice` which is used throughout the modules.
* Like we already have a `isPermissionScopeError` utility function, we could introduce another `isInsufficientPermissionsError` utility function. If yes, we would alter the message to display a message defined per the ACs.
* The `StoreErrorNotice` component could require the module's `slug` as additional prop, in order to look up the module name from `core/modules` store.

> In order to check for the `list_users` capability in JS, we'll want to use the selector: `wp.data.select('core').canUser('read', 'users')`. To do this we'll need to add `@wordpress/core-data` to our dependencies and load that data store. Given a lot of components can run into this error, it likely makes sense to load it all of the time.

I wonder if that's really worth bundling that dependency, especially given that it also ships with WordPress core and it's just this functionality. I think for now a simpler solution would be to add `list_users` to the capabilities map created in the `Permissions` PHP class on the `googlesitekit_user_data` filter. This way we can rely on our existing `googlesitekit.data.select( 'core/user' ).hasCapability( 'list_users' )`.

**Comment by tofumatt** [comment]
> I wonder if that's really worth bundling that dependency, especially given that it also ships with WordPress core and it's just this functionality. I think for now a simpler solution would be to add `list_users` to the capabilities map created in the `Permissions` PHP class on the `googlesitekit_user_data` filter. This way we can rely on our existing `googlesitekit.data.select( 'core/user' ).hasCapability( 'list_users' )`.

Ah, that's a fair point. I was wondering if we might want other `core/data` functionality going forward, but let's cross that bridge when we come to it. For now, adding that one capability to the `core/user` store seems reasonable 👍 

----

Regarding adding this to the "new" components: works for me. I tried to focus on the older code first as it's the more cumbersome to work with, but adding this functionality to the `StoreErrorNotice` should be straightforward. I'll update the IB.

**Comment by felixarntz** [comment]
@tofumatt IB mostly LGTM, just one feedback item:

`isInsufficientPermissionsError` sounds like it should return a boolean. For that itself, the function wouldn't require the module name, that could simply be known by looking at `error.data.reason` and whether it's `'insufficientPermissions'`. If the goal is to return the specific error description to display from that function, I'd rather say this could happen in something like `getInsufficientPermissionsErrorDescription( error, moduleName )`.

Another side note, keep in mind the translation string variants using different terms like "property" or "view" need to be entirely different strings and cannot be concatenated or interpolated, otherwise they won't be translation-ready. The only part that's okay to add in via `sprintf` is the module name.

**Comment by tofumatt** [comment]
Good point on the `isInsufficientPermissionsError` naming. I've updated it to be the boolean check and added `getInsufficientPermissionsErrorDescription` as the function to get a modified error. I think it's better to do that in a function than in each component, so we have a singular place for that logic.

Re: translation strings interpolating—I'm not sure I understand why we can't have "this {moduleName} {propertyName}" for Analytics + Profile/Property/View. That would result in "this Analytics View", which seems fine to me. If they should be entirely custom strings that's fine but I'm not clear why that is.

**Comment by felixarntz** [comment]
> Re: translation strings interpolating—I'm not sure I understand why we can't have "this {moduleName} {propertyName}" for Analytics + Profile/Property/View. That would result in "this Analytics View", which seems fine to me. If they should be entirely custom strings that's fine but I'm not clear why that is.

The only thing that should ever be interpolated in translation strings is names, numbers or similar. Things like "property" or "account" are regular words though, so that doesn't apply. For example, translating to German:

* "this Analytics account" -> "dieses Analytics-Konto"
* "this Analytics view" -> "diese Analytics-Ansicht" (see how the first word is different here; this wouldn't be possible if we interpolated `propertyName`)

Denominator translations rely on knowing which noun they're for, which is why we'll need entirely separate translation strings. Generally, with translation strings it's always better to duplicate even with minimal differences, otherwise it easily becomes "too clever".

**Comment by tofumatt** [comment]
Sounds good! I've made an explicit note to make sure we use separate strings for each "entity name".

**Comment by felixarntz** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
This is ready for code review. Added a few notes to the "relevant technical choices" section. The most important one is that we can't rely on the standard REST API endpoint for users because it can be modifed or disabled by site developers or 3rd party plugins. Thus we don't need to check `list_users` capability and need to provide owner display name as part of module information.

**Comment by felixarntz** [comment]
@eugene-manuilov We'll need awareness of whether the current user can `list_users` not for technical reasons but because a the owner user data shouldn't be exposed otherwise. See my PR review for more context.

**Comment by tofumatt** [comment]
QA kind of okay…

With an admin user it works as expected:

<img width="615" alt="Screenshot 2020-09-10 at 14 45 33" src="https://user-images.githubusercontent.com/90871/92738964-5372a680-f374-11ea-948c-0f277202adfa.png">

But I can’t get a user with the “Editor” role to view Site Kit. A new user with non-Admin role can’t access the Site Kit dashboard at all, but converting an Admin to an Editor and then accessing Site Kit gives me stack traces:

<img width="1096" alt="Screenshot 2020-09-10 at 15 06 29" src="https://user-images.githubusercontent.com/90871/92742125-3c818380-f377-11ea-81ec-f398d3feec6e.png">

**Comment by tofumatt** [comment]
Update: I shouldn't have added non-admins to the QA brief since they don't _yet_ work.

So QA ✅, with the caveat that only admin users were tested thus far.
