### ISSUE TITLE
Improve reset message by clearly informing the ramification

### ISSUE THREAD

**Issue by ThierryA** [google/site-kit-wp#1825]
## Feature Description

Currently the reset modal message doesn't clear explain the side effects of the action, specifically the ramification for other users. We should explicitly list the effect of reseting the plugin (erase setup, kick out all users etc.). I would vote to go the extra mile and add a confirmation mechanism (field or checkbox) to ensure the user reseting the plugin understands the side effects, we which case we might create a separate issue for.

Current message:
![Screenshot 2020-07-23 at 10 51 01](https://user-images.githubusercontent.com/3531426/88320437-6fda5700-ccd2-11ea-9f30-2e5db7052f8a.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The dialog shown for resetting Site Kit should use a similar format to module deactivation with a message including a list of results that will happen as a result.

* Heading: _Reset Site Kit_ (no change)
* Body:  
> Resetting will disconnect all users and remove all Site Kit settings and data within WordPress.
> You and any other users who wish to use Site Kit will need to reconnect to restore access.

## Implementation Brief

* Update `ResetButton` component:
  * Change `subtitle` property for the `Dialog` component to be the one from the ACs.

## QA Brief

* Go to Site Kit->Settings->Admin Settings and click the Reset Site Kit button to trigger the modal.
* Confirm text changes.

## Changelog entry

* Update the Reset Site Kit dialog message to be more clear.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz @ThierryA regarding the wording of the message, to me it sounds to be describing a _disconnect_ for all users rather than a full reset. We should make it clear that all configuration will also be lost/deleted and that Site Kit will essentially be restored to a clean slate. We should be careful to word it in a way that conveys that no access is changed _at the service level_ but only user's access via Site Kit is removed.

Perhaps something like this?
> Resetting will restore Site Kit back to its initial un-configured state and all of its settings and data within WordPress will be removed. If you choose to proceed, Site Kit will need to be reconfigured before data in WordPress will be available again. You and any other users who wish to use Site Kit will also need to reconnect with Site Kit to restore access.

**Comment by ThierryA** [comment]
+1 on being more specific

> You and any other users who wish to use Site Kit will also need to reconnect with Site Kit to restore access.

I would change the last sentence with "You and all other users will loose access to all services, everyone will need to reconnect to Site Kit to restore access.

**Comment by aaemnnosttv** [comment]
@ThierryA I think we should be careful with the wording of "will lose access to all services" so that people don't understand this to mean anything will change outside of WordPress or the Site Kit service.

It should also read the way that if someone wants to uninstall Site Kit that this is a reasonable, safe action to take.

Maybe it would be a bit more clear to use a format similar to module deactivation where it lists what will happen?

E.g.
> **By resetting Site Kit you will:**
> * Deactivate all service modules (perhaps even list out all active modules?)
>    - Analytics
>    - Tag Manager
> * Disconnect all users
> * Remove all plugin and module configuration
> * Remove all authentication with Google APIs via Site Kit

**Comment by ThierryA** [comment]
> @ThierryA I think we should be careful with the wording of "will lose access to all services" so that people don't understand this to mean anything will change outside of WordPress or the Site Kit service.

Good point, disconnect is a better way of saying it for sure.

Yes listing is a better format IMO.

**Comment by aaemnnosttv** [comment]
@ThierryA I've updated the ACs per our conversation here and moved the issue back to AC to reflect this as these changes will require redefinition as well as updates the the PR. Let me know if you think anything should change, otherwise this can move on to IB 🙂

**Comment by ThierryA** [comment]
Let's have @marrrmarrr review is as she originally wrote the ACs.

**Comment by marrrmarrr** [comment]
Thanks @aaemnnosttv for the suggestions! The message is a lot more specific now. 
I suggest we strike a balance b/w specificity and brevity, since the modal will become quite sizeable with the current text. 

A shortened version:
_Resetting will restore Site Kit back to its initial un-configured state and all of its settings and data within WordPress will be removed. You and any other users who wish to use Site Kit will also need to reconnect with Site Kit to restore access._

_By resetting Site Kit you will do the following:_
Deactivate and reset all service modules: (list the name of each active module as sub-list items)_
_Disconnect all users from Google APIs via Site Kit_
_Remove all Site Kit plugin, service module, and user settings_

**Comment by aaemnnosttv** [comment]
This looks good to me @marrrmarrr – just a few questions and findings:

> Deactivate and reset all service modules: (list the name of each active module as sub-list items)

Since this item no longer appears to be formatted as a bulleted list, would it simply be a comma-separated list instead?

Making a quick prototype in the browser, it looks like some of these lines will be cut off due to the length:

![image](https://user-images.githubusercontent.com/1621608/93621807-c61efa00-f9e4-11ea-93f4-fd81efd99e32.png)

Looks like we may need to rethink this a little bit as we also need to allow room or otherwise account for varying line length which will happen when translated.

One solution which seems a bit safer than just using less words would be to allow the lines to wrap, we'd need to update the styles a bit more though because it seems that each item has a fixed height as it is.
![image](https://user-images.githubusercontent.com/1621608/93622619-1d719a00-f9e6-11ea-83a0-8d600aa1c55d.png)

As a reference to something we currently use, here is what module deactivation looks like which includes a "Note" at the bottom where the multiple dependent module names are listed:

![image](https://user-images.githubusercontent.com/1621608/93622933-9a9d0f00-f9e6-11ea-8a85-bb1a8980505d.png)

Perhaps something like this?

![image](https://user-images.githubusercontent.com/1621608/93623350-46465f00-f9e7-11ea-9a63-94b01d5268ca.png)

What do you think?

**Comment by marrrmarrr** [comment]
@aaemnnosttv @felixarntz Going back to the initial reason we started this discussion, the intention was to clarify to the specific admin user that their action here will affect all other users. 
To simplify this screen and shorten the text, let's focus on that. 

"Resetting will disconnect all users and remove all Site Kit settings and data within WordPress. /n
You and any other users who wish to use Site Kit will need to reconnect to restore access."

**Comment by aaemnnosttv** [comment]
Much better @marrrmarrr 👍 

IB ✅

**Comment by cole10up** [comment]
**Tested**

Installed, activated and setup latest develop SK. 

Reset SK:
![image](https://user-images.githubusercontent.com/57115907/95294545-4f7a5d00-082a-11eb-87e1-ef990cf59634.png)

Confirmed content. Checked reset functionality and cancel button as well as look and feel across browsers.

**Question:** @marrrmarrr - I see you have the following copy, looking like a new line after 'WordPress" I don't see that above. Should we send this back to adjust?

"Resetting will disconnect all users and remove all Site Kit settings and data within WordPress. /n
You and any other users who wish to use Site Kit will need to reconnect to restore access."

**Comment by felixarntz** [comment]
@cole10up Good catch, yes this should be in two separate lines. @ryanwelcher Can you push an update?

**Comment by cole10up** [comment]
Confirmed this is now on 2 lines.

![image](https://user-images.githubusercontent.com/57115907/95511077-ce2ae380-096b-11eb-9cc1-03d2b04ab410.png)

Passed QA ✅
