### ISSUE TITLE
Create a link to the official AMP plugin for existing AMP references  

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1827]
## Feature Description

When connecting the Tag Manager and Optimize modules consider adding a hyperlink to the AMP [plugin website](https://amp-wp.org/) or wp.org [plugin repository page](https://wordpress.org/plugins/amp/).

![image](https://user-images.githubusercontent.com/41326532/88302928-59e28b80-ccfe-11ea-87c8-649ce8e834cc.png)

Optimize

![image](https://user-images.githubusercontent.com/41326532/88316034-180e1100-cd0f-11ea-8300-9244728e95da.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@amedina @westonruter With the AMP reference only appearing once the plugin is already activated the most suitable links may be to a dedicated section for each product, or a FAQ for that product.

**Comment by westonruter** [comment]
The “AMP” text itself may make more sense to link directly to amp.dev, or else if we link “paired AMP” then it could be an amp-wp.org page that talks about Transitional and Reader modes.

Otherwise, in the Optimize module, the “AMP experiment” text should rather link to https://amp.dev/documentation/components/amp-experiment/#configuration (if the Learn More link doesn't already link there).

**Comment by marrrmarrr** [comment]
@jamesozzie have you seen many users confused because there's a missing link to these docs? 

Ideally we want to have only one action per screen (in this case, selecting the right account) and don't want to send users off to a different page if it's not directly relevant to the action they're trying to complete.

**Comment by jamesozzie** [comment]
@marrrmarrr No users have made enquiries in the support forums. If there is a preference to have one action per page it makes sense to not include this feature. Most users would already having an understand of AMP given it's already active on their site.
