### ISSUE TITLE
Unable to complete set up

### ISSUE THREAD

**Issue by hafrang** [google/site-kit-wp#1834]
## Bug Description

I am not able to set up Google Sit Kit on my WordPress website. Once I get on to the Google Site Kit app set up wizard, I have to review the allowance for the application and then I am always redirected to the first step again and again without any piece of information.

## Steps to reproduce

Not applicable.

## Screenshots

Not applicable.

## Additional Context

 - PHP Version: 7.4
 - OS: Tried on Linux, Windows and Android
 - Browser Tried on Mozilla Firefox, new Edge and Chrome
 - Plugin Version 1.12.0
 - Device: Laptops and mobile device

Already tried to do:
- allow search engine indexing
- switch the theme to twenty nineteen
- disable all the other plugins
- update Google Site Kit plugin (current version is 1.12)
- remove the access of Google Site Kit app on my Google account
- incognito window
- tried on laptops (Linux & Windows) and mobile device
- reset Google Site Kit
- removed Google DNS entries for verification

I think that this bug occurs because I already set up Google Site Kit in the past on the same website. I disconnected from Google Site Kit. But it seems like the disconnection was not smooth because the property was still on my Google Search Console and on my Analytics (now deleted, and tried after).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@hafrang Thanks for reporting. As we've moved Site Kit support over to the plugins WordPress support forums initial support requests can be submitted by [creating a new topic.](https://wordpress.org/support/plugin/google-site-kit/#new-post) 

When creating a new topic please provide your [Site Health information](https://i.imgur.com/Rtkmsba.png) within the topic or [privately](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/). We can then try and determine the root cause in your case, while revisiting this GitHub issue if necessary.
