### ISSUE TITLE
Fix over-aggressive API requests to check whether Analytics and AdSense are linked

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1858]
## Bug Description

At the moment Site Kit determines the connection between Analytics and AdSense by making Analytics API requests with AdSense-specific metrics which are restricted and will result in an error, if AdSense is not connected.

These requests naturally happen for:
* The top earning pages widget on the Site Kit dashboard (`AdSenseDashboardWidgetTopPagesTableSmall`)
* The top earning pages widget on the AdSense page (`AnalyticsAdSenseDashboardWidgetTopPagesTable`)

However, a similar request is also manually triggered, separately from regular batch requests, **only** to check whether it returns an error (via `isAdsenseConnectedAnalytics()` utility function) for:
* The Analytics page overall (`AnalyticsDashboardWidget`)
* The AdSense page overall (`AdSenseDashboardWidget`)

The latter request is completely pointless: While it's supposed to prompt the user to connect AdSense and Analytics, this already happens in the two aforementioned widgets anyway if an error is returned, so we don't need to have an additional prompt (currently in the form of the `AdSenseDashboardOutro` component). Furthermore, this doesn't seem to work properly anyway (I see the prompts in the widgets, but I don't see the `AdSenseDashboardOutro` component being rendered).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### Legacy fixes

* The `isAdsenseConnectedAnalytics()` utility function and all of its usages should be removed.
* The `AdSenseDashboardOutro` component and all of its usages should be removed.

### Future fixes

* The `modules/analytics` store should receive a selector `getAdsenseLinked()` and an action `setAdsenseLinked( linked )`. These should **not** be handled via the regular settings store (although this technically is a setting), because that setting is automatically handled on the server, and a client-side change should not cause the settings to be flagged as outdated. This selector and action should only affect the client.
    * The initial value for the state should come from the server though (i.e. via `getSettings().adsenseLinked`, where this is present), but it should then be stored (and possibly modified) separately.
* The resolver for `getReport` in the 'modules/analytics' store should be updated:
    * If `options.metrics` includes any `ga:adsense*` metrics, the resolver should inspect the results of the `fetchGetReport` call:
        * If there is a 400 error with the message starting in "Restricted metric(s):", it should `dispatch( 'modules/analytics' ).setAdsenseLinked( false )`.
        * Otherwise `dispatch( 'modules/analytics' ).setAdsenseLinked( true )`.

## Implementation Brief

* Remove `isAdsenseConnectedAnalytics` from `assets/js/modules/adsense/util/index.js`
* Remove `isAdsenseConnectedAnalytics` util usage from files:
    `assets/js/modules/adsense/components/dashboard/AdSenseDashboardWidget.js`  
    `assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidget.js`  
    - Remove `isAdSenseConnected` from state
    - Remove `isAdSenseConnected` method
    - Remove `isAdSenseConnected` use and conditionally displayed `AdSenseDashboardOutro` from `render`
* Remove `assets/js/modules/adsense/components/dashboard/AdSenseDashboardOutro.js`
* Remove the `AdSense Outro` story from `stories/module-adsense.stories.js`
* Remove/update comment reference to `AdSenseDashboardOutro` in `assets/js/modules/analytics/components/dashboard/AnalyticsAdSenseDashboardWidgetTopPagesTable.js` under `getDataError`

#### Analytics Datastore
> New *AdsenseLinked selector+action pieces should be added to a new `datastore/adsense.js` partial
* `INITIAL_STATE.adsenseLinked` should be set to `undefined`
* Add a new `actions.setAdsenseLinked( linked: bool )` function which sets `state.adsenseLinked` in the reducer with the given value, which should be a boolean
* Add a new `selectors.getAdsenseLinked` which should return `state.adsenseLinked` (not from settings)
* Add a `resolvers.getAdsenseLinked` which selects `getSettings()`
    - only select + set the following if selecting `getAdsenseLinked() === undefined`
    - if an object is returned, call `setAdsenseLinked` with `settings.adsenseLinked`
* Update `resolvers.getReport`
    * If `options.metrics` includes any `ga:adsense*` metrics, the resolver should inspect the `error` from `fetchGetReport`
        * if the `error.code === 400` and `error.message` starts with in `Restricted metric(s):`
            dispatch `setAdsenseLinked( false )`
        * Otherwise dispatch `setAdsenseLinked( true )`
* Add Jest tests for added `(get|set)AdsenseLinked` selector and action
* Add/update tests for changes to `getReport` ensuring the behavior of both the above error and non-error cases are covered, as well as a different (non-400) error
* No changes to Storybook or E2E necessary

## QA Brief

Note the client side additions are not currently used yet as the legacy widgets used today don't use the datastore yet.

* Setup Site Kit with Analytics
* Enabled AdSense and complete setup using a site that is not connected to the configured Analytics profile
    - The tester plugin can be used to fake a connected AdSense account
* Load the Site Kit dashboard with the console open
* See the warning in the console:  
    > WP Error in data response {code: 400, message: "Restricted metric(s): ga:adsenseRevenue, ga:adsens….com/analytics/devguides/reporting/core/dimsmets.", data: {…}}
* You should see the blue "Link Analytics and AdSense" widget at the bottom of the page
* Open developer tools, clear all browser caches, then open the Network tab, set to "XHR". Go to the AdSense module page in Site Kit. Ensure there is no individual request fired to `modules/analytics/data/report` that includes a value within `metrics` that starts with `ga:adsense*`. (This request would have been present before this fix.)
* The Adsense module page cannot be tested without a real data connection
    - If you have access to real data, you should see the same "Link Analytics and AdSense" widget at the bottom of the page

If possible, setup Site Kit using a AdSense account and linked Analytics account/property
* The "Link Analytics and AdSense" widgets should not be shown, instead widgets with data are shown

## Changelog entry

* Avoid unnecessarily excessive requests to constantly check whether the active Analytics property and AdSense client are connected.

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@felixarntz there is an important detail here that was missed during the definition which is that the `getReport` selector currently supports several different formats for the different values in its `options` object https://github.com/google/site-kit-wp/blob/62c82436e2a69f7d7e4c544f07c73d7e838269a8/assets/js/modules/analytics/datastore/report.js#L59-L62

This makes building functionality based on `options` values much more complicated as we now need to account for all different shapes this may take. It's worth noting as well that we seem to use the same shape in all our requests – i.e. for `metrics` it's always an array of objects.

If we want to support multiple formats for `options`, we should at least normalize them during `argsToParams` and pass them to the server in a consistent way (even if the endpoint is a bit more flexible). However this doesn't solve the problem I'm running into for this issue where we're referencing `options` in the resolver where it wouldn't have been normalized yet. Why wouldn't we require a specific shape for the provided options rather than so many possible variants? This seems like a slippery slope as well though in terms of precedent to set – where do we draw the line in terms of which formats we support and those we don't? What selectors/functions should support extra formats? etc.

Perhaps we were a bit ambitious in the flexibility allowed for the `getReport` selector options. What do you think about simplifying the API here and requiring a single format instead?

cc: @tofumatt @eugene-manuilov

**Comment by tofumatt** [comment]
Spoke with @aaemnnosttv on a call about this, but basically I agree that the `options` validation and argument flexibility is too extensive here. This is on me a bit, because in reviewing the PR I assumed we needed all of the different `options` formats for different responses from the API, but @aaemnnosttv explained that simply the _array of objects_ shape would be sufficient for our needs and all needs (we only use _array of objects_).

Since we don't need those other shapes—even if the API accepts them—we should remove them and make our API stricter and easier to work with. If we support many different ways to get these reports, it will make checking the `options.metrics` params (like in this PR: https://github.com/google/site-kit-wp/pull/1991/files#diff-6b4f89301e27e64c32e347e11c3b3e0bR98-R106) way more complex as we'll have to account for many different styles.

I think it'll make our code easier to understand if we keep the API surface area low, so let's simplify those report arguments in #1991 before we start using different ones and it gets harder to simplify. 👍🏻

**Comment by eugene-manuilov** [comment]
> ... even if the API accepts them ...

@aaemnnosttv @tofumatt If I remember correctly, we wanted to support formats supported by Google APIs because 3rd party developers could use our API, and they would expect it to work like the official APIs and accept parameters in the same format.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> This makes building functionality based on `options` values much more complicated as we now need to account for all different shapes this may take. It's worth noting as well that we seem to use the same shape in all our requests – i.e. for `metrics` it's always an array of objects.

I think we should keep the current flexibility there - yes, the array of objects is what would cover everything, so I see your point, but it's also very explicit and makes it overly complex to use if you just want a metric that you could specify as `ga:users` instead of `[ { expression: 'ga:users' } ]`. We should be able to account for the different formats in our logic here - it's a bit more complex that way, but shouldn't be too crazy to detect a metric like that: If a string, check that. If an array of strings, check every string. If an object, check that object's `expression` string and so on.

**Comment by aaemnnosttv** [comment]
> it's also very explicit and makes it overly complex to use if you just want a metric that you could specify as `ga:users` instead of `[ { expression: 'ga:users' } ]`.

@felixarntz I agree that in that case it makes it _a bit more_ verbose and explicit to write, but is that a bad thing?

Perhaps all of this was already sorted out before and I'm just late to this conversation so forgive me if this is repetitive, but the added convenience doesn't seem worth the cost in terms of additional variants to support and test for. I would also suggest that it might even be a diminished developer experience to use because it's less clear how to use. As posted above, the `invariant` message is substantially more verbose, in contrast to most other places where we require something specific. e.g.
```
Metrics for an Analytics report must be an array of objects with "expression" properties.
```

My point here is not so much about this particular issue or challenge – you're right that it wouldn't be that hard to work around for this specifically, but this seems a bit inconsistent with the approach we've taken elsewhere.

One reason in particular that may not have been considered before is cache key generation. By supporting different structures for the request args, we undermine the caching mechanism we have because it isn't able to generate the same cache key for equivalent requests written with different formats.

We could introduce a normalization function to reduce these variants into a consistent output before it is fed into the fetch action, but again, we don't use it so I don't see the value to adding this just yet.

In the end, it's a tradeoff; flexibility for the consumer adds burden to the provider and vice versa (to an extent) whereas a clear definition simplifies both. That's not always desirable of course, but I think we should be careful about setting a precedent of being potentially overly flexible.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> In the end, it's a tradeoff; flexibility for the consumer adds burden to the provider and vice versa (to an extent) whereas a clear definition simplifies both. That's not always desirable of course, but I think we should be careful about setting a precedent of being potentially overly flexible.

I agree with that, and part of me prefers to only support the array of objects way because it makes it more explicit. However, the main reason for having it that flexible is because of consistency:
* The different `getReport` selectors across Site Kit modules should be consistent to use: Passing an array of strings to something called `metrics` feels intuitive, and it works the same way between the AdSense and Analytics datastore.
* `getReport` should be consistent with the Google API: If a user reads the Google API endpoint's docs, they should be able to provide `metrics` in that format.

Providing strings for `metrics` works in both Analytics and AdSense. The only reason objects are supported for Analytics is due to the extra support for `alias` in the Google API.

We're doing similar consistency tweaks in other fields, e.g. `orderby` in AdSense can be passed the same way as in Analytics, although it's technically sent in a different way.

> One reason in particular that may not have been considered before is cache key generation. By supporting different structures for the request args, we undermine the caching mechanism we have because it isn't able to generate the same cache key for equivalent requests written with different formats.

That's worth an issue for normalizing on the client, I don't think it's critical though.

**Comment by aaemnnosttv** [comment]
> The different `getReport` selectors across Site Kit modules should be consistent to use

💯  – although making them consistent with each other may make them inconsistent with the Google API docs so I'm not sure we can do both.

> `getReport` should be consistent with the Google API: If a user reads the Google API endpoint's docs, they should be able to provide `metrics` in that format.

That sounds like a good reason to support it, but I don't see the place in the docs you're referring to – can you point me to where it shows all of these are supported? In our case, the `options` for `getReport` seem to map to a [`ReportRequest`](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet#reportrequest) which defines `metrics` as an array of [`Metric`](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet#Metric) objects.

I'll go ahead and update the PR here to account for these variants for now as changing `getReport` here would have larger implications than this issue but it shouldn't block this from being completed for the release.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> That sounds like a good reason to support it, but I don't see the place in the docs you're referring to

What I meant was the API only supports this array of objects, so we should support that too. At the same time, we should allow for consistent behavior between our datastore `getReport` selectors, and e.g. in AdSense `metrics` cannot be an array of objects, only an array of strings, so we wanna keep the experience between AdSense and Analytics `getReport` metrics consistent - which is why to also allow for an array of strings in the Analytics `getReport` selector. The latter is for being intuitive across our datastores, while supporting objects is to cater to those developers that read the API docs.

**Comment by aaemnnosttv** [comment]
That makes more sense now 😄  thanks for clarifying.

**Comment by tofumatt** [comment]
QA ✅
