### ISSUE TITLE
React hooks fail when third-party libraries import from React

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#1888]
## Bug Description

We have noticed in upgrading dependencies (see #1835) and adding Reach Combobox (#1761) that third-party libraries using React hooks (mainly ones that `import { useRef } from 'react';`—where `useRef` is any hook, but using it as an example) cause React hooks errors, even though we aren't breaking the rules of hooks internally.

@aaemnnosttv and I looked into it, and both suspected that the issue with these seemingly unrelated hooks errors are down to us needing a shim for React imports, similar to the shims we use in `element-shim.js`. Essentially: we need to make sure our React imports—especially for hooks—are always importing from the same place for both our own code and third-party code.

This should allow us to add Combobox (for #1761), but also allow us to upgrade WordPress Data and other packages we have not upgraded while we diagnosed this issue.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Importing React code from third-party modules does not cause hooks errors

## Implementation Brief

* Add a React shim similar to `element-shim.js` that exposes hooks to third-party libraries.
* Add tests to ensure we are exporting all exports from `react` properly (similar to `element-shim.test.js`).
* Merge #1889.

## QA Brief

* A good way to QA this would be to merge `develop` into #1761 and go to the dashboard after running `npm run watch`.  It should load without issue and not display an "Invalid hooks error".

## Changelog entry

* Fix bug where certain React code being imported in third-party code could cause JavaScript errors.

**Comment by aaemnnosttv** [comment]
@tofumatt the IB looks good to me to fix the problems we were having. Regarding the AC, I'm not sure we should involve other issues directly or have items which are not directly related to the changes we're making such as the ability to upgrade `@wordpress/data` which isn't being upgraded in this issue. Thinking in terms of QA it seems odd that someone would need to check that `@wordpress/data` would be able to be upgraded - especially as a `@wordpress` package, it shouldn't be affected by this problem since it doesn't import from `react` but from `@wordpress/element` which is already shimmed.

Let's update the AC to be more specific to the changes that are needed and independent of other issues 😄 .

Also, since you created the PR and the IB includes a PR to merge, please complete the QA Brief section so that this is ready to merge, once CR is approved 👍

**Comment by tofumatt** [comment]
Fair enough, that makes sense!

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by ryanwelcher** [comment]
Confirmed that before merging `develop` hook errors were being fired. Post merge and build, the component rendered correctly
QA ✅
