### ISSUE TITLE
Blank display on all plugin menus after upgrading on WordPress 5.5

### ISSUE THREAD

**Issue by lmanyonho** [google/site-kit-wp#1912]
## Bug Description
We updated the plugin in on a site running WordPress 5.5 the plugin has gone blank (no display on all menus)

I've narrowed down the issue to the Site Kit plugin. This error appears as soon as the plugin is upgraded on a website running WordPress 5.5. Since this a production environment, everything is set up in the plugin itself.
## Steps to reproduce
Upgrade plugin on a website running WordPress 5.5

1. Go to 'Plugins'
2. Click on 'Update Google SitKit Plugin'
3. Scroll down to '.Sitekit and open all the menus Dashboard to Settings'

## Additional Context

 - PHP Version: 
 - OS: Linux 5.3.0-1034-azure x86_64
 - Browser Chrome
 - Plugin Version Version 1.14.0
 - Device: Dell Laptop
![SitKit-Error](https://user-images.githubusercontent.com/8328092/90243385-17a8f780-de2f-11ea-8425-e4716147ac52.PNG)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@lmanyonho Thanks for reporting. Initial bug or support requests can be submitted using the plugins WordPress support forum. 

If you open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) we can try and determine the root cause in your case, while revisiting this GitHub issue if necessary. Bear in mind I've been unable to recreate this issue so it may including your [Site Health information](https://i.imgur.com/Rtkmsba.png) might be useful as we troubleshoot this issue. You can share [privately](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) if preferred.

**Comment by jamesozzie** [comment]
@lmanyonho Upon further inspection other users have reported the same issue as per #1908. Feel free to keep track of that issue while we investigate this further.
