### ISSUE TITLE
My site doesnt work anymore with the newest update

### ISSUE THREAD

**Issue by xtomyserrax** [google/site-kit-wp#1934]
Hello, Im really noob with this Wordpress world but when I downloaded the latest G Site update (v 1.14.0), my page stopped working when I went there while having my admin sesion opened. What do I mean? That if I go to my page with private mode of chrome then it works fine, if I go to my page in normal mode (I have my admin credentials enabled) then it doesnt hopen and I have a message saying "There has been a critical error on your website.".

This error made me crazy, but if I deactivate this plugin, then it works perfectly for me.

I dont really know how to get an error log or something like that so sorry for being so noob haha, but maybe this info somehow helps. Im using Wordpress 5.5 version.

Let me know if you need more info and please tell me how to send it to you. The admin panel works fine for me except when I try to edit some plugins. Again, if I disable this plugin, everything works perfectly.

![image](https://user-images.githubusercontent.com/6054192/90579383-3ba46a00-e19c-11ea-8fef-e09ae4bfbbd8.png)

Thanks!

**Comment by xtomyserrax** [comment]
Also I noticed that no more information is being showed. In the past I used to see page speeds info, analytics, search console info, now its stucked in searching but nothing happened. Again, this started happening after I updated the plugin, it used to work perfectly for me.

**Comment by jamesozzie** [comment]
@xtomyserrax Thanks for getting in touch. We've moved Site Kit support to the WordPress support forum. You can open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we can assist. We can also reopen this GitHub issue if neccessary although it seems similar to #1908, which can be caused by a combination of plugins. 

Within your WordPress support topic or [privately](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) please share your [Site Health information](https://i.imgur.com/Rtkmsba.png) and we'd be happy to troubleshoot this issue with you.

**Comment by xtomyserrax** [comment]
Thank you, just posted it there: https://wordpress.org/support/topic/my-site-doesnt-work-anymore-with-the-newest-update/

I also shared the site health information privately! Thanks!!
