### ISSUE TITLE
Refactor Storybook Stories to use Component Story Format (CSF)

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1935]
## Feature Description

Currently our Storybook stories are all located under the `./stories` directory in the repository and use the legacy `storiesOf` API.

According to the [docs](https://github.com/storybookjs/storybook/tree/master/lib/core/docs/storiesOf.md):
> `storiesOf` is Storybook's Legacy API for adding stories. Up until Storybook 5.2, it has been the primary way to create stories in Storybook.
>
>In Storybook 5.2 we introduced a simpler and more portable [Component Story Format](https://storybook.js.org/docs/react/api/csf), and all future tools and infrastructure will be oriented towards CSF. Therefore, we recommend migrating your stories out of `storiesOf` API, and even provide [automated tools to do this](https://github.com/storybookjs/storybook/blob/master/lib/core/docs/storiesOf.md#component-story-format-migration).
>
> That said, the `storiesOf` API is not officially deprecated. For the time being we plan to support it for the foreseeable future.

According to the docs for [Component Story Format](https://storybook.js.org/docs/react/api/csf)
> The Component Story Format (CSF) is the recommended way to write stories. It's an open standard based on ES6 modules that is portable beyond Storybook.

One of the benefits of this format is that it allows us to co-locate component stories with the components to make it easier to switch between the two files during development, as well as see which components have stories or not. This is also more consistent with our approach to how tests are defined for our components with a `ComponentName.test.js`; the stories would be in a `ComponentName.stories.js` file in the same directory.

As mentioned above, there is a [first-party tool for automating the conversion](https://github.com/storybookjs/storybook/blob/master/lib/core/docs/storiesOf.md#component-story-format-migration) from one format to another so this shouldn't be an entirely manual process.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
This sounds great, I'm 100% for it.

> One of the benefits of this format is that it allows us to co-locate component stories with the components to make it easier to switch between the two files during development, as well as see which components have stories or not.

That's the main win for me, and what won me over on co-located tests. Being able to quickly see which files are _missing_ tests is really handy.

That there's an automated tool for converting is even better, I say we move to this approach! 👍

**Comment by felixarntz** [comment]
Definitely +1 for this. I wonder if it is possible to do this incrementally somehow though. The automatic migration may be helpful, but we'll probably need to manually adjust a lot of things, especially because a lot of our current stories aren't necessarily testing a specific component. Furthermore as part of this it would be great to revisit our Storybook hierarchy and naming conventions for which I'm sure there's room for improvement.

Last but not least we also have our Storybook build actions that put the current Storybook on GitHub Pages, so we'll need to also ensure that continues to work.

**Comment by aaemnnosttv** [comment]
> we'll probably need to manually adjust a lot of things, especially because a lot of our current stories aren't necessarily testing a specific component.

True, although it could probably be made that way. E.g. Analytics Setup stories could be associated with the Analytics `SetupMain` component, or maybe in `analytics/components/setup/stories.js`.

> Furthermore as part of this it would be great to revisit our Storybook hierarchy and naming conventions for which I'm sure there's room for improvement.

Yes, agreed 👍 

> we also have our Storybook build actions that put the current Storybook on GitHub Pages, so we'll need to also ensure that continues to work.

I would expect this to not require any changes since the only thing that would change is where the story definitions are located, which shouldn't affect the result of the Storybook build.

**Comment by felixarntz** [comment]
Closing, since we're not going to do a holistic refactoring towards CSF, but more on demand, based on the guidelines we've put together.

See #2940, #2941, #2942 for the only refactoring issues defined at this point - we want to limit Storybook refactoring to those, to have example cases for the different types of stories. Other existing stories should be migrated on demand within other issues, or their own individual issues per component.
