### ISSUE TITLE
Log in required

### ISSUE THREAD

**Issue by pql89** [google/site-kit-wp#1947]
Hi, i'm trying to install site kit on my website.

i've connected search console and speed page while analytics is not able to complete the connection. All of them (moreover the two connected) don't show anything because of log in required. But i'm using my personal google account on chrome browser and i've the website connected with another business account. so when i do the log in for ex in the search console page i can swich easily to the other account. how can i do this log in???

thank you very much

**Comment by jamesozzie** [comment]
@pql89 Thanks for reporting. Initial support requests can be submitted using the plugins WordPress support forum. 

If you open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there while providing your [Site Health information](https://i.imgur.com/Rtkmsba.png) within the topic or [privately](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) we can try and determine the root cause in your case, while revisiting this GitHub issue if necessary.
