### ISSUE TITLE
Do not show Tag Manager module in congratulations CTA notification

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2025]
The Congratulations notification for Site Kit includes a list of modules to activate (or whether they are already active). This list currently only includes modules that don't have any dependencies. Now that Tag Manager has been split out to no longer be dependent on Analytics, it shows up there too as expected - however it shouldn't as it's a fairly minor module that shouldn't be exposed here at this point.

![Screenshot 2020-09-14 at 13 42 57](https://user-images.githubusercontent.com/3531426/93136459-d3f51800-f690-11ea-8ecf-0a8ac1602dc5.png)

Let's simply modify the notification to only include information for the following modules:
* `search-console`
* `adsense`
* `analytics`
* `pagespeed-insights`

**PR for this should be opened against `feature/ga-gtm-separation`.**

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Only the following modules should be included in the "Congrats on completing..." notification:
    * `search-console`
    * `adsense`
    * `analytics`
    * `pagespeed-insights`

## Implementation Brief

* Introduce new optional prop `moduleSlugs` to `ModulesList` component. If provided, the modules to be rendered should be filtered against that list so that only those are included.
* In `DashboardSetupAlerts` component, pass the four slugs from the ACs to the `ModulesList` rendered.

## QA Brief

* Before this fix, after completing module setup for a module, the "Congrats on completing..." notification would include Tag Manager.
* After this fix, Tag Manager should no longer be included in that notification.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
@felixarntz this issue is related to https://github.com/google/site-kit-wp/issues/1148 which I raised a while back.

It's a bit different now of course that GTM will no longer depend on Analytics, but part of the idea there is that the CTA  is useful for showing other modules to activate (i.e. module discovery). I would suggest that we not _prevent_ Tag Manager from showing up there but implement a few rules to help better manage this area
- Only show a maximum of 4 modules to prevent it breaking to multiple rows on desktop
- Show inactive modules first and fill in the rest with active modules to always show 4, but prioritize inactive to streamline activating multiple
- Potentially use `module.order` as a secondary sort/prioritization
- Potentially always include the activated module to "reinforce" the messaging that it is now active/connected

This way, the user isn't forced to go through _Settings > Connect_ to activate other modules than those here. I think this might be a better experience than making this area specific to only certain modules. What do you think?

**Comment by felixarntz** [comment]
@aaemnnosttv I think #1148 raises a valid point, however this issue here is merely about keeping the current experience as is - Tag Manager and Optimize right now are different from the 4 "flagship modules" and that's why they shouldn't be included here for now.

We'll get rid of these notifications as part of the new onboarding and related notifications workstream anyway, so we shouldn't invest much effort into this legacy notification - that's also why I chose to use a quick approach for the IB (despite the generally-sounding name, `ModulesList` is only used for that notification anyway).

**Comment by aaemnnosttv** [comment]
IB ✅
