### ISSUE TITLE
Tag Manager support for Web Stories

### ISSUE THREAD

**Issue by swissspidy** [google/site-kit-wp#2070]
## Feature Description

Site Kit currently only prints an analytics tag for Web Stories when using the Analytics module.

The Tag Manager module does not support Web Stories yet. Can we fix this?

For reference, the Analytics module config:

https://github.com/google/site-kit-wp/blob/84c97270919ca63101b114c6a73a1c7ca63f4e49/includes/Modules/Analytics.php#L143-L160

And the Tag Manager one (no mention of Web Stories):

https://github.com/google/site-kit-wp/blob/84c97270919ca63101b114c6a73a1c7ca63f4e49/includes/Modules/Tag_Manager.php#L128-L143

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Tag Manager module should render its AMP tag (see `Google\Site_Kit\Modules\Tag_Manager\AMP_Tag` class) in Web Stories if an AMP container has been configured, the same way that the Analytics module does (see `web_stories_print_analytics` action).

## Implementation Brief

Following the completion of https://github.com/google/site-kit-wp/issues/2998
In `includes/Modules/Tag_Manager.php` add a call to print the amp tag for web stories:
`add_action( 'web_stories_print_analytics', $print_amp_gtm );`

For reference, the Analytics module has this logic, see the snippets in the `Feature Description` of this ticket.

## QA Brief
* Set up Tag Manager and verify if the `amp-analytics` is outputted in AMP.

## Changelog entry

* Add Tag Manager AMP tag support for Web Stories.

**Comment by swissspidy** [comment]
cc @felixarntz

**Comment by felixarntz** [comment]
@swissspidy This is a bit more involved than just adding the hook:
* An "AMP" container must be used in GTM to be compatible with Web Stories.
* When detecting the "AMP mode" (relevant during GTM setup), we currently don't consider Web Stories (which e.g. in combination with a non-AMP website would still mean what we call "secondary" AMP because the site would have both AMP and non-AMP content). The lack of this means that, just from having Web Stories, Site Kit wouldn't allow selecting an "AMP" container in GTM.
* Note that the Web Stories-specific tracking modifications for Analytics wouldn't work. Tag Manager is also technically not necessarily Analytics, it really depends on how the container is configured, whether there is Analytics connected in its configuration. I believe the story-specific events tracking would also need to happen within Tag Manager configuration, so it wouldn't be something that the Web Stories plugin can control.

**Comment by swissspidy** [comment]
Ah, forgot about the whole detection and container selection part.

**Comment by swissspidy** [comment]
> When detecting the "AMP mode" (relevant during GTM setup), we currently don't consider Web Stories

Would this be as simple as detecting whether the plugin is active?

> Note that the Web Stories-specific tracking modifications for Analytics wouldn't work.

Noted 👍

**Comment by felixarntz** [comment]
I've included the improvement to consider the Web Stories plugin for the AMP mode detection in #2998. Afterwards we should be able to get this sorted.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@asvinb OK, I have tried to test this but need some more direction.  In the QAB.  `Set up Tag Manager and verify if the amp-analytics is outputted in AMP.` Would it be possible to get more information on what we should expect to see and where we would verify this?   I have set up Site Kit with Tag manager, AMP and activated Web Stories. I've looked in the debug log. 

![image](https://user-images.githubusercontent.com/73545194/129925854-187aab55-2fb7-4c8e-bcee-60a0e735b4f5.png)

**Comment by swissspidy** [comment]
You shouldn't need to activate the AMP plugin for this.

When you create a new story in the Web Stories editor and preview that story on the frontend, you should see some `<amp-analytics>` tag in the source code with a configuration that matches the Tag Manager container ID in Site Kit.

**Comment by wpdarren** [comment]
@swissspidy perfect, thank you for the explanation!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Initially, Google tag manager was not appearing in the source code on a Web story. When the branch was switched to `develop` the AMP container appeared in the Google tag manager source code.  I checked that the configuration matches the Tag Manager container ID in Site Kit. 

![image](https://user-images.githubusercontent.com/73545194/129930380-2e2a6636-f8f6-45c6-95bc-a19c68cbdbf6.png)
