### ISSUE TITLE
Improve accuracy of detecting whether a URL relevant for service registration has changed

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2132]
#1857 added a mechanism to disconnect users and prompt for reconnection once the site's `home_url()` has changed. This has caused some issues with certain plugins, see #2131. While this allows for 3P code to fix the issues, it may be possible to improve accuracy of our detection mechanism ourselves in a general way so that we don't need to ask all those 3P plugins to integrate with the filter introduced in #2131.

The problem right now is essentially that, if a 3P plugin filters the home URL, we don't know whether that filter is to make a "persistent" change to the home URL (e.g. filtering it to change `http://` to `https://`) or whether it is for a contextual change (e.g. add language path segment based on which language path segment is in the current URL). Let's think about whether we can make our detection more accurate to separate these two cases somehow (only the first should cause the disconnect for Site Kit users).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eugene-manuilov** [comment]
@felixarntz, to correctly detect whether a URL has changed, we need to make sure that the old site's home URL isn't reachable anymore. Site availability helps us to decide whether it is a kind of home URL filtering or a real URL change because if the site is still available at the old URL, then the current setup is still valid. Am I right?

The easiest way to check if the old URL is reachable is to send a request to it and verify its response. For this purpose, we need to do the following:

* create an auxiliary endpoint which gets data from a transient and sends it in response;
* update `Authentication::check_connected_proxy_url` function to schedule a single event that will run in an hour;
* add a hook for the scheduled event that will verify the old URL and disconnect Site Kit if it is not reachable anymore.

To correctly verify the old URL, the hook should do the following:

* save a random value (a UUID or a hash code of a random string/value) with the transient name used by the new endpoint;
* send a request to the new endpoint located at the old home URL;
* check the response and do nothing if we get the same value generated by this hook, otherwise disconnect.

The scheduled event is needed to avoid spamming requests to the old URL. We will check if there is already a scheduled event and return early in the `Authentication::check_connected_proxy_url` function. It will guaranty that we send requests only once an hour to detect when the old URL stops to be accessible.

Does it make sense to you? cc @aaemnnosttv

**Comment by aaemnnosttv** [comment]
> to correctly detect whether a URL has changed, we need to make sure that the old site's home URL isn't reachable anymore.

I don't think this is necessarily true; if a site changed its URL, it may be as simple as `http` -> `https` which I believe is enough to require the user to reconnect (correct @felixarntz ?). In this case, it's common to have a redirect in place from one to another, but some sites work with both without forcing one or the other. Even in the case of a more substantial URL/domain change, there will likely be a redirect in place. We could check the URL without allowing for redirects, but I'm not sure if it makes sense to do that.

Perhaps we shouldn't automatically disconnect, but instead display a notification for the user to confirm if the change is permanent. We could then potentially disable some functionality for sites in this state, again with an added notification that capable users could use to confirm the change and update the connected proxy URL. 

Jetpack has a similar functionality as it is also tied to your specific site and displays a prompt like this when using between different instances of the same site.

![image](https://user-images.githubusercontent.com/1621608/95308287-60f74f80-0892-11eb-9e39-0ff1566978b2.png)

I'm not sure if there's an equivalent "safe mode" that applies to Site Kit but perhaps something like this would be better?

**Comment by felixarntz** [comment]
Closing this as `invalid`, since for a while now Site Kit has been using a request before connecting to check the service URLs. As such, improving the accuracy of Site Kit's own checks shouldn't be needed any longer.
