### ISSUE TITLE
Introduce `ReportError` and `ReportZero` components

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2246]
There should be new `ReportError` and `ReportZero` components that replace similar legacy components returned by the functions `getDataErrorComponent` and `getNoDataComponent`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new functional component `ReportError` in `assets/js/components/ReportError.js`:
    * It should require props `error` (error object) and `moduleSlug` (module slug string).
    * It should return the same as `getDataErrorComponent`, but relying on the `core/modules` store to get module information. It should also not use `ctaWrapper`.
* There should be a new functional component `ReportZero` in `assets/js/components/ReportZero.js`:
    * It should require prop `moduleSlug` (module slug string).
    * It should return the same as `getNoDataComponent`, but relying on the `core/modules` store to get module information (the module name is all that's needed for now). It should also not use `ctaWrapper`.
* All refactored widget components (`assets/js/modules/*/components/dashboard/Dashboard*Widget.js`) should use `ReportError` instead of `getDataErrorComponent` and `ReportZero` instead of `getNoDataComponent`.

## Implementation Brief

* Create a new functional component `ReportError` in `assets/js/components/ReportError.js` that satisfies requirements in the AC;
* Create a new functional component `ReportZero` in `assets/js/components/ReportZero.js` that satisfies requirements in the AC;
* Update all module widgets that use `getNoDataComponent` and `getDataErrorComponent` functions to use `ReportZero` and `ReportError` components instead;
* Add appropriate storybook stories in the Global section.

### Test Coverage

* N/a

### Visual Regression Changes

* No visual changes should occur as a result of these changes.

## QA Brief

* Check that all module widgets(`assets/js/modules/*/components/dashboard/Dashboard*Widget.js`) use `ReportZero` and `ReportError` components and don't use `getNoDataComponent` and `getDataErrorComponent` functions;
    - Note the PSI dashboard widget renders errors differently (without the inner `CTA` so it's error display has not changed to preserve the current design).
* There should be no visual changes on the dashboard page.

## Changelog entry

* Introduce `ReportError` and `ReportZero` components which should be returned by widgets that are in error state or have no data to display.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ❌

* Looks like https://github.com/google/site-kit-wp/blob/7ceb81b49b1914178961193c58ec0c2dda1cbecd/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidget.js#L180 still uses the legacy `getDataErrorComponent` and `getNoDataComponent` functions.
* It's also used here: https://github.com/google/site-kit-wp/blob/7ceb81b49b1914178961193c58ec0c2dda1cbecd/assets/js/modules/search-console/components/dashboard/GoogleSitekitSearchConsoleDashboardWidget.js#L198-L200
* Also: https://github.com/google/site-kit-wp/blob/7ceb81b49b1914178961193c58ec0c2dda1cbecd/assets/js/modules/adsense/components/dashboard/AdSenseDashboardWidget.js#L194-L196

Maybe I'm confused about the QA steps here, but it seems "modern", functional components should always be using the new `<ReportZero />` and `< ReportError />` components instead of the legacy `getDataErrorComponent` and `getNoDataComponent` functions.

Is that not correct? @aaemnnosttv: let me know if I'm off-base on that one. Otherwise the QA looks good.
