### ISSUE TITLE
Error 403 It appears you don't have permission to access this page. 

### ISSUE THREAD

**Issue by IdioticDoodler** [google/site-kit-wp#228]
### Bug Description
I'm getting this error getting on step 2 the authentication part, after I sign-in in google, allow the permission. 
then it show me this
**It appears you don't have permission to access this page. 403 Error. Forbidden. ** 

### Steps to reproduce
1.Install it on wordpress
2. Stert the setup
3.Create Client ID
4.authentication  - then after verifying there's the error

### Screenshots
![image](https://user-images.githubusercontent.com/39472759/61130382-1fd68b00-a4e9-11e9-9ad7-d2c5f58890fa.png)

**Comment by jamesozzie** [comment]
@IdioticDoodler Thanks for reporting. Do you mind trying the steps below so we can troubleshoot further?

1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate your other active WordPress plugins
3. Install Site Kit in a new incognito window (so Chrome extensions/caching doesn't interfere)

If you have any additional Firewall or Security software in place maybe temporarily deactivate that also during the setup process. Let me know if any of the above works.

**Comment by marketingconcafe** [comment]
Hi, I have the same problem. Try the solutions you mentioned @jamesozzie but it did not work for me.

**Comment by jamesozzie** [comment]
@IdioticDoodler @marketingconcafe Can you confirm that you have full access rights to the site being added from within [Google Search Console](https://search.google.com/search-console/users)? 
Also please check that you don't have any [API Key Restrictions](https://i.imgur.com/p9c4S3M.png)

Lastly can you let me know if you have any additional Firewall or security software setup on your machine?

**Comment by bobonski** [comment]
I have the same issue. I am the account owner and do not use G Suite... did someone find the issue?

**Comment by jamesozzie** [comment]
@bobonski @IdioticDoodler Can you inform me the plugins which you have active? In particular any caching or security plugins. They could be impacting or conflicting with Site Kit during setup.

**Comment by jamesozzie** [comment]
@bobonski @IdioticDoodler Does the issue you are encountering persist? If so please inform me of the below:
- Any console errors 
- WordPress environment (You can use a plugin such as "[Debug Info](https://i.imgur.com/VhGa8ob.png)" to share your environment)

**Comment by writetoevv** [comment]
Hi @jamesozzie 

While activating Google Site Kit, it has been failing  @ 2nd step "Authenticate"...
Mysite starts https://...
As suggested by you, i tested in private window of browser.
Please refer attached console log errors & warning info.. 
I have been tested it in 3websites with no other plugin. In all cases it failed @2nd step..
please help...


![Google Site Kit Error Log 2](https://user-images.githubusercontent.com/15318669/62743504-46440380-ba60-11e9-8836-fb6670001b48.jpg)
![Google Site Kit Error Log](https://user-images.githubusercontent.com/15318669/62743505-46440380-ba60-11e9-8106-a1df4cba7fbc.jpg)
![Google Site Kit warning Log 2](https://user-images.githubusercontent.com/15318669/62743506-46dc9a00-ba60-11e9-8f0a-783a8c6348c8.jpg)

**Comment by jamesozzie** [comment]
@writetoevv Some of the resources on your website might not be served over https, despite having a https website. Can you check with a non Firefox browser for the same error? An alternative is to click on the 'shield' icon in the top-left corner of the address bar from your screenshot, then click on the 'Disable Protection on This Page', 

You'll find more on how Firefox treats mixed content [here](https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox?redirectlocale=en-US&redirectslug=how-does-content-isnt-secure-affect-my-safety). 

Let me know if that works for you.

**Comment by writetoevv** [comment]
1. Also tried by "Disabling Protection on This Page" on firefox Browser. 
   403 forbidden in firefox too.
2. I tested with Chrome Browser. The same issue of '403 forbidden' in Chrome Brower too.

**Comment by writetoevv** [comment]
it is because of these HTTP links...

http://www.iyfforb.com/px.js?ch=2
http://www.iyfforb.com/px.js?ch=1
http://www.iyfforb.com/display.cfm
http://i3.cdn-image.com/__media__/js/min.js?v2.2
http://i4.cdn-image.com/__media__/fonts/ubuntu-r/ubuntu-r.woff
http://i4.cdn-image.com/__media__/fonts/ubuntu-r/ubuntu-r.woff2
http://i4.cdn-image.com/__media__/fonts/ubuntu-b/ubuntu-b.ttf
...
http://i3.cdn-image.com/__media__/pics/12471/bodybg.png

**Comment by jamesozzie** [comment]
@writetoevv If you are using a CDN or other security service can you temporarily disable them before trying again? 

Please share your [Site Health information](https://i.imgur.com/Rtkmsba.png) and we can investigate further.

**Comment by writetoevv** [comment]
1) i m not using CDN in websites. 

2)[Site Health Info.txt](https://github.com/google/site-kit-wp/files/3486688/Site.Health.Info.txt)

**Comment by writetoevv** [comment]
hi  jamesozzie 

Anything you need from side to investigate the issue?

Regards

**Comment by jamesozzie** [comment]
@writetoevv What is the URL where you are seeing the "No Permissions" message on?

If you have any other WordPress sites on the same server you can try setup Site Kit on those sites, or alternatively on a clean install without any additional plugins. We can at least then try to determine if it's an issue with your environment or hosting setup.

**Comment by writetoevv** [comment]
Hi jamesozzie 

when i tested in incognito mode, i got below error code for https://auniqueweb.in ( A brand new domain with only two plugins "Google Site Kit" & "Debug Info"

**Error: ICE failed, add a STUN server and see about:webrtc for more details**

also, pls rerer attached snapshot
![a unique web --googlekit Incognito](https://user-images.githubusercontent.com/15318669/63016968-aac4ef80-beb2-11e9-8b00-2dced6a770b9.jpg)

**Debug Info: WordPress Debug Info**
Below is some information about your current WordPress and server setup. This information may be useful for your technical support, website developers, and plugin or theme developers who need to diagnose problems on your site.

WordPress Version: 5.2.2
Current WordPress Theme: Twenty Nineteen version 1.4
Theme Author: the WordPress team - https://wordpress.org/
Theme URI: https://wordpress.org/themes/twentynineteen/
PHP Version: 7.3.5
MySQL Version: 5.6.33-79.0-log
Apache Version: This information is not available.
Active Plugins:
    Debug Info (1.3.8)
    Site Kit by Google (1.0.0-beta.1.0.3)

**Comment by jamesozzie** [comment]
@writetoevv That error reported isn't specific to the Site Kit plugin. Do you have any additional software such as a security/firewall or other service setup at host level? In addition when looking at your screenshot you are accessing the non secure (http) version of your site. Can you put a redirection in place to your https before checking again.

**Comment by writetoevv** [comment]
1. No security/firewall installed in domain.
2. Installed a plugin named "https-redirection" to force http  to HTTPS redirection.
      https://wordpress.org/plugins/https-redirection/
3. i am not explicitly calling http url. While i try to install "google Kit" , my site is always 'https'.. & when i get 403 error page, it shows as yellow triangle @address bar of website..
3. However, issue is same. 
![gk errors](https://user-images.githubusercontent.com/15318669/63027462-a6a4cc00-beca-11e9-944f-851a8402c598.png)

**Comment by jamesozzie** [comment]
@writetoevv Do you know  the source of the iyfforb.com URL reference? Maybe try to deactivate any CDN feature (which could be active via your hosting) and any other additional services you have active.

**Comment by writetoevv** [comment]
https://www.ip-adress.com/website/iyfforb.com

i m not explicitly using any CDN..i found above link (check DNS information)..

**Comment by writetoevv** [comment]
TLS Recommendations

HTTPS mixed content found. Your HTTPS website is referring to an HTTP resource:
http://i1.cdn-image.com/__media__/js/min.js?v2.2 on https://auniqueweb.in/wp-includes/css/
http://www.iyfforb.com/display.cfm on https://auniqueweb.in/wp-includes/css/
http://www.iyfforb.com/px.js?ch=1 on https://auniqueweb.in/wp-includes/css/
http://www.iyfforb.com/px.js?ch=2 on https://auniqueweb.in/wp-includes/css/

**Comment by writetoevv** [comment]
Mixed Content: The page at 'https://sgbckdk.in/?oauth2callback=1&code=4/nQFEKSrVFv27SDWxfhT4Y9guDQTMVfNzhIN9Z4F4_pRCBeZwgdohLSnLyZlgqVGVwvOXKObXgpNB_YwF96-bsWs&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/webmasters%20https://www.googleapis.com/auth/siteverification%20openid&authuser=0&session_state=eff80e6859cd31d87fd7271d5b049c31ad381452..1f47&prompt=consent' **was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://www.iyfforb.com/display.cfm'**. This endpoint should be made available over a secure connection.

**Comment by writetoevv** [comment]
Here is the log from Web Server... Webserver's support team informed below log to me.
**"Your application is triggering mod security rules which cannnot see be whitelisted on the server.
Refer this link: https://support-tools.com/?43ae2b41f922420f#fMd9dg3KKYb/g2GdTkN1C5AejOTnRgKWDsZLe847Cas=
So you will have to optimize the code of your application in order to overcome this issue."**


**Log from Webserver:**
[Thu Aug 15 05:06:28.239330 2019] [:error] [pid 230290:tid 139635044652800] [client 115.110.127.198:61752] [client 115.110.127.198] ModSecurity: Warning. Matched phrase ".profile" at ARGS:scope. [file "/etc/apache2/conf.d/modsec_vendor_configs/OWASP3/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf"] [line "41"] [id "930120"] [rev "4"] [msg "OS File Access Attempt"] [data "Matched Data: .profile found within ARGS:scope: email profile openid https:/www.googleapis.com/auth/userinfo.profile https:/www.googleapis.com/auth/userinfo.email https:/www.googleapis.com/auth/webmasters https:/www.googleapis.com/auth/siteverification"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-lfi"] [tag "OWASP_CRS/WEB_ATTACK/FILE_INJECTION"] [tag "WASCTC/WASC-33"] [tag "OWASP_TOP_10/A4"] [tag "PCI/6.5.4"] [hostname "auniqueweb.in"] [uri "/"] [unique_id "XVToVC2Zms8iTPR3puoZqQAAAAE"], referer: https://accounts.google.com/signin/oauth/consentsummary?authuser=2&part=AJi8hANKftegMCj2Mc81b2qgexRZNKunrD7FoL_mHjMRKUqqmRXG--EUk0KPSJvaH4k0OqaeKZBjSLwcv7vQcWa1G6ASLwkaLf8r9fFvsoS2DpwiMgwOn6NXpw0qNwOcoqtwXHe9iEC9pVUJzxE6aF_wwglIBnVmuvCT3808Yztv3NmxhHVEtaiE3FXKSPLJ1uHSpx7wQkEDd7CH2iwmnddZ3o8dMFqQCyFtsLRJlA-8R0hYDDKaIoWhbstIybo6oLUo2XJYWyzLZSKAqtPIonplk7bFZUSX4wQkruueaIjmFNJ5BWzpJyQSws7cjWKNZQJ4E_SNzF62WrTaLRNzbjIuHhBhPY32Qrr5zDKdcdU90akUypX2sFwy3Vyyr_ak4qFw7fCzYeX8Xd7F80rn8PWUWaqwFWc-iYN2zRK3OuytZp9MoXbvF8aOS4HKtN2yjG0dkulxGDtHwLsPMvuN_Mr0Ixhi6T364oChSPPmPIaY6oly9hxOplCaDjMrwB5iYv66o2Micux1OHnegVWoGKT1Aew0LnVNtw4k-RN7ZXyhQxpMBzAUQ-UpvxTTWmpRvubySjL4IxKBIzXcEU8le4TdwpF0k1nI0CV_meHWWjYQFrhYgo4zn1WPASKOV8P6TFuPxmjyjK1oHB4pEEoUysZKUC0h14Gh9uP65raNjjkYb3hjIGaKPyxJxgV9Ojo9-blpEQenWsX5MPugHurzw_KKFzGuA41XYJSMW8LaGHL8L5a50xd2yWrOt7vz1xMCzcZgRVreTMCXIXO5Fj5r3XzqN2UVVbRPDvUmxHg1wWn6obKV9-fUrtpWSIEStMtbZI3UOuy0DEuIJFZhwzkhuM8ndvizQNVImibFXlBHuypyPZXhEoq8rMLnT2vAvKEp2GIVVx0iihHHAQmWLkZZj2D4YUFt3p6s2VrVbOoMk81YGiUJSdvlusJoVYM95c387LKHEtG8B96bJSFNhoZ36Uw2lBpRR6eNm67X1mdkcvaljsl2M9LSSWDVq99FJwb9Al77-rmkuwYC&as=PkSwgunVLSL-UJ-vtFgNng&rapt=AEjHL4OBlGvjxnEfK3RSNxhzTd8WEmeHQjbJ3FmQiD_yHHNoxMJhhCFMsNYQWk2Q213_JcY59jrQsD7mpc2-f0IZwF8GL-qdXw&approvedScope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fwebmasters%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsiteverification
[Thu Aug 15 05:06:28.242799 2019] [:error] [pid 230290:tid 139635044652800] [client 115.110.127.198:61752] [client 115.110.127.198] ModSecurity: Access denied with code 403 (phase 2). Operator GE matched 5 at TX:anomaly_score. [file "/etc/apache2/conf.d/modsec_vendor_configs/OWASP3/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "30"] [id "949110"] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [severity "CRITICAL"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "auniqueweb.in"] [uri "/"] [unique_id "XVToVC2Zms8iTPR3puoZqQAAAAE"], referer: https://accounts.google.com/signin/oauth/consentsummary?authuser=2&part=AJi8hANKftegMCj2Mc81b2qgexRZNKunrD7FoL_mHjMRKUqqmRXG--EUk0KPSJvaH4k0OqaeKZBjSLwcv7vQcWa1G6ASLwkaLf8r9fFvsoS2DpwiMgwOn6NXpw0qNwOcoqtwXHe9iEC9pVUJzxE6aF_wwglIBnVmuvCT3808Yztv3NmxhHVEtaiE3FXKSPLJ1uHSpx7wQkEDd7CH2iwmnddZ3o8dMFqQCyFtsLRJlA-8R0hYDDKaIoWhbstIybo6oLUo2XJYWyzLZSKAqtPIonplk7bFZUSX4wQkruueaIjmFNJ5BWzpJyQSws7cjWKNZQJ4E_SNzF62WrTaLRNzbjIuHhBhPY32Qrr5zDKdcdU90akUypX2sFwy3Vyyr_ak4qFw7fCzYeX8Xd7F80rn8PWUWaqwFWc-iYN2zRK3OuytZp9MoXbvF8aOS4HKtN2yjG0dkulxGDtHwLsPMvuN_Mr0Ixhi6T364oChSPPmPIaY6oly9hxOplCaDjMrwB5iYv66o2Micux1OHnegVWoGKT1Aew0LnVNtw4k-RN7ZXyhQxpMBzAUQ-UpvxTTWmpRvubySjL4IxKBIzXcEU8le4TdwpF0k1nI0CV_meHWWjYQFrhYgo4zn1WPASKOV8P6TFuPxmjyjK1oHB4pEEoUysZKUC0h14Gh9uP65raNjjkYb3hjIGaKPyxJxgV9Ojo9-blpEQenWsX5MPugHurzw_KKFzGuA41XYJSMW8LaGHL8L5a50xd2yWrOt7vz1xMCzcZgRVreTMCXIXO5Fj5r3XzqN2UVVbRPDvUmxHg1wWn6obKV9-fUrtpWSIEStMtbZI3UOuy0DEuIJFZhwzkhuM8ndvizQNVImibFXlBHuypyPZXhEoq8rMLnT2vAvKEp2GIVVx0iihHHAQmWLkZZj2D4YUFt3p6s2VrVbOoMk81YGiUJSdvlusJoVYM95c387LKHEtG8B96bJSFNhoZ36Uw2lBpRR6eNm67X1mdkcvaljsl2M9LSSWDVq99FJwb9Al77-rmkuwYC&as=PkSwgunVLSL-UJ-vtFgNng&rapt=AEjHL4OBlGvjxnEfK3RSNxhzTd8WEmeHQjbJ3FmQiD_yHHNoxMJhhCFMsNYQWk2Q213_JcY59jrQsD7mpc2-f0IZwF8GL-qdXw&approvedScope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fwebmasters%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsiteverification
[Thu Aug 15 05:06:30.003010 2019] [:error] [pid 230290:tid 139634436241152] [client 115.110.127.198:61752] [client 115.110.127.198] ModSecurity: Warning. Operator GE matched 5 at TX:inbound_anomaly_score. [file "/etc/apache2/conf.d/modsec_vendor_configs/OWASP3/rules/RESPONSE-980-CORRELATION.conf"] [line "37"] [id "980130"] [msg "Inbound Anomaly Score Exceeded (Total Inbound Score: 5 - SQLI=0,XSS=0,RFI=0,LFI=5,RCE=0,PHPI=0,HTTP=0,SESS=0): OS File Access Attempt"] [tag "event-correlation"] [hostname "auniqueweb.in"] [uri "/errors/404_Forbidden_php.php"] [unique_id "XVToVC2Zms8iTPR3puoZqQAAAAE"], referer: https://accounts.google.com/signin/oauth/consentsummary?authuser=2&part=AJi8hANKftegMCj2Mc81b2qgexRZNKunrD7FoL_mHjMRKUqqmRXG--EUk0KPSJvaH4k0OqaeKZBjSLwcv7vQcWa1G6ASLwkaLf8r9fFvsoS2DpwiMgwOn6NXpw0qNwOcoqtwXHe9iEC9pVUJzxE6aF_wwglIBnVmuvCT3808Yztv3NmxhHVEtaiE3FXKSPLJ1uHSpx7wQkEDd7CH2iwmnddZ3o8dMFqQCyFtsLRJlA-8R0hYDDKaIoWhbstIybo6oLUo2XJYWyzLZSKAqtPIonplk7bFZUSX4wQkruueaIjmFNJ5BWzpJyQSws7cjWKNZQJ4E_SNzF62WrTaLRNzbjIuHhBhPY32Qrr5zDKdcdU90akUypX2sFwy3Vyyr_ak4qFw7fCzYeX8Xd7F80rn8PWUWaqwFWc-iYN2zRK3OuytZp9MoXbvF8aOS4HKtN2yjG0dkulxGDtHwLsPMvuN_Mr0Ixhi6T364oChSPPmPIaY6oly9hxOplCaDjMrwB5iYv66o2Micux1OHnegVWoGKT1Aew0LnVNtw4k-RN7ZXyhQxpMBzAUQ-UpvxTTWmpRvubySjL4IxKBIzXcEU8le4TdwpF0k1nI0CV_meHWWjYQFrhYgo4zn1WPASKOV8P6TFuPxmjyjK1oHB4pEEoUysZKUC0h14Gh9uP65raNjjkYb3hjIGaKPyxJxgV9Ojo9-blpEQenWsX5MPugHurzw_KKFzGuA41XYJSMW8LaGHL8L5a50xd2yWrOt7vz1xMCzcZgRVreTMCXIXO5Fj5r3XzqN2UVVbRPDvUmxHg1wWn6obKV9-fUrtpWSIEStMtbZI3UOuy0DEuIJFZhwzkhuM8ndvizQNVImibFXlBHuypyPZXhEoq8rMLnT2vAvKEp2GIVVx0iihHHAQmWLkZZj2D4YUFt3p6s2VrVbOoMk81YGiUJSdvlusJoVYM95c387LKHEtG8B96bJSFNhoZ36Uw2lBpRR6eNm67X1mdkcvaljsl2M9LSSWDVq99FJwb9Al77-rmkuwYC&as=PkSwgunVLSL-UJ-vtFgNng&rapt=AEjHL4OBlGvjxnEfK3RSNxhzTd8WEmeHQjbJ3FmQiD_yHHNoxMJhhCFMsNYQWk2Q213_JcY59jrQsD7mpc2-f0IZwF8GL-qdXw&approvedScope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fwebmasters%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsiteverification

**Comment by jamesozzie** [comment]
@writetoevv Can you try disabling Modsecurity temporarily before trying to setup Site Kit as you did previously?

**Comment by writetoevv** [comment]
This is from web-hosting support team:

**Unfortunately, as you mentioned that google has suggested to disable mod security, which is not possible on the server on which your websites are present, as there are multiple users on the server, and this mod security rule cannot be disabled**

**Comment by jamesozzie** [comment]
@writetoevv I have opened an issue specifically for this conflict with a ModSecurity configuration. You can keep track of it here, #412.

**Comment by writetoevv** [comment]
@jamesozzie appreciates ...

**Comment by jamesozzie** [comment]
Hi all, Site Kit support is now provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your questions or issues on there, where we would be happy to assist.

**Comment by pauldaddy** [comment]
I have such 403 Error too, how to fix it? 
Wordpress 5.3 website in bluehost.com
The latest google site kit.
https link.
Please tell me.

**Comment by amusdnom** [comment]
I have such Error 403. My website [learn4funs.com](https://www.learn4funs.com/)
Same problems happening my other website too website [grocery.lockheartz.com](https://grocery.lockheartz.com/)

The Error is just like bellow.


> It appears you don't have
> permission to access this page.
> 403 Error. Forbidden."
> 
I'm unable to activate google Site kit latest version too.
![image](https://user-images.githubusercontent.com/41697598/69400832-1bcd3c00-0d19-11ea-93a9-64a1670141ed.png)


how to resolve this issue  Any help would be a great relief for me. Please, some help me, please.

Thanks...

**Comment by poperodney** [comment]
@amusdnom  how did you do to solve your website issue ?

**Comment by amusdnom** [comment]
> @amusdnom how did you do to solve your website issue?

Problems not solved until now.  Remains the same.

**Comment by Schiocco** [comment]
The problem is not related to WordPress but to the hosting and apache. The URL provided by Google container some like https://www.googleapis.com/auth/userinfo.email and this url is blocked by the server.

**Comment by amusdnom** [comment]
> The problem is not related to WordPress but to the hosting and apache. The URL provided by Google container some like https://www.googleapis.com/auth/userinfo.email and this url is blocked by the server.

Then How can we solve this issue?

**Comment by Schiocco** [comment]
For me the issue was caused by Web Application Firewall (ModSecurity) I'm using a dedicated server with Plesk and I solve it with this help:  https://support.plesk.com/hc/en-us/articles/213378669-Website-is-not-available-with-enabled-ModSecurity-403-Forbidden

**Comment by Schiocco** [comment]
For me the issue was caused by Web Application Firewall (ModSecurity) I'm
using a dedicated server with Plesk and I solve it with this help:
https://support.plesk.com/hc/en-us/articles/213378669-Website-is-not-available-with-enabled-ModSecurity-403-Forbidden








[image: SCHIOCCO] <http://schiocco.com/>

**Comment by Schiocco** [comment]
From this week Support Board provides several tools for developers to make magic happen. Use our powerful WEB APIs and the APIs for PHP, and JS. Automate your work and create custom integrations. 
    
<http://tracking.schiocco.com/tracking/click?d=YN6d4_b-uSS8lqBrHSyap5WVes5j2AaWCUealMYHFUAi2DGcB37gD8--VbxDZxWenBjk0AERFO_axc1qu2PtXohNzzyBvkcptE96zrMM2ZuSo2qsDZ49nQDcmI6RnqRrbg2>

<http://tracking.schiocco.com/tracking/click?d=YN6d4_b-uSS8lqBrHSyap5WVes5j2AaWCUealMYHFUDjB_RKqFGb3vjMnrlI66AryN2DyVsNxSbNFNCOcszNZP3jQx5tJJpITHxTDbWyUhzaSRTqF976-JX3OwGP9hvfBA2>
Support Board API available!

         From this week Support Board provides several tools for developers to make magic happen. Use our powerful WEB APIs and the APIs for PHP, and JS. Automate your work and create custom integrations. The APIs' capabilities include complete users and conversations management, Webhook and events. View the docs 
<http://tracking.schiocco.com/tracking/click?d=I-UOHuuS_s3raSer4I1FD--mEsC44ADslxqpSEZRRQJ-qCVe5rLZQYPsbmaLAlshWq0-REmo6sJ48o2Ygy5_99QOG3OBtwCr6j4455to5U7-bT3ORcWkaGjB7GHr9XWclH9kKic0fkJIwZSEinbfMQE1>
here.
        
<http://tracking.schiocco.com/tracking/click?d=YN6d4_b-uSS8lqBrHSyap5WVes5j2AaWCUealMYHFUBBOW_INuN6e7CKiRQ6EyG_lPhIhrDMl_G5REstdmDwbHaMWw4X1l1IpxrwAvEa1bTxuIKFRMONpPjoUMxZAGcpOA2>
It's Friday!
Save $15 and use it for a drink!
          Use the promo code below and get a 50% discount on both Slack and Dialogflow Apps purchases.
        
          gnhgt6r
        
          Promo valid for a few more purchases only.
        
<http://tracking.schiocco.com/tracking/click?d=YN6d4_b-uSS8lqBrHSyap5WVes5j2AaWCUealMYHFUAMGFOmxbVKcHfFs3-U7CeiG9roCVVMS4G19WEmhaC6m6qunFFJCzkVCXu8_HIOKfezkw-C11YvZXvdV1IP0kZDKw2>
Visit board.support

          This email was sent to you by Schiocco LTD. By using our services, you agree to our 
          
<http://tracking.schiocco.com/tracking/click?d=-2x629vzN02BSGtkLXjbK2lkc7v5Xocd6q_bfshTy4h6P8saBXkbYSPm_Ot1MRy62mViCy3YldfsJG6Fd9b1iJvllgrsZm9XwafgWsG1DFGncwRnna1OdGZL6peLqDntrnFCHTWoTEmiroW-mZ74xdU1>
Privacy Policy. © Schiocco LTD 2020. All rights reserved.
          
<http://tracking.schiocco.com/tracking/unsubscribe?msgid=QH5YpJfPFw4RKfPHm12sHA2&c=1268602892835736070>
Unsubscribe

**Comment by Schiocco** [comment]
With the Tickets App, you can add a customer tickets area to your website, so that your customers can get immediate help from a single interface, in whatever form they like best.
    
<http://tracking.schiocco.com/tracking/click?d=IwlUVKhyKjnWVnXb9tDTcCeRTqOXr9bgKvuy6Sf9kDZSYm6MI_bV_PVV5GvxSZCmY77cvrd8jai2K_Mz04LCHh048-ANyuOCb-qJBxyZvl2pU0ntjnoynz6RhgqoDlAg0g2>

<http://tracking.schiocco.com/tracking/click?d=IwlUVKhyKjnWVnXb9tDTcCeRTqOXr9bgKvuy6Sf9kDY-hsYKYj6Erta-cEbowLX4QaqsF6A1DA_Gk5qMZtN2G1UYTaB9sCdSNNEFjT74fcxVIVPKLgPd-MHCgjRfbTpdXA2>
The New Tickets App is here!

          With the Tickets App, you can add a customer tickets area to your website, so that your customers can get immediate help from a single interface, in whatever form they like best. For more details click
          
<http://tracking.schiocco.com/tracking/click?d=uXjudGEQcq9tdxoeuI-KvGHUVOG2UwDtm5qCstgEX-tPmA9rKhTijMHDd6ds4BurczoQEyYBZ6lhIFNxjlppJfeKO3kAMcs0rHc5OPenplExKAVc6AHiIf2lK9bXmAJ0EikY6wlCnvk8M1UMEodp2aDpaik4nREIYPMPtml7IdLplTs8hyPzom5JefE-rK-KghP7-OuStGcIasbkrrhX1y9G-YGLJ_lL0wwTowsG9m730>
here.
        
<http://tracking.schiocco.com/tracking/click?d=IwlUVKhyKjnWVnXb9tDTcCeRTqOXr9bgKvuy6Sf9kDbE1fJ9A135Yr9KTXOMW_HpvBV_LiuvSjKHLzCl_qdRw3vtxULiSQT9Aeky4RTsC90baBn9cflG9dYIIHhcVj2SPw2>
Get 20% off Tickets App!
Promo valid only for the first 10 purchases!
          Use the promo code below and enjoy 20% off the first 10 purchases of the Tickets App.
        
          krso1ro
        
          Promo valid for the first 10 purchases only.
        
<http://tracking.schiocco.com/tracking/click?d=IwlUVKhyKjnWVnXb9tDTcCeRTqOXr9bgKvuy6Sf9kDYInbv9j06xjrAe8bGqb0HVfvhkiEaYBDfd7zLIpMTU5nTctF_4fuTVFqMA3VZU3kEU3lCt12FScSFDe0U0iiY8vw2>
Visit board.support

          This email was sent to you by Schiocco LTD. By using our services, you agree to our 
          
<http://tracking.schiocco.com/tracking/click?d=a5HGUq4Ye2qmzQpjqkbf7qO7kNIPi6hFHPssbjGjS07LDd80d_HW54TTtGJXxjrPeVHkuSpI2JWb1TAQSjx9W_is6CAvfaiJgEEgESUQJ7OyGbGJTggkFFVm6Cd9MEkJAMUGAHZXjbvRUzNcng64Msc1>
Privacy Policy. © Schiocco LTD 2020. All rights reserved.
          
<http://tracking.schiocco.com/tracking/unsubscribe?d=gewZbOm2kzGXJzqVAVFyFOLuX6JET8cVg7hjQtsd52rsfd58xmL2ZOQquzfBfRQC0UJ-RWeD9TH4l079M_zeSehuoGFAZlZwWpJerxheCwEG9y1qu5NgOc0Q90qbGUHmQcLT92kFonHlzZ_o1oLm_kc1>
Unsubscribe
