### ISSUE TITLE
Display more fresh Search Console data

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2284]
For a while now, Search Console has been able to serve fresher data than it used to: https://webmasters.googleblog.com/2019/09/search-performance-fresh-data.html

However, Site Kit hasn't updated to use this behavior, it still requests Search Console data with an offset of 3, which means that e.g. on 2020-10-29 it will only show data up until 2020-10-26. This should be adjusted so that Site Kit will show data from up until 1 day ago which is what Search Console makes available (i.e. on 2020-10-29 you should see data up until 2020-10-28).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Search Console should display data up until 1 day ago.
* The date range offset with which Search Console data is requested should be updated to just 1, instead of 3.
* This mostly applies to PHP right now, but if #2237 has already been implemented, it also needs to be ensured there.

## Implementation Brief

* Change https://github.com/google/site-kit-wp/blob/aaa92bf37c97aabf5fb1236579e04d26bafb3542/includes/Modules/Search_Console.php#L203 to be `1` instead of `3`.

### Test Coverage

* No addition tests needed.

### Visual Regression Changes

* This might alter VRTs; they should be updated if so.

## QA Brief

* Ensure Search Console data is not three days from today when viewed. In my testing of this I got Nov 3 when viewing on Nov 5, I think that might be the API just not having yesterday's data quite yet? 🤷🏻‍♂️ 

## Changelog entry

* Modify Search Console API queries so that they include results up until one day ago.

**Comment by felixarntz** [comment]
IB ✅ 

@tofumatt Shouldn't this be an estimate of 1? :)

**Comment by wpdarren** [comment]
### QA Update:  Pass ✅ 

**Verified:** 

On the latest version of SK within search console the data is 3 years old. When I activated the develop branch I could see that this fix has been implemented but please note observation below. 

![image](https://user-images.githubusercontent.com/73545194/98678695-ebebce00-2399-11eb-9f0e-5d9b333c1c38.png)

@asvinb in my search console, I can see data up to 11/08/2020, and was expecting to see data for 11/09/2020 since we're now on 11/10/2020.  When I login to search console though I see the same date. In the QA brief it mentions that it could be a delay in the API, so I have passed, but wanted to highlight my observation.
