### ISSUE TITLE
Introduce separate feature flag for `serviceSetupV2`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2309]
With [Service setup redesign](https://github.com/google/site-kit-wp/issues/2308) now being a separate epic from [User Input](https://github.com/google/site-kit-wp/issues/2035), let's use a separate feature flag for that.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A JavaScript feature flag for `serviceSetupV2` should be introduced that's only `true` for a development build.
* The splash screen logic that currently relies on the `userInput` (see #2046) feature flag should instead rely on `serviceSetupV2`.

## Implementation Brief

* Add `serviceSetupV2.enabled` to the `webpack.feature-flags.config.js` file. It should be identical to `userInput.enable` property.
* Update the `assets/js/components/setup/setup-proxy.js` file to use `featureFlags.serviceSetupV2.enabled` instead of `featureFlags.userInput.enabled`.

### Test Coverage

* Not needed.

### Visual Regression Changes

* No visual changes expected.

## QA Brief

* Check that the `serviceSetupV2` flag has been added to the `webpack.feature-flags.config.js` file and the `SetupUsingProxy` component uses it instead of the `userInput` flag.

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## QA ✅ 

**Note: `webpack.feature-flags.config.js` is now `feature-flags.json`**

---

✅  `serviceSetupV2` should only be enabled for a development build.
* https://github.com/google/site-kit-wp/blob/df4fea64e479c9299c969855f450a338760ae48d/feature-flags.json#L16-L18

✅  `SetupUsingProxy` is using the `serviceSetupV2` feature flag rather than `userInput`
* https://github.com/google/site-kit-wp/blob/97d4ed6a43af22ebeed6df508913ba3647623421/assets/js/components/setup/SetupUsingProxy.js#L128
* https://github.com/google/site-kit-wp/blob/97d4ed6a43af22ebeed6df508913ba3647623421/assets/js/components/setup/SetupUsingProxy.js#L131
* https://github.com/google/site-kit-wp/blob/97d4ed6a43af22ebeed6df508913ba3647623421/assets/js/components/setup/SetupUsingProxy.js#L149-L150
