### ISSUE TITLE
There is a vulnerability in lodash 4.17.19,upgrade recommended

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/site-kit-wp#2312]
https://github.com/google/site-kit-wp/blob/21464e98e574d80721aaf4551096e9acd915bf2f/package.json#L139

CVE-2020-8203

Recommended upgrade version：4.17.20

**Comment by aaemnnosttv** [comment]
Hi there, and thanks for the report!

According to the security advisory:
> Versions of lodash prior to 4.17.19 are vulnerable to Prototype Pollution.

This means that `4.17.19` was the first version not to have the vulnerability. Our `package.json` requires this as a minimum version, but the actual installed version may be higher.

I noticed a [few](https://nvd.nist.gov/vuln/detail/CVE-2020-8203) [places](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8203) reference the wrong version for this, but [the lodash changelog shows that this vulnerability was fixed in `4.17.19`](https://github.com/lodash/lodash/wiki/Changelog#v41719)

I'm closing this out because we are using a non-vulnerable version of lodash. Thanks again!
