### ISSUE TITLE
Add user's Site Kit capabilities to Site Health report.

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#2314]
## Feature Description

Add user capability information to the Site Kit section of the Site Health screen in order to assist debugging issues where users reports insufficient capabilities to use Site Kit (eg. they get an error: `You don't have permissions to authenticate with Site Kit.`). 

Site Kit uses a set of [primitive capabilities](https://github.com/google/site-kit-wp/blob/782d3697679bc478ebd5ca56dc0a935df07342a5/includes/Core/Permissions/Permissions.php#L24-L33) which are mapped to WordPress core capabilities. On the site health screen, we should add a `user_capabilities` section with a line for whether the user has each capability:  
`[Capability Name]: current_user_can( [CAPABILITY] ); `

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Site Kit section of the Site Health screen should include a "User Capabilities" entry that lists all Site Kit capabilities (the primitive capabilities declared in the `Permissions` class) and whether the current user has them or not.
* Visually this should look similar to the existing "Required scopes" list, with each capability accompanied by an emoji icon.

## Implementation Brief

* Add a new private function `get_capabilities_field` to the `Core\Util\Debug_Data` class:
  * It should return an array that contains the following elements:
    * `label` equal to `User Capabilities`
    * `value` - an associative array where each key is a capability slug defined in the `Core\Permissions\Permissions` class and value is either ✅ or ⭕ depending on whether the current user has that capability or not (see [get_required_scopes_field](https://github.com/google/site-kit-wp/blob/782d3697679bc478ebd5ca56dc0a935df07342a5/includes/Core/Util/Debug_Data.php#L310-L324) for reference).
* Add `capabilities` element to the `fields` array in the `get_fields` method. It should get a result from the `get_capabilities_field` function call.

### Test Coverage

* Not needed

### Visual Regression Changes

* Nothing should be changed on the plugin pages, but a new section should be added to the site health page.

## QA Brief

* Go to the Site Health page and open `Info` tab. You should see capabilities information in the site kit section.

## Changelog entry

* Include current user's Site Kit capabilities in Site Health report.

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Failed  ❌ 

**Fail:**

When SK is reset and the Google account is no longer connected the `googlesitekit_authenticate` and `googlesitekit_setup` user capabilities are checked :white_check_mark:  but not sure if this should be the expected behaviour. This site previously was connected so possibly that could be the reason why, but wanted to highlight this. 

![image](https://user-images.githubusercontent.com/73545194/98946150-79f8bd80-252e-11eb-8af0-bb22e80f8f61.png)

**Verified:**

- Viewed the Site Health page and Info tab.  Looked at the Site Kit data and can see the user capabilities information. 

![image](https://user-images.githubusercontent.com/73545194/98944846-a7446c00-252c-11eb-803d-dd3569633fd2.png)

**Comment by aaemnnosttv** [comment]
That looks expected to me @wpdarren. Those indicate that the user _can_ setup and authenticate which are necessary to use the plugin 🙂

The others that changed after you reset are based on being setup/authenticated already so that's why they turn red after reset. This probably should have been mentioned in the QAB as to what to expect, but it looks right to me 👍

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- Viewed the Site Health page and Info tab.  Looked at the Site Kit data and can see the user capabilities information. 

![image](https://user-images.githubusercontent.com/73545194/98944846-a7446c00-252c-11eb-803d-dd3569633fd2.png)

When SK is reset and the Google account is no longer connected the appropriate capabilities are ⭕ which as per the comment above is expected.   

![image](https://user-images.githubusercontent.com/73545194/98946150-79f8bd80-252e-11eb-8af0-bb22e80f8f61.png)
