### ISSUE TITLE
Expose date picker in Site Kit header bar and make it sticky

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2331]
A long-standing UX issue with the plugin has been the date pickers on the various screens since they are only shown on top of the page, which makes it cumbersome to adjust the date when looking at metrics further down on the page. This issue aims at improving this.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Site Kit header bar should be modified so that it's sticky, i.e. that it remains at the top of the screen when scrolling down. It should remain right below the WordPress admin bar in case the admin bar is sticky too.
    * Note that this might require some detailed look at admin bar scroll behavior across various viewports.
* On all pages where there is a date-picker, that date picker should be displayed as part of the Site Kit header bar (enabled via React component prop):
    * Site Kit dashboard
    * single URL details view
    * AdSense module screen
    * Analytics module screen
    * Search Console module screen
* The date picker UI and the new UI overall should look like in [this Figma file](https://www.figma.com/file/XxCBceEOfDsljYv9DNaJdS/Version-1---Sticky-header%2C-no-animation?node-id=0%3A1).

## Implementation Brief

- Using the file: `/assets/sass/components/global/_googlesitekit-header.scss`
  - Update styles for `.googlesitekit-header` to use `position: sticky;` with the `top` value taking into account the WordPress admin bar across all breakpoints.
- Using the file: `/assets/js/components/Header.js`
  - Update component to accept the `children` prop which will be outputted before `UserMenu`
- Using the file: `/assets/js/components/dashboard/dashboard-app.js`
  - Move the `DateRangeSelector` component to being a prop for the `Header` component
- Using the file: `/assets/js/components/dashboard-details/dashboard-details-app.js`
  - Import the `DateRangeSelector` component and use it as a prop for the `Header` component only if `currentEntityURL` is defined.
- Using the file: `/assets/js/components/dashboard-details/DashboardDetailsEntityView.js`
  - Remove the `DateRangeSelector` component
- Using the file: `/assets/js/modules/adsense/components/dashboard/AdSenseDashboardWidget.js`
  - Move the `PageHeaderDateRange` component to be a prop for the `Header` component
- Using the file: `/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidget.js`
  - Move the `PageHeaderDateRange` component to be a prop for the `Header` component
- Using the file: `/js/modules/search-console/components/dashboard/GoogleSitekitSearchConsoleDashboardWidget.js`
  - Move the `PageHeaderDateRange` component to be a prop for the `Header` component
- Create new file`/assets/sass/components/global/_googlesitekit-date-range.scss` which will contain all the styles for the date range within the `Header` component.
- Add another story for the `Header` in `/stories/header.stories.js` which contains the date picker.

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* When Scrolling the header should remain fixed under the wp admin header - check on mobile, tablet and desktop breakpoints
* Dashboard: Switching the date range from Last 7, 14, 30 and 90 days should update the data updates
* AdSense: Switching the date range from Last 7, 14, 30 and 90 days should update the data updates
* Analytics: Switching the date range from Last 7, 14, 30 and 90 days should update the data updates
* SearchConsole: Switching the date range from Last 7, 14, 30 and 90 days should update the data updates

## Changelog entry

* Move the date picker into the Site Kit header bar and make it sticky so that it is always visible when scrolling.

**Comment by felixarntz** [comment]
@asvinb 
> - Using the file: `/assets/js/components/dashboard-details/dashboard-details-app.js`
>   - Import the `DateRangeSelector` component and use it as a prop for the `Header` component.

Note that the date range selector is currently only used if there is a current entity (i.e. `DashboardDetailsEntityView`), and this should be maintained. So it should only be passed as prop if `currentEntityURL`.

It would be great to add a second version of the `Header` component that contains the date picker to Storybook so we have it there too.

Otherwise the IB looks solid, I'd advise to bump the estimate maybe to 7 since it might take some iterations to make this behave and look exactly as intended.

**Comment by asvinb** [comment]
@felixarntz IB updated as per your comments.

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ Engineer check

@benbowler here are two observations that I would like you to confirm if they are issues or expected. 

**Observations:**  

On Android and iOS mobile phones, the WordPress admin header was not sticky, so, the SK header scrolls with a gap at the top, rather than remaining at the top of the screen. [Screenshot](https://user-images.githubusercontent.com/73545194/100361835-9cfa9580-3035-11eb-8fcc-ac06bea80346.png) Is there anything we can do about this?

On Google Adsense. I am using the tester plugin because I do not have an account with real data, so this could be the cause of this issue but wanted to highlight it.  On Last 28 days, no values are appearing.  - [Screenshot](https://user-images.githubusercontent.com/73545194/100365416-6b37fd80-303a-11eb-8a9e-49ea147dc106.png) but as you can see on Last 7 days, there is data. [Screenshot](https://user-images.githubusercontent.com/73545194/100365526-90c50700-303a-11eb-8ebe-597349afa264.png)  There is also data for 14 and 90 days. Nothing for 28 days.  

Would you be able to try recreate this? 

**Verified:**

- When Scrolling the header remains fixed under the wp admin header - [Tablet screenshot](https://user-images.githubusercontent.com/73545194/100362172-09759480-3036-11eb-85a4-c7c6331af2ae.png) - [Desktop screenshot](https://user-images.githubusercontent.com/73545194/100362210-15615680-3036-11eb-9c39-64bb37d34b53.png)  Tests were completed on Windows, Mac, Android and iOS devices, using Browserstack. See observation above re. mobile devices. 

- Dashboard: Switching the date range from Last 7, 14, 28 and 90 days should update the data updates - [Screenshot](https://user-images.githubusercontent.com/73545194/100363428-ac7ade00-3037-11eb-9fa5-a50bea8f5f39.png)
- Analytics: Switching the date range from Last 7, 14, 28 and 90 days should update the data updates - [Screenshot](https://user-images.githubusercontent.com/73545194/100364885-abe34700-3039-11eb-8f6a-90a54608e41d.png)
- SearchConsole: Switching the date range from Last 7, 14, 28 and 90 days should update the data updates - [Screenshot](https://user-images.githubusercontent.com/73545194/100364870-a423a280-3039-11eb-8411-ffbc096d0dad.png)

**Comment by benbowler** [comment]
Hey @wpdarren, thanks so much for QA'ing this.

Based on your first point, I've updated in the PR above to make sure the [header only becomes fixed above 600px wide which matches when the wp admin bar becomes sticky](https://github.com/google/site-kit-wp/pull/2446/files).

To your second point, I set up the testing plugin on my machine with these settings:

<img width="546" alt="Screenshot 2020-11-27 at 08 56 36" src="https://user-images.githubusercontent.com/119352/100435200-87b55380-3095-11eb-91be-ee3642dc91f2.png">

For me the data does update correctly when switching the date range selector on the AdSense page:

<img width="1194" alt="Screenshot 2020-11-27 at 08 31 34" src="https://user-images.githubusercontent.com/119352/100435275-9f8cd780-3095-11eb-8758-8f0c3c776e26.png">
<img width="1196" alt="Screenshot 2020-11-27 at 08 30 58" src="https://user-images.githubusercontent.com/119352/100435327-aca9c680-3095-11eb-979e-e7908e950fe0.png">
<img width="1194" alt="Screenshot 2020-11-27 at 08 31 16" src="https://user-images.githubusercontent.com/119352/100435341-af0c2080-3095-11eb-89df-ef0505eda823.png">
<img width="1196" alt="Screenshot 2020-11-27 at 08 31 26" src="https://user-images.githubusercontent.com/119352/100435343-b03d4d80-3095-11eb-8a60-18f8ff0eb9e4.png">

**Comment by aaemnnosttv** [comment]
@wpdarren ready for another pass 👍

**Comment by wpdarren** [comment]
@benbowler @aaemnnosttv I am using the same site as yesterday and on develop branch, I am not seeing this change.  When I scroll down the page the Site Kit header is not sticky and scrolling down.  I reset, deactivated and reactivated the plugin, reconnected and refreshed the branch but not seeing the change.   

Please could you confirm if you are seeing the same behaviour?

**Comment by wpdarren** [comment]
@benbowler now on Android and iOS mobile phones, the Site Kit header bar is no longer sticky.  When I scroll down, the Site Kit header disappears.  You can see it in action on this screencast here https://d.pr/v/ayUJJU  I am assuming this is not expected behaviour?  To confirm, It is sticky on desktop and tablets one as per the screencast here https://d.pr/v/LyOaGU

**Comment by benbowler** [comment]
[Updated based on feedback from @wpdarren](https://github.com/google/site-kit-wp/pull/2449/files).

**Comment by aaemnnosttv** [comment]
Back to you @wpdarren 👍

**Comment by wpdarren** [comment]
### QA Update:  Pass ✅ 

**Verified:**

- When Scrolling the header remains fixed under the wp admin header - [Tablet screenshot](https://user-images.githubusercontent.com/73545194/100362172-09759480-3036-11eb-85a4-c7c6331af2ae.png) - [Desktop screenshot](https://user-images.githubusercontent.com/73545194/100362210-15615680-3036-11eb-9c39-64bb37d34b53.png) - [Mobile](https://user-images.githubusercontent.com/73545194/100739000-6f389680-3411-11eb-8d35-b9e6498e3eff.png) Tests were completed on Windows, Mac, Android and iOS devices, using Browserstack. 

- Dashboard: Switching the date range from Last 7, 14, 28 and 90 days updates the data - [Screenshot](https://user-images.githubusercontent.com/73545194/100363428-ac7ade00-3037-11eb-9fa5-a50bea8f5f39.png)
- Analytics: Switching the date range from Last 7, 14, 28 and 90 days updates the data - [Screenshot](https://user-images.githubusercontent.com/73545194/100364885-abe34700-3039-11eb-8f6a-90a54608e41d.png)
- Adsense. Switching the data range from Last 7,14,28 and 90 days updates the data -  [Screenshot](https://user-images.githubusercontent.com/73545194/100739207-b3c43200-3411-11eb-8290-b10bcb062486.png)
- SearchConsole: Switching the date range from Last 7, 14, 28 and 90 days updates the data - [Screenshot](https://user-images.githubusercontent.com/73545194/100364870-a423a280-3039-11eb-8411-ffbc096d0dad.png)

@benbowler this is perfect, thanks for fixing those issues!

**Comment by marrrmarrr** [comment]
LGTM
