### ISSUE TITLE
Investigate high instance of `profile_id_not_set` errors.

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#2358]
## Bug Description

Our new error logging has revealed an unexpectedly high rate of errors from the `POST:modules/analytics/data/report` endpoint with the message/code: `Analytics view ID not set. (code: profile_id_not_set)`. (Note that profile ID is called a "View" in the Analytics UI).

This happens at this [code point](https://github.com/google/site-kit-wp/blob/edafc3d19bc305f2d829fa50f83df63088e65858/includes/Modules/Analytics.php#L846).

This lookup happens for every data call in Analytics, since the profile ID is required for those queries. We need to determine what condition causes the profile ID to not be set, and avoid making queries in that case.

## Steps to reproduce

1. Activate Analytics, **do not complete setup**
1. Navigate to Site Kit dashboard
1. Observe response to `google-site-kit/v1/data/` includes many responses with the `profile_id_not_set` error code
1. Observe a "WP Error in data response" warning in the console for each

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/99418521-ca439700-2903-11eb-9a2f-4e5f01ddbbec.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should never issue a REST API request to `modules/analytics/data/report` when the Analytics module is not **connected** (it is not sufficient to check only for whether the module is activated). In other words, it should not be possible to run into a `profile_id_not_set` error through regular usage of the plugin.

## Implementation Brief

* Skip requests for modules which have not completed setup in `withData`
* Finish and merge #2382 (mostly adding a few more tests)

### Test Coverage

* Add basic test coverage for `withData` functionality, including the setup incomplete component rendering, and request skipping

### Visual Regression Changes

* N/A

## QA Brief

* The PR for this issue changes the way batch requests are handled which only affects legacy components
* Test with a production build
* Batch requests for modules which have incomplete setup should be skipped now (does not affect others in the same batch)
	- This means warnings in the console should no longer appear for these as well
* Test dashboard widgets on main Site Kit dashboard, WP dashboard, and module dashboard pages continue to display as before
	- Note: module dashboards are not reachable when the module's setup is not yet completed so this should only affect the first two
* Test with different modules in various states of active, active + setup complete, and active + setup incomplete
    - Analytics and AdSense are the only two modules which can be activated and require setup that have dashboard widgets that make requests

## Changelog entry

* Fix bug where Analytics widgets would fire their API requests even when the module wasn't completely set up, resulting in unnecessary error responses.

**Comment by aaemnnosttv** [comment]
My first thought is that this could be coming from E2E, although we do have code in place which should disable event tracking completely there 🤔

**Comment by aaemnnosttv** [comment]
@felixarntz @adamsilverstein the problem is because legacy components are still rendered when Analytics is active even if setup isn't complete which causes these requests to be made.

![image](https://user-images.githubusercontent.com/1621608/99418521-ca439700-2903-11eb-9a2f-4e5f01ddbbec.png)

To reproduce, simply activate Analytics but don't complete the setup and navigate to the dashboard. Analytics widgets will make many requests via `withData` because the data component is still rendered, even though setup isn't completed.

E.g. https://github.com/google/site-kit-wp/blob/aa6cdd0792898920dd626dd71b2d722663a50756/assets/js/modules/search-console/components/dashboard-details/DashboardDetailsSearchFunnel.js#L51-L62
https://github.com/google/site-kit-wp/blob/aa6cdd0792898920dd626dd71b2d722663a50756/assets/js/components/wp-dashboard/wp-dashboard-modules.js#L48-L60
https://github.com/google/site-kit-wp/blob/aa6cdd0792898920dd626dd71b2d722663a50756/assets/js/modules/analytics/components/adminbar/AnalyticsAdminbarWidget.js#L37-L53

We should use something like this instead: https://github.com/google/site-kit-wp/blob/aa6cdd0792898920dd626dd71b2d722663a50756/assets/js/modules/analytics/components/dashboard/DashboardUniqueVisitorsWidget.js#L161-L164
Note `whenActive` actually checks that the component is connected which the same as the legacy `setupComplete`.

**Comment by aaemnnosttv** [comment]
Turns out I was close but not completely correct about where the CTA was coming from. Only the inactive CTA is coming from the references above, however the setup incomplete component is coming from `withData` in the HOC's render method https://github.com/google/site-kit-wp/blob/aa6cdd0792898920dd626dd71b2d722663a50756/assets/js/components/higherorder/withdata.js#L272-L275

While this is fine for rendering the component, it does nothing to prevent a data request for such a module which is what's needed here.

**Comment by felixarntz** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA update: Pass ✅ 

**Verified:**

- For Analytics and Adsense modules with incomplete setup, no errors appear in the console - [Screenshot](https://user-images.githubusercontent.com/73545194/99685792-eb4fe780-2abd-11eb-8c18-9a3384bdf17d.png)
- For Analytics and Adsense modules with complete setup, no errors appear in the console  - [Screenshot](https://user-images.githubusercontent.com/73545194/99685907-0ae71000-2abe-11eb-897a-0d912f42dd17.png)
- Tested dashboard widgets on main Site Kit dashboard, WP dashboard, and module dashboard pages continue to display as before  - [Screenshot 1](https://user-images.githubusercontent.com/73545194/99686526-a0829f80-2abe-11eb-8cbf-332ed781d796.png) [Screenshot 2](https://user-images.githubusercontent.com/73545194/99686548-a5475380-2abe-11eb-9adb-b17d2347c24d.png)

**Comment by aaemnnosttv** [comment]
@felixarntz there was a regression introduced in the changes to `LegacyAnalyticsAllTraffic` that https://github.com/google/site-kit-wp/pull/2404 has been opened to fix.

**Comment by cole10up** [comment]
### QA ✅

Rested https://github.com/google/site-kit-wp/pull/2404 on latest release candidate.

**Passed**

![Site Kit by Google Dashboard ‹ Hellogoodbye1 — WordPress (2)](https://user-images.githubusercontent.com/57115907/99749836-11609200-2a94-11eb-8479-0add28525582.gif)
