### ISSUE TITLE
Analytics: Account doesn't seem to have access to this Analytics property

### ISSUE THREAD

**Issue by jagadeeshiba** [google/site-kit-wp#245]
We've detected there's already an existing Analytics tag on your site (ID 182117722), but your account doesn't seem to have access to this Analytics property. You can either remove the existing tag and connect to a different account, or request access to this property from your team.

**Comment by s0a0a0z** [comment]
the similar problem is here that I already have analytic account but couldn't connect SiteKit to analytic...
"Looks like you don't have Analytics account yet. Once you create it click "Re-fetch my account" and Site Kit will locate it." 

anyone there to sort it out
:)

**Comment by albnavper** [comment]
"Looks like you don't have Analytics account yet. Once you create it click "Re-fetch my account" and Site Kit will locate it."

I have this same problem.

**Comment by s0a0a0z** [comment]
No its not ... I have the said account but failed to connect... I re-fetch again and again but useless

anyways would you check to visit my site eyefashion.pk suggest me what other improvements needed

**Comment by jamesozzie** [comment]
@jagadeeshiba Have you added Analytics to your site previously? It's possible that Analytics was implemented via another plugin, via your active theme or by alternative implementation methods. If you want to share your site I can take a look.

@s0a0a0z @albnavper You might need to re-authenticate your Analytics account. In order to do so please first of all disconnect the Site Kit module (Site Kit > Settings > Analytics > Edit > Disconnect Analytics from Site Kit). Please then try add the module again.

**Comment by albnavper** [comment]
@jamesozzie didn't work. I even tried to disconnect the entire connection.

Thank you very much.

**Comment by jamesozzie** [comment]
@albnavper In order to troubleshoot further can you please try the following:

1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Ensure you have the correct and matching URLs (including 'https') in your [Site Settings](https://i.imgur.com/MkFLF0E.png)
3. Temporarily deactivate your other active WordPress plugins
4. Delete your existing Site Kit [project](https://i.imgur.com/EoA1edo.png) from your [Cloud Console ](https://console.cloud.google.com/cloud-resource-manager)and checking your [API key](https://console.cloud.google.com/apis/credentials), ensuring it has [no restrictions](https://i.imgur.com/p9c4S3M.png).
5. Install Site Kit in a new incognito window (so Chrome extensions/caching don't interfere). Be sure to use the same Google account which is connected to your Google Analytics profile.

**Comment by jamesozzie** [comment]
@jagadeeshiba Have you been able to troubleshoot the issue?

**Comment by rosscorp** [comment]
jamesozzie: the above fixed it! Thank you!

**Comment by aesstechindia** [comment]
resetting site kit and deactivating related plugins and then finally reconfiguring site kit worked for me

**Comment by jamesozzie** [comment]
@aesstechindia Great to hear it. If you run into any further issues or if you have any queries in relation to Site Kit you can reach us in the [WordPress support forums](https://wordpress.org/support/plugin/google-site-kit/).
