### ISSUE TITLE
Conflict with UpdraftPlus plugin when backup to GoogleDrive remote storage

### ISSUE THREAD

**Issue by ewanly** [google/site-kit-wp#246]
## Bug Description

I'm using UpfraftPlus plugin for site backup which also uploading the backup files to Google Drive for off-site disaster recovery. After I installed Site Kit, the connection of UpdraftPlus to Google Drive never succeeded (and generating errors) till I deactivated SiteKit plugin. 

## Steps to reproduce

Just install Site Kit on a website using UpdraftPlus with Google Drive connection.

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by mbdiener** [comment]
I am having the same issue. 

The error message received from UpdraftPlus is:
PHP Fatal error (TypeError) has occurred during deleteset subaction. Error Message: Argument 1 passed to Google_Client::__construct() must be of the type array, object given, called in /home/jwocinfo17/domains/dev.jwoc.info/wp-content/plugins/updraftplus/methods/googledrive.php on line 721 (Code: 0, line 92 in /home/jwocinfo17/domains/dev.jwoc.info/wp-content/plugins/google-site-kit/vendor/google/apiclient/src/Google/Client.php). 


Please contact UpdraftPlus support for info regarding their code.

**Comment by swissspidy** [comment]
Sounds like a dependency conflict.

UpdraftPlus includes version 1.1.4 of the Google API PHP client, while Site Kit includes version 2.x.

**Comment by MohamadFtah** [comment]
is there a fix for this? Iv'e disabled site-kit for now

**Comment by swissspidy** [comment]
There's currently no solution for this. There has been no discussion about it yet.

I imagine that the only solution would be to prefix Composer dependencies using a tool like [Mozart](https://github.com/coenjacobs/mozart) or [PHP-Scoper](https://github.com/humbug/php-scoper).

**Comment by mbdiener** [comment]
I received this response from UpdraftPlus’ support rep:

Hi Michael,
I’ve got a word from one of our lead developers.
We use the older version of Google API PHP to maintain backwards compatibility with older PHP and WordPress versions. Google Site Kit should also not be loading the Google API on another plugin’s page.
Please could you ask the Google Site kit developer’s if it is possible to prevent that plugin from running on specific wp-admin pages?
Regards,
Bryle

I’ve asked them to directly reply on this Github issues thread rather than having the end users sit in the middle of two development organizations.

Here’s my response to UpdraftPlus:

Hi Bryle,
I’ll be glad to post your response on the github issues page opened by another user. However, I strongly suggest that you or your developers respond on the page yourselves instead of having me or another UpdraftPlus user be the go between. I think it’s best if your technical folks discuss this with their technical folks.
Here’s the link to the github issue:
https://github.com/google/site-kit-wp/issues/246

**Comment by MohamadFtah** [comment]
@mbdiener and @swissspidy thanks for the update, hope its fixes soon, or at least a respond.

**Comment by swissspidy** [comment]
Related: #41, #223.

**Comment by madbradj** [comment]
Here is a screenshot and the problem still exists today. 
![Google site kit](https://user-images.githubusercontent.com/45303969/63635677-eacb6580-c65c-11e9-8834-2b7d579e7785.png)

**Comment by maciejmackowiak** [comment]
Hi @swissspidy when are you planning to implement this in the site kit plugin?

> 
> 
> There's currently no solution for this. There has been no discussion about it yet.
> 
> I imagine that the only solution would be to prefix Composer dependencies using a tool like [Mozart](https://github.com/coenjacobs/mozart) or [PHP-Scoper](https://github.com/humbug/php-scoper).

Without it I'm afraid that when you will publish the stable version into WordPress.org there may be a lot of errors like this:
https://github.com/google/site-kit-wp/issues/349

**Comment by swissspidy** [comment]
@maciejmackowiak I don't have an ETA for this yet, but rest assured that we'd address this before the stable release. At the moment Site Kit is still in Developer Beta to catch exactly these kind of issues :-)

**Comment by swissspidy** [comment]
We're now tracking work on this in #612.

**Comment by felixarntz** [comment]
We just merged the work on #612, so this should be fixed in the upcoming release.

**Comment by felixarntz** [comment]
This should be fixed in the latest rc.2 - please reopen if you still encounter issues with this.
