### ISSUE TITLE
Require SVGs for all images and remove unnecessary image support

### ISSUE THREAD

**Issue by caseymorrisus** [google/site-kit-wp#2468]
## Feature Description

All existing images should be removed and replaced with SVGs as we will only support SVGs going forward. Existing logic for handling images can be removed to simplify logic.

~~We currently need to explicitly append a global variable (`global._googlesitekitLegacyData.admin.assetsRoot`) to every image source that we use. This is a bit tedious and could be handled better via a Webpack loader that appends this variable to every image source automatically.~~

See [this conversation](https://github.com/google/site-kit-wp/pull/2313#discussion_r517701856) for the origins of this issue.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All plugin usage of non-vector images (e.g. `.png`, `.jpg`, ...) should be replaced with using SVG.
    * Note most non-vector images will be removed via #2285 or #2290 anyway.
    * Please ping @felixarntz / @marrrmarrr with a list of images where we need SVG replacements that we don't have.
* The `assets/images` folder should be removed and it should be removed from the build process.
* The `smallImage` and `winImage` props of the `Notification` component should be removed to encourage usage of vector images.
* Storybook stories using images should be updated accordingly and checked that they display as expected as well.

## Implementation Brief

- Please ping @felixarntz / @marrrmarrr with a list of images where we need SVG replacements that we don't have.
- Remove `allImagesLoaded` logic from `./storybook/preview-head.html` which can be found [here](https://github.com/google/site-kit-wp/pull/2173/files).
- Remove build infra and dependencies
  - Within `package.json` remove all `imagemin` related scripts
  - Remove all `imagemin-*` (dev)dependencies
- Remove images within `/assets/images/`
- Update usage of removed images to use vectors
  - **`logo-g_white_small.png`**
    - Create a new `Core\Util\Google_Icon` class which holds the source SVG string in an `::XML` class constant  
      - Add a public static `to_base64` method which returns a base64-encoded version of the html string
        ```html
        <svg viewbox="0 0 20 20"><path d="M17.6 8.5h-7.5v3h4.4c-.4 2.1-2.3 3.5-4.4 3.4-2.6-.1-4.6-2.1-4.7-4.7-.1-2.7 2-5 4.7-5.1 1.1 0 2.2.4 3.1 1.2l2.3-2.2C14.1 2.7 12.1 2 10.2 2c-4.4 0-8 3.6-8 8s3.6 8 8 8c4.6 0 7.7-3.2 7.7-7.8-.1-.6-.1-1.1-.3-1.7z" fillrule="evenodd" cliprule="evenodd"></path></svg>
        ```  
        _This was generated by using the source from the [`google` dashicon](https://github.com/WordPress/dashicons/blob/cd0fc2cb46f2d628ebe664ca40b9efc1b5eae95f/sources/svg/google.svg) icon in `@wordpress/icons`, importing it and rendering it as a string to optimize the output – we shouldn't need to change this any time soon._
    - Remove imported in `/assets/js/googlesitekit-base.js` which was a side-effect to load the image for the parent menu item.
    - Update [`$icon_url` argument to `add_menu_page`](https://developer.wordpress.org/reference/functions/add_menu_page/#parameters) in `/includes/Core/Admin/Screen.php` for admin menu icon to use the base64 encoded svg instead
        ```diff
        - $context->url( 'dist/assets/images/logo-g_white_small.png' )
        + 'data:image/svg+xml;base64,' . Google_Icon::to_base64()
        ```
    - Remove [inline styles for image icon](https://github.com/google/site-kit-wp/blob/8cdc1bb03800a297c0d931f0a0213d25079b6165/includes/Core/Admin/Screens.php#L118-L134) (or update if necessary to keep)
  - **`rocket.png`**
    - Used within `/assets/js/components/legacy-notifications/dashboard-setup-alerts.js` as `rocketImage` which is passed as the `winImage` prop for the `Notification` component. 
    - Used within `/stories/notifications.stories.js` as `rocketImage` which is passed as the `winImage` prop for the `Notification` component.
    - Remove `winImage` prop and replace with an SVG by importing the svg directly and passing to the `WinImageSVG` prop for the `Notification` component:
      ```js
      import RocketImageSVG from '../path/to/file.svg';
      <Notification
	      // ... other props
        WinImageSVG={ RocketImageSVG }
      />
      ```
  - **`sun-small.png`**
    - Remove reference in array as `winImage` in `/includes/Modules/AdSense.php`
    - Update `assets/js/components/Alert.js` to pass the new svg to all `Notification`s as the `WinImageSVG` prop as above
  - **`thumbs-up.png`**
    - Used within `/assets/js/components/settings/SettingsModules.js` as `thumbsUpImage` which is passed as the `smallImage` prop for the `Notification` component.
    - Used within `/stories/notifications.stories.js` as `thumbsUpImage` which is passed as the `smallImage` prop for the `Notification` component.
    - Remove `smallImage` prop and replace with an SVG by importing the svg directly and passing to the `SmallImageSVG` prop for the `Notification` component (see `rocket.png` example above)
- Remove existing image logic within the `Notification` component at `/assets/js/components/legacy-notifications/notification.js`
  - `winImage` and `smallImage` props are no longer used, remove conditional and rendering logic.
- All instances of `winImage` and `smallImage` props should now be replaced and these should no longer exist anywhere in the codebase
- Remove `image` arg from `\Google\Site_Kit\Core\Notifications\Notification` and doc blocks

### Test Coverage

 - Existing tests should still pass, no need to add new tests.

### Visual Regression Changes

* Should remain the same or if new SVG images look different (new design), it should be okay to accept changes.

## QA Brief

Open a location with each of the images to ensure it still works as expected:
**Logo SVG**
Load any dashboard page, make sure to hard refresh and ensure you don't get a flash of unstyled content as shown. https://github.com/google/site-kit-wp/issues/2468#issuecomment-782558059 
Add and set a custom colour scheme using e.g. https://wordpress.org/plugins/admin-color-schemes/ for your user to ensure the menu item has the correct colour when a non default admin colour scheme is used.

**Rocket SVG**
/wp-admin/admin.php?page=googlesitekit-dashboard&notification=authentication_success&slug=analytics

**Thumbs UP SVG**
After you write your first post

**Sun Small SVG**
Not sure.

See the new referenced backstop images for differences.

## Changelog entry

* Rely exclusively on SVGs for graphics and remove other image support.

**Comment by aaemnnosttv** [comment]
@felixarntz while the suggested change here would simplify our usage of the few images we use, perhaps we should redefine this issue to replace all images with svgs since images seem to be mostly a legacy thing for us (do we plan on adding images in the future?). Most of these are very much icon-like as it is (not sure if we can find the vector versions for all of these – if not perhaps we could replace them?). Several of them are specific to the legacy set up, legacy splash app, and publisher wins (which are being removed in #2285) as well. Of course we could keep support for images too, but they definitely seem to be more of an exception to the rule.

**Comment by felixarntz** [comment]
@aaemnnosttv I like the idea of changing our overall approach to only rely on SVGs going forward. IMO we don't need to fix/improve image handling then, and we could even consider removing image-specific props and behavior, to set a clear precedent that all images going forward should be SVGs. If we ever need to introduce an image that doesn't make sense as SVG (like a photo maybe), we could revisit, but I don't see that need coming up anytime soon.

I'll make this dependent on #2285 and #2290 since those will already remove a bunch of legacy images, and then we can take care of replacing the remaining ones with SVGs.

**Comment by aaemnnosttv** [comment]
@felixarntz ACs LGTM. We could also remove our use of `imagesLoaded` from our `.storybook/preview-head.html` which I added somewhat recently when attempting to fix the instability we were seeing although it ultimately didn't solve the issue at the time. Perhaps we should document this somewhere for the future, should we ever need to restore support for images.

**Comment by felixarntz** [comment]
@caseymorrisus @eclarke1 Looks like the remaining images that we'll need to get SVG versions/replacements of are:
* [logo-g_white_small.png](https://github.com/google/site-kit-wp/blob/develop/assets/images/logo-g_white_small.png)
* [rocket.png](https://github.com/google/site-kit-wp/blob/develop/assets/images/rocket.png)
* [sun-small.png](https://github.com/google/site-kit-wp/blob/develop/assets/images/sun-small.png)
* [thumbs-up.png](https://github.com/google/site-kit-wp/blob/develop/assets/images/thumbs-up.png)

Can we define an Asana task to find or recreate the above four images as SVGs?

**Comment by aaemnnosttv** [comment]
@caseymorrisus 

> [ logo-g_white_small.png ] Added to admin menu within `/includes/Core/Admin/Screen.php`.

This one could use a bit more clarification on what is needed here since this image the only one referenced in PHP as part of the admin menu item for Site Kit. In particular, we need to update the way the image is provided to [`add_menu_page`](https://developer.wordpress.org/reference/functions/add_menu_page/) via the `$icon_url` parameter. As noted in the linked docs, this supports a "base64-encoded SVG using a data URI, which will be colored to match the color scheme" which is what we want. "This should begin with 'data:image/svg+xml;base64,'." As an example, this is how it is implemented in the AMP plugin:
https://github.com/ampproject/amp-wp/blob/d048e956b1fde897feb3523e0475f2c71e2101f6/src/Admin/OptionsMenu.php#L141-L148
https://github.com/ampproject/amp-wp/blob/d048e956b1fde897feb3523e0475f2c71e2101f6/src/Admin/OptionsMenu.php#L34-L39

If we can, I think it would be preferable to avoid storing a hardcoded base64 encoded string and do that part on-the-fly.

Note, this may require some duplication since the source `svg` file won't exist in a production build since these are bundled into the JS instead.

Regarding this icon specifically, I think we can use the source of the latest [`google` dashicon](https://github.com/WordPress/dashicons/blob/cd0fc2cb46f2d628ebe664ca40b9efc1b5eae95f/sources/svg/google.svg). While `$icon_url` also supports using a dashicon, the google icon used to be for Google Plus and only very recently became the standard Google icon so we wouldn't be able to safely use that and be consistent across all versions of WP that Site Kit supports.

---

Also, would you please complete the last two sections of the IB for tests+VRT? These should always be filled out even if there are no changes to be made – then that would be fine to put there, but let's make sure nothing is missed in the process 👍

**Comment by aaemnnosttv** [comment]
Thanks @caseymorrisus ! Almost there, just a few details left to work out here.

> Rather than storing a hardcoded string, we can generate this on-the-fly using something like the following:
> ```php
> add_menu_page(
> 	$this->args['title'],
> 	__( 'Site Kit', 'google-site-kit' ),
> 	$this->args['capability'],
> 	$this->slug,
> 	'',
> 	'data:image/svg+xml;base64,' . base64_encode(file_get_contents($context->url( 'path/to/file.svg' )))
> );
> ```

This wouldn't work as-is since svg files are no longer included in production builds. Even if they were, this would result in an HTTP request for the URL of the svg on every page load which we shouldn't do.

Perhaps you meant `$context->path( 'path/to/file.svg' )` instead? This would be much more preferable but would require that we preserve or otherwise make the source file available since it will currently only be part of the JS bundles.

Regarding the replacements, you mention instances where the image is currently used, e.g. props to `Notification`. In cases like this, would you please elaborate a little to mention how they should be replaced?

In particular, for `sun-small.png` which you noted as "Passed into alert within `/includes/Modules/AdSense.php`" – let's define how cases like this would be handled where the icon to use is coming dynamically from the server side.

**Comment by caseymorrisus** [comment]
@aaemnnosttv Concerning SVGs being added to production builds, my current idea is to copy SVGs (ideally only those that are used) to the `dist` directory (copied later for release). This could be handled fairly easily using the [CopyWebpackPlugin](https://webpack.js.org/plugins/copy-webpack-plugin/). This would need to be added as a dependency.

@felixarntz `GET:notifications` within `AdSense.php` currently passes an image src to the `Notification` component `winImage` prop (`sun-small.png`) whereas the new SVG prop requires a component to be passed in. Should we create a one-off prop to allow us to pass a string here from PHP or is it possible to remove the requirement for this entirely?

**Comment by aaemnnosttv** [comment]
@caseymorrisus regarding the use of `CopyWebpackPlugin`, this would work but would bypass any configuration we have for svg optimization in the process, would it not? Ideally we could use our existing dependencies to "build" the one svg into the dist directory for use by PHP. If there isn't a simple solution for this using the build, then it might be a good idea to use a similar approach to the AMP plugin and just keep the svg string in PHP since it will not be changing any time soon (and not fuss with the build at all).

One idea about the notification component – maybe modules could have the option of registering their own `Notification` component and if present, notifications for that component would use its component, otherwise use the generic one. That way this graphic could live in that component and the server wouldn't need to handle it any differently. Thoughts @felixarntz ?

**Comment by aaemnnosttv** [comment]
@felixarntz we also have `includes/Core/Notifications/Notification.php` which has an `image` key in its `args`. I think these are intended to be remote images though for the most part?

**Comment by felixarntz** [comment]
@aaemnnosttv @caseymorrisus It looks like the `image` argument of `Notification` is only used by the AdSense notification. The remote notifications (`Notifications`) do not use the `image` argument, so let's remove this argument and its usage entirely.

For now, to keep the original UI, let's take care of that part fully in JS: For any notification returned by `modules/{moduleSlug}/data/notifications`, the sun SVG should be included. AdSense is the only module that currently has any notifications anyway. We'll likely revisit this in the near future anyway, but for now that should be a good working approach.

I wouldn't wanna add more complexity add this point around notifications. We'll holistically revisit notifications throughout Site Kit once we'll tackle the Notification Center epic.

**Comment by aaemnnosttv** [comment]
@felixarntz – I've taken over the IB here to finish it up so this is ready for another pass 👍 

I decided to take an alternate approach to how we handle the menu icon in PHP to [avoid reading extra files from disk when possible](https://github.com/google/site-kit-wp/issues/2806#issuecomment-779378714).

**Comment by felixarntz** [comment]
IB ✅

**Comment by ivankruchkoff** [comment]
With an SVG icon, it loads as black and then changes colour once some WordPress javascript loads to style it according to the theme colours. Looking into preventing that from occurring.

https://user-images.githubusercontent.com/373931/108583833-424d9e80-72f1-11eb-8017-91fa350c6a77.mp4

**Comment by aaemnnosttv** [comment]
@ivankruchkoff I think we just need to add `fill="currentColor"` to the `path` element of the svg. Can you give that a try? This way it should fill based on the current `color` style which I think _should_ eliminate the lag (or even the need for WP's svg painting).

**Comment by ivankruchkoff** [comment]
Unfortunately, that approach doesn't work.

**Comment by wpdarren** [comment]
### QA Update:  ⚠️ Engineer to Confirm

@ivankruchkoff I am observing the error below when visiting the dashboard. At the point of seeing the message, Adsense was not activated. So, I went ahead and activated Adsense using the tester plugin, and the error still appeared. It seems to appear on Site Kit Dashboard and also on the Adsense screen. I don't see the message on Search Console, Analytics, etc. 

The Rocket SVG does appear on the screen. 

Unsure it's related to the ticket but not noticed this message before. 

`https://domain.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-modules-adsense.85e7e6d975bb1941d252.js?ver=3a289f7060dd7d5c50af8a3166a8a186 GET https://domain.com/favicon.ico?google-site-kit=/adsense/pagead2.googlesyndication.com/pagead/js/adsbygoogle.js 404`

![image](https://user-images.githubusercontent.com/73545194/110327585-1eaa8800-8055-11eb-86cb-0fd85550be0b.png)

**Verified:**

- The Google Logo SVG loads on any dashboard with no unstyled content.  
Also loads fine with Admin colour scheme plugin used.  - [Screenshot](https://user-images.githubusercontent.com/73545194/110326540-be671680-8053-11eb-9580-b460b30f4fd2.png)

![image](https://user-images.githubusercontent.com/73545194/110326521-b7d89f00-8053-11eb-8927-5b56a53cf70c.png)

**Comment by aaemnnosttv** [comment]
> Unsure it's related to the ticket but not noticed this message before

@wpdarren – this is related to the adblocker detection we updated recently and is only 404ing because you don't have a [`/favicon.ico`](https://hivevine.com/favicon.ico). 😄

**Comment by wpdarren** [comment]
@aaemnnosttv hmm I have a favicon.ico, that's part of the reason why I was confused. So, I can ignore this error message? I've used this site may times before and this message has never appeared. No Adblocker is activated on my browser. I removed them all.

**Comment by aaemnnosttv** [comment]
@wpdarren if you look, your favicon references a path in `wp-content/uploads`, not [at the root of the site](https://hivevine.com/favicon.ico).

You see this 404 because the favicon is part of a fallback detection mechanism. No need to worry about this 404 though.

**Comment by wpdarren** [comment]
@aaemnnosttv any chance I could have a URL for Thumbs UP SVG and Sun Small SVG?  

I had a look through storybook but couldn't find them. 

**Verified:**

- The Google Logo SVG loads on any dashboard with no unstyled content.  
Also loads fine with Admin colour scheme plugin used.  - [Screenshot](https://user-images.githubusercontent.com/73545194/110326540-be671680-8053-11eb-9580-b460b30f4fd2.png)

![image](https://user-images.githubusercontent.com/73545194/110326521-b7d89f00-8053-11eb-8927-5b56a53cf70c.png)

- The Rocket SVG loads on  `/wp-admin/admin.php?page=googlesitekit-dashboard&notification=authentication_success&slug=analytics`

![image](https://user-images.githubusercontent.com/73545194/110332202-03427b80-805b-11eb-9cda-ff0738f09e89.png)

**Comment by wpdarren** [comment]
@aaemnnosttv @ivankruchkoff unable to get the thumbs up SVG notification on a site, when first post is published. I am still unsure where the Sun small SVG is appearing in Site Kit.  Need some more help to get this approved.  Do you have URLs that you could provide so I can go directly to the notifications? This would save me time.

**Comment by aaemnnosttv** [comment]
@wpdarren regarding the thumbs up, the normal "win" notifications where this was shown were recently removed. I think the only place left where it is used are for module notifications which are only for AdSense right now (I think). I'll see if we can use a mini plugin to trigger one for testing, otherwise this part will probably need to be a QA:Eng.

Will check on the small sun too.

**Comment by aaemnnosttv** [comment]
@wpdarren – the Thumbs Up graphic is only used on the Settings > Connect tab once all modules have been activated:

![image](https://user-images.githubusercontent.com/1621608/110691634-0de14a00-81ee-11eb-8847-ea9a8d0aef67.png)

It's also used in a story in Storybook for a notification here:
https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global-notifications--small-with-image

The small sun is only visible on module dashboards – specifically AdSense since it is the only module which supports notifications right now. I tweaked it locally to force a notification here and this is what it looks like

![image](https://user-images.githubusercontent.com/1621608/110692755-6238f980-81ef-11eb-96a2-cd0fc5e16d14.png)

> It's worth pointing out as well that a `Notification` with a `format="small"` and a `WinImageSVG` prop renders the image below the notification content which looks off. This may have been intentional or just never used though because the code for these styles hasn't changed since the initial release.

This looks like a regression since this placement uses the `<Alert />` component which didn't previously render any image at all, but we've added one now and the `Notification` uses the `small` format so it has the odd layout as a result:
https://github.com/google/site-kit-wp/blob/a7cf9f33f4ad978de376375e229012e2a2ff8cd8/assets/js/components/Alert.js#L80-L92

https://github.com/google/site-kit-wp/blob/9f92b89b0951af458063c7208608d2f3cbb7d1b9/assets/js/components/Alert.js#L86
**^^ This should be removed**

The same notification is also rendered on the main dashboard via `<DashboardNotifications>` > `DashboardModulesAlerts` which looks correct.
![image](https://user-images.githubusercontent.com/1621608/110693892-a11b7f00-81f0-11eb-958f-c59257fa17f0.png)

---

I'll open a PR to fix this quickly since it's a very small change.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> This looks like a regression since this placement uses the `<Alert />` component which didn't previously render any image at all, but we've added one now and the `Notification` uses the `small` format so it has the odd layout as a result:

Makes sense. The sun should only appear in these notifications on the Site Kit dashboard, not the module screens. I've missed that nuance during IB review.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- The Google Logo SVG loads on any dashboard with no unstyled content.  
Also loads fine with Admin colour scheme plugin used.  - [Screenshot](https://user-images.githubusercontent.com/73545194/110326540-be671680-8053-11eb-9580-b460b30f4fd2.png)

![image](https://user-images.githubusercontent.com/73545194/110326521-b7d89f00-8053-11eb-8927-5b56a53cf70c.png)

- The Rocket SVG loads on  `/wp-admin/admin.php?page=googlesitekit-dashboard&notification=authentication_success&slug=analytics`

![image](https://user-images.githubusercontent.com/73545194/110332202-03427b80-805b-11eb-9cda-ff0738f09e89.png)

- The Thumbs Up SVG loads on the settings page when all services are connected (`wp-admin/admin.php?page=googlesitekit-settings#connect`)

![image](https://user-images.githubusercontent.com/73545194/110780522-bd2a2980-829f-11eb-8519-4e2384cb4787.png)


The small sun SVG appears

![image](https://user-images.githubusercontent.com/73545194/110780378-979d2000-829f-11eb-9a57-11bc1a7f1c17.png)
