### ISSUE TITLE
Setup & Authorization Flow | Admin

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#250]
Set up Core Site Kit Functionality, Authorization flow. Note this was already started with WP Assure here: https://gitlab.10up.com/google/google-site-kit-tests/merge_requests/1 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

From a post-reset state: 
* Go to Site Kit splash page
* Fill in client configuration
* Sign in with Google (bypass this request and send back to authentication success URL)
* Verify the user is on the dashboard and seeing the congratulations message 

## Implementation Brief

* n/a

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@aaemnnosttv Which parts of the authorization flow does this cover exactly? I'm asking because from what I can tell, we have separate groups of E2E issues for handling the setup flow for various groups:
* second admin (#253, #254, #255)
* editor (#257, #258, #259)
* contributor (#261, #262, #263)

The title/description on all of these are very vague, so the above is based on my assumption for what they mean. Would be great to clarify.

I agree we generally need E2E issues for:
* initial setup flow for first admin
* setup flow for secondary admins (i.e. without step 1, and with Search Console property already set)
* authorization flow for editor (only includes Google OAuth flow)
* authorization flow for author/contributor (only includes Google OAuth flow)

To clarify, what we label as "setup flow", technically includes what we label "authorization flow" - as in an administrator also needs to grant access for scopes in order to set up the plugin.

**Comment by aaemnnosttv** [comment]
@felixarntz this test is currently for the initial setup for the first admin.

**Comment by lucymtc** [comment]
QA looks good. 

```
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
```

**Comment by aaemnnosttv** [comment]
Retroactively updating the estimate on this one to M to be more consistent with the change in scope that happened after work was started on it, per @lilybonney .
