### ISSUE TITLE
Adding links on the installed plugin page - "Rate Site Kit | Support"

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#2516]
## Feature Description

Following an open discussion with the UX stream of work, we recommend adding links on the 'Installed Plug-In' page to help encourage users to reach out for support, or write a review.

![image](https://user-images.githubusercontent.com/56588136/101766298-80049e80-3ada-11eb-9900-5a0341394072.png)

Adding "Rate Site Kit" and "Support" as two additional links. 
They should point to: 
https://wordpress.org/support/plugin/google-site-kit/reviews/#new-post
https://wordpress.org/support/plugin/google-site-kit/#new-post 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be two additional "plugin row meta" for the Site Kit entry in the Plugins list:
    * "Rate Site Kit" should point to https://wordpress.org/support/plugin/google-site-kit/reviews/#new-post
    * "Support" should point to https://wordpress.org/support/plugin/google-site-kit/#new-post
* This should be controlled by a new class within `includes/Core/Admin/`.

## Implementation Brief

* Add  a new class `includes/Core/Admin/PluginRowMeta.php` in the `Google\Site_Kit\Core\Admin` namespace.
* Add a private `get_plugin_row_meta` member function to this class
	* Returns: `string[]` link HTML for both links. E.g.
	  ```php
	  '<a href="#">' . __( 'Rate Site Kit', 'google-site-kit' ) . '</a>';
	  ```
	* Use the URLs and link text from AC.
* Add a public `register` member function. This function must add a filter as follows:
  ```php
  add_filter( 'plugin_row_meta', function ( $meta, $plugin_file ) { /* ... */ }, 10, 2 );
  ```
	- If the `$plugin_file == GOOGLESITEKIT_PLUGIN_BASENAME` then append the return value of the `get_plugin_row_meta` method to the `$meta` array  
  Otherwise, return the given `$meta` unchanged
* In the `includes/Plugin.php`'s `register` function, do the following
  ```php
  ( new \Google\Site_Kit\Core\Admin\PluginRowMeta() )->register();
  ```

### Test Coverage

* No new tests to be added

### Visual Regression Changes

* No changes

## QA Brief

* When you go to Plugins page in Wordpress admin, there must be two added links from the AC after "View Details" link. The links must point to the URLs mentioned in the AC

## Changelog entry

*

**Comment by kostyalmm** [comment]
@felixarntz we want to add the links as "`plugin_action_links`" or "`plugin_row_meta`"? 

"plugin action links" will add the link to the left side besides "deactivate"
"plugin row meta" will add the link to the right side besides "view details"

**Comment by felixarntz** [comment]
@kostyalmm Good catch - plugin row meta is the correct way.

**Comment by aaemnnosttv** [comment]
@kostyalmm would you please add an estimate?

**Comment by aaemnnosttv** [comment]
@kostyalmm – thanks for your IB, a few comments regarding the proposed approach:

> Add a public `build_row_meta` member function to this class
> Add a public `add_row_meta` member function.

These two proposed methods add the meta to the array via filter, and the other adds the filter. For adding actions/filters, let's simply use `register` as this is the convention used by all other classes.

Then only one other method is needed for getting the meta to add (this method can be private) – perhaps `get_plugin_row_meta` which would return `string[]`.

The `register` method can add the filter using an anonymous function as the callback which can append the meta from the `get_plugin_row_meta` to the value provided by the filter, if `$plugin_file === GOOGLESITEKIT_PLUGIN_BASENAME`.

> This function must add a filter if `is_admin()` as follows:

No need to use `is_admin()` since these filters are only invoked on the plugins page.

> $rate_site_kit = array( 'rate_site_kit' => '<a href="#">' . __( 'Rate Site Kit', 'google-site-kit' ) . '</a>' );

The `$plugin_meta` being filtered is simply an array of items that are joined with a pipe (`' | '`), so there's no need to make the links associative arrays (I think this format is only needed for action links). Each link should be a string of HTML which is appended to the array.

>   ```php
>  add_filter( 'plugin_row_meta', array( $this, 'rate_site_kit' ), 1, 2 );
>  ```

Apart from the changes mentioned above, we'd want the priority to be the default `10` (no reason to use an earlier priority here).

**Comment by kostyalmm** [comment]
@aaemnnosttv 
>The register method can add the filter using an anonymous function as the callback which can append the meta from the `get_plugin_row_meta` to the value provided by the filter, if `$plugin_file === GOOGLESITEKIT_PLUGIN_BASENAME`.
The `$plugin_file` value is `google-site-kit/google-site-kit.php`
and `GOOGLESITEKIT_PLUGIN_BASENAME` value is `/absolute/path/google-site-kit/google-site-kit.php`

Since these two aren't the same, I added the logic
`basename( GOOGLESITEKIT_PLUGIN_BASENAME )` is `google-site-kit.php`
and `$plugin_file` string contains this value.

**Comment by aaemnnosttv** [comment]
@kostyalmm I think you may be mixing the constants 🙂 

You originally had this defined using `basename( GOOGLESITEKIT_PLUGIN_MAIN_FILE )` where `GOOGLESITEKIT_PLUGIN_MAIN_FILE` is the absolute path to the `google-site-kit.php` file.

In my comment I used `GOOGLESITEKIT_PLUGIN_BASENAME` which is the relative path from the `plugins` directory which is what WP uses for the value of `$plugin_file` in the filter (and many other places). Note that this value is set by using [`plugin_basename`](https://developer.wordpress.org/reference/functions/plugin_basename/) which is different than PHP's `basename`.

e.g. using `wp shell`
```
wp> GOOGLESITEKIT_PLUGIN_MAIN_FILE
=> string(68) "/var/www/html/wp-content/plugins/google-site-kit/google-site-kit.php"
wp> GOOGLESITEKIT_PLUGIN_BASENAME
=> string(35) "google-site-kit/google-site-kit.php"
```

This is why I suggested this alternate conditional to use in my comment because `$plugin_file` will equal `GOOGLESITEKIT_PLUGIN_BASENAME` for Site Kit.

**Comment by kostyalmm** [comment]
@aaemnnosttv My bad 😅 . Thanks for pointing this put. Updated the IB accordingly.

**Comment by aaemnnosttv** [comment]
IB looks good for the most part. Just a few final points to clarify here:

> Add a private `get_plugin_row_meta` member function to this class
>	* Parameters: `$links`(`string[]`), `$plugin_file`(`string`). Returns: `string[]`
>	* If the `$plugin_file == GOOGLESITEKIT_PLUGIN_BASENAME` then do the following:
	It must append the links to the `$links` array. 

This method only needs to return the array to be appended, it doesn't need to accept a parameter to be mutated or appended to. The appending can happen in the callback to the filter. E.g. https://github.com/google/site-kit-wp/blob/42ec0aaa2a9b1861a8ad0288ebf7b3d86448617a/includes/Core/Authentication/Authentication.php#L288-L293

Of course, we still need to keep the condition with `$plugin_file` so it wouldn't be quite as simple as above but that's just an example. Doing it this way also avoids the need for the method to be public.

Note `array_merge` concatenates arrays when the two are indexed (lists) as they are in this case.

> Do the above for Support as well.

I'm not sure if you're suggesting that a dedicated method would be added for each meta item, but they can both be returned by the same `get_plugin_row_meta` method.

**Comment by aaemnnosttv** [comment]
@kostyalmm I made a few tweaks to the IB to get this moving since it was already very close, no need to go through another round 🙂 

IB ✅

**Comment by wpdarren** [comment]
QA Update: Pass ✅ 

Verified that the `Support` and `Rate Site Kit` options appear.

![image](https://user-images.githubusercontent.com/73545194/104025738-0a3a4280-5200-11eb-871e-42b4958c495c.png)

Rate Site Kit links to https://wordpress.org/support/plugin/google-site-kit/reviews/#new-post
Support links to https://wordpress.org/support/plugin/google-site-kit/#new-post
