### ISSUE TITLE
Authorization Flow | Editor

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#256]
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* This must be an alternate scenario for the E2E test from #250, #251, and #360. As such, it is blocked by these to be completed first.
* Editor goes to Site Kit splash page and sees the splash screen "Welcome to Site Kit", with product information.
* User clicks "Connect Your Account".
* User is forwarded to Google OAuth flow (needs to be intercepted similar to how it's done in the  above issues).
* User comes back and lands on the Site Kit dashboard.

## Implementation Brief

* N/A

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@bjackson27 @aaemnnosttv What is this about? An editor cannot "activate Site Kit". Could you please clarify?

Another note regarding workflows, please don't add a changelog entry when opening an issue. It should be provided when the implementation is clear, and in the specific case of E2E tests always be set to "N/A".

**Comment by circlecube** [comment]
Little note to mention this is partially blocked by #344

**Comment by circlecube** [comment]
Working through a snag on this with @aaemnnosttv and as a result we'll probably need to update the auth utility plugin. The admin state is not persisting for the editor user because the plugin filters values rather than sets them. So the utilities may end up having to move to rest endpoints in an mu-plugin rather than being plugin-based, since it's a bit weird to programmatically set values in the DB just by activating a plugin.

**Comment by circlecube** [comment]
Moved this back to To Do, until it has been unblocked.

**Comment by felixarntz** [comment]
QA passed
