### ISSUE TITLE
Make PHPUnit test setup self-contained (for local development)

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2578]
Right now the PHPUnit test setup requires some external things to be set up locally, such as installing the development version of WordPress in a directory and exporting a `WP_TESTS_DIR` environment variable with the path to it (although there are many alternative ways to do it) as well as setting up a MySQL database and configuring credentials for WordPress tests to connect to it.

For CI, this is (unfortunately) the preferred approach. Since the version of WordPress is coupled to its tests, we should keep the approach of downloading the full development version for CI (via `install-wp-tests.sh` script). Locally however, we don't need all that - the main thing we should focus on is making the local setup self-contained and allowing to run the PHPUnit tests _overall_ (e.g. against the latest WordPress version).

We should remove the requirements for external setup so that one can run PHPUnit tests locally by just running a few `composer` / `npm` commands.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be no external requirements for running PHPUnit tests locally (while still allowing for the existing approaches using e.g. the `WP_TESTS_DIR` or `WP_DEVELOP_DIR` environment variables to work).
* Running PHPUnit tests should be possible by solely relying on a few `composer` / `npm` commands.

## Implementation Brief

* Rely on [`wp-phpunit/wp-phpunit`](https://github.com/wp-phpunit/wp-phpunit) as PHP dev dependency to get the latest WordPress test suite.
* Rely on `roots/wordpress` as PHP dev dependency to get the latest WordPress version.
* Include a new `tests/phpunit/wp-tests-config.php` file, which refers to the above WordPress directory and uses the MySQL database from the local environment Site Kit already comes with (`bin/local-env`, MySQL container).
* Expose the port 3306 as 9306 in the `bin/local-env/docker-compose.yml` file for the `mysql` container, to ensure the database is accessible on that port (9306) from the outside.
* Modify `tests/phpunit/bootstrap.php`:
    * For the case that no WP test-specific environment variables are set, fall back to using the local standalone setup powered by the above two dependencies (latest WP version, as for basic local testing we don't need to replicate the entire CI flexibility of using different versions).
        * The conditions for the other environment variables should be kept and continue to take precedence, to allow for CI as well as users that would like to leverage a similar setup locally to still work as before.
    * Set the `WP_PHPUNIT__TESTS_CONFIG` environment variable to the `tests/phpunit/wp-tests-config.php` file so that the `wp-phpunit/wp-phpunit` test library knows where that configuration file is.
* Merge #2581.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Clone the Site Kit repository on a machine where you haven't set up the PHPUnit test environment yet (i.e. no `WP_TESTS_DIR` or `WP_DEVELOP_DIR` environment variables or some sort of other symlinking to automatically find the WordPress test suite (make sure base requirements such as Composer, Node, and Docker are present, as usual for development).
* Run `composer install` and `npm install`.
* Run `npm run env:start` to start the Docker containers.
* Run `composer test` to run the PHPUnit tests. They should now run without any further setup of your environment.
* Run `composer test:multisite` to run the PHPUnit tests again for a multisite environment.
* That's it (don't forget to run `npm run env:stop` to stop the Docker containers again).

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
Nice work @felixarntz ! This will be a much better developer experience 👍 

A few thoughts on the IB as it is now:

> Include a new `tests/phpunit/wp-tests-config-sample.php` file, which refers to the above WordPress directory and uses the MySQL database from the local environment Site Kit already comes with (`bin/local-env`, MySQL container).
> * Git-ignore `tests/phpunit/wp-tests-config-sample.php` so that anyone is free to use their own preferred approach, e.g. if they don't want to rely on the included WordPress directory or the MySQL database from the included Docker container.
> * Copy the sample config to the actual file location on `composer install`, so that this setup step is automatically done. Use the `-n` flag of the `cp` command to ensure it does not override, should the file already have been set up.

I think we have as much flexibility as we need without introducing this logic:
* This is why we ship a `phpunit.xml.dist` file and ignore the default `phpunit.xml`. A developer can then copy and customize the entire config.
* Supporting alternate values for `WP_TESTS_DIR` or `WP_DEVELOP_DIR` environment variables (and thus not using `wp-phpunit`) is already provides full control over everything else as this config file would only be loaded by wp-phpunit.

This approach would also require everyone to delete their `wp-tests-config.php` file any time we make an upstream change in the source/sample file, or copy it over, which isn't a great experience.

> Include the port 3306 in the `bin/local-env/docker-compose.yml` file for the `mysql` container, to ensure the database is accessible on that port from the outside.

This wouldn't work for anyone who already has the default port bound to something else. This was the case for me as 10up Local Docker that I use for normal development uses a global `mysql` instance across all site instances. I would recommend we use a non-standard port like we do for most other things already (Storybook, E2E) to not occupy default ports. How about `9306`? Then we only need to update the `DB_HOST` constant to include it in the config.

Otherwise, this looks good and worked well for me. I'll take a look at the PR as well and leave any additional comments there.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> I think we have as much flexibility as we need without introducing this logic

Agreed, I've adjusted that part.

> This wouldn't work for anyone who already has the default port bound to something else.

Good point, adjusted to use port 9306.

I've updated the PR as well.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
### **QA ✅**

- Ran composer install and npm install.
- Ran npm run env:start
- Ran composer test and composer test.multisite

All checked out, no issues on my end.
