### ISSUE TITLE
Dashboard Site Overview All Traffic Text is off centre.

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#2654]
## Bug Description

In Dashboard > Site Overview > All Traffic, the minimised pie chart has labels that are off centre when resizing the screen.

## Steps to reproduce

1. Open the Site Kit dashboard page ( wp-admin/admin.php?page=googlesitekit-dashboard ) with a window that is too narrow for mini pie chart to appear (see screenshot 3 for reference), _analytics module_ connected.
2. Resize window horizontally making it slightly wider.
3. Notice that the small pie chart has slightly off centre text (screenshot 1, right section)
4. Compare with screenshot 2 where text is centred.

## Screenshots

**Screenshot 1: Off centre**
<img width="823" alt="Screen Shot 2021-01-19 at 10 21 00 PM" src="https://user-images.githubusercontent.com/373931/105135422-d9ca9200-5aa4-11eb-9d97-0feb4a9b2ee2.png">

**Screenshot 2: Centred**
<img width="823" alt="Screen Shot 2021-01-19 at 10 23 03 PM" src="https://user-images.githubusercontent.com/373931/105135457-ebac3500-5aa4-11eb-83d2-bcbe21e4d6e1.png">

**Screenshot 3: Setup**
<img width="577" alt="Screen Shot 2021-01-19 at 10 25 29 PM" src="https://user-images.githubusercontent.com/373931/105135662-43e33700-5aa5-11eb-911c-7c3fb89a86dc.png">

## Additional Context

 - OS: OSX
 - Browser Chrome Version 87.0.4280.141 (Official Build) (x86_64)
 - Plugin Version 1.24.0
 - Device: Computer

Issue also occurs in Firefox 84.0.2 (64-bit) and Chrome Canary Version 90.0.4393.0 (Official Build) canary (x86_64)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
I'm not sure if this is worth fixing, but I was able to reproduce it on the Analytics module page in the `LegacyAnalyticsDashboardWidgetTopAcquisitionSources` component which is currently the only one left that looks like this.

Given it only happens when loading the page with a very small viewport and then resizing it larger, seems like quite an edge case. The problem isn't that the text is off center though – it's that the result is inconsistent with what is displayed when the page is loaded in a non-mobile viewport.

| Loaded in mobile first | Desktop load |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1621608/114538358-fae1ef80-9c5b-11eb-9254-cea213be1e58.png) | ![image](https://user-images.githubusercontent.com/1621608/114538401-09c8a200-9c5c-11eb-99db-95dc25ba8645.png) |

Seems like the benefits aren't really worth the effort, at least right now. cc: @felixarntz
