### ISSUE TITLE
Improve UX to close tooltips within charts

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#2659]
## Feature Description
For the new Analytics module on Site Kit Dashboard, when a user clicks on a slice from the pie chart, the tooltip is displayed. However in order to hide the tooltip, the user needs to click on the slice again which is not intuitive. The tooltip should be hidden whenever the user uses the "Escape" key or clicks anywhere outside of the pie chart.

## Steps to reproduce
Have a website connected to Site Kit that has a good amount of traffic.

- Go to 'Site Kit Dashboard'
- Scroll down to 'All Traffic'
- Look for the new Analytics module with users and the pie chart.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Condition for displaying the tooltip: when the user clicks on a slice of the donut chart
* Condition for hiding the tooltip: when the user clicks anywhere again (on the slice or outside of it) or presses the Esc key. 

## Implementation Brief
* Using `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/UserDimensionsPieChart.js`,
	* Upon component mount, add 2 global event listeners, namely `keyup` and `click`. In the callback function, check if the the `ESCAPE` key was pressed (imported from `@wordpress/keycodes`) or whether the click target does not have `.googlesitekit-widget--analyticsAllTraffic__dimensions-chart` as ancestor. If either of the conditions are true, then deselect the selected slice by setting `UI_DIMENSION_VALUE`, `UI_DIMENSION_COLOR` to a blank string and `UI_ACTIVE_ROW_INDEX` to `null`.
	* When component is unmounted, remove the 2 event listeners.

### Test Coverage
* No new tests to be added

### Visual Regression Changes
* N/A

## QA Brief

* Using the pie chart on the All Traffic Widget, verify that the ACs have been met.

## Changelog entry

* Improve UX to close tooltips within charts

**Comment by aaemnnosttv** [comment]
@asvinb is this still an issue? We've changed how tooltips work a few times now I think 🤔

**Comment by asvinb** [comment]
@aaemnnosttv Yes, I checked and it's still an issue.

**Comment by danielgent** [comment]
Just to mention something important here which may have been missed

**initial state - no slice selected**
![initial state - no segment selected](https://user-images.githubusercontent.com/8496063/118309360-7352ff00-b4ed-11eb-9e85-0cdf3f4c7c3f.png)


**segment selected after clicking**
![segment selected](https://user-images.githubusercontent.com/8496063/118309385-79e17680-b4ed-11eb-8f6c-7e9f19b07eba.png)

In order to return to the _Initial state_ **All Users** (initially a title but this becomes a link when a slice is selected)

Is this also what is wanted when clicking outside?

I can have more of a look, but it doesn't look like we get a huge amount of control with Google Charts (compared to more powerful libraries like Vx)


We're setting the behaviour so the tool tip appears when the segment is selected.  The library default looks like it's `focus`
```
if ( dimensionValue?.length ) {
	options.tooltip.trigger = 'selection';
} else {
	options.tooltip.trigger = 'focus';
}
```

We could just make the tool tips appear on hover as a quick fix

Additionally we also have a z-index issue on the tool tip
![zindex tooltip](https://user-images.githubusercontent.com/8496063/118309695-eb212980-b4ed-11eb-82c2-78f383047047.png)

**Comment by aaemnnosttv** [comment]
> In order to return to the Initial state (no segments selected) the user has to click All Users (initially a title but this becomes a link when a slice is selected)
> Is this also what is wanted when clicking outside?

@danielgent – no, this is only about the tooltip only, not about changing the selected slice.

> We could just make the tool tips appear on hover as a quick fix

This was something we did at one point and the problem there is that some tooltips (maybe only one) have links inside that can be impossible to click if only triggered by hover.

> Additionally we also have a z-index issue on the tool tip

The screenshot shows the tooltip over the header which looks a bit odd, but maybe better than if it was covered by the header; I think it could go either way. Are you're referring to the position where some libraries might decide to float it below instead based on scroll position or something else? We updated select menus to have a higher z-index than the header in a previous issue as some elements are otherwise hidden or potentially unselectable so this is somewhat similar. I agree it is a bit odd though.

**Comment by wpdarren** [comment]
### QA Update ❌ 

@johnPhillips an observation: as you can see from the screen cast when you click on the white area outside of the pie chart, the tooltip does not disappear.  When I clicked further away from the chart, it did close.  Just wondering if this is expected?

https://user-images.githubusercontent.com/73545194/131813867-4fa2b32a-0715-49c0-b554-df51208e44b4.mp4

**Comment by johnPhillips** [comment]
Thanks @wpdarren 

Yes, that's expected... at least from point of view of the IB:

> check if the the ESCAPE key was pressed (imported from @wordpress/keycodes) or whether the click target does not have  .googlesitekit-widget--analyticsAllTraffic__dimensions-chart  as ancestor

I implemented according to this, so if you click on the chart or chart container (see screenshot below - I've given it a red border), the tooltip is not closed.

<img src=https://user-images.githubusercontent.com/2470911/131817469-5b365e3f-15c0-4fdc-a9c3-f622790a4057.png width=300 />

However, you are right to flag it because now I look at it more closely, this seems not to be quite in line with the ACs:

> Condition for hiding the tooltip: when the user clicks anywhere again (on the slice or outside of it) or presses the Esc key.

So there does seem to have been some confusion along the way and I'm very happy to refactor this if required - @tofumatt can you advise?

**Comment by aaemnnosttv** [comment]
## QA ❌ 

@wpdarren @johnPhillips while this may be implemented according to the IB, the AC is not met – clicking anywhere outside of the tooltip does not cause the tooltip to be hidden and the boundary for where this takes effect seems almost arbitrary because it's invisible. As far as I can tell, the only thing that is really needed here is to change the selector checked to use `.google-visualization-tooltip` rather than `.googlesitekit-widget--analyticsAllTraffic__dimensions-chart` but maybe it's more complicated than that.

@johnPhillips can we take another look here to see if it's as simple as that?

**Comment by johnPhillips** [comment]
Sure thing @aaemnnosttv 👍

**Comment by johnPhillips** [comment]
So... it was a bit more complicated than that 😂

The same tooltip HTML (`.google-visualization-tooltip` etc.) is identical both when you hover over a slice and when a slice is selected, and we only want to close the tooltip in the latter case. So checking the DOM won't help as we get false positives. 

I ended up checking whether a slice has been selected using the values in Redux to determine if the tooltip was open.

**Comment by johnPhillips** [comment]
CC @eugene-manuilov - I hope it's ok to assign you for CR because you did it last time round and have a bit of context. See the discussion above 👆

**Comment by eugene-manuilov** [comment]
@wpdarren this is ready for another round of qa

**Comment by eugene-manuilov** [comment]
@wpdarren sending it to you for another round of QA

**Comment by wpdarren** [comment]
QA Update: ❌ 

@johnPhillips @eugene-manuilov afraid this is still an issue based on the ACs.  

When I click on the slice for the first time, the tooltip appears and when I click the slice again it disappears.  👍 
When I click on the slice for the first time, the tooltip appears and when I click on the white space around the pie chart (or anywhere on the page), or press the Escape key, the tooltip does not disappear. 

https://user-images.githubusercontent.com/73545194/132230361-76e5bfe7-a4d0-4564-ad33-2871130fc7d8.mp4

**Comment by johnPhillips** [comment]
That one's on me, sorry 🙈  
There was a typo in the logic that I didn't commit correctly. Sorry to waste your time Darren!

**Comment by eugene-manuilov** [comment]
@wpdarren back to you :smile:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- Verified the tooltip displays when the user clicks on a slice of the donut chart
- Verified that the tooltip is hidden when the user clicks anywhere again (on the slice or outside of it) or presses the Esc key.

**Comment by wpdarren** [comment]
### QA Update: ❌ 

Unfortunately, we broke the legends under the pie chart.  
When I click on one of the legends, the slice is not highlighted and the tooltip does not appear.  

John has created a PR to fix this, so it's now back in QA.

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

**Verified:**

Verified the tooltip displays when the user clicks on a slice of the donut chart
Verified that the tooltip is hidden when the user clicks anywhere again (on the slice or outside of it) or presses the Esc key.
Verified that when I click on a legend the tooltip appears aand slice is selected
Verified that the tooltip is hidden when the user clicks the legend. 

@aaemnnosttv @felixarntz this was a fix after the latest zip file was generated. I QA'd this on `main` 
Just letting you know in case you need to regenerate the zip file again.

**Comment by aaemnnosttv** [comment]
> Just letting you know in case you need to regenerate the zip file again.

Thanks @wpdarren – this happens automatically, it just takes a few minutes to run after the PR is merged 👍
