### ISSUE TITLE
Avoid two column layout for All Traffic widget on narrow viewports

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2663]
As noticed in https://github.com/google/site-kit-wp/pull/2661#pullrequestreview-572718835, the new All Traffic widget currently still tries to fit its content into a two column layout for rather narrow viewports, which results in a squished UI. For such narrow viewports, it should wrap into a single-column layout with two rows.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For narrow viewports (smaller than desktop), the new All Traffic widget should not use its regular two-column layout, but instead wrap its columns on top of each other into a single column.

## Implementation Brief

* Set the `mdSize` props on the two grid `Cell` elements in the `DashboardAllTrafficWidgetV2` component to `8` and remove the `smSize` props, so that on those viewports (tablet and phone) the full width is filled per column.
* Merge #2664.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Use a development build so that you can see the new All Traffic widget.
* On narrow viewports, there layout should be a single column instead of two columns like before, where the content barely fit.
* See comparison screenshots below for reference.

**Before:**
![Screen Shot 2021-01-20 at 2 53 40 PM](https://user-images.githubusercontent.com/3531426/105252393-2e681e80-5b32-11eb-83eb-361353246e9c.png)

**After:**
![Screen Shot 2021-01-20 at 3 11 28 PM](https://user-images.githubusercontent.com/3531426/105252396-31630f00-5b32-11eb-9235-8e7d358e8366.png)

## Changelog entry

* Fix layout of new All Traffic widget on mobile viewports to use a single column.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

On narrow viewports, the layout is a single column instead of two columns like before.  This was tested on various browser sizes on desktop and mobile. - Screenshots: [Phone](https://user-images.githubusercontent.com/73545194/105360690-d44f8200-5c33-11eb-9023-b801d75636db.png)  [Tablet](https://user-images.githubusercontent.com/73545194/105360802-f3e6aa80-5c33-11eb-9d73-92b7dd518fb6.png)

@felixarntz @aaemnnosttv This has passed but a UX/UI observation. On smaller screens not all of the dimension tabs are displayed. I realise you can swipe across to see the next tab but it is not obvious.  Would you like me to create a new ticket for this?  - [Screenshot](https://user-images.githubusercontent.com/73545194/105361024-360fec00-5c34-11eb-8cc0-8e9e266b5c7c.png)

**Comment by felixarntz** [comment]
@wpdarren Good point, definitely worth a follow-up issue. It's not super critical, but let's see if we can address it.
