### ISSUE TITLE
Tag Manager Snippet is output twice in AMP URLs

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2668]
As reported in the [WordPress support forums](https://wordpress.org/support/topic/tag-manager-code-snippet-inserted-twice/#post-13938356) the Tag Manager snippet is inserted twice in AMP URLs. 

Example duplicate snippet:

```html
<!-- Google Tag Manager added by Site Kit -->
<amp-analytics config="https://www.googletagmanager.com/amp.json?id=GTM-MH4PNSJ" data-credentials="include" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:1px;height:1px;" i-amphtml-layout="fixed"><script type="application/json">{"optoutElementId":"__gaOptOutExtension"}</script></amp-analytics>
<!-- End Google Tag Manager -->
```

This only started occurring since 1.24.0. Reproducible in support. 

## Steps to reproduce

1. Install the AMP plugin and set the mode to "Transitional" or "Standard"
2. Install Site Kit version 1.24.0 and setup the Google Tag Manager module
3. Access your site and view the snippet place via Site Kit (snippet is duplicated)

## Screenshots

![image](https://user-images.githubusercontent.com/41326532/105378016-4a87c080-5c03-11eb-8d59-f324f59753fb.png)

## Additional Context

 - Only occurs with 1.24.0
 - Reproducible in support, two sites tested
 - Snippets evident by viewing https://www.pribrat.cz/
 - GIF created showing example (happy to share if required)
 - Occurs with only the SC & Tag Manager modules active, no need for additional modules to be connected

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Tag Manager snippet should only be inserted once in AMP pages.
* It should be verified that the snippets for Analytics and AdSense are only inserted once (since potentially there could be a similar regression there).

## Implementation Brief

* Merge #2678

### Test Coverage

* Add phpunit tests to test the `Method_Proxy_Trait` trait.

### Visual Regression Changes

* Tags should be inserted only once after the fix for this ticket is implemented.

## QA Brief

* Install and activate the AMP plugin;
* Set up the plugin on your local;
* Activate and connect Analytics, AdSense, and Tag Manager modules;
* Make sure these modules insert their tags only once both on web and amp pages.

## Changelog entry

* Fix bug where Tag Manager and Analytics snippet could be inserted twice on AMP pages.

**Comment by felixarntz** [comment]
Potentially caused by #475? cc @eugene-manuilov

**Comment by eugene-manuilov** [comment]
@felixarntz IB is added and PR is created #2678

**Comment by felixarntz** [comment]
@eugene-manuilov How does #2678 fix the problem? Would be good if you could add a brief explanation on how your changes are related to the issue. I can see what the fix does technically, but I'm wondering, are we maybe adding an extra hook where we shouldn't?

**Comment by eugene-manuilov** [comment]
@felixarntz the `get_method_proxy_once` is intended to prevent proxied methods to be called multiple times, but due to the bug, it doesn't work correctly and let the protected method be called multiple times.

The AMP tag for the Tag Manager module uses three hooks for different actions to render the tag. Whichever action fires first, it should render the tag. The next actions shouldn't render it again which is not the case due to the bug.

My PR fixes the `get_method_proxy_once` method functionality and thus it fixes the issue with duplicate tags.

https://github.com/google/site-kit-wp/blob/df38a87cef996a23f35434400d5eac632b604df8/includes/Modules/Tag_Manager/AMP_Tag.php#L33-L43

**Comment by aaemnnosttv** [comment]
@felixarntz the main problem with the current implementation is that `$calls` is not passed (used) by reference so it will always be an empty array in the returned function since mutations are happening to a copy of the array rather than the array itself.
@eugene-manuilov see my comments on your PR as I think we can simplify this a bit further.

**Comment by eugene-manuilov** [comment]
Thanks, @aaemnnosttv! PR is updated.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by cole10up** [comment]
### QA ✅

Tested on a personal site. Installed AMP. Analytics and Tag Manager

Was able to confirm on AMP specific pages only one GMT Tag was added

![image](https://user-images.githubusercontent.com/57115907/106098331-b4b1d100-60ed-11eb-89f7-cb772b6a59a6.png)

Confirmed the functionality of Tag Manager and Analytics

Sending to Approval
