### ISSUE TITLE
Trigger authorization action hooks also for sites that do not use the proxy

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2693]
The `googlesitekit_authorize_user` action (receiving a new set of access token and refresh token) and `googlesitekit_reauthorize_user` action (receiving a new access token using a refresh token) are currently only fired when using the proxy. `googlesitekit_authorize_user` was originally introduced like that because the proxy includes some extra arguments in the response, but that's not really a good reason to not fire that hook for other sites that use manual OAuth credentials and directly access Google's OAuth infrastructure. `googlesitekit_reauthorize_user` was simply put behind the same flag for parity with the existing action.

We should change it so that these actions run regardless of whether or not a site is using the Site Kit authentication proxy, since the action names are not specific to that and imply a certain action that is also relevant without the proxy.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `googlesitekit_authorize_user` and `googlesitekit_reauthorize_user` actions should be fired regardless of whether the proxy is being used. The `TODO` comments around the clauses should be removed accordingly.
* Any callbacks hooked into one of these actions should be individually reviewed, and it should be determined whether they need to be modified:
    * If the callback relies on data in the `$token_response` action parameter that is only present when using the proxy, it should be ensured this callback does not cause an error when not using the proxy (e.g. because of an undefined array index).
    * If the callback performs functionality that is only relevant for the proxy (e.g. anything around user input, remote feature detection, checking proxy URLs, ...), the callback should receive an early return for when the proxy is not being used.

## Implementation Brief

* Update `includes/Core/Authentication/Clients/OAuth_Client.php`, removing the if statement around the `googlesitekit_authorize_user` action trigger *and removing the TODO: comment*:

https://github.com/google/site-kit-wp/blob/fb2bbdf94d435753a3c84f2a1064108144e390df/includes/Core/Authentication/Clients/OAuth_Client.php#L729-L745

---

* Update hooks into the action `googlesitekit_authorize_user`:
* Update `includes/Core/Authentication/Authentication.php` use of the `googlesitekit_authorize_user` hook to return early if the proxy is not being used, to prevent	`$this->set_connected_proxy_url();` and `$this->require_user_input();` being called in this case:

https://github.com/google/site-kit-wp/blob/baec79d391492896a1ac4d0b41a6c93ac67ccf5c/includes/Core/Authentication/Authentication.php#L295-L301

* The use of `googlesitekit_authorize_user` in `includes/Core/Authentication/Disconnected_Reason.php` [does not need to be updated at this point.](https://github.com/google/site-kit-wp/issues/2693#issuecomment-781264983)

*  The use of `googlesitekit_authorize_user` in `includes/Modules/Search_Console.php` [does not need to be updated at this point.](https://github.com/google/site-kit-wp/issues/2693#issuecomment-781264983)

https://github.com/google/site-kit-wp/blob/baec79d391492896a1ac4d0b41a6c93ac67ccf5c/includes/Modules/Search_Console.php#L66-L92

* Update `includes/Modules/Site_Verification.php` hook to return early if the proxy is not being used, to prevent	`$this->user_options->set( Verification::OPTION, 'verified' );` being called in this case:

https://github.com/google/site-kit-wp/blob/baec79d391492896a1ac4d0b41a6c93ac67ccf5c/includes/Modules/Site_Verification.php#L85-L90

---

* Update `includes/Core/Authentication/Clients/OAuth_Client.php`, removing the if statement around the `googlesitekit_reauthorize_user` action trigger *and removing the TODO: comment*:

https://github.com/google/site-kit-wp/blob/fb2bbdf94d435753a3c84f2a1064108144e390df/includes/Core/Authentication/Clients/Google_Site_Kit_Client.php#L187-L202

---

* There is only one hook using `googlesitekit_reauthorize_user` in the codebase currently:
* Neither the hook `googlesitekit_authorize_user` nor `googlesitekit_reauthorize_user` in `includes/Core/Authentication/Authentication.php` need to be updated as it is useful to store the initial version regardless of the authentication method.

### Test Coverage

* Ensure `AuthenticationTest.php` and `Disconnected_ReasonTest.php` pass after the above updates.
* No additional tests should be added.

### Visual Regression Changes

* There should be no visual regressions.

## QA Brief

* Confirm the hooks `googlesitekit_authorize_user` and `googlesitekit_reauthorize_user` are now called without restriction.
* Confirm each use of the hooks still triggers correctly and there are no errors using non-proxy auth.

## Changelog entry

* The `googlesitekit_authorize_user` and `googlesitekit_reauthorize_user` actions are now also fired when not using the authentication service flow.

**Comment by benbowler** [comment]
Added an IB and estimate.

**Comment by felixarntz** [comment]
@benbowler I think there are some things to review for the IB here:

The main part that needs to be changed here is that the two actions should _fire_ (i.e. `do_action` calls) regardless of whether the proxy is being used, so the related if clauses around the `do_action` calls need to be removed.

Then, all callbacks that are added to one of the two actions using `add_action` have to be audited in what they do, and whether that functionality is generally applicable or only relevant when the proxy is being used. If they are generally applicable, they don't need to be changed; however if they are only relevant when the proxy is being used, they need to receive a check that ensure they only are executed when that is the case. In other words, the responsibility for making the check whether the proxy is being used has to be moved from around firing the action itself to every individual callback where it is necessary.

Does that make sense? We can connect otherwise to discuss further.

**Comment by benbowler** [comment]
Hey @felixarntz,

I didn't include enough detail in the first round. I've gone through and mentioned each use of the above hooks and the one that should be updated.

**Comment by aaemnnosttv** [comment]
Thanks @benbowler –  few comments to iterate on here:

* Please avoid referring to specific line numbers in plain text since these can easily change by the time the issue is picked up for execution. It's better to refer to the change in a more abstract way (e.g. using method name, or "directions" to get there) or by using a [permalink](https://docs.github.com/en/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet) to the code which will always point to the code at this point in time; that way we can easily find it if it moved.  
I noticed you did this in a few places already but sometimes applying the link to some describing text is a bit cleaner, if the embedded snippet isn't necessary.

Regarding your review of callbacks on the actions:

> `includes/Core/Authentication/Authentication.php:L296/L377` - Does not need to be updated because it does not rely on the `$token_response`.

This does need to be updated because both `set_connected_proxy_url` and `require_user_input` are proxy-only features/functionality. Like @felixarntz [said above](https://github.com/google/site-kit-wp/issues/2693#issuecomment-771288203), we need to be more considerate regarding what is being done, not only if the `$token_response` is used (in most cases, it isn't).

I won't go through them all but I think there may be a few more that need changes as well.

We can chat through the callbacks if there are any you're not sure about 👍

**Comment by benbowler** [comment]
Thanks Evan, I've been through and reviewed and updated them. Can you confirm I was correct for:

* `includes/Core/Authentication/Disconnected_Reason.php`
* `includes/Modules/Site_Verification.php`

As it wasn't immediately clear here what the delete and verification function do and whether they should be limited to the proxy.

**Comment by aaemnnosttv** [comment]
> Update `includes/Core/Authentication/Disconnected_Reason.php` to a full callback function which returns early if the proxy is not being used to prevent the `delete` function from being called

@benbowler the `Disconnected_Reason` class is an instance of `User_Setting` so it doesn't have access to know if the proxy is being used or not. There isn't really any harm in leaving this as-is even though the setting is proxy-specific. Looking at the other usage of it, we only ever set it if the user is using the proxy, but there are other places where we don't check that when its value is read. Updating these is probably beyond the scope of this issue if needed. I don't think we need to change this one though since there's no harm in deleting an option that doesn't exist, and even if it did for some odd reason, it should be deleted here. cc: @felixarntz 

> Update`includes/Modules/Search_Console.php` - Add a new check before using the $token_response as this won't be returned without proxy auth: `if ( array_key_exists('search_console_property', $token_response) && ! empty( $token_response['search_console_property'] ) ) {` to prevent an error:

This isn't necessary as the existing condition `if ( ! empty( $token_response['search_console_property'] ) ) {` is sufficient and will not result in an error/warning if the `search_console_property` key does not exist.

Otherwise this looks good to me. Back to you @benbowler to finalize.

**Comment by benbowler** [comment]
Thanks for looking through @aaemnnosttv I've updated it based on your comments above.

**Comment by aaemnnosttv** [comment]
IB ✅ 

@benbowler Regarding the estimate, 15 seems too high since this is mostly simple PHP changes which should be fairly straightforward to do. There may be a few tests to update but I would imagine 7 or maybe 11 would be sufficient. Is there something in particular that you're thinking of that might require a substantial amount of time?

**Comment by benbowler** [comment]
Hey @aaemnnosttv, agreed and updated. I added the estimate fairly early on, looking into each of the updates more closely 7 seems reasonable.

**Comment by benbowler** [comment]
QA brief added.

**Comment by felixarntz** [comment]
QA ⚠️ 

The `googlesitekit_authorize_user` hook in `Site_Verification` is always relevant, not only when using the proxy. Setting that user option has been around since the dawn of Site Kit, before there was the proxy. So the new check here needs to be reverted.

**Comment by aaemnnosttv** [comment]
> The `googlesitekit_authorize_user` hook in `Site_Verification` is always relevant, not only when using the proxy. Setting that user option has been around since the dawn of Site Kit, before there was the proxy. So the new check here needs to be reverted.

@felixarntz This still happens when Site Kit isn't using the proxy, it just happens in a different place which is specific to the legacy flow:
https://github.com/google/site-kit-wp/blob/5268ae9f21e589a8c3104a4d98f63b372a88a916/includes/Modules/Site_Verification.php#L186
https://github.com/google/site-kit-wp/blob/5268ae9f21e589a8c3104a4d98f63b372a88a916/includes/Modules/Site_Verification.php#L227

The added guard preserves the way it was before the changes in this issue to not potentially interfere with the legacy setup flow. It shouldn't be a problem as nothing else would have changed to influence that flow but we can of course remove it if needed 😄

**Comment by felixarntz** [comment]
@aaemnnosttv Ah thanks for clarifying - my bad, that makes sense.

**Comment by ivankruchkoff** [comment]
QA ✅

Created a mu-plugin for testing 
```php
<?php

add_action( 'googlesitekit_authorize_user', function() { error_log('googlesitekit_authorize_user');});
add_action( 'googlesitekit_reauthorize_user', function() { error_log('googlesitekit_reauthorize_user');});
```

On a public site with no dev/tester plugins:
[09-Mar-2021 20:13:29 UTC] googlesitekit_reauthorize_user
then after `wp google-site-kit reset --persistent`, and a reauth:
[09-Mar-2021 20:14:17 UTC] googlesitekit_authorize_user
