### ISSUE TITLE
All Traffic pie chart tooltip should only be shown on hover

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2701]
The tooltips on the new All Traffic widget pie chart should be changed to only show up on hovering the pie slice, they should no longer persistently appear when the pie slice is selected, since:
* Showing a tooltip apart from hovering is unintuitive UX.
* Hovering another pie slice will result in two tooltips being shown at the same time, sometimes overlapping each other (see screenshot).
* The data they surface is mostly already present in the total count and graph on the left, so they're duplicated.

![Screen Shot 2021-01-27 at 11 13 24 AM](https://user-images.githubusercontent.com/3531426/106041708-ffe9c680-6090-11eb-9ef6-2dbd91ed471d.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The pie chart tooltips in the new All Traffic widget should only be displayed when hovering over a pie slice. They should no longer be displayed when a pie slice is selected (unless of course that same pie slice is hovered over).

## Implementation Brief

* Merge #2707

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Set up the plugin on your local;
* Activate and connect the Analytics module;
* Go to the dashboard page;
* Make sure that the tooltip appears only when you hover over a pie slice in the user dimensions chart and doesn't stick when you select a slice.

## Changelog entry

* Modify pie chart tooltip behavior for new All Traffic widget so that tooltips are only shown when hovering over a pie slice.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Engineer to confirm ⚠️ 

@felixarntz @aaemnnosttv 

This is working as per the QAB but have an UX observation. 

When you have a tooltip with a link, if you hover away from a slice, the tooltip disappears, so you are unable to click the link. 

It depends on the placement of the slice and tooltip.  

On my test site I've not being able to demonstrate this but let's pretend that the Yellow slice is `Others` when I hover away from the slice the tooltip would disappear and I'd not be able to click on the link. 

![image](https://user-images.githubusercontent.com/73545194/106221094-e626bb80-6217-11eb-9579-cad29ed8c079.png)

This might not be an issue but wanted to flag it.

**Comment by felixarntz** [comment]
@wpdarren I flagged the same in https://github.com/google/site-kit-wp/issues/2709#issuecomment-769343573 and there has since a fix been added. I don't encounter this problem anymore on `master`, can you check?

**Comment by wpdarren** [comment]
`Can we maybe achieve it so that the tooltip remains there as long as you hover over the pie slice or the tooltip?`

@felixarntz I am using master. I have cleared my cache. The tooltip is slightly displayed further away from the pie chart, so you move your mouse to go over the tooltip to click on the link but it's not possible.  Of course, in the example below the blue slice doesn't have a link but if it did I would not be able to click it. I suspect it might also depend on the screen size. 

![pie](https://user-images.githubusercontent.com/73545194/106247983-4daa2e80-624b-11eb-9daa-1c379dbaca60.gif)

**Comment by aaemnnosttv** [comment]
@wpdarren 
> The tooltip is slightly displayed further away from the pie chart, so you move your mouse to go over the tooltip to click on the link but it's not possible.

In my testing, the only tooltip with a link (Locations for _Others_ slice) was always overlapping the slice and clickable.
![image](https://user-images.githubusercontent.com/1621608/106299385-c1553700-625d-11eb-8c09-b85006f7d139.png)

@felixarntz I think this is a good observation but probably shouldn't block the issue here (I'm also not sure we have that much control over the positioning of the tooltips). The main issue here IMO is that we probably shouldn't put links in these tooltips. Originally these were triggered on click only so using links inside seems more viable in that light but as-is I think we should probably find an alternate way to expose these (maybe below legend?) since these tooltips are more informational now.

**Comment by felixarntz** [comment]
@aaemnnosttv Agreed, it looks like having links inside these tooltips is not intended if the library makes them show up slightly away from the actual hover UI. But we should also investigate whether we can customize it so that these tooltips would _always_ overlap what is being hovered over.

@wpdarren @aaemnnosttv Can one of you open a follow-up bug?

**Comment by wpdarren** [comment]
@felixarntz @aaemnnosttv sure, I will create a bug ticket for this.

**Comment by wpdarren** [comment]
### QA Update: ✅  Pass

- The tooltip appears only when you hover over a pie slice in the user dimensions chart and doesn't stick when you select a slice.
