### ISSUE TITLE
Add support for breakpoint-specific sizes to `PreviewBlock`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2727]
The `PreviewBlock` component only supports a single `width` and `height`. This is not always sufficient, as the "loaded" versions of where the `PreviewBlock` is used may differ in height e.g. between tablet and desktop, or even desktop and larger desktops.

See https://github.com/google/site-kit-wp/pull/2712#pullrequestreview-579513552, where a workaround around this limitation was necessary.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `PreviewBlock` component should be expanded to support additional props `smWidth`, `smHeight`, `mdWidth`, `mdHeight`, `lgWidth`, `lgHeight`.
* The values passed to these props should result in the respective width/height only being applied in the specific viewport.
* `width` and `height` should continue to be supported, e.g. if no further specification per breakpoint is necessary, or as fallback.

## Implementation Brief
* Install the `@react-hook/window-size` [package](https://www.npmjs.com/package/@react-hook/window-size).
* Create new file `assets/js/hooks/useBreakpoint.js` which will export the `useBreakpoint` function. The function should:
	* use the `useWindowWidth` hook, from `@react-hook/window-size/throttled`
	* based on the width returned from `useWindowWidth`, return the following string if:
		* width > 1280: `xlarge`
		* width > 960: `desktop`
		* width > 600: `tablet`
		* default: `small`
	* The values above are the same as defined in the SASS variables file, to maintain consistency between the JS and CSS breakpoints. https://github.com/google/site-kit-wp/blob/develop/assets/sass/config/_variables.scss#L157-L162
* Edit the `PreviewBlock` component:
	* To accept the following additional props, all string:
		* `smallWidth`
		* `smallHeight`
		* `mediumWidth`
		* `mediumHeight`
		* `largeWidth`
		* `largeHeight`
	* Use the `useBreakpoint` hook to get the current breakpoint.
	* Add 2 new variables, `blockWidth` and `blockHeight` which should be initialized to the `width` and `height` props values respectively.
	* Update the output of the component to use the `blockWidth` and `blockHeight` variables when setting the width and height of the `googlesitekit-preview-block` container.
	* If the breakpoint is `small` and the props `smallWidth`, `smallHeight` are defined, set the `blockWidth` and `blockHeight` to the `smallWidth`, `smallHeight` respectively.
	* If the breakpoint is `tablet` and the props `mediumWidth`, `mediumHeight` are defined, set the `blockWidth` and `blockHeight` to the `mediumWidth`, `mediumHeight` respectively.
	* If the breakpoint is `desktop` or `xlarge` and the props `largeWidth`, `largeHeight` are defined, set the `blockWidth` and `blockHeight` to the `largeWidth`, `largeHeight` respectively.

### Test Coverage
* Add tests for the `useBreakpoint` function.

### Visual Regression Changes
* No visual changes should be reported because the new `*Width` and `*Height` props are not used for the time being.

## QA Brief
* Run storybook `npm run storybook`
* Visit the `Preview Block` story under `Global`
* The responsive `PreviewBlock` should have the following dimensions according to the breakpoints below:
	* 100x100 on when screen width <= 600px
	* 200x200 for screen widths > 600px and <= 960px
	* 300x300 for screen widths > 960px

## Changelog entry

* Enhance `PreviewBlock` JS component to support breakpoint-specific sizes via props.

**Comment by tofumatt** [comment]
I think the IB presented here will introduce a lot of `onResize` event handlers for the entire app, though having looked at what React hooks like [`@react-hooks/window-size`](https://www.npmjs.com/package/@react-hook/window-size) do, [it's similar](https://github.com/jaredLunde/react-hook/blob/16a1db0b06c48fd93b814b7e0b74c6f39ee5caab/packages/event/src/index.tsx#L4). Though they do clean up their event listeners, which wasn't mentioned in the IB.

I think the best bet is to use an existing hook to get the window size (I recommend https://www.npmjs.com/package/@react-hook/window-size), rather than implementing that logic ourselves. Part of me thinks: "Oh, it'd be better to have one listener installed in the `<App />` component that passes the width/height via context, but I think that's overkill/premature optimisation.

So let's try using an existing hook to get the width/height values instead, as they're more robust and saves us maintaining our own `onResize` handling code. I'd recommend using the Throttled API: https://www.npmjs.com/package/@react-hook/window-size#throttled-api

Also, a minor note: let's use non-abbreviated prop names for the sizes, eg `smallWidth` instead of `smWidth`. Or even better, `mobileWidth`, `tabletWidth`, and `desktopWidth`. That's a bit more illustrative.

**Comment by asvinb** [comment]
Thanks for the suggestion @tofumatt . I've updated the IB, can you review again?

**Comment by tofumatt** [comment]
IB ✅

I still think it might be nicer to use variable names like `mobileWidth` over `smallWidth`, because it more clearly indicates the intent of the prop. But I think that can be handled in code review, the approach here looks good to me! 👍🏻

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- 100x100 on when screen width <= 600px  - [Screenshot](https://user-images.githubusercontent.com/73545194/111644459-d4868b00-883a-11eb-81dd-bc522cc35f3f.png)

- 200x200 for screen widths > 600px and <= 960px - [Screenshot](https://user-images.githubusercontent.com/73545194/111644478-d9e3d580-883a-11eb-9eea-89afa1def6d4.png)

- 300x300 for screen widths > 960px - [Screenshot](https://user-images.githubusercontent.com/73545194/111644501-dea88980-883a-11eb-9a19-c350a5dddbe3.png)
