### ISSUE TITLE
Core Site Kit Functionality | Reset Site Kit 

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#273]
Set up Site Kit Settings | Reset Site Kit 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Test that when the user clicks "Reset Site Kit" (link at the bottom left of the Admin settings), all Site Kit services are disconnected for all users, 
* Test that any codes that were placed are removed. 
* Test that the plugin is deactivated for any additional users that had set it up. 
* UI: 
    * Confirm that the user sees a warning before proceeding ("_Resetting this site will remove access to all services. After disconnecting, you will need to re-authorize your access to restore service._"). 
    * Confirm that if they click "Reset", they will be taken to the first step of the Site Kit setup process. 

## Implementation Brief

* n/a

## Changelog entry

* Site Kit Settings | Tabs, editing functionality

**Comment by felixarntz** [comment]
@bjackson27 @aaemnnosttv What does "editing functionality" refer to?

**Comment by aaemnnosttv** [comment]
I believe "editing functionality" is specific to certain modules, such as Analytics which provide an edit link to change configuration of the service after it is connected (Settings > Connected Services).

This should probably be part of a module-specific test for modules that have editable configuration. I'm not sure we need a dedicated issue for testing generic functioning of the settings page since we already test other things on it, such as Reset and opt-in/out for tracking.

**Comment by marrrmarrr** [comment]
Agree that editing functionality or changing the status of a specific service is more relevant to the user flows for that service. 
What we can focus on in this issue is the various reset and disconnect functions (added in the AC section).

**Comment by marrrmarrr** [comment]
Re-scoped this to be only for the Reset functionality, since Disconnect is covered in #252

**Comment by aaemnnosttv** [comment]
We already have a test for Reset in #275 😄
