### ISSUE TITLE
All Traffic pie chart tooltip is too far away to click link

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#2737]
## Bug Description

For the new All Traffic pie chart, the tooltip is displayed slightly away from the slice. So, when you move your mouse to go over the tooltip to click on the link, it closes.  In the example below the blue slice doesn't have a link but if it did I would not be able to click it. I suspect it might also depend on the screen size. 

## Steps to reproduce

1. Go to 'Dashboard' and scroll to the new pie chart
2. Click on a Slice and observe position of tooltips

## Screenshots

![pie](https://user-images.githubusercontent.com/73545194/106247983-4daa2e80-624b-11eb-9daa-1c379dbaca60.gif)

--------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The All Traffic widget pie chart slice tooltips should always overlap their respective pie slice so that the user can move their cursor over there without leaving the pie slice, which would have the tooltip disappear, i.e. make it unreachable.
    * This might be hard to reproduce consistently, please check in different browsers.
* The "Others" tooltip should no longer include a link. It should instead have a text (different per tab / dimension name):
    * _See the full list of channels in Analytics_
    * _See the full list of locations in Analytics_
    * _See the full list of devices in Analytics_

## Implementation Brief

* Add the following code before the render in `GoogleChartV2`:
```js
if ( dimensionValue?.length ) {
	options.tooltip.trigger = 'selection';
} else {
	options.tooltip.trigger = 'focus';
}
```

### Test Coverage

* N/A

### Visual Regression Changes

* 

## QA Brief

* Click a pie slice.
* After the slice is selected, you should be able to move the mouse outside the slice and the tooltip should stay visible. This means you can select it.
* This should work on a browser window with a viewport larger than `1400px` wide.

## Changelog entry

* Show All Traffic pie chart tooltips persistently when a slice is selected to allow interaction with the tooltip, which would not be possible when hovering.

**Comment by tofumatt** [comment]
This component will use the new `GoogleChartV2` component, so marking it as blocked by that issue.

**Comment by tofumatt** [comment]
I a fair bit of time today going through Google Chart issues in GitHub/Google Code archives, Stack Overflow, etc.

Unfortunately this seems to be an issue with Google Charts that we can't resolve ourselves, if we want to maintain the hover/focus state only.

One thing to note is that this problem is especially bad on wider screens, because the chart is set to a width of 100%:

![2021-02-15 22 40 48](https://user-images.githubusercontent.com/90871/107999246-e3311680-6fde-11eb-90bc-92e9a459f9f3.gif)

But even on smaller screens or with the width of the chart locked to a max of `260px`, the problem persists. It's still possible to mouse over sections _inside_ the chart and have the legend be unclickable:

![2021-02-15 22 42 27](https://user-images.githubusercontent.com/90871/107999366-1ffd0d80-6fdf-11eb-9bb6-31c759ad8cd9.gif)

---

The issue is that the `tooltip: { trigger: 'focus' }` setting we use hides the tooltip as soon as the user moves their mouse outside the pie slice, even if the tooltip is still underneath the mouse cursor. There's no way around this with CSS because it's a JavaScript event and doesn't seem straightforward to override. Even if we did: it'd be hacky and not future-proof.

The only way to **fix** this is to change the trigger to "selection" instead of focus. Then the tooltip stays for as long as the `dimensionValue` is selected. The trade-off is that hover states are disabled while a value is selected and the tooltip stays visible for the whole time:

![2021-02-15 22 56 25](https://user-images.githubusercontent.com/90871/108000791-acf59600-6fe2-11eb-97ec-c3e7a520e829.gif)

But I think that's the best, most flexible solution, so it's what I've proposed in the IB.

**Comment by felixarntz** [comment]
@tofumatt Given the circumstances, I think this is a quite elegant solution - let's try that! IB ✅

**Comment by felixarntz** [comment]
@tofumatt I'll assign to you since that probably makes most sense as you've already spent considerable time in this and the V2 component.

**Comment by wpdarren** [comment]
This ticket is blocked until #2714 is fixed.

**Comment by wpdarren** [comment]
### QA Update: Fail ❌ 

@tofumatt   This works fine for every other slice other than those that has a link in the tooltip, i.e. `others` etc.  Right now, you cannot click on the `others` slice to make it active so that tooltip remains in the chart.  This is due to the issue reported [here](https://github.com/google/site-kit-wp/issues/2714#issuecomment-785674747) where you [mentioned](https://github.com/google/site-kit-wp/issues/2714#issuecomment-785876927) this is expected behaviour, but it does not resolve the issue here. 

Here's a screencast

https://user-images.githubusercontent.com/73545194/109165405-7a078b00-77b6-11eb-8451-bcebcf644280.mov

**Comment by felixarntz** [comment]
@wpdarren @tofumatt Just discussed this with Mariya, and I've added a new point to the ACs on this issue to get rid of the link in the "Others" tooltip.

We just need to exchange the link for regular text based on the ACs.

**Comment by felixarntz** [comment]
@aaemnnosttv Opened #2878 to address the above, ready for review.

**Comment by aaemnnosttv** [comment]
#2878 is merged now. Back to you @wpdarren for another pass 👍

**Comment by wpdarren** [comment]
QA Update: Fail ❌ 

@felixarntz @aaemnnosttv I'm afraid that this solution does not fixe the problem.  

On first load of the pie chart, if I hover over the `others` then the appropriate tooltip appears, and all is good. 

![image](https://user-images.githubusercontent.com/73545194/109237652-f7f68100-780c-11eb-9cf5-642afdd9637f.png)

But, if you select another slice first, e.g. `organic search` and then try and then hover over `others` no tooltip appears. 

This is because the `others` slice is no longer selectable.

You can see that in action on this screencast. 

https://user-images.githubusercontent.com/73545194/109237710-1492b900-780d-11eb-8911-0c8ecbf0eb21.mov

**Comment by felixarntz** [comment]
@wpdarren This is expected behavior now:

* The "Others" slice should never be selectable.
* The only way to see the "Others" slice tooltip should be to hover over the slice.
* Hovering over any slice only shows the tooltip though when no other slice is currently selected, to avoid the potential of two tooltips overlapping each other. This is the situation in your screencast.

Can you confirm this is the current behavior? If so, it should be good to go.

**Comment by wpdarren** [comment]
@felixarntz this is the current behaviour, so since this is expected, I will move this on. 

### QA Update: Pass ✅ 

- After the slice is selected, you can move the mouse outside the slice and the tooltip stays visible. 
- The "Others" slice is not selectable.
- The only way to see the "Others" slice tooltip is to hover over the slice.
