### ISSUE TITLE
Adding a "today" and "yesterday" tab option

### ISSUE THREAD

**Issue by bastbra** [google/site-kit-wp#2757]
## Feature Description

Hi,

I have a feature request (for the future, if this is possible): Can you add a “today” and “yesterday” tab in the overviews (Analytics, Search Console, AdSense)? Because just “last 7 days” etc. is too much, at least in my mind.
Also, a “active users in real time” for the analytics tab would be great.

Thank you for the great plugin!
---------------

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Many thanks for your suggestion. I've labelled this as a feature request for the team to review. While there is no ETA or guarantee this feature will be added to future releases the team do review such suggestions periodically.

**Comment by myedgy** [comment]
Any Updates?

**Comment by myedgy** [comment]
Any news? It's almost 1 year later for data that exist but needs to become available with a switch in the plugin.

**Comment by felixarntz** [comment]
@bastbra @myedgy Apologies for the long silence here.

After revisiting this issue, we can provide an update here:
* We are currently working on an entirely revamped way to select date ranges in Site Kit, based on an actual date picker so that you will be a lot more flexible in what you can select. It may still take a while to land in Site Kit, but it is prioritized on our roadmap. That mechanism will then replace the current dropdown with a few options entirely.
* With that said, while we could still add "Today" and "Yesterday" as options to the current dropdown as a temporary enhancement, unfortunately there are limitations which make this not very useful:
    * All Google services that Site Kit relies on do not provide data for the current day. Therefore "Today" would be a pointless option to provide.
    * Similarly, all Google services that Site Kit relies on provide very limited data or in some cases none at all for the previous day as well. So even "Yesterday" would be a hit-or-miss situation depending on what service you're using and what time of the day you look at the Site Kit data.
    * For these two reasons, we wouldn't be able to provide good value with these options, so it wouldn't make much sense to provide them. The limitations here are unfortunately out of our control as they relate to how the respective Google services aggregate and provide data.

We definitely see the value in seeing stats for today and yesterday, but unfortunately this is nothing we can provide at this point. This could be revisited in the future if the relevant Google services potentially expanded their capabilities to provide more short-term data.
