### ISSUE TITLE
Enhance logging of API errors to better support E2E debugging and iterate on E2E stability

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2777]
## Bug Description

Our E2E tests have become somewhat less stable lately and so this issue is about implementing a few changes in the way our errors are logged to better support debugging E2E failures which are almost always related to some unexpected API request which fails inconsistently.

Related to https://github.com/google/site-kit-wp/issues/2674, the changes here will help us to understand what requests are failing since the failures are not always easily reproducible locally; we somewhat rely on the transcript from CI to understand why it failed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Both modern and legacy API modules should log errors with all important details as strings, rather than objects,
    * `method`
    * `type`
    * `identifier`
    * `datapoint`
    * `error` (message)
* Batch requests should report errors for individual requests as `GET` rather than `POST` (which is an implementation detail of the batch request itself rather than the individual requests which are all `GET`)

## Implementation Brief

* Merge #2775

### Test Coverage

* No increases or reductions in coverage but some tests will need updating

### Visual Regression Changes

* N/A

## QA Brief

* Current E2E tests should consistently pass for builds on develop

## Changelog entry

* N/A

**Comment by ivankruchkoff** [comment]
Two approaches:

1) Via github actions CI test
https://github.com/google/site-kit-wp/pull/2775/checks?check_run_id=1864162827
https://github.com/google/site-kit-wp/pull/2775/checks?check_run_id=1864162832
https://github.com/google/site-kit-wp/pull/2775/checks?check_run_id=1864162771
https://github.com/google/site-kit-wp/pull/2775/checks?check_run_id=1864162765

Since it passes via github:
QA: ✅

2) Local test is timing out

<img width="725" alt="Screen Shot 2021-02-11 at 10 11 35 AM" src="https://user-images.githubusercontent.com/373931/107679590-9b626600-6c51-11eb-825d-c4dc7e3fbcd9.png">
