### ISSUE TITLE
>60s load time for some JSON endpoints

### ISSUE THREAD

**Issue by onpaws** [google/site-kit-wp#2778]
## Bug Description

I'm not sure this is a bug on the Site Kite side, or something else, possibly related to the hosting. Hoping anyone might have insight into where I might look to try and resolve.

## Steps to reproduce
1. Install Site Kit v 1.25.0 on WordPress 5.6.1
2. Setup domain on CloudFlare (default settings)
3. Configure Site Kit (connect Analytics/Ad Sense/Search Console to some Google account)
4. Login to WordPress admin and attempt to pull up the default Site Kit dashboard at 
     `https://example.com/wp-admin/admin.php?page=googlesitekit-dashboard`
While Site Kit's initial server-rendered page seems to load, all subsequent AJAX calls fail (request response time exceeds 60s).

## Screenshots
![image](https://user-images.githubusercontent.com/182515/107405118-4581a700-6b07-11eb-9a79-63a7179cc1ae.png)

## Additional Context
 - PHP Version:  7.4
 - OS: macOS
 - Browser Chrome 90.0.4412.0
 - Plugin Version 5.6.1
 - Device: MBP16" macOS 11.2

It behaves as if there is some side effect that loading the Site Kit dashboard triggers, that blocks all subsequent requests for around 60s (perhaps a bit longer). Even pulling up the public URL for this WordPress deployment also hangs, which makes me think PHP is blocking/hanging. (is there some kind of request queue cap?)

Sadly I don't have access to the server's error log, and [enabling](https://wordpress.org/support/article/debugging-in-wordpress/) WP_DEBUG, WP_DEBUG_LOG hasn't yet revealed any hints. 
I guess this is unsurprising b/c this looks like a request timeout, not necessarily a code error.

What might the dashboard be doing, that would 'max out' or otherwise tie up the PHP instance for quite some time? Enough to block the HTTP handler from even replying to subsequent requests for a while. Might there be some kind synchronous call(s) that somehow time(s) out?

Thanks for any insight you might have :)
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Thanks for opening a GitHub issue. We've moved Site Kit support to the WordPress support forums. If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to investigate this further. We can then reopen this issue should we determine any possible bugs or fixes to applied at plugin level. 

Note that the error you're encountering "Response is not a valid response" has came up previously, with third party plugin conflicts having resulted in these notices for users. I suspect this may be contributing to the loading delays encountered. Rather than deactivating other plugins we can troubleshoot this using the [Health Check & Troubleshooting](https://wordpress.org/plugins/health-check/) plugin. 

After opening a support topic feel free to share your Site Health information privately using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) so we can check your current setup.

**Comment by onpaws** [comment]
OK, will open a new issue support topic there. Thanks @jamesozzie !
