### ISSUE TITLE
Output .htaccess related factors which may result in Site Kit setup failure

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2803]
## Feature Description

With the Site Kit specific information added to a users site Health information there may be an opportunity to output any aspect of a users .htaccess file that may be resulting in setup failure. These may include redirects, caching configurations, modSecurity rules or REST API restrictions. Many plugins or hosting providers automatically insert these additions with particular configurations.

A simply non standard .htaccess file may be of use, or flags such "Http redirects" or "ModSecurity rules applied".

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@felixarntz Happy to create an Asana task for this if you want to review.

**Comment by aaemnnosttv** [comment]
Many sites don't use Apache as the web server (which uses .htaccess), so any checks we perform should be independent of the specific web server used. Also, warning about redirects or mod security rules may be more confusing than useful since these could be implemented by the host and the user may have no idea about them, what they are, or even able to change anything about them. Both could also be configured in a way which doesn't conflict with Site Kit.

We updated the setup compatibility checks to warn if the REST API is not available, so that much has already been done 👍 

Closing this out as the rest is not really actionable. cc: @felixarntz
