### ISSUE TITLE
Issue with Legends/Pie Chart on All Traffic Widget for a Single URL Dashboard Page

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#2865]
## Bug Description

As part of the QA for the All Traffic Widget on [Single URL dashboard page](https://github.com/google/site-kit-wp/issues/2856)  I've found two issues that are linked. 

1) For channel dimension. For a period of 28 days. There's a legend for `social` and `(other)` that have zero values, so I am assuming these should not appear.  They do not appear in the pie chart, just the legends. 

![image](https://user-images.githubusercontent.com/73545194/109000464-b667b800-76de-11eb-866d-51be8aa1da4a.png)

<details><summary>Non-issue hidden. (Click to expand.)</summary>
(Not an issue, <a href="https://github.com/google/site-kit-wp/issues/2865#issuecomment-785221206">see comment below.</a>)
<strike>
2) For channel dimension. When I extended the period to 90 days, the `(other)` option had 1 user, but it does not appear in the pie chart. I am assuming it should.
</strike>

![image](https://user-images.githubusercontent.com/73545194/109002458-33942c80-76e1-11eb-96e8-87d5626895eb.png)
</details>

I couldn't see any issues on other periods and the other dimensions appear to be fine on my test site. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The All Traffic pie chart legend should only include dimension values which are also present in the pie chart (i.e. have data).

## Implementation Brief

* Edit the `extractAnalyticsDataForPieChart` function:
  * Add a new option `hideEmpty` with `false` as its default value;
  * Don't add new row data to the dataMap array if the `hideEmpty` option is truthy and `users` equals to 0.
* Add `hideEmpty: true` option to the extractAnalyticsDataForPieChart function options in the UserDimensionsPieChart component.

### Test Coverage

* N/A

### Visual Regression Changes

* Empty slices should become hidden after implementing the aforementioned changes.

## QA Brief

To test this a channel dimension users data value needs to be set to zero in assets/js/modules/analytics/util/index.js extractAnalyticsDataForPieChart.  Then the legend for that users value should not appear beneath the pie chart.

## Changelog entry

*

**Comment by felixarntz** [comment]
@wpdarren I've specified the ACs around the first point of your observations. I'm not sure about your second point though - I think "(other)" is actually included in the pie chart in the screenshot, it's just so tiny that it's hard to see (since it's just one user). When I enlarged the screenshot, I _am_ seeing a tiny extra pie slice there, so I don't think there is a bug there. Can you check?

**Comment by wpdarren** [comment]
@felixarntz yes, you're quite right, the second issue can be removed. When I enlarged the screenshot, the slice can be seen.

**Comment by tofumatt** [comment]
IB ✅

**Comment by felixarntz** [comment]
After revisiting this, potentially the ACs here are actually incorrect and this may not be an issue at all:
* Analytics API already only includes rows that have data (greater than 0) by default (see https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet#ReportRequest.FIELDS.include_empty_rows).
* The reason "Social" is included in the above screenshot is because it _does_ have data in the previous period, so from that angle it's correct to include it even if in the current period it is `0`.

I'll discuss that with @marrrmarrr to decide whether that should be proceeded with or whether it is a non-issue.

**Comment by aaemnnosttv** [comment]
> Analytics API already only includes rows that have data (greater than 0) by default

@felixarntz [we include empty rows in our results](https://github.com/google/site-kit-wp/blob/0075f6de4035b67d5830ada399bbc8cdca9c5a37/includes/Modules/Analytics.php#L945) though because it was causing problems before without it. I don't think this would make a difference though, would it?

**Comment by felixarntz** [comment]
@aaemnnosttv Hmm good point. I guess I'm not clear then on what would currently happen. My expectation on how it should behave is:
* If you have 0 users in a channel in both the current _and_ previous period, **it should not show**.
* If you have 0 users in a channel in the current period, but had more than that in the previous period, **it should show**.

I think the logic currently is correct. In the issue description, "Social" only shows because there were users in the previous period, which is correct. When there are 0 users in both periods, it doesn't show.

**Comment by felixarntz** [comment]
I've confirmed the above with @marrrmarrr as the correct behavior of the plugin; while this is indeed a tricky scenario, this issue is actually invalid and does not require any changes.
