### ISSUE TITLE
Update "Your site may not be ready for Site Kit" messaging to reflect all cases

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#2908]
## Bug Description

As discussed in our 2 March Site Kit support meeting, the following error message appears after a user initially activates the Site Kit plugin:

_Your site may not be ready for Site Kit
Looks like you may be using a caching plugin which could interfere with setup. Please deactivate any caching plugins before setting up Site Kit. You may reactivate them once setup has been completed._

While this message does often correctly appear when a site has caching plugins installed, it also appears under other circumstances, including:

* Homepage altered - i.e. usage of a maintenance mode/coming soon plugin or Bluehost's development mode
* User is trying to set up via http in wp-admin when https is available
* User has their site URLs in wp-admin defined as http but their site redirects to https - very common in cases where the site was recently upgraded to https

It would be ideal to create distinct warning messages for each of these use cases, as opposed to using the caching message for all of them. Many users are confused by this message because they are not using a caching plugin and don't know how to troubleshoot.

## Steps to reproduce

1. Install the Minimal Coming Soon & Maintenance Mode plugin
2. Activate maintenance mode in Settings > Maintenance Mode > Enable Maintenance Mode > Save Changes
3. Install the Site Kit plugin
4. Activate Site Kit plugin
5. Warning message will appear

## Screenshots

![image.png](https://images.zenhubusercontent.com/6036809e6144b29061ec22c1/5ba62700-ecfe-40bf-84c1-98ba96213489)

## Additional Context

 - PHP Version: 7.3.26
 - OS: Mac
 - Browser Chrome
 - Plugin Version: 1.27.0
 - Device: Macbook Pro
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The copy shown when Site Kit cannot place/detect tags in the frontend (_Looks like you may be using a caching plugin which could interfere with setup. Please deactivate any caching plugins before setting up Site Kit. You may reactivate them once setup has been completed._) should be replaced with: _Looks like Site Kit is unable to place or detect tags on your site. This can be caused by using certain caching or maintenance mode plugins or your site's frontend is configured on a different host or infrastructure than your administration dashboard._

## Implementation Brief
* Using `assets/js/components/setup/CompatibilityChecks/CompatibilityErrorNotice.js`, update the text for the `ERROR_TOKEN_MISMATCH` case as per the AC.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes

* 

## QA Brief

* Disconnect the SK plugin, then install a Maintenance Mode Plugin and activate maintenance mode within it. 
* Now try connecting the SK Plugin. Check to see if the message is updated as per the AC.

## Changelog entry

* N/A

**Comment by marrrmarrr** [comment]
@felixarntz are we able to accurately detect all of the 3 sub-cases Bethany outlined in the description?

**Comment by felixarntz** [comment]
@bethanylang Regarding your first point, I've thought about this one, and I'm not sure how we can reliably detect that, so I'd suggest to modify the message we currently have to be more specifically about that Site Kit is not able to reliably place tags on the homepage / in the frontend, providing the use of a caching plugin or maintenance plugin as potential reason.

Regarding your 2nd and 3rd bullet points, I have a question: To clarify, you got this message because the site is redirecting to the respective other protocol than what is configured in WP (e.g. HTTP to HTTPS)? I'm not sure I fully understand.

If it's that, it shouldn't really be a problem at all. We should be able to follow the redirect for our checks the same as the browser would do. @aaemnnosttv Do we potentially have an issue that we don't follow redirects? 🤔

**Comment by jamesozzie** [comment]
@felixarntz I can jump in on this one. I did [some testing](https://app.asana.com/0/1185360131189553/1199938125092438/f) and I added steps to reproduce this in cases where a site is defined as http although it had https available. You'll find a recording of this in the task, with the caching notice easily reproducible.

**Comment by bethanylang** [comment]
Thanks, @jamesozzie! 

> Regarding your first point, I've thought about this one, and I'm not sure how we can reliably detect that, so I'd suggest to modify the message we currently have to be more specifically about that Site Kit is not able to reliably place tags on the homepage / in the frontend, providing the use of a caching plugin or maintenance plugin as potential reason.

@felixarntz That makes sense to me. Just make the language broader than "caching" would be really helpful here, so folks have a better idea of where to look.

**Comment by aaemnnosttv** [comment]
> Do we potentially have an issue that we don't follow redirects?

@felixarntz `fetch` follows redirects by default so that shouldn't be a problem.

**Comment by jamesozzie** [comment]
[One more example](https://wordpress.org/support/topic/the-necessary-verification-token-could-not-be-found-on-your-site-7/) in the support topics today, a user has a maintenance mode feature active (via their Bluehost CP as opposed to a plugin).

**Comment by felixarntz** [comment]
@marrrmarrr @bethanylang I've added some preliminary wording to the ACs here. What do you think?

**Comment by jamesozzie** [comment]
Another [example of this today](https://wordpress.org/support/topic/your-site-may-not-be-ready-for-site-kit/page/3/#post-15022918), from a user who isn't using a caching plugin.

**Comment by marrrmarrr** [comment]
Great. We can link to the new guide once it's published, that should give plenty of actionable advice to people. Thanks @bethanylang ! 
I updated the message copy slightly.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When the Maintenance Mode Plugin is activated and you try connecting the SK Plugin, the message is updated as per the AC appears on the dashboard splash page and also on the plugin page when trying to connect. 

`Looks like Site Kit is unable to place or detect tags on your site. This can be caused by using certain caching or maintenance mode plugins or your site's frontend is configured on a different host or infrastructure than your administration dashboard.`

![image](https://user-images.githubusercontent.com/73545194/145031918-d19b01e9-e292-4854-8d55-e4f37aceb295.png)
