### ISSUE TITLE
Couldn't initialize

### ISSUE THREAD

**Issue by jsmshay** [google/site-kit-wp#301]
## Bug Description

Pressing on GET OAUTH CREDENTIALS this errors pops up:

Couldn't initialize
A network error occurred and the request could not be completed.

## Steps to reproduce

1. Go to 'Site Kit Dashboard'
2. Click on 'developers.google.com/web/sitekit'
3. On Sitekit website - click GET OAUTH CREDENTIALS button
4. See error: 

Couldn't initialize
A network error occurred and the request could not be completed.

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@jsmshay Do you mind trying the following, the error you are encountering could be due to Ad Blocker, security plugin or chrome extension. 

1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. If you are using iThemes security can you uncheck [this](https://i.imgur.com/7OyyYyI.png) option from the general settings
3. Temporarily deactivate your other active WordPress plugins
4. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png)  

Please let me know if it works after you perform the above steps.

**Comment by Bannerman** [comment]
uBlock Origin was the culprit in my case, disabling solved. Thanks!

**Comment by jsmshay** [comment]
It was AdBlock that stopped it.
