### ISSUE TITLE
Ad Blocker incorrectly detected when using GoDaddy CDN

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3018]
## Bug Description

As reported in #3007 when using the GoDaddy CDN Site Kit is incorrectly detecting an Ad Blocker, resulting in non reporting of AdSense dashboards and the inability to connect the module. 

A temporarily workaround for impacted users is to deactivate this CDN configuration from their GoDaddy control panel. 

## Screenshots
 
![image](https://user-images.githubusercontent.com/41326532/112326956-e9d13e80-8cac-11eb-8a07-7313b237e123.png)

## Impacted Users

In addition to the helpful insights @rafapontederino provided there have been 3 additional reports in the support forms, details below, all occurring in the past week:

- [Report 1](https://github.com/google/site-kit-wp/issues/3007) _**unresolved**_ ([SH info provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNh0jEAF3gSYjbYC-KvfLitAqa3rI5m-STxEhLDndzyRh1SLB1MFHyEgOtE8r9nvsXg))
- [Report 2](https://wordpress.org/support/topic/ad-blocker-detected-you-need-to-disable-it-in-order-to-set-up-adsense-2) _**unresolved**_ ([SH info provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNik_JWvvqQPOfYIGqQPkDJ_chOIDKDXyImYwWERLGZKWeAXvlmD4K0LQj5ZPwE98Lk))
- [Report 3](https://wordpress.org/support/topic/ad-blocker-detected-you-need-to-disable-it-in-order-to-set-up-adsense-3) **_unresolved_** ([SH info provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNi7daldAUBE5p1kdG0XMwmH_gs9bp_betJdB_nRNjtKG7chm4J8iD92WV2NJxj9IuM))
- [Report 4](https://wordpress.org/support/topic/ad-blocker-detected-you-need-to-disable-it-in-order-to-set-up-adsense/) _**unresolved**_ 
- [Report 5](https://wordpress.org/support/topic/ad-blocker-detected-you-need-to-disable-it-in-order-to-setup-adsense-2/#post-14240356)  - **Unresolved** ([SH info provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNjxdeRRQ7g2rF3BmhpU1fVmEDnPM5xH5In2Ul0c4zyHzR-NU4mNvQDSS_SBD4b5g3o))

## Additional Context

- No common plugins between impacted users
- All sites fully secure with redirection in place
- No additional hosting level additions applied by original user who reported this
- [Unreproducible in support](https://recordit.co/3i12JVYko4) so far on GoDaddy hosting
- Incognito doesn't allow setup to proceed

Some screenshots kindly provided from original reporter below:

https://user-images.githubusercontent.com/41326532/112163215-b88d3b80-8be4-11eb-9546-29ae3b4b3fa7.png
![image](https://user-images.githubusercontent.com/41326532/112327943-c35fd300-8cad-11eb-95d0-4abfeb755ab5.png)

![image](https://user-images.githubusercontent.com/41326532/112327923-be9b1f00-8cad-11eb-8283-433ffb401bb7.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The fallback adblocker detection mechanism should receive "no adblocker" in the case of a redirect to avoid a potential false positive if the subsequent request is blocked

## Implementation Brief

* Merge #3055 

### Test Coverage

* No changes (see note in PR)

### Visual Regression Changes

* N/A

## QA Brief

**Engineering QA**

* Testing requires the server to be configured to issue a cross origin redirect for `/favicon.ico`, e.g. `http://via.placeholder.com/16`
    - Important: the response should not include a `Access-Control-Allow-Origin` header
* Any adblocker should be deactivated to ensure fallback is triggered
* Trigger adblocker check by going to Connect services with AdSense inactive
* See favicon request triggers redirect but does not result in an "adblocker detected" warning/error

**Standard QA**
* Test general adblocker detection continues to work as expected with various adblockers  
(uBlock Origin, AdBlock (Plus), AdGuard)

## Changelog entry

* Fix Ad Blocker detection issue which occurred on sites with GoDaddy CDN enabled.

**Comment by jamesozzie** [comment]
Another report added to primary context. Another user without a caching plugin with a migrating plugin active. Possible stale content on GoDaddy CDN.

**Comment by abdullah1908** [comment]
**Escalation Activity:**
Tried to recreate this issue on GoDaddy environment by enabling CDN but I couldn't see any AdBlock Detection. I can see a different errors in browser console that can be related to AdSense Account.
Steps Followed:
- Created new account on GoDaddy Demo Server
- Signed in User
- Configured AdSense account & I can't see any AdBlock detection error but can see some other errors on browser consoler.
_**By going through the SH info provided by the impacted user cache plugins & cache on hosting level might be the reason.**_

![adsense-godaddy-cdn](https://user-images.githubusercontent.com/14175927/112884284-c3663580-90e8-11eb-84b8-f5fd7ca26c32.png)

**Comment by aaemnnosttv** [comment]
Thanks @bethanylang – I see what's going on; will update this issue with next steps 👍

**Comment by ivankruchkoff** [comment]
QA:Eng ✅
QA ✅
1. Add redirect rule to nginx `rewrite ^/favicon.ico$ http://via.placeholder.com/16 redirect;`
2. Open http://sitekit.10uplabs.com/wp-admin/admin.php?page=googlesitekit-settings#settings/adsense/view

Before `98fcde0af` Release 1.29.0
<img width="830" alt="Screen Shot 2021-04-05 at 3 18 04 PM" src="https://user-images.githubusercontent.com/373931/113634009-dade7a80-9622-11eb-8048-2b278d0b988d.png">

After `2e18eb831` Latest develop
<img width="846" alt="Screen Shot 2021-04-05 at 3 18 12 PM" src="https://user-images.githubusercontent.com/373931/113634047-ef227780-9622-11eb-96f5-15580cf6e709.png">

QA:

- Chrome Version 89.0.4389.114 (Official Build) (x86_64) + uBlock Origin 1.34.0 -  Ad blocker detected, you need to disable it in order to set up AdSense.
- Chrome Version 89.0.4389.114 (Official Build) (x86_64) + Adblock Plus - free ad blocker 3.10.2 - Ad blocker detected, you need to disable it in order to set up AdSense.
-  Chrome Version 89.0.4389.114 (Official Build) (x86_64) + AdGuard AdBlocker 3.5.34 - Ad blocker detected, you need to disable it in order to set up AdSense.
- Brave Browser Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (x86_64) - Ad blocker detected, you need to disable it in order to set up AdSense.
- Tor Browser 10.0.14 (based on Mozilla Firefox 78.9.0esr) (64-bit) -  Ad blocker detected, you need to disable it in order to set up AdSense.

**Comment by bethanylang** [comment]
Noting that this issue also appears to be affecting SiteGround's CDN, as well, per https://wordpress.org/support/topic/adsense-unable-to-connect-ad-blocker-detected/page/2/#post-14287379.
