### ISSUE TITLE
Verify that Help/header icons should be highlighted in inactive state

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#3026]
## Bug Description

The Help icon is highlighted even when the menu is deactivated. 

## Steps to reproduce

1. Click on the Help icon, menu dropdown appears
2. Click on the Help icon again, the menu disappears, but the icon stays highlighted. 
This happens both on the Site Kit Service and in product, with different visual treatments: 

Let's verify that (1) this is expected behaviour and if yes (2) that this is the expected visual treatment. 
cc @aarondruck for an expert consult.

## Screenshots

Highlighted icon on Site Kit Service:
![SKS-help](https://user-images.githubusercontent.com/13304791/112533620-6c8bf380-8daa-11eb-93ae-81455c5dd29c.png)

Highlighted icon in product:
![plugin-help](https://user-images.githubusercontent.com/13304791/112533657-77468880-8daa-11eb-8814-ae25788b6206.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following UX bugs with the help visibility icon in the Site Kit header bar (behind `helpVisibility` feature flag) should be fixed:
    * The blue outline that is displayed e.g. when clicking the menu icon to close the menu should be completely removed (applies to both active and focus state). This should be removed from _all_ header buttons, in fact—see https://github.com/google/site-kit-wp/issues/3026#issuecomment-811074432.
    * When clicking a link from the menu (opens in a new tab) and then going back...
        * ...the menu icon should be visually active but the menu should be closed. It should still be the currently focused item.
        * ...clicking on the menu icon should open the menu again. Currently this is clearly broken, as the first click in this scenario doesn't do anything, and only on the second click it will reopen.
* As a guidance, in terms of the above three bullet points it should behave similar to the question mark icon you can see e.g. in [Google Drive](https://drive.google.com/drive/my-drive). But the help icon should still be visually highlighted upon return, as it is the focused element and that visual indicator is useful to a keyboard user, especially after the menu was closed on clicking a link.

## Implementation Brief

* edit the `HelpMenu` component and remove the `<Fragment>`
* edit the file `assets/sass/components/global/_googlesitekit-dropdown-menu.scss`
* add the following to the class `.googlesitekit-header_dropdown` to the file with:
	`&:focus {
		outline: 0;
	}`
* edit `assets/js/components/Menu.js` and set a default function for the `onSelected` prop which sets `menuOpen` to false

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Check that the dotted blue outline no long appears when the plugin header help icon is focused or active
* Click on one of the links in the dropdown help menu.  Switch back to the plugin tab:
  * check that the help icon is still highlighted.
  * check that the dropdown help menu is displayed when the icon is clicked once
 
## Changelog entry

* Fix bug with help visibility icon in header where clicking it wouldn't trigger the menu to open in some scenarios, and also address some visual design problems with it.

**Comment by felixarntz** [comment]
@tofumatt Can you check this for the `helpVisibility` one? The behavior also felt slightly odd to me, but part of it might be intended for accessibility reasons.

**Comment by aarondruck** [comment]
the button shouldn't stay highlighted if it's not active

**Comment by felixarntz** [comment]
@aarondruck I think this happens when you come back to the Site Kit tab after having been to the other tab that clicking the menu link opened. So at that point, the button to toggle the menu is technically active, I think - so it _might_ be expected.

Not sure about it, just wanted to give additional clarity: It's not like the icon is highlighted even though it's inactive. 🤔

**Comment by aarondruck** [comment]
ah ok then, that makes sense that would be expected behaviour

**Comment by tofumatt** [comment]
I've made some tweaks to the ACs here, because _visually_ hiding that the menu button is focused is not accessible to keyboard-only users. The Google Drive behaviour is largely good, as focus on the help menu button is maintained, but the fact that there's no visual indication of this is not friendly to keyboard users.

It would be better to leave the focus state and focus styles on that element after _changing/hijacking_ focus from the link inside the menu after selecting it, which we do to close the menu after a click. That's a fine behaviour, but removing the visual indicator of focus when the user returns is confusing and forces them to tab simply to figure out where they are upon returning to their Site Kit tab.

But the outline is unneeded, the grey background is sufficient there.

**Comment by tofumatt** [comment]
@Hazlitte There's already a `googlesitekit-help-menu` `className` we can/should use for styles on this component, no need to add another class. I notice actually that there's a needless `Fragment` wrapping the whole component that we could probably ditch as part of this change too.

And the button itself has the class `googlesitekit-help-menu__button`, so I'd say let's target that to tweak the button styles, but I'm noticing the outline effect we want to remove exists for all header dropdown buttons:

![2021-03-31 14 31 32](https://user-images.githubusercontent.com/90871/113152840-6e343c00-922e-11eb-91b0-e87b60f825ac.gif)

Let's remove that style from _all_ dropdown buttons, because it'd be awkward to remove it from just the help menu.

The default menu action sounds good though 👍🏻

**Comment by felixarntz** [comment]
@tofumatt 
> I've made some tweaks to the ACs here, because visually hiding that the menu button is focused is not accessible to keyboard-only users. The Google Drive behaviour is largely good, as focus on the help menu button is maintained, but the fact that there's no visual indication of this is not friendly to keyboard users.

Sounds good, I also thought that was a bit odd in Google Drive. Yet, when updating ACs in user-facing things like this, please confirm this in the future with who wrote the ACs - a ping would be good :)

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update:  Pass ✅ 

**Verified:**

- The dotted blue outline no long appears when the plugin header help icon is focused or active.

- When you click a link in the dropdown help menu, then switch back to the website, the help icon is highlighted.

- When you click on one of the links in the dropdown help menu, then switch back to the website, the dropdown help menu is displayed when the icon is clicked once. 

![image](https://user-images.githubusercontent.com/73545194/113707783-fe80ee00-9712-11eb-911e-3dab802fa7ab.png)

@Hazlitte @tofumatt this has passed but I wanted to highlight a styling observation. Only minor, so, will let you decide. On mobile, the icon is slightly off from centre when you hover over or, click it.  You can see it in the screenshot  [here](https://user-images.githubusercontent.com/73545194/113708253-954daa80-9713-11eb-9b27-0f957d860299.png)
