### ISSUE TITLE
Improve language throughout codebase

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3031]
The Site Kit codebase should always use inclusive language; this is not fully the case currently as there are still some terms being used which should be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The default branch should be renamed to `main`.
* The following terms should no longer be used in the Site Kit codebase (roughly sorted by priority for removal):
    * `master`
    * `whitelist`
    * `ninja`
    * `dummy`
    * `kebab`
    * `sane`, `sanity`, etc.
    * `agnostic`
    * `primitive`
    * `hang`
    * ~~`hit`~~ (we only use "cache hit" which has a different meaning)
* The only place where these terms are okay to be kept is when required due to third-party code.

## Implementation Brief

* Merge #3032.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Ensure the terms in the ACs are no longer to be found in the codebase, unless it is in places where it is required due to third-party code usage.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by asvinb** [comment]
@felixarntz I just wanted to confirm something about the strikethrough word: `hit`. Is it no longer relevant because I can see occurrences of this word in the following files:
- `assets/js/googlesitekit/api/middleware/preloading.js`
- `assets/js/modules/analytics/components/dashboard/LegacyAdSenseDashboardWidgetTopPagesTableSmall.js`
- `assets/js/modules/analytics/components/dashboard/AnalyticsAdSenseDashboardWidgetTopPagesTable.js`

If that's fine, then QA approved.

**Comment by felixarntz** [comment]
@asvinb Ah, good catch! Yes, it should be replaced everywhere where it's not "cache hit". **QA** ❌

**Comment by asvinb** [comment]
Thanks for confirming @felixarntz . Assigning task back to you.

**Comment by asvinb** [comment]
Checked the codebase for the terms in the AC and none found.
### QA: ✅
