### ISSUE TITLE
Booleans converted to strings between addQueryArgs and rest endpoint.

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#3043]
## Bug Description

In js, here is how [addQueryArgs](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-url/#addQueryArgs) performs
```
addQueryArgs( '/foo/', { a: false } );
"/foo/?a=false"
```

Code example:
https://github.com/google/site-kit-wp/blob/cfcf8b68ab73c78a4085f53d30bb58dfb32ce582/assets/js/googlesitekit/api/index.js#L155

In PHP, `WP_REST_Request $request->get_params()` treats the false as a string "false"
https://github.com/google/site-kit-wp/blob/cfcf8b68ab73c78a4085f53d30bb58dfb32ce582/includes/Core/Modules/Modules.php#L781

## Steps to reproduce

1. Checkout `bug/3043-repro-steps`
2. In console, run this: `window.googlesitekit.api.get( 'modules', 'analytics', 'foo', { bar: false }, { cacheTTL: 1, useCache: false } )`
3. Open network tab
4. See error in response 
```json 
{"slug":"analytics","datapoint":"foo","bar":"false","_locale":"user","gettype":"string"}
 ```

`bar` should be a boolean false, and `gettype` should be boolean, not string 'false'

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When we pass boolean variables in a GET query string parameter, they are correctly handled as true and false, including cases where the value is in an array.

## Implementation Brief

* Add a filter with [rest_request_before_callbacks](https://developer.wordpress.org/reference/hooks/rest_request_before_callbacks/), to `includes/Core/REST_API/REST_Routes.php` in https://github.com/google/site-kit-wp/blob/cfcf8b68ab73c78a4085f53d30bb58dfb32ce582/includes/Core/REST_API/REST_Routes.php#L91
* If the request route [get_route](https://developer.wordpress.org/reference/classes/wp_rest_request/get_route/) doesn't start start with '/' . REST_ROOT then return $response as this isn't a sitekit endpoint. 

https://github.com/google/site-kit-wp/blob/3bc8638/includes/Core/REST_API/REST_Routes.php#L37

* If the request's [get_query_params](https://developer.wordpress.org/reference/classes/wp_rest_request/get_query_params/)
contain user supplied values, then run it through a recursive replacement function to replace _string_ `"false"` with _boolean_ `false` and _string_ `"true"` with _boolean_ `"true"`, remember that we can (and do) supply arrays, so we need to account for those too.

* If we did make changes to the `get_query_params` because we encountered what should be boolean values, we can call [set_query_params](https://developer.wordpress.org/reference/classes/wp_rest_request/set_query_params/) with the updated query params.
* Return $response, the first param of the filter as we didn't need to make changes to it, only pre-filter all GET params.

### Test Coverage

* Write tests for the boolean replacement function we're implementing.
 
### Visual Regression Changes

* N/A

## QA Brief

* 

## Changelog entry

*

**Comment by ivankruchkoff** [comment]
Raised this as an issue against the Gutenberg repo https://github.com/WordPress/gutenberg/issues/30428 and WordPress trac https://core.trac.wordpress.org/ticket/52956 with a poc mu-plugin to demonstrate the issue:
https://core.trac.wordpress.org/attachment/ticket/52956/poc.php

**Comment by aaemnnosttv** [comment]
@ivankruchkoff can you give a more concrete example of where this is a problem for us?

**Comment by ivankruchkoff** [comment]
> @ivankruchkoff can you give a more concrete example of where this is a problem for us?

@aaemnnosttv  Short answer, it's **no longer a problem** for us for the issue that I was facing.

Longer answer, copied from https://github.com/google/site-kit-wp/issues/2069#issuecomment-809707111 in IB for https://github.com/google/site-kit-wp/issues/2069 we needed (but **no longer need to** following an update from @felixarntz ) to pass through a `url` param:
https://github.com/google/site-kit-wp/blob/ef1a7e5/assets/js/modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetTopAcquisitionSources.js#L134
`url: global._googlesitekitLegacyData.permaLink`

Testing in console:
```
window._googlesitekitLegacyData.permaLink gives boolean false
```

So we pass through a url param, with value false, to a selector `getReport` which url encodes everything (`&url=false`) which in our handler is then interpreted as `true` example:
https://github.com/google/site-kit-wp/blob/713821b7a2b9f9704aa47eac7b108da4b8e011d3/includes/Modules/Analytics.php#L489 (php: empty("false") === false whereas empty(false) === true)

Currently not a problem, but if we ever had any boolean params in getReports (maybe we do elsewhere) they would behave in an unexpected manner.

**Comment by aaemnnosttv** [comment]
Thanks @ivankruchkoff. I see a few solutions to this that don't require trying to fix things at the WP REST API level. As was mentioned in the trac ticket, this is a non-issue for rest routes that properly declare their schema for each parameter, and it will transform a string "false" into a boolean if the parameter is defined as one.

The problem in our case is that we share endpoint definitions for multiple datapoints and so the route definition can't register a complete schema because not all datapoints use the same parameters. This all goes back to the batch request architecture we have because support for batch requests in core is a very recent thing, otherwise we could probably have much more straightforward endpoint definitions.

So the solutions in our case are:
- Don't use boolean values for request parameters - we could instead use `1` and `0` or `"1"` and `""` [empty string])
- In PHP filter the given value to a boolean using [`filter_var( $value, FILTER_VALIDATE_BOOLEAN )`](https://www.php.net/manual/en/filter.filters.validate.php) which will properly handle a string "true" or "false"

I think these two would be sufficient. Particularly the second one would be good to use anyways for any input that we can't guarantee as a boolean.

For example, the above case that you ran into could be solved with an OR:
```js
url: global._googlesitekitLegacyData.permaLink || ''
```
which would translate to `&url=` in the query string and an empty string, `false`, or `null` on the server depending on how it's received.

For this case specifically, we've used the false/empty `url` to indicate the current site's reference URL which is problematic for other reasons, but that's mostly been a development concern so far. It would be better to always pass through the `url` instead.

Let me know what you think or if there's anything else I'm missing 😄

**Comment by aaemnnosttv** [comment]
Closing this for now, but we can reopen again if needed. cc: @felixarntz
