### ISSUE TITLE
Add detection functionality from AMP plugin

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#3086]
## Feature Description

The AMP plugin has code that will automatically detect where problematic code for AMP compatibility is coming from in order to direct the user to where to look to fix. Consider adding this functionality to the Site Kit plugin in order to point users to where to go to fix identified conflicts, such as a GA tag already installed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
The library I was talking about is https://github.com/GoogleChromeLabs/wp-origination, however it is not yet completed (i.e. the AMP plugin doesn't use it _yet_ either). Given we can't use it right now, I'll move this to _Stalled_ for us to revisit once available.

cc @westonruter

**Comment by westonruter** [comment]
Improving the markup attribution logic is gonna be important for our PX guide work to identify theme/plugin responsible for bad code, as well as just generally being needed by the AMP plugin for validation. After we get AMP plugin v2.1 out the door I'd be able to turn attention to it again. It would be good for the AMP plugin as there's quite a bit of technical debt for the old implementation that will be improved by having it in a standalone package. I'm thinking it could be available for integration by end of Q2/summer.

Some things aren't currently attributed, for example script translation sources (https://github.com/ampproject/amp-wp/issues/4750) and also scripts/styles enqueued from blocks aren't attributed currently either. So those are the kinds of things that need to be addressed.

Nevertheless, what is in the AMP plugin currently should suffice for detecting who is responsible for analytics on the page.

**Comment by westonruter** [comment]
Nevertheless, the full scope of Origination and what the AMP plugin is doing is likely overkill for what you need. Given that you most likely are exclusively looking for analytics that is output via printing in an action, you could just extract this code from the AMP plugin:

https://github.com/ampproject/amp-wp/blob/2d0de18b0f33b3f56e718742407f2c8a195a0f60/includes/validation/class-amp-validation-manager.php#L515

https://github.com/ampproject/amp-wp/blob/2d0de18b0f33b3f56e718742407f2c8a195a0f60/includes/validation/class-amp-validation-manager.php#L1050-L1126

https://github.com/ampproject/amp-wp/blob/2d0de18b0f33b3f56e718742407f2c8a195a0f60/includes/validation/class-amp-validation-callback-wrapper.php

https://github.com/ampproject/amp-wp/blob/2d0de18b0f33b3f56e718742407f2c8a195a0f60/src/DevTools/CallbackReflection.php

The key thing you'd want to do is wrap each action callback with a function that output buffers the output:

https://github.com/ampproject/amp-wp/blob/2d0de18b0f33b3f56e718742407f2c8a195a0f60/includes/validation/class-amp-validation-callback-wrapper.php#L91

Then after the invocation of the action callback is done, inspect the output buffer contents to see if it contains the string in question. If so, then you can can look up where the callback came from via `CallbackReflection` and that is the source of the markup.

So yeah, I think you could get by with a minimal implementation in the short term rather than needing to have exhaustive source attribution: just action hooks and disregarding widgets, shortcodes, blocks, etc.

**Comment by bethanylang** [comment]
@felixarntz Given @westonruter's comments above I'd like to propose taking this out of Stalled and getting it into Triage. We get at least 1-2 topics a week from users who get the “We’ve detected there’s already an existing Analytics tag on your site," and supporting them can be difficult as finding and removing the existing snippet can require a fair amount of technical knowledge. Being able to point them (more) directly to where the snippet is would be extremely helpful and a big UX improvement.

**Comment by felixarntz** [comment]
@bethanylang That's a fair point, we could implement this by copying the approach in the AMP plugin. It's not really a great situation to have to copy it, being able to reuse a library that centralizes this functionality would be more appropriate; but given the regularity of support requests it's probably worth prioritizing despite the technical maintenance burden. I suggest we put this on the agenda for next week's team meeting to discuss within the group how to proceed.

**Comment by tofumatt** [comment]
The library mentioned here is not archived and noted to be unmaintained, so it's not a good fit for inclusion into Site Kit.

I'm going to close this for now as it's been in "Stalled" for four years and is something only tangental to Site Kit's core functionality anyway. I think the support requests here have been reduced and this isn't a feature we need to include _directly_ in Site Kit 🙂
