### ISSUE TITLE
Show stats in Admin bar for non-single posts

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#312]
## Feature Description

For many sites, the home page is the best performing in terms of impressions and clicks in Search. However, if the site owner has selected it to display the latest posts instead of being a static page, it's not considered a post and Site Kit currently won't display stats for it in e.g. the Admin bar. 

![Screenshot 2019-07-18 at 18 27 06](https://user-images.githubusercontent.com/13304791/61476948-7121c700-a98e-11e9-85df-35aefc95ba72.png)

Let's define a way to display stats in the Admin bar for the home page even if it's not a post by aggregating per URL. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Admin bar stats display for home pages even if they're not a single post 
 
## Implementation Brief

* Always compare the current page's _canonical URL, not its post ID_ with the data in SiteKit.
* Add `get_reference_canonical()` method to the `Context` class (https://github.com/google/site-kit-wp/blob/b42304c5e577eb13fa5934bd9c02f2a0cba1e44b/includes/Context.php#L3)—this should return the canonical URL for the current request (with the original base URL replaced with the reference site URL, similar to `get_reference_permalink()`). (Return `false`—or maybe more appropriately `null`—if no URL can be found.)
* Change https://github.com/google/site-kit-wp/blob/b42304c5e577eb13fa5934bd9c02f2a0cba1e44b/includes/Core/Admin_Bar/Admin_Bar.php#L150 to retrieve the current URL and pass the URL (along with the Post ID) to the `googlesitekit_show_admin_bar_menu` filter.
* `googlesitekit_show_admin_bar_menu` filter's function signature should change from `function( bool $display, int $post_id )` to `function( bool $display, string $url, mixed $post_id = null )`.
* Rename `has_data_for_post` to `has_data_for_url`.
* Change transient key to use the hashed URL of the post instead of its ID. This will, as a bonus, cause a page with a changed URL to be re-checked immediately, which is appropriate. Eg. `googlesitekit_sc_has_data_for_5` becomes `googlesitekit_sc_has_data_for_/post-5/`. (It might actually be required to hash the URL because of the [172 character limit on keys for WP Transients](https://codex.wordpress.org/Transients_API#Saving_Transients)). Using the post ID will require a different kind of key for archive pages, which is more complex for no obvious gain.

## Changelog entry

* Show admin bar stats also for home page and blog page, if available.

**Comment by felixarntz** [comment]
There are a couple of issues with the implementation brief, this needs to be implemented in a future-proof way. A few key requirements:

* While we do this now for only the (blog) home page, it should be able to work for every archive.
* It should be URL-based, because that's what the Google APIs deal with.
    * I recommend adding a `get_reference_canonical()` method to the `Context` class, which allows at any time to return the canonical URL for the current request (with the original base URL replaced with the reference site URL, similar to `get_reference_permalink()`). In fact, `get_reference_canonical()` can call `get_reference_permalink()` at the beginning, and then fall back to alternative detection mechanisms if the current URL is not for a single post (it is okay to only add `is_home()` for now). If no URL can be determined, false should be returned.
* The existing `googlesitekit_show_admin_bar_menu` filter should be modified (which is okay to do now since we haven't really established it publicly yet): The post ID (currently second parameter) should become the third parameter and be set to 0 if there is no post, and the new second parameter should always be the current URL.

**Comment by lucymtc** [comment]
Removing current IB for re-work

> Add is_home() condition to Admin_Bar is_active() logic so it doesn't depend only on post object.
> Add is_home() condition to has_data_for_post updating transient key to be googlesitekit_sc_has_data_for_homepage and $post_url to be empty if is_home is true.
> Rename method has_data_for_post to something more generic like has_data

**Comment by tofumatt** [comment]
Rather than using `0` as effectively a `null` value for the `$post_id` argument, I think it's better to allow/expect that variable to be either `null` or `int`—I understand that a `$post_id` of `0` shouldn't happen and we could use that as a placeholder for "no post ID", but I think `null` communicates that intent clearly whereas an "invalid" post ID doesn't. I've specified that the function signature of the `googlesitekit_show_admin_bar_menu` filter should allow for (and, in fact, supply as a default) a `null` $post_id`.

**Comment by felixarntz** [comment]
IB looks great ✅ 

@tofumatt I'm still leaning more towards a unified data type. `0` is falsy too, and it is common to return that for an integer ID value in WP if no entity was found. Another alternative might be to pass the entire `WP_Post` object or `null`, since for objects `null` is a more common return type to indicate none was found.

That is an implementation detail though, so I think we can continue discussing that on the PR.

**Comment by tofumatt** [comment]
Right now this one strikes me as a small-sized task, but it should be noted that I'm less a WP PHP developer than a JS one these days. Still, I think that's the right-ish size. 😅

**Comment by tofumatt** [comment]
Tested this and it works a treat, even after a page's permalink changes and then changes back!

(Stats omitted from screenshots for privacy, but they _do_ appear.)

#### Tested with a homepage:

<img width="977" alt="Screenshot 2019-09-25 20 23 08" src="https://user-images.githubusercontent.com/90871/65633025-09fa4180-dfd3-11e9-8372-fd74c78d82ae.png">

#### Blog frontend
<img width="989" alt="Screenshot 2019-09-25 20 23 28" src="https://user-images.githubusercontent.com/90871/65633058-20080200-dfd3-11e9-9b50-91a0997e00e0.png">
<img width="1015" alt="Screenshot 2019-09-25 20 23 21" src="https://user-images.githubusercontent.com/90871/65633059-20080200-dfd3-11e9-91d9-5ac0f50beca0.png">

#### Blog backend
##### URL matches
<img width="1134" alt="Screenshot 2019-09-25 20 23 44" src="https://user-images.githubusercontent.com/90871/65633138-52b1fa80-dfd3-11e9-911c-3475fae13538.png">
##### URL doesn't match (page refresh required)
<img width="1070" alt="Screenshot 2019-09-25 20 24 06" src="https://user-images.githubusercontent.com/90871/65633094-3910b300-dfd3-11e9-84ef-f0324eff92bc.png">
##### URL matches again (page refresh required)
<img width="1096" alt="Screenshot 2019-09-25 20 24 22" src="https://user-images.githubusercontent.com/90871/65633083-31510e80-dfd3-11e9-986d-e0e9ea3070e7.png">

#### Posts continue to work when URL matches
<img width="974" alt="Screenshot 2019-09-25 20 35 38" src="https://user-images.githubusercontent.com/90871/65633484-2054cd00-dfd4-11e9-94ca-e52d01f96360.png">

Dunno if it's possible to change that menu when a permalink is changed, that could be a neat future enhancement. I imagine not though, because it's rendered by PHP 😢

-----

At any rate: works great! 👍

**Comment by felixarntz** [comment]
@adamsilverstein @aaemnnosttv Testing this right now, it works well mostly, but it does not work for the case where you have WordPress's default of "Latest Posts" as the home page (in that case there is no actual page for that).

I think I already found the issue in the code, will open a PR.

**Comment by felixarntz** [comment]
Approved!
