### ISSUE TITLE
E2E Tests fail with Jest console output failure in WordPress Nightly

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#3183]
## Bug Description

The WordPress Nightly E2E tests have started failing since last week, because there is an unexpected console output in the block editor:

<img width="1012" alt="Screenshot 2021-04-19 at 10 02 18" src="https://user-images.githubusercontent.com/90871/115210263-5695f800-a0f6-11eb-8b0c-8cf2735f2168.png">

Oddly, this [change is from _years ago_](https://github.com/WordPress/WordPress/commit/03390f00c58a5d1a21052397e414ee43be845dd3), but it's recently started causing our tests to fail.

We should ignore this console message so our tests start passing again.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* WordPress Nightly E2E tests should pass.

## Implementation Brief

* Ignore the `'Block successfully updated for'` console message in our list of ignored console messages in `tests/e2e/config/bootstrap.js`
* Merge #3181.

### Test Coverage

* N/A.

### Visual Regression Changes

* N/A.

## QA Brief

* The WordPress Nightly E2E tests should pass.

## Changelog entry

* N/A.

**Comment by aaemnnosttv** [comment]
Weird indeed. I tried to see if WP had anything to account for this, but it's only expected in one test for the parser itself. Maybe it has to do with something in the newest version of the default theme and the fact that we install Twenty Twenty after the dummy posts are created in the E2E provisioning? I'm not really sure but it isn't worth digging into at the moment since this is very minor and isn't relevant for us.

IB ✅

**Comment by aaemnnosttv** [comment]
## QA ✅ 

![image](https://user-images.githubusercontent.com/1621608/115215653-63bde180-a10c-11eb-82c5-cb626b38e659.png)
