### ISSUE TITLE
Switch module screens UI to be conditional between widget-based and legacy version

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3226]
Similar to the Site Kit dashboard, the Site Kit module pages should display _either_ the widget-based version _or_ the legacy version. Like with the Site Kit dashboard, it was intentionally decided to first render both to allow for easy comparison, but now that all widgets have been migrated, the screens should only display one or the other based on whether the `widgets.moduleScreens` feature flag is set.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The module screens (Search Console, Analytics, AdSense) should only display one version of their UI depending on the `widgets.moduleScreens` feature flag, instead of both.
    * In other words, if the feature flag is active, the widget-based version (currently at the top) should be displayed.
    * Otherwise, the legacy version (currently at the bottom) should be displayed.

## Implementation Brief
* Using `ModuleApp`, conditionally render the `LegacyModuleApp` component if the `widgets.moduleScreens` feature is set. The existing variable `shouldRenderWidget` can be used for the condition.

### Test Coverage
* No changes needed.

### Visual Regression Changes
* N/A

## QA Brief

* Connect AdSense, Analytics, Search Console
* Disable flag `widgets.moduleScreens`
* View dashboards for AdSense, Analytics, Search Console
* Assert can see legacy components
* Enable `widgets.moduleScreens`
* Refresh the three dashboards
* Assert can see new widget components

To be sure of the difference between the legacy and new widgets components (as there are slight differences!) you could either
* use React dev tools and inspect
Or:
1. view x3 dashboards on develop branch (so can see both, new widget comes first)
2. Check out this branch
3. Then view x3 dashboards with feature flag Disabled and then Enabled 

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
## QA ❌ 

@cole10up @danielgent – as mentioned in #3321, the changes here result in React console error/warnings about state updates on an unmounted component.

The reason this happens is due to the condition on this line for the `screenWidgetContext` which will be `null` on the initial render because its selector is fulfilled by an async resolver:
https://github.com/google/site-kit-wp/blob/8c341d37f0ba40d83ce5a8a067ac223f42c4f9d8/assets/js/components/module/ModuleApp.js#L53

This causes `shouldRenderWidget` to be `false` for 1 render with the `LegacyModuleApp` before it immediately switches out for the widget-based context. Let's update this to be switched based on the feature flag alone (like we do elsewhere) and address any potential problems with that (such as `slug={ screenWidgetContext }` when `null` perhaps) to be more graceful.

<details>
<summary>If passing a `null` slug to `WidgetContextRenderer` is a problem...</summary>

In this case, I think `getScreenWidgetContext` should actually return `undefined`  if `getModules` hasn't loaded yet
https://github.com/google/site-kit-wp/blob/8c341d37f0ba40d83ce5a8a067ac223f42c4f9d8/assets/js/googlesitekit/modules/datastore/modules.js#L825-L829
This is more consistent with our convention to return `undefined` to signify a selector which hasn't been fulfilled yet by an underlying resolver (in this case `getScreenWidgetContext` doesn't have one of its own, it relies on `getModules`). Then if it returns `undefined`, `ModuleApp` would return `null`, delaying the rendering of `WidgetContextRenderer` until the `screenWidgetContext` is available. I think this should be fine, but it would be simpler of course if we didn't have to go this route.

</details>

cc: @felixarntz @johnPhillips

**Comment by wpdarren** [comment]
### QA Update:  Pass ✅ 

**Verified:**

This was tested with the React dev tools and inspecting of components. 

- For AdSense, Analytics, Search Console, when widgets.moduleScreens is disabled, the legacy components appear. 

[Screenshot 1](https://user-images.githubusercontent.com/73545194/118506414-340ef300-b725-11eb-8abb-84c49ed0f588.png) - [Screenshot 2](https://user-images.githubusercontent.com/73545194/118506433-38d3a700-b725-11eb-8d40-4605eed117f9.png) - [Screenshot 3](https://user-images.githubusercontent.com/73545194/118506555-530d8500-b725-11eb-803e-e410da34cf3b.png) 

- For AdSense, Analytics, Search Console, when widgets.moduleScreens is enabled, the new widget components appear.

[Screenshot 1](https://user-images.githubusercontent.com/73545194/118506886-9ec02e80-b725-11eb-95f1-826f6765b368.png) - [Screenshot 2](https://user-images.githubusercontent.com/73545194/118506898-a1bb1f00-b725-11eb-96a9-492f9b9cb2af.png)
