### ISSUE TITLE
Update Analytics settings UI to include specified GA4 property (if set)

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3254]
If the `modules/analytics-4` store is loaded (i.e. the `ga4setup` feature flag is enabled) and a GA4 property is set, the Analytics settings panel should allow controlling the selected GA4 property.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the `ga4setup` feature flag is enabled, the Analytics `SettingsView` should display the value for the currently used GA4 property _if one is set_. If none is set, no information about this setting should be displayed entirely.
* The Analytics `SettingsEdit` component should contain UI to specify the GA4 property that matches the UA property currently chosen, relying on `getSetupFlowMode`:
    * If it returns "legacy" or "ga4" (the latter of which would be a special case here where the current user doesn't have access to the currently selected property), nothing about GA4 should show.
    * If it returns "ua", the [notification that is also used in the setup](https://www.figma.com/file/ix0pcdTQi1Bf9QFNBlBByB/GA4-%2B-UA-onboarding?node-id=20269%3A8621) to indicate a new GA4 property will be created should be shown. In that case, the `propertyID` setting of the `modules/analytics-4` store should automatically be set to `PROPERTY_CREATE`.
    * If it returns "ga4transitional", the notification with a GA4 property dropdown from [this Figma design](https://www.figma.com/file/ix0pcdTQi1Bf9QFNBlBByB/GA4-%2B-UA-onboarding?node-id=20269%3A9075) should be shown, relying on the `PropertySelect` component of the `analytics-4` module.
        * In other words: Differently from setup where for this case there's a dropdown with all GA4 and UA properties (see #3250), in the settings UI the UA property is for now always the "primary" property.

## Implementation Brief
* Using `SettingsView`,
    * Query the `analytics/4` data store using the `getPropertyID` selector to check for the currently used GA4 property.
    * If this is the case, then display the property ID using the `DisplaySetting` component like it's done right now with the non GA4 property.
* Using `SettingsEdit`,
    * Query the `analytics` data store using the `getSetupFlowMode` selector.
    * Based on the value returned by `getSetupFlowMode`,
        * If it returns `SETUP_FLOW_MODE_LEGACY` or `SETUP_FLOW_MODE_GA4`, nothing about GA4 should be displayed.
        * If it returns `SETUP_FLOW_MODE_UA`,
            * use the `SettingsNotice` component to display the following text "A Google Analytics 4 property will also be created." as per the designs in Figma.
            * set the property ID to `PROPERTY_CREATE` via the `selectProperty` action of the `analytics/4` data store.
        * If `SETUP_FLOW_MODE_GA4_TRANSITIONAL` is returned,
            * display the `PropertySelect` component of the analytics-4 module.

### Test Coverage
* No new tests needed.

### Visual Regression Changes
* N/A

## QA Brief

Commit https://github.com/google/site-kit-wp/commit/9205dbce2 has the changes that can be run to trigger each state to display the relevant settings / form views. Be aware that https://github.com/google/site-kit-wp/issues/3251 introduces some changes which will handle some layout updates to match the figma, the `Read More` positioning.

Prior to rendering SettingsView() `assets/js/modules/analytics/components/settings/SettingsView.js`, set the GA4 propertyID, e.g.:
`global.googlesitekit.data.stores[ 'modules/analytics-4' ].actions.setPropertyID( 12345 );`
View the settings view via: `/wp-admin/admin.php?page=googlesitekit-settings#settings/analytics/view`

Prior to rendering SettingsForm() `assets/js/modules/analytics/components/settings/SettingsForm.js`, which can be viewed via: `/wp-admin/admin.php?page=googlesitekit-settings#settings/analytics/edit`, hardcode the `getSetupFlowMode` selector to return:  --- https://github.com/google/site-kit-wp/blob/df5db3326f92551b0c229699b3d199ff786cccda/assets/js/modules/analytics/datastore/setup-flow.js#L36 
`SETUP_FLOW_MODE_UA` and compare to figma (see ac) screenshot attached:
<img width="907" alt="Screen Shot 2021-05-20 at 2 31 53 PM" src="https://user-images.githubusercontent.com/373931/119052182-0de19100-b979-11eb-87f7-9fb0626785b8.png">

next hardcode it to 
`SETUP_FLOW_MODE_TRANSITIONAL`
 and compare to figma (see ac) screenshot attached:

<img width="869" alt="Screen Shot 2021-05-20 at 2 31 59 PM" src="https://user-images.githubusercontent.com/373931/119052199-15a13580-b979-11eb-9a6e-18d882116973.png">

## Changelog entry

* Show GA4 property in Analytics Settings when available.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by Hazlitte** [comment]
Hi @felixarntz,
Between the first paragraph of the AC and the first paragraph of the IB I can't figure out whether the GA4 property ID should be displayed as well as the standard ID or instead of it.  And I can't find a relevant design to understand what to do.  Do you know where the right design is or wether both of the IDs are displayed or just one of them?

**Comment by felixarntz** [comment]
@Hazlitte If a GA4 property ID is set, it should be displayed _in addition to_ the UA property ID. It should be displayed in its own row, below the three other IDs (account ID, UA property ID, profile/view ID).

**Comment by ivankruchkoff** [comment]
A few notes/deviations from IB: (URL to view each screen is in the QA brief)
1. Based on comment from @felixarntz  added the GA4 property in its own row, what's the label to use here?
<img width="513" alt="Screen Shot 2021-05-20 at 2 59 28 PM" src="https://user-images.githubusercontent.com/373931/119054436-7da54b00-b97c-11eb-8b2e-a64463bde202.png">

2. Rather than making the part 2 changes in `SettingsEdit`, I added them to `SettingsForm` it looked like the more correct place to make the change.
3. `getSetupFlowMode` doesn't return anything as `window.googlesitekit.data.stores['modules/analytics-4'].selectors.isAdminAPIWorking()` gives us undefined.
4. I didn't remove the GA4Notice / selectively display it, though the figma implies that it shouldn't be shown for `SETUP_FLOW_MODE_UA` / `SETUP_FLOW_MODE_TRANSITIONAL`
5. I changed the return statements from strings (ga4/legacy etc) to their contstants (`SETUP_FLOW_MODE_GA4`/`SETUP_FLOW_MODE_GA4_TRANSITIONAL` this one was mistyped)
6. Seems to me that we should be doing stories for this so we can backstop these scenarios. (Test Coverage / View Regression both say No new tests needed.)
7. Not sure if the hyperlinks for all of the `Learn More` links should be the same as the GA4 Notice.
8. If you take a look at the attached screenshot, we're close but not quite there, for positioning content is there a set of classes we should be using? If it's CSS + markup, is there someone who can takeover the last part as my CSS skills aren't up to par. (If someone is taking over for css, branch is `feature/3254-settings-ui-ga4` and has all code pushed.)
<img width="880" alt="Screen Shot 2021-05-20 at 2 16 40 PM" src="https://user-images.githubusercontent.com/373931/119054479-901f8480-b97c-11eb-97a0-c21f9e75821e.png">

**Comment by aaemnnosttv** [comment]
> A few notes/deviations from IB: (URL to view each screen is in the QA brief)
> 
> 1. Based on comment from @felixarntz  added the GA4 property in its own row, what's the label to use here?

@ivankruchkoff this is something @felixarntz or @marrrmarrr will need to confirm but for now, I think "Google Analytics 4 Property" is probably what we want to use since this is how it is referred to elsewhere.

> 1. Rather than making the part 2 changes in `SettingsEdit`, I added them to `SettingsForm` it looked like the more correct place to make the change.

Sounds right to me since this is where the selects are rendered 👍 

> 2. `getSetupFlowMode` doesn't return anything as `window.googlesitekit.data.stores['modules/analytics-4'].selectors.isAdminAPIWorking()` gives us undefined.

This selector requires GA4 requests to be made first: https://github.com/google/site-kit-wp/blob/0231db23ab1cef478be2dff152e9d9a3e6aec396/assets/js/modules/analytics-4/datastore/api.js#L56-L57

> 3. I didn't remove the GA4Notice / selectively display it, though the figma implies that it shouldn't be shown for `SETUP_FLOW_MODE_UA` / `SETUP_FLOW_MODE_TRANSITIONAL`

I'm not sure if this should change as part of this issue, but I don't see that notice in the Figma doc at all there which leads me to think that it should only show if `! ga4setup` but this should probably be handled in a separate issue.

> 4. I changed the return statements from strings (ga4/legacy etc) to their constants (`SETUP_FLOW_MODE_GA4`/`SETUP_FLOW_MODE_GA4_TRANSITIONAL` this one was mistyped)

👍 

> 5. Seems to me that we should be doing stories for this so we can backstop these scenarios. (Test Coverage / View Regression both say No new tests needed.)

I agree stories should be added but not sure why these weren't included in the IB. It looks like maybe 4 stories would be added here? Seems like it would be useful but this issue has already been scoped without them so we should probably leave those for a new issue.

> 6. Not sure if the hyperlinks for all of the `Learn More` links should be the same as the GA4 Notice.

Good point – let's keep them the same for now but we'll need to follow up with @felixarntz (maybe @marrrmarrr knows?)

> 7. If you take a look at the attached screenshot, we're close but not quite there, for positioning content is there a set of classes we should be using? If it's CSS + markup, is there someone who can takeover the last part as my CSS skills aren't up to par. (If someone is taking over for css, branch is `feature/3254-settings-ui-ga4` and has all code pushed.)

Sounds good – let's tap @asvinb for this

**Comment by felixarntz** [comment]
@ivankruchkoff @aaemnnosttv 
> > A few notes/deviations from IB: (URL to view each screen is in the QA brief)
> > 
> > 1. Based on comment from @felixarntz  added the GA4 property in its own row, what's the label to use here?
> 
> @ivankruchkoff this is something @felixarntz or @marrrmarrr will need to confirm but for now, I think "Google Analytics 4 Property" is probably what we want to use since this is how it is referred to elsewhere.

Yes, it should be "Google Analytics 4 Property".

> > 1. I didn't remove the GA4Notice / selectively display it, though the figma implies that it shouldn't be shown for `SETUP_FLOW_MODE_UA` / `SETUP_FLOW_MODE_TRANSITIONAL`
> 
> I'm not sure if this should change as part of this issue, but I don't see that notice in the Figma doc at all there which leads me to think that it should only show if `! ga4setup` but this should probably be handled in a separate issue.

This notice is practically no longer relevant with the new flows, i.e. the only place where it should still be shown is in the `legacy` flow (which otherwise ignores GA4 and therefore needs this).

> > 1. Seems to me that we should be doing stories for this so we can backstop these scenarios. (Test Coverage / View Regression both say No new tests needed.)
> 
> I agree stories should be added but not sure why these weren't included in the IB. It looks like maybe 4 stories would be added here? Seems like it would be useful but this issue has already been scoped without them so we should probably leave those for a new issue.

Makes sense, @aaemnnosttv can you define a follow-up issue?

> > 1. Not sure if the hyperlinks for all of the `Learn More` links should be the same as the GA4 Notice.
> 
> Good point – let's keep them the same for now but we'll need to follow up with @felixarntz (maybe @marrrmarrr knows?)

Yes, they can all point to the same current documentation section, we will update that one in time.

**Comment by ivankruchkoff** [comment]
@asvinb,

Passing this to you for FE updates, the blue background / blue star sections highlighted below.

Here are the relevant figma files:
https://www.figma.com/file/ix0pcdTQi1Bf9QFNBlBByB/GA4-%2B-UA-onboarding?node-id=20269%3A7775
https://www.figma.com/file/ix0pcdTQi1Bf9QFNBlBByB/GA4-%2B-UA-onboarding?node-id=20269%3A8621

FIGMA Screenshot:
<img width="892" alt="Screen Shot 2021-05-24 at 5 58 25 PM" src="https://user-images.githubusercontent.com/373931/119424823-0ee92a00-bcbb-11eb-817d-a3a79986a5a0.png">


Current State of the FE:
<img width="1223" alt="Screen Shot 2021-05-24 at 6 06 27 PM" src="https://user-images.githubusercontent.com/373931/119424736-dcd7c800-bcba-11eb-9c76-c0cb19d8ccd6.png">


FIGMA Screenshot:
<img width="898" alt="Screen Shot 2021-05-24 at 5 57 18 PM" src="https://user-images.githubusercontent.com/373931/119424395-3ab7e000-bcba-11eb-9849-fc82335f4827.png">

Current State of the FE:
<img width="1220" alt="Screen Shot 2021-05-24 at 6 04 26 PM" src="https://user-images.githubusercontent.com/373931/119424562-8d919780-bcba-11eb-86dd-1a7815892f0b.png">


Branch: `feature/3254-settings-ui-ga4` everything has been pushed up including latest develop branch merge.

Some helpers to remove when the CR is ready but useful for triggering the different views:
https://github.com/google/site-kit-wp/pull/3407/files#diff-8288a7c1bc54d93872341dd5b2e65fed3fba481ea2cef9a025d5160e2ef41ee1R66-R70

Same for settings view if it needs to be tweaked:
https://github.com/google/site-kit-wp/pull/3407/files#diff-675d44efe969d4f5fd7806beb9c3b433ca7a037c439879e32500c760a7987c83R39-R40

**Comment by ivankruchkoff** [comment]
> > I agree stories should be added but not sure why these weren't included in the IB. It looks like maybe 4 stories would be added here? Seems like it would be useful but this issue has already been scoped without them so we should probably leave those for a new issue.
> 
> Makes sense, @aaemnnosttv can you define a follow-up issue?

Created in https://github.com/google/site-kit-wp/issues/3412
