### ISSUE TITLE
IntersectionObserver is not defined dashboard error when accessing Analytics tab

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3278]
## Bug Description

There have been reports of the below dashboard error, both occurring from Site Kit 1.31.0 users. This seems to occur only when clicking on the Analytics tab for one user while it only occurs on the primary dashboard tab for another. 

One user reported that disconnecting Analytics results in no dashboard notice. 

Awaiting further insights.

```
Can't find variable: IntersectionObserver

    in header
    in DashboardPageSpeed
    in div
    in Layout
    in div
    in LegacyDashboardSpeed
    in FilteredComponent
    in WithFilters(LegacyDashboardModule)
    in div
    in Row
    in div
    in Grid
    in div
    in DashboardApp
    in GoogleSitekitDashboard
    in RestoreSnapshots
    in ErrorHandler
    in Root
```

https://wordpress.org/support/topic/cant-find-variable-intersectionobserver/ | **Open** | Awaiting SH info
https://wordpress.org/support/topic/site-kit-encountered-an-error-32 | **Resolved** (by user, unknown cause) | [SH info filled in although not complete](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNiRUkImypFv2sEuzamlFFnx9Kr1Xd6Sb1bWIn_EhjACze_Rh_z0lsXrr5b1rEMzoxg)
https://wordpress.org/support/topic/intersectionobserver-is-not-defined/#post-14401649 | **Open** | awaiting SH info
https://wordpress.org/support/topic/site-kit-encountered-an-error-34/ | **Open** | Awaiting SH info
https://wordpress.org/support/topic/fatal-error-3876/ | **Open** | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNisbpvhpuTeGXncvNi1A8VkysLQ0H5Zclv09L6Xt7gHBH3uc_O-e_Ov9p_lhoBsGvQ)
https://wordpress.org/support/topic/fatal-error-3876/#post-14475607 | **Resolved** | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNisbpvhpuTeGXncvNi1A8VkysLQ0H5Zclv09L6Xt7gHBH3uc_O-e_Ov9p_lhoBsGvQ) - Safari specific - MacOS Big Sur, version 11.4.

## Additional Context

 - SK 1.31.0
 - From the impacted URL we have from one reporter only the Yoast plugin is evident, no obvious caching, optimization or other plugins

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should provide a polyfill for the `IntersectionObserver`, which is loaded in case it isn't available. See [these docs for reference](https://github.com/thebuilder/react-intersection-observer#polyfill).

## Implementation Brief

* Add `intersection-observer` to our npm dependencies
* Add a new `googlesitekit-polyfills.js` entry
    * This module will only include feature tests and dynamically require polyfills as needed
    * Checks for intersection observer and load the polyfill asynchronously if the feature is not available 
* Add this new entry as a dependency of our vendor asset so that it is automatically loaded with our dependencies
* Merge #3965 

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

Testing Site Kit
* Test intersection observer specific functionality – enable usage tracking, enable PSI and scroll down to view the widget – no error should occur

Browsers
* Test Site Kit using a modern browser (check for errors in the console related to polyfills or intersection observer)
* Test Site Kit using an older browser that does not support intersection observer (e.g. Safari 12.0 or below) – there should be no errors related to intersection observer

## Changelog entry

* Fix potential error in older browsers that don't support IntersectionObserver.

**Comment by bethanylang** [comment]
<a href="https://wordpress.org/support/topic/cant-find-variable-intersectionobserver/">This user</a> reports that they're using Mac 10.11.6 OS X El Capitan and Safari version 11.1.2. I tried testing in Safari 11 in BrowserStack and am not able to replicate. Site Health is available.

**Comment by jamesozzie** [comment]
We've had another report of this today, troubleshooting ongoing. Added to the list of impacted users in original post.

**Comment by abdullah1908** [comment]
Couldn't find out any kind of conflict/error while testing in Safari.
cc: @bethanylang @jamesozzie

**Comment by abdullah1908** [comment]
[As per this topic](https://wordpress.org/support/topic/fatal-error-3876/#post-14475245), user is not observing any issues in the incognito window. By checking SH info I can see there is a plugin NitroPack installed that might be the reason. Asking the user to disable the plugin & check again.

**Comment by jamesozzie** [comment]
This seems Safari specific, similar to #3255, as confirmed by 2/6 impacted users heighted in the issue description. Awaiting response from impacted users, follow up responses sent and testing to be performed today. 

From checking the Intersection Observer API Safari doesn't provide full support yet, with many reporting similar issues in [Stackoverflow](https://stackoverflow.com/questions/60432805/intersectionobserver-api-erratic-in-safari).
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

[One user](https://wordpress.org/support/topic/fatal-error-3876/#post-14475607) stated that they enabled "prevent cross-site-tracking" within their Safari configuration.

**Comment by bethanylang** [comment]
@jamesozzie Checking in here – should this go over to L2 or are you and @abdullah1908 still working on it?

**Comment by jamesozzie** [comment]
@bethanylang Sounds good to me to escalate to L2. Alternatively we can check with the team whether the upcoming changes from #3255 would impact this issue.

**Comment by aaemnnosttv** [comment]
This seems to be related to our use of `react-intersection-observer` which was added in #3116.

I found a similar issue on the repo which also indicates that it isn't compatible out-of-the-box with Safari 11:
https://github.com/thebuilder/react-intersection-observer/issues/469#issuecomment-834125871

There is a section in the readme about how to add this:
https://github.com/thebuilder/react-intersection-observer#polyfill

I think this is sufficient to move the issue forward with – thanks all!

**Comment by aaemnnosttv** [comment]
@felixarntz we talked about conditionally relying on the intersection observer, but this may be more trouble than it's worth since we can't call hooks conditionally: https://github.com/google/site-kit-wp/blob/37e9cad8e29c8fa83bd8337bf9403f80243d42a4/assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeed.js#L92 

The library does offer an `InView` component instead which we _could_ use conditionally but again, may be more problematic than it's worth.

There is the polyfill as [documented on the repo](https://github.com/thebuilder/react-intersection-observer#polyfill) – the [cost of adding this to our bundle](https://bundlephobia.com/package/intersection-observer@0.12.0) doesn't look too bad though. What do you think?

**Comment by felixarntz** [comment]
@aaemnnosttv Sounds good, let's include the polyfill.

**Comment by eugene-manuilov** [comment]
@felixarntz @aaemnnosttv WordPress supports the [last 2 Safari versions](https://make.wordpress.org/core/handbook/best-practices/browser-support/). IntersectionObserver has been fully implemented in [Safari 12.1](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#browser_compatibility) that is not supported by WordPress anymore because Safari has already released versions 13th and 14th. So, I think we shouldn't add a polyfill for IntersectionObserver, users need to update their browser instead. What do you think?

**Comment by aaemnnosttv** [comment]
@eugene-manuilov I agree that a browser upgrade is the best solution for us here but is still a poor experience for the user who will end up with a fatal React error screen when using PageSpeed Insights where things are otherwise working fine. Users encountering this error will have no indication that upgrading the browser will fix the problem so Site Kit will get the blame.

This isn't affecting a large number of users, but we should aim to provide a better experience where possible. In the future, we may want to use Intersection Observer in other places as well which could make this more severe though so it's not only about the one module.

I think adding the polyfill is okay as a temporary fix, but we should revisit improving UX for unsupported browsers in another issue.

**Comment by eugene-manuilov** [comment]
Ok, IB is added. @aaemnnosttv do you mind reviewing it?

**Comment by aaemnnosttv** [comment]
Thanks @eugene-manuilov – I'm not sure if we want to leverage a third-party script for this although that would provide it without increasing our bundle size. The trade-off there though is that the engineer needs to know to add the polyfill asset dependency to their the entrypoint whenever intersection observer is used, which seems rather fragile to me.

What do you think about using the [async polyfill on the repo](https://github.com/thebuilder/react-intersection-observer#polyfill) using `import()`? This way it wouldn't increase the size of the initial bundles but load the polyfill on-demand but from the local site. This way, it would be safe to add the module to all our main bundles via Webpack so that it would be added automatically as needed with only minimal overhead to the bundle itself.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv the problem with dynamic import is that webpack uses a static public path which is an empty string and tries to load the imported script from the current virtual directory. In our case, webpack loads dynamically imported scripts using `http://{domain}/wp-admin/{imported-script}` URLs instead of `http://{domain}/wp-content/plugins/google-sitekit/dist/assets/js/{imported-script}`. Unfortunately, I don't see how we can override it.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov ah yes – I believe that's why in the past we had to [set the public path on-the-fly](https://v4.webpack.js.org/guides/public-path/#on-the-fly) before using a dynamic import. The base path should be already available via Site Kit's base data global:
 
![image](https://user-images.githubusercontent.com/1621608/127857475-418114cc-c35b-4378-8599-c9bd8dc73c62.png)

**Comment by eugene-manuilov** [comment]
@aaemnnosttv unfortunately, the public path on-the-fly doesn't seem to work. Tried it on my local machine and I still see the empty public path string:

```javascript
// runtime.js
...
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
...
```

**Comment by aaemnnosttv** [comment]
> unfortunately, the public path on the fly doesn't seem to work. Tried it on my local machine and I still see the empty public path string in the generated `runtime.js` file

@eugene-manuilov I don't think setting it on the fly would cause it to be updated in the built `runtime.js`, instead it's changing it at runtime. We used to use this in a few places back when we were using chunks for a few things so it does work 🙂 

I've created a quick PR to do this as a proof of concept but I also think it's good to go as-is. In development the added `googlesitekit-polyfills.js` was 3kb (850b in prod) and only does the dynamic require for the feature polyfill if needed so it's very lightweight.

I've updated the IB to use this, let me know what you think.

**Comment by eugene-manuilov** [comment]
> I don't think setting it on the fly would cause it to be updated in the built runtime.js, instead it's changing it at runtime. We used to use this in a few places back when we were using chunks for a few things so it does work slightly_smiling_face

It works :tada:! IB :heavy_check_mark:

**Comment by eugene-manuilov** [comment]
@aaemnnosttv could you please add QAB?

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@aaemnnosttv can I have a sanity check on what I tested:  the ticket mentions 'Analytics tab' and when I read a few of the support tickets they mention when disconnecting Analytics or PSI. I am a little confused that the QAB does not mention this.   Anyway, what I did in a modern browser and Safari 11.1 is connected PSI and scrolled down to the widget on the dashboard and no errors appear in the FE or console. Just as a precaution, I also disconnected PSI and no errors appeared. 

Is this all I have to do?

**Comment by aaemnnosttv** [comment]
@wpdarren on the current release, if you activate PSI in Safari 11.1 you should see this error 
![image](https://user-images.githubusercontent.com/1621608/131665204-bb3cbc77-eac5-42e6-8be8-7c037bdbc52c.png)

On the develop branch, no such error occurs 
![image](https://user-images.githubusercontent.com/1621608/131665599-7249abb9-878f-4de0-945f-68e913656dc3.png)

Feel free to try other pages too, but you can test it right on the main dashboard as long as PSI is active.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

When on Safari 11.1 and connecting PSI, I was able to recreate the issue on the latest release. When I switched to develop, the error no longer appears when the module is connecting or displaying the insights.  While on the branch, I disconnected and connected a few other modules and no error message appeared.
