### ISSUE TITLE
Source Links Appearing in Acquisition Widget with No Data

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3319]
## Bug Description

Under the `Acquisition` widget on `Site Kit Dashboard`, for a new site, under the 'gathering data' messages are source links visible, which link to Search Console and Analytics, even though there is no data.  

Should these links be hidden until data appears? 

![image](https://user-images.githubusercontent.com/73545194/117465334-809a4780-af49-11eb-9975-ccfd63d947d6.png)
 
## Steps to reproduce

1. Connect your Google account to Site Kit for Search Console and Analytics
2. Make sure that the site is new with no data
3. Go to Site Kit Dashboard 
4. Scroll down to the `Acquisition` widget 
5. Observe source links as per screenshot above. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
That's a good question. I think there's probably value in keeping them even when there's no data since these are deep links into the configured entity in the respective service frontends. It's a quick and easy way to get right to your account/property in those services where you can do more than just see data/stats (e.g. grant user access, or manage other settings, etc). Will discuss with the rest of the team though 👍

**Comment by marrrmarrr** [comment]
I think the appearance of these will change significantly in the current zero state rework, so they might not take this much space. Let's discuss with the UX team what is currently planned.

**Comment by aaemnnosttv** [comment]
After discussing earlier with @felixarntz and @marrrmarrr we agreed that these links are still useful in a no data state so no changes are needed here 👍
