### ISSUE TITLE
Add context to the messaged displayed when admins exclude "Users that can write posts" from Analytics tracking

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3390]
## Feature Description

Now that the option to exclude all logged in users apart from subscribers is set to be shipped as per #1891 consider adding additional information that adds further clarity by mentioning the user roles. 

![2021-05-21-12-54-39](https://user-images.githubusercontent.com/41326532/119133657-0f23c400-ba34-11eb-9fc6-afe2a63901d4.gif)
 
At present the notice displays the below:
**Users that can write posts will be excluded from Analytics tracking.**

Consider changing it to the below:
**All logged-in users with the exception of "Subscribers" be excluded from Analytics tracking.**

The reason I'm proposing this modification is based on the below:
- The suggested change is more in line with the message displayed when "All logged-in users" are excluded - "_All logged-in users will be excluded from Analytics tracking._"
- There is no mention of the WordPress user roles included. This could lead to multiple support topics. 
- While "users that can write posts" does include "Web Designer" and "Contributor" roles not all WordPress administrators who may setup Site Kit may be aware of this. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks @jamesozzie. My initial thought is that the existing language is more clear and will always be accurate because it's based on a capability. What I mean is that permissions checks in WordPress are almost always (read: should be) based on capabilities rather than roles. While it's true that all default roles except for Subscribers can write posts, there's nothing stopping someone from using a plugin or other code from granting that capability to Subscribers. Also, custom roles may be created by other plugins which have a different mix of capabilities that might not include the ability to write/edit posts. It's also possible for capabilities to be granted without a role 😄 

I think WordPress only references roles in the user-facing interfaces, but as far as I know, it doesn't list what roles have which capabilities anywhere so admins need to be somewhat familiar with these things anyways and writing posts is something all admins will understand.

Given that this was released in 1.33.0, have there been any related support requests raised yet?

**Comment by jamesozzie** [comment]
@aaemnnosttv Thanks for the additional insights. With regards support topics - no, there were no support topics questioning this particular configuration. Given this I'm happy to close this feature request, to be reviewed or discussed should users raise this in the forums.

**Comment by marrrmarrr** [comment]
+1 to Evan's comments, let's leave as-is for now.
