### ISSUE TITLE
Sign in loop - reverting to setup screen

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3427]
[One user in the support forums](https://wordpress.org/support/topic/sign-in-loop/) is unable to proceed with Site Kit setup, with the plugin redirecting back to the initial setup screen on the proxy after signing in. This is after moving the site from a staging environment to a live site although all the records on the Site Kit service look fine. 

## Additional Context

 - Occurring for previous versions of Site Kit ( up until current version)
 - [Site Health information provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=google.com#response=ACYDBNhCynu2W3A0d1utsLj7W16JDAE-_nhBC0NdZDoCr5T_xh90cnI2j_POxgJ_j1yvU6c) 
 - Site records look fine on the SK service (previously check by Adam)
 - The same issue occurs on a clean WordPress install on the same hosting provider
 - The user did provide a support video of what's occuring in a [second SH info form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNj-Szy3wbJnOzykQy-S7RwIM3lfQb7uiHivb7XAKAF_w7bGZ4AJA5-CbnT8c9CJCqY)

## Insights & Troubleshooting Checks performed 

- [x] Health Check & Troubleshooting plugin check - Same issue occurs
- [x] Front end check (mixed content, minified content, combined JS) - No obvious issues
- [x] Incognito mode - 
- [x] Checked users Site Health info, no identified causes
- [x] Checked .htaccess rules applied - No additional rules evident from SH info 
- [x] Uninstalled and reinstalled plugin
- [ ] User confirmed no "Critical errors" in their Site Health status
- [ ] Temporary disabled WAF rules at host level - including ModSecurity
- [x] Attempted setup/viewing dashboards from another device 
- [x] Checked site setup and dashboard from another WordPress site on the same hosting platform - same issue (https://kitinfoamazonia.hacklab.com.br)
- [ ] Reset Site Kit (on the SK service) - Checked and all site records are fine 
- [ ] Reset previous site records (on the SK service) - site used dev.infoamazonia.org previously
- [x] Disconnected Site Kit
- [x] Checked does the same occur from another admin users account
- [ ] Checked setup using a separate Google account
- [x] Modified WordPress site settings (switching https > http, logging in once once more & reverting to https)
- [ ] Reviewed error logs 
- [x] Reviewed XHR requests 
- [x] WP CLI checks - No issue, 200 response
- [x] cURL check at host level - No issue, 200 response

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@adamsilverstein If you can think of any checks I can perform next based on the above let me know. The user did setup a clean WordPress install and the same is occurring, with a video provided of this behavior.

**Comment by adamsilverstein** [comment]
@jamesozzie 

Were there any console errors reported?

From the video it looks like when the user lands back on the server after authorizing, either query parameters or request headers are missing, and - lacking the correct information - the service deduces the user is at step 1. It looks more like a browser level block than a server issue - however you mentioned the user already tried incognito mode which should disable browser level blocking. Can you have the user disable any security/firewall on their computer temporarily, and/or try another browser?

One other thing you could have the user try to set up Site Kit on https://jurassic.ninja/create/ to see if they run into the same issue there - if so it is something about their computer/account/system causing the issue rather than the host.

If it is a host level issue rather than user configuration, can we see who the host is and if we can get an account for testing or have their support review the issue (the user would ideally request this since they are the hosting customer)? it is hard to see where the error is happening from the video, my guess is that there is either something in the user's system or a host level redirect or that only certain headers or query parameters are being allowed. 


With a test site we could run the plugin in a way that enables logging so we can better pinpoint the exact failure point.

**Comment by willowmagrini** [comment]
Hello @adamsilverstein, thanks for helping!
We tried from different machines in totally different locations and from different users, that's why I think is unlikely a browser level problem. I've also tried in different browsers (firefox, brave and chrome) with the same outcome.
There are no errors on the console.
We host the website in a custom server with kubernetes and docker, and we use an nginx ingress controller. 
I agree that the problem could be related to a nginx ingress configuration that is preventing some headers or parameters to be sent.  We've set up a test environment and can provide you with credentials for testing if you think that could help.
Thank you once more.

**Comment by adamsilverstein** [comment]
Hi @willowmagrini - thanks for the additional details. Do you have any firewall rules running on your platform and if so, can you try temporarily disabling? we have seen some sites fail because of rules that restrict query parameters or length.

**Comment by bethanylang** [comment]
Hi @willowmagrini, just checking in here! Are you still experiencing these issues?

**Comment by bethanylang** [comment]
@adamsilverstein No reply from the user, so shall I move this over to L2 for deeper testing?

**Comment by bethanylang** [comment]
@adamsilverstein @jamesozzie Moved to L2 and unassigned both of you. Feel free to jump back in if you'd like, or this can be picked up by another eng.  :)

**Comment by willowmagrini** [comment]
Sorry for the delay, still experiencing these issues.

**Comment by jamesozzie** [comment]
@willowmagrini Thanks for the update. It would be great if you could perform the following checks:
1. While you've already confirmed the same occurs on a clean WordPress install on the same hosting platform can you check does setup proceed on a temporarily WordPress install using https://jurassic.ninja/create?
2. If you could share another screen recording with your browser [console errors](https://imgur.com/KyLAzgH.png) tab open that might provide some useful insights. You can use a service such as [Loom ](https://loom.com)or [RecordIt](https://recordit.com) to share a video, while using the [same form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) previously used to share privately if preferred.

**Comment by willowmagrini** [comment]
1. Everything good
2. https://www.loom.com/share/8755e3c284f94241bb65dfbe9bc662b2 
If you need to see any response from the requests please let me know.
I'm still thinking there is something being blocked on our nginx ingress controller. 
I've tried to add the following annotations to increase several parameters but still no success. 

nginx.ingress.kubernetes.io/client-body-buffer-size=100m
nginx.ingress.kubernetes.io/configuration-snippet=proxy_set_header Authorization $http_authorization;
nginx.ingress.kubernetes.io/cors-allow-headers=*
nginx.ingress.kubernetes.io/enable-cors=true
nginx.ingress.kubernetes.io/proxy-body-size=100m
nginx.ingress.kubernetes.io/proxy-buffer-size=80k
nginx.ingress.kubernetes.io/proxy-max-temp-file-size=1024m
nginx.ingress.kubernetes.io/server-snippet=http2_max_header_size 160k; http2_max_field_size 160k;

**Comment by eugene-manuilov** [comment]
Thanks, @willowmagrini. Looks like all redirects happen between proxy and google accounts sites. @adamsilverstein can it happen because the proxy server can't find the verification code on the WordPress site?

**Comment by adamsilverstein** [comment]
@eugene-manuilov - possibly - I will take a look. Have you been able to reproduce the issue?

**Comment by adamsilverstein** [comment]
> I'm still thinking there is something being blocked on our nginx ingress controller.

This could very well be the case @willowmagrini, we have had issues in the past where nginx was stripping some query parameters. It is a bit hard to see in your video, but right after you click the Verify button, you are sent back to your website, then back to the service. If you set the network tab to "preserve" logs you will be able to see the redirect.

The URL will start `youdomain.com/wp-admin/index.php?action=googlesitekit_proxy_setup`. Make sure your nginx server isn't stripping any of the passed query variables which include action, nonce, and googlesitekit_ code, site_code, verification_token and verification_token_type.

**Comment by bethanylang** [comment]
@willowmagrini Checking back in on this. Were you able to update your NGINX server and did that fix these issues? Thank you!

**Comment by bethanylang** [comment]
@willowmagrini As we haven't heard back, I'm going to close this issue. If you're still experiencing these problems, please do let us know and we can take another look. Thank you for using Site Kit!
