### ISSUE TITLE
Error on Analytics Account Creation: An appropriate representation of the requested resource could not be found.

### ISSUE THREAD

**Issue by abdullah1908** [google/site-kit-wp#3473]
## Bug Description
While setting up Analytics module user is observing the issue. It seems more relevant to HostGator as both users are using the same hosting service. Also Firewall feature disabled from the server while setting up Analytics.
Following users reported the issues:
- https://wordpress.org/support/topic/error-in-analytics-creation-hel-please | **Open | [SH Info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNj62PmQ50sIgl2QdanSwqNDB_2-x9-yKJ37lSoRG-YxdiIVj6qecr8fknlAYTtTOOg)**
- https://wordpress.org/support/topic/an-appropriate-representation-of-the-requested-resource-could-not-be-found | **Open | [SH Info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNiyjPImJPa62ewXuOSjW5QvPu3crlWQCcI5wv7Vr5si0jM11beCNROjOTLfxRkeyTA)**

## Steps to reproduce

1. Setup WordPress Site on HostGator
2. Configure Site Kit
3. Configure Analytics module
4. You'll [observe error](https://imgur.com/a/zE03AA0) while you selecting new property to setup the Analytics on the website

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by abdullah1908** [comment]
Finally I am able to setup Analytics property after continues discussion with the HostGator Support Team. As per support team we have whitelisted the rule ID globally so it should work fine for all users.

**Comment by jamesozzie** [comment]
Reopening this as other users remain impacted. 

From speaking with a Hostgator representative today there are different regional Hostgator servers and while it's "easy to fix" impacted users must contact Hostgator and request Site Kit be whitelisted. 

> However we can't really say for sure, because we have our different server rules and firewall, different from other HG branches and servers like Hostgator Mexico. But it would be best to consult this with them. But normally Mod_sec is a common firewall that prevents any suspicious contents to access the server or a real-time filter for malicious activity

Correspondence ongoing.

**Comment by jamesozzie** [comment]
I've been able to recreate this on a HostGator shared hosting account (although not with their WordPress specific hosting). This occurs only when creating a new Analytics account and not when selecting an existing account. The console error that appears is below:
`​ GET https://examplesite.com/wp-admin/index.php?action=googlesitekit_connect&nonce=eb61b0fd00&redirect=https%3A%2F%2Fsharedhg.cmsdevrel.com%2Fjames%2Fwp-admin%2Fadmin.php%3Fpage%3Dgooglesitekit-settings%23settings%2Fanalytics%2Fedit&additional_scopes%5B0%5D=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fanalytics.provision 406`

![2021-06-08-00-20-08](https://user-images.githubusercontent.com/41326532/121099233-5dd0ac80-c7ef-11eb-84bd-a2a901cda5b0.gif)

**Temporary workarounds for impacted users** (2 different options):
1. Create an Analytics account and property from [analytics.google.com](https://analytics.google.com). After doing so connect the Analytics module within Site Kit, using that newly created
2. Use the HostGator support center and request ensure you're able to proceed with Analytics account setup within Site Kit. This may include whitelisting http connections to googleapis.com or by confirming there are no other restrictions such as long query strings (requires further testing to determine the exact block). 

Additional information:
- This only started to occur since last week, with multiple impacted users reporting the same since raised. 
- Individual ModSecurity configurations are not possible for individual users on Hostgator shared hosting plans, this requires Hostgator support intervention at present. There is no ModSecurity CPanel or hosting configuration.

**Comment by jamesozzie** [comment]
Closing with as this is ModSecurity related, and not specific to one hosting provider. More details contained in a separate issue - #3532
