### ISSUE TITLE
Smaller browser window/mobile causes long property names move the drop down out of the frame

### ISSUE THREAD

**Issue by cole10up** [google/site-kit-wp#3497]
Smaller browser window/mobile causes long property names move the drop down out of the frame

## Steps to reproduce

1. Run storybook locally via the following command: npm run storybook
2. Visit the Analytics -> Setup -> SetupFormUA story.
3. Use Redux DevTools to check if the SET_PROPERTY_ID action has been dispatched upon page load, with property_create as value.
4. Choose a property from the Property dropdown. After selecting a property, a blue notice as per the designs should appear before the "Configure Analytics" button.

Notice:

![image](https://user-images.githubusercontent.com/57115907/121084610-b5dac500-c795-11eb-8591-2ae811eada84.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit (Material) dropdowns should not overlap the available content area (see screenshot above), they should be capped in width at 100%, even if the text inside is longer than that.

## Implementation Brief
* Using `assets/sass/vendor/_mdc-select.scss`,
    * Add `max-width: 100%;` to the `.mdc-select` selector.
    * Add new selector `.mdc-select__selected-text` with the following styles:
        ```css
        .mdc-select__selected-text {
            display: block;
            overflow: hidden;
            text-overflow: ellipsis;
        }
        ```

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* Expected changes to dropdowns due to above CSS changes.

## QA Brief

* Compare `develop` to `main` on Storybook for the  Analytics -> Setup -> SetupFormUA story
* View the story as a small mobile

https://google.github.io/site-kit-wp/storybook/main/?path=/story/modules-analytics-setup-setupformua--without-existing-tag

https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-setup-setupformua--without-existing-tag

Note that the text in the property dropdown doesn't overflow on develop

Also this can be checked in the Site Kit plugin
1. Reset Site Kit
1. Ensure there is an Analytics property with a long-ish name
1. Start the Analytics set up
1. Reduce the size of the browser window until the Property name is truncated with ellipses 
 

## Changelog entry

* Improve display of long names in select dropdowns.

**Comment by skpandey885** [comment]
Hey, Sir! Can I Contribute To This!?
I am A Beginner and Want To Contribute!

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by danielgent** [comment]
Seven hours seems a really generous estimate for this! It's only taken me one hour...

Note on the linked PR there were no VRT failures (I don't see the SetupFormUA story as being configured as a VRT)

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@danielgent an observation.  While the initial reported issue is fixed, I did notice that if you create a brand new Analytics account with a long property name then the issue still exists.  This would really only be on very small screens (i.e. Galaxy Fold) but wanted to highlight this here in case we want to fix this in the ticket. 

What do you think? 

![image](https://user-images.githubusercontent.com/73545194/126511751-3df8b249-b6fc-404d-95ef-7c32c55f0a2a.png)

**Comment by wpdarren** [comment]
@danielgent would you like me to create a separate ticket for what I discovered, or, is this easy to fix within this ticket since it's linked?

**Comment by danielgent** [comment]
@wpdarren Could you create a video of the bug please? I'm not following.  I thought you meant this but it looks fine to me


https://user-images.githubusercontent.com/8496063/126680176-c00e0002-4fd1-4483-adbc-18ad1d7bedd3.mp4

**Comment by wpdarren** [comment]
@danielgent You have fixed the issue when you connect a property  that is already created with a long name, but my observation was that when you create a `new Google Analytics account and property`, and enter a long property name then the same issue occurs. So my question was, should this be fixed as part of the ticket, or, do you want me to create a new one to fix this in a future release?  

The observation is not a big problem because it only impacts phones like the Galaxy Fold with the thin screen sizes. 

Does this make sense? 

https://user-images.githubusercontent.com/73545194/126794520-4028af0a-ed6e-4e44-ac09-277adce0d505.mp4

**Comment by danielgent** [comment]
The IB only targets the select `.mdc-select` so I just need to apply similar styles to the text input  `.mdc-text` and then it should fix it.  Will try now :+1:

**Comment by danielgent** [comment]
@wpdarren I've done this fix and created a PR here https://github.com/google/site-kit-wp/pull/3754

https://user-images.githubusercontent.com/8496063/126981978-b916c3fa-204e-4e6b-b6ce-905c2262f036.mp4

I'm concerned that we might have jumped a few steps here

The bug you're seeing is because the existing styles for the text input have a min-width that will break out the screen at this resolution! (if we're supporting Galaxy Fold), and making style changes to core form inputs is not something I take lightly!

I commented on the PR as I don't agree with the updated VRT.  Let's discuss this in our standup? :smile:

**Comment by wpdarren** [comment]
@danielgent this is why I was happy to create a new ticket if it wasn't something we wouldn't fix in this ticket. I wasn't sure how quick it would be to do, or, if its something we would fix.  From a QA perspective we would usually get guidance from the engineer on that. Happy to discuss if we even support this mobile device in the stand up.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

Verified that for an Analytics property with a long name on a small screens: he size of the browser window truncates the property name with ellipses.  [Screenshot](https://user-images.githubusercontent.com/73545194/127161227-4e8805e2-1a0c-4615-a49d-62947a7e7dfc.png)
