### ISSUE TITLE
Configure eslint-plugin-import 

### ISSUE THREAD

**Issue by danielgent** [google/site-kit-wp#3502]
## Feature Description

We have `eslint-plugin-import` installed but it doesn't look like it's configured

I created a branch here where I configured this https://github.com/google/site-kit-wp/tree/eslint-import-idea (you can see from the diff that it even found one error :smile: )

The remaining errors on this branch that need fixing are:
```
error  Multiple exports of name 'getLocale'  import/export
error  Unable to resolve path to module 'tests/js/utils'  import/no-unresolved
error  Unable to resolve path to module 'assets/js/googlesitekit/datastore/site'  
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The ESLint configuration should be modified to extend `plugin:import/recommended`.  
_The plugin is already installed_
* Any errors or warnings raised as a result should be fixed

## Implementation Brief

* Merge linked PR https://github.com/google/site-kit-wp/pull/3745

### Test Coverage

* There should be no changes and no updates to tests needed (apart from those done to fix new linting rules!)

### Visual Regression Changes

* There should be no changes

## QA Brief

* Check that JS linting is passing correctly

## Changelog entry

* N/A

**Comment by danielgent** [comment]
Just to give an example of a task I've done a few times.  I need to delete a load of files. Instead of vscode then using eslint to syntax highlight, I have to leave it building to then open the files.  It's possible, but it's just way nicer to use eslint

![no import](https://user-images.githubusercontent.com/8496063/123455042-86bfb280-d5e1-11eb-899a-837d59c111b6.png)

Also it means that I can then make a commit with a bad import that will break the build
![failing commit checked in](https://user-images.githubusercontent.com/8496063/123455068-90e1b100-d5e1-11eb-84a4-4ede630ebab5.png)

**Comment by aaemnnosttv** [comment]
Thanks @danielgent – this looks like a nice enhancement to add 👍 

Looking at your branch, is there a reason why you chose the import plugins for `errors` and `warnings` over the [`recommended`](https://github.com/benmosher/eslint-plugin-import/blob/1012eb951767279ce3b540a4ec4f29236104bb5b/config/recommended.js) ruleset? It looks like that one has all the same rules in one. Any reason not to use that instead?

**Comment by danielgent** [comment]
No @aaemnnosttv .  Most likely I quickly read the readme incorrectly :smile:   

Just doing `- plugin:import/recommended` is enough

**Comment by danielgent** [comment]
@aaemnnosttv `plugin:import/recommended` pulls in the `comma-dangle` rule so I'll change back to using the alternative config as documented under installation https://www.npmjs.com/package/eslint-plugin-import

```
  - plugin:import/errors
  - plugin:import/warnings
```

It seems odd that this would be done

![comma-dangle-reference](https://user-images.githubusercontent.com/8496063/126352613-6c77b91a-69be-4299-a8d4-726f36d4ff11.png)

It can of course easily be auto fixed, but I don't see why!  

![comma-dangle-errors](https://user-images.githubusercontent.com/8496063/126352675-3690f500-b52a-46c3-a28a-db67726c0a7a.png)

I could raise an issue with the library author as it does seem odd but it's a super popular library

**Comment by aaemnnosttv** [comment]
> It seems odd that this would be done

Yes, it's really bizzare. It doesn't even seem to have any reference to this rule in the package installed in `node_modules` either.

@tofumatt any idea why it would be including/flagging `comma-dangle` when using `plugin:import/recommended`?

**Comment by tofumatt** [comment]
I'm not sure it's that plugin using that rule, because I see it enabled when I check for the rules we have enabled in `develop`:

```bash
./node_modules/.bin/eslint --print-config assets/js/util/index.js
```

That'll output a bunch of rules, including:

```
"comma-dangle": [
  "error",
  "always-multiline"
],
```

I can't see _where_ it's coming from there, but doing some digging it's coming from our existing plugins, namely `@wordpress/eslint-plugin/recommended-with-formatting`. Here's the route it takes to get to that rule:

1. The rule definition itself: https://github.com/WordPress/gutenberg/blob/3da717b8d0ac7d7821fc6d0475695ccf3ae2829f/packages/eslint-plugin/configs/recommended-with-formatting.js#L7 (which imports `esnext.js`)
2. `esnext.js`: https://github.com/WordPress/gutenberg/blob/3da717b8d0ac7d7821fc6d0475695ccf3ae2829f/packages/eslint-plugin/configs/esnext.js#L5 (which extends `es5.js`)
3. `es5.js`: https://github.com/WordPress/gutenberg/blob/3da717b8d0ac7d7821fc6d0475695ccf3ae2829f/packages/eslint-plugin/configs/es5.js#L13 (which sets `comma-dangle` as a rule)

So… we already have that rule enabled. 🙂

Maybe I'm not following, but what's the issue? Was it not being flagged for you in the past? That'd be weird!

**Comment by tofumatt** [comment]
Let's amend the IB to say we should use the recommended config rather than individual ones, because I don't think the config is causing the comma-dangle to appear.

If for some reason comma dangle is now appearing where it shouldn't that's weird, but let's just fix the errors as part of the PR 🙂

**Comment by aaemnnosttv** [comment]
@tofumatt @danielgent The ACs already mention that we should use the `recommended` ruleset, so I don't think there's really much to change about the IB, except maybe adding that `comma-dangle` errors will also be fixed since that seems to be unrelated, but is a rule we've had enabled that hasn't been enforced properly/consistently.

Also, please always fill in the Test Coverage and VRT sections to make these explicit when not needed or relevant rather than implicit (or just forgotten).

Finally, please add an estimate 🙂

**Comment by danielgent** [comment]
@aaemnnosttv @tofumatt   ran auto fix on `comma-dangle` and there are 315 changed files :sweat_smile: 

https://github.com/google/site-kit-wp/commit/88edece724640e9dcf31141c4a62d110b22d682a

**Comment by aaemnnosttv** [comment]
@danielgent that's probably okay since those are all auto-fixes. Even if we review it, they're almost all 1-line changes per file. I think they're almost all added commas for multi-line function calls though and the trailing comma looks odd for those, but I suppose that's something I'll have to get used to 😄 Good call about the amount of changes though – let's bump the estimate one tick to account for the added diff but otherwise I think it's fine.

As @tofumatt said, the rule is already enabled for us, it just wasn't being enforced for some reason so we can consider this somewhat of a bug fix at the same time 😄

**Comment by danielgent** [comment]
Bump if from 3 to 7?  3 hours seems fine though to check the diff, but your call!

**Comment by tofumatt** [comment]
IB ✅

**Comment by ivankruchkoff** [comment]
QA ✅
