### ISSUE TITLE
Add an eslint rule for functional components style

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#3513]
## Feature Description

Currently, we use two approaches for functional components: regular and arrow functions. This is not an issue but it would be nice if we can add an eslint rule that will force us to use one approach for all our functional components. Here is an example rule that we may use: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/function-component-definition.md

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All React components should be written as "regular functions", eg. `function MyComponent(props) {}`, not `const MyComponent = (props) => {};`

## Implementation Brief

* Using the [`react/function-component-definition`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/function-component-definition.md) ESLint rule:
  * For all (named components and unnamed) components: `function-declaration` should be forced. This is the way most named components are written, and we should be consistent with our formatting throughout.
* All ESLint errors caused by this change should be fixed.

### Test Coverage

* ESLint should pass; no tests are needed.

### Visual Regression Changes

* N/A

## QA Brief

* `npm run lint` should pass and components written like `const FooComponent = () => {};` should cause an ESLint error.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
ACs and IB here are similar, but adjust the ACs slightly and used the previous ones as the IB 🙂 

The ACs should be more explicit with the outcome here, eg. which type of rule to force for each type of component. In reality, since this is just about consistency, I've opted for the `function-declaration` style everywhere.

IB ✅

**Comment by aaemnnosttv** [comment]
@tofumatt left a question for you on the PR 👍

**Comment by tofumatt** [comment]
Left a reply, back over to you 😄

**Comment by tofumatt** [comment]
QA ⚠️

@eugene-manuilov noticed the `TextField` stories were duplicated as part of this change, seemingly due to the auto-fix confusing something 🤔

You can see the issue in the PR here: https://github.com/google/site-kit-wp/pull/7952/files#diff-1daab5b6a6decade51f9c48c84e163820c01c4aea8c229472497f575e8e77db7R76-R134 and in stories:

![CleanShot 2023-12-19 at 12 14 43](https://github.com/google/site-kit-wp/assets/90871/3171a667-ec67-4f08-a3b8-5c5521d61e15)

I'll work on a follow-up PR to remove those extra stories/VRTs.

**Comment by nfmohit** [comment]
Thank you for the follow-up PR, @tofumatt. It is now merged. This is back in QA for another pass, thanks!

**Comment by hussain-t** [comment]
### QA:Eng Update ✅ 

1. Verified errors with the ESLint VS Code plugin enabled

![Screenshot 2024-01-03 at 12 00 32 PM](https://github.com/google/site-kit-wp/assets/24408261/7f15f7c7-bf69-4ed6-98ad-1337139738c1)

2. Verified errors by executing `npm run lint`  with the ESLint VS Code plugin disabled

![Screenshot 2024-01-03 at 12 22 09 PM](https://github.com/google/site-kit-wp/assets/24408261/e2ff3669-8ef1-4105-ae6e-c2885c64965d)
