### ISSUE TITLE
Implement Idea Hub widget functionality for saving and unsaving an idea

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3519]
The Idea Hub widget's functionality to save and "unsave" an idea should be implemented.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Idea Hub widget functionality for saving and unsaving an idea should be implemented:
    * When clicking on the pin icon in the "New" tab, the idea should be saved via the `saveIdea` action of the `modules/idea-hub` data store. After completing the action, both the "New" and "Saved" tabs should be "force-refreshed" via re-running the two respective API calls after clearing their client-side caches. The number on the "Saved" tab should accordingly increase by 1.
    * When clicking on the pin icon in the "Saved" tab, the idea should be unsaved via the `unsaveIdea` action of the `modules/idea-hub` data store. After completing the action, both the "New" and "Saved" tabs should be "force-refreshed" via re-running the two respective API calls after clearing their client-side caches. The number on the "Saved" tab should accordingly decrease by 1.

## Implementation Brief
All the following will be inside [assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js](https://github.com/google/site-kit-wp/blob/90cada68c0294b915f9ac71e17b780e4d98395d6/assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Idea.js).

In the `handlePin` callback, call the `saveIdea` action from the Idea Hub store. 
- Pass the `ideaName` (i.e. the component's `name` prop) and await the response. (eg. `await dispatch( MODULES_IDEA_HUB ).saveIdea( name )`)
- Clear the cache by calling [`await invalidateCache()`](https://github.com/google/site-kit-wp/blob/d778e6b404670e446c394e925c6e7a77e0caac94/assets/js/googlesitekit/api/index.js#L299) for the `new-ideas` and `saved-ideas` endpoints (i.e. call it twice, passing `'modules', 'idea-hub', 'new-ideas'` and `'modules', 'idea-hub', 'saved-ideas'` respectively).
- Force-refresh the component by dispatching the Idea Hub store's `fetchGetSavedIdeas()`  and `fetchGetNewIdeas()` actions. Verify that the number on the 'Saved' tab increases by 1.

Now do a similar thing for un-saving (unpinning) an idea.
In the `handleUnpin` callback, call the `unsaveIdea` action from the Idea Hub store. 
- Pass the `ideaName` (i.e. the component's `name` prop) and await the response. (eg. `await dispatch( MODULES_IDEA_HUB ).unsaveIdea( name )`)
- Clear the cache as before by calling `await invalidateCache()` for the `new-ideas` and `saved-ideas` endpoints.
- Force-refresh the component as before by dispatching the Idea Hub store's `fetchGetSavedIdeas()`  and `fetchGetNewIdeas()` actions. Verify that the number on the 'Saved' tab **decreases** by 1.

### Test Coverage

* No new tests needed; existing tests should pass.

### Visual Regression Changes

* None anticipated.

## QA Brief
* Visit the "Idea Hub -> Components -> Widgets -> DashboardIdeasWidget -> Data Unavailable: Saved"
* Click on the "New" tab. Check functionality to pin and dismiss an idea
* Click on the "Saved" tab. Check functionality to unpin an idea.

## Changelog entry

* Implement Idea Hub widget functionality for saving and unsaving an idea

**Comment by tofumatt** [comment]
So, the problem with this approach is that it's a touch incomplete: we cache the API responses on the client, yes, but the selectors are also already resolved, so we'd need to call `dispatch( MODULES_IDEA_HUB ).invalidateResolutionForStoreSelector( 'getSavedIdeas' )` and `dispatch( MODULES_IDEA_HUB ).invalidateResolutionForStoreSelector( 'getNewIdeas' )`. That alone isn't a big deal, but this is:

https://github.com/google/site-kit-wp/blob/9d9c1c3a57455927c9e5773eb51cb7df2630f4ca/assets/js/modules/idea-hub/datastore/saved-ideas.js#L47-L52

We do this in a lot of places—I forget why at this point… I think it might be to have an easier time receiving data and then having resolvers not request API data again if they've never resolved. But it means the above `undefined` check needs to be removed, because otherwise the resolver will not re-request code even if the API cache is cleared. We can't simply dispatch `receiveGetNewIdeas( undefined )` because that'll cause `invariant` errors.

Sorry for complicating this (and not catching it when we first discussed this issue), but that check will need to be removed as well, which might involve updating some tests.

Let me know if you need any clarifications here or if the above is enough to work with, but I think this will require re-working the `getSavedIdeas` and `getNewIdeas` resolvers.

**Comment by tofumatt** [comment]
Just a note that reference was made to `fetchGetSavedIdeas()` and `fetchGetNewIdeas()` as selectors, but they're actually actions that need to be dispatched to update the data store. Not a huge deal; I updated the IB accordingly.

I also added a note to `await invalidateCache` as well, because our API cache layer is async.

Otherwise looks good, the approach is right-on.

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@asvinb having a few difficulties getting this working, here are the steps I took. 

I am using the `Test Idea Hub connection` plugin to force Idea Hub into a connected state.  I am also using the Tester plugin with the ` ideaHubModule` feature flag enabled. I successfully [connected to Idea Hub](https://user-images.githubusercontent.com/73545194/125085602-0f068300-e0cb-11eb-8283-92266672209a.png) and can see the `DashboardIdeasWidget` on Site Kit dashboard.   When I click on the `Pin` and `Dismiss`  icons, in the `New tab` an error appears in the console.  I tried this a few times, since I know jurassic.ninja sites can be temperamental. 

![image](https://user-images.githubusercontent.com/73545194/125086406-e6cb5400-e0cb-11eb-89bb-7ad5a155f9ac.png)

`react_devtools_backend.js:2560 Google Site Kit API Error method:POST datapoint:update-idea-state type:modules identifier:idea-hub error:"The response is not a valid JSON response."`

**Comment by asvinb** [comment]
@wpdarren This is expected for now since #3518 is still under development.

**Comment by eugene-manuilov** [comment]
@wpdarren @asvinb Yes, the real Idea Hub APIs aren't connected yet. So those errors should be expected for now.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

When visiting Storybook as per the QAB:

- The "New" tab. The `X` icon dismissed the idea and the `Pin` icon sent the idea to the `Saved` tab
- The "Saved" tab. When clicking the `Pin` icon, it was removed from the tab.
