### ISSUE TITLE
User feedback show terms in the footer

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3528]
## Feature Description

Potential to add 'terms and conditions' section at the bottom of the user feedback notice as per discussion [in Asana](https://app.asana.com/0/1200379030254833/1200441839407985).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* _If_ the current user has not opted in to Site Kit's regular Analytics tracking, the user feedback survey (specifically only the first question) should also include a footer informing about the data being sent to Google.
    * The copy should be: _ By continuing, you agree to allow Google to use your answers and account info to improve services, per our Privacy & Terms._ (this is intentionally slightly different from the text in the screenshot below, as we don't send any system information)
    * The word "Privacy" should link to `https://myaccount.google.com/privacypolicy?hl={currentLocale}`
    * The word "Terms" should link to `https://policies.google.com/terms?hl={currentLocale}`
    * The locale value used for these (and in principle any URLs using the `hl` query parameter) should only include the first two segments of the actual locale (see #2105).
    * It should have a separator above with equal spacing above and below, and generally it should follow the design from the following screenshot (which shows a demo survey in one of Google's own services):
![image (3)](https://user-images.githubusercontent.com/3531426/121406634-3f63d180-c913-11eb-9a22-47d66d4ba227.png)

## Implementation Brief
* Using `assets/js/googlesitekit/datastore/site/info.js`,
    * Update the `getGoogleSupportURL` selector to have the host of the URL dynamic (default value: `support.google.com`) so that the host can be specified and not hardcoded to `support.google.com`.
* Using `assets/js/components/surveys/CurrentSurvey.js`,
    * Query the user data store via the `isTrackingEnabled` selector to check if tracking is enabled.
    * Check if `isTrackingEnabled` is still resolving, via the `hasFinishedResolution` selector of the user data store and return `null` if this is the case, meaning that the survey should not be displayed if it's still resolving.
    * Get the "Privacy" and "Terms" URL by querying the site data store via the `getGoogleSupportURL` selector passing the appropriate parameters.
    * If user tracking is explicitly set to `false`, and the question ordinal is `1`, then display the text as per the AC wrapped in a `p` tag, which is itself wrapped within a container with the `googlesitekit-survey__footer` class name. For e.g:
        ```js
        <div className="googlesitekit-survey__footer">
            <p>...</p>
        </div>
        ```
* Using `assets/sass/components/surveys/_googlesitekit-surveys.scss`, style the `p` tag within the `googlesitekit-survey__footer` class name. The p should have the following styles:
    * font size, font family same as the text below the first and last icons.
    * `border-top` set to `1px solid $c-iron`
    * `padding-top` of `12px`
    * `margin-top` of `-12px` so that the space before and after the paragraph is consistent and not have a big whitepace and also the form looks good when the footer is not present.
* Update the `CurrentSurvey` stories to include a story where the user has not enabled tracking so that the footer is visible. To disable tracking, use the `receiveGetTracking` action of the user data store, passing `enabled: false`.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief

* Ensure the User Survey is being displayed (use the User Survey plugin to trigger a survey when the dashboard is loaded, see the [User Feedback Bug Bash instructions for more info](https://app.asana.com/0/1200379030254833/1200379030254852))
* Go to the settings and turn off tracking.
* Go back to the dashboard and verify that you see terms conditions like explained in the AC.

## Changelog entry

* Show Terms of Service and Privacy Policy in User Feedback survey if the user hasn't opted-in to tracking.

**Comment by tofumatt** [comment]
Two things to note for the IB here:

1. The IB says "If tracking is enabled, and the question ordinal is 1, the display the text as per the AC…" but I think that was a typo, it should display the text if tracking is _not_ already enabled. If the user enabled tracking they're already fine sending data and have agreed to the terms. So we want to display this on the first question, when `isTrackingEnabled` is explicitly `false`, not falsey.
2. More importantly: this means we should NOT display the survey AT ALL until the `isTrackingEnabled` selector has resolved and we have a non-`undefined` answer. If the user doesn't have tracking enabled (meaning they haven't agreed to share data or the terms of service) and we _don't_ show the notice about how we'll treat their data because the resolver is still loading, it could give them a chance to answer without being informed of the way their answer will be handled.

So I think we need to explicitly wait to render until `isTrackingEnabled` is resolved and to note that in the IB. Otherwise there's the possibility that a privacy notice would "jump in" after an answer, or worse not load until after the first question is answered, by which time we won't show it anymore.

**Comment by asvinb** [comment]
Good catch @tofumatt . IB updated. Can you review?

Thanks!

**Comment by tofumatt** [comment]
Lovely, thanks for using `hasFinishedResolution` as well, much nicer. 🙂 

For whoever implements this: it might be nice to add a storybook component for this option, but aside from that:

 IB ✅

**Comment by wpdarren** [comment]
### QA Update: Fail ❌ 

@eugene-manuilov a few observations:

1) The `privacy` link is `myaccount.google.com/privacypolicy?hl=en-US` but it redirects to `https://policies.google.com/privacy?hl=en-US` is that expected behaviour? Just wondering if we should hard code the link to the one it directs to? 

2) The `terms` link is `support.google.com/terms?hl=en-US` but it redirects to `support.google.com/?hl=en` rather than a page about the terms.  Is this the correct URL? 

3) Neither of the links open in a new tab/window, but I suspect they should, would you agree? 

4) Looking at the AC it mentions about equal spacing above and below, but I am not seeing this in the [screenshot](https://user-images.githubusercontent.com/73545194/122772308-278b3680-d29f-11eb-912a-8ded524658cd.png)

**Comment by felixarntz** [comment]
@wpdarren Thanks for pointing these out. Some clarifications:

1. That link is correct as is, but it should use a the two-letter language code instead of full locale (see ACs).
2. That link is incorrect as it's not what's in the ACs, plus it also should use the two-letter language code (see ACs).
3. That was not explicitly specified, but external links should always open in a new window/tab unless otherwise specified - so this needs to be changed.
4. Indeed, the spacing below looks like too much.

cc @eugene-manuilov

**Comment by eugene-manuilov** [comment]
Thanks, @wpdarren and @felixarntz. I have created a follow-up PR (#3610) that fixes these issues.

**Comment by tofumatt** [comment]
@felixarntz: Can you take a look at https://github.com/google/site-kit-wp/pull/3610#discussion_r656140747? I think the ACs here are a bit off and I just noticed that now, but I don't think we should be removing the second bit of the locale from URLs.

**Comment by felixarntz** [comment]
@eugene-manuilov @tofumatt Replied to the comment - apologies, this was a mis-assumption from my end. So this will need a few more changes to reflect the updated requirements.

**Comment by eugene-manuilov** [comment]
@felixarntz could you please take a look at Matthew's question here: https://github.com/google/site-kit-wp/pull/3610#discussion_r657231328 ?

**Comment by felixarntz** [comment]
@eugene-manuilov Left a reply. Let's cut off anything after the second segment (if there is more, which usually won't be, but might).

**Comment by bethanylang** [comment]
Sorry to barge in here, but wanted to add that there seem to be some missing words in the terms. It's currently:

> By continuing, you agree Google uses your answers and account info to improve services, per our Privacy & Terms.

This should change to:

> By continuing, you agree to allow Google to use your answers and account info to improve services, per our Privacy & Terms.

cc @eclarke1

**Comment by wpdarren** [comment]
### QA Update:  ⚠️ 

@eugene-manuilov @felixarntz this is looking good but an observation. On smaller screen sizes like mobiles, the spacing after the policy/terms notice is a concern for accessibility because you would have to touch the link to open it. On some devices  there is a menu/icons on the bar underneath, i.e. screenshot.  Wondered what you thought?  - [Screenshot](https://user-images.githubusercontent.com/73545194/123426909-e0ad8180-d5bb-11eb-965a-884bda8f9584.png)

**Verified:**

- Text on the feedback form reads  `By continuing, you agree to allow Google to use your answers and account info to improve services, per our Privacy & Terms`
- The word "Privacy" links to `myaccount.google.com/privacypolicy?hl=en-US`
- The word "Terms" links to `policies.google.com/terms?hl=en-US`
- The separator has equal spacing above and below, and follows the design in the screenshot
- Verified that the styling looks as expected on smaller screen sizes. 
- Checked the feedback form on primary browsers, i.e. Safari, Firefox etc. 

![image](https://user-images.githubusercontent.com/73545194/123424680-13a24600-d5b9-11eb-8b8e-1bfb8730c9bc.png)

**Comment by felixarntz** [comment]
@wpdarren Good catch! Re-posting your screenshots here for comparison:

**Here the spacing looks correct:**
![image](https://user-images.githubusercontent.com/73545194/123424680-13a24600-d5b9-11eb-8b8e-1bfb8730c9bc.png)

**Here the spacing looks off (below is less than above, making it hard to click the link):**
![image](https://user-images.githubusercontent.com/73545194/123426909-e0ad8180-d5bb-11eb-965a-884bda8f9584.png)

@eugene-manuilov Is that some weird situation with the mobile overlay that's causing this difference? It almost looks like it overlaps a small part of the screen, resulting in this bad appearance. Let's see if we can cater for that and make the spacing look appropriate also in the second case above.

**Comment by eugene-manuilov** [comment]
@felixarntz no, I don't think so. I have updated styles in the #3645, so it should look good now.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- Text on the feedback form reads  `By continuing, you agree to allow Google to use your answers and account info to improve services, per our Privacy & Terms`
- The word "Privacy" links to `myaccount.google.com/privacypolicy?hl=en-US`
- The word "Terms" links to `policies.google.com/terms?hl=en-US`
- The separator has equal spacing above and below, and follows the design in the screenshot
- Verified that the styling looks as expected on smaller screen sizes. 
- Checked the feedback form on primary browsers, i.e. Safari, Firefox etc. 

![image](https://user-images.githubusercontent.com/73545194/123424680-13a24600-d5b9-11eb-8b8e-1bfb8730c9bc.png)
