### ISSUE TITLE
A new GA4 property has not been created for a new account created via settings page

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3539]
## Bug Description

A new GA4 property has not been created for a new account created via settings page. Now I see wrong GA4 property on the view settings page.

[Related Asana task](https://app.asana.com/0/1200316599642381/1200447371742693)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When creating a new Analytics account via the setup flow, a new GA4 property for that account and the current site should also be created (in addition to the regular account creation process which already includes creating the UA property).
    * This was already implemented in #3252, but there seems to be a problem with the implementation.

## Implementation Brief

* Merge #3571

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Create a new account via setup or settings form.
* Verify that it also creates GA4 property with the appropriate web data stream.

## Changelog entry

* Update Analytics account creation to ensure a GA4 property is always created when GA4 is enabled.

**Comment by eugene-manuilov** [comment]
@felixarntz @aaemnnosttv after digging into this issue it turned out that this issue caused by insufficient permissions scopes error that is thrown when we call the `create` method: https://github.com/google/site-kit-wp/blob/af36f9384d3a56fedb3daddc74bbdbbbda1ad0e6/includes/Modules/Analytics_4.php#L224

Here is the error body:
```
{
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "errors": [
      {
        "message": "Insufficient Permission",
        "domain": "global",
        "reason": "insufficientPermissions"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}
```

Do you know how we can overcome it? :thinking:

**Comment by felixarntz** [comment]
@eugene-manuilov Oh I assume that is because creating an account only requires the `https://www.googleapis.com/auth/analytics.provision` scope, but creating the property requires the `https://www.googleapis.com/auth/analytics.edit` scope.

I suggest we therefore include _both_ scopes as new requirement for the `POST:create-account-ticket` data point. While strictly the second scope is only needed to create the property, from a user-facing perspective, this is now a single unified process - and technically the creation of an account includes already the creation of a UA property anyway (which would already require `https://www.googleapis.com/auth/analytics.edit` if it had been done individually).

The above fix should be fairly straightforward and would resolve this problem. Probably we should only require the extra scope for now if the `ga4Setup` feature flag is enabled.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov looks like we can do that pretty easily by conditionally adding that scope here:
https://github.com/google/site-kit-wp/blob/e1303f68e3645dbb05f262b72105fdaa4b09b47a/assets/js/modules/analytics/components/common/AccountCreate/index.js#L107

**Comment by eugene-manuilov** [comment]
Thanks, @aaemnnosttv. It helps!

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- I was able to create a new account via setup _and_ settings form.
- In both tests, a GA4 property was created (and UA property) 
- When looking in Google Analytics, both accounts have a GA4 property, with the appropriate web data stream.

Setup with GA4 and UA property for a new account  - [Screenshot](https://user-images.githubusercontent.com/73545194/122571968-32e32580-d045-11eb-9944-5303e8c49f5c.png)

Settings with GA4 and UA property for a new account  - [Screenshot](https://user-images.githubusercontent.com/73545194/122572027-42626e80-d045-11eb-8dcb-0c3df8adee94.png)
