### ISSUE TITLE
Existing GA4 tag detected but useSnippet not disabled

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3542]
## Feature Description

This is probably because the setting shown is for UA analytics. If the setting for GA4 is toggled here behind the scenes, it's confusing for the user.

[Related Asana task](https://app.asana.com/0/1200316599642381/1200441839408014)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* _If_ the `ga4Setup` feature flag is enabled and _if_ the user has already set a GA4 property during the Analytics setup flow, the `SettingsEdit` panel of the Analytics module should modify the way that it displays the toggle for `useSnippet`.
    * It should in that case display _two_ toggles, which appear next to each other, similar to how we have multiple toggles in a single row for the control to exclude certain user groups from tracking.
    * The first toggle should control the UA `useSnippet` setting, the second toggle should control the GA4 `useSnippet` setting.
    * The section label (i.e. label for the group of two toggles) should be: _Let Site Kit place the Analytics code on your site_
    * The first toggle should use label: _Place Universal Analytics code_
    * The second toggle should use label: _Place Google Analytics 4 code_
    * There should be a common description below which is conditional, one of (depending on the situation):
        * _Site Kit will add the Universal Analytics and Google Analytics 4 codes automatically_
        * _Site Kit will add the Universal Analytics code automatically_
        * _Site Kit will add the Google Analytics 4 code automatically_
        * _Site Kit will not add the code to your site_
* Just to clarify, in case GA4 is not set up yet, the existing UI should be kept as is - so it might make sense to create two high-level components to differentiate between.
* As part of this issue, no changes need to be made to `SettingsView`. That is worth doing, but can happen separately (slightly lower priority).

### Update

* If there is an existing GA4 tag in the frontend with the same measurement ID as the selected GA4 property's web data stream, the GA4 `useSnippet` setting should be disabled.
* If this happens during Analytics setup, the setting should be automatically disabled and saved upon form submission. If it happens during Analytics settings, the setting's toggle should be toggled off, but the user should be required to save in order for the changes to take effect.

## Implementation Brief

To start with, rename `UseSnippetSwitch` to `UseUASnippetSwitch`. Mentioning this here at the start to prevent confusion about which component is which 🙂 . All references to `UseUASnippetSwitch` can be thought of as references to `UseSnippetSwitch`, which should be renamed and imports updated.

### Add new component to render both switches
Create a new functional component,  `assets/js/modules/analytics/components/common/UseUAandGA4SnippetSwitches.js`
Most of the code in `assets/js/modules/analytics/components/common/UseUASnippetSwitch.js` can be re-used, with the following additions / changes:

#### Add additional selector logic for GA4
- We also need to query the GA4 store's `getCanUseSnippet` selector and `getUseSnippet` selectors, so 4 total constants need to be defined, e.g. `useGA4Snippet`, `canUseGA4Snippet`, `useUASnippet` and `canUseUASnippet`.
- Return `null` if either  `useGA4Snippet` or `useUASnippet` are `undefined`.

#### Implement two Switches instead of one
We will need to render two `Switch` components instead of just one - one for GA4 and one for UA:
- The UA switch's `checked` prop will reflect `useUASnippet` and its `disabled` prop will be `!canUseUASnippet`. The `label` will be `'Place Universal Analytics code'`.
- The GA4 switch's `checked` and `disabled` props will reflect the corresponding GA4 equivalents, and its `label` should be `'Place Google Analytics 4 code'`
- Each `Switch` should have its own `onClick` handler (for example `onUAChange` and `onGA4change`). Using the `onChange` handler from the existing `UseUASnippetSwitch` as a template:
	- call `setUseSnippet` from the relevant store (you will likely want to alias them to make it easier to read, e.g.
	```js
	const { setUseSnippet: setUseUASnippet } = useDispatch( STORE_NAME );
	const { setUseSnippet: setUseGA4Snippet } = useDispatch( MODULES_ANALYTICS_4 );

	const onUAChange = useCallback( () => {
		setUseUASnippet( ! useUASnippet );
		// ...
	}, [ ... ] );

	const onGA4Change = useCallback( () => {
		setUseGA4Snippet( ! useGA4Snippet );
		// ...
	}, [ ... ] );
	```
	- The UA handler will need to fire a `trackEvent` call as it does in `UseUASnippetSwitch.js`
- The switches should be rendered side by side (i.e. in a single row), with the UA switch on the right. See `assets/js/modules/analytics/components/common/TrackingExclusionSwitches.js` for an example.

#### Add description copy
Depending on which switch has been enabled, or whether both are enabled / disabled, render a description below the switches. It should read:
    - Both switches enabled: _Site Kit will add the Universal Analytics and Google Analytics 4 codes automatically_
    - UA enabled only  _Site Kit will add the Universal Analytics code automatically_
    - GA4 enabled only:  _Site Kit will add the Google Analytics 4 code automatically_
    - Both disabled: _Site Kit will not add the code to your site_

### Refactor and rename existing snippet switch component
Inside `assets/js/modules/analytics/components/common/UseUASnippetSwitch.js` 
- Change the `label` prop of the `Switch` component to read *'Place Universal Analytics code'*

### Put it all together
Inside `assets/js/modules/analytics/components/settings/SettingsForm.js`:
- Add an import for the new `UseSnippetSwitches` component
- Determine if the  `ga4Setup` feature flag is enabled by calling the `useFeature` hook
- Determine if the user has set a GA4 property by using the `getPropertyID` selector of the Analytics 4 module
- If the  `ga4Setup` feature flag is enabled AND there is an existing GA4 property ID:
	- render the `UseUAandGA4SnippetSwitches` component
	- otherwise, render the (renamed) `UseUASnippetSwitch` component
- The legend above the switch components should read _Let Site Kit place the Analytics code on your site_ (see how  the `Exclude from Analytics` legend has been done)

### Peripheries
- Add storybook coverage for the new permutations of the Analytics settings form which have been introduced here. 
- Existing stories (e.g. https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-settings--edit-open-with-all-settings) may need updating.
- Update VRT images as necessary.

### Test Coverage

* No new tests; existing ones should pass.

### Visual Regression Changes

* As mentioned above, some images may need updating.

## QA Brief

* Enable the `ga4Setup` feature flag 
* Set up Analytics with a GA4 property
* Navigate to the Analytics settings panel and click 'edit'
* You should see the two snippet switches (one for UA and one for GA4)
* If the `ga4Setup` feature flag is disabled and / or a GA4 property has not been chosen during set up, the settings form should revert to the previous structure, with a single snippet switch for UA. However, the copy should be updated (_Place Universal Analytics code_ etc.) as per the ACs.
* There should be a corresponding story in storybook under `Modules > Analytics > Settings > SettingsEdit > UA and GA4 tag snippet switches`
* The existing stories under `Analytics Module > Settings` do not handle the GA4 edge cases and should just be showing the UA snippet switch with the updated copy (_Place Universal Analytics code_ etc.) as per the ACs.
* Test the extra ACs under the "Update" section above. The tester plugin can be used to inject an existing tag with the same "G-xyzxyz" measurement ID that is present in the GA4 property you (intend to) connect.

## Changelog entry

* Show separate UA and GA4 snippet toggles in Analytics Settings.

**Comment by marrrmarrr** [comment]
@felixarntz these UI descriptions SGTM.

**Comment by felixarntz** [comment]
Thanks @marrrmarrr!

**Comment by johnPhillips** [comment]
Note to IB reviewer:
- I've estimated it at 15, largely because I was uncertain about refactoring in Storybook - there are about 5 stories that cover the 'edit' mode of the settings panel, for example. It might be that 11 is sufficient, let me know what you think.
- I wasn't sure whether there should also be a `trackEvent` call when the GA4 switch is toggled like the existing UA switch does

**Comment by tofumatt** [comment]
Looks great! I made a few tweaks to the IB to clarify `UseSnippetSwitch` vs `UseUASnippetSwitch`. I thought it was easier-to-follow with the renaming/import updates being mentioned at the top of the IB, then all subsequent references being to either `UseUASnippetSwitch` or `UseUAandGA4SnippetSwitches`, as appropriate.

To answer your questions: 15 hours and adding a `trackEvent` for GA4 sounds right to me. 👍🏻 

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@johnPhillips When `ga4setup` was enabled on the tester plugin, and I created Analytics UA and GA4 properties, all looked good. I could see the two switches in settings to place the UA and GA4 code on the site.  

![image](https://user-images.githubusercontent.com/73545194/123926592-ec19f780-d983-11eb-93e3-ef49315d0a55.png)

The issue arose though when I disabled `ga4setup` and then went into edit Analytics settings, this error appeared. 

![image](https://user-images.githubusercontent.com/73545194/123925929-4c5c6980-d983-11eb-856b-30700492118a.png)

I was expecting to be able to edit the settings and see the UA switch to place the code on the site.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Verified that `Place Universal Analytics code` and `Place Google Analytics 4 code` appears when GA4 is enabled on the tester plugin.  Also tested that the appropriate code appears in the source when settings updated. 

![image](https://user-images.githubusercontent.com/73545194/123968163-e685d700-d9ae-11eb-9c02-4816719fdd3b.png)

- Verified that `Place Universal Analytics code` appears when GA4 is disabled on the tester plugin.  Also tested that the appropriate code appears in the source when settings updated. 

![image](https://user-images.githubusercontent.com/73545194/123968343-0c12e080-d9af-11eb-9989-65a2ddecba0b.png)

- Checked Storyboard and under Modules > Analytics > Settings > SettingsEdit > UA and GA4 tag snippet switches.
- Checked Storyboard and the existing stories under Analytics Module > Settings show the UA snippet switch with the updated copy as per the ACs.

**Comment by felixarntz** [comment]
## Approval ❌ 

There is something missing here that @marrrmarrr  and I encountered while testing: If there is an existing GA4 tag on the page, it doesn't seem to affect the GA4 `useSnippet` toggle at all.

Taking a closer look, it appears that we missed this requirement in the ACs entirely, even though that specifically was the original reason to introduce the two toggles instead of one. So this is mainly on us, we refocused this issue on having two toggles for granular control, but then missed the original reason the issue had been opened in the first place. 🤦 

The missing behavior here is critical though, so we should get this in before the 1.36.0 release. With the release being next Wednesday, that should give us enough time to fix this follow-up piece.

I will go ahead and add the two bullet points to the ACs. Let's skip another IB for this one and dive straight into a follow-up PR with a fix, against `main`.

cc @wpdarren @eugene-manuilov @tofumatt @johnPhillips

**Comment by eugene-manuilov** [comment]
@felixarntz I have created a follow-up PR that adds the missing functionality. Also, it turns out that the GA4 API now returns `measurementID` prefixed with `G-` even though the [documentation](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/properties.webDataStreams#WebDataStream.FIELDS.measurement_id) still says that it returns without it. So, I have made the required changes to account for it.

Could you please review #3662?

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@eugene-manuilov can I just confirm this scenario:

During Analytics setup, a message appears saying that a tag is already used (because I entered it into the tester plugin). I am able to save the form by clicking on the `configure analytics` button. I then go to the Analytics settings and edit.  By default the GA4 `useSnippet` is disabled as expected. I am able to save the form with any changes, other than the GA4 switch. When I enable the GA4 switch, the save button is grey and deactivated.  

I am assuming this is correct because tag is already there?  Just want to confirm this. 

**Verified:**

- When the `ga4Setup` feature flag is enabled. Within the Analytics settings you can see two snippet switches.

![image](https://user-images.githubusercontent.com/73545194/124280251-5d9ea500-db40-11eb-896d-b9b233e9c515.png)

- When the `ga4Setup` feature flag is disabled the settings form reverts a single snippet switch for UA. 

![image](https://user-images.githubusercontent.com/73545194/124280485-a35b6d80-db40-11eb-990a-d62883d4d968.png)

- Checked Storyboard and under Modules > Analytics > Settings > SettingsEdit > UA and GA4 tag snippet switches. Checked Storyboard and the existing stories under Analytics Module > Settings and show the UA snippet switch with the updated copy.

- In the tester plugin, the the same measurement ID is added and within Analytics settings, the GA4 `useSnippet` setting is disabled by default and a message informing the user of this appears. 

![image](https://user-images.githubusercontent.com/73545194/124280593-c6861d00-db40-11eb-8492-6d9d42d7887b.png)

**Comment by eugene-manuilov** [comment]
> During Analytics setup, a message appears saying that a tag is already used (because I entered it into the tester plugin). I am able to save the form by clicking on the configure analytics button. I then go to the Analytics settings and edit. By default the GA4 useSnippet is disabled as expected. I am able to save the form with any changes, other than the GA4 switch. When I enable the GA4 switch, the save button is grey and deactivated.
>
> I am assuming this is correct because tag is already there? Just want to confirm this.

@wpdarren can you make a screencast? I can't reproduce it on my end.

**Comment by wpdarren** [comment]
@eugene-manuilov this is a screencast.  I am assuming this is the correct behaviour because the code is already on the site, but wanted to check because the QAB/AC didn't clarify this. 

https://user-images.githubusercontent.com/73545194/124290556-795b7880-db4b-11eb-8a20-403f6dd5ecd4.mp4

**Comment by eugene-manuilov** [comment]
@wpdarren yes, this is the correct behavior. What you show is this:

```
If it happens during Analytics settings, the setting's toggle should be toggled off, but the user should be 
required to save in order for the changes to take effect.
```
It detected the existing tag and automatically pre-disabled the `useSnippet` of the analytics-4 module. If you turn on it manually, it will mean that there is no changes, thus you can't save the form.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

**Verified:**

- When the `ga4Setup` feature flag is enabled. Within the Analytics settings you can see two snippet switches.

![image](https://user-images.githubusercontent.com/73545194/124280251-5d9ea500-db40-11eb-896d-b9b233e9c515.png)

- When the `ga4Setup` feature flag is disabled the settings form reverts a single snippet switch for UA. 

![image](https://user-images.githubusercontent.com/73545194/124280485-a35b6d80-db40-11eb-990a-d62883d4d968.png)

- Checked Storyboard and under Modules > Analytics > Settings > SettingsEdit > UA and GA4 tag snippet switches. Checked Storyboard and the existing stories under Analytics Module > Settings and show the UA snippet switch with the updated copy.

- In the tester plugin, the the same measurement ID is added and within Analytics settings, the GA4 `useSnippet` setting is disabled by default and a message informing the user of this appears. 

![image](https://user-images.githubusercontent.com/73545194/124280593-c6861d00-db40-11eb-8492-6d9d42d7887b.png)

During Analytics setup, a message appears saying that a tag is already used (because I entered it into the tester plugin). I am able to save the form by clicking on the `configure analytics` button. I then go to the Analytics settings and edit.  By default the GA4 `useSnippet` is disabled as expected. I am able to save the form with any changes, other than the GA4 switch. When I enable the GA4 switch, the save button is grey and deactivated.  

![image](https://user-images.githubusercontent.com/73545194/124297042-8d56a880-db52-11eb-9474-8f68304f9695.png)

**Comment by felixarntz** [comment]
Thanks @eugene-manuilov @tofumatt @wpdarren for getting this through so promptly!
