### ISSUE TITLE
Update language & format on Analytics tab post-GA4 connection

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#3588]
## Feature Description

After successfully connecting a GA4 property to an existing UA property in Settings > Connected Services > Analytics, the language and format of the message regarding GA4 continues to be an alert that prompts the user to connect:

![image](https://user-images.githubusercontent.com/12189958/122227606-07194180-ce85-11eb-9ac1-949da333847a.png)

This is confusing as there's already been a successful connection. Should we keep this styled as an alert box even post-connection? Would it be possible to at least change the language to indicate that a GA4 property is connected, i.e.:

"This GA4 property is currently connected. Use the dropdown to select a different GA4 property or create a new one."

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In the Site Kit `SettingsEdit` panel, _if_ a GA4 property was already provided on pageload (i.e. if it has been done before, e.g. in Analytics setup), the notice text above the dropdown should be conditionally adjusted to say: _This GA4 property is currently connected. Use the dropdown to select a different GA4 property or create a new one._

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@marrrmarrr Can you review the wording in the ACs (what @bethanylang suggested) and move forward to IB if good to go?

**Comment by johnPhillips** [comment]
I can't recreate this, even after discussion with @bethanylang, who was able to clarify that the steps to reproduce are as follows:
- deactivate tester plugin, and set up analytics with a UA property
- create a GA4 property using the setup assistant
- activate the tester plugin, and enable the GA4 feature
- now head to analytics settings and click 'edit'.

Inspecting redux, I can see that if I do this then GA4 is active but not connected. Looking in the [SettingsForm component](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/components/settings/SettingsForm.js#L91), it seems that the logic has changed and now requires GA4 to be connected.

So now I am wondering if this might have already been addressed by @eugene-manuilov as part of https://github.com/google/site-kit-wp/pull/3602?

Is someone able to confirm that this issue is no longer present using updated `main`?
CC @bethanylang @wpdarren

**Comment by wpdarren** [comment]
@johnPhillips sure, I can take a look at this and see if it can be recreated. c.c. @bethanylang

**Comment by eugene-manuilov** [comment]
Yes, the settings form has already been updated in #3586. @felixarntz I think we don't need this ticket and can close it, right?

**Comment by johnPhillips** [comment]
Assigning to @felixarntz for a verdict 👍

**Comment by felixarntz** [comment]
Yes, this was indeed already fixed via #3586. Closing.
