### ISSUE TITLE
Learn More Link for Idea Hub documentation landing at 404

### ISSUE THREAD

**Issue by abdullah1908** [google/site-kit-wp#3596]
## Bug Description
[Learn More](https://imgur.com/a/pwQdvOB) link for Idea Hub documentation is landing at [404 page](https://sitekit.withgoogle.com/documentation/idea-hub-module/).

## Steps to reproduce

1. Enable Idea Hub module from Tester plugin
2. Setup Idea Hub
3. On Complete Setup section you'll see Learn More link

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@abdullah1908 Good catch! I think we missed to actually look into this link.

@marrrmarrr @bethanylang We probably should create a documentation page on the website about the Idea Hub module as well, in time for when it launches. Particularly, people might be confused if they hear about it but then don't see it in Site Kit (which would be e.g. because they don't use a supported locale or don't yet have prompts available).

**Comment by marrrmarrr** [comment]
@felixarntz indeed, we will need a brand new page for this. @bethanylang is this something that the support team can apply the same process as we discussed for GA4 (test extensively, then write up the expected top questions?)

**Comment by bethanylang** [comment]
@marrrmarrr @felixarntz Yep, I have a task for drafting this documentation in July and we'll make sure to put it at the URL that's included throughout the product (https://sitekit.withgoogle.com/documentation/idea-hub-module/). 

Are we okay to close this out for now as it's being tracked in Asana?

**Comment by marrrmarrr** [comment]
@bethanylang SGTM!
