### ISSUE TITLE
Add features that other Plugins have - Google Analytics

### ISSUE THREAD

**Issue by ghost** [google/site-kit-wp#36]
Hello,

I would like to propose to the Google Team some additions to the plugin regarding Google Analytics (there are also attached screenshots):

1) Top 10 Countries, This list shows the top countries your website visitors are from ( https://ibb.co/zsJfGZT );

2) Top 10 Referrals, This list shows the top websites that send your website traffic, known as referral traffic. ( https://ibb.co/4MNDQgb );

3) Enable reporting on Demography and Interest for Remarketing and Advertising ( https://ibb.co/bddH32d )

4) Anonymize IP Addresses ( https://ibb.co/Sw3zcSJ )

5) New vs. Returning Visitors / Device Breakdown ( https://ibb.co/VHLmMwy )

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by sviluppomania** [comment]
@felixarntz

**Comment by sviluppomania** [comment]
@ivankristianto  @ThierryA

**Comment by felixarntz** [comment]
@ghost I have broken down this issue into a few sub-issues, since it encompasses multiple features and enhancements:

1. The top countries are now available in the new version of the All Traffic widget, which has been included in the Site Kit dashboard since version 1.25.0.
2. Please follow #3052 to keep track of this feature.
3. Please follow #3053 to keep track of this enhancement.
4. This was implemented in Site Kit a long time ago, i.e. this should no longer be relevant.
5. Please follow #3054 to keep track of this feature.

I will close this now as a duplicate, please refer to the issues above for further feedback.
