### ISSUE TITLE
Update Google PHP client services library to latest version (again)

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3628]
Since the Idea Hub API is still being under development and sees frequent updates, we need to make sure we keep the Google API client services library up to date so that we can work with the latest version of that API intuitively.

Unfortunately it looks like the entire library was recently bumped to a `0.2xx` (see [release notes](https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.200.0)), including a few substantial changes on the included code - so this update might not be super trivial. However, we shouldn't have to deal with overall API changes like we had to before with AdSense (see #3517), so it's still good we were able to do that separately.

Let's update to the latest version of the library, so that we have the latest Idea Hub API client code and then are set up updating it again in the future more easily to keep up with the Idea Hub API.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Google API client services PHP library should be updated to its latest version (`"google/apiclient-services": "^0.200"` in `composer.json`).
* The Site Kit PHP code using this library should be updated to still work correctly with the [high-level changes made in version 0.200.0](https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.200.0).
    * It also needs to be ensured that code is still properly included in the `third-party` directory via PHP-Scoper.
* From a QA perspective, this shouldn't result in any user-facing change, but there should be thorough testing throughout all modules to avoid unexpected breakage. Preferably this should be merged as early as possible in a release cycle, so that enough organic testing can happen.

## Implementation Brief
The goal here is to update the dependency, and load the site until it stops breaking, here's the general approach to do this:

* Ensure you have the following in your `wp-config.php` 
  * define( 'WP_DEBUG', true );
  * define( 'WP_DEBUG_LOG', true );
* Update `composer.json` per AC (version bump)
* Update the dependency`composer update "google/apiclient-services"`
* Next you'll need to update `scoper.inc.php` in several places to account for the updated paths:
  * https://github.com/google/site-kit-wp/blob/develop/scoper.inc.php#L74
  * https://github.com/google/site-kit-wp/blob/develop/scoper.inc.php#L83
  * One of the changes in the release is the move to psr-4 modules, so you'll need to load the `autoload.php` file. https://github.com/googleapis/google-api-php-client-services/blob/master/autoload.php
* Next re-run `composer install` and try loading the site, if any errors appear, resolve those too.

Once the site is up and running, test setting up each module to ensure the API for them still works as expected to get data.

### Test Coverage

* No new tests needed.

### Visual Regression Changes

* N/A

## QA Brief

* For engineering dev builds: install latest composer dependencies.
* Enable debug logging in WordPress
* Activate and use every module.
* Note any errors in debug.log, there shouldn't be any.

## Changelog entry

* Update Google PHP client services library to latest version

**Comment by ivankruchkoff** [comment]
Giving this a bigger estimate to highlight the testing that we'll need to do.

**Comment by tofumatt** [comment]
IB ✅ . 

I think it's a bit fuzzy exactly what this'll entail but that's the often case with issues like this 😆 . Thanks for the step-through of the approach though, and the estimate makes sense for something that'll take a lot of time to test. 👍🏻

**Comment by ivankruchkoff** [comment]
@felixarntz , question regarding the namespaces / classnames, with reference to the old / new code:

Old version sans namespace `Google_Service_AnalyticsReporting_OrderBy`:
https://github.com/googleapis/google-api-php-client-services/blob/7272d5407ae281c67259c8997a3d481e0b26dc51/src/Google/Service/AnalyticsReporting/OrderBy.php

New version with namespace `Google\Service\AnalyticsReporting\OrderBy`:
https://github.com/googleapis/google-api-php-client-services/blob/7272d5407ae281c67259c8997a3d481e0b26dc51/src/Google/Service/AnalyticsReporting/OrderBy.php

How do we prefer our updated scoped classes with namespace (all via changes to scoper.inc.php)?
Option 1) How we currently have it, by rewriting as :
`Google\Site_Kit_Dependencies\Google_Service_AnalyticsReporting_OrderBy`

Option 2) Prepending `Google\Site_Kit_Dependencies\` before all the namespaces to get us:
`Google\Site_Kit_Dependencies\Google\Service\AnalyticsReporting\OrderBy`

The only slight caveat with option 2, other than needing to update all of our imports is the following scenario:
https://github.com/google/site-kit-wp/blob/59a7d90b159a26aafb7cde5f9f457868bfdf0a8a/includes/Modules/Analytics.php#L59-L62

```
use Google\Site_Kit_Dependencies\Google\Service\Exception
use Exception
```

We can get around this by also using aliases e.g. `use Google\Site_Kit_Dependencies\Google\Service\Exception as Google_Service_Exception`.

My preference is to **Option 2** as it makes it very to see which class in the dependency corresponds to our source code rather than also doing some rewriting:
`Google\Service\AnalyticsReporting\OrderBy` becomes `Google\Site_Kit_Dependencies\Google\Service\AnalyticsReporting\OrderBy` and **NOT** `Google\Site_Kit_Dependencies\Google_Service_AnalyticsReporting_OrderBy`

**Comment by felixarntz** [comment]
@ivankruchkoff Good point, I agree with you we should go with option 2, keeping the real class names with simply a prefix. We can use aliasing where this causes issues.

**Comment by ivankruchkoff** [comment]
It seems that in https://github.com/googleapis/google-api-php-client-services/commit/0375af405757b36f3bcc82e19d7daf61e0b4cfd8 

`src/Google/Service/Pagespeedonline.php` is removed but `src/Pagespeedonline.php` isn't created. 
We use it here: https://github.com/google/site-kit-wp/blob/develop/includes/Modules/PageSpeed_Insights.php#L188

**Comment by ivankruchkoff** [comment]
To elaborate further, the previous commit has both `PagespeedInsights.php` and `Pagespeedonline.php`

https://github.com/googleapis/google-api-php-client-services/blob/7272d5407ae281c67259c8997a3d481e0b26dc51/src/Google/Service/PagespeedInsights.php

https://github.com/googleapis/google-api-php-client-services/blob/7272d5407ae281c67259c8997a3d481e0b26dc51/src/Google/Service/Pagespeedonline.php

Here's a diff of the two files, they're very close, but not sure if the differences are relevant to us or if the file should be re-added or if we need to create a separate ticket to upgrade from `Pagespeedonline` to `PagespeedInsights`.

**Comment by felixarntz** [comment]
@ivankruchkoff Looking at the latest source, basically the `Pagespeedonline` service was migrated to `PagespeedInsights` (see https://github.com/googleapis/google-api-php-client-services/blob/master/src/PagespeedInsights.php). The old one now is no longer present. The service itself hasn't really changed it looks like.

This needs to be changed in here as well, it cannot be in a separate issue since it would result in a temporarily broken state otherwise. The code looks slightly different, but most likely it requires no changes other than renaming the classes (and making sure we update the PHP Scoper config file so that it includes the new classes and no longer the old ones).

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- I tested this on two sites: 1) a new site with all modules connected but no data and 2) a live site with all modules connected with data.  Both of these sites had `Query Manager` and `Debug Toolbar` enabled and no errors appeared when connecting the modules or using them, changing date periods, engaging with the data, i.e. pie charts, etc.  
- No new console errors appeared while browsing Site Kit modules, settings, etc.
