### ISSUE TITLE
WPDashboardIdeaHub pulls saved ideas even though the Idea Hub module is not active

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#3634]
## Bug Description

When I checked XHR requests on the WordPress dashboard page, I noticed that there were Idea Hub requests that had been sent. It shouldn't happen because the Idea Hub module hadn't been activated on my site.

## Steps to reproduce

1. Make sure you have the idea-hub feature enabled, but the Idea Hub module disconnected.
2. Go to the WordPress dashboard page.
3. Check network requests
4. You should see XHR requests to the `/google-site-kit/v1/modules/idea-hub/data/saved-ideas` endpoint

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the Idea Hub module is disconnected, the WordPress dashboard widget should not send requests to pull saved ideas.

## Implementation Brief

* Merge #3635 

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Enable the `idea-hub` feature flag.
* Disconnect the Idea Hub module.
* Go to the WordPress dashboard page.
* Make sure there are no XHR requests to pull saved ideas.
* Activate the Idea Hub module.
* Go back to the WordPress dashboard page.
* Make sure you see XHR requests to pull saved ideas in the devtools.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
Thanks for raising this @eugene-manuilov.

Regarding your suggested fixes, it looks like the attached PR would work but I wonder if we should use this opportunity to simplify this component a bit in the process.

The main thing I see is that we're somewhat re-implementing `whenActive` inside the component rather than using that around it which would prevent the select from ever running if the module wasn't active like we use elsewhere. It might also be a nice touch to extend the HOC to accept an array of `features` which would all be required. If any of the features provided aren't enabled, it would also return `null` early. Then this component could be simplified quite a bit into only 2 (separate) selects for 
`getSavedIdeas` and `getAdminURL`. What do you think?

**Comment by eugene-manuilov** [comment]
@aaemnnosttv the `whenActive` HOC is tailored for widgets only. In my opinion, we should avoid using it for regular components to escape a need to maintain different use cases in the `whenActive` HOC.

**Comment by aaemnnosttv** [comment]
> @aaemnnosttv the `whenActive` HOC is tailored for widgets only. In my opinion, we should avoid using it for regular components to escape a need to maintain different use cases in the `whenActive` HOC.

While we currently only use `whenActive` for widgets, I don't think it should necessarily be a widget-only HOC. Conditionally rendering another component using an HOC is one of the main use-cases for using an HOC for us because of the unconditional nature of hooks.

I'll move this forward for now and we can explore refactoring with `whenActive` or potentially a new/alternative HOC in a separate issue.

IB ✅

**Comment by Hazlitte** [comment]
** QA Eng ✅ * *
Without the feature flag enabled I don't see `saved-ideas` XHR requests on the WP dashboard.  I do when it is enabled.
