### ISSUE TITLE
Fix refactored AdSense module screen to behave similar to legacy one

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3667]
## Bug Description

The refactored version of the AdSense module screen is missing one specific required behavior that is present in the legacy version: If there is no data available, it should show a special state, rather than the regular CTA summary that other module screens show.

In addition, there is another thing that is simply a bug: It attempted to show me Analytics data for my AdSense account, even though I don't have Analytics connected.

For reference about both of these issues, two screenshots here:

**Legacy state (expected behavior)**
<img width="1551" alt="Screen Shot 2021-07-02 at 9 58 15 AM" src="https://user-images.githubusercontent.com/3531426/124307059-1d2d3000-db1c-11eb-96c2-86b9fc13564e.png">

**Refactored state (incorrect behavior about both things above)**
<img width="1551" alt="Screen Shot 2021-07-02 at 9 58 30 AM" src="https://user-images.githubusercontent.com/3531426/124307068-20282080-db1c-11eb-869e-1284951d133c.png">

To replicate:
1. Use an AdSense account/site where you don't have any impressions (yet).
2. Connect AdSense, but not Analytics.
3. Toggle the `widgets.moduleScreens` feature flag. If enabled, you see the above incorrect UI. If disabled, you see the expected UI.

While those two bugs are somewhat decoupled, they should be small enough and are in a related place so it should be good to fix them both as part of this issue.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

With the `widgets.moduleScreens` flag enabled:
* The refactored AdSense widgets which require Analytics should only request data if the Analytics module is also active and connected, in addition to AdSense.
* If the AdSense module screen is in a complete "zero data" state, instead of showing the blue CTA, the same UI that is present in the first screenshot above should be displayed.
* Essentially, the user-facing experience should be similar to the one with the feature flag disabled.

#### Only request Analytics data when Analytics module is active and connected 
In `assets/js/modules/adsense/components/module/ModuleTopEarningPagesWidget/index.js`:
- wrap the exported component in the `WhenActive` HOC, passing `'analytics'` as the `moduleName` prop, so that it is only loaded if the Analytics module is both connected and active

#### Show special state component when there is no AdSense data
In `assets/js/modules/adsense/components/module/ModuleOverviewWidget/index.js`
- In the zero data case, modify the returned code so that the `DashboardZeroData` component is returned as well as `WidgetReportZero`. 
- `WidgetReportZero` should be hidden using the `HIDDEN_CLASS` CSS class from `widgets/util`. 
- Both should be wrapped in a `<Widget noPadding>` wrapper.

  For example:
  ```js
  if ( /* zero data */ ) {
	return (
		<Widget noPadding>
			<DashboardZeroData />
			<div class={ HIDDEN_CLASS }>
				<WidgetReportZero moduleSlug="adsense" />
			</div>
		</Widget>
	)
  }
  ```
#### Peripheries 
* Double check Storybook - the ['Data Unavailable' story for the module overview component ](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/adsense-module-components-module-overview-widget--data-unavailable) should show the new zero data component.
* VRT images may need updating.

### Test Coverage

* No new tests required; existing tests should pass.

### Visual Regression Changes

* VRT images will need updating to reflect these two new scenarios.

## QA Brief

* You'll need to compare the legacy UI with the new one, so open a tab with the `widgets.moduleScreens` feature enabled, and follow the steps to reproduce above. The UI in question is on the AdSense module page.
* Open a second tab, switch the `widgets.moduleScreens` off, and navigate to the AdSense module page to see the legacy UI.
* Compare the tabs: the new UI should be the same as the legacy UI.

## Changelog entry

* Fix message for AdSense account with no data in new widget-based screen.

**Comment by aaemnnosttv** [comment]
> Refactor these two files so that the data is only requested from Analytics if the Analytics module is both connected and active

@johnPhillips – the outlined approach for this part sounds a bit manual. Let's use the `whenActive` HOC for this as that's exactly what we need. No fallback or incomplete components needed 👍 

> if there is no data, rather than displaying the `WidgetReportZero` component, display the `DashboardZeroData` component

This is correct, but it's important to note that the `DashboardZeroData` component shouldn't be wrapped with a `Widget` as the `WidgetReportZero` currently is.

Also, I don't think this would hide the other widget on the page if Analytics was connected. We should either update `DashboardZeroData` so that it sets the same widget state as `WidgetReportZero`, or render them both (using `WidgetReportZero` from props) but hiding `WidgetReportZero` so that only `DashboardZeroData` is visible. Then the other widget would check the widget state and return `WidgetNull` if the main widget's state was `ReportZero`. Does that make sense?

**Comment by johnPhillips** [comment]
> Let's use the whenActive HOC for this as that's exactly what we need. No fallback or incomplete components needed

This is really helpful, thanks. Looks like `DashboardTopEarningPagesWidget` is already using it and requires both Analytics and AdSense to be active. Should `ModuleTopEarningPagesWidget` require both modules to be active as well, or just Analytics? 

> update DashboardZeroData so that it sets the same widget state as WidgetReportZero

Do you mean literally the same state, i.e. with `ReportZero` as the `Component`?
```js

useWidgetStateEffect( 
 'adsenseModuleTopEarningPages', 
  ReportZero, 
  { moduleSlug: 'adsense' },
);

```

There seem to be a few layers of abstraction with `WidgetReportZero` and I'm not sure how many to replicate. If I take this approach:
- should I use the same pattern as with `ReportZero` / `WidgetReportZero`, i.e. leave `DashboardZeroData` as-is, and create a wrapper (the analogue of `WidgetReportZero`) that calls `useWidgetStateEffect`? Or should I just add the effect to `DashboardZeroData` (I'm wary of breaking something - it does seem to be used in a couple of places, but I think they are all legacy...)?
- I'm guessing I should create a constant for the widget slug ('adsenseModuleTopEarningPages') so that it can be passed to `useWidgetStateEffect`, and then use it to replace [the string in the index file](https://github.com/google/site-kit-wp/blob/192106fa6ba8ee33db874cd892ead81aeb167778/assets/js/modules/adsense/index.js#L137)?

> Then the other widget would check the widget state and return WidgetNull if the main widget's state was ReportZero. Does that make sense?

I'm unclear on what 'the other widget' and 'the main widget' refer to here, sorry. 🙈

**Comment by aaemnnosttv** [comment]
> Looks like `DashboardTopEarningPagesWidget` is already using it and requires both Analytics and AdSense to be active. Should `ModuleTopEarningPagesWidget` require both modules to be active as well, or just Analytics? 

@johnPhillips `DashboardTopEarningPagesWidget` requires both because it's a (main) dashboard widget. Widgets are always registered regardless of module activation so the HOC includes both there because users will be able to access the dashboard before activating any additional modules. `ModuleTopEarningPagesWidget` is for the module dashboard only which is only reachable if AdSense is connected, so we don't need to include AdSense for that too, just like we don't check if Analytics is active for its `Module*Widget` components.

> There seem to be a few layers of abstraction with `WidgetReportZero` and I'm not sure how many to replicate

I think the better route is to not replicate any of it, and render _both_ – the only caveat is that we need to hide the report zero component so that we get the benefit of its effect without the display.

E.g.
```js
// const ModuleOverviewWidget = ( { Widget, WidgetReportZero, WidgetReportError } ) => {
// ... 
	if ( /* zero data */ ) {
		return (
			<Fragment>
				<DashboardZeroData />

				<div class={ HIDDEN_CLASS }>
					<WidgetReportZero moduleSlug="adsense" />
				</div>
			</Fragment>
		)
	}
```

> I'm unclear on what 'the other widget' and 'the main widget' refer to here, sorry. 🙈

Yeah, sorry for the ambiguity there. By "other widget" here I meant on the module screen, i.e. `ModuleTopEarningPagesWidget` – the one other than the overview above 🙂 

I hope that clarifies things a bit more. Let me know if you have any other questions though.

**Comment by johnPhillips** [comment]
@aaemnnosttv Thanks for this, it clarifies things.

I agree, I think route B is the more sensible one. I've edited the IB accordingly. The only divergence is from this:

> it's important to note that the DashboardZeroData component shouldn't be wrapped with a Widget as the WidgetReportZero currently is.

I found that adding `<Widget noPadding>` looked pretty identical to the legacy UI (which uses a `div` with `googlesitekit-layout googlesitekit-layout--fill` classes applied. Was there another reason to avoid `Widget`, or was it just for the padding?

**Comment by aaemnnosttv** [comment]
> Was there another reason to avoid `Widget`, or was it just for the padding?

I don't think so. If it looks right then that should be fine 👍  Thanks!

IB ✅

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

Tested this with a site that has active AdSense account but no data. 

With the `widgets.moduleScreens` flag enabled: 

- The AdSense module screen is in a complete "zero data" state, instead of showing the blue CTA as per the screenshot.

Comparing this with the `widgets.moduleScreens` flag disabled: 

The user-facing experience is the same to the one with the feature flag enabled.

![image](https://user-images.githubusercontent.com/73545194/125652846-67b4b75e-5d42-4ede-a7d7-ee25af3788bd.png)
