### ISSUE TITLE
Google Analytics Module Links Default to 7 Days Rather than Period Selected

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3684]
## Bug Description

This issue only occurs on the legacy widgets, so not sure if we want to fix this, but thought it deserved a ticket. 

On the Google Analytics module page, the external links on all widgets on the page default to 7 days instead of the period selected in the dropdown. E.g. 90 days is selected on Site Kit, when the link is clicked the report opens in Analytics and the date period is 30 June to 6 July. 

![image](https://user-images.githubusercontent.com/73545194/124785780-71cf1180-df47-11eb-822c-3c0ca63d30cf.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks @wpdarren – this was addressed in #3042 for the widget-based screens only. Legacy dashboards have been omitted from this to avoid extra effort for non-critical things like this which will be removed soon anyways.

Closing this as a wontfix since widget-based dashboards will be the only ones as of 1.38.0. See #1997 and #2077
