### ISSUE TITLE
Link components render `button` tag even when `href`/`to` props are supplied

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#3719]
## Bug Description

The React Router (#2514) PR (#3309) introduced a regression: any `Link` with an `onClick` prop is _always_ rendered as a `<button>` tag, but it should really only be rendered as a `<button>` if there is no `href`/`to` prop.

## Steps to reproduce

1. Visit the Help Menu
2. Click on any help link
3. Note it doesn't navigate/have a `href` prop and is rendered as a `<button>` tag when it should be an `<a>` tag.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Any `<Link>` component with a `href`/`to` prop should render as an `<a>` tag in the HTML

## Implementation Brief

* Merge #3718.

### Test Coverage

* Add tests to ensure the correct HTML tag is output

### Visual Regression Changes

* N/A

## QA Brief

* Ensure the help links above work

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update ✅ 

Verified that the help menu links now function as expected.  I also tested the other links on the Site Kit dashboard as reported in [#3713](https://github.com/google/site-kit-wp/issues/3713) and those links are also now working. 

Just c.c @cole10up because is currently working on (#2514) as far as I am aware.
