### ISSUE TITLE
Idea Hub dashboard widget layout shift when switching tabs

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3723]
## Feature Description

Currently the Idea Hub dashboard widget has the potential to render different heights on different tabs resulting in a layout shift. This may only be possible in the zero-data state for Search Console, but we should try to keep the height stable regardless whether or not it has ideas or not.

https://user-images.githubusercontent.com/1621608/125916893-ba054fa5-bfff-48dc-b197-6eb4400fc960.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Idea Hub dashboard widget should maintain the same height across all of its tabs once loaded
* Secondarily, the height may vary between viewport sizes (it should remain responsive to allow for wrapping text, etc)

## Implementation Brief

* Go through three files below and:
  * Remove the block that returns `null` if the `active` prop is falsey
  * Remove the `active` prop altogether, along with the `propTypes` definition.
  
  ```
  assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/NewIdeas.js
  assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/SavedIdeas.js
  assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/DraftIdeas.js
  ```
* Inside `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`, remove the assignments of the `active` prop to the above components.

* Inside `assets/sass/components/idea-hub/_googlesitekit-idea-hub-dashboard-ideas-widget.scss`:
  * Add `display: flex` to `.googlesitekit-idea-hub__body`
  * For the rule addressing `.googlesitekit-idea-hub__content[aria-hidden="true"]`:
    * Remove `display: none`, and replace with `visibility: hidden`. This will hide the inactive tab, but it will still take up the same space in the document flow that it would if it were visible.
    * Add `margin-right: -100%;`, which will move the visible tab into view.
  * Add a new `visibility: visible` rule for ` .googlesitekit-idea-hub__content[aria-hidden="false"]`. This will make the active tab visible.
  * See the following gist if the above is unclear:
  ```diff
  +       .googlesitekit-idea-hub__body {
  +               display:flex;
  +       }
  +
          .googlesitekit-idea-hub__content {
  +                       width: 100%;

                  &[aria-hidden="true"] {
  -                       display: none;
  +                       visibility: hidden;
  +                       margin-right: -100%;
  +               }
  +
  +               &[aria-hidden="false"] {
  +                       visibility: visible;
                  }
  ```
* Merge #3746

### Test Coverage

* No new tests required.

### Visual Regression Changes

* Images dealing with this widget may need updating.

## QA Brief

* Load the dashboard such that the Idea Hub widget is visible on the dashboard
* Click through each of the tabs; the height of the Idea Hub widget should not change

## Changelog entry

* Improve the tab-switching UX in the Idea Hub dashboard widget.

**Comment by johnPhillips** [comment]
I ended up implementing a solution in the process of investigating this and writing the IB, so I've opened a PR. This is what the fix looks like:


https://user-images.githubusercontent.com/2470911/126355985-c69e2c4b-aac9-40dd-89ea-f592f78232b2.mov

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@johnPhillips an observation on small screen sizes, i.e. mobile.   When I click through the tabs, `new` and `saved` display fine, but the `draft` tab seems to jump down the page slightly.  It looks like the widget is the same size, but the behaviour is a little confusing.  This only happens when there are no drafts in the tab.  With drafts the tab loads fine. 

Here's a screencast

https://user-images.githubusercontent.com/73545194/126504724-800a98be-6434-4e8c-be13-866bd4749d61.mp4

**Comment by johnPhillips** [comment]
Hi @wpdarren,

This is a real head-scratcher! 

I've sunk a fair bit of time into investigating this, with the following observations:

- I can’t replicate this behaviour on an iPhone simulator via xcode (running Safari)
- I also can’t replicate it on Safari desktop using the emulator mode in dev tools.
- I _can_ replicate it on Chrome / Brave (which are very similar) using the phone emulator in dev tools.
- I swapped out the fix for an alternative which uses floats instead of flexbox, and was still seeing some jumping
- I investigated a couple of other theories and added some fixes to rule them out, and again was still seeing some jumping.
- The behaviour is annoyingly transient, meaning that sometimes I believe I've fixed it, only for it to happen again. 

It might be to do with the fact that we are using anchors in the URL. Sometimes I can observe a jump if I load the page and then scroll slightly before selecting a different tab.

Anyway, so far this is looking more like it might be a bug in chrome's phone / responsive emulator than a problem on mobile per se :exploding_head:

That said, I only have access to an iphone simulator via xtools. It might be an idea to try this out on some actual devices?

Let me know what you think 👍

**Comment by wpdarren** [comment]
@johnPhillips I'm going to run this through Browser Stack and also my mobile devices, so I have assigned it back to QA.  Thanks for the time looking into this.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

- Verified that the height of the Idea Hub widget does not change. 

I am going to also pass this for small screen sizes because after further testing on Browserstack,  the widget height does not change but there is odd behaviour when you click on the 'Draft' tab.  I feel this is low priority and will create an entry on the bug bashing board with screenshot.  c.c. @johnPhillips 

https://user-images.githubusercontent.com/73545194/126672533-24b0a967-3e01-4bb3-a5df-30a6ed8d72c5.mp4

**Comment by aaemnnosttv** [comment]
@felixarntz maybe worth a follow-up issue here, but looking at the component above, I feel like the "Updated every 2-3 days" should be closer to the bottom of the widget so that the layout fills the vertical space. As it is, it looks a little bit off to me. We could even move that part of the component to be a widget footer which would show on all tabs, although we could make it dynamic based on the selected tab. What do you think?

**Comment by felixarntz** [comment]
@aaemnnosttv Great point. I like the idea of making it a dynamic widget footer. Can you open an issue for that?
