### ISSUE TITLE
Move Idea Hub widget footer into Widget.Footer prop

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3773]
## Feature Description

In #3723, we made the Idea Hub widget's height consistent across all of the tabs. As a result, the layout of the widget looks somewhat off compared to other widgets because the footer content is not flush against the bottom of the widget.

![image](https://user-images.githubusercontent.com/1621608/127292260-d23a3287-0281-4fad-967e-5413de3f2f47.png)
 
The "updated every 2-3 days" line/component should be moved into a new `Footer` component that is rendered as a prop to `Widget.Footer`. It should still change based on the selected tab as it does today, but rendered in a different place.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Idea Hub `DashboardIdeasWidget` should be updated to render footer content for the selected tab into its `Widget.Footer` prop rather than as part of the tab-specific tab content component.
* ~~The passing of the prop should be conditional based on the selected tab – e.g. for no new/saved/draft ideas, the zero state should look the same as today (with no footer)~~

## Implementation Brief
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Pagination.js`
	* Remove the existing `total`, `page`, `ideasPerPage`, `handlePrev` and `handleNext` props.
	* Add a new prop `tab`, string having `new-ideas` as default value.
	* Query the `core/ui` data store via the `getValue` selector and passing a key which contains the `tab` value (for e.g `idea-hub-page-${ tab }`) to get the current page the user is on. The value should be assigned to the `page` constant. If the selector returns `undefined`, `page` should be `1`, meaning we are on the first page by default.
	* Get the total for each tabs by querying the `MODULES_IDEA_HUB` data store via the `getNewIdeas`, `getSavedIdeas` and `getDraftPostIdeas` selectors.
	* Then based on the value of the `tab`, assign the result of above selector call to the `total` variable.
	* Add 2 new functions, `handlePrev` and `handleNext` using the same logic as in `NewIdeas` but instead of using `setPage`, use the `setValue` action from `core/ui`, passing the unique key, for e.g `idea-hub-page-${ tab }`, as key and the appropriate value.
	* Replace `ideasPerPage` references by the `IDEA_HUB_IDEAS_PER_PAGE` constant.
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Footer.js`,
	* Remove the existing `totalIdeas`, `page`, `handlePrev` and `handleNext` props.
	* Add a new prop `tab`, string having `new-ideas` as default value.
	* Pass on the `tab` prop only to the `Pagination` component.
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/NewIdeas.js`,
	* Remove the `page` state variable. Instead grab the page for the new ideas tab by quering the `core/ui` data store via the `getValue` selector and passing the appropriate key, for e.g `idea-hub-page-new-ideas`
	* Remove the `handlePrev` and `handleNext` functions.
	* Remove the `Footer` component.
	* Repeat steps above for the `SavedIdeas` and `DraftIdeas` components.
* Using `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`,
	* Add the `Footer` prop to the `Widget` component, having the `Footer` component as value and passing `activeTab` as value for the `tab` prop.
* Update the styles for `.googlesitekit-idea-hub__footer` to remove the `padding` and `box-shadow`.
* Tweak the styles for `.googlesitekit-widget--ideaHubIdeas .googlesitekit-widget__footer` to that the borders of the footer align with adjacent widgets.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief

* Check the Idea Hub widget on the Site Kit Dashboard
* Tabs should work as before. Specifically
    * Changing tabs
    * Pagination on all tabs
    * Totals

## Changelog entry

* Update the Idea Hub widget to display its footer in the `Widget.Footer` prop.

**Comment by aaemnnosttv** [comment]
@felixarntz – anything to add/update here?

**Comment by felixarntz** [comment]
@aaemnnosttv 
> The passing of the prop should be conditional based on the selected tab – e.g. for no saved or draft ideas, the zero state should look the same as today (with no footer)

Shouldn't this also be if there are no new ideas?

**Comment by aaemnnosttv** [comment]
Thanks @felixarntz – I've updated the ACs to clarify that 👍

**Comment by asvinb** [comment]
@aaemnnosttv Please note I have added the IB which contains 2 potential solutions. A CSS only solution or another one which uses the `core/ui` data store.

**Comment by aaemnnosttv** [comment]
Thanks @asvinb! Overall, both versions of the IB look pretty good. The CSS-only solution seems appealing and doesn't technically meet the ACs but does achieve the same end result. Maybe it makes sense to do the CSS version first and revisit this later? It doesn't seem like much work to shift things around in React either; what do you think @tofumatt?

**Comment by tofumatt** [comment]
The CSS solution is clever, but the React one seems straightforward as well so I'd rather we do it that way 🙂 . If it were more complicated and this was a shipping bug I'd see the value in the quick-fix solution, but I don't think either are the case here so let's do it "properly". I'll admit though: that's a slick CSS-only solution, nice one @asvinb 👍🏻 

Let's go with the React version. IB ✅

**Comment by wpdarren** [comment]
### QA Update:  Pass ✅ 

- Can confirm that tabs are working as before. Specifically: changing tabs, pagination on all tabs and totals.


https://user-images.githubusercontent.com/73545194/128388644-b950a248-15a2-41df-8103-21d2ee17a2d5.mp4

**Comment by aaemnnosttv** [comment]
## QA ❌ 

@wpdarren there seems to be a detail that was missed, in that the footer should not appear in the case that there are no ideas for that tab – it should only show the zero state. Also you can see in the video that the size of the footer changes when switching to the saved ideas tab (which has none and I think the graphic squishes the footer).

Sending this back to @danielgent for a follow-up which should be fairly quick.

**Comment by danielgent** [comment]
I'm not sure what you mean by this @aaemnnosttv  :thinking: 

@eugene-manuilov  added a fix to my PR where he hides the new footer when the tab is empty

_when has pagination_

![footer with pagination](https://user-images.githubusercontent.com/8496063/128495551-b7d1d849-12a5-411d-990e-760e0eed25df.png)

_when empty_

![without pagination](https://user-images.githubusercontent.com/8496063/128495560-cef522b3-6c85-45ab-8f37-38534f4bb18a.png)

**Comment by danielgent** [comment]
I think what is wanted is that I make the footer size consistent with and without pagination

I'll fix this now by applying the padding to a different element... or maybe a min-height. I'll have a play around

**Comment by danielgent** [comment]
One thing I have noticed (which I'm surprised @aaemnnosttv  and @wpdarren  haven't picked up on) is the horizontal scroll now appearing :thinking: 

There are `.googlesitekit-idea-hub__content` divs flowing off the screen

![horizontal scroll](https://user-images.githubusercontent.com/8496063/128495883-7ef8dc7c-e1da-4da4-bdf7-684188c925d1.png)



If @aaemnnosttv  and @wpdarren  haven't picked up on it then that makes me wonder if it's just on my machine :upside_down_face:

**Comment by aaemnnosttv** [comment]
@danielgent I am aware of the overflow - I believe it is to  prevent the widget changing height when switching tabs which was a recent change. Cc: @asvinb

**Comment by wpdarren** [comment]
@aaemnnosttv apologies, I should have read the AC because it doesn't mention the footer in the QAB, although I realise that was the detail of the ticket.  Will make sure to double check. 

@danielgent I do have a note about the scrolling to add to the bug bash board because I assumed (possibly wrongly) when QAing this that this was not related.

**Comment by wpdarren** [comment]
@tofumatt @aaemnnosttv could you check that the QAB is correct? I just want to make sure I am not missing anything.

**Comment by aaemnnosttv** [comment]
@wpdarren it could be a little more detailed but essentially the change is that the "Updated every 2-3 days" with the pagination buttons has been moved into the footer of the widget itself rather than in the content part of the widget. When this is shown should still be the same as before. No ideas for any tab should still only show its graphic with no footer/pagination as before. The height of the widget should also not change between tabs as before. The thing that caught my eye from the initial round of QA was how the size of the footer changed between tabs, but also that the footer should not have been shown in the no-idea case.

From the screencast:
![image](https://user-images.githubusercontent.com/1621608/128835485-e3ec15fd-6760-47ac-b197-659c04402fe8.png)
![image](https://user-images.githubusercontent.com/1621608/128835507-2183f052-43bf-4e47-b8bc-503599c2ea3e.png)

Let me know if you have any other questions 👍

**Comment by wpdarren** [comment]
QA Update: ❌ 

Thanks for the explanation @aaemnnosttv 

`No ideas for any tab should still only show its graphic with no footer/pagination as before. `

When I go to the Saved or Draft tab with no ideas, the footer still appears with the text `Updated every 2-3 days` 

![image](https://user-images.githubusercontent.com/73545194/128842645-8c6ebe5c-a660-4945-ac41-e835620cf8b8.png)

Another observation when I paginate to the next page the widget area size changes. Should this always be the same size no matter how many ideas are in the tab? 

https://user-images.githubusercontent.com/73545194/128842562-467afaaf-48ee-41ec-b7d2-1f7f19e9ec65.mp4

I tested this on `main` and `develop` because I wasn't sure if this work was done before we made the switch. I also cleared session storage etc.  

**Verified:**

- Can confirm that tabs are working as before. Specifically: changing tabs, pagination on all tabs and totals.
- The issue with how the size of the footer changed between tabs is fixed.

**Comment by danielgent** [comment]
@wpdarren 
_When I go to the Saved or Draft tab with no ideas, the footer still appears with the text Updated every 2-3 days_

This was already like this.  The only change in this PR are the pagination controls :smile: 

_Another observation when I paginate to the next page the widget area size changes._

I don't see this at all!  Could you record a full-screen video to show us the resolution you're at? :thinking: 

I can't replicate this at all!  

https://user-images.githubusercontent.com/8496063/128906146-c60f8229-3a7f-46ae-915c-22f78e14991d.mp4

**Comment by wpdarren** [comment]
@danielgent the first observation was because of the [previous comment](https://github.com/google/site-kit-wp/issues/3773#issuecomment-895841868) @aaemnnosttv left  `No ideas for any tab should still only show its graphic with no footer/pagination as before.` I am assuming the `Updated every 2-3 days` is within the footer and wasn't expecting that to be there.  Can either of you clarify that? Apologies if I have misunderstood! 😄 

As for my second observation, yes, I am not seeing that now either, so please ignore that.

**Comment by danielgent** [comment]
Understood @aaemnnosttv !  I missed that point from the AC as it wasn't present in the IB :smile: 

_(I'll revert the follow up PR I did as that was totally wrong)_

I'm not too sure what to do here with the widget component.

Things I've tried
* **Adding extra height to an empty tab**
Does not work.  All tabs are always rendered, so the Footer appears below the tallest one

https://user-images.githubusercontent.com/8496063/129195359-f218ad1f-88d2-4219-a47c-a018f98faa6a.mp4

* **Absolutey positioning Footer**
Works, *but* breaks all the other widgets (note visual artifacts)

https://user-images.githubusercontent.com/8496063/129195470-1e2b3c9c-9878-405c-863a-965daafa6860.mp4

* **Pass in empty footer**
Does not work because `Widget` wraps the passed `Footer` component in a styled div.

```
{ Footer && (
    <div className="googlesitekit-widget__footer">
        <Footer />
    </div>
) }
```
Here I could pass a fixed height div for the `Footer` and we could maintain the same Footer height but we'd still get the border outline

https://user-images.githubusercontent.com/8496063/129196468-a6e98159-3d7d-44c8-9dc7-235a8453d3f7.mp4

**Comment by danielgent** [comment]
@aaemnnosttv  I've created a branch https://github.com/google/site-kit-wp/pull/3848 with a working fix on but I think this is descending into hacks around the design of the `Widget` component :stuck_out_tongue: 


https://user-images.githubusercontent.com/8496063/129196915-aa2c0b8e-4443-4402-8a27-1d26618d5794.mp4

I added a `placeholderFooter` prop to the `Widget` component and I'm passing in a fixed height empty div.

This works for now but it's far from ideal!

**Comment by aaemnnosttv** [comment]
@danielgent you can pass `Footer={ null }` to not render any footer or wrapping - have you tried doing something with that?

**Comment by danielgent** [comment]
@aaemnnosttv  Yes but then the height changes.

Not acceptable as you put in your previous comment:
_"Also very important is that the height of the widget does not change when switching tabs. From what I've seen, this is the complicated bit that together with a conditional footer makes it a bit tricky to meet both criteria."_

**Comment by aaemnnosttv** [comment]
@danielgent Yes, that's the tricky part. I'll open a new issue for this part to not block this issue. cc: @felixarntz

**Comment by aaemnnosttv** [comment]
@wpdarren sending this back to you for a final pass – note I've crossed out the second point in the ACs for now which we'll handle in a follow-up issue.
