### ISSUE TITLE
Display a notification when a user goes offline

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#3820]
## Feature Description

Currently, our dashboard and other js-driven pages don't react to the connection lost. So users won't notice it until they make an action that requires an API call and an error is shown. I think it would be a slightly better UX if we can inform the user that they lost connection beforehand by showing an appropriate notification.

We can use [online/offline events](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/Online_and_offline_events) to detect the online status changes and display/hide the banner, though we will also need to occasionally check against an actual site (like `captive.apple.com`, `google.com`, etc. because `navigator.online` only checks for a network connection, but not the reliability of one).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The user's online/offline status should be monitored in the background by some JS code.
  * A check to a URL should be made to ensure the user is online, as `navigator.online` alone is not enough, see: https://github.com/sindresorhus/is-online
* Whenever the user goes offline, display a toast/notification informing them that they're offline. This notification should be minimal and appear in a fixed place on the screen.
* The user should be able to dismiss the notification.
* When the user comes back online, the notification should be immediately cleared with them needing to do anything.

## Implementation Brief

The basics of writing the hook for monitoring internet connection are here: https://gist.github.com/tofumatt/5461b9ba3830877813d5959520f18c29

This could be placed at a high-level of the component tree.

* Extend the `core/ui` store initialState with a `isOnline: true`.
  https://github.com/google/site-kit-wp/blob/1c82eb46b7089f93172e0336e419397af7c8afef/assets/js/googlesitekit/datastore/ui/ui.js#L34-L36

* Create a new `useMonitorInternetConnection()` hook in `asset/js/hooks/`. See the the basic implementation from @tofumatt https://gist.github.com/tofumatt/5461b9ba3830877813d5959520f18c29
  * The hook should monitor the online status and set the `isOnline` on the `CORE_UI` store.
   * Check for `navigator.onLine`. If this returns false, set the isOnline status to false.
   * If it returns true, do a manual fetch request against `http://connectivitycheck.gstatic.com/generate_204` to verify the user is online because `navigator.onLine` is not reliable enough.
     * Only check of `onlineResponse.ok` and `onlineResponse.status === 204`, not a response content.
   * The online status should be checked on:
     * on mount
     * window events "online" and "offline"
     * On an interval, if current state is online, every 120 seconds, if current state is offline, every 15 seconds.
   * Ensure that intervals and event listeners are cleaned up on unmount.
   * Call this hook within the [MainDashboardApp](https://github.com/google/site-kit-wp/blob/1c82eb46b7089f93172e0336e419397af7c8afef/assets/js/components/DashboardMainApp.js).
 * Create a new "OfflineNotification" component in `assets/js/components/notifications`.
   * Get the isOnline state from the `CORE/UI` store.
   * If "isOnline" is false, use the `SettingsNotice` to render a Offline message according to the AC
   * To make the notice dismissable, create a "DISMISSED_KEY" const with the value "offline-notification" and pass it as the "dismiss" prop to the `SettingsNotice` component.
   * Style the component OfflineNotification to show up as a toast notification, with position fixed on the botton right of the screen.
   * Render this OfflineNotification component at the bottom of the `DashboardMainApp` component.
   * To ensure accessibility, the toast message should act as a "polite alert". Therefore wrap the `SettingsNotice` with a div a `aria-live="polite"` attribute. Ensure that the div is rendered (not visually shown), even when the user is online. 
   * Create a storybook story for the new `OfflineNotification` component and add it to VRT scenarios.

### Test Coverage
- Add new tests for the `useMonitorInternetConnection()` hook.
- Test online and offline state
- Test switching between online and offline state.

### Visual Regression Changes

* A new OfflineNotification VRT scenario should be added. All other scenarios should be unchanged.

## QA Brief

* Setup Site Kit
* Open a network tab, and switch between offline and online mode, or switch the WiFi off/on
* Verify that notice appears when offline, and dissapears when going back online
* When offline notice is dismissed, going back offline again should bring the notice back again

## Changelog entry

* N/A

**Comment by derweili** [comment]
To monitor the online status, we could use the google cloud health status endpoint and check for a 200 response. https://status.cloud.google.com/products.json

**Comment by tofumatt** [comment]
@derweili The captive Apple URL was suggested by my example because it's a very small payload (and it's also designed to be used for the purpose of checking a valid internet connection.)

I'm not sure if the GCLoud URL would ever get rate-limited, but the Apple one doesn't. Additionally, it's a much smaller payload:

![CleanShot 2023-12-07 at 22 09 15](https://github.com/google/site-kit-wp/assets/90871/d7d069a0-01c3-4b03-b2f2-7765215046a6)

![CleanShot 2023-12-07 at 22 09 32](https://github.com/google/site-kit-wp/assets/90871/08510eff-fdd0-47fb-8e4f-b907a1e3a718)

It's probably not a _huge_ deal, but it's a URL we'll request a lot, and the size difference is 9kB:

![CleanShot 2023-12-08 at 13 47 43](https://github.com/google/site-kit-wp/assets/90871/22c7f2ad-5ac3-4411-beae-58eedc3db2b2)
![CleanShot 2023-12-08 at 13 47 29](https://github.com/google/site-kit-wp/assets/90871/d304c7ce-b951-46a6-8598-21e8a8980042)

Let's use a smaller URL to do our offline checks 😄 

-----

Also, my example is probably a bit too aggressive with check intervals, we can probably do 120 online, 15 offline or something like that 😄

**Comment by tofumatt** [comment]
@derweili Nice, that works for me 👍🏻 

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@zutigrm I would be interested to know your thoughts on the placement of the notification.  While the AC says it should be `minimal and appear in a fixed place on the screen,` for me, it wasn't instantly obvious because I expected it to appear in the top half or center of the screen.   Other than this, all looks good. 

**Verified:**

- The notice appears when offline and disappears when going back online.
- When offline notice is dismissed, going back offline again should bring the notice back again.

https://github.com/google/site-kit-wp/assets/73545194/c8f34ba6-e64b-4153-b388-cb71871863fd

**Comment by zutigrm** [comment]
@wpdarren Thank you for checking this.

Usually this kind of "fixed" non-intrusive notifications appear in the bottom/bottom right edge of the screen, so I followed that logic.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@zutigrm Yes, that makes sense - I was thinking about it after leaving the comment.  All looks good! 

**Verified:**

- The notice appears when offline and disappears when going back online.
- When offline notice is dismissed, going back offline again should bring the notice back again.

https://github.com/google/site-kit-wp/assets/73545194/c8f34ba6-e64b-4153-b388-cb71871863fd

**Comment by aaemnnosttv** [comment]
## ❌ Approval

While this feature works and satisfies the AC, the implementation introduces a very large increase to Google API consumption which is not something this feature requires. I'll open a PR to disable this for now and we can refine it in a follow-up.

**Comment by nfmohit** [comment]
> ## ❌ Approval
> While this feature works and satisfies the AC, the implementation introduces a very large increase to Google API consumption which is not something this feature requires. I'll open a PR to disable this for now and we can refine it in a follow-up.

PR to disable the hook #8080 merged.

**Comment by aaemnnosttv** [comment]
Thanks @nfmohit ! I've opened #8081 as a follow-up to address the changes and reintroduce the notification. This can now be closed again.
