### ISSUE TITLE
the idea tab doesn't show my idea in the draft tab if i return to the dashboard page by clicking on the back button.

### ISSUE THREAD

**Issue by simonchampion** [google/site-kit-wp#3860]
## Bug Description

the idea tab doesn't show my idea in the draft tab if i do the following: 1. click on create draft, go to the draft tab, click on view draft for the idea i just clicked on create draft, after getting to the draft compose page hit the back navigation button.  the idea for the draft i was just looking at is missing from the list of drafts and if i click on the new tab, i see it back there.  after refresh, the drafts tab show the idea again.  however, the new tab still shows the drafted ideas even though when i first clicked on the create draft, they disappeared

**Asana** https://app.asana.com/0/1200491083500938/1200760567419961

## Screenshots

https://user-images.githubusercontent.com/73545194/130076030-91783abf-2182-4060-b9e0-f96d7a89987f.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the user goes back to the dashboard pave using the Back button in the browser, the previous state of the Idea Hub widget should remain the same as before leaving the dashboard page.

## Implementation Brief

* This issue is solved by using React Router, which will reliably load the correct tab on page load. See #3886.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* Visit http://sitekit.10uplabs.com/wp-admin/admin.php?page=googlesitekit-dashboard&idea-hub-tab=draft-ideas
* Click on a link to another WordPress dashboard page.
* Click the browser's "Back" button.
* The Draft Ideas tab and content should be active.

## Changelog entry

* Improve Idea Hub tab behaviour when using browser navigation.

**Comment by eugene-manuilov** [comment]
I can't reproduce this issue. @wpdarren can you take a look at it too?

**Comment by wpdarren** [comment]
@eugene-manuilov yes, I was able to recreate this issue.  I followed the steps, here's a screencast.

https://user-images.githubusercontent.com/73545194/130076030-91783abf-2182-4060-b9e0-f96d7a89987f.mp4

**Comment by eugene-manuilov** [comment]
Thanks, @wpdarren. Which browser do you use?

**Comment by wpdarren** [comment]
@eugene-manuilov I used Chrome. Would you like me to try with another browser?

**Comment by eugene-manuilov** [comment]
No, that's fine, just wanted to double-check it.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by tofumatt** [comment]
The React Router PR uses a Memory Router to handle the tabs, because using query params for routing is a bit awkward, but also because we shouldn't allow components like widgets to control the routing on a page.

In this case this might require a new IB, possibly one that _does_ alter the query param of the `idea-hub-tab` when changing tabs.

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@tofumatt I am seeing odd behaviour. As you can see from the screencast.   

I have 1 draft, I then start a new draft, go to the `Drafts` tab, and click on the `View Draft` link and I am taken to the post editor.  I click `Back` on the browser and there's only 1 draft appearing.  

https://user-images.githubusercontent.com/73545194/132886512-cfdf6859-670b-4372-ae81-5d48d258c730.mp4

It's a little inconsistent.  When I had no drafts. I start a new draft, go to the `Drafts` tab, and click on the `View Draft` link, when I click `Back` on the browser it takes me to the `Drafts` tab and the idea is there, but not always. Tried it a few times and on some occasions the `Drafts` tab was empty.

**Comment by tofumatt** [comment]
Looks like another issue here is the drafts cache not being cleared after they're updated, so to fix the issue mentioned above we'll need to do that. I'll address that issue with a follow-up PR.

**Comment by tofumatt** [comment]
Hmm, I explored this further and the cache is actually being cleared appropriately. I think this might be an idiosyncrasy of browser "back button state restoration" behaviour. For me, this happens intermittently.

@wpdarren If you navigate back to the dashboard with links in the menu bar rather than using the back button, does the error ever happen? If you refresh the page after using the back button, does the count update?

**Comment by wpdarren** [comment]
@tofumatt here are my responses to your questions. 

> If you navigate back to the dashboard with links in the menu bar rather than using the back button, does the error ever happen?

 If I use the links in the menu bar, rather than the back button, I am always taken to the `new ideas` tab.  

Which I think is expected. 

> If you refresh the page after using the back button, does the count update? 

No, even refreshing does not update the `Drafts` tab.

I have just run this through on a new site.

- When you only have one draft, this passes every time.  When I click back from the post editor, I am taken to the  `Drafts` tab and the draft idea appears.  On Friday it was a little intermittent. 
- When you have two or more drafts, this fails.  When I click on the back button, I am taken to the `Drafts` tab, but only 1 draft appears rather than two. I refresh the page but still only 1 draft appears.

**Comment by tofumatt** [comment]
> If I use the links in the menu bar, rather than the back button, I am always taken to the `new ideas` tab.

Yes, but when you select the "Drafts" tab, is it populated with the correct number of drafts?

**Comment by tofumatt** [comment]
I tried refreshing and navigating with back buttons and couldn't reproduce this error anymore. 😓 

Can you try with the most recent `develop` and see if this happens? @wpdarren

**Comment by wpdarren** [comment]
@tofumatt it's working for me now too, bit of a head scratcher that. 

### QA Update: ✅ 

When navigating away from `Drafts` on SIte Kit dashboard, by clicking on the `View drafts` link, you are redirected to the post editor. Clicking on the back button on the browser sends you back to the `Drafts` tab and the correct number of drafts appear.
