### ISSUE TITLE
AdSense: Option to restrict Auto Ads to AMP URLs only

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#389]
## Feature Description

Many users who have monetized their sites via AdSense have carefully placed Ads via plugins or manual insertion (ie. they don't use Auto Ads). 

When they adopt AMP or experiment with the AMP plugin Site Kit can a really useful plugin for implementing Auto Ads for AMP. For future releases having the ability to restrict Auto Ads to AMP might be useful. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
This can already be accomplished as of now, using a filter, e.g.:
```php
add_filter( 'googlesitekit_adsense_tag_blocked', '__return_true' );
```

This would block the AdSense tag from being rendered in non-AMP.

Exposing an option for this use-case in the UI is a bit too much for this specific use-case, so we'll close this for now as fixed, since it can be accomplished with a single-line plugin.
