### ISSUE TITLE
Improving Navigating Site Kit Modules on Mobile

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3894]
## Bug Description

This has been bugging me for a while and wanted to create this ticket to gather thoughts.  On mobile, it's quite cumbersome to navigate around the different Site Kit modules. In the screencast you will see that I start on the Site Kit dashboard, scroll down the page to view my data. Then decide to visit the search console page. So, I have to scroll to the top, then click on the WordPress menu icon to then find item.  The WordPress top menu should be sticky on mobile as it is on desktop, but for some reason it's not.  I tested this on my iPhone and also on browser stack for a few mobiles. 

https://user-images.githubusercontent.com/73545194/129769520-a9c7946d-8dfc-4020-981c-f02ae9db2e3f.mp4

Is there anything that we can do to make it a better user experience? 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@wpdarren I think this will be addressed by #3945

**Comment by aaemnnosttv** [comment]
Thanks @wpdarren ! After discussing with the team, we concluded that this will be fixed by the changes coming unified dashboard. The only thing is maybe we'll want to add a link to the settings from the SK header nav (maybe under the user menu since only logged in users can manage settings).

We're going to start on this soon so you shouldn't need to suffer too much longer 😉
