### ISSUE TITLE
Improve User Experience when Site Kit Access is not authorised

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3970]
## Bug Description

Not a bug, but would be good to improve the user experience.  When you set up Site Kit (or add a new module) the Google oAuth page appears. 

Previously, the access options were checked by default (see screenshot). This meant that when the user clicked continue, they automatically gave authorisation.   

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/badc195d-b88d-4c8d-987f-21640691fd10)

With a recent change, the access options are no longer checked by default and it's easy to continue without noticing. When you click continue you are redirected back to the WordPress dashboard with a vague message.

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/11216f7b-9678-40a9-99b1-6ace8e23213b) 

It would be good for the user to be sent back to the Site Kit dashboard for them to re-authorise, but with a more user-friendly message. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The copy for the `access_denied` error code should be updated as follows:
    * Instead of _The Site Kit setup was interrupted because you did not grant the necessary permissions. To fix this, redo the plugin setup._
    * it should be _The Site Kit setup was interrupted because you did not grant the necessary permissions. To use Site Kit, you’ll need to redo the plugin setup – make sure to approve all permissions at the authentication stage._

## Implementation Brief

In `get_authentication_oauth_error_notice` method of `Google\Site_Kit\Core\Authentication\Authentication` class, 

* Deduplicate the `message` concatenation logic inside `$this->credentials->using_proxy()` and its else block by doing the following:
    * Create a new `setup_url` variable outside the condition block. 
    * Conditionally assign either `proxy url` or `splash url` to it using the current conditional blocks. 
    * Move out `message` concatenation logic from the `if-else` block.
* If `$error_code` is `access_denied`, concat `message` with the correct wording from the AC.
* Otherwise, keep the current message - `To fix this, <a href="%s">redo the plugin setup</a>.`.
* In both case, use the `setup_url` as the hyperlink. 

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

**!THIS NEEDS TO BE QA'D ON `main` BRANCH!**

* Connect to sitekit using a fresh google account. 
* While in the auth flow, don't give all the required permission (make sure some of the permissions are unchecked). 
* Continue with the auth flow. 
* You should get the new error message from the AC. 

## Changelog entry

* Update handling of OAuth error with clarified language and the URL used for retry.

**Comment by bethanylang** [comment]
@wpdarren Thanks for creating this issue. We've seen some confusion about this in the forums as well: 

- https://wordpress.org/support/topic/cant-connect-my-google-account-to-sitekit/
- https://wordpress.org/support/topic/unable-to-login-to-sitekit-because-you-did-not-grant-the-necessary-permission/page/2/#post-14781652

**Comment by felixarntz** [comment]
@marrrmarrr @aaemnnosttv I've added ACs with wording here that is entirely based on the other more accurate message we already have when similar errors happen in the Site Kit dashboard. Please review - if it's good to go we can move to IB.

**Comment by aaemnnosttv** [comment]
@kuasha420 I think we can simply update this in `OAuth_Client_Base::get_error_message` – it shouldn't need to be specific to only proxy users.

**Comment by kuasha420** [comment]
@aaemnnosttv noted and I will update the IB accordingly.

**Comment by kuasha420** [comment]
@aaemnnosttv the `OAuth_Client_Base::get_error_message` only provides first part of the message `The Site Kit setup was interrupted because you did not grant the necessary permissions`. the second part, `To fix this, redo the plugin setup.` with the hyperlink comes from `Authentication::get_authentication_oauth_error_notice`. where the second part is appended to `get_error_message`. 

if we add the whole copy to the `get_error_message` for only `access_denied` then wouldn't we have to skip adding the second part to the message on `get_authentication_oauth_error_notice` when error code is `access_denied` ? 

If we want to show the new copy for non-proxy users as well, we can update the copy for `access_denied` in the else block of `get_authentication_oauth_error_notice` as well. Is that something that should work? 

Just to visualize, from my understanding - we are only interested in updating the second part of the copy for `access_denied`:

from:

> To fix this, **redo the plugin setup**.

To:

> To use Site Kit, you’ll need to **redo the plugin setup** – make sure to approve all permissions at the authentication stage.

retaining the hyperlink (to proxy or dashboard) in the bold.

I will await your response before going with either approach. 

Cheers.

**Comment by kuasha420** [comment]
@aaemnnosttv how about something like this? 

```php
$setup_url = '';

if ( $this->credentials->using_proxy() ) {
	$setup_url = esc_url( $auth_client->get_proxy_setup_url( $access_code ) );
	$this->user_options->delete( OAuth_Client::OPTION_PROXY_ACCESS_CODE );
} else {
	$setup_url = esc_url( $this->context->admin_url( 'splash' ) );
}

if ( 'access_denied' == $error_code ) {
	$message .= ' ' . sprintf(
		/* translators: %s: setup screen URL */
		__( 'To use Site Kit, you’ll need to <a href="%s">redo the plugin setup</a> – make sure to approve all permissions at the authentication stage.', 'google-site-kit' ),
		$setup_url
	);
} else {
	$message .= ' ' . sprintf(
		/* translators: %s: setup screen URL */
		__( 'To fix this, <a href="%s">redo the plugin setup</a>.', 'google-site-kit' ),
		$setup_url
	);
}
```
I have updated the IB accordingly but I found it hard to describe. :D So, leaving the code here as well. 

Cheers.

**Comment by wpdarren** [comment]
### QA Update: ❌ 

Brand new Jurassic.ninja site with new Google account.  Connected Site Kit / Search console.  When the oAuth page appears, the checkboxes for permissions are left unchecked.  I click on the continue button and redirected to the WordPress dashboard. The same error appears though. I am on the `main` branch.

I was expecting the message to say `The Site Kit setup was interrupted because you did not grant the necessary permissions. To use Site Kit, you’ll need to redo the plugin setup – make sure to approve all permissions at the authentication stage.` as per the AC. 

![image](https://user-images.githubusercontent.com/73545194/137941745-79575af8-383e-4a64-94aa-cd13c5772c52.png)
