### ISSUE TITLE
Fix font problems in Idea Hub widget

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4012]
## Bug Description

There are two problems with the title of the Idea Hub widget, one pointed out in https://github.com/google/site-kit-wp/issues/3810#issuecomment-916170914. In addition, the title font here is `Google Sans`, which was like that in the original Figma file, but this should actually use `Roboto` like we do elsewhere.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Both the Idea Hub widget title and the experimental label (in general, not only for the Idea Hub widget) should use our regular Roboto font instead of Google Sans.
* When the experimental label breaks into a new line, it shouldn't appear as if it was indented.

## Implementation Brief

* Inside `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`:
  *  Add the class `.googlesitekit-subheading-1` to the `h3.googlesitekit-idea-hub__title`. This will change the font-family to Roboto.
  * Wrap the text inside `h3.googlesitekit-idea-hub__title` in a `<span>`, with a className such as `.googlesitekit-idea-hub__title-text`.
  * In other words the `h3` should now have two children: the new `span` and the `<Badge>`.

Inside `assets/sass/components/global/_googlesitekit-badge.scss`:
* Remove the margin from `.googlesitekit-badge`. This margin is the reason for the indentation.
 
Inside `assets/sass/components/idea-hub/_googlesitekit-idea-hub-dashboard-ideas-widget.scss`:
* Increase the `line-height` of `.googlesitekit-idea-hub__title` to `1.5`. This will create a bit more space between the lines when the badge wraps.
* Create a new rule for the new `span.googlesitekit-idea-hub__title-text`, and give it a `padding-right` of `12px`. This will create the space that the margin on the badge provided, but will not indent the badge when it wraps.

### Test Coverage

* No new tests required.

### Visual Regression Changes

* Images dealing with the Idea Hub dashboard widget might need updating.

## QA Brief

* Verify that the ACs above have been met

## Changelog entry

* Fix font problems in the Idea Hub widget.

**Comment by eugene-manuilov** [comment]
> Using createInterpolateElement, wrap the text inside h3.googlesitekit-idea-hub__title in a <span>, with a className such as .googlesitekit-idea-hub__title-text.

@johnPhillips we don't need to use the `createInterpolateElement` function here. Nothing blocks us from wrapping the translated text directly:

```diff
<h3 className="googlesitekit-idea-hub__title">
-	{ __(
+	<span>{ __(
		'Ideas to write about, from actual questions people asked on Search',
		'google-site-kit'
-	) }
+	) }</span>

	<Badge
		label={ __( 'Experimental', 'google-site-kit' ) }
	/>
</h3>
```

**Comment by johnPhillips** [comment]
Thanks @eugene-manuilov - IB amended.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@johnPhillips unfortunately, there's one place where the experimental label font is still Google Sans.  When you have connected Idea hub, go to the settings, and you will see the label as per screenshot.  

![image](https://user-images.githubusercontent.com/73545194/133443784-0afd3eb9-9fed-495b-ab13-dcc6d4784119.png)

**Verified:**

- Both the Idea Hub widget title and the experimental label should use our regular Roboto font instead of Google Sans. -- [Screenshot 1](https://user-images.githubusercontent.com/73545194/133444324-c855346e-3036-401d-bff7-771ea12a861d.png) - [Screenshot 2](https://user-images.githubusercontent.com/73545194/133444350-50ba5b85-52f2-417d-8b72-7eb0cf147a2e.png)

- When the experimental label breaks into a new line, it shouldn't appear as if it was indented. - [Screenshot](https://user-images.githubusercontent.com/73545194/133444305-d051336f-50d2-45ab-bd96-b3b68a5171a3.png)

**Comment by johnPhillips** [comment]
@felixarntz Just to check before I address the QA feedback: I was operating under the assumption that this issue was about the dashboard widget only? 
Happy to change the `Badge` to Roboto on the settings page as well, just let me know.
CC @wpdarren

**Comment by johnPhillips** [comment]
@felixarntz disregard, sorry. It's in the ACs 🤦

**Comment by aaemnnosttv** [comment]
Ready for another pass @wpdarren 👍

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Both the Idea Hub widget title and the experimental label should use our regular Roboto font instead of Google Sans. -- [Screenshot 1](https://user-images.githubusercontent.com/73545194/133444324-c855346e-3036-401d-bff7-771ea12a861d.png) - [Screenshot 2](https://user-images.githubusercontent.com/73545194/133444350-50ba5b85-52f2-417d-8b72-7eb0cf147a2e.png)

- When the experimental label breaks into a new line, it shouldn't appear as if it was indented. - [Screenshot](https://user-images.githubusercontent.com/73545194/133444305-d051336f-50d2-45ab-bd96-b3b68a5171a3.png)

- The issue reported [here](https://github.com/google/site-kit-wp/issues/4012#issuecomment-920031326) is fixed.

![image](https://user-images.githubusercontent.com/73545194/134010380-89ec5cef-7035-488a-98cc-e368d2a13440.png)
