### ISSUE TITLE
Create `useInViewSelect` hook

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4096]
## Feature Description

We should add a new hook named `useInViewSelect` that triggers a `useSelect` only when the nearest element in an "In-View Context Provider" (likely a `WidgetAreaRenderer`) is on-screen.

For more context refer to the section ["Lazy-load rendering of widget contexts/areas not in view" in the design doc](https://docs.google.com/document/d/1StGx76XXisE9MfwM1916D9fn7-H9BRiRgizRejTsecI/edit?pli=1#).

This should rely on the `useInView` hook created in #4120, specifically using `useInView( { resetWhenOffScreen: false } )`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a `useInViewSelect` hook created in `assets/js/hooks/useInViewSelect.js`.
    * This component should have the exact same signature as WordPress Data's/[Site Kit Data's `useSelect` hook](https://github.com/google/site-kit-wp/blob/6101771d0653fec3db89876eecc9013ee3e5f1f7/assets/js/googlesitekit/data/index.js#L57).
    * This hook should use the value of the `useInView( { resetWhenOffScreen: false } )` hook to either:
        * Pass the arguments to `useInViewSelect(...args)` through to `useSelect(...args)` (if `useInView()` is `true`)
        * Pass `() => undefined` to the `useSelect` hook if `useInView()` is `false`
* The WP dashboard widget should use the new `useInViewSelect` hook from #4096 for all of its API-based selector calls, replacing `useSelect` for those.
* The result should be that these API requests are only made when the WP dashboard widget is in or close to the viewport. The best way to test it is to hide the widget entirely via screen options. In that case, no API requests should be made.
    * When testing, please ensure to always clear your browser cache, since API requests are only made when nothing is cached yet.

## Implementation Brief

**`useInViewSelect( mapSelect, deps )`**

* Create hook in path referenced in AC
* Should use the new `useInView` introduced in #4120 (not to be confused with the current/old hook from `react-intersection-observer` which should be removed now) which will return a boolean based on the context provider's element (the widget area) is in view
* The given `mapSelect` function should be wrapped with `useCallback` using the given `deps` since we can't change the length of `deps` passed to `useSelect` which is essentially [used in the same way](https://github.com/WordPress/gutenberg/blob/3e867dd7c6560e4b2cb9a59cc02856e055be6142/packages/data/src/components/use-select/index.js#L78), we just do it ahead of time here
* Returns `useSelect( mapSelect )` (note no deps passed)
    - If `inView` returns `true`, pass the given `func` as `mapSelect` with the given `deps`
    - If `inView` returns `false`, pass a function that always returns `undefined` (this should be defined as a constant rather than an a new function every time to avoid triggering the select unnecessarily)

**WP Dashboard**

* Update `WPDashboardApp` to work similar to the changes in `WidgetAreaRenderer` made in #4120, essentially using `useIntersection`, and wrapping the WP dashboard widget with an `InViewProvider` and setting the `ref` on the `div.googlesitekit-wp-dashboard`
* Update `useSelect` hooks in `WPDashboardWidgets` to use `useInViewSelect` instead
    - Add a condition to return `null` if selected values return `undefined` to prevent nested components from rendering
    - Ensure widget selectors/resolvers only run when widget is in view (see #4001)

### Test Coverage

* Add Jest unit tests for `useInViewSelect`

## QA Brief

* Open the developer console in your browser and observe the network requests (specifically XHR/Fetch requests, probably in the "Network" tab). Ensure Analytics is connected.
* Visit the WordPress Dashboard (eg `/wp-admin` on a site that has Site Kit setup
* Note that no requests to Site Kit's REST API routes (eg. matching `/google-site-kit/v1/` are made when at the top of the page
* Scroll down to the bottom of the page
* Note the widgets for Site Kit's box start to show a loading/preview block, then load in their contents. There should also now be XHR/Fetch requests for `/google-site-kit/v1/`.

## Changelog entry

* Add a new `useInViewSelect` hook that allows to call a specific selector only when in view.

**Comment by felixarntz** [comment]
@tofumatt Maybe a good idea to actually test-drive this while implementing (rather than just implementing without using it anywhere initially) would be the WP dashboard widget - see https://github.com/google/site-kit-wp/issues/4001#issuecomment-923421368. I wonder if we should just merge these two tickets.

The main load is really implementing this hook, using it in WP dashboard widget would just be a matter of replacing `useSelect`s, and by doing that here we would be able to know that it actually works.

**Comment by tofumatt** [comment]
Fair enough, we can test-drive it there for sure. I'd be happy to include replacing the usage inside the WP Dashboard as part of this issue though 👍🏻

**Comment by felixarntz** [comment]
@tofumatt Let's do that. Once that's part of the ACs here, you can close #4001 with a reference to here. We should then explicitly include that bit in the changelog here as well, maybe even change the issue title to "Create useInViewSelect hook and use it in WP dashboard widget".

**Comment by aaemnnosttv** [comment]
@tofumatt I think we need to update the ACs here which don't include the relevant changes to @felixarntz 's https://github.com/google/site-kit-wp/issues/4096#issuecomment-926885002 above (I've included in the IB though).

> The hook should return either `true` or `false`—`false` if the parent component/context has NEVER been on-screen, but `true` as soon as it has been visible even once.
> * If the component appears on-screen, then is scrolled out-of-screen, the `useInView` hook should still `return true`.

I don't recall why we wanted this but I think we should avoid introducing it as it makes things quite a bit more complicated. The part I remember is that we needed a reset to be avoid the mass select that would be triggered on the dashboard (if everything had been in view once) when changing the date range. However, if we leave it as-is and don't implement in-view means "was ever in view", then this is no longer a concern because any `useInViewSelect` uses which were not in view would not trigger selects again. These would likely be back in their loading state though which shouldn't really matter if they're out of view as long as it doesn't result in a layout shift. As soon as they came back into view, they should of course render as before, or load/request new data if needed.

I've added the current IB without this which seems like a good place to start. If needed, I suggest we explore enhancing the behavior in a follow-up issue.

Back to @tofumatt for revising the ACs but LMKWYK

**Comment by felixarntz** [comment]
Per https://github.com/google/site-kit-wp/issues/4096#issuecomment-924477283, I've updated the ACs here to also encompass what was previously the ACs of #4001. The IB already accounts for that, so execution here can proceed as is.

**Comment by felixarntz** [comment]
## Approval ❌ 

@eugene-manuilov Per what we discussed yesterday, the implementation in #4347 isn't really accurate. It changes a couple of `useSelect` to `useInViewSelect` that don't trigger API calls, while it doesn't actually change the `useSelect` that _do_ trigger API calls. Specifically, the `WPDashboardWidgets` shouldn't need to be modified in this issue at all, but the sub-components (which are the ones triggering the API calls) like `WPDashboardClicks`, `WPDashboardImpressions` etc. should.

cc @tofumatt @aaemnnosttv

**Comment by aaemnnosttv** [comment]
@felixarntz back to you for another pass 👍

**Comment by felixarntz** [comment]
## Approval ❌ 

@tofumatt @aaemnnosttv The fix PR is mostly good, but one API request is still being made from the WP dashboard widget even when it is hidden, likely because the `isGatheringData` call in `WPDashboardPopularPages` is still using `useSelect`.

**Comment by aaemnnosttv** [comment]
@felixarntz agh, I must have missed that in my testing because Analytics wasn't connected. Submitting a PR to fix it now 👍

**Comment by felixarntz** [comment]
## Approval ✅
