### ISSUE TITLE
Ad blocker detection is not working when using uBlock Origin

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#4140]
## Bug Description

When using uBlock Origin on either Firefox or Chrome, Site Kit's adblock detection is not working. 

## Steps to reproduce

1. Install uBlock Origins on Firefox or Chrome and make sure it is enabled for the test site.
2. Make sure AdSense Module is not active.
3. See that AdSense Module is offered as an option for activation on Connect More Module or Dashboard. 

## Screenshots

![Screenshot_20210928_045505](https://user-images.githubusercontent.com/6187401/134996262-e91d9e31-169d-42dd-9dc7-3884bae9d9a1.png)

![Screenshot_20210928_045608](https://user-images.githubusercontent.com/6187401/134996284-1c172620-86ce-4a29-92b7-9e4586cbe4fd.png)

## Additional Context

 - PHP Version: 7.4.23
 - OS: Arch Linux, macOS
 - Browser: Firefox, Chrome
 - Plugin Version: 1.42.0
 - Device: Desktop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit's ad blocker detection should work as expected with [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en).

## Implementation Brief
* Using `assets/js/modules/adsense/datastore/adblocker.js`, instead of making a request to `/favicon.ico`, make a request to `https://pagead2.googlesyndication.com/` without any parameters.

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by asvinb** [comment]
@aaemnnosttv Was the reason we were requesting `/favicon.ico` was to prevent an external request? I tested and even with the params `google-site-kit=/adsense/pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` appended to `/favicon.ico`, the ad blockers do not detect anything. I've wrote the IB where I suggest we make a request to `https://pagead2.googlesyndication.com/` where the ad blockers I tested, AdBlocker and UBlock Origin, prevented the URL to be loaded.

**Comment by aaemnnosttv** [comment]
> Was the reason we were requesting `/favicon.ico` was to prevent an external request? I tested and even with the params `google-site-kit=/adsense/pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` appended to `/favicon.ico`, the ad blockers do not detect anything.

@asvinb yes, because the request will fail due to CORS. The problem with changing the request to be made to `https://pagead2.googlesyndication.com/` instead is that while it will be blocked when uBlock Origin is enabled, it will also fail when no adblocker is active due to CORS:

> Access to fetch at 'https://pagead2.googlesyndication.com/' from origin 'http://sitekit.10uplabs.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Modifying the request mode to use `no-cors` prevents it from failing but it's also no longer blocked by the adblocker either. Same for using the full URL to `adsbygoogle.js`.

Part of the problem I'm seeing is due to the way uBlock Origin works, which is that it doesn't always block the request. Instead, it intercepts the request and serves an internal redirect which resolves to a 200 response to a different script, which is quite tricky 😄 

![image](https://user-images.githubusercontent.com/1621608/140314101-e107a9ff-0702-4608-99e3-07ff6965df6d.png)
![image](https://user-images.githubusercontent.com/1621608/140314119-0d1f54f5-05d3-4d47-9654-f34633640bb2.png)
![image](https://user-images.githubusercontent.com/1621608/140314137-7b9fda5c-69e9-47dc-a211-386c1276c2e0.png)
https://github.com/gorhill/uBlock/blob/25823f0819286e93c6638e6777f43a43e793d11a/src/web_accessible_resources/googlesyndication_adsbygoogle.js

I'm not sure if we can accurately detect if an adblocker is used or not, but if it isn't actually _blocking_ the request, I don't think it's really a problem. My understanding of this detection is really about avoiding our AdSense module REST API requests from being blocked by an overly aggressive adblocker rather than needing generally detect all adblockers. cc: @felixarntz

**Comment by felixarntz** [comment]
@aaemnnosttv 
> I'm not sure if we can accurately detect if an adblocker is used or not, but if it isn't actually _blocking_ the request, I don't think it's really a problem. My understanding of this detection is really about avoiding our AdSense module REST API requests from being blocked by an overly aggressive adblocker rather than needing generally detect all adblockers.

+1 to that. We only need to alert the user about an adblocker if that adblocker is causing problems with our AdSense module, particularly its REST routes etc. If the adblocker (rightfully so) lets those requests go through, we don't really care I guess.

I'm going to close this as `invalid` for now. cc @bethanylang @jamesozzie for visibility
