### ISSUE TITLE
Idea Hub: Introduce feedback form when a new idea is dismissed

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4277]
## Bug Description

In the Figma file, there's a mini feedback form that displays once an idea has been dismissed, this is missing from Idea Hub module.  The API doesn't currently support this so it was delayed from the initial launch.  Creating this ticket so that this functionality is picked up for a future release. 

https://app.asana.com/0/1200491083500938/1200757690664686

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
This is probably worth checking in with the Idea Hub API team about—I've added it to the Open Bucket call to discuss internally 🙂

**Comment by tofumatt** [comment]
For some extra context after speaking with @marrrmarrr: this is very likely still a planned feature _but_ is likely at least a year away while the Idea Hub team focuses on internal API improvements and other features.

Let's leave this in stalled because this is still planned and a desired feature.

**But it's worth noting this should likely not be re-raised with the Idea Hub team until Q3 2023.**

**Comment by aaemnnosttv** [comment]
Closing this one in favor of #6235
