### ISSUE TITLE
Tag Manager setup/settings blocks user while container data is loading without loading indicator

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4311]
## Bug Description

It takes a long time (10 seconds plus) for Site Kit to recognize a non Site Kit placed GTM snippet and populate the account and container fields with that manually inserted information. While this may be in relation to a lookup of all Tag Manager accounts during the wait users there are a couple of issues:
1. Users may be uncertain on how to proceed, do they wait or do they exit (there is no loading indicator and the "Confirm and Continue" buttons are greyed out
2. The pre-populated GTM account and container are not necessarily the correct GTM account and container (_this should be addressed once #4209 is has been resolved_)
3. It only changes to the correct pre-populate data after the wait/lookup
 
https://recordit.co/IW511jun1l

An improvement for this would be for the field to be not pre-populated and ideally a loading indicator would appear. 

## Steps to reproduce

1. Insert GTM manually with the code snippet in the head and body of your site  
2. Connect GTM within Site Kit. It takes some time for GTM to populate with the correct GTM already connected, in the meantime showing possibly incorrect data

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The **primary** loading indicator shown while loading Tag Manager setup or settings-edit views should _continue to be shown_ under the following conditions:
    - The presence of an existing tag is not yet finished resolving
    - An existing tag is present and its permissions check has not finished resolving
* A **new** loading indicator should be shown to the right of the container selects in the Tag Manager setup and settings views when the live container version is loading
    * It should use the same type of mini progress bar that is used for the compatibility checks which happen on the splash screen, i.e. next to the disabled CTA button. The small text above it should say:  
        > Checking tags
    * Only a single loading indicator should be shown for this which should show regardless of which container(s) the version data is being fetched for

## Implementation Brief

* In `assets/js/modules/tagmanager/components/setup/SetupMain.js`: and `assets/js/modules/tagmanager/components/settings/SettingsEdit.js` components:
    * Continue showing the progress bar when `hasExistingTag` and `hasExistingTagPermision` is undetermined by expanding the logic that sets the `ProgressBar` as `viewComponent`. ie. `if ( ... || hasExistingTag === undefined || hasExistingTagPermission === undefined ) { ...`
* In `assets/js/modules/tagmanager/components/setup/SetupForm.js` and `assets/js/modules/tagmanager/components/settings/SettingsForm.js`:
    * Get the `accountID`, `internalContainerID` and `internalAMPContainerID` using the `getAccountID`, `getInternalContainerID` and `getInternalAMPContainerID` selectors from the `MODULES_TAGMANAGER` store.
    * Define `isResolvingWebGetLiveContainerVersion` and `isResolvingAMPGetLiveContainerVersion` using the `isResolving` with `getLiveContainerVersion` as the first argument and array of `accountID` and `internalContainerID` / `internalAMPContainerID` as the second argument of the `isResolving` selectors respectively. ie.

````js
const isResolvingWebGetLiveContainerVersion = useSelect( ( select ) =>
  select( MODULES_TAGMANAGER ).isResolving( 'getLiveContainerVersion', [
    accountID,
    internalContainerID,
  ] )
);
```` 

* Conditionally render a `ProgressBar` inside the `googlesitekit-setup-module__inputs` div either of the `isResolvingWebGetLiveContainerVersion` or `isResolvingAMPGetLiveContainerVersion` is `true`.
        * It should be something like this: https://github.com/google/site-kit-wp/blob/f8b423e14e8e0878db86e4530b11cb8d414d6c1a/assets/js/components/setup/CompatibilityChecks/index.js#L84-L89
    * Use the text from the AC as the label. 

### Test Coverage

* No changes needed.

## QA Brief

**QA:Eng**
- Create a Google Tag Manager account manually
- Open `wp-content/themes/twentytwentyone/header.php` file. Make sure you're on the `Twenty Twenty One` theme. If not add the scripts respectively.
- Copy the scripts and add it to the `<head>` and `<body>` tags respectively
- Go to the Site Kit settings page and connect/setup Tag Manager
- Verify the new loading animation with the text `Checking tags…` along with the small `ProgressBar` while the container is loading data. Please refer to the screenshot attached in the PR description.
- Once connected, go the settings connected services and edit the  Tag Manager and refresh the page
- Verify the new loading animation with the text `Checking tags…` along with the small `ProgressBar` while the container is loading data. (The loader might be visible only on the first time in the setting page)
- Verify the same loading behaviour without an existing tag

## Changelog entry

* Update Tag Manager setup and settings edit views with loading indicator while tags are being checked.

**Comment by aaemnnosttv** [comment]
@jamesozzie I've noticed this one as well although I've never seen it take longer than a few seconds. I can imagine for some users this could take a bit longer and makes for a confusing experience.

@felixarntz I've added preliminary ACs but let's define how the loading state should look as it's a bit different than other modules where the progress bar would replace the select for example. Here we could maybe add a spinner next to the submit button which is disabled. Alternatively, we could show the mini progress bar with a message similar to the compatibility checks we do during initial set up. Thoughts?

**Comment by felixarntz** [comment]
@aaemnnosttv Using the mini progress bar like we do in the compatibility checks sounds good to me. I've defined this in the ACs. If that looks good to you, let's move this to IB.

**Comment by aaemnnosttv** [comment]
@felixarntz mostly LGTM, my only suggestion would be to maybe make the messaging more generic (like "Checking configuration/containers") or have it without a label (just a progress bar). We can probably start on this and finalize the exact wording later though. I'll add this to the AC so we can move it forward to IB.

**Comment by eugene-manuilov** [comment]
Thanks, @kuasha420, but I think the proposed IB won't work very well. The problem is that `canSubmitChanges` can stay falsy even after successful detection of the existing tag, thus the progress bar will remain if we implement it as defined in IB.

I think what we need to do is to add new actions `startSelectingExistingTagAccount` and `finishSelectingExistingTagAccount` actions to the `tags` datastore that will set `isSelectingExistingTagAccoun` flag in the datastore state. Plus, add a new selector `isSelectingExistingTagAccount` that will return that flag which we can use in the `SetupForm` component to display the progress bar. Finally, we will need to update the `useExistingTagEffect` hook to call the aforementioned actions before and after calling `selectAccount` and `selectContainerByID` actions: https://github.com/google/site-kit-wp/blob/33c55b834369bcff465e6cdf76d34e21a4d6e653/assets/js/modules/tagmanager/hooks/useExistingTagEffect.js#L57-L60

> In assets/js/modules/tagmanager/components/common/ContainerSelect.js:

Also, I think we don't need to make changes in the `ContainerSelect` component because it will affect both settings and setup forms. What we need to do is to update the `SettingsForm` component to display the progress bar with the appropriate label instead of `WebContainerSelect` and `AMPContainerSelect` components when the `isSelectingExistingTagAccount` selector returns `true`.

Probably would be better to create a separate component for the progress bar and use it in both forms instead of repeating the logic in both places.

**Comment by eugene-manuilov** [comment]
Also, @kuasha420, please, don't forget to enter the `Test Coverage` section even if there is nothing to do.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov @kuasha420 there seems to be some confusion around what the ACs call for here which is leading the IB a bit off target.

The AC describes an additional progress bar which is to be rendered adjacent to the submit button that is shown while live container versions are being fetched/resolved (similar to what we do in the activation notice or compatibility checks). While this issue was raised around existing tags, it isn't related to that as any existing tag is already known before the fields are rendered; the only delay (as shown in James' screencast above) is from the live container version data we fetch any time the selected container(s) change (although only if Analytics is active I believe). This causes the submit button to be disabled from this part of the `validateCanSubmitChanges` function

https://github.com/google/site-kit-wp/blob/ebc8b605ec7618fac47453a368036110b615f5d8/assets/js/modules/tagmanager/datastore/settings.js#L254-L268

Using the core `isResolving` selector for the `getLiveContainerVersion` resolver (with some additional logic to account for one or both containers depending on AMP) would probably be sufficient to determine if the progress bar should be shown or not. There might be a bit more to it but that should cover the majority of what's needed 👍 

I'll revise the wording of the issue to be less about existing tags to avoid any confusion in the future.

**Comment by aaemnnosttv** [comment]
Actually, part of the delay there is likely from waiting for tag permission to be resolved (not the existing tag itself). I think this detail was missed when @felixarntz and I initially reviewed it and decided on the ACs.

The live container version bit is still relevant but doesn't seem to be the case in the screencast shown here as that would be the case if account and container were selected and it was still disabled, while here it is disabled until the container is selected.

@felixarntz thoughts on changes to the ACs here? I think we could update it to simply keep the container's progress bar spinning while tag permissions were being resolved? i.e. adding an another selector for `hasFinishedResolution` for `getTagPermission( containerID )`?
https://github.com/google/site-kit-wp/blob/e3d4227f6b04c9e33bac5baa63a8940630fa4157/assets/js/modules/tagmanager/components/common/ContainerSelect.js#L64-L65

**Comment by felixarntz** [comment]
@aaemnnosttv 
> thoughts on changes to the ACs here? I think we could update it to simply keep the container's progress bar spinning while tag permissions were being resolved? i.e. adding an another selector for `hasFinishedResolution` for `getTagPermission( containerID )`?

Sgtm! I've added a note to the ACs.

**Comment by aaemnnosttv** [comment]
@felixarntz just to clarify: if tag permissions are not resolved yet, the `ContainerSelect`'s progress bar would show, but if the live container version was being fetched, only then the separate progress bar would show next to the submit button, correct? The way it's worded now sounds like the latter would be used for both but I don't think we'd want that.

**Comment by kuasha420** [comment]
@aaemnnosttv can we have a call sometimes tomorrow to go over current behavior and expected behavior? I think that would be best course of action.

**Comment by eclarke1** [comment]
@kuasha420 @aaemnnosttv are we able to progress this IB at all please? What do we need to do to get it moving? Thank you.

**Comment by aaemnnosttv** [comment]
@kuasha420 I've updated the ACs to address this (cc @felixarntz). I think this can already move forward with a revised IB, the main difference being that the new loading indicator is only for loading state once the main `viewComponent` is loaded. Existing tag and permissions loading should happen before the initial/primary loading indicator is removed so we just need to tweak some logic there 👍

**Comment by kuasha420** [comment]
Hi @aaemnnosttv ,

The first part of AC is clear. But I have some confusions regarding the second part.

* You have said getting the `liveContainerVersion` using the `isResolving` selector, but I couldn't get it to work in my testing. How to get it and would the approach change based on whether AMP is active? 
* Where do we put the new `ProgressBar` in the Settings Page? Couldn't quite figure it out. 

I have changed the IB partially but it still needs bit more tweaks. Once the above points are clarified, I'll amend the IB and send it for review again.

Cheers.

**Comment by aaemnnosttv** [comment]
> * You have said getting the `liveContainerVersion` using the `isResolving` selector, but I couldn't get it to work in my testing. How to get it and would the approach change based on whether AMP is active?

@kuasha420 you would need to check the status of the `getLiveContainerVersion` selector which as it is the only one that has a resolver. This is specific to a single container (using `accountID` and `internalContainerID`). See the `getAnalyticsPropertyIDs` selector to see the related logic as to which containers are checked, which is essentially the same logic that determines which container selects are shown (web only, amp only, or both).

> * Where do we put the new `ProgressBar` in the Settings Page? Couldn't quite figure it out.

Oops, you're right this will be a problem in the Settings edit view 🤔  Maybe something like below would be good but we'll need to consult with @felixarntz here as we probably want to make the same change in both views.

![image](https://user-images.githubusercontent.com/1621608/146756272-27dfb914-cc2e-40f8-80b1-1dfe7509f7ff.png)

I think this looks okay but not great. Thoughts @felixarntz ?

**Comment by felixarntz** [comment]
@aaemnnosttv Shouldn't the small progress bar display on the right of the dropdown instead? That would be closer to how we have on the splash screen for the compatibility checks and IMO would look better. I think the mock you have above is a bit odd as it makes me think this dropdown is an autocomplete that is loading, but what we're loading here doesn't really affect the content of that dropdown.

Regarding the ACs, should we finalize the copy as "Checking tags"? That would work for me.

**Comment by aaemnnosttv** [comment]
@felixarntz the best placement would be next to the submit button IMO (as with compatibility checks) as it is providing more context as to why the button is disabled. That doesn't work in both places without more substantial changes so I think putting the progress bar next to the selects is the next best place. We should make it clear though that only one progress bar should be added regardless of which containers are fetching versions (rather than one per container). I'll update the ACs.

**Comment by aaemnnosttv** [comment]
@kuasha420 this should be ready for revision now 👍

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by aaemnnosttv** [comment]
@hussain-t regarding the QAB, this issue is not specific to an existing tag case (at least for the "Checking tags" indicator). Tags are checked both for an existing tag but also any time the user chooses a specific container under normal circumstances.

Would you please update the QAB to clarify?

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@hussain-t this is looking good but have an observation when editing tag manager settings. I refresh the page, and do not see the `Checking tags` text along with the small ProgressBar. I know you said that you might only see it the first time, but I've not seen it appear at all.  I've set throttling to slow 3G, but nothing appears.  Any thoughts? 

https://user-images.githubusercontent.com/73545194/148544383-a192cad7-6b87-4e1e-ae65-94e4d871eabd.mp4

**Verified:**

- With GTM code manually added. The new loading animation appears with the text Checking tags, along with the small ProgressBar while the container is loading data. Please refer to the screenshot attached in the PR description.
- With GTM added via Site Kit the same loading behaviour appears without an existing tag. 
- Tested both scenarios on various screen sizes including mobile to make sure there are no styling issues with the animation. 

<details>
 <summary>Screencasts</summary>

https://user-images.githubusercontent.com/73545194/148546999-2c59149d-3696-4393-aa81-1caa47777b70.mp4


https://user-images.githubusercontent.com/73545194/148547059-4bbcccb4-3231-4d27-8ac7-e261d58af734.mp4

</details>

**Comment by hussain-t** [comment]
@wpdarren the `TagCheckProgress` component (i.e. the loading animation) renders only when the container data is loading. Even I tried multiple times and I happened to notice only once. 

Any thoughts or steps to reproduce it in the settings page @aaemnnosttv?

**Comment by aaemnnosttv** [comment]
@wpdarren – in this case, because the container it is checking the tags for is known during the initial load (ie it's initially set via settings), the check may finish before the main loader is done so it appears as though it doesn't happen, but it just starts earlier. This actually only happens if there is no existing tag because it takes extra time to determine the account ID if there is an existing tag, but if settings are saved it's already known.

In this case, you should be able to see it by:
- removing the existing tag
- saving the settings with a different container
- restoring the existing tag
- going back to settings edit

Give that a try and let me know if that does it for you. It's not entirely required that it's always seen in all cases. The important thing here is that the user is not blocked from proceeding (disabled submit button) due to these checks which are in progress which weren't visible before. The submit button can be disabled for various reasons, but this was the only one where everything in the form appeared valid and the submit button could be "stuck" disabled for a second or two without any indication as to why.

**Comment by wpdarren** [comment]
QA Update: ✅ 

**Verified:**

- With GTM code manually added. The new loading animation appears with the text Checking tags, along with the small ProgressBar while the container is loading data. Please refer to the screenshot attached in the PR description.
- With GTM added via Site Kit the same loading behaviour appears without an existing tag. 
- With GTM code manually added. When I go to edit Tag Manager, I can see the text Checking tags, along with the small ProgressBar while the container is loading data
- Tested both scenarios on various screen sizes including mobile to make sure there are no styling issues with the animation. 

<details>
 <summary>Screencasts</summary>

https://user-images.githubusercontent.com/73545194/148546999-2c59149d-3696-4393-aa81-1caa47777b70.mp4


https://user-images.githubusercontent.com/73545194/148547059-4bbcccb4-3231-4d27-8ac7-e261d58af734.mp4

</details>
