### ISSUE TITLE
Revise wording on snippet status when an existing GTM snippet is manually inserted

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4314]
When connecting Tag Manager within Site Kit the plugin automatically populates the Tag Manager fields as it should. The default configuration is that Site Kit does not insert the same snippet. The status within the GTM module appears as "Snippet is not inserted". 

This may result in confusion with users then editing and allowing Site Kit to insert the snippet - which would be a duplicate snippet.

Revise the wording to the below or similar:

- Change the "_Snippet is not inserted_" to "_Snippet is not inserted **by Site Kit**_"
- Change the "_Snippet is inserted_" to "_Snippet is inserted **by Site Kit**_"

**Below: Default configuration with a non SK placed snippet**

![image](https://user-images.githubusercontent.com/41326532/140316178-91d2cb4e-8833-491d-931e-ad5467862cf5.png)

**Below: Editing the Tag Manager module and allowing SK to also insert a snippet **

##![image](https://user-images.githubusercontent.com/41326532/140316156-75fcab31-36fc-4e75-9cb9-3b42235cfac8.png)Steps to reproduce

1. Manually insert a GTM snippet
2. Connect the Tag Manager module with Site Kit - all default settings
3. Revisit the Tag Manager settings. The status is "Snippet is not inserted". This can lead to confusion and result in double placement 

 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Just noting that the "by Site Kit" when displaying the snippet status could also apply to Analytics and AdSense.

**Comment by aaemnnosttv** [comment]
This one looks closely related to my comment on the previous issue https://github.com/google/site-kit-wp/issues/4313#issuecomment-977719342

**Comment by bethanylang** [comment]
Coming back to this as part of reviewing these settings for ETS testing, I agree with the changes that James suggests here.

**Comment by aaemnnosttv** [comment]
Thanks @bethanylang – we probably need to rethink this a bit because the settings view here should be more/less a reflection of the current settings values for the module. We don't currently persist the concept of an existing tag so the [tag placed but not by SK] case needs some thinking. IMO, the view should show Site Kit's snippet status and if we want to also show the status of an existing tag, that should be shown in addition to the other rather than just changing the wording to a separate variant. Then I think we could provide more useful feedback regarding both, rather than trying to use one space for a more complicated composite concept.

I'll raise this again with @marrrmarrr in our next sync 👍

**Comment by aaemnnosttv** [comment]
Closing as this is quite stale but also not specific to GTM.
