### ISSUE TITLE
Create a helper hook to reduce useSelect boilerplate

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#4378]
## Feature Description

At present we have a coding convention to use a single `useSelect` call per selector. This means we have a lot of code that looks like this:

```js
const clientID = useSelect( ( select ) =>
	select( MODULES_ADSENSE ).getClientID()
);
```

For an extreme example, see [`assets/js/modules/adsense/components/setup/SetupMain.js`](https://github.com/google/site-kit-wp/blob/b6da750ce6c41ba2b3740874192bdafa82573dca/assets/js/modules/adsense/components/setup/SetupMain.js) which has twenty occurrences of `useSelect` at the time of writing.

This issue proposes a helper hook, something like the following, in order to cut down on the repetition and improve readability, especially in places where there are numerous calls to `useSelect`.

```js
const clientID = useSelectFrom(  MODULES_ADSENSE ).getClientID();
```

An alternative name could be `useSingleSelect`... Or, something else! :)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks @techanvil – what did you have in mind? I'm not sure the suggested API would work because the selector needs to be called within the `mapSelect` function passed to `useSelect` but I don't think this would be possible as suggested as `useSelectFrom` wouldn't have the context of which selector is being called.

**Comment by techanvil** [comment]
@aaemnnosttv, I was just thinking of something simple like this, to accommodate the common simple use case of a single selector without login in the `mapSelect` function:

```js
function useSelectFrom( storeName ) {
	return useSelect( ( select ) => select( storeName ) );
}

//

const siteURL = useSelectFrom( CORE_SITE ).getReferenceSiteURL();
```

**Comment by aaemnnosttv** [comment]
@techanvil the problem with that I think is that the hook wouldn't trigger a re-render when the result of the `mapSelect` changes. See https://github.com/WordPress/gutenberg/blob/3e867dd7c6560e4b2cb9a59cc02856e055be6142/packages/data/src/components/use-select/index.js#L131-L138

You can return store selectors from a `useSelect` but those are only intended for use in event listener.

**Comment by techanvil** [comment]
@aaemnnosttv thanks for pointing that out. Sorry for clearly not reading the docs on this, as that would have given me a hint:

> Don’t use useSelect this way when calling the selectors in the render
function because your component won’t re-render on a data change.

https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#useselect

FWIW, I have confirmed the fact that it doesn't re-render with this approach, with a codesandbox (forked from one of yours, which I fortuitously found when I googled "wordpress data codesandbox" :) - https://codesandbox.io/s/wp-data-demo-forked-u5p5m. I did briefly have an idea that we could do something with the Proxy API but I don't see it working within the constraints of React hooks...

**Comment by tofumatt** [comment]
It's worth noting as well, that placing the `select()` call inside the `mapSelect` functions allows us to conditionally call selectors that have associated resolvers only when appropriate. This is how `useInViewSelect` works, but we also do it elsewhere—only calling a selector when we have enough data to call it or when the right conditions are met.

Since we can't conditionally call hooks, we would need to be mindful about using this hook when we want to call selectors conditionally, which is an awkward developer experience in a way too 😅

I think you're right that this isn't possible without a lot of effort, if at all, so I think we should close the issue for now so it isn't lost in the shuffle. 🙂
