### ISSUE TITLE
Improve UX on the Idea Hub Setup & PageSpeed CTA to jump to the widget

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4410]
## Bug Description

While testing #4275 I noticed an UX issue, which I understand is out of scope. When you connect Idea Hub or PageSpeed Insights, you are redirected to the dashboard. The `Congrats on completing the setup for Idea Hub!` notification appears.  When you click on the `Jump directly to Idea Hub to see topic suggestions for your site` link you are sent to the Idea hub widget but it is not at the top. The user still needs to scroll up slightly to see the header and tabs. 

Note: This is an issue for the current and unified dashboard.

https://images.zenhubusercontent.com/191387173/b7ceb82b-61b3-4f19-9649-dcbadcfe69d8/ideahub.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When clicking the jump link in the success banner notification after setting up PageSpeed Insights or Idea Hub (which should take you to the respective widget), it should be ensured that the viewport actually ends up in a way that the respective widget's top is visible. Right now, because of default browser anchor link behavior, the respective widget is partly hidden behind the sticky header.
    * Potentially this can reuse the approach from the pill navigation in the unified dashboard.
    * If straightforward (via the above), adding the visual scroll effect (instead of jumping) would also be nice to have here. That's not a must-have requirement though.
* This should be fixed for both the unified dashboard and the current dashboard (i.e. with and without `unifiedDashboard` feature enabled).

## Implementation Brief
* Using `assets/js/components/notifications/BannerNotification.js`,
	* Add a new function which will be passed as value to the `onClick` prop of `Link` that wraps `anchorLinkLabel`. The function should do the following:
		* If `anchorLink` contains a hash and is not a valid URL, scroll the user to the appropriate section identified by the hash (if the section exists) using the same logic as in `assets/js/components/DashboardNavigation.js`, i.e using `window.scrollTo` taking the header, sub header height in consideration.
* As part of this issue, maybe it'll be best if we can extract `getContextScrollTop` from `assets/js/components/DashboardNavigation.js` to `assets/js/util/scroll.js` and make it more generic so that it works with classes and ids as well.
	* Replace `getElementById` by `querySelector` and update the codebase to cater for this change, i.e adding a `#` if we are targetting an element with an id.

### Test Coverage
* No new tests to be added.

## QA Brief

* Turn ON Idea Hub feature flag for all tests below. Test the below links on different viewports. 
* Turn OFF Unified Dashboard feature flag.
  1. Test AC of #4380 - Go to Settings -> Connected Services -> PageSpeed Insights -> Click on `Visit the Dashboard`. The page should scroll to the top of `Page Speed and Experience` Header.
  2. Test AC of this issue - Deactivate and then activate PageSpeed insights in settings and click on the `Jump to the bottom of the dashboard to see how fast your home page is` in the Success Banner Notification. The page should scroll to the top of `Page Speed and Experience` Header.
  3. Activate Idea hub in settings and click on the `Jump directly to Idea Hub to see topic suggestions for your site` in the Success Banner Notification. The page should scroll to the `Ideas to write about...` header.

* Turn ON Unified Dashboard feature flag.
  1. Repeat above three tests but this time, check that the links go to the top of the new `Speed` widget (for PSI links) and still go to the `Ideas to write about...` header for the Idea Hub banner link. 
  2. Also test that clicking on the chips in the new dashboard navigation make the page scroll to the correct headers as before.

## Changelog entry

* Update jump links in the setup success banner notification to scroll to the appropriate location instead of jumping to it using the hash.

**Comment by ivankruchkoff** [comment]
More detail in https://github.com/google/site-kit-wp/issues/4275#issuecomment-979587337 the sitekit header and #wpadminbar cover the top of the element making it appear like we've scrolled too far down.

Issue exists for both idea hub module and page speed insights (only visible when we've loaded the full module content).

**Comment by eugene-manuilov** [comment]
@asvinb I think we can implement the logic to scroll to an anchor within the `BannerNotification` component itself without exposing the `onAnchorLinkClick` property. The idea is very simple, if we have an anchor in the banner, then the `BannerNotification` component scrolls to it using the selector provided in the `anchorLInk` property. In this case, the solution will be more universal and we won't need to make changes in the `SetupSuccessBannerNotification` component. What do you think?

**Comment by asvinb** [comment]
> @asvinb I think we can implement the logic to scroll to an anchor within the `BannerNotification` component itself without exposing the `onAnchorLinkClick` property. The idea is very simple, if we have an anchor in the banner, then the `BannerNotification` component scrolls to it using the selector provided in the `anchorLInk` property. In this case, the solution will be more universal and we won't need to make changes in the `SetupSuccessBannerNotification` component. What do you think?

@eugene-manuilov I thought about that as well but eventually decided to go with the current approach to have more control and flexibility. But happy to update the IB to make things simpler 👍

**Comment by eugene-manuilov** [comment]
Yes, let's do it in the `BannerNotification` component. It will be a more concise change 😄. Thanks, @asvinb.

**Comment by asvinb** [comment]
Thanks @eugene-manuilov , IB ready for you to review again.

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb. IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@jimmymadon I'm seeing some odd behaviour with this on `develop` branch. 

1. I go to the Site Kit Settings > PageSpeed and click on the `Visit the dashboard` link.  This with Unified Dashboard disabled and Idea Hub enabled but not connected. As you can see from my screencast the link doesn't jump to the PSI widget.    I'm on Chrome on desktop.

https://user-images.githubusercontent.com/73545194/146801080-e8441bb7-bd63-4c7f-b10e-febd2d98c859.mp4

2. This is also with Unified Dashboard disabled and Idea Hub enabled but not connected. I disconnect PageSpeed, and then reconnect.  I am redirected to the dashboard and I click on the link. It initially takes me close to the PSI widget, but then jumps up to the content area.  You can see the behaviour on the screencast.  

https://user-images.githubusercontent.com/73545194/146801593-adaa20c3-dec0-4b65-a55d-c44dc7fdfa02.mp4

3. For both of the tests above, but with Unified Dashboard enabled. When the links are clicked it scrolls down to the PSI title but then a second later, jumps up to the content area as the PSI widget is loading. I tested this with Idea Hub connected and unconnected and the same issue occurred.

The 3rd test for Idea hub works fine for current and unified dashboard. It just seems to be an issue for PSI. 

**Verified:**

- Activated Idea hub in settings and clicked on the Jump directly to Idea Hub to see topic suggestions for the site in the Success Banner Notification. The page scrolled to the Ideas to write about... header. This was tested with Unified Dashboard enabled and disabled. Looks good.

**Comment by jimmymadon** [comment]
@asvinb @eugene-manuilov The original issues raised here in the Bug Description have been fixed as per the IB. I tested this as per my QA brief without connecting to Analytics. The bug tested by @wpdarren above is with Analytics connected. Since the widgets above PSI change their height post-loading *_after_* the correct scrolling has finished, it appears to *_move_* the corrected scrolled anchor to the wrong place. I have [recorded another example](https://user-images.githubusercontent.com/1721319/147243900-4ec24a9b-b3ac-434a-a8e5-8d966da9c19b.mov) which shows the difference when you click the anchor link before and after everything else has loaded. I am not sure what the correct behaviour/fix should be here - should we move the scroll twice or should we wait for all widgets on the page to load or try something else? This behaviour of widgets resizing themselves after loading is also occurring in a few different places with different combinations of widgets enabled/disabled.

**Comment by eugene-manuilov** [comment]
I am not sure that we can do anything with this because we don't know the height of the upper widgets before they load their data. :thinking:

@felixarntz, can you also check Darren's comment?

**Comment by felixarntz** [comment]
@jimmymadon @eugene-manuilov To be clear, which Analytics widget(s) are we talking about? Is it specifically the one for Popular Pages? Reason I'm asking is that we've been trying to mostly match the vertical space for loading states with the populated widgets, so this shouldn't be happening. But I see how there can definitely be a shift in the Popular Pages widget.

The spacing pretty much matches for the loading state of the Top Keywords widget, which makes sense looking at it, given that it typically only has a single line per row. I think it would be worth refining the loading state for the Popular Pages widget to be closer to the populated state (not 100% match, which is impossible due to the dynamic nature) by increasing the height of the individual gray bars within it. Thoughts?

cc @wpdarren

**Comment by jimmymadon** [comment]
@felixarntz I had another look and it is not only the `Popular Pages` widget. Below are approximate heights of all the widgets before and after their content is loaded. As you mentioned, the `Popular Keywords` widget almost matches (and so does the `Search Console All Traffic` widget. But the rest have considerable differences.
```
Analytics All Traffic: 550px vs 550px
Search Funnel: 532px vs 584px
Search Console Popular Keywords: 590px vs 594px
Analytics overall page metrics: 338px vs 408px
Popular Pages: 662px vs 853px
```

We should be able to easily refine the loading states of every widget other than `Popular Pages`. 

For the `Popular Pages` widget, we can refine the height to always account for 10 pages. We can ensure all page titles and URLs do not wrap to another line. But when the widget does not have data for 10 pages, this will be inaccurate again unless we leave a ridiculous amount of white space.

**Comment by aaemnnosttv** [comment]
@jimmymadon thanks for the information about the sizes of the loading states vs the loaded state. I think this is worth revisiting and adjusting (perhaps even before the launch of the UD) but IMO the problem here is not really solvable by updating the size of the loaders alone because not all widgets have predictable heights as you pointed out. One solution might be to update widgets to always have a predictable/fixed height but this would probably require some substantial review and iteration.

Another solution is one that I envisioned we might need a while back with the introduction of the `useInViewSelect` hook which is to essentially only allow the select to be enabled if the area is in view (as today) but also only if it's context ID matches the hash in the URL. This way, when the page loads and scrolls, it doesn't trigger every selector along the way to the target scroll position (and in turn resulting in a potential layout shift once it loads). This may also be relevant for #4490. This would result in more of a lazy-loaded interface (so more loading states would be seen) but I believe this is the simplest solution for now.

This would also have the added performance benefit due to lazy loaded requests and widget initialization.

The main downside to this approach is that it obviously wouldn't work for the non-unified dashboard, but IMO this is acceptable as the experience is still better overall and UD is rolling out soon and I would expect it to be available to all users relatively quickly. I would also say that I don't think the scrolling behavior as it is now would raise additional support requests any more than it might now.  

I opened a PR (mostly to build the zips) as a POC for this suggestion but I would prefer to see this land in its own issue if we ultimately decide to go with this approach. I don't think this issue needs to be blocked from moving forward though, especially since it's already been merged and the behavior works as intended (it just isn't ideal due to reasons mentioned above).

Going forward, I would suggest the following

* This issue goes back to QA with the understanding that the experience issues mentioned above will be addressed in subsequent issues
* Open a new issue for updating widget layouts (particularly loading states) to be consistent with the loaded state
* Consider the proposal outlined above (as in #4634) and potentially open a new issue for this if we're in agreement on this as a solution

Thoughts @felixarntz @tofumatt @eugene-manuilov ☝️ 

@wpdarren would you please test using the build for #4634 and see what you think about that?

**Comment by wpdarren** [comment]
@aaemnnosttv is this ready for me to run through now on #4634 build?

**Comment by aaemnnosttv** [comment]
@wpdarren please give it a brief testing, it's still only a proof of concept for my proposal.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv another alternative would be changing the styles of list/table-style widgets to have the `max-height` property for the widget body and to show a tiny vertical scrollbar if the content, in the widget body, overflows the allowed height. :thinking: 

In this case, we will always have a constant height of all widgets and will have no issues with layout shifts.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov yes, I mentioned that as well but this would require more attention per-widget I think as I'm not sure we'd be able to have one rule that we could apply to all widgets.

**Comment by felixarntz** [comment]
@aaemnnosttv Let's try the approach that you started in his #4634 PR. I agree though that makes more sense to be done in a separate follow-up issue - can you open one for that and add ACs please? We should then prioritize this for the next sprint and fix it before the rollout.

@wpdarren If everyone agrees with the above, I think we can let the issues you discovered here slip over to the new issue, and then this one could be good to go.

**Comment by aaemnnosttv** [comment]
@felixarntz 👍 see #4641

**Comment by felixarntz** [comment]
@aaemnnosttv Yes, let's move back to QA then. cc @wpdarren See the above comment.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@felixarntz @aaemnnosttv I'm sorry if I'm duplicating things here but there has been a lot of conversation regarding this ticket and 23 days since I last looked at it.  I have approved this ticket because we have created a new one for the issues, but felt it was worth going through the QAB again.

```
Turn ON Idea Hub feature flag for all tests below.
Turn OFF Unified Dashboard feature flag.
```

> Go to Settings -> Connected Services -> PageSpeed Insights -> Click on Visit the Dashboard. The page should scroll to the top of Page Speed and Experience Header.

Initially jumps to the top of the the top of Page Speed and Experience Header but jumps up as its loading.  ❌ 

> Deactivate and then activate PageSpeed insights in settings and click on the Jump to the bottom of the dashboard to see how fast your home page is in the Success Banner Notification. The page should scroll to the top of Page Speed and Experience Header.

Initially jumps close to the the top of Page Speed and Experience Header but jumps up as its loading.  ❌ 

> Activate Idea hub in settings and click on the Jump directly to Idea Hub to see topic suggestions for your site in the Success Banner Notification. The page should scroll to the Ideas to write about... header.

This works as per the QAB ✅ 

`Turn ON Unified Dashboard feature flag.`

> Go to Settings -> Connected Services -> PageSpeed Insights -> Click on Visit the Dashboard. The page should scroll to the top of Page Speed and Experience Header.

Initially jumps to the top of the the top of Page Speed and Experience Header but jumps up as its loading.  ❌ 

> Deactivate and then activate PageSpeed insights in settings and click on the Jump to the bottom of the dashboard to see how fast your home page is in the Success Banner Notification. The page should scroll to the top of Page Speed and Experience Header.

Initially jumps close to the the top of Page Speed and Experience Header but jumps up as its loading.  ❌ 

> Activate Idea hub in settings and click on the Jump directly to Idea Hub to see topic suggestions for your site in the Success Banner Notification. The page should scroll to the Ideas to write about... header.

This works as per the QAB ✅ 

There's a test that isn't included in the QAB, but is an issue. When you go to the settings for Idea Hub and click on the `visit the dashboard` link, you go back to the Unified Dashboard but not to the Idea Hub widget. I have a feeling there's a ticket for this so it could be an outstanding issue. ❌ 

> Also test that clicking on the chips in the new dashboard navigation make the page scroll to the correct headers as before.

The chips work as expected and navigate to the correct widgets ✅
