### ISSUE TITLE
Create `Module_Sharing_Settings`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4475]
## Feature Description

In preparation for the interface for managing dashboard sharing settings, we need a new class for managing the value like we have for other settings and options.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new `Module_Sharing_Settings` class in the `Core\Modules` namespace, extending the `Core\Storage\Setting` class
* The option it name it manages is `googlesitekit_dashboard_sharing`
* The default value is an empty array
* The type it is registered with should be `object`
* Its `sanitize_callback` should enforce the following structure:  
	```
	[module-slug]: SharingSettings
	```
	where `SharingSettings` has the following shape
	```
	{
		sharedRoles : string[],
		management  : string,
	}
	```
	`management` can only be one of the following: `owner` or `all_admins` (default: `owner`)

## Implementation Brief

* Create a new class `Core\Modules\Module_Sharing_Settings` that extends the `Core\Storage\Setting` class.
  * Add the `OPTION` constant with the `googlesitekit_dashboard_sharing` value.
  * Add a new protected method `get_default()` that returns an empty array.
  * Add a new protected method `get_type()` that returns `'object'` string.
  * Add a new protected method `get_sanitize_callback()` that returns an anonymous function that accepts `$option` argument and enforces the structure defined in AC.

### Test Coverage

* Add phpunit tests to check the `Module_Sharing_Settings` class.

## QA Brief

QA: Switch on Dashboard Sharing and perform simple smoke testing.

QA:Eng: Additional code review to verify the requirements are met.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by jimmymadon** [comment]
@aaemnnosttv Regarding the `get_sanitize_callback()`, I think you suggested only casting/removing elements rather than modifying/adding default elements. For the `sharedSetting[ $module_slug ][ 'management' ]` key, we said we could modify the `get_default()` method in the future to enforce its value to be `owner` by default. However, the `default` value for the setting is probably only used when the option is not set. So as @eugene-manuilov [suggests](https://github.com/google/site-kit-wp/pull/4668#discussion_r787772641 ), would it make sense to enforce the AC in this callback? Can you confirm what you had in mind for this method in [this PR](https://github.com/google/site-kit-wp/pull/4668)? Thanks!

@eugene-manuilov Thank you for the feedback - I've actioned all the other items for now.

**Comment by jimmymadon** [comment]
@aaemnnosttv I have replied to your suggestion in the PR and wanted to check if I should implement this as part of this issue.

**Comment by kuasha420** [comment]
# QA:Eng :heavy_check_mark: 

Code meets the AC and newly added & existing tests all pass. Since this newly added class is not used anywhere in the Codebase yet other than the test in this ticket, regular smoke testing/QA is not really needed here. 

Sending to approval. 

CC @wpdarren @aaemnnosttv
