### ISSUE TITLE
Chip doesn't do anything when in the section

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4488]
## Bug Description

As per bug bash tickets:
https://app.asana.com/0/1201438453642602/1201478352201031
https://app.asana.com/0/1201438453642602/1201453960164093
https://app.asana.com/0/1201438453642602/1201479361460033

Upon initial dashboard load, clicking the 'Traffic' chip doesn't do anything because the user is already in the Traffic section. If you scroll down the page after initial load and then click the Traffic chip, it does work. Perhaps the issue here is that the Traffic chip appears like it isn't working because the user is already at that anchor on the page.

Potential suggestion to make the chips active when scrolling to make it clear to users what section they are in on the dashboard.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `DashboardNavigation` component is updated to use a custom implementation of chips instead of using the functionality from the `@material/react-chips` package. The updated component works as following:
  * The selected chip can't be unselected
  * When the user clicks on a non-selected chip, the page scrolls to the correct location, the clicked chip becomes selected instead of the previously selected one, and the current URL hash changes to the newly selected chip anchor.
  * When the user scrolls the page, an appropriate chip becomes selected and the URL hash changes to the new anchor if the top of the corresponding area reaches the upper visible position of the widgets area (below the navigation bar).
    ![sitekit 10uplabs com_wp-admin_admin php_page=googlesitekit-dashboard](https://user-images.githubusercontent.com/873049/145206333-c6cc3085-fac5-43f6-b19e-f9afd679c797.png)
  * When the user has scrolled to the very top of the page and the first area is still behind due to a notification banner, the first chip is selected anyway. In other words, if the first widget area is lower than the navigation chips, the first chip should be selected.

## Implementation Brief

* Edit the `DashboardNavigation` component:
  * Update the `selectedIds` state variable to be a single string instead of an array and rename the variable to be just `selectedId`. Rename the companion `setSelectedIds` function to `setSelectedId`.
  * Update the `handleSelect` callback that should get "hash" from the `.target.id` property of the `event` argument passed to the callback function instead of the `selections`.
  * Replace the `ChipSet` element with a simple `<div>` using the same class name.
  * Update all `Chip` elements:
    * Add `onClick={ handleSelect }` property.
    * Add `selected={ selectedId === ... }` property.
  * Add a new `useEffect` hook that does the following:
    * Defines a new throttled function `onScroll` that finds the closest widget context area to the top and selects its id using the `setSelectedId` function.
      * To find the closes widget context area, loop through each area and get their top positions. The closest will be the one with the biggest negative value (closest to `0`).
         ```js
         let closest = undefined;
         let closestId = ANCHOR_ID_TRAFFIC;
         
         for ( const areaId of [ ANCHOR_ID_TRAFFIC, ANCHOR_ID_CONTENT, ... ] ) {
             const top = document.getElementById( areaId ).getBoundingClientRect().top;
             if ( top < 0 && ( closes === undefined || closest < top ) ) {
                 closest = top;
                 closestId = areadId;
             }
         }
         ```
         Also, don't forget to subtract the height of all sticky elements in the header to make sure that chips update their position when their top borders go under sticky elements.
         * Or as an alternative, find the closest area whose top position is the closest to the bottom position of the `DashboardNavigation` element. 
      * If there are no areas with a negative top position, then select the first area which is `ANCHOR_ID_TRAFFIC`.
      * Use the `_.throttle` function from the `lodash` library with `50` ms timeout to wrap the function:
         ```js
         import throttle from 'lodash/throttle';
         const onScoll = throttle( () => { ... }, 50 );
         ```
    * Adds a new event listener for the `scroll` event using the `onScroll` function.
    * Returns an anonymous function that removes the previously defined scroll event listener.
* Edit `assets/sass/components/global/_googlesitekit-dashboard-navigation.scss`:
  * Set `display: flex` for the `.googlesitekit-navigation` class.
  * Update chip styles to display correctly after removing the `ChipSet` element.

### Test Coverage

* Fix any failing tests.

## QA Brief

- Go to the Site Kit dashboard
- Scroll the page to each section from top to bottom (Traffic, Content, Speed, and Monetization)
- Verify the appropriate chip is selected and the URL is updated with the hash
- Click the chips and verify the same
- Make sure everything works as expected

## Changelog entry

* Update unified dashboard to update the active navigation chip on scroll.

**Comment by eugene-manuilov** [comment]
@felixarntz do you mind reviewing AC?

**Comment by eugene-manuilov** [comment]
Thanks, @felixarntz. AC is updated.

**Comment by kuasha420** [comment]
There is a lot going on in the AC. I've broken it down to the following:

* New component design and styling. 
* Scroll Behavior
* Hash management
* Chip Auto Selection on page load/scroll.

I've opted to use `react-scroll` which will allow us to take care of last 3 with reasonably minimal effort, leaving only the design of new component as the main `execution` task. Once I was mostly done with the IB using the approach outlined, I realized that I should have asked about using `react-scroll` and the overall approach first before continuing. Apologies! 

Oh well, what's done is done. Sending it to IBR. Let me know if the approach is something that we're comfortable with and any other issues with the IB. 

Regarding estimate, this is a hard one, considering all the styling needed for new component to be up to par with figma design on desktop and mobile. @asvinb, may be you will be able to help out with the guesstimate here.

**Comment by eugene-manuilov** [comment]
The `react-scroll` package seems to be pretty big: [237kB](https://packagephobia.com/result?p=react-scroll) when minified. I think the desired functionality can be easily implemented by ourselves and we don't need to use an external library for it.

**Comment by tofumatt** [comment]
Agreed on `react-scroll`. What is the reason for using `react-scroll`, specifically? Its README isn't very illustrative of _exactly_ what it does, and if it's about animated scrolling, something like `scrollTo({ behaviour: 'smooth' })` is fine; [we use that elsewhere in the plugin](https://github.com/google/site-kit-wp/blob/86c5353c5ac1a3c97c444f2aff7cf1d538133fcc/assets/js/components/DashboardNavigation.js#L112-L118) and it's built-in to the browser 🙂 

I'm guessing it's mostly used for the `spy` type attributes, which seemingly highlight the chip when the appropriate element is on-screen, correct? If that's the case: yeah, I think @eugene-manuilov's right and we can probably implement that on our own… using `useIntersection` (which we already use elsewhere) or even with a lighter-weight library.

We could do `useIntersection` for each Widget Context and figure out whichever one is either the "most" on-screen (we can get the `intersectionEntry?.intersectionRatio` for each section) to choose which chip should be highlighted. And/or we could just use the "last" one in the list that's on-screen and treat that one as the one on-screen.

Either way: if we remove the `react-scroll` usage I think we can also remove the need to do the complicated `offset` calculation, right?

Let's try for an approach with `react-scroll`, if that all makes sense 🙂

**Comment by kuasha420** [comment]
I have updated the IB to use `useIntersection` and removed the need for `react-scroll`. This is going to be quite a bit more involved and we must test all the interactions here (hash change, scrolling, soft refresh, race condition) etc. New component based on `Button` will also be need to replace the chip library.

There are some downsides to this approach however,
* Unless we do some fancy/complicated margin calculation, I think we will not be able to achieve the perfectly aligned scroll based Chip selection that is highlighted in the AC screenshot. (Intersection Observer only gives us ratio, not exact pixel position, also it is calculated based on the entire viewport. We have WP Sidebar/Adminbar/Header which will mess with the ratio. 
* The 0.5 threshold is not foolproof. Not sure how to handle that from my limited experience with the API. 
* More things to test and get right instead of using already established library solution. 

I have kept the previous IB in case we want to go back. Regarding size of the package, I assume there should be some tree shaking involved. Not entirely sure though.
I have bumped the estimate to 19 to account for the manual implementation of spying and state management that was handled by `react-scroll` in the previous iteration of the IB. 

@eugene-manuilov or @aaemnnosttv please review it as Matt is ooo. 

Cheers.

**Comment by aaemnnosttv** [comment]
> The existing `@matierial/react-chips` library is not supposed to be used as a navigation element. It has been created with aims to be used as form elements to allow users to select or deselect something (as some kind of a toggle). Thus it doesn't allow to turn off the ability to unselect a chip or, which is even worth, to select another chip from the outside of the `ChipSet` component because the selected chip information is stored in the state of the `ChipSet` element.

@eugene-manuilov @kuasha420 This is accurate about the `ChipSet`, however what prevents us from continuing to use the `Chip` component and wrap that with our own behavior that `ChipSet` doesn't work for? E.g. `selected` is a prop we can control on the `Chip`, just as are other interaction handlers. We will need `@material/react-chips` in dashboard sharing later so I think it would be preferable to keep this if possible to avoid inconsistencies as well as potentially reimplementing a component unnecessarily.

> * Instead, use layout components (`Grid`, `Row`, `Cell`) for the container element and a customized version of `Button` (ie. `ChipButton` more on this later) component to replicate the design from Figma.

@kuasha420 I don't think grid is appropriate for this case because we want the items to be centered in a fluid way, rather than adhering to more specific columns. We probably want to ensure the gap between them is consistent with the grid gap, but that's more about visual consistency. I also don't think we'd ever want the items to wrap onto multiple lines for this component either. If needed, the content should scroll horizontally.

> * Unless we do some fancy/complicated margin calculation, I think we will not be able to achieve the perfectly aligned scroll based Chip selection that is highlighted in the AC screenshot. (Intersection Observer only gives us ratio, not exact pixel position, also it is calculated based on the entire viewport. We have WP Sidebar/Adminbar/Header which will mess with the ratio.

Can we not use the `.googlesitekit-page` as the root element to use for intersection calculation? This would at least rule out the admin bar and admin menu, so the only thing we'd need to adjust for is our own header.

> * The 0.5 threshold is not foolproof. Not sure how to handle that from my limited experience with the API.

Other than the concern above, are you referring to something else?

> I have kept the previous IB in case we want to go back. Regarding size of the package, I assume there should be some tree shaking involved. Not entirely sure though.
> I have bumped the estimate to 19 to account for the manual implementation of spying and state management that was handled by `react-scroll` in the previous iteration of the IB.

It would be good to check how much our bundle size would actually be affected after tree-shaking to get a sense of if this package is considerable or not. BundlePhobia shows it only adds 6.9kb minified and gzipped which looks more accurate as the source doesn't seem that large, and it only has two dependencies. https://bundlephobia.com/package/react-scroll@1.8.4
See https://github.com/styfle/packagephobia/blob/main/README.md#how-is-this-different

**Comment by eugene-manuilov** [comment]
> This is accurate about the `ChipSet`, however what prevents us from continuing to use the `Chip` component and wrap that with our own behavior that `ChipSet` doesn't work for? E.g. `selected` is a prop we can control on the `Chip`, just as are other interaction handlers.

@aaemnnosttv, in our case, what we call `chips` are just `div`-s with rounded corners. I don't think it's worth adding a whole 3rd party library just to avoid adding rounded corners to a `div` ourselves.

> We will need `@material/react-chips` in dashboard sharing later so I think it would be preferable to keep this if possible to avoid inconsistencies as well as potentially reimplementing a component unnecessarily.

We can always add it back if it's needed. Can you remind me how we want to use it for the dashboard sharing functionality? If I remember correctly, then it's going to be used to display selected roles, right?

> It would be good to check how much our bundle size would actually be affected after tree-shaking to get a sense of if this package is considerable or not. BundlePhobia shows it only adds 6.9kb minified and gzipped which looks more accurate as the source doesn't seem that large, and it only has two dependencies.

Our assets are already quite big. I think that we should avoid adding 3rd party libraries for simple things that can be solved by a single event listener, even though it is just ~7kb when minified and gzipped.

**Comment by eugene-manuilov** [comment]
@kuasha420 @tofumatt @aaemnnosttv IB is unnecessarily complicated. I'll rework it to use a more straightforward approach.

**Comment by felixarntz** [comment]
@eugene-manuilov @kuasha420 @tofumatt I just revisited this one with @aaemnnosttv, and we came to the conclusion that the decision to remove the `@material/react-chips` was made a bit preliminarily. At a minimum that part should not be in the ACs since that is more IB material, but we also think it would be better to keep the package, for the following reasons:
* The `Chip` component from there comes with all the styles and behavior we need. It may seem that that is trivial, but there's a lot of small visual and accessibility tweaks here or there, which would make it tedious to manually recreate the component.
* We already use other Material React packages for components, and from a maintenance perspective that is preferable. That way we ensure we use the correct Material design and don't have to manually maintain the styles. For example, if the styles for all Material components changed with some update, we would risk the chips styles getting "out of sync" if we maintained them manually.
* We will most likely need `@material/react-chips` again for dashboard sharing anyway, for the UI to modify shared roles - and for that even the `Chipset` component would likely be the right use-case.

The `Chip` component from the package can be controlled via props, so I'd suggest we keep using them, but only implement a custom version of `Chipset`. Maybe something like a `ScrollNavigationChipset` component. So while we would not use `Chipset` for this issue at all, I think the `Chip` component still provides enough benefit for us to keep the package.

**Comment by eugene-manuilov** [comment]
IB is updated.

**Comment by aaemnnosttv** [comment]
> * The `DashboardNavigation` component is updated to use a custom implementation of chips instead of using the functionality from the `@material/react-chips` package.

The AC needs tweaking to reflect the latest changes. I noticed there are a few older points that were ~~stricken through~~, please remove these instead – we can always dig back into the edit history if needed.

> * To find the closes widget context area, loop through each area and get their top positions. The closest will be one with the biggest negative value (closest to `0`).

In this case I believe `0` would be the top of the viewport, correct? Can use the bottom of the  `DashboardNavigation` element instead as that would be the top visually?

> * Use the `_.throttle` function from the `lodash` library with `50` ms timeout to wrap the function:

`@wordpress/compose` has a `useThrottle` hook which has some benefits over `throttle` by itself like cancelling scheduled callbacks if the dependencies change. The downside is our version of compose doesn't include this yet. We copied over `useDebounce` a while back, maybe we could do the same here since it's such a simple hook. Take a look and see what you think though – maybe it's not needed.

The IB LGTM otherwise unless there's anything from @felixarntz 👍

**Comment by eugene-manuilov** [comment]
> The AC needs tweaking to reflect the latest changes. I noticed there are a few older points that were stricken through, please remove these instead – we can always dig back into the edit history if needed.

Updated :+1:.

> In this case I believe 0 would be the top of the viewport, correct? Can use the bottom of the DashboardNavigation element instead as that would be the top visually?

Added it as an alternative approach.

> @wordpress/compose has a useThrottle hook which has some benefits over throttle by itself like cancelling scheduled callbacks if the dependencies change. The downside is our version of compose doesn't include this yet. We copied over useDebounce a while back, maybe we could do the same here since it's such a simple hook. Take a look and see what you think though – maybe it's not needed.

Yes, in this case, we can just use the `throttle` function from the `lodash` library because we need to throttle a regular function, thus there is nothing to cancel for the `useThrottle` hook.

**Comment by aaemnnosttv** [comment]
Thanks @eugene-manuilov 👍 

IB ✅

**Comment by eugene-manuilov** [comment]
@hussain-t did you push your changes? I see there is nothing has changed since my last review.

**Comment by hussain-t** [comment]
@eugene-manuilov I just pushed the changes.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@eugene-manuilov just one observations. In the AC it says:
 
> The selected chip can't be unselected

It is true that the chip can't be unselected but when you hover over the selected chip, the mouse cursor and hover style, makes it appear that you can.  Of course, nothing happens, but it's a weird UX/UI in my opinion. Could be out of scope?

**Verified**

- When I scroll the page to each section from top to bottom (Traffic, Content, Speed, and Monetization) the appropriate chip is selected and the URL is updated with the hash. 
- When I click the chips they jump to each section, the appropriate chip is selected and the URL is updated with the hash. 
- When I click on a non-selected chip, the page scrolls to the correct location, the clicked chip becomes selected instead of the previously selected one, and the current URL hash changes to the newly selected chip anchor.
- When I have scrolled to the very top of the page and the first area is still behind due to a notification banner, the first chip is selected. Tested this with a few different notification messages.
- Tested the behaviour on smaller screen sizes and ensured the checks passed with and without notification banner. 
- Tested the behaviour functions the same with Idea hub module activated. 
- Tested the behaviour with various modules disconnected, i.e AdSense and PSI

![image](https://user-images.githubusercontent.com/73545194/149325771-d94cff5c-e074-4adc-8d67-43bbc56091bf.png)

**Comment by eugene-manuilov** [comment]
> It is true that the chip can't be unselected but when you hover over the selected chip, the mouse cursor and hover style, makes it appear that you can. Of course, nothing happens, but it's a weird UX/UI in my opinion. Could be out of scope?

@wpdarren, this is how the `@material/react-chips` library works. I think this is out of scope and it would be better if we create a separate ticket for it.
