### ISSUE TITLE
Mobile view: Google Analytics setup contents overlap

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4494]
## Bug Description

As per bug bash ticket: https://app.asana.com/0/1201438453642602/1201480915602753

There is a minor design issue on mobile view GA setup page. Please refer to the screenshot.

## Steps to reproduce

1. Start Analytics setup using an account that has a matching UA + GA4 property
2. In a mobile viewport, note the GA4 notice overflows horizontally 

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/145430447-c4d47c67-4b06-43ee-ad4a-1f7636999b77.png)

[Big screenshot](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/55b07348-7f8f-4593-9a15-793860f80af9)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On a small-width viewport, the content in the Analytics setup (specifically within the blue notice box) should respect the container width and not exceed it (see screenshot above).

## Implementation Brief
* Using `assets/sass/components/settings/_googlesitekit-settings-notice.scss`,
	* Add `min-width: 0` to `.googlesitekit-settings-notice__body`. It's good to know that for flex elements, the `min-width` is set to `auto`. This can make block elements take up much more space than desired, even stretching their container beyond the screen edge on small screens. The fix is to set the `min-width: 0` which tells the browser that for this element, to take up the available space.

### Test Coverage

* No new tests to be added.

## QA Brief

- Disconnect Google Analytics if it is already connected
- Go to the Site Kit settings page
- Open the developer tools and enable mobile view
- Try connecting GA
- Verify that the blue notice box and the property dropdown doesn’t overflow specially when the dropdown item’s text is longer

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
@eclarke1 While this was found in the bug bash, this is unrelated of the unified dashboard, so I'm gonna remove the epic here. It's still worth fixing this soon, but not actually a launch blocker since it doesn't have to do with the epic. On that note though, fixing this is therefore probably even more important, since this already surfaces in production today.

**Comment by aaemnnosttv** [comment]
@asvinb this addresses the AC but leaves a bit to be desired as far as the experience goes on mobile as the value in the select gets truncated. I tested making the notice content horizontally scrollable which isn't great either; particularly how the menu is handled in this situation isn't good. I think for mobile perhaps the best experience might be using a native select, but that's a discussion for another issue 😄  I think this is the best we can do for now as a simple change.

IB ✅ 

Since this is no longer a launch blocker for the unified dashboard, I'm going to downgrade the severity here as it is more of a visual flaw than anything broken.

**Comment by asvinb** [comment]
That's right @aaemnnosttv Looks like the text within the selects are meant to be on one line as well, else they look weird when on 2 lines. That's why they are truncated. Looks like it's the default behaviour though:
https://mui.com/components/selects/
If you test here, and put a very long text within the select, the latter will grow to its maximum size and then truncate any overflowing text.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The blue notice box and the property dropdown doesn’t overflow especially when the dropdown item’s text is longer.
- Tested this on various mobile devices and also responsive screen settings. 

<details>
 <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/73545194/145670000-c9c7c8e6-40ac-4923-aa1a-01153d207ab2.png)

</details>
