### ISSUE TITLE
Box shadow animation when scrolling top of the page

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4502]
## Bug Description

When scrolling to the top of the main dashboard, the box shadow animation is weird, with 2 borders showing up momentarily.

https://user-images.githubusercontent.com/1621608/146362433-86d77e36-df43-4847-ab89-2252ed31ee9c.mp4

A quick inspection shows the problem is related to the added space here which is only shown when scrolled to the top due to the sticky position of the header. https://github.com/google/site-kit-wp/blob/85a5e02c0cabf732b651a2fd5ebdff6c113e28e7/assets/sass/components/global/_googlesitekit-header.scss#L173

https://app.asana.com/0/1201438453642602/1201480648448644

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Site Kit header should not appear to change in height between scrolled at the top-most position and below in the context of the unified dashboard. It also should be ensured that there is no visual change in the box-shadow at the moment of the "transition" between regular and sticky header.

## Implementation Brief

- Remove the `shadow` mixin from `.googlesitekit-subheader` and the `min-height` property.
- Add a new pseudo element at `.googlesitekit-navigation`, specifically `before` and make sure is visible using the full width of the container.
  - Set the position to `absolute`
  - Add the `shadow` mixin
  - Set the height to `3px`.
  - Set the `top` position to `-3px`.

### Test Coverage

* 

## QA Brief
* Enable the `unifiedDashboard` feature flag.
* Scroll up and down on the main dashboard.
* There should be no weird behaviors with the box-shadow for the header.

## Changelog entry

* N/A

**Comment by eclarke1** [comment]
@felixarntz @aaemnnosttv this was one of our 'Nice to have' for launch issues, which is sitting in Triage right now. Any chance we could move this over to AC?

**Comment by aaemnnosttv** [comment]
@felixarntz I've added some preliminary AC, let me know what you think as it's a bit odd to define. cc: @asvinb thoughts here?

**Comment by felixarntz** [comment]
@aaemnnosttv Makes sense - looks like it's indeed just a height change and not actually a change in the box shadow itself. I still added a note that there should not be any notable box shadow style change.

**Comment by eclarke1** [comment]
@mitogh please could you kindly add an estimate here, considering engineering, CR and QA? Thanks

**Comment by mitogh** [comment]
Added an estimate @eclarke1

**Comment by aaemnnosttv** [comment]
@mitogh this looks like an interesting solution - does it worth the same as today both with and without content in the subheader when scrolled to the top and below?

**Comment by mitogh** [comment]
Yes, basically the current solution has a subheader before the header, but the actual shadow comes from the navigation, I've tested this solution for the main dashboard page and also individual post page where content is present there looked good on my end.

The end goal with the new approach is to move the shadow where it actually should be which is the top of the navigation instead of the bottom of the header as that one is moved as you scrolled on the page instead the navigation header remains stick at the top which eventually would stick the shadow at the same time.

Let me know in case you have any additional concerns / questions @aaemnnosttv

**Comment by aaemnnosttv** [comment]
Sounds good to me. @asvinb would you give this a quick look over? If it sounds good to you let's move it forward 👍

**Comment by asvinb** [comment]
@mitogh The IB looks good from what I can see! Great job! For context, we have the border in the subheader because at the time of its implementation, we didn't have the navigation yet, basically we had to find a workaround using only the header and subheader.
IB: ✅

**Comment by asvinb** [comment]
@aaemnnosttv The changes look good. I tested and everything works fine. Assigning ticket back to you to review and merge.

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified**

- This issue is resolved now and there are no weird behaviors with the box-shadow for the header.
- Verified issue on Chrome, Safari, Edge and Firefox.
- Verified issue on both main dashboard and entity dashboard.

<details>

https://user-images.githubusercontent.com/94359491/151292848-42350f5d-0156-412e-9675-5aed729b111f.mp4

</details>
