### ISSUE TITLE
Code Coverage link in PSI widget goes to a 404 page when clicked

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4513]
## Bug Description

Within the Page Speed Insights widget there are suggestions to improve the speed of the site.   

Under `Reduce unused JavaScript` we have a link to the code coverage page, which is an external link to: 

`https://developers.google.com/web/updates/2017/04/devtools-release-notes#coverage` 

When you click on it, you receive a 404.  Do we have a replacement URL or do we need to remove this link?  

This widget appears on the current dashboard, unified main and entity dashboard.  

The link also appears in the desktop and mobile reports within the widget. 

![image](https://user-images.githubusercontent.com/73545194/145242217-6f31f1d0-5dad-4733-a21f-76afb63febd2.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@wpdarren this comes from the PageSpeed API so we'll need to raise this elsewhere to get it corrected 👍

**Comment by felixarntz** [comment]
@aaemnnosttv @wpdarren This is already fixed actually (@jamesozzie had already reported it in https://github.com/GoogleChrome/lighthouse/issues/12473), and it was fixed in https://github.com/GoogleChrome/lighthouse-stack-packs/pull/75. It should probably appear correctly by now, since that PR was merged about a month ago.
