### ISSUE TITLE
Enhance module data request infra to allow for shared requests

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4532]
## Feature Description

This issue is responsible for implementing the foundational infrastructure for dashboard sharing on the backend. The main changes needed for dashboard sharing are moving away from using a single "main" `OAuth_Client` (which provides the necessary Google `Client` class needed for communicating with Google APIs), to using a more localized client instance which could be set up on behalf of the module's owner.

A substantial amount of the implementation has been laid out in an exploratory proof of concept which will be used as a base for the remaining work to be done. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Module data request infrastructure should be updated to make shared data requests on behalf of the module owner (instead of the current user) if the request qualifies satisfies the following:
	* The datapoint is defined as `shareable`
	* The current user is capable of reading shared data for the module executing the request
* Non-shared requests should continue to work as today

## Implementation Brief

**Building on the POC started in #5126**

* Mostly tests left to address
* Summary of POC
	* Extracted a new `Datapoint` class to represent a datapoint definition
	* Introduced new method for providing the `OAuth_Client` instance to use for the given request
	* Refactored request validation to be decoupled from main client

### Test Coverage

* Fix broken tests
* Add test coverage where possible (with/without `dashboardSharing`)

## QA Brief

* Module data requests should continue to work as today with `dashboardSharing` off
* Qualifying view-only users should be able to request data successfully on the main and entity dashboards

## Changelog entry

* Allow view-only users to make data requests for shared modules with owners.

**Comment by felixarntz** [comment]
IB ✅

**Comment by eclarke1** [comment]
@aaemnnosttv is this an issue you are intending to work on? Or can we unassign from you and have anyone in the team pick this up? cc @FlicHollis

**Comment by aaemnnosttv** [comment]
@eclarke1 thanks for the nudge; yes, I am planning on working on it this week. I should be able to have it in CR by EOW (there's already a PR started for it as well).

**Comment by FlicHollis** [comment]
Great thanks @aaemnnosttv let me know if this changes and we can see if someone else can pick this up.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@aaemnnosttv I have a few observations when viewing data on the view only dashboard.  The PSI still has an error message `Error: Site Kit can’t access the relevant data from PageSpeed Insights because you haven’t granted all permissions requested during setup.`. I suspect that this is because of another ticket in Execution/CR. 

Also there are a number of console errors appearing as you can see in the screenshot below.  Again, I suspect that this is because of another ticket in Execution/CR.  Please could you confirm if what I see is expected at this time? 

By the way, I used elasticpress.io so this is a site with real data. 

![image](https://user-images.githubusercontent.com/73545194/171161730-fd0aa514-61ff-49b6-8a31-c2415a85614b.png)

**Verified:**

- To test this I set up all of the modules where data is loaded on the main and entity dashboard.  This was tested with `dashboardSharing` feature flag disabled.  No issues occurred with the data. Everything loads as expected for all modules, i.e. Search Console, Analytics, AdSense, PSI and Idea Hub. 

- To test this I set up a new user with Editor role with `dashboardSharing` feature flag enabled  Using the Shared settings plugin, I gave the editor access to all of the modules highlighted above.  When I logged in with the editor user, I saw the splash page and was able to view the dashboard.  All of the data for the modules appeared on the main and entity dashboard. No issues occurred with the data. Everything loads as expected for all modules.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@aaemnnosttv The data does load as expected for the non-admin user (editor) and I can see all of the data that I would expect, but the I wanted to expand on the error messages I am seeing in the console. I am unsure if these errors are related to this ticket or not, so cannot approve it right now. 

1. `Google Site Kit API Error method:GET datapoint:settings type:modules identifier:adsense error:"Sorry, you are not allowed to do that."` This also appears for Analytics and Search Console.  I think that this is picked up with #5307 which you created yesterday, but would like that confirmed. 

2. When I have connected AdSense and given the non-admin user permissions to view data, this message appears in the console. `ncaught (in promise) TypeError: Cannot read properties of undefined (reading 'adsenseLinked')`

3. There are also a few 403 errors that I have not seen before: `googlesitekit-vendor-872f77e3e87909a9bc3a.js:7          GET https://elasticpress.us8.instawp.xyz/index.php/wp-json/google-site-kit/v1/modules/analytics/data/settings?_locale=user 403` and  `googlesitekit-vendor-872f77e3e87909a9bc3a.js:7          GET https://elasticpress.us8.instawp.xyz/index.php/wp-json/google-site-kit/v1/modules/adsense/data/settings?_locale=user 403`

Any thoughts if these are a result of outstanding issues, or, if they are issues we need to investigate?

**Comment by aaemnnosttv** [comment]
> 1. `Google Site Kit API Error method:GET datapoint:settings type:modules identifier:adsense error:"Sorry, you are not allowed to do that."` This also appears for Analytics and Search Console. I think that this is picked up with [Owner ID not set for shared ownership modules when saving sharing settings  #5307](https://github.com/google/site-kit-wp/issues/5307) which you created yesterday, but would like that confirmed. 

@wpdarren that issue is specific to shared ownership modules (i.e. PSI, IH), it shouldn't be a problem with other modules. This is likely related to #5305 though as the settings datapoint is not shareable. This may also be related to a different known issue around source links.

> 2\. When I have connected AdSense and given the non-admin user permissions to view data, this message appears in the console. `ncaught (in promise) TypeError: Cannot read properties of undefined (reading 'adsenseLinked')`

`adsenseLinked` is an Analytics setting related to AdSense. Is Analytics also active and connected?


> 3\. There are also a few 403 errors that I have not seen before: `googlesitekit-vendor-872f77e3e87909a9bc3a.js:7          GET https://elasticpress.us8.instawp.xyz/index.php/wp-json/google-site-kit/v1/modules/analytics/data/settings?_locale=user 403` and  `googlesitekit-vendor-872f77e3e87909a9bc3a.js:7          GET https://elasticpress.us8.instawp.xyz/index.php/wp-json/google-site-kit/v1/modules/adsense/data/settings?_locale=user 403`

This may be partially be fixed by #5305 but is likely also related to source links. I'll open an issue for this.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Note: the errors in console highlighted above, will be fixed in 5305 and another ticket. They are not directly impacted by this ticket so have moved this to approved. 

**Verified:**

- To test this I set up all of the modules where data is loaded on the main and entity dashboard. This was tested with dashboardSharing feature flag disabled. No issues occurred with the data. Everything loads as expected for all modules, i.e. Search Console, Analytics, AdSense, PSI and Idea Hub.

- To test this I set up a new user with Editor role with dashboardSharing feature flag enabled Using the Shared settings plugin, I gave the editor access to all of the modules highlighted above. When I logged in with the editor user, I saw the splash page and was able to view the dashboard. All of the data for the modules appeared on the main and entity dashboard. No issues occurred with the data. Everything loads as expected for all modules.
