### ISSUE TITLE
Remove all direct imports from 'react'

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4535]
There are a few places where we accidentally import things from `react` - when any of those should _always_ be imported from `@wordpress/element` instead. Those occurrences are partly from legacy code, partly from oversights (likely based on auto-imports where it went wrong). Let's clean those up in this issue.

This doesn't break any production behavior so far, but still happens in a bit of production code, hence framing as a (very low-priority) bug.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Any code that imports something directly from `react` should instead import that from `@wordpress/element`.
    * Do a search for `from 'react'` to find those occurrences.
    * It should also be ensured that, as always, those imports are under the proper comment-based group "WordPress dependencies" (where `react` would have belonged under "External dependencies").
* One of those happens in `.storybook/_example.story.js`. This file is unnecessary _and_ out of date, so it should be deleted.

## Implementation Brief

* Update the `SettingsForm` component and the `compatibilityChildren` component in the `assets/js/components/setup/CompatibilityChecks/index.test.js` file to import the `Fragment` component from `@wordpress/element` instead of `react`
* Remove `import React from 'react';` in the `assets/js/components/legacy-setup/wizard-progress-step.js` file.
* Delete the `.storybook/_example.story.js` file.
* Remove the `ProvidePlugin` usage in the webpack config.
* Delete `react` and `react-dom` packages from the dependencies list.

### Test Coverage

* N/A

## QA Brief
- Do a smoke testing and make sure everything works as expected

**QA:Eng**
- Verify all the changes mentioned in the IB have been addressed

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
cc @aaemnnosttv @tofumatt @eugene-manuilov

**Comment by DerekJxy** [comment]
Hello! Can I try to fix this issue?

**Comment by aaemnnosttv** [comment]
Thanks @eugene-manuilov – just a few questions, otherwise this looks good overall 👍 

> * Remove the `ProvidePlugin` usage in the webpack config.

Is this no longer necessary? If we don't need it, then great, but if we would need to update all our components to import it instead now, that would be too much I think, but we could perhaps change the `React` to be provided `@wordpress/element` instead. See https://github.com/google/site-kit-wp/pull/1013 where this was added.

> * Remove `react` and `react-dom` from node modules.

(I assume you mean from `package.json`) I'm not sure we can do this, but it's also not called for in the ACs. I think this is needed for pinning the specific version of React we use which is not quite the same as which version can be installed based on dependencies.

**Comment by eugene-manuilov** [comment]
> Is this no longer necessary? If we don't need it, then great, but if we would need to update all our components to import it instead now, that would be too much I think, but we could perhaps change the `React` to be provided `@wordpress/element` instead. See #1013 where this was added.

This has never been needed. We use the `@wordpress/babel-preset-default` preset that has its own pragma declaration to use `React.createElement` from the `@wordpress/element` package.

> (I assume you mean from package.json) I'm not sure we can do this, but it's also not called for in the ACs. I think this is needed for pinning the specific version of React we use which is not quite the same as which version can be installed based on dependencies.

We don't need `react` and `react-dom` packages, and we don't use them because we rely on the version installed with `@wordpress/element` package. If we want to pin a specific version of React, we need to pin the specific version of `@wordpress/element` that uses that version.

> PS. don't forget to mention .storybook/_example.story.js which is also called for removal in the ACs

Ah.. yes, forgot to add it. Thanks! Updated :+1:

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by tofumatt** [comment]
QA ⚠️ 

Looks like there's one thing from the IB that's missing from the implementation: removing the `ProvidePlugin` from `webpack.config.js`. I left a comment here: https://github.com/google/site-kit-wp/pull/4552/files#r769127566

But from my testing that can be removed without any issue, and we might as well do that to simplify our config since the WordPress babel config does that for us, as @eugene-manuilov pointed out above.

----

Everything else seemed fine—I did some smoke testing and the existing changes work fine. I also did some smoke testing with my recommended change (eg. removing the `ProvidePlugin` from the `webpack.config.js` and it worked fine, so unless there's something that needs it we should remove it.

**Comment by tofumatt** [comment]
Hmm, I just saw the discussion on that PR saying it was needed for E2E tests. I ran those locally after removing the `ProvidePlugin` and saw the errors. Okay, in that case: QA ✅

**Comment by hussain-t** [comment]
To close the loop here, we need the `ProvidePlugin` for e2e and VRT tests. Please refer to [this comment](https://github.com/google/site-kit-wp/pull/4552#discussion_r769236017) :)

**Comment by hussain-t** [comment]
Thanks @tofumatt. Yes, we need the `ProvidePlugin` for e2e and VRT tests.
