### ISSUE TITLE
Assets are being loaded on non site kit pages.

### ISSUE THREAD

**Issue by mitogh** [google/site-kit-wp#4583]
## Bug Description

When a logged-in user opens a page that does not have a module related to Site Kit plugin like viewing a blog post, the JS and CSS assets from the plugin are loaded in.

Technically this does not break anything but I don't think this should be the right behavior due we are downloading and transferring unused assets into not site kit pages.

## Steps to reproduce

1. Open your browser console and select the network tab, then enable JS, and on the filter place `wp-content/plugins/`
2. Navigate in pages of WordPress that are not site kit related to like:
- wp-admin/
- wp-admin/edit.php
3. Observe the list of downloaded files.

Replicate the same steps for FE pages like posts and pages as well.

## Screenshots

![2021-12-17_17-09](https://user-images.githubusercontent.com/3921289/146618215-d940d069-3104-4384-bac1-c0cd07400181.png)
![2021-12-17_17-10](https://user-images.githubusercontent.com/3921289/146618217-cd318543-f926-4875-85df-c34079e9c2b3.png)
![2021-12-17_17-10_1](https://user-images.githubusercontent.com/3921289/146618219-bfb7c5b0-da2b-4171-a671-ab339f8503c4.png)

## Additional Context

 - PHP Version:  7.4
 - OS: iOS
 - Browse Chrome
 - Plugin Version 1.48.0
 - Device: iPad

This behavior only happens when the user is logged in. And is not affecting non-logged-in users. Scripts and Styles from the plugin are downloaded on each request that is not site kit related.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This is intentional when Site Kit is setup (and the current user is able to use Site Kit) as it enhances a number of other locations, such as the WordPress dashboard (with the Site Kit Summary widget) and the admin bar app on the front end which provides similar metrics and a link to the detailed dashboard for that URL within Site Kit.

Other pages such as the post list screen also load Site Kit assets if Idea Hub is enabled.

So, many common screens that aren't technically Site Kit screens do load our assets but we need to look at them individually to assess whether or not they should be loaded.

It's worth noting that there is a single Site Kit script which is [loaded globally across wp-admin](https://github.com/google/site-kit-wp/blob/4b13e7ee8e5bf030cc315dae4f9c6a19416ffe2d/includes/Core/Assets/Assets.php#L287-L292) which is `googlesitekit-base` which is a minimal script that does not load everything else (like most screens). Looking at this script again, I'm not sure we really need it globally anymore as it only does two things, one of which is scoped to Site Kit screens and the other seems unnecessary (cc: @felixarntz). This also loads our `i18n` asset which is the substantially larger script to load relatively speaking.

So most other non-Site Kit screens only load these two 
![image](https://user-images.githubusercontent.com/1621608/146738720-4a5da42c-acca-4fd4-a13c-b3c37e13232d.png)
