### ISSUE TITLE
Consolidate and improve docker images

### ISSUE THREAD

**Issue by mitogh** [google/site-kit-wp#4591]
## Feature Description

Currently, there are 3 images related to this project when running `npm run env:start` the images being:

- `googlesitekit-e2e_cli_1`
- `googlesitekit-e2e_wordpress_1`
- `googlesitekit-e2e_mysql_1` 

Currently, the only usage of `googlesitekit-e2e_cli_1` is to run `wp cli` commands, the idea with this ticket is to consolidate both into a single image instead, by adding support and installing `wp cli` in `googlesitekit-e2e_wordpress_1` and get ride of `googlesitekit-e2e_cli_1`.

In addition to that the current image `googlesitekit-e2e_wordpress_1` does not have `composer` available and neither `npm` it would be ideal to have both:

- `composer`
- `npm`

In the required version to make sure all local environments are using the same version when running `tests`, adding dependencies or building assets.

This would be really useful, to improve the workflow for a local development.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks for the suggestion @mitogh – these containers aren't intended for local development but E2E specifically (the mysql container is shared with PHP tests now as well). We don't impose much on the local development environment that's used other than Docker being available for some things (e.g. E2E or VRT).

We don't need `composer` or `npm` within these because the build is done outside (locally or in CI) and then the plugin files are mounted inside.

We've recently discussed the possibility of using alternate images for performance but that would be for another issue 😄
