### ISSUE TITLE
Host Site Kit & Google Analytics Locally (on the hosting server) option

### ISSUE THREAD

**Issue by RicaNeaga** [google/site-kit-wp#463]
## Feature Description

There is already a plugin that does this, but only for basic Analytics code integration - https://wordpress.org/plugins/host-analyticsjs-local/

Advantages of this approach (if needed) - solves Yslow score & other benchmark issues / a small blog post here -  https://antonyagnel.com/host-google-analytics-locally/

Since Google considers speed a CRUCIAL factor and ranks it accordingly, please treat your plugin in the same manner. It would be nice for site owners to know that Site Kit & Analytics integration can be done in a slim and speedy way via your plugin.

Thanks :)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
The main problem with hosting Analytics locally is users having to configure and update the tracking code. Site Kit is primarily for users who want easy to understand and implement insights, which is why it uses an API connection implementation. I will mark it as an enhancement for the team to consider.

**Comment by jamesozzie** [comment]
Closing as we already have #1132 open in relation to this request.
