### ISSUE TITLE
Site Kit blocking wp-login via Installatron

### ISSUE THREAD

**Issue by midigitalsolution** [google/site-kit-wp#4638]
Good morning,

We have numerous sites using GoogleSiteKit.  Typically our devs login serverside via installatron. 
 As of last night Site Kit seems to be effecting (blocking) wp-login via installatron.  Strangely enough credentials are still being passed to wp so as a work around you mod the url

https://examplesite.com/deleteme.ssoacc17a0884f2472997e340f314161307.php?7a7b7c76d705add81552823932e38fa31

to

https://examplesite.com/

and you will be logged in.  See detailed error below.  Can you please advise as to a solution other than this workaround?

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Google\Site_Kit\Plugin::Google\Site_Kit\{closure}(), 1 passed in /home/examplesite/public_html/wp-includes/class-wp-hook.php on line 303 and exactly 2 expected in /home/examplesite/public_html/wp-content/plugins/google-site-kit/includes/Plugin.php:200 Stack trace: #0 /home/examplesite/public_html/wp-includes/class-wp-hook.php(303): Google\Site_Kit\Plugin->Google\Site_Kit\{closure}('MI Digital Solu...') #1 /home/examplesite/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array) #2 /home/examplesite/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #3 /home/examplesite/public_html/deleteme.ssob47c9f00a23b4946ac2aa0a87ee007f0.php(16): do_action('wp_login', 'MI Digital Solu...') #4 {main} thrown in /home/examplesite/public_html/wp-content/plugins/google-site-kit/includes/Plugin.php on line 200

**Comment by jamesozzie** [comment]
Thanks for reaching out @midigitalsolution. When logging into a standard WordPress sites there are no HTTP requests send to the Site Kit service during a typical log in. We therefore may need to check this with a similar setup to your own. With that can you share the following:
- Is this occurring with each site your devs are accessing via installatron?
- Can you confirm there are no issues logging in via Installatron with sites with Site Kit temporarily deactivated?
- Would you be able to share a screen recording showing this behaviour while including any error logs [using this Google form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/)? In order to submit the form you can reference the [sticky post URL](https://wordpress.org/support/topic/read-first-welcome-to-the-site-kit-support-forums-3/) URL as opposed to a standard WordPress support forum topic, where we typically investigate these issues before escalating to the engineers on GitHub. 

We'll also perform some checks on our side with a similar setup.

**Comment by jamesozzie** [comment]
I can confirm the same issue occurs on a support testing site. 

- No issue with Site Kit temporarily deactivated
- The issue occurs as soon as Site Kit activated (no need to set up the plugin)
- [Internal testing task](https://app.asana.com/0/1185360131189553/1201645199846628/f)

To recreate this issue:
- Install a WordPress site using Installatron
- Click on the wp-admin link provided within the Installatron interface - single sign in access proceeds (no login required)
- Install and activate Site Kit (no need to setup)
- Revisit the Installation interface from your web hosting CP
- Click on the wp-admin link once more. The critical error appears



_Below is the experience with SK installed (this occurs as soon as the plugin is activated, without having to set up)_ 

![2022-01-11-18-53-37](https://user-images.githubusercontent.com/41326532/149003950-80e11f32-e038-4cf3-80ff-495cc3acd5c1.gif)

_The below errors are logged_


![image](https://user-images.githubusercontent.com/41326532/149003688-a9f46e0f-2e9f-46df-a6a3-2e66ebfa2463.png)

**Comment by midigitalsolution** [comment]
Thank you jamesozzie :-) We really appreciate you looking into this and are looking forward to further review / response. Thanks again

**Comment by jamesozzie** [comment]
No problem @midigitalsolution.

In my case after performing a sync on a test site the wp-admin link [does work](https://recordit.co/0WJ23IdxpO). Can you perform a sync on your side and check whether this allows you to proceed? You [don't need to perform a backup](https://i.imgur.com/NvcoRzY.png) before syncing, where requested. 

We'll continue performing other checks on this in the meantime.

**Comment by midigitalsolution** [comment]
Excellent - Good job!  That appears to be the Silver Bullet.  Issue Resolved.  Thank you SK team.

**Comment by jamesozzie** [comment]
@midigitalsolution Glad to hear it, thanks for the update. Note that the fix may not necessarily be from performing a sync. It's possible this may have been a temporary issue. From testing new installs on a separate domain today I don't encounter the same. 

I'll also close this issue given that there doesn't seem to be any action required on the plugin side. If however you run into any further errors be sure to reach out. Thank you.
