### ISSUE TITLE
Provide Site Kit by Google Dev Settings Plugin in WordPress.org Repository, or Composer Package, or Git Repository

### ISSUE THREAD

**Issue by timnolte** [google/site-kit-wp#4732]
## Feature Description

When we want to install the Site Kit by Google Dev Settings plugin, using Composer, we have no source other than a download link on the [Site Kit website](https://sitekit.withgoogle.com/documentation/using-site-kit-on-a-staging-environment/). If we could at the very least get this in a Git repository that we can pull from via Composer, or ideally published to the WordPress.org repository it would be much easier to get this installed. Currently it's a very manual process. There is also no place to really report issues specifically with this add-on, or even contribute to it since the code doesn't even exist in a Git repository.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
Many thanks for your suggestion @timnolte. I'll check this with the team and report back to you here. 

In the meantime if you have any queries in relation to setting up Site Kit on a staging environment, you can always reach out to us in the WordPress support forums.

**Comment by jamesozzie** [comment]
Hi @timnolte, 

Thanks again for your suggestion. As it turns out our team did have a discussion on this and at this time a separate repository for the helper plugin isn’t in our plans. However, you can reference the zip file while using Composer, or indeed add it to an individual repository if you wish. 

I’ll mark this issue as resolved as it’s not a request we’ll be moving forward with at this time, but if you have additional feature requests, feel free to add them as a new issue, and if you have other questions about Site Kit, you can always get in touch with on [our support forum](https://wordpress.org/support/plugin/google-site-kit/).
