### ISSUE TITLE
Add AdSense site status to Site Health information

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4757]
Currently, only the AdSense account status is surfaced in Site Kit's Site Health information. This issue is about also surfacing the current site status, which is especially relevant in relation to the upcoming enhanced AdSense setup flow.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense module should expose an additional value in Site Health:
    * Identifier: `adsense_site_status`
    * Label: `AdSense site status`
    * Value should be the value of the `siteStatus` module setting

## Implementation Brief
* Using `includes/Modules/AdSense.php`,
	* Update `get_debug_fields`,
		* Add the another property to the `fields` array, having `adsense_site_status` as key and the value should be an array with the following keys:
			* `label` set as per the AC.
			* `value` set to the `$settings['siteStatus']`.

### Test Coverage
* No new tests to be added.

## QA Brief

* In the WP Admin menu, go to Tools -> Site Health. Click on the Info tab on the page. In the Google Site Kit accordion:
  - If AdSense is connected, ensure that the new setting is added as per AC.
  - If AdSense is not connected, the AdSense setting above should not be displayed (nor any other AdSense info).

## Changelog entry

* Add AdSense site status to Site Kit's Site Health output.

**Comment by eugene-manuilov** [comment]
@asvinb, it should be defined in the AdSense class, the same way how we define the `adsense_account_status` property: https://github.com/google/site-kit-wp/blob/b9cd7148099cce10a6bb9362779a466d3bace9a5/includes/Modules/AdSense.php#L168-L171

So, we don't need to modify the `Debug_Data` class. Could you please update your IB?

**Comment by asvinb** [comment]
Thanks @eugene-manuilov , definitely simpler 😁 IB has been updated.

**Comment by eugene-manuilov** [comment]
Thanks, @asvinb. IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `AdSense site status` is now included in the Site Kit site health information. 

![image](https://user-images.githubusercontent.com/73545194/154915036-edb9128d-2376-4406-b24c-657cba26d256.png)

- Tested this with the different AdSense statuses, i.e. disapproved.  The `AdSense site status` still appears but 'None' was selected instead of 'added'. 

![image](https://user-images.githubusercontent.com/73545194/154915963-34ada5b8-f9e5-418c-b9ab-ef1526739134.png)

- The AdSense data does not appear when the module is not connected.

**Comment by jamesozzie** [comment]
@wpdarren Just to confirm, the "AdSense site status" will appear as "none" in both cases below?
- If a site has not yet been added
- If a site was not approved

**Comment by wpdarren** [comment]
@jamesozzie Yes, this is correct. I also noticed if the site is pending then the site status is 'added'.  Do we have a list of the different statuses? I'd like to run through them because it doesn't mention the different statuses in the AC/IB.

![image](https://user-images.githubusercontent.com/73545194/154958457-979e2461-4022-4832-bfca-3ba9f7c3edee.png)

**Comment by jamesozzie** [comment]
@wpdarren Looking at the [AdSense Management API](https://developers.google.com/adsense/management/reference/rest/v2/accounts.sites#state) I can see the below:

- REQUIRES_REVIEW | The site hasn't been checked yet.
- GETTING_READY | Running some checks on the site. This usually takes a few days, but in some cases can take up to 2 weeks.
- READY | The site is ready to show ads.
- NEEDS_ATTENTION | Publisher needs to fix some issues before the site is ready to show ads.

Would that be what you're looking for?
