### ISSUE TITLE
Adsense is not working for me

### ISSUE THREAD

**Issue by ikymbo** [google/site-kit-wp#477]
## Bug Description

After connecting my adsense account, when I try to visualize the information (the statistics) it loads for a moment, then the screen goes blank ...

**images:** 

https://i.imgur.com/f8ioobe.png
https://i.imgur.com/jjkZ31H.png

## Additional Context

 - PHP Version: 7.2.21
 - OS: Windows
 - Browser chrome
 - Plugin Version 1.0.0-beta.1.0.5

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@ikymbo Can you please attempt the steps below in order to get Site Kit connected:
1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate any caching plugins you might have active
3. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png).

If the above fails to resolve your issue can you please share the following:
- Any [console errors](https://i.imgur.com/KyLAzgH.png) that appear
- Your WordPress [Site Health information](https://i.imgur.com/Rtkmsba.png)
- Any security plugins or software in use (ModSecurity, iThemes, WordFence etc)

**Comment by jamesozzie** [comment]
@ikymbo Have you been able to successfully connect Site Kit by following the previous suggested steps?
