### ISSUE TITLE
Expose shared ownership modules to the client

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4790]
## Feature Description

[Shared ownership modules](https://docs.google.com/document/d/19OtWe7jXKC6dIUfs6J4gDrXujHgCuXnksxBM1uUWmOQ/edit#heading=h.mei1mnj9uwgh) are modules that are manageable by all admins (previously known as "all admin modules").

This subset of modules are shareable modules that do not have a specific "owned entity" (e.g. an Analytics property) but instead are relevant for the site as a whole.

Currently these modules are only PageSpeed Insights, and Idea Hub, but more could be added in the future.

These modules need to be made available to the client along with other data from the server relevant for dashboard sharing. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The [`googlesitekit-dashboard-sharing-data` script data](https://github.com/google/site-kit-wp/issues/4473) should be extended to include a new `sharedOwnershipModules` property as a list of qualifying module slugs (`string[]`)
* For now, a shared ownership module is a [shareable module](https://docs.google.com/document/d/19OtWe7jXKC6dIUfs6J4gDrXujHgCuXnksxBM1uUWmOQ/edit#heading=h.j8mstfogtglx) that does not implement the `Module_With_Service_Entity` interface. Currently, at most this would only include PageSpeed Insights and Idea Hub, and at a minimum be an empty list (mostly due to limitations applied by `is_shareable` which requires the module is connected)

## Implementation Brief

- In `Modules.php`, create a new method `get_shared_ownership_modules` which filters the list returned by `get_shareable_modules()` and checks if each module is **not** an `instanceof Module_With_Service_Entity`.
- Within the `Modules::register()` method, modify the callback method for the `googlesitekit_dashboard_sharing_data` filter hook:
    - Add a new element `sharedOwnershipModules` to the existing `$data` array. Set it to modules returned by the new `get_shared_ownership_modules()` method.

### Test Coverage

* Add a PHPUnit test to cover the new `get_shared_ownership_modules()` method. 

## QA Brief

* Enable the `dashboardSharing` feature flag
* Go to the dashboard page
* Verify that when you enter `window._googlesitekitDashboardSharingData.sharedOwnershipModules` to the browser console, you see `['pagespeed-insights']`.

## Changelog entry

* Add `sharedOwnershipModules` to Site Kit module sharing data.

**Comment by eugene-manuilov** [comment]
> * In `Modules.php`, create a new method `get_shared_ownership_modules` which filters the list returned by `get_shareable_modules()` and checks if each module is an `instanceof Module_With_Service_Entity`.

It should return modules that do not implement the `Module_With_Service_Entity` interface. So it should say: "... and checks if each module is **not** an instanceof ...".

> In `includes/Core/Assets/Assets.php` -> `get_inline_dashboard_sharing_data()`:
> * Add a new element `sharedOwnershipModules` to the existing `$inline_data` array. Set it to modules returned by the new `get_shared_ownership_modules()` method.

No need to make changes in the `Assets` class. There is a hook in the `Modules` class that we can use to add the new property to the sharing data: https://github.com/google/site-kit-wp/blob/5f3288819b42c21d0f5cbcc9c48bf8c0fdb46abc/includes/Core/Modules/Modules.php#L319-L325

**Comment by eugene-manuilov** [comment]
Also, I think that `3` is too low estimate. Let's make it `7` because phpunit tests will take time too.

**Comment by eugene-manuilov** [comment]
No worries, @jimmymadon. Thanks for updating IB. LGTM :heavy_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 


Verified:

1. When `dashboardSharing` feature flag enabled and PSI module is connected. Then on entering 
     `window._googlesitekitDashboardSharingData.sharedOwnershipModules` to the browser console, we can  
     [`pagespeed-insights`].

2. When Page speed insight module is not connected. Then getting empty array in console.

3. Also, verified https://github.com/google/site-kit-wp/issues/4473 . Now it's showing 'Page speed insight' under `sharedownershipmodules`.

4. Because 'Idea Hub' is also shareable module. That's why verified same for the idea hub module also. When Idea hub module is connected then we can see [ `idea-hub`] in console.

<details>

Screenshot 1
![image](https://user-images.githubusercontent.com/94359491/156765559-676582b4-7460-4a6b-8862-34ac45917861.png)

Screenshot 2
![image](https://user-images.githubusercontent.com/94359491/156765599-cb495ad2-fb20-424b-99a8-9cd192cdf737.png)

Screenshot 3
![image](https://user-images.githubusercontent.com/94359491/156765633-24f77c17-04a6-49e7-a60e-a3ea4bf933d3.png)

Screenshot 4
![image](https://user-images.githubusercontent.com/94359491/156766319-2b46eccf-5268-41b8-a339-bb2a87a72d1d.png)
![image](https://user-images.githubusercontent.com/94359491/156766356-cfc5b911-48f8-4439-ba2a-8757151db945.png)


</details>
