### ISSUE TITLE
Bounce rate statistics: Modify "up" arrow colour when positive (from red to green)  

### ISSUE THREAD

**Issue by WebFactoryLtd** [google/site-kit-wp#481]
## Bug Description

The change in bounce rate percentage is calculated correctly, but the arrow beside it, that should indicate a good or bad movement, is inverted.

## Steps to reproduce

Open Analytics in Site Kit.

## Screenshots

![image](https://user-images.githubusercontent.com/1980388/64063826-eae9d900-cbf9-11e9-8503-1500681ccd89.png)

## Additional Context

I've double-checked the numbers in GA and it's all good. So the only thing to fix is the arrow. It should be green and pointing downward. As clearly shown in the screenshot my bounce rate dropped. So it's good, should be green :)

![GKeMYxwHG9n](https://user-images.githubusercontent.com/41326532/64101764-784a3c00-cd66-11e9-8835-613f38cd2750.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the trend shows that bounce rate is decreasing, display a downward-pointing arrow in green colour. 
* When the trend shows that bounce rate is increasing, display an upward pointing arrow in red colour. 
(currently, exactly the opposite is happening)

## Implementation Brief

<details>
<summary>Simplest change</summary>

* Update the `DataBlock` component with a new boolean `invertChange` prop (default `false`)
* Use `invertChange` internally in place of `reverseArrowDirection`
* When `invertChange` is truthy, multiply the provided `change` prop by `-1` to make a positive change negative, and vice-versa
* Remove the old `reverseArrowDirection` prop as it is only used for this purpose (bounce rate specifically)
* Document why this is done this way in the `DataBlock` component

</details>

Better change

* Create a new `<ChangeArrow>` component to replace usage of these svg sprites and provide more control
* Render [`<svg>` for an up arrow](https://github.com/google/site-kit-wp/blob/develop/assets/svg/arrow-positive.svg) directly to allow for styling via CSS
    - The path fill can inherit its color from `currentColor` rather than any specific value
* Accept a `direction` prop - `up` or `down`
    - Add a `arrow-pointing-${ direction }` class accordingly  
    For downward arrows, add a CSS class to rotate it `180 deg`
    - Add a class to apply the color based on the direction (by default)
* Accept an `invertColor` prop to apply the opposite color class based on the `direction`
* Update usage of `arrow-positive` and `arrow-negative` svg if others exist outside of `DataBlock` to use new component
* Rename `DataBlock.props.reverseArrowDirection` to `invertChangeColor` to be passed to the new inner `ChangeArrow` component's `invertColor` prop

## Changelog entry

* Fix incorrect change arrow direction and color on "inverted" properties like bounce rate.

**Comment by aaemnnosttv** [comment]
This appears to be correct now, is it not?

![image](https://user-images.githubusercontent.com/1621608/73342008-6d98c200-4286-11ea-8472-1ae5ca7ad478.png)

**Comment by aaemnnosttv** [comment]
Nevermind, the large number is the average. After looking at the actual data I can confirm this is incorrect.

**Comment by felixarntz** [comment]
@aaemnnosttv I don't think the IB table is correct:

* The arrow direction should always match whether the change is positive or negative. E.g. if +50%, show upward arrow, regardless of whether inversed or not.
* The color is the only thing that should change: If inversed, an upward arrow should be red, and a downward arrow should be green.

As such, maybe we should have `inverseColor` instead.

**Comment by aaemnnosttv** [comment]
You're right, good catch @felixarntz! As for the prop name, I think `invertChange` or `invertValue` may be a bit more apt as it's more of an inversion of the logic as to what is good and bad rather than color specifically. The only thing we need to do in this case is to multiply the provided `value` by `-1` and the color will change, but that's more of an implementation detail. Color could be represented by a 👍 / 👎 , etc. In the end the prop name isn't all that important, just sharing my thoughts. I'll update the IB.

**Comment by felixarntz** [comment]
@aaemnnosttv I'm not sure about multiplying the change with `-1`, wouldn't this result in both the arrow direction and the color to be inverted? Only the color should be inverted.

**Comment by aaemnnosttv** [comment]
@felixarntz digging into this a bit more, the implementation is a bit odd. There are 2 separate svgs used for the arrows; one for [positive](https://github.com/google/site-kit-wp/blob/develop/assets/svg/arrow-positive.svg) and one for [negative](https://github.com/google/site-kit-wp/blob/develop/assets/svg/arrow-negative.svg) which include the color and the direction in the svg itself. The current reverse arrow direction prop then adds a class to rotate the arrow by 180 deg using css.

The idea of multiplying by `-1` was something I found that solved the problem when looking into it [initially](https://github.com/google/site-kit-wp/issues/481#issuecomment-530738923) (as the code is now). So for bounce rate specifically, multiplying the change makes a positive change (increase - bad) negative (red pointing down) and then the added prop reverses the direction making it point up which is correct (hence the confusion).

Ideally, we would only have a single arrow svg which pointed up or down based the change being positive or negative using css for the direction. The color of the arrow should also be determined by CSS by styling the fill of the svg's `path` element. Given these changes, a single `invertColor` prop makes sense and no multiplication or reversal of the arrow direction is necessary.

However, since the svgs are implemented as a sprite, we can't apply styles to the svg itself in this way. For this reason, the invert prop (while replacing the old reverse direction prop) needs to both invert direction _and_ the change value to achieve the desired result (a negative/red arrow reversed to point up, or a positive/green arrow reversed to point down).

I hope that makes more sense now. I'll update the IB.

**Comment by felixarntz** [comment]
@aaemnnosttv Oh thanks for clarifying! That existing implementation seems a bit odd indeed.

Let's go with your "Better change" variant - I'll move this to the estimate column so you can confirm/adjust the estimate based on that implementation.

IB ✅

**Comment by aaemnnosttv** [comment]
Sounds good. I'll keep it as-is. One thing I forgot to mention is that we'll still need a prop of some kind on `DataBlock` to pass through to the new component. Perhaps an `invertChangeColor` prop? I'll add that to the IB 👍

**Comment by felixarntz** [comment]
@aaemnnosttv 
> Sounds good. I'll keep it as-is. One thing I forgot to mention is that we'll still need a prop of some kind on `DataBlock` to pass through to the new component. Perhaps an `invertChangeColor` prop? I'll add that to the IB 👍

SGTM

**Comment by cole10up** [comment]
I'm not sure this is fixed. See below. I'm seeing a decrease from month to month yet the arrow shows

**Comment by aaemnnosttv** [comment]
Good catch @cole10up , there was indeed a bug in the way the arrow direction was being set. There is a PR to fix this now in #1119. Using this branch you can see that the arrow is pointing correctly now

![image](https://user-images.githubusercontent.com/1621608/74233259-042ba100-4cd3-11ea-93b4-23a321cd458a.png)

> Also noting the X axis showing multiples of the same day with different values
Another note, (see 2nd shot) both lines are showing the same month

Thanks for mentioning these. These are unrelated to the changes introduced here but should be further investigated. Can you please open a new issue for these?
