### ISSUE TITLE
Google sitekit Does not showing any data

### ISSUE THREAD

**Issue by Idealcamper1** [google/site-kit-wp#482]
I added google site kit but it does not show any data. All the fill are blank.

**Comment by jamesozzie** [comment]
@Idealcamper1 Can you please attempt the steps below in order to get Site Kit connected:
1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate any caching plugins you might have active
3. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png).

If the above fails to resolve your issue can you please share the following:
- Any [console errors](https://i.imgur.com/KyLAzgH.png) that appear
- Your WordPress [Site Health information](https://i.imgur.com/Rtkmsba.png)
- Any security plugins or software in use (ModSecurity, iThemes, WordFence etc)

**Comment by jamesozzie** [comment]
@Idealcamper1 Did you have any success getting Site Kit connected?

**Comment by Idealcamper1** [comment]
Its really a great plugin
