### ISSUE TITLE
Admin Bar briefly shows the wrong layout when there is no data for the page.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#4839]
## Bug Description

When there is no data for a page, the first time the Admin Bar app is shown it briefly displays the wrong layout. The correct layout is then shown. See screenshots / capture below.

Subsequent views show the correct layout straight away.

It's possible to reset the behaviour by deleting the cached analytics response from Session Storage (as seen in the screen capture).

## Steps to reproduce

1. Visit a new WP page which there is no Analytics data for.
2. Hover to display the SK Admin Bar app.
3. The empty data layout should briefly appear, followed by the correct layout.

## Screenshots

**This is what is briefly displayed:**

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/50671bec-7d69-4fb7-8448-157a8257af34)

**Then the correct view is shown:**

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/25e0e65c-dbc7-4f6f-b1f5-7728603a85a1)

<details>
	<summary>Screen capture</summary>
	
![bug-admin-bar-first-page-view](https://user-images.githubusercontent.com/18395600/153625483-1729c936-d6a7-4d83-b0d1-20ec6818874f.gif)

</details>

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The logic for what widgets are displayed in the admin bar app should be refined as follows:

**Search Console active only**
* If gathering data, show the standard Gathering Data CTA in place of the two SC widgets

**Search Console + Analytics**
* If both modules are gathering data, show the full-width zero state message (`AdminBarZeroData`)
	- This is the only condition where it should be shown
* Otherwise, either module can show a single gathering data CTA in place of its two widgets

**Gathering Data**
* The gathering data state should be determined by the `isGatheringData` selector only
	- Use of `isZeroReport` in the admin bar widgets should be removed
* If not gathering data, zero data should be displayed as on the dashboard as appropriate zero values in all cases

**Loading**
* The loading states of the widgets should be synchronized such that when Analytics is active, all the widgets should remain in their loading states until the gathering data state is known.
	- If the gathering state of SC is loading, Analytics widgets should remain loading and vice versa
	- This is to avoid a single module's gathering CTA to flicker before they are all replaced with the full-width gathering component
	- This is only relevant for the gathering states, it _does not_ need to synchronize loading of all widgets such that all data boxes show at the same time

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks for raising this @techanvil. I'm not sure that this is necessarily a bug as we don't know that there is zero data until the data is loaded. What would you imagine is the correct layout in this state?

**Comment by aaemnnosttv** [comment]
@techanvil this is similar to how we show things on the SK dashboard where individual widgets have their own loading state (using `PreviewBlock`) and if zero data, this is selectable elsewhere using the `getWidgetState` selector. We don't have a widget state for loading though as these states are currently just for aggregating adjacent widgets with the same "special" (zero/activation CTA) states.

Part of the problem here is that you only have SC active: the report query loads quite quickly but the CTA for Analytics is shown immediately but then the whole thing is replaced by the zero data state which is a bit jarring.

I would suggest we do the following:
* If Analytics isn't active (as shown above) and SC is zero data, show the usual gathering data CTA in place of the two SC widgets as we would normally on the dashboard, keeping the Analytics CTA in place the whole time.
* If Analytics is active, synchronize the loading states (not sure exactly how to best do this but we do this elsewhere I believe) so that all widgets remain in the loading state until all data are loaded
	* If only SC or Analytics are zero data, show the zero report CTA for that module's widgets respectively (1 per module, spanning both data blocks just like the activation CTA)
	* If both are zero data, show the full-width zero state as shown above

How does that sound?

**Comment by aaemnnosttv** [comment]
@marrrmarrr what do you think about the suggestion above? The current approach is consistent with how we do things on the dashboard, but we could probably enhance the experience in the Admin bar due to the fixed set of widgets (unlike the dashboard where things need to be more flexible). Thoughts?

**Comment by techanvil** [comment]
Thanks @aaemnnosttv, what you've suggested sounds more in keeping with the general UX than my spinner suggestion :+1:

**Comment by marrrmarrr** [comment]
Thanks @techanvil for raising this and @aaemnnosttv for the detailed outline of a possible solution. 
Synchronising the loading states SG! One thing that would be good to adjust as well is the difference in height of the blue GA CTA and the SC stats.  

I think it would also be good to distinguish b/w "gathering data" and "no traffic" for SC. (We've done [some work](https://www.figma.com/file/lPdnmgVoPqOEO82AMle9gH/Zero-State?node-id=435%3A1677) on this for the dashboard, which is right now aimed to roll out in ~April)

**Comment by eclarke1** [comment]
@aaemnnosttv @techanvil this issue is currently in Sprint 69, however what are next steps here please? Can this move to AC? 
cc @FlicHollis

**Comment by aaemnnosttv** [comment]
@marrrmarrr @felixarntz ACs have been added – thoughts?

**Comment by felixarntz** [comment]
Following up on our discussion during the standup call: While this is a bug, we don't need to bother fixing it at this point, since it's rather minor and the zero data states work will supersede this and is going to launch soon.

In the zero data states implementation, it should be ensured though that the Analytics CTA always appears if the module isn't set up, i.e. the original bug report here is still valid and should apply to the new implementation. In that new implementation, that whole "No data available yet" replacement content should no longer be used in any circumstance, we should always see the regular admin bar widgets with their "gathering" or "zero" state UI. cc @jimmymadon @aaemnnosttv @techanvil
