### ISSUE TITLE
Site Kit show blank page after javascript error

### ISSUE THREAD

**Issue by tottaz** [google/site-kit-wp#485]
## Bug Description

I have installed Site Kit, when I try configure I just get a blank page. I had this previously working, with the current theme I have. Since the problem occurred, I have uninstalled Site Kit and installed and activated again. Same error as show below. 

Uncaught TypeError: Cannot read property 'call' of undefined
    at l (googlesitekit-dashboard-splash.js:1)
    at Object.<anonymous> (vendor.js:258)
    at Object.<anonymous> (vendor.js:258)
    at l (googlesitekit-dashboard-splash.js:1)
    at Object.18 (commons.js:1)
    at l (googlesitekit-dashboard-splash.js:1)
    at Object.24 (commons.js:1)
    at l (googlesitekit-dashboard-splash.js:1)
    at Object.23 (commons.js:1)
    at l (googlesitekit-dashboard-splash.js:1)

Can not access Site Kit due to javascript error.

## Steps to reproduce

1. Go to Site Kit

Shows a blank page.

## Additional Context

 - PHP Version: 7.3.6
 - OS: [e.g. iOS] CentOS
 - Browser [e.g. chrome, safari] Chrome, Brave, Firefox
 - Plugin Version [e.g. 22] Version 1.0.0-beta.1.0.5 Site Kit

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Hi there

Thanks for your report! Which version of WordPress are you using and which other plugins are active? Mind sharing your Site Health info with the details about that?

**Comment by jamesozzie** [comment]
@tottaz Did you have a chance to re-attempt setup? If you are encountering the same issue you can attempt the following:
1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate any caching plugin you might have active
3. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png).

If the above fails to resolve your issue can you please share of the following:
- Your WordPress [Site Health information](https://i.imgur.com/Rtkmsba.png)
- Any changes to your site (plugin updates/installations) since it last worked

**Comment by jamesozzie** [comment]
@tottaz Did you have any luck getting Site Kit connected?
