### ISSUE TITLE
Gap between AdSense CTA and WordPress footer on unified dashboard

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4904]
## Bug Description

This is minor but on Unified Dashboard, underneath the AdSense CTA, there's a large gap between the widget and WordPress footer. Would be good to see the widget appear with no gap, like it does when you have AdSense connected. 

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/0b6d3c76-e28f-4b2a-a6f7-e290c2b94af8)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@wpdarren this was added intentionally in https://github.com/google/site-kit-wp/issues/4490 and is necessary at the moment for the section to load when scrolling to manually due to the logic for lazy-loading relative to the area's position in the viewport.

It's worth adding that the gap only fills space needed for the section to reach the top of the content area near the header. When the widgets are active the area is taller so less/no gap is added.

Closing this out for now but perhaps something we can address in the future.
