### ISSUE TITLE
Minor UI change for Monetization CTR on Unified Dashboard

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4937]
## Bug Description

A very minor UI change - on Unified Dashboard, the Monetization CTR has a title `Connect Service` which is styled differently than other connect service CTRs.  As you can see in the screenshot below, the title is in upper case and slightly smaller font size.  Would be good to have it consistent.  

![image](https://user-images.githubusercontent.com/73545194/157870123-5a1eef31-f1f8-47d5-83c0-c6df562e26fa.png)

![image](https://user-images.githubusercontent.com/73545194/157870377-16bff00a-5173-4a97-8520-c2bec1b3e7fb.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The treatment of the "Connect Service" text/header of the `AdSenseConnectCTA` should be consistent with the similar interface for module setup, particularly:
    * Font size and case
    * Margin
    * Letter spacing

<details>
<summary>Screenshots</summary>

**Current**
![image](https://user-images.githubusercontent.com/1621608/160202812-4d95a7c1-38bb-42eb-b182-b3eace1e228d.png)

**Target**
![image](https://user-images.githubusercontent.com/1621608/160202870-24a986d7-59c0-4ba4-9a40-3416b5c901b9.png)

Note the lack of margin-top here as well

</details>

## Implementation Brief

* In `assets/sass/components/setup/_googlesitekit-setup.scss`.
    * Define `.googlesitekit-setup__wrapper` class inside the `.googlesitekit-plugin` class but outside the `.googlesitekit-setup` class. 
    * Move the  `.googlesitekit-setup__intro-title` class with all its properties from `.googlesitekit-setup` to the newly added `.googlesitekit-setup__wrapper` class.

### Test Coverage

* VRTs may need to be updated. 

## QA Brief

* QAing this would require checking the `Modules -> AdSense -> Widgets -> AdSenseConnectCTA -> Ready` story and making sure the "Connect Service" heading looks like the other similar CTAs.
* You can use the screenshots in AC for reference.

## Changelog entry

* N/A

**Comment by kuasha420** [comment]
@asvinb I have added the IB for it. But I was wondering whether we could just add a `.googlesitekit-setup` wrapper to the `AdSenseConnectCTA` instead. Would you kindly review it? 

Cheers.

**Comment by asvinb** [comment]
@kuasha420 We could certainly do that, however `.googlesitekit-setup` adds an extra `10px` padding within the widget and will cause some visual regressions. What we can do instead is add `.googlesitekit-setup__wrapper` but without the `.googlesitekit-setup` prefix within `assets/sass/components/setup/_googlesitekit-setup.scss` so that we have `.googlesitekit-plugin .googlesitekit-setup__wrapper` (we can leave the existing `.googlesitekit-setup__wrapper` in case this can cause some visual regressions). Then we **move** `.googlesitekit-setup__intro-title` within `.googlesitekit-plugin .googlesitekit-setup__wrapper`. This will not cause any regressions. I checked and we are only using `.googlesitekit-setup__intro-title` in 2 places and making that change will not affect anything.

**Comment by asvinb** [comment]
IB ✅

**Comment by eclarke1** [comment]
@kuasha420 please could you add an estimate to this one, thanks

**Comment by kuasha420** [comment]
@eclarke1 Oops, done!
