### ISSUE TITLE
Behaviour of Legends loading animation on Pie chart with Zero Data

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4938]
## Bug Description

While testing #4675 I noticed weird behaviour when you are viewing the pie chart on the All Traffic widget for zero data. 

As you can see from the screencast, when you click on the location and device tabs, the legends loading animation appears and then disappears.  This does not happen when you click back on the channels tab. 

https://user-images.githubusercontent.com/73545194/157873565-ba8d0096-a24b-4239-a0fb-15ce07fd74cc.mp4

When the pie chart loads, I would not expect the legends loading animation to appear when clicking through the tabs. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If there is no traffic data for a particular site, don't display loading states for elements which ultimately will not be rendered (like the pie chart legend). 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
@felixarntz I've added ACs for this issue, have a look if they are detailed enough and if it LGTY let's move it to IB.

**Comment by felixarntz** [comment]
@marrrmarrr Hmm, I'm not sure this is possible unfortunately. We don't know whether there is traffic before the data is loaded. Because this is a matter of when which API request has completed, it would mean that for sites with no data sometimes we show the loading state for the legend and sometimes we don't - it would be completely random.

The only way to avoid that would be to run those requests about zero data first before even showing the loading state, but that would mean we would need to have some other even higher-level variant of a loading state for the entire page, which would be bad UX.

Maybe we can somehow store whether a service has zero or is gathering data on the server-side. While we originally decided to not cache any results on the server, this would just be simple booleans for whether there is data or not, so there shouldn't be any concerns with storing that data in the WP database.

Let's think about this a bit more.

**Comment by eclarke1** [comment]
@marrrmarrr @felixarntz could we kindly ask for further thoughts here so we can agree whether this is required for launch? Currently we have this in Sprint 72 starting next week so if it is needed, would be good to define it soon please
cc @FlicHollis

**Comment by aaemnnosttv** [comment]
@felixarntz @marrrmarrr per our conversation about this earlier this week, I believe we decided not to implement additional server-side calls+storage for service gathering data states as gathering data is somewhat of an edge case that probably isn't worth introducing additional complexity around for such a minimal benefit (if any at all).

I would opt for closing this and leaving it as-is and optimizing the user experience for the most common case (having data). If there are minor sub-optimal effects for edge cases like this, I think that's an acceptable compromise in the interest of keeping things simple internally.
