### ISSUE TITLE
Blue Box CTA shows to notify user to complete Analytics set up if user do not complete or cancel Analytics set up. 

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#4966]
## Feature Description

If user cancels or does not complete the Analytics set up then "Blue box CTA" display to notify user about completing the Analytics set up. As we are removing 'Blue Box widget' and implementing new designs on other places. I think this should be change too.

Steps: 
1. Using the tester plugin, force the 'gathering data' state or 'zero' data state.
2. Activate the "zeroDataStates" feature flag
3. Go to Site Kit Dashboard.
4. Click on set up Analytics.
5. Cancel or do not complete Analytics module set up.
6. See "Blue box widget' on Main Dashboard, Entity dashboard and WP dashboard.

## Screenshots

Main Dashboard

![image](https://user-images.githubusercontent.com/94359491/159644201-62a02925-e565-4ce3-bbdb-3863e152af31.png)

Entity Dashboard

![image](https://user-images.githubusercontent.com/94359491/159644112-0503995d-8201-4af9-99a5-ea8428f472e3.png)

WP Dashboard 
![image](https://user-images.githubusercontent.com/94359491/159644276-fb08a6ad-2b47-4a80-9ea6-318bc8b06a1e.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All "Complete module activation" CTAs for Analytics should look exactly the same as the respective new "Activate Analytics" CTA, with the only difference being that the CTA button says "Complete setup".
    * Preferably, the same component should be used under the hood for the very similar UI.
* This change should happen everywhere this CTA can be present, i.e. the Site Kit dashboard, the WP dashboard widget, and the WP admin bar menu.
* Storybook for the UI in "Complete module activation" state should be added.

## Implementation Brief

- Create a new hook - `useCompleteModuleActivationCallback.js` which accepts `moduleSlug` as a parameter:
    - Move the entire logic of computing the `onCTAClick` callback from `CompleteModuleActivationCTA.js` into this new hook.
      https://github.com/google/site-kit-wp/blob/4baca515e05bddbe5dc26c6302789588d4a0d9d5/assets/js/components/CompleteModuleActivationCTA.js#L44-L61 
    - Rename the `onCTAClick` const to `completeModuleActivationCallback` and return this value. 
    - This refactor is similar to the one done in [#4694](https://github.com/google/site-kit-wp/issues/4694) which can be used as a reference. 
- Use this new hook within `CompleteModuleActivationCTA.js` to get the onCTAClick value.
- Refactor `assets/js/components/ActivateAnalyticsCTA.js` component:
    - Accept a new boolean prop, `isCompleteSetup` which is false by default.
    - Call the new `useCompleteModuleActivationCallback` hook passing `analytics` as the module slug and store it in a new variable `completeModuleActivationCallback`.
    - Add a new check: if the `isCompleteSetup` prop is `true` and if the result of `useCompleteModuleActivationCallback` is falsey, then the component should return `null`.
    - Modify the `<Button>` component: 
        - If the `isCompleteSetup` prop is `true`, the `onClick` property should be set to `completeModuleActivationCallback`.
        - If the `isCompleteSetup` prop is `true`, the button label should be set to `Complete setup` as per the AC.
- Update the following components to accept a new prop, `isCompleteSetup` and simply pass it down to the `ActivateAnalyticsCTA` component they render:
    - `assets/js/components/adminbar/AdminBarActivateAnalyticsCTA.js`
    - `assets/js/components/wp-dashboard/WPDashboardActivateAnalyticsCTA.js`
    - `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/ActivateAnalyticsCTA.js`
- In the following components, if the `zeroDataStates` feature flag is enabled, render the new corresponding AnalyticsCTAComponent (highlighted below) instead of `CompleteModuleActivationCTA`. Pass the `isCompleteSetup` prop to be true.
    - In `AdminBarWidgets` -> render `AdminBarActivateAnalyticsCTA` with `isCompleteSetup` prop as true.
    - In `WPDashboardWidgets` -> render `WPDashboardActivateAnalyticsCTA` with `isCompleteSetup` prop as true.
    - In `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js` -> render `assets/js/components/ActivateAnalyticsCTA` with `isCompleteSetup` prop as true.
- Add a new Storybook story where each of the above components are rendered in storybook, passing the `isCompleteSetup` prop as true.

### Test Coverage

* Add tests for the new `useCompleteModuleActivationCallback` hook.

## QA Brief

* With `zeroDataStates` on, verify the new `SET UP GOOGLE ANALYTICS` CTA continues to appear when Analytics is completely disconnected in the Admin Bar, WordPress Dashboard and SiteKite Dashboard.
* Click on the CTA but do not continue connecting Analytics fully (by setting up an Analytics Property). In this state, verify the points in the AC (the new `COMPLETE SETUP` CTA appears).
* Go through the above 2 points with `zeroDataStates` off to ensure the old CTAs (Blue Boxes) remain unchanged.
* Verify the new stories load correctly for [AdminBar](https://google.github.io/site-kit-wp/develop/?path=/story/views-adminbarapp-adminbarwidgets--analytics-inactive-new-complete-activation), [WPDashboard](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-wpdashboardapp-wpdashboardwidgets--ready-with-activate-analytics-cta) and [Search Console Traffic widget.](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-searchconsole-widgets-searchfunnelwidget--ready-with-complete-analytics-activation-cta)

## Changelog entry

* Update complete Analytics activation CTA for consistency with new zero data states activation CTA.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@aaemnnosttv I have passed this ticket but as @jimmymadon mentioned previously when `zeroDataStates` is disabled, the Analytics CTA does not appear on the Admin bar. It appears for a second then disappears.  This is what I see both on my test site but also on the Admin bar Story.  Would you like me to create a ticket for this, or, since we're launching ZDS soon, should we bother?  Thoughts welcome. 

![image](https://user-images.githubusercontent.com/73545194/162881987-842f148f-c7f6-4f66-a0e6-5b62e62865b9.png)

**Verified:**

With `zeroDataStates` enabled:

- The new Set up Google Analytics CTA continues to appear when Analytics is completely disconnected in the Admin Bar, WordPress Dashboard and Site Kit Dashboard.
- After cancelling connecting Analytics the new Complete Setup CTA appears.  It's styled like the Set up Google Analytics CTA but the button says Complete setup. This appears on Admin Bar, WordPress Dashboard and Site Kit Dashboard.

With `zeroDataStates` disabled:

- The old blue box Set up Google Analytics CTA appears when Analytics is completely disconnected in the Admin Bar, WordPress Dashboard and Site Kit Dashboard.
- After cancelling connecting Analytics the old blue box Complete Setup CTA appears.  This appears on WordPress Dashboard and Site Kit Dashboard. See note re. Admin Bar. 
- The new stories load correctly for [WPDashboard](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-wpdashboardapp-wpdashboardwidgets--ready-with-activate-analytics-cta) and [Search Console Traffic widget.](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-searchconsole-widgets-searchfunnelwidget--ready-with-complete-analytics-activation-cta)

**Comment by jimmymadon** [comment]
@wpdarren [This comment ](https://github.com/google/site-kit-wp/issues/4839#issuecomment-1080922385) summarises our plan to ignore the little bug above and wait for ZDS to launch which will automatically "fix" the issue.
