### ISSUE TITLE
Update wording on Analytics CTA

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#5005]
## Bug Description

This CTA appears in a few places. The colon and "install Google Analytics" should be removed so the sentence is just:

"See how many people visit your site from Search and track how you're achieving your goals."

## Screenshots

![image](https://user-images.githubusercontent.com/12189958/160863991-a07bc225-68c1-4483-a1b9-700200667311.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ActivateAnalyticsCTA` component is updated to display the following description instead the one that was previously used:

  ```
  See how many people visit your site from Search and track how you're achieving your goals.
  ```

## Implementation Brief

* Merge #5013 

### Test Coverage

* N/A

## QA Brief

* Once merged the fix should be observable here:
https://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-wpdashboardapp-wpdashboardwidgets--ready-with-activate-analytics-cta

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
IB ✅ 

(I'll merge this as well 👍🏻 )

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified :

- The ActivateAnalyticsCTA component is updated to display the following description instead of the one that was previously used:

`See how many people visit your site from Search and track how you're achieving your goals.`

- Verified for the gathering data state.
- Verified for the zero data states.
- Verified on SiteKit Dashboard, WP dashboard and WP admin Bar.

<details>

![image](https://user-images.githubusercontent.com/94359491/161250909-50da8964-6133-435b-a1cc-f1df07dde3d4.png)

![image](https://user-images.githubusercontent.com/94359491/161250956-75081c42-a85f-4557-bdef-7902d429daf3.png)

![image](https://user-images.githubusercontent.com/94359491/161250978-083520e5-5fa9-46d0-8e03-fa27834cbd9c.png)

![image](https://user-images.githubusercontent.com/94359491/161251241-8490efa7-1ed7-4301-9695-fd9c4b7c990b.png)

![image](https://user-images.githubusercontent.com/94359491/161251294-3eec965a-cb66-4151-a61f-d06a092d0e19.png)

![image](https://user-images.githubusercontent.com/94359491/161251335-a7876b99-3ec3-4728-bd00-200864abab9a.png)


</details>
