### ISSUE TITLE
Incorrect dashboard notification briefly shows before correct one is loaded

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5008]
## Bug Description

When one module (e.g. Analytics) is gathering data while the other module (e.g. Search Console) has just zero data available, the Site Kit dashboard may briefly flash the notification about the zero data module (Search Console) before showing the notification about the gathering data module (Analytics).

It is expected for the latter to have precedence, so that's all good, but we should ensure we don't show the other one first to then replace it. Instead, the components should ensure the necessary data has been loaded for both notifications to determine which one to show before showing any.

To replicate that, configure the modules as described in the first paragraph and load the Site Kit dashboard. You may see the one notification about the zero data module briefly show up before the other one takes over.

From the [bug bash asana ticket](https://app.asana.com/0/1201999381911618/1202030688961883/f)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Before showing the banner notification for either "gathering data" or "zero data", it must be ensured that _all_ relevant data affecting their conditions has been loaded (i.e. is not `undefined`).
    * It should no longer be possible for one of the two notifications to briefly pop up just to be replaced by the other one a second later (as the check determining the other one is needed only completed a bit later).

## Implementation Brief

* Add `=== undefined` checks for all "gathering data" and "zero data" `useSelect` results in `ZeroDataStateNotifications.js`, eg:

```js
if (
	analyticsGatheringData === undefined ||
	searchConsoleGatheringData === undefined ||
	analyticsHasZeroData === undefined ||
	searchConsoleHasZeroData === undefined
) {
	return null;
}
```

This ensures no notification is shown until all data is ready.

That said, it might also be worth only displaying the zero data notification if "gathering data" is `false`, given the "gathering data" scenario "takes precedence" over "zero data", so there's no sense outputting even the _component_ if gathering data is true.

### Test Coverage

* No new tests are needed.

## QA Brief

- Ensure `zeroDataStates` feature flag is enabled.
- Using the tester plugin, enable the `gathering` data state for Analytics and `zero` data state for Search Console.
- Clear the session and reload the page.
- Ensure the `zero` data state notification doesn’t pop up briefly and disappear.
- Ensure the `gathering` data state notification appears as expected.

## Changelog entry

* Fix bug that could cause the incorrect notification to briefly appear when Analytics or Search Console is gathering data.

**Comment by aaemnnosttv** [comment]
@tofumatt I was thinking it might be worth introducing a way to select `hasFinishedResolution` for `isGatheringData` (i.e. the internal report) which would apply here too since the two are very similar. There is actually a bug in the implementation because we don't use these which can cause an infinite loading state in the event of an error in those report requests (see #4542).

> That said, it might also be worth only displaying the zero data notification if "gathering data" is `false`, given the "gathering data" scenario "takes precedence" over "zero data", so there's no sense outputting even the _component_ if gathering data is true.

It's worth noting that `hasZeroData` selectors use `isGatheringData` internally so if `isGatheringData`, `hasZeroData` will also return true. Not sure checking for gathering data to be `false` first in `ZeroDataStateNotifications` would be the right check – can you elaborate on what you mean?

The IB looks good to solve the problem I think but maybe there is an additional guard worth adding in the component like you said.

**Comment by aaemnnosttv** [comment]
> So updating the component not to render both React components, as it currently does, would make sense: [`8b0be2c`/assets/js/components/notifications/ZeroDataStateNotifications.js#L100-L135](https://github.com/google/site-kit-wp/blob/8b0be2c57fbffe01acac6e929d9c617d213f1ea1/assets/js/components/notifications/ZeroDataStateNotifications.js#L100-L135)
> 
> Sure, our notifications system is "smart" enough not to show both, but it's still needless and might be confusing to a developer because the logic here isn't what we INTEND to happen.

That makes sense, I missed that it currently rendered both simultaneously (under the right conditions) so that would be good to fix as well 😄 


> Sorry, I think I'm a bit lost here. Do you mean a `hasFinishedResolution` for `isGatheringData`? I mean, we could do that instead of checking for `undefined`… but the result would be the same I think.

That is what I meant but once #4542 is done `undefined` will only mean loading so the result would be the same. Not having the internal report args is a bit problematic in a few cases but it isn't something we need to tackle as part of this issue.

IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@hussain-t  while this does pass the QAB, I decided to run through a few additional tests. 

I am assuming that if I click on the `OK, Got it!` link on the `Search Console is gathering data` notification, the `Not enough traffic yet to display stats` notification should appear next when Analytics is set to zero?   At the moment, it does not appear on the develop branch but it does on latest release (1.71.0).  

https://user-images.githubusercontent.com/73545194/162400191-a55a4e1b-7bba-4116-a8e7-9154f2658d7f.mp4

**Verified:**

- The zero data state notification doesn’t pop up briefly and disappear and the gathering data state notification appears.

**Comment by hussain-t** [comment]
Thanks, @wpdarren 👍 

@tofumatt, this is happening due to [this condition](https://github.com/google/site-kit-wp/blob/f939348e6209302592c857c3f81f197df3905410/assets/js/components/notifications/ZeroDataStateNotifications.js#L116-L117). It seems it's incorrect to have this condition since we should render both the notifications one after another if either one of the modules is in `zero` data state and other is `gathering` data state.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The zero data state notification doesn’t pop up briefly and disappear and the gathering data state notification appears.
- Confirmed the issue [reported above](https://github.com/google/site-kit-wp/issues/5008#issuecomment-1092612059) is also fixed. 
- Also checked the behaviour of the gathering notifications with search console on zero and analytics on gathering.
- Checked the notifications on small screen sizes.

https://user-images.githubusercontent.com/73545194/162450849-44079bd5-0e8e-4e09-899d-b3d8ac395a5f.mp4
