### ISSUE TITLE
Clarify proxy request error message

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5038]
When the proxy request to register the site or sync site fields fails, the plugin currently shows a generic message: _The request to the authentication proxy has failed. Please, try again later._

This message lacks any detail about the actual error that occurred, so this should be enhanced.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The error message _The request to the authentication proxy has failed. Please, try again later._ should be refined to include information about the actual error that occurred, if available:
    * _If_ there is a `WP_Error`, the message should include detail from there as follows: _The request to the authentication proxy has failed with an error: %s_
    * The placeholder should be the `WP_Error`'s error message if not empty, or its error code otherwise (as a fallback in case there's no error message).
    * In case the error is just due to the `filter_var` call, the original message can remain.

## Implementation Brief

- In `includes/Core/Authentication/Setup.php`, within the `handle_action_setup_start()` method:
    - Split out the condition that checks if `$oauth_setup_redirect` is a `WP_Error`.
    - If `$oauth_setup_redirect` is a `WP_Error`, get the error message using `WP_Error::get_error_message()` and if it is empty, get the error code `WP_Error::get_error_code()` and die with the message as per the AC.

### Test Coverage

- Add a PHPUnit test similar to `Setup_Test::test_handle_action_setup_start__syncs_site_fields()` that returns a WP_Error when a request to the Google Proxy server is made. It can be called `test_handle_action_setup_start__dies_if_proxy_server_errors()`. The logic to mock a WP_Error when an HTTP request is made can be similar to the [`AuthenticationTest::test_cron_update_remote_features__wp_erro()` method](https://github.com/google/site-kit-wp/blob/8240848c2d4aa499af87786c02cc5a343a5937b5/tests/phpunit/integration/Core/Authentication/AuthenticationTest.php#L990-L1004).

## QA Brief

- To reproduce the error that this issue enhances:
  - Disconnect SiteKit and then navigate again to the Google SiteKit Dashboard. You should be on the "Setup SiteKit" splash screen with "Sign in with Google" as the CTA. 
  - Disconnect your computer from the internet and then click the CTA (which will prevent the next immediate request being made to the proxy server). The request should fail with a WP Die / Error screen like below. Verify the error is as per the AC.
  <img width="850" alt="Screenshot 2022-05-23 at 12 28 40" src="https://user-images.githubusercontent.com/1721319/169809964-bfb9c333-7509-4c4a-ba2f-b942b012edc7.png">

## Changelog entry

* Update the setup error screen to include an error message returned from the proxy server.

**Comment by eugene-manuilov** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@jimmymadon hello! I am unable to recreate the message:

> Disconnect your computer from the internet and then click the CTA (which will prevent the next immediate request being made to the proxy server). The request should fail with a WP Die / Error screen like below. Verify the error is as per the AC.

I tried two ways, 1) disconnecting my internet connection and 2) going to the network tab in chrome  and selecting offline in the throttling setting.  All that happens is when I click on the CTA on the splash screen, it just changes to the no internet message on Chrome. 
 
`No Internet Try: Checking the network cables, modem and router. Reconnecting to Wi-Fi ERR_INTERNET_DISCONNECTED`

Any other ideas on how I can generate this message to QA? 🤔

**Comment by wpdarren** [comment]
@mohitwp please could you have a look at this ticket since it is non-dashboard sharing. Read the QAB, and see if you can recreate the error message.

**Comment by mohitwp** [comment]
@wpdarren I tried to replicate issue following the steps mentioned under QAB.
I'm also redirecting to 'No internet page' after clicking on 'Sign in with Google' button. Tried on both 'revoke site kit' and 'setup sitekit' splash screen. I'm not getting any error as per AC.

**Comment by jimmymadon** [comment]
@wpdarren I tried this again yesterday and was able to get the error after disabling the Wi-fi on my Mac and then immediately clicking on the CTA. For some reason, Chrome does not think I am offline when I do this. However, when I use the throttle feature in Chrome Dev Tools, it also shows me the "No Internet" Chrome Error page. At this stage, I think we could add the QA:Eng label and let an engineer test this by preventing a successful request using a Firewall rule / Proxy software. Even when using Proxyman, completely blocking the request causes a "Connection closed" Chrome error instead of the WP Error. Mocking a wp_error as a response to the request here is something I have already done locally - so not sure if doing this in QA:Eng is the right way to proceed.
@aaemnnosttv Any ideas from the top of your head on how else to trigger an error here?

**Comment by aaemnnosttv** [comment]
@jimmymadon the easiest way would be to use a filter to override the request to the proxy but this is only possible for requests that are made via WP HTTP (i.e. `Google_Proxy::request`) using https://developer.wordpress.org/reference/hooks/pre_http_request/. This covers almost all requests to the proxy except those that are done by the Google `Client` which uses Guzzle internally. So we should be able to create a mini plugin to force an error for requests to the proxy.

One option that just came to mind would be to use the `WP_HTTP_BLOCK_EXTERNAL` constant which will block all HTTP requests and return a `WP_Error`. This can be set in your wp-config with `define( 'WP_HTTP_BLOCK_EXTERNAL', true );`. You may need to setup SK first but this is the easiest way to force a WP Error for a request 👍  This constant also will not affect dashboard requests, again because the client uses Guzzle.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@jimmymadon @aaemnnosttv going through changing the wp-config file with `define( 'WP_HTTP_BLOCK_EXTERNAL', true );` I do see a similar error message but not as per the screenshot in the QAB. 

![image](https://user-images.githubusercontent.com/73545194/174061839-4132788d-5898-4ce5-907a-85ffc4be218a.png)

To get this I had to disconnect Site Kit and get to the splash screen and then sign in with Google. 

I was unable to trigger any error while Site Kit was connected.

**Comment by jimmymadon** [comment]
@wpdarren It is expected to have the error message change to whatever is returned in the message from WP_Error which now is "user blocking requests". It does pass the AC. I do not get the Query Monitor message in my tests as I do not have that plugin. So this should be sufficient.
<img width="1435" alt="Screenshot 2022-06-16 at 13 27 06" src="https://user-images.githubusercontent.com/1721319/174069954-5c96aaf8-dc43-4b60-84c9-fc4177b03720.png">

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Going through changing the wp-config file with `define( 'WP_HTTP_BLOCK_EXTERNAL', true );` I do see a similar error message as per the screenshot in the QAB. 

![image](https://user-images.githubusercontent.com/73545194/174061839-4132788d-5898-4ce5-907a-85ffc4be218a.png)
