### ISSUE TITLE
While search console and analytics is in zero data state.  'Total Impression', 'Total clicks', 'Total impressions' or 'Unique visitors from search' from the SearchFunnel widget are clickable.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#5057]
## Bug Description

While search console and analytics is in zero data state.  'Total Impression', 'Total clicks', 'Total impressions' or 'Unique visitors from search' from the SearchFunnel widget are clickable.
We have disable click, hover and tabbed functionality on these data blocks when analytics is in gatheing state through this PR : https://github.com/google/site-kit-wp/issues/4967 .
I wonder we should implement same when analytcis and search console are in zero data state. 

## Steps to reproduce

1. Create a new site which will have default gathering state.
2. Activate the "zeroDataStates" feature flag
3. Go to Site Kit Dashboard.
4. Set up Analytics.
5. Force the zero data state for analytics and search console..
6. Total Impression', 'Total clicks', 'Total impressions' or 'Unique visitors from search' from the SearchFunnel widget are clickable.

## Screenshots

![image](https://user-images.githubusercontent.com/94359491/162396890-5cd5036f-0588-4198-8347-06188f699227.png)

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
@marrrmarrr @aaemnnosttv I'm not sure about whether this is really a problem. It makes sense to me to not have these clickable when gathering data, however when it's showing all 0s, it's still a "regular" or "valid" state, so I think it would be weird to disallow clicking the tabs.

For example, it could also be that last month the site had data and now it has zero, which indicates to me we should still treat this data as completely "normal" (other than having a message just to tell the user why it could be that they have zero data).

My vote would be to close this.

**Comment by aaemnnosttv** [comment]
@felixarntz I agree, we shouldn't disable them just because they're zero, even if all the previous data is also zero. We only disable them in the gathering state to prevent things breaking due to the alternate interface but also that is a much more well-defined state where we know there really is nothing to show yet.

There is also the case where the value in the data block is `0`, but the previous month had data in which case those values are exposed on the chart when you hover. This is technically not a zero report for that reason but I don't think we should treat a true all zero report any differently. The zero report utilities are really more of a tool to catch a false positive gathering data state now, I don't think we have much use for them otherwise.

I also vote to close this unless @marrrmarrr has any objections?

**Comment by marrrmarrr** [comment]
+1, we can keep this as is.
