### ISSUE TITLE
Include a notice to inform users that some modules have been deactivated, via the googlesitekit_available_modules filter

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5059]
## Bug Description

Since we've added the _**googlesitekit_available_modules**_ filter (https://github.com/google/site-kit-wp/issues/3993) some administrators may wish to deactivate the connection of some modules. With this there is a likelihood that users will open support topics regarding not being able to connect some services, with no in-product notice regarding these modules unavailability for site administrators - although we do remove such unavailable modules from a users Site Health information, [under the "Active modules" flag](https://i.imgur.com/WaOfweV.png). 

Considering adding a notice that some modules may have been deactivated by another administrator, to the below screen:

![image](https://user-images.githubusercontent.com/41326532/162432534-1b00e712-1c47-4ca4-94e1-764afd0d85c3.png)

Video showing experience if only Search Console is available, with all others deactivated via the below:

```
add_filter(
	'googlesitekit_available_modules',
	function( $modules ) {
		return array( 'search-console' );
	}
);
```

https://user-images.githubusercontent.com/41326532/162432742-e5299bbe-b6c0-4370-a584-7d56a96bcd31.mp4

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

* 
__

**Comment by aaemnnosttv** [comment]
This will require some rethinking of many things in order to support well. There are many places in Site Kit where we don't consider whether or not a module has been made unavailable (particularly Analytics) and is currently error-prone for that reason.

**Comment by felixarntz** [comment]
@jamesozzie While there is a commitment on Site Kit side to not cause errors in cases where certain modules have been made unavailable through code (there are some issues to address remaining quirks), using this filter is otherwise in the responsibility of the site owner (or whoever controls the code). Site Kit will not cater e.g. with specific UI for potentially slightly odd scenarios that removing certain services may result in (again, other than actual errors).

The purpose of this filter is for example in a site managed by an agency where the agency wants to "make things easier" for the site owner and only allow modules to be activated that they are configuring for the site owner, to reduce the chances of the site owner accidentally messing something up. So it would not be responsibility of the Site Kit plugin in this situation to tell the site owner that a certain module isn't available because for their own user experience, it should behave as if that module is not even a part of Site Kit.
