### ISSUE TITLE
Show errors instead of infinite loading state in AdSense V2 setup flow

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5107]
## Bug Description

In case of API errors, the V2 setup currently remains in an infinite loading state instead of showing the error to the user.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense V2 `SetupMain` component should be adjusted to show any relevant errors: Similar to the V1 version of the component, if there are any AdSense API errors (via `hasErrors` selector), it should show the errors via the AdSense `ErrorNotices` component.
    * In such cases, only that component should be shown instead of the regular `SetupCreateAccount`, `SetupSelectAccount`, or `SetupAccount`.
* The AdSense `ErrorNotices` component should be slightly adjusted: If the `adsenseSetupV2` feature flag is active, it shouldn't call the `errorToStatus` utility function to decide whether an error should show. _Any_ error should show in the V2 flow.

### `SetupMain` component

Within file `assets/js/modules/adsense/components/setup/v2/SetupMain.js`:

- Check for AdSense errors via the `MODULES_ADSENSE` store's `hasErrors` selector, which returns a boolean.
- Update the `if/else` sequence which determines `viewComponent` to first check the result of `hasErrors` and set `viewComponent` to `<ErrorNotices />` if so, as seen in the V1 `SetupMain` component:
https://github.com/google/site-kit-wp/blob/64e9b6c7f7576d33b23f7105a1e4311c0fa40b4a/assets/js/modules/adsense/components/setup/SetupMain.js#L458

### `ErrorNotices` component

Within file `assets/js/modules/adsense/components/common/ErrorNotices.js`:

- Use the `useFeature` hook to check whether the `adsenseSetupV2` feature flag is enabled.
- Update the rendered `StoreErrorNotices` component, passing `undefined` for the `shouldDisplayError` prop if the feature flag is enabled, otherwise continue to pass the `shouldDisplayError` callback.

### Storybook

- Add a new story for V2 `SetupMain` displaying the error state.

### Test Coverage

* No new tests needed.

## QA Brief

- Ensure the Adsense Setup V2 `Error Notice` story displays the error instead of the loading state. Story URL path - `/story/modules-adsense-components-setup-v2-setupmain--error-notice`
- Currently, we can’t test the error notice scenario using the tester plugin. Refer to this [comment](https://github.com/google/site-kit-wp/issues/5107#issuecomment-1114747818).

## Changelog entry

* Update the AdSense SetupMain component to show existing errors.

**Comment by tofumatt** [comment]
IB ✅

**Comment by hussain-t** [comment]
@felixarntz, @wpdarren, We can’t test the error notice scenario using the tester plugin due to the response the API returns. The `getAccounts()` selector returns `undefined` due the error response. Hence the `<ProgressBar />` rendered instead of the `<ErrorNotices />`. Please refer to this related [comment](https://github.com/google/site-kit-wp/issues/5106#issuecomment-1112156574).

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@felixarntz I can see the error message in Storybook, but would be good to see it in a test site.  As Hussain has mentioned we can’t test the error notice scenario using the tester plugin. Refer to this https://github.com/google/site-kit-wp/issues/5107#issuecomment-1114747818.  I am happy to pass, but is this something we can change in the tester plugin?

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@felixarntz @hussain-t I have sent this back to execution because I am unable to set it to `disapproved` on V2 to generate the error message. When I set it using `'disapproved (legacy)'` with `adsenseSetupV2` enabled,  the same issue occurs with the loading state.  I have been able to QA this by the story, but would expect to be able to test this scenario? 

![image](https://user-images.githubusercontent.com/73545194/166671947-50f1cd16-2001-4d2f-8a1b-9f8074729b2d.png)

**Comment by hussain-t** [comment]
Thanks, @felixarntz. 

>In general, looking for `undefined` values as the indicator for whether to show a loading state is a bit unreliable, for this very reason, that the request could have an error, in which case it should be displayed. We should use `! hasFinishedResolution` for the relevant selector to show the loading state.

I agree with this point 💯 

I have created a follow-up [PR](https://github.com/google/site-kit-wp/pull/5170) against `main`.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- The Adsense Setup V2 Error Notice story displays the error instead of the loading state. Story URL path - `/story/modules-adsense-components-setup-v2-setupmain--error-notice`
- I also tested this on my test site. The error now appears as expected.

![image](https://user-images.githubusercontent.com/73545194/166909009-471e68eb-784d-4e25-9282-d9d11c05ecb9.png)
