### ISSUE TITLE
Limit widget areas and contexts displayed on the shared dashboard to those which the user has access to

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5161]
## Feature Description

Building on the work started in #4807 and #4813, users on the shared dashboard should only see widget contexts that have non-empty widget areas. As it is now, the dashboard will show all areas and contexts

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `isWidgetContextActive` and `isWidgetAreaActive` selectors of the `core/widgets` store should be extended with a second (optional) `options` parameter that includes a single `modules` (`string[]` module slugs) option (just like `getWidgets`)
	* The functionality of this option is already handled by `getWidgets` so this is mostly about passing it through where needed
	* If provided, both selectors should only consider the given context/area active if it has any non-empty areas/widgets respectively (after filtering by the given modules)
	* All usage of these selectors in the following components should be updated to include the new `modules` argument (from `getViewableModules`) if in view-only context (relying on the `useViewOnly()` hook from #4814)
		- `DashboardEntityApp`
		- `DashboardMainApp`
		- `DashboardNavigation`
		- `WidgetContextRenderer`
		- `WidgetAreaRenderer`

## Implementation Brief
* Using `assets/js/googlesitekit/widgets/datastore/areas.js` and `assets/js/googlesitekit/widgets/datastore/contexts.js`,
	* Update the following selectors to include a new optional parameter, `options` that includes a single `modules` (`string[]` module slugs) option (just like `getWidgets`).
		* `isWidgetAreaActive`
			* Pass `modules` as second parameter to the `getWidgets` selector.
		* `isWidgetContextActive`
			* Pass `modules` as second parameter to the `isWidgetAreaActive` selector.
* Using the components listed in the last point from the AC, 
	* Query the user data store via the `getViewableModules` selector to retrieve the list of viewable modules for the user.
	* Check if we are in view-only mode via the `useViewOnly` hook.
	* If in view-only mode and there is a list of modules, update calls to `isWidgetAreaActive` and `isWidgetContextActive` to include the list of viewable modules as second parameter.

### Test Coverage
* Update tests to the `isWidgetAreaActive` and `isWidgetContextActive` selectors to include tests when a list of modules is passed as second parameter.

## QA Brief

**See https://github.com/google/site-kit-wp/issues/4813#issuecomment-1135037589 about how to reach the shared dashboard before #5188 is done.**

Once the Shared Dashboard can be viewed we should verify that only widgets which are shared with the user's role are visible on the Shared Dashboard (both the Main and the Entity Dashboard).

The shared roles will eventually be configurable via the UI, but in order to configure them prior to the UI controls being implemented use the [Dashboard Sharing tester plugin](https://app.asana.com/0/1185360131189553/1202293816056636/f).
```

## Changelog entry

* Limit widget areas and contexts displayed on the shared dashboard to modules which are shared with the user.

**Comment by tofumatt** [comment]
Looks good to me.

IB ✅

**Comment by techanvil** [comment]
Hi @aaemnnosttv, having implemented this I think it's not quite right in terms of functionality. When we retrieve the list of viewable modules that gives a list of _all_ the modules the user has permission for.

E.g. `[ 'pagespeed-insights', 'search-console' ]`.

However, as specced we then pass this list through via `isWidgetAreaActive` / `isWidgetContextActive` to `getWidgets`.

In `getWidgets` the list of modules is checked so only widgets that are assigned to _all_ of the listed modules are returned:

https://github.com/google/site-kit-wp/blob/16aefc7586732ef65e451b4964f621766db49459/assets/js/googlesitekit/widgets/datastore/widgets.js#L334-L337

That is to say, if viewable modules is `[ 'pagespeed-insights', 'search-console' ]`, only widgets assigned to _both_ of those modules will be returned, rather than to _either_ module. Therefore `isWidgetAreaActive` will only return true if the area contains active widgets which are assigned to _both_ `pagespeed-insights` and `search-console` (and likewise for `isWidgetContextActive`).

This is evidently not quite right as, for example, the number of widgets assigned to _both_ `pagespeed-insights` and `search-console` will be pretty slim!

It's worth mentioning that we have a similar situation already in `develop`, in `WidgetAreaRenderer`, where only widgets assigned to _all_ the viewable modules will be rendered:

https://github.com/google/site-kit-wp/blob/16aefc7586732ef65e451b4964f621766db49459/assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js#L101-L105

I think we just haven't spotted this as the feature is not yet integrated enough to the point of real-world end to end testing.

On the face of it, changing the logic so that widgets matching _any_ of the viewable modules are checked/returned should fix this. However I did notice that the requirement to match _all_ modules in `getWidgets` was quite explicit - see https://github.com/google/site-kit-wp/issues/4807 - so, I am a bit hesitant to suggest a change to `getWidgets`, maybe the calling code should instead be modified.

I hope I've not missed something here but assuming this all makes sense I think we should update the ACs here and the call to `getWidgets` in `WidgetAreaRenderer` needs a revision too. Interested to hear your thoughts.

**Comment by aaemnnosttv** [comment]
> In `getWidgets` the list of modules is checked so only widgets that are assigned to _all_ of the listed modules are returned:

@techanvil – This is incorrect in the implementation in `getWidgets`. It should essentially be 

```js
intersection( widget.modules, allowedModules ).length === widget.modules.length
```

That is – the widget should only be returned if all of **its** modules are included in the list of available/allowed modules, not the other way around.

We don't however want to loosen the logic to allow for any of a widget's modules available enabling it, that would largely defeat the purpose of the limitation.

Let me know if that makes sense. If so, I think we can make this correction as part of your PR without additional changes to the ACs.

**Comment by techanvil** [comment]
Hi @aaemnnosttv, thanks for pointing that out! I hadn't spotted that subtle disconnect between the AC and the implementation.

I think we can make that correction here too, will go ahead and make it happen. Cheers
