### ISSUE TITLE
Default Snippet Toggle Behavior for GA4 Doesn't Work on Analytics Settings Page

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#5167]
## Bug Description

Default snippet toggle behavior doesn't work for GA4 on Analytics settings page because the settings page doesn't call `useExistingTagEffect` of `analytics-4` module.

## Steps to reproduce

Make sure you are on `feature/existing-tag-simplification` branch. 

1. Setup Analytics Module with GA4 or UA+GA4. 
2. See that the default snippet toggle behavior works for UA and GA4.
3. Go to Settings. 
4. Change GA4 Measurement ID from/to existing tag. 
5. See that the Snippet Toggle doesn't change. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GA4 Snippet Toggle should behave correctly in Settings Page.

## Implementation Brief

* In `assets/js/modules/analytics/components/settings/SettingsEdit.js`:
    * Import `useExistingTagEffect` from the `analytics-4` module and use it. 
* Review and merge #5168

### Test Coverage

* Not applicable. 

## QA Brief

* Follow step to reproduce and ensure that the default toggle behavior for GA4 Snippet Toggle is working correctly. 
* For a refresher on the default toggle behavior and what/how to test, see QA Brief section of #4713

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When a site has GA4 and/or UA properties, and go to settings, the toggle behaves as expected. 

As additional tests:

- I have an existing snippet GA4 snippet in the header.php.  I also have a new GA4 and UA account and property.  When I connect Analytics with this new account the existing tag appears under the GA4 snippet and it is enabled because the existing tag is not linked with this account. If I change the account to the same as the existing tag, then the toggle is disabled as expected. When Analytics is connected I go to edit the settings page:
- Underneath the GA4 toggle is the message informing of the existing tag.  The toggle is enabled because  the existing tag is not linked with this account. If I change the account to the same as the existing tag, then the toggle is disabled as expected.

The GA4 toggles work as expected.

Here's a screencast of the test in action.

https://user-images.githubusercontent.com/73545194/166695043-d38ba791-931e-4078-9000-cb42a5f7fb62.mp4
