### ISSUE TITLE
Implement header bar GA events for dashboard sharing

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5220]
Based on the [custom GA events defined for dashboard sharing](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit), this issue is focused on implementing the events that are part of the header bar.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new GA event should be fired when the user clicks on the "Share" button in the Site Kit header bar:
    * Event name: `open_sharing`
    * Event category: `{viewContext}_headerbar`
    * Event label: either `simple` (if the site has only one administrator) or `advanced` (if the site has more than one administrator)
* A new GA event should be fired when the user clicks on the "View only" button in the Site Kit header bar:
    * Event name: `open_viewonly`
    * Event category: `{viewContext}_headerbar`
    * No event label
* A new GA event should be fired when the user clicks on the "Sign in with Google" button (only available for administrators) in the Site Kit header bar's view only menu:
    * Event name: `start_user_setup`
    * Event category: `{viewContext}_headerbar_viewonly`
    * Event label: either `proxy` (if site is using the proxy) or `custom-oauth` (if site is not using the proxy)
* A new GA event should be fired when the user opts in to tracking from within the Site Kit header bar's view only menu:
    * Event name: `tracking_optin`
    * Event category: `{viewContext}_headerbar_viewonly`
    * No event label
* A new GA event should be fired when the user clicks on the "Learn more" link in the Site Kit header bar's view only menu:
    * Event name: `click_learn_more_link`
    * Event category: `{viewContext}_headerbar_viewonly`
    * No event label

## Implementation Brief

* In the `DashboardSharingSettingsButton` component:
  * Get the current view context using the `useViewContext` hook.
  * Call the `trackEvent( '{viewContext}_headerbar', 'open_sharing' )` function in  the `openDialog` callback.
* In the `assets/js/components/ViewOnlyMenu/index.js` file:
  * Get the current view context using the `useViewContext` hook.
  * Update the `toggleMenu` callback to call `trackEvent( '{viewContext}_headerbar', 'open_viewonly' )` function when the current value of the `menuOpen` variable is false.
* In the `assets/js/components/ViewOnlyMenu/Description.js` file:
  * Update the `onButtonClick` callback to call the `trackEvent` function for the `start_user_setup` event unconditionally.
    * Update the event category to be `{viewContext}_headerbar_viewonly`.
    * Add event label that is either `proxy` (if site is using the proxy) or `custom-oauth` (if site is not using the proxy).
  * Add a new callback that calls the `trackEvent( '{viewContext}_headerbar_viewonly', 'click_learn_more_link' )` function and set it as the `onClick` property to the "learn more" link.
* In the `OptIn` component:
  * Add a new optional property `trackEventCategory`.
  * Update the `trackEvent` call to use the `trackEventCategory` property if provided, otherwise use the current `viewContext` variable.
* In the `assets/js/components/ViewOnlyMenu/Tracking.js` file:
  * Get the current view context using the `useViewContext` hook.
  * Add `trackEventCategory={ '{viewContext}_headerbar_viewonly' }` property to the `OptIn` element.

### Test Coverage

* N/A

## QA Brief

* Verify that events described in AC are triggered correctly.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Looks good to me, IB ✅

**Comment by wpdarren** [comment]
QA Update: ⚠️ 

@eugene-manuilov I have a few questions:

> A new GA event should be fired when the user clicks on the "Share" button in the Site Kit header bar:

1. I do not see a "Share" button.  Does this appear under a specific scenario? I do not see it when in view only for an editor, and I am unable to see the view only dashboard for a secondary admin because when I click on the `Skip sign-in and view limited dashboard` link on the splash screen, it just refreshes the page and no view only button appears. 

> A new GA event should be fired when the user clicks on the "Sign in with Google" button (only available for administrators) in the Site Kit header bar's view only menu:

As I mentioned above and also in the [comment here](https://github.com/google/site-kit-wp/issues/5219#issuecomment-1138389492) when I click on the `Skip sign-in and view limited dashboard` link on the splash screen, it just refreshes the page and no view only button appears. So, I am unable to test this at the moment. 

**Verified:**

- A new GA event is fired when I opt in to tracking from within the Site Kit header bar's view only menu, as per the AC. 
- A new GA event is fired when I click on the "Learn more" link in the Site Kit header bar's view only menu, as per the AC.
- A new GA event is fired when I click on the "View only" button in the Site Kit header bar, as per the AC.




A new GA event should be fired when the user clicks on the "Sign in with Google" button (only available for administrators) in the Site Kit header bar's view only menu:
Event name: start_user_setup
Event category: {viewContext}_headerbar_viewonly
Event label: either proxy (if site is using the proxy) or custom-oauth (if site is not using the proxy)


![image](https://user-images.githubusercontent.com/73545194/170473323-aafebcc4-86fd-4849-838c-e80f3eaaa90c.png)

![image](https://user-images.githubusercontent.com/73545194/170472117-dc2abc2a-d20c-46ad-bd10-a46d320c562b.png)

![image](https://user-images.githubusercontent.com/73545194/170473982-8afeaefd-5f51-41b5-9bf2-0b9126b47721.png)

**Comment by eugene-manuilov** [comment]
@wpdarren looks like we need to wait until #5188 is merged to be able to QA this properly. I am going to assign this to you for now. Please, check it again when that ticket is ready and assign it back to me if this one still doesn't work for you.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@eugene-manuilov just one observation. When I click on the 'Sharing settings' icon in the header bar, all of the AC passes other than `Event label: either simple (if the site has only one administrator) or advanced (if the site has more than one administrator)` is not getting triggered.  Could this because we still have 4822 in Execution? 

**Verified:**

- A new GA event is fired when I opt in to tracking from within the Site Kit header bar's view only menu, as per the AC. 
- A new GA event is fired when I click on the "Learn more" link in the Site Kit header bar's view only menu, as per the AC.
- A new GA event is fired when I click on the "View only" button in the Site Kit header bar, as per the AC.
- A new GA event is fired when I click on the "Sign in with Google" button in the Site Kit header bar, as per the AC.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/170473323-aafebcc4-86fd-4849-838c-e80f3eaaa90c.png)

![image](https://user-images.githubusercontent.com/73545194/170472117-dc2abc2a-d20c-46ad-bd10-a46d320c562b.png)

![image](https://user-images.githubusercontent.com/73545194/170473982-8afeaefd-5f51-41b5-9bf2-0b9126b47721.png)

![image](https://user-images.githubusercontent.com/73545194/171013537-2c67bf60-979d-4d01-8519-fd09f07722f0.png)

</details>

**Comment by eugene-manuilov** [comment]
> @eugene-manuilov just one observation. When I click on the 'Sharing settings' icon in the header bar, all of the AC passes other than `Event label: either simple (if the site has only one administrator) or advanced (if the site has more than one administrator)` is not appearing in the GA data. Could this because we still have 4822 in Execution?

Good catch, @wpdarren. No, the event label should be added in this ticket and not depend on 4822. I have created a follow-up PR that adds the label #5304. Once it is reviewed and merged, this issue should be fixed.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- A new GA event is fired when when I click on the "Share" button in the Site Kit header bar, as per the AC.
- A new GA event is fired when I opt in to tracking from within the Site Kit header bar's view only menu, as per the AC. 
- A new GA event is fired when I click on the "Learn more" link in the Site Kit header bar's view only menu, as per the AC.
- A new GA event is fired when I click on the "View only" button in the Site Kit header bar, as per the AC.
- A new GA event is fired when I click on the "Sign in with Google" button in the Site Kit header bar, as per the AC.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/171177741-59aee00d-cf19-447b-b708-c7f356a763e4.png)

![image](https://user-images.githubusercontent.com/73545194/171177755-4fed92cc-80cb-4ad9-ac3c-03411e6e7b0b.png)

![image](https://user-images.githubusercontent.com/73545194/170473323-aafebcc4-86fd-4849-838c-e80f3eaaa90c.png)

![image](https://user-images.githubusercontent.com/73545194/170472117-dc2abc2a-d20c-46ad-bd10-a46d320c562b.png)

![image](https://user-images.githubusercontent.com/73545194/170473982-8afeaefd-5f51-41b5-9bf2-0b9126b47721.png)

![image](https://user-images.githubusercontent.com/73545194/171013537-2c67bf60-979d-4d01-8519-fd09f07722f0.png)

</details>
