### ISSUE TITLE
Implement GM2+ styles.

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#5254]
## Feature Description

As we wait for the new GM3 libraries to be out, we can start implementing some GM3 styles within the plugin which will be an intermediary step known as GM2+. Those style changes are:
* Basic colour changes
* Typography, e.g Google Sans and font size adjustments.
* Rounded corners on some UI surfaces.
* Removal of drop shadow on some UI surfaces.
* Buttons to look closer to GM3 (more rounded corners).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Current colours should be replaced by the closest ones found in the [Figma designs](https://www.figma.com/file/ZL8qlbUyR9lmBaF95t0xpq/sitekit-design-system?node-id=301%3A209). The following [colour mapping](https://user-images.githubusercontent.com/31818/170030649-5f57b5ed-63b2-4485-952b-340517bffda0.png) should be used.
* `Roboto` and `Google Sans` fonts should no longer be used and be replaced by `Google Sans Text` and `Google Sans Display`.
* Font sizes and line heights should be adjusted to use the closest possible values from the [updated type scale](https://www.figma.com/file/ZL8qlbUyR9lmBaF95t0xpq/sitekit-design-system?node-id=398%3A250).
* Border radius should be set to either `8px`, `16px` or `24px` for appropriate UI surfaces. For e.g 
	* dropdown menus and small UI elements such as tooltips should have a `8px` border radius.
	* widgets and "sections" within pages, for e.g sections within the admin settings, should their border radiuses set to `16px`.
* Box shadows should be removed from all UI elements.
* Buttons should be updated to match the [designs in Figma](https://www.figma.com/file/ZL8qlbUyR9lmBaF95t0xpq/sitekit-design-system?node-id=409%3A2253) as close as possible.
	* Buttons should not be all caps.
* Links should be #108080
* Table headers should be 16px and 14px if the widget containing the table has a title.
* Navigation pills should have a font size of 16px (disregard the designs in Figma where the font size is 12px).
* Disregard the rounded bottom corners for the header in the designs. https://www.figma.com/file/f1I9Mc0ITE6Uk0qiTRbggK/GM2%2B?node-id=601%3A775

References:
* https://www.figma.com/file/f1I9Mc0ITE6Uk0qiTRbggK/GM2%2B?node-id=601%3A746
* https://www.figma.com/file/ZL8qlbUyR9lmBaF95t0xpq/sitekit-design-system?node-id=301%3A209

## Implementation Brief

**Note:** When creating a pull request for this, please do it as a draft PR, so that it is not accidentally merged. This PR should not be merged as usual when code review is complete, as it will require an extensive design review together with the UX team, which we will schedule once the PR is ready to review.

* Using `includes/Core/Assets/Assets.php`,
	* Update `get_fonts_src` to load `Google Sans Text` and `Google Sans Display` instead of `Roboto` and `Google Sans`.
	* Font weights should be as follows:
		* `Google Sans Text`: `400` and `500`
		* `Google Sans Display`: `400`, `500` and `700`
* Using `assets/sass/config/_variables.scss`,
	* replace the colours by the [mappings found here](https://www.figma.com/file/ZL8qlbUyR9lmBaF95t0xpq/sitekit-design-system?node-id=791%3A7997).
	* update `$f-primary` to `"Google Sans Text", "Helvetica Neue", Helvetica, Arial, sans-serif`
	* update `$f-secondary` to `"Google Sans Display", "Helvetica Neue", Helvetica, Arial, sans-serif`
	* update `$typography` to use the closest values from [type scale](https://www.figma.com/file/ZL8qlbUyR9lmBaF95t0xpq/sitekit-design-system?node-id=398%3A250).
	* add new variables for border radiuses, which should be either `16px` or `24px`.
* Scan `*.scss` files to look for `font-size` and `line-height` declarations and update them to use the closest values from the type scale.
* Remove the `shadow` mixin from `assets/sass/config/_mixins.scss` and usage across the codebase or any `box-shadow` declarations.
* Using `assets/sass/widgets/_widgets.scss`, set the `border-radius` to `24px` for the `.googlesitekit-widget` class.
* Drop down menus should be styled as per[ the designs in Figma,](https://www.figma.com/file/ZL8qlbUyR9lmBaF95t0xpq/sitekit-design-system?node-id=627%3A1330) specifically they have a background color now that there is no more box shadow.
* Buttons should be styled as per the designs in Figma specifically,
	* more rounded corners, with the border radius set to `100px`.
	* capitalize the button label instead of having it in all caps.
	* colors should remain unchanged for now pending UX review.

### Test Coverage
* No new tests to be added.
* VRT to be updated.

## QA Brief
* Ensure plugin has been styled as per the designs in Figma.
* We don't have designs for all the screens, for e.g user input, editing a module settings. Those screens have been styled with the new colors and fonts and has been reviewed by UX.

## Changelog entry

* Update the plugin styling in line with Google Material 3.

**Comment by aaemnnosttv** [comment]
> * Border radius should be set to either `16px` or `24px` for appropriate UI surfaces. For e.g dropdown menus should have a `16px` border radius and widgets should their border radiuses set to `24px` .

@asvinb Are these the only places where radiuses are changing? If so, it would probably be more clear as two separate points. If not, it would still probably be better to separate them and list all the places that should be affected by the change.

> * Box shadows should be removed from all UI elements.

Is this specific to buttons, etc or ALL elements everywhere? The description above says "some surfaces". I.e. I would think we would still want shadows for the header and other sticky elements below it, as well as tooltips/modals?

**Comment by asvinb** [comment]
@aaemnnosttv For the border radius changes, it's not an extensive list because things might change as we review with the design team. But for a start, the dropdown menus and widgets are the most eye-catching "candidates" to have round border radiuses.
As for the box shadow, it'll be applicable to ALL elements. I also asked the same question as you about the box shadow for sticky elements, or even in the header where we have a box shadow between the header and possible notification beneath it. Short answer is that for now we'll be removing all of them and design will see how it looks and then provide recommendations on how to tweak things. A possible solution would be to add background colours or even solid borders.

**Comment by aaemnnosttv** [comment]
LGTM for the most part! Regarding the added web font files, do we only need `woff` or do we need to include multiple formats for compatibility? Looks like `woff` covers all our browsers but `woff2` is more performant. I'm not sure we can use only `woff2` but maybe we can since we don't support IE anymore.

Also, @asvinb would you please add an estimate?

@felixarntz would you also give this a quick look-over?

**Comment by asvinb** [comment]
Good question @aaemnnosttv ! Initially I was planning to add both, `woff` and `woff2` with `woff` only for IE and then I saw we are [no longer supporting](https://github.com/google/site-kit-wp/issues/1475#issuecomment-827718821) IE11. From [caniuse.com](https://caniuse.com/?search=woff2), only `Opera Mini` is not supported. Not sure we are supporting this browser though.

**Comment by aaemnnosttv** [comment]
> From [caniuse.com](https://caniuse.com/?search=woff2), only `Opera Mini` is not supported. Not sure we are supporting this browser though.

I don't think we are – Opera Mini doesn't support `woff` either (maybe that's what you meant though). It actually seems React [doesn't support Opera Mini at all](https://create-react-app.dev/docs/supported-browsers-features/) which may be due to the browsers [restrictions around JavaScript](https://en.wikipedia.org/wiki/Opera_Mini). TL;DR we can't support a browser that React doesn't 😄

**Comment by felixarntz** [comment]
@asvinb Some feedback on the IB:
> * Buttons should be styled as per the designs in Figma specifically,
> 	* more rounded corners, with the border radius set to `100px`.
> 	* switch the blue background color to be green including the hover and active states.

The ACs state _not_ to change the button colors, so this contradicts it as far as I can tell. I would agree with the ACs that we should not change the button colors as the extra tweaks for all the different button variants would make that a relatively large maintenance burden.

> * Using `includes/Core/Assets/Assets.php`,
> 	* Remove the `get_fonts_src` function and associated usage since the new font used "Google Sans", is not available on Google Fonts.

Oh wow. We really had this "invalid" Google Fonts request in our code for all this time? I never realized that "Google Sans" wasn't even available from there. 🤔 Does this in fact not work? What happens if you access `https://fonts.googleapis.com/css2?family=Google+Sans` or `https://fonts.googleapis.com/css2?family=Google+Sans+Display` for example?

> 	* update `$f-primary` to `"Google Sans Text", "Helvetica Neue", Helvetica, Arial, sans-serif`
>	* update `$f-secondary` to `"Google Sans Display", "Helvetica Neue", Helvetica, Arial, sans-serif`

Is that really accurate to address the ACs? In there it says the type of "Google Sans *" to use should be based on the font size (with 24px as "breakpoint"). Are all usages of `$f-primary` and `$f-secondary` in fact following this requirement in terms of font sizes?

---

And now to the bigger concern:
> * Add the `Google Sans Text` and `Google Sans Display` `woff2` font files to `assets/fonts` folder. Check with the design team for those assets.

If we really need to do this to have access to the "Google Sans" fonts, we may need to do further investigation before signing off on this. Theoretically loading these fonts from a font CDN (which apparently may not have been working all this time 😆) is one thing, but bundling them into the plugin comes with potential licensing concerns. Every part of a WordPress plugin has to be compatible with the GPL, and I'm not sure what the license for these "Google Sans" fonts are. At a higher level note, I'm not sure whether we are even allowed to distribute them in a WordPress plugin. Of course this is not something you can address in the IB right away, but we need to investigate and discuss next steps on this. cc @aaemnnosttv 

Feel free to go ahead and address my other feedback already though.

**Comment by asvinb** [comment]
@felixarntz 
For the buttons I initially wrote the AC where I mentioned that we won't style it, only to talk to Victor and find out that we'll want to include buttons style updates as well. The most noticeable changes would be:

- change background color
- change font size
- change border-radius

I agree, changing the buttons will take quite a bit of time but I think it should be doable, but curious to hear Victor's and Seba's take on it, whether we should include buttons or not in the updated styles. Personally I feel the buttons will look a bit out of place with the other changes, namely the border radius changes and color changes for the widgets.

For the "Google Sans" font, apologies for the confusion. I meant to say the "Google Sans Text" and "Google Sans Display" font sizes. 🤦 
About using the "24px" breakpoint, this is something which Victor suggested but I think we can have another rule where all titles and headings use the "Google Sans Display" and all body text use "Google Sans Text". 

So, we can load the fonts from Google fonts:

- [https://fonts.googleapis.com/css2?family=Google+Sans+Display](https://fonts.googleapis.com/css2?family=Google+Sans+Display)
- [https://fonts.googleapis.com/css2?family=Google+Sans+Text](https://fonts.googleapis.com/css2?family=Google+Sans+Text)
but it's explicitly [mentioned that this font is not Open Source](https://fonts.google.com/license/googlerestricted), so I doubt we can use them.

**Comment by felixarntz** [comment]
@asvinb 
> I agree, changing the buttons will take quite a bit of time but I think it should be doable, but curious to hear Victor's and Seba's take on it, whether we should include buttons or not in the updated styles.

To get this started, I'd say let's keep the changes rather simple, so could you remove the button color changes part from the IB? We will review the eventual PR extensively with the UX team before it can be merged, so we can always add such changes later if they are really needed after the review.

I've added a note on the PR special case above your IB to clarify that.

> About using the "24px" breakpoint, this is something which Victor suggested but I think we can have another rule where all titles and headings use the "Google Sans Display" and all body text use "Google Sans Text".

Sounds good.

> So, we can load the fonts from Google fonts:
> 
> - [https://fonts.googleapis.com/css2?family=Google+Sans+Display](https://fonts.googleapis.com/css2?family=Google+Sans+Display)
> - [https://fonts.googleapis.com/css2?family=Google+Sans+Text](https://fonts.googleapis.com/css2?family=Google+Sans+Text)
but it's explicitly [mentioned that this font is not Open Source](https://fonts.google.com/license/googlerestricted), so I doubt we can use them.

The same applies to "Google Sans" though (https://fonts.googleapis.com/css2?family=Google+Sans) which we have had in the plugin forever. We cannot add these fonts _into_ the plugin, but we can load them from this CDN, so we should actually be good with that. Can you please update the IB so that we keep the Google Fonts loader and use _that_ for the new Google fonts? You should then remove the part about adding the fonts to the plugin codebase.

**Comment by asvinb** [comment]
Sounds good @felixarntz . IB has been updated, can you check again?

**Comment by asvinb** [comment]
Sounds good @felixarntz Over to you for a final review.

**Comment by felixarntz** [comment]
Thanks @asvinb! IB ✅

**Comment by eclarke1** [comment]
@felixarntz any chance you could get to this CR today please? Might also be worth having 2 sets of eyes on this @aaemnnosttv as this is a big visual change. We are aiming to get this into release 1.78.0.
I have also chatted to @asvinb and we are intending to update the AC and QAB once the CR has been approved so it's clear to QA exactly what has changed (given there's no true reference point to check against)
cc @wpdarren @mohitwp

**Comment by wpdarren** [comment]
@mohitwp as per our conversation. The focus on this ticket will be on ensuring that there are no UX/UI issues with the new styles on our supported browsers on desktop and small screen sizes.  We need to test all screens, including the different scenarios for a site with live data, zero and gathering data states.  We'll have to check the notifications, and CTA's.  

A lot of changes were made to the design through the engineering process, so, use the site mentioned in Slack as a reference point when comparing to your test site. You can also reference the AC's for additional checks. 

**The QAB mentions the Figma designs but in my opinion we should avoid comparing to these because they are out of date and will cause confusion with the amount of expected differences.**  

@aaemnnosttv @eclarke1 do we expect that the AC and QAB will be updated on this ticket?

**Comment by eclarke1** [comment]
@wpdarren @mohitwp adding here @aaemnnosttv note from Slack:

This should be good to go but there is a quirk I ran into with VRT failing even after changes were approved and pushed. We should fix this before merging though or it will break VRT for all other PRs. QA can test this with the tester plugin by installing the build for the PR 5314, so this CI issue shouldn't block the team from moving forward with it because everything in the plugin is fine. If anyone can help identify and fix the VRT problem that would be great!

So perhaps we can get a head start on QA here whilst we wait for the VRT tests to be resolved.

@FlicHollis let's identify someone in the team to pick up the VRT tests please

**Comment by eclarke1** [comment]
@aaemnnosttv noting here one thing we do still need to add is the green background to the feature tour as per discussions yesterday. Could I kindly ask you to add that today please?

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified design on latest versions of Chrome, Firefox , Safari and Edge browser.
- Verified responsive design on i-Phone 13, I-pad, Mac Safari and android mobile using browserstack.
- Verified site in zero data state for both gathering and zero data state.
- Verified site when feature flag 'user input' is active.
- Verified site when 'Dashboard sharing' feature flag is active.
- Verified CTA's.
- For comparison, I used reference site shared in slack because Figma designs are out of date and missing many screens.


cc @wpdarren

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

The new background colour on the menus is perfect. Much easier to read.  I just have one observation on the search bar though. I'd assumed this was going to be picked up with it being a menu dropdown in the header.  As you can see when you type in the search box the dropdown is in the darker grey colour.  Do you think this should be fixed to be consistent? 

Sorry if I wasn't specific with this. Screencast below. 

![menu](https://user-images.githubusercontent.com/73545194/178628024-c32aa4ad-cee2-4920-a1ae-96a468bf4dd5.gif)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The background colour of the feature tour tips are primary green rather than black
- The colour of the menu dropdowns have been changed to have light background with border and are much easier to read.
