### ISSUE TITLE
Improve assigned-to fields for Project Board Automation

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#527]
## Feature Description

Currently moving an item from "IB/Estimate" to "IB Review", "In Progress" to "Code Review", and "Code Review" to "QA" all result in (reasonably) predictable changes to the "assigned to" field in GitHub; for the first and second options the assignment is almost always @felixarntz, and for the last option the assignment is cleared.

Rather than depend on users to manually do this admin work, we should automate that assignment when an issue is moved with a GitHub Action.

We may also be able to automatically assign the _previously-assigned_ user to an issue that has been changed from "Code Review" to "In Progress" or "IB Review" to "IB/Estimate" given it's usually the person last working on it who should be assigned.

There are edge-cases where these automated assignments will be off, but for the majority of time they will reduce human error/manual human interaction with the project boards, which I think is a win.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
That would be a great thing to automate now that we can use GitHub Actions on this repo! A bit skeptical about the assign-everything-to-Felix part though.

**Comment by felixarntz** [comment]
@tofumatt I'm gonna close this for now since we have multiple code reviewers and QA reviewers now, so it won't be as trivial (fortunately!). Maybe we could have something that automatically assigns _a_ code reviewer, but I think that's not worth it and might even be detrimental since sometimes a certain reviewer might be more applicable for an issue than another one, so I think manual is better here.

Feel free to reopen if you have another suggestion.
