### ISSUE TITLE
Include a "request access" link to Analytics when a user encounters an "Insufficient Permissions" notice

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5308]
## Bug Description

When a wp-admin sets up Site Kit and they don't have access to the already connected Analytics property, which was connect by another wp-admin, they encounter an insufficient permissions notice. Consider adding a link to that specific Google Analytics property page, so users can "request access". That way they don't need to specifically know the wp-admin in question, as the wp-admin username doesn't always appear within the error. 

Note that this link already exists within the Site Kit dashboard, but only under the "Top content over the last ** days" widget, see example in the video within this issue:

![image](https://user-images.githubusercontent.com/41326532/171371337-8cd30495-b7d7-4620-93b6-e23f3cab8e76.png)

The link should look something like this, including the users email and property details:
`https://analytics.google.com/analytics/web/?authuser=**emailhandle**%40gmail.com#/report/content-pages/a145833174w302476565p260252701/_u.date00=20220503&_u.date01=20220530/
`

## Steps to reproduce

1. Set up Site Kit while also connecting Analytics
2. Login as another wp-admin user that doesn't have access to the connected GA property
3. Set up Site Kit 
4. You'll see the "Insufficient permissions" notice
5. Only by clicking on the Analytics link in the lower Analytics widget (Top content over the last 28 days) will you be directed to a link where you can "request access"

https://user-images.githubusercontent.com/41326532/171373350-21cce51b-5895-4682-85f2-c373a1e3eaf8.mp4

## Additional Context

Should this be added it would solve the problem as described in https://github.com/google/site-kit-wp/issues/5267

A possible fix to this would be to change the text to the below:

```diff
- Your Google account does not have sufficient permissions to access Analytics data, so you won’t be able to see stats from it on the Site Kit dashboard. This service was originally connected by the administrator "****" — you can contact them for more information.. 
+ Your Google account does not have sufficient permissions to access Analytics data, so you won’t be able to see stats from it on the Site Kit dashboard. This service was originally connected by the administrator "****" — you can contact them for more information, or **request access here**.
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All JS stores for modules where the Google service allows requesting access for an entity where the account does not have access currently, should receive a new selector consistently named `getServiceEntityAccessURL` (parameter-less). These are:
    * Analytics: Should basically return the same as `getServiceReportURL` selector with `type` set to `report-home`.
    * Search Console: Should return the same as `getServiceURL` selector with a single query argument `resource_id` set to the current Search Console property ID.
    * All other Google services do not have any UI that would inform about how to get access.
* Any "insufficient permissions" error message (for any module/service) should be conditionally enhanced as follows:
    * If the module's data store includes a `getServiceEntityAccessURL` selector, a primary CTA button with label "Request access" should be shown below the error message that links to the service URL (i.e. the plain service URL from the selector).
        * From there, the respective Google service will show corresponding UI for what the end user can do to get access.
    * The button should look similarly to the retry button (conditionally added to other types of errors) from #5236.
* A Storybook story for one of these errors should be added, alongside the existing story for the retry button (see #5236).

## Implementation Brief

* Within `/assets/js/modules/analytics/datastore/service.js` and `/assets/js/modules/search-console/datastore/service.js`:
    - Create a new `getServiceEntityAccessURL` selector using `createRegistrySelector()`. Define the new selector as per the AC.
* Within `ReportError`:
    - Use the `getModuleStoreName` selector from the `CORE_MODULES` store. 
    - Call the new `getServiceEntityAccessURL` selector on the module's store only if the function exists, e.g.  `typeof select( moduleStoreName ).getServiceEntityAccessURL === 'function'`.
    - If the selector returns a value and if one of the `errors` is an "Insufficient Permissions Error" (use the selector `isInsufficientPermissionsError`), then return a `<Button>` with the label `Request access` similar to how the Retry button is being added currently.
* Modify the existing "ReportError with Insufficient Permissions" story mocking the data of a module which has the `getServiceEntityAccessURL` selector.

### Test Coverage

* Add tests for the new selectors.

## QA Brief

- Follow the steps in the description to reproduce the issue.
- Ensure the `Request access` button with the URL is rendered for Analytics and Search Console insufficient permission errors.
- Click the `Request access` button from the Analytics and Search Console and ensure they navigate to the right place to request access.
- For CR, ensure [this new story](https://google.github.io/site-kit-wp/storybook/pull/5759/?path=/story/components-reporterror--report-error-with-insufficient-permissions-with-request-access) is as expected.
- For QA, ensure [this new story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-reporterror--report-error-with-insufficient-permissions-with-request-access) is as expected.

**Follow-up PR Update**
- Ensure the `Request access` button and the `Get help` link are aligned vertically, as pointed out in this [comment](https://github.com/google/site-kit-wp/issues/5308#issuecomment-1241041740).

![Screenshot 2022-09-09 at 2 45 19 PM](https://user-images.githubusercontent.com/24408261/189316345-2bea4fce-1bd2-4b46-8dd2-488e048a4105.png)

## Changelog entry

* Add "Request access" button to permission error messages for modules where their service supports it.

**Comment by jamesozzie** [comment]
Tagging both @aaemnnosttv and @bethanylang here for visibility.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by aaemnnosttv** [comment]
⚠️ while the IB appears to fulfill the AC, I don't believe the current AC will achieve the intended end result. That is, the grant-access flow we're providing a button to for the user to follow happens when the user attempts to access a specific URL for an entity that the user doesn't have access to. The `getServiceURL` selector however is not entity-specific; it's more of the homepage for the service. So as-is, this would just send the user to Analytics, but not prompt the user to request access because we haven't sent them to anything they would need to request access to.

Secondarily, I'm not sure all services implement this kind of request access feature. @felixarntz I'm somewhat certain that SC does but what about others? I would be surprised if AdSense did. We should avoid setting false expectations that access can be requested where it can't be.

**Comment by felixarntz** [comment]
@aaemnnosttv Ahh good catch, I messed up this part of the ACs, I had forgotten that `getServiceURL` returned only the overall generic URL. The URLs should indeed always be specific to the connected entity for the service. I guess we don't have any centralized selectors for that across the relevant module stores? Maybe we should introduce them using a specific name, e.g. `getServiceEntityURL`?

Right now, at least for AdSense we have `getServiceAccountURL`, and for Analytics and Search Console we could use something close to their `getServiceReportURL` selectors.

**Comment by felixarntz** [comment]
@aaemnnosttv Ahh good catch, I messed up this part of the ACs, I had forgotten that `getServiceURL` returned only the overall generic URL. The URLs should indeed always be specific to the connected entity for the service. I guess we don't have any centralized selectors for that across the relevant module stores? Maybe we should introduce them using a specific name, e.g. `getServiceEntityURL`?

Right now, at least for AdSense we have `getServiceAccountURL`, and for Analytics and Search Console we could use something close to their `getServiceReportURL` selectors. What do you think?

**Comment by aaemnnosttv** [comment]
> Maybe we should introduce them using a specific name, e.g. `getServiceEntityURL`?
> 
> Right now, at least for AdSense we have `getServiceAccountURL`, and for Analytics and Search Console we could use something close to their `getServiceReportURL` selectors. What do you think?

That sounds good, but seeing as we haven't had a need for it just yet, maybe we should make the selector specific to the action rather than something generic? I.e. `getServiceRequestEntityAccessURL` or something like that – could point to whatever the URL is that would prompt for access if the user didn't have it, and that's all it would be used for. Also, we could treat the presence of the selector as an implicit interface – we'd treat modules that implement it as services that have entities that access can be requested for. This would solve the other problem I mentioned above where some services may offer this an others won't, and we'd want to avoid presenting the user with this action to take if it isn't really possible. Using a more generic name would make it a bit easier to define this selector for another purpose and cause the "request access" CTA to appear where it shouldn't as an unintended side-effect.

Something like `getServiceEntityURL` could be useful in the future too and in some cases the URLs might even be the same, but I'd suggest we use separate selectors for the reasons above.

**Comment by felixarntz** [comment]
@aaemnnosttv SGTM, I've updated the ACs accordingly. I shortened it a bit to just `getServiceEntityAccessURL` though. Note that this is actually only relevant for Analytics and Search Console, so with the new selector that part is also improved and we don't unnecessarily add these buttons for services where it doesn't make sense.

@jimmymadon @techanvil This should be ready to iterate on the IB based on the updated ACs. Of course due to the new first point, the estimate is likely to increase a little.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The Request access button with the URL is rendered for Analytics and Search Console insufficient permission errors.
- When I click the button from the Analytics and Search Console error, I am taken to GA and ask to request access.
- [This new story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-reporterror--report-error-with-insufficient-permissions-with-request-access) is displayed as expected.

<details>
 <summaryScreenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/188131528-80e53507-5797-4a34-b93f-031bc0697fe8.png)
![image](https://user-images.githubusercontent.com/73545194/188131571-c7dfaa60-0eee-484c-b001-ac8d19a29869.png)

</details>

**Comment by hussain-t** [comment]
Thanks for pointing it out, @felixarntz 👍 I have fixed it in a follow-up [PR](https://github.com/google/site-kit-wp/pull/5810). Here is the fixed screenshot:

![Screenshot 2022-09-09 at 2 45 19 PM](https://user-images.githubusercontent.com/24408261/189316578-0dbbebe2-7411-41ae-80e4-ae4721e9a751.png)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Apologies, I should have picked up on this!   I can confirm that the 'Get Help' text is aligned to the request access text.

![image](https://user-images.githubusercontent.com/73545194/189365800-d6072cbd-9ec0-4009-a2a2-1c9ba02ee115.png)

**Comment by aaemnnosttv** [comment]
LGTM 👍 
<img width="254" alt="image" src="https://user-images.githubusercontent.com/1621608/189408846-c0e9c9bd-8431-409d-8fe0-d77100f9520f.png">
