### ISSUE TITLE
Issue with Idea Hub and Analytics setup flow after not giving permission

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5344]
## Bug Description

While testing #3160  I noticed odd behaviour that when investigated by @tofumatt it was appears in the latest version of Site Kit.  The issue arises with Idea hub and Analytics. The setup flow does not complete. 

Here are the steps:

- Click the CTA button to set up Idea Hub on the Dashboard (or link in settings). 
- Do not give permission (or cancel) and you are redirected back to the SK Dashboard with the error message `Error Connecting Site Kit` 
- Click on the `Redo the Plugin setup` button and you go through the authorisation process and this time give permission.  
- You are then redirected back to the dashboard, but as you can see from the screencast, the set up hasn't completed.  

The Idea Hub step where you have to agree for Idea Hub to track usage of the feature does not appear. 

https://user-images.githubusercontent.com/73545194/170970508-a9f16504-1008-4df2-9b71-0373ebd14c4e.mp4

3. The same issue was also occurring for Analytics but the only thing different this time is that when I was redirected back to the dashboard, the Analytics success notification appeared but you can see from the screencast below, it hasn't. 

https://user-images.githubusercontent.com/73545194/170971072-5da5e572-2f4a-48ee-816c-fbed88d121b6.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
This is somewhat expected and really applies to all modules rather than Idea Hub specifically. We have to set the redirect (i.e. "next step after oauth") URL before sending the user to oAuth. If a user cancels that flow after activating a module, when they return the module will still be active which is why the notice about needing to redo setup is there because required scopes are not granted.

When the user clicks the redo setup link, this CTA lacks the context from before that the user was going through setup for a module and that we should resume setup for it which is why that doesn't happen on return in this case.

While this would be ideal, it is a bit of an edge case and the added complexity it would take to handle this isn't quite worth the effort. We can always reconsider this later but closing for now.
