### ISSUE TITLE
Improve experience with recoverable modules for view-only users

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5376]
## Feature Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202445528223671 please refer to Asana issue for background

Improve the messaging & experience if an admin has connected a module, shared access, and then disconnects. If an admin has connected a module (ie. Analytics), shared view only access with other roles (include admins), and then disconnects they'll be presented with an option to "Set Up" Site Kit or to access "View only" data. 

If they choose to only view the data they'll encounter the below message, which isn't the most suitable ([screenshot](https://i.imgur.com/WibdHvP.png)):

**Data error in Analytics**
Site Kit can’t access the relevant data from Analytics because you haven’t granted all permissions requested during setup.

The reason is not suitable is that the user did provide access previously but they disconnected. They do actually have access to the Analytics property but they need to re-do the plugin setup, and there is no obvious link to do so (after choosing the "view only" dashboard). 

The only way for the admin to re-do plugin set up is to [click on the "View only" link and then "Sign in with Google" option](https://i.imgur.com/oXXP0rK.png). This isn't very obvious, and would likely lead to many admins resetting the plugin. 

[Recording of experience](https://recordit.co/TyaVuv5X06)

[Improved recording of experience](https://recordit.co/dIC0iH0RNt) - showing all 3 CTA's on the dashboard after disconnecting

Steps to recreate:
1. Connect SK with Google Analytics
1. Share Google Analytics with all roles
1. Disconnect from Site Kit
1. You'll be present with the option to set up Site Kit once more, this time with 3 options (which can be confusing)
1. Select the option to "View limited data"
1. You'll encounter the error, with no obvious way out other then that mentioned above

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/4619aee4-e7fe-49ee-bb38-2aaaf572b40d)

Related to [#5354](https://github.com/google/site-kit-wp/issues/5354)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When a module is in a recoverable state, all widgets associated with it (via their registration) should be replaced by a new component when viewed in the context of the view-only dashboard.
  * The recoverable state should look similar to the [`Data Unavailable`](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--data-unavailable) state of the widget but has different title and message.
  * The title should be `Data Unavailable`
  * The message should be `{Module} data was previously shared by an admin who no longer has access. Please contact another admin to restore it.`
	* For widgets that require multiple recoverable modules, the message should read slightly differently: `The data for the following modules was previously shared by an admin who no longer has access: {Module1, Module2, ...}. Please contact another admin to restore it.`
* The new component when rendered should be treated as a [special widget state](https://github.com/google/site-kit-wp/blob/62db713119c587b2b1a9ec63de4b6e591f899a30/assets/js/googlesitekit/widgets/util/constants.js#L34), similar to gathering data, which when multiple adjacent widgets render the same state, they are combined into a single widget automatically
* Unlike other special widget states, this should be handled outside of the registered widget components but handled automatically by the widget infrastructure based on a widget's registered `modules` and the current set of recoverable modules
  
## Implementation Brief

* Add a new `RecoverableModules` component which takes `moduleSlugs` (`string[]` module slugs) as a prop
  * Renders a `CTA` with the title and message as defined in the AC informing about the recoverable modules
* Add a new `WidgetRecoverableModules` component, similar to `WidgetReportError` which renders `RecoverableModules` (passing through its props to it) and uses the `useWidgetStateEffect` hook internally to set the widget state on mount using `RecoverableModules` as the component and `moduleSlugs` as the `metadata`
* Update `WidgetRenderer` to conditionally override the [`widgetElement`](https://github.com/google/site-kit-wp/blob/affa782aab7b74ad44d8dbb55cdc6a5f2d854806/assets/js/googlesitekit/widgets/components/WidgetRenderer.js#L53) with a `WidgetRecoverableModules` if `widget.modules` contains any recoverable modules, if so, passing the intersection of module slugs as `props.moduleSlugs` to `WidgetRecoverableModules`
  - Note this should only happen in a view-only context (`useViewOnly`)
* Add the `RecoverableModules` to the list of [special widget states](https://github.com/google/site-kit-wp/blob/62db713119c587b2b1a9ec63de4b6e591f899a30/assets/js/googlesitekit/widgets/util/constants.js#L34)

### Test Coverage

* Add Jest tests to cover the basics of this functionality (essentially the alternate component rendered in place of the widget's registered component); 
* A basic test covering widget combination for adjacent widgets with the same state + metadata

## QA Brief

* Site up Site Kit and enable the `dashboardSharing` feature flag.
* Put the Search Console and PageSpeed Insights modules into the recoverable state. This can be achieved by sharing them as a user and then disconnecting that user from Site Kit.
* View the Dashboard in view-only mode with a user whose role the modules were shared with.
* Widgets for the recoverable modules should be rendered using the `RecoverableModules` component:

![image](https://user-images.githubusercontent.com/18395600/176177127-12177462-e4f9-4fb0-8171-2379ef4a438b.png)

## Changelog entry

* Update view-only dashboard to use a new placeholder for widgets that rely on recoverable modules.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv what do you think if we update widgets to display a special state for recoverable modules instead of hiding widgets? In this case, a widget will say that the corresponding module has been configured by an admin that has disconnected his account and the module needs to be re-configured to continue showing their widgets. It will explain the problem and motivate users to reach out to their admins to re-configure the module. What do you think?

cc @felixarntz @marrrmarrr

**Comment by eclarke1** [comment]
Assigning back to @eugene-manuilov to please add AC

**Comment by eugene-manuilov** [comment]
Thanks, @aaemnnosttv. Does AC look good to you?

**Comment by felixarntz** [comment]
@aaemnnosttv I only have higher-level feedback on the IB: I'm wondering, shouldn't we rather make this `RecoverableModule` and have it per module? I realize that it could be multiple modules that need to be recovered, but I think together with that combination logic that approach makes more sense to me since not all modules may need to be recovered at the same time.

So I think the per-module approach is more targeted and also better in line with the other special states we have so far which are typically per module. What do you think about that?

**Comment by aaemnnosttv** [comment]
> shouldn't we rather make this `RecoverableModule` and have it per module? I realize that it could be multiple modules that need to be recovered, but I think together with that combination logic that approach makes more sense to me since not all modules may need to be recovered at the same time.

@felixarntz The problem I see is that this component would replace a widget which doesn't necessarily have a 1:1 relationship with a module (even though most do). If we made it singular to one module, if a widget had multiple recoverable modules it makes sense to surface all of those dependencies, otherwise a user may recover a single module and then still not see the module they are trying to "unlock". Otherwise it could result in a kind of moving target.

If a module isn't truly necessary for a widget to function, it probably shouldn't declare it in its `modules` when registering. Similar to the concept of "viewable modules", a user needs to have read access to all modules a widget is associated with to see it on the shared dashboard.

> I think together with that combination logic that approach makes more sense to me since not all modules may need to be recovered at the same time.

Each widget would only surface the recoverable modules it depends on, not all recoverable modules on the dashboard. Maybe that part wasn't clear?

**Comment by felixarntz** [comment]
@aaemnnosttv 
> Each widget would only surface the recoverable modules it depends on, not all recoverable modules on the dashboard. Maybe that part wasn't clear?

Ahh, that makes total sense. I hadn't thought about that a widget can be associated with multiple modules. If we only group them based on the modules that each individual widget is tied to, then this sounds good.

IB ✅

**Comment by tofumatt** [comment]
Oh, looks like this is good to go into the backlog, maybe there was a Zenhub error here.

I had a look over and this looks good though, so another IB ✅

**Comment by techanvil** [comment]
Hi @aaemnnosttv, as I'm implementing this I've run into a slight hiccup with regard to the requirement to combine the widgets.

At present the [`shouldCombineAllWidgets`](https://github.com/google/site-kit-wp/blob/bec8b62986a509b0df82ea687ba20e3124a34a4d/assets/js/googlesitekit/widgets/util/combine-widgets.js#L49) function is designed to only combine widgets which share the same module (singular), and it accordingly checks `metadata.moduleSlug` for the associated module.

https://github.com/google/site-kit-wp/blob/bec8b62986a509b0df82ea687ba20e3124a34a4d/assets/js/googlesitekit/widgets/util/combine-widgets.js#L57

However this issue introduces a new metadata item, a list of modules, `metadata.moduleSlugs`.

I suspect we should amend `shouldCombineAllWidgets` to handle either `moduleSlug` _or_ `moduleSlugs`, so widgets can be combined if they share the same _set_ of modules rather than singular module.

Does this sound right to you? It seems fairly trivial but I didn't want to just go ahead with the change unilaterally as it's modifying existing behaviour and there are also tests to consider...

**Comment by aaemnnosttv** [comment]
Thanks for raising this @techanvil – I think at one point the engine combined widgets based on equivalent `metadata` rather than checking specific properties within it so I missed this detail when writing the IB.

In the interest of not increasing the scope here (and because most widgets have only a single module), I would suggest we join the widget's modules into a single `moduleSlug` string when constructing the `metadata`, essentially shoehorning it into the current logic. This is a bit of a hack but it should be harmless and have the intended effect for most widgets. We can then open a follow-up issue for how we want to handle this for multi-module widgets.

**Comment by techanvil** [comment]
Thanks @aaemnnosttv, sounds like a plan.

**Comment by mohitwp** [comment]
### QA Update ✅ 

**Verified :**

![image](https://user-images.githubusercontent.com/94359491/176648205-2ab4ed08-2f98-48cc-b7a9-e420f8a0ec7e.png)

![image](https://user-images.githubusercontent.com/94359491/176648291-20f2bf0f-ef0f-4fa4-a5b5-884e1b7fa7d5.png)
