### ISSUE TITLE
UX/UI issue on small screens when adding roles

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5396]
## Bug Description

Odd UX/UI on small screen sizes when you are adding roles on a site that has two admin users. The `Who can manage view access` title appears at the top, but the dropdown appears underneath the user roles.  I was able to recreate on Android and iOS mobile phones. 

See screencast.

https://user-images.githubusercontent.com/73545194/174759046-f569b21b-3537-4dc8-9db5-703d102c12a4.mp4

https://app.asana.com/0/1202258919887896/1202406665934855/f

## Steps to reproduce

On a mobile device: 

1. Go to 'Dashboard sharing settings'
2. Click on 'Add User role' for a module
3. See issue as detailed above

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

* 
I

**Comment by tofumatt** [comment]
I tried to recreate this on the iOS Simulator (iPhone SE and iPhone 13 sizes) and Chrome with responsive design.

I couldn't get this to appear—can you verify if it still happens? And if so: the exact dimensions of the browser (what device?).

Thanks! 🙏🏻

**Comment by wpdarren** [comment]
@tofumatt can I just clarify that you are clicking on the icon to assign a user role to the module.  That's when the styling issue appears. From your screenshot, you are on the dashboard settings before you click the icon to select a user role.  

I have tested this with iPhone 12 Pro and also Samsung S22.   I am using Browser Stack but the same applies when using the Chrome responsible tool.  Please confirm that you are clicking on the icon to view the issue. If you still do not see the issue then I will get some more information for you on dimensions.

**Comment by eclarke1** [comment]
Assigning back to @tofumatt for review here

**Comment by tofumatt** [comment]
Oh, I see now, yes:

![CleanShot 2022-06-22 at 12 34 56](https://user-images.githubusercontent.com/90871/175019774-8715f788-3cd0-4884-a42c-ecf5974a9f3d.gif)

I… am not sure what the solution here is 😅

I suppose it's a bit "odd", but the only "solution" I can think of would be moving the dropdown's label below the list of roles… that said, that would break the grid and I think be equally odd. 🤔

What do you propose would be better/more expected here? I'm inclined to mark this one as a "won't fix" because—while a bit awkward—it's still usable and only causes another element to be oddly placed on a small screen when editing a different element anyway.

**Comment by wpdarren** [comment]
@tofumatt the expected behaviour would be for the dropdown to appear at the side like it does with the inactive module, that said, I totally get your point of how complex of a change it could be when not many users are going to do this task on a mobile phone. It's fine for tablets. I am happy to close this ticket. Thanks for looking into this. 👍
