### ISSUE TITLE
"Add roles" placeholder is missing if the role is deleted or `edit_posts` capability is revoked

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5435]
## Bug Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202443593793369 please see Asana task for background

Steps To Reproduce:

- Using the User Role Editor plugin, add a custom user role and provide edit_posts capability to that role to be available in the DS settings user roles.
- Set the custom role to a module in the DS settings.
- Delete the custom role.
- Or revoke the edit_posts  capability.
- Go to the DS settings modal.

Actual:
The module with the custom role set is currently empty, which is expected. However, the Add roles placeholder is missing. That's due the role is still available in the _googlesitekitDashboardSharingData.settings[module].sharedRoles array. The current logic checks the length of that array and displays the placeholder.

Expected:
Add roles placeholder should be visible if the role is deleted or the edit_posts capability is revoked.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The shared roles of a module must always be a subset of the list of all current shareable roles
    * Non-shareable roles should be filtered out accordingly when saving module sharing settings and when reading/loading the value on the backend

## Implementation Brief

In `includes/Core/Modules/Module_Sharing_Settings.php`:
- Create a new protected filter method `filter_shared_roles` with the following logic:
  * It should receive `shared_roles` as an argument.
  * Filter the `shared_roles` using the `array_filter`.
  * Get the role object using the `get_role` method,
  * Return `false` if the role object does not exist. This means that the role was deleted.
  * Check if the role has the `edit_posts` capability. If it does not, return `false`.
  * Otherwise, return `true`. See:
  https://github.com/google/site-kit-wp/blob/e87bd022874396b3e876a6a25d1710f03b8b7b75/includes/Core/Assets/Assets.php#L823-L826

**For reading data from the backend, the following steps are taken:**

- Within the `Module_Sharing_Settings::get` method, call the `filter_shared_roles` method to get the filtered list of shared roles.
- Return the filtered list of shared roles within the `sharing_settings`.

**For saving data to the backend, the following steps are taken:**

- Similarly to the above, the `Module_Sharing_Settings::get_sanitize_callback` should use the `filter_shared_roles` method to get the filtered list of shared roles.
- Return the filtered list of shared roles within the `sanitized_option`.

### Test Coverage

- In `tests/phpunit/integration/Core/Modules/Module_Sharing_SettingsTest.php`, update the `test_get` and `test_get_sanitize_callback` tests to add coverage for the above scenario.

## QA Brief

* Follow the provided steps to reproduce, and ensure that the "Add roles" placeholder is present, after deleting/revoking the `edit_posts` capability for a custom role.  

## Changelog entry

* Ensure the user role select always displays properly based on current shareable roles.

**Comment by techanvil** [comment]
Hi @hussain-t, here's a bit of commentary on the IB so far.

The `option_` and `default_option_` filters are applied _after_ the value is read from the database. So, in order to filter when _writing_ to the DB we should in fact augment the `Module_Sharing_Settings::get_sanitize_callback` method.

Also because `option_` / `default_option_` are applied after reading from the DB, the change you have suggested to `get_all_shared_roles` should not be necessary.

Mind you another consideration is, seeing as we will be updating `Module_Sharing_Settings::get_sanitize_callback` to filter on write, maybe we should apply the filter-on-read to `Module_Sharing_Settings::get` rather than having this filtering logic spread across `Module_Sharing_Settings` and `Module`. So we could have a reusable `filter_shared_roles` helper method in `Module_Sharing_Settings` and then call that in both `get_sanitize_callback` and `get`...

**Comment by hussain-t** [comment]
Thanks for the suggestions, @techanvil. I have updated the IB.

**Comment by techanvil** [comment]
Thanks @hussain-t!

IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ❌ 

@makiost 

I followed the steps to reproduce the issue. I'm able to reproduce issue on latest environment. 

**Issue:**
When I'm trying to access dashboard sharing settings modal after deleting custom role or after revoking the edit-posts capability. I'm getting below error. 

```
``An error occurred while running 'mapSelect': r.filter is not a function
The error may be correlated with this previous error:
TypeError: r.filter is not a function
    at https://oxious-owl-rupu.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-modules-38f02b97d5e57022eec3.js:15:12899
    at Array.some (<anonymous>)
    at haveSharingSettingsExpanded (https://oxious-owl-rupu.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-modules-38f02b97d5e57022eec3.js:15:12791)
    at https://oxious-owl-rupu.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-0f2805ad9b6a16691225.js:7:80948
    at Object.n [as haveSharingSettingsExpanded] (https://oxious-owl-rupu.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-0f2805ad9b6a16691225.js:7:80518)
    at Object.current (https://oxious-owl-rupu.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-dashboard-c581558eac47ad610d7a.js:41:4437)
    at e (https://oxious-owl-rupu.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-0f2805ad9b6a16691225.js:7:94087)
    at https://oxious-owl-rupu.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-0f2805ad9b6a16691225.js:7:94252
    at https://oxious-owl-rupu.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-0f2805ad9b6a16691225.js:7:83865
    at Array.forEach (<anonymous>)

Original stack trace:

    in Footer
    in footer
    in Unknown
    in div
    in div
    in div
    in t
    in Portal
    in DashboardSharingDialog
    in DashboardSharingSettingsButton
    in div
    in Cell
    in div
    in ForwardRef
    in div
    in ForwardRef
    in header
    in Header
    in DashboardMainApp
    in DashboardEntryPoint
    in RestoreSnapshots
    in ErrorHandler
    in ThemeProvider
    in StrictMode
    in Root``
```

![image](https://user-images.githubusercontent.com/94359491/192765499-f8e47bd8-baa1-4c64-9043-5effd7810b73.png)

**Comment by aaemnnosttv** [comment]
@mohitwp back to you for another pass! Thanks 👍

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@makiost @aaemnnosttv 

- Verified this on main branch.
- Now I'm getting errors mentioned [here.](https://github.com/google/site-kit-wp/issues/5435#issuecomment-1260755465)
- I'm able to reproduce issue on latest environment using user role editor plugin.
- Issue is now resolved on main environment.
- Add roles placeholder is now visible if the role is deleted or the edit posts capability is revoked.
- Dashboard sharing modal settings are getting update on revoking the require access and deleting the user role.

<details>

https://user-images.githubusercontent.com/94359491/194299217-56e5c5ee-4695-47f9-83e6-600ca157cdbe.mp4

</details>

**Issue** : I've found regression issue which not exist on latest environment. I'm not sure if this issue is due to related PR or any another PR. 
When we open dashboard sharing modal first time after refreshing the page then it shows some content on the place of placeholder/user roles and then it shows the actual content. This behavior I've noticed on the latest environment. 


https://user-images.githubusercontent.com/94359491/194299941-17c04566-0a92-48c9-b572-7b119683332d.mp4

FYI - I've notice that if we remove any user role and create another user role using the same id (grant edit post access) and dashboard sharing settings under modal are not changed then new created role automatically gets access under dashboard settings modal due to same id. This can be correct but I will create separate ticket to discuss this just in case if it creates security concern.

cc @wpdarren

**Comment by aaemnnosttv** [comment]
@mohitwp I'm unable to reproduce the flicker you're seeing. Can you try again on the latest on `main`?

**Comment by mohitwp** [comment]
@aaemnnosttv 

I'm able to reproduce issue on dev and main.  
It's weird issue not able to replicate if I disconnect  and again connect analytics module. To reproduce it again I reset the plugin.
Also, it reproducing only when site have more than one admin and analytics module is connected.

**Steps :**

- Create new InstaWP site.
- Set up site kit make sure analytics module is connected.
- Add 2 admin user.
- Go to Site kit dashboard.
- Open dashboard sharing setting modal
- See flicker.
- Again open dashboard sharing settings modal. This time modal will get open without any flicker.
- Refresh the page.
- Open dashboard sharing settings modal.
- See flicker.


**Test environment-**

OS : Windows 11
PHP :8.0
WP version - 6.0.2
Browser - Chrome Version 106.0.5249.62 (Official Build) (64-bit)

https://user-images.githubusercontent.com/94359491/194391608-7fe5a563-0570-4dfe-adf5-137badc99530.mp4

**Comment by aaemnnosttv** [comment]
Thanks @mohitwp – I've identified the changes in #5772 as the cause for your observation here, so let's pick this up on that one.

The QA here can continue apart from this one thing 👍

**Comment by wpdarren** [comment]
@mohitwp while testing 5772, I was unable to recreate the issue on main branch, so the reported regression looks to be fixed. For a second pair of eyes, please could you confirm this when finishing off the QA on this ticket.  Thank you! :)

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified this on main branch.
- Now I'm getting errors mentioned [here.](https://github.com/google/site-kit-wp/issues/5435#issuecomment-1260755465)
- I'm able to reproduce issue on latest environment using user role editor plugin.
- Issue is now resolved on main environment.
- Add roles placeholder is now visible if the role is deleted or the edit posts capability is revoked.
- Dashboard sharing modal settings are getting update on revoking the require access and deleting the user role.
- @wpdarren I verified the issue mentioned [here](https://github.com/google/site-kit-wp/issues/5435#issuecomment-1270530080) on main branch. This issue is now resolved.
Note : I will separate ticket to discuss regarding my observation.

<details>

https://user-images.githubusercontent.com/94359491/194299217-56e5c5ee-4695-47f9-83e6-600ca157cdbe.mp4

</details>

**Comment by aaemnnosttv** [comment]
> * Now I'm getting errors mentioned [here.](https://github.com/google/site-kit-wp/issues/5435#issuecomment-1260755465)

@mohitwp just to confirm, there is no error raised any more (especially one that shows the full page error, e.g. `r.filter is not a function`), correct?

**Comment by aaemnnosttv** [comment]
Thanks @mohitwp – It seems good in my test, I just wanted to double check 👍
