### ISSUE TITLE
Implement TwG setup UI for publication in review scenario

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5527]
Follow-up to #5455: The actual UI for the `SetupPublicationPendingVerification` component should be implemented based on the Figma design.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SetupPublicationPendingVerification` component should have its proper UI implemented, from [this Figma design](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=648%3A6454), reusing the applicable components introduced in #5525.
* The secondary button should technically be a simple link, for now pointing to `https://publishercenter.google.com/` (opening in a new tab).

## Implementation Brief

In `assets/js/modules/thank-with-google/components/setup/SetupPublicationPendingVerification.js`. This component is being implemented in #5455:
- Render the `SetupPublicationScreen` component (which is being implemented in #5525) with the following props:
  * `title` - "Reviewing your account application"
  * `description` - "We received your request to create a Thank with Google account. Check again for updates to your status."
  * Render the `Link` component as children with the translated copy "Check your status". It should have the following props:
    * `href` - `https://publishercenter.google.com/`
    * `external` - `true`
    * `ariaLabel` - "Check your status on Thank with Google Publisher Center"
  * Fix the link styles to match the Figma design.

### Test Coverage

- Verify the `SetupMain` component story for this scenario works as expected.

## QA Brief

* QAing this would require making sure the Thank with Google publication setup "no publication yet" scenario is according to the Figma design as mentioned in the AC.
* The latest Figma design iteration should be used. The latest iteration is four. It can be found [here](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=1781%3A11338).
* For CR, [this story](https://google.github.io/site-kit-wp/storybook/pull/5607/?path=/story/modules-thank-with-google-setup-setupmain--publication-pending-verification) can be used for verification.
* For QA, [this story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-thank-with-google-setup-setupmain--publication-pending-verification) can be used for verification.

## Changelog entry

* Implement TwG setup UI for publication in review scenario.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@nfmohit a few observations to highlight.

1. There's a bit of confusion between the AC, IB and Figma designs for the  `Check your status`  According to the AC it should be a text link, but on the Figma it's a button and in the IB it says fix the link styles to match the Figma design.  Please could confirm if it should be a button or text link? 

2. In the IB it says that the link should be `External - true` - does this mean that we should have the external link icon? 

**Verified:**

- The `SetupPublicationPendingVerification` component has its UI implemented from Figma design.
- The secondary button should technically be a simple link, for now pointing to https://publishercenter.google.com/ (opening in a new tab).
- The `SetupPublicationScreen component` renders with the following props:
  - Title - `Reviewing your account application`
  - Description - `We received your request to create a Thank with Google account. Check again for updates to your status.`
  - The translated copy is `Check your status` :
  - The link href is - `https://publishercenter.google.com/`
  - Accessibility ariaLabel - `Check your status on Thank with Google Publisher Center`

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/180772862-77c28391-b8e7-4cd7-a173-0612debaeab0.png)
![image](https://user-images.githubusercontent.com/73545194/180772880-29b86020-dc14-4e60-a396-e586c848a57f.png)

</details>

**Comment by nfmohit** [comment]
Thank you for spotting this @wpdarren!

I believe the AC and IB were written using the second iteration of the Figma design, which I followed mistakenly as well. I'm moving this back to execution to add a new PR updating the button design to match with the latest iteration (iteration four).

**Comment by aaemnnosttv** [comment]
Ready for another pass @wpdarren 👍

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The `SetupPublicationPendingVerification` component has its UI implemented from Figma design.
- The secondary button should technically be a simple link, for now pointing to https://publishercenter.google.com/ (opening in a new tab).
- The `SetupPublicationScreen component` renders with the following props:
  - Title - `Reviewing your account application`
  - Description - `We received your request to create a Thank with Google account. Check again for updates to your status.`
  - The translated copy is `Check your status` :
  - The link href is - `https://publishercenter.google.com/`
  - Accessibility ariaLabel - `Check your status on Thank with Google Publisher Center`

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/180772862-77c28391-b8e7-4cd7-a173-0612debaeab0.png)
![image](https://user-images.githubusercontent.com/73545194/180772880-29b86020-dc14-4e60-a396-e586c848a57f.png)
![image](https://user-images.githubusercontent.com/73545194/181221575-11f8bb73-e292-4c44-8534-6747afa4d580.png)

</details>

**Note:** there are some font type/size differences and these were also flagged in [5528](https://github.com/google/site-kit-wp/issues/5528#issuecomment-1192386429) The response was that what we are seeing is correct, because the figma are focused on GM3, and we've gone with how we display other module splash screens.
