### ISSUE TITLE
Implement TwG setup UI for no publication yet scenario

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5528]
Follow-up to #5455: The actual UI for the `SetupCreatePublication` component should be implemented based on the Figma design.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SetupCreatePublication` component should have its proper UI implemented, from [this Figma design](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=648%3A3898), reusing the applicable components introduced in #5525.
* The button should technically be a simple link, for now pointing to `https://publishercenter.google.com/` (opening in a new tab).

## Implementation Brief

In `assets/js/modules/thank-with-google/components/setup/SetupCreatePublication.js`. This component is being implemented in #5455:
- Render the `SetupPublicationScreen` component (which is being implemented in #5525) with the following props:
  * `title` - "Create your Thank with Google account"
  * `description` - "To get started, create an account. Currently available only in the US."
  * Render the `Button` component as children with the translated copy "Create account". It should have the following props:
    * `href` - `https://publishercenter.google.com/`
    * `target` - "_blank"
    * `ariaLabel` - "Create your Thank with Google account"
  * If a class was created for the `Button` component to match the Figma designs in #5525, add it to the `Button` component.

### Test Coverage

- Verify the `SetupMain` component story for this scenario works as expected.

## QA Brief

* QAing this would require making sure the Thank with Google publication setup "no publication yet" scenario is according to the Figma design as mentioned in the AC.
* For CR, [this story](https://google.github.io/site-kit-wp/storybook/pull/5608/?path=/story/modules-thank-with-google-setup-setupmain--create-publication) can be used for verification.
* For QA, [this story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-thank-with-google-setup-setupmain--create-publication) can be used for verification.

## Changelog entry

* Implement TwG setup UI for no publication yet scenario.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@nfmohit  I have a some observations that I'd like to run by you. 

1. When I click on the `Set up Thank with Google` link in the connect more services tab: no oAuth page appears asking me to sign into my Google account.   From the figma designs, this should happen.  I think this is because it isn't set up yet, but don't want to make any assumptions. Please could you confirm? 

2. There are a few differences on my test side when comparing it with FIgma. I am assuming that these are expected but because it doesn't mention them in the QAB, I'll raise them here: 
    - Experimental and US only labels do not have a background colour. 
    - Says 'Connect Services' rather than 'Connect Service' 
    - The description text is different compared with AC/IB. Mentions about disconnecting if non US site. 
    - The TwG logo is 33 x 33 pixels but is 40x39 pixels, and it does look bigger.  
    - The font sizes are different, e.g.. Google Sans text is 14px on my site but 16px on figma. Google Sans display is 24px on my site but should be 16px according to the figma designs. 
 
3. Interested to know what you think about the amount of white space between the title, description and button, to where the graphic is located.  Maybe it's my screen resolution, but the graphic looks a little lost due to its size.  This could be because of my screen resolution.  Maybe this is something we can raise with UX, interested in your thoughts. 

4. For mobile, it's the opposite of point 3 above. There's not enough white space, the graphic, title, description and button look quite compact and tested this on a few different iOS and Android devices.  Also, the 'Connect Service' text looks a little lost at the top.  Interested in your thoughts on this.  We don't have any figma designs, so we might want to get UX involved. 

![image](https://user-images.githubusercontent.com/73545194/180406221-c4592b71-ee24-4630-8daa-3bafa9bc5128.png)

**Verified:**

- The `SetupCreatePublication` matches the figma design:
  - title - `Create your Thank with Google account`
  - description - `To get started, create an account. Currently available only in the US.`
  - The Button has copy `Create account`
  - The button href is `https://publishercenter.google.com/` which opens up in a new window. 
  - The button has an ariaLabel - "Create your Thank with Google account"

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/180404070-0b650dd5-4abb-4706-a265-62647f16a0db.png)
![image](https://user-images.githubusercontent.com/73545194/180406316-4ad70420-57c1-429c-9b34-042fd1c34395.png)

</details>

**Comment by aaemnnosttv** [comment]
> 1. When I click on the `Set up Thank with Google` link in the connect more services tab: no oAuth page appears asking me to sign into my Google account.   From the figma designs, this should happen.  I think this is because it isn't set up yet, but don't want to make any assumptions. Please could you confirm?

@wpdarren it will, but the module does not require any additional scopes yet (probably because it doesn't use the Google APIs at all yet) so this will come in the future.

> 2. There are a few differences on my test side when comparing it with FIgma.
> * Experimental and US only labels do not have a background colour.

I'm guessing this is expected. We can check with UX. 

> * Says 'Connect Services' rather than 'Connect Service' 

Should remain consistent using singular like we have elsewhere (in this case Figma is incorrect). Looks like this is missing entirely in the setup component though.

> * The description text is different compared with AC/IB. Mentions about disconnecting if non US site.

Copy in the designs usually isn't final and we probably want to refine this before launch anyways.

> * The font sizes are different, e.g.. Google Sans text is 14px on my site but 16px on figma. Google Sans display is 24px on my site but should be 16px according to the figma designs.

Font sizes should remain consistent with other modules in setup. This may be a GM3 detail which will come later, I'm not sure.

> * Interested to know what you think about the amount of white space between the title, description and button, to where the graphic is located.  Maybe it's my screen resolution, but the graphic looks a little lost due to its size.  This could be because of my screen resolution.  Maybe this is something we can raise with UX, interested in your thoughts.

Do you mean the graphic is far off to the side? Could you share a screenshot to clarify what you're referring to?

> 4. For mobile, it's the opposite of point 3 above.

Would you please share a screenshot for this as well?

**Comment by nfmohit** [comment]
Thank you so much for helping out here with the confirmations, @aaemnnosttv!

Chiming in here to try and help with the follow-up questions (@wpdarren please object if I'm wrong, thanks!).

> Do you mean the graphic is far off to the side? Could you share a screenshot to clarify what you're referring to?
I believe yes, that's what Darren was referring to. The space between the text column and the graphic on wider screens seems far too big. Screenshot:
![image](https://user-images.githubusercontent.com/73545194/180406221-c4592b71-ee24-4630-8daa-3bafa9bc5128.png)

> For mobile, it's the opposite of point 3 above.
> > Would you please share a screenshot for this as well?

In mobile, the spacing between the graphic and the text column seems too short.
![image](https://user-images.githubusercontent.com/73545194/180412713-108aa822-cbf1-4657-a029-e4c718949896.png)

**Comment by wpdarren** [comment]
@aaemnnosttv Thanks for clarifying my observations.   As per @nfmohit screenshots above. This is what I am seeing for issue 3 and 4 in my original comment.

**Comment by nfmohit** [comment]
@aaemnnosttv @wpdarren Just FYI, I've opened a [new PR](https://github.com/google/site-kit-wp/pull/5608) that addresses the follow-ups to this issue. For now, it only contains the update to the icon/logo size as mentioned in point 2(d) [here](https://github.com/google/site-kit-wp/issues/5528#issuecomment-1192386429).

If we decide to make any more changes, I'll include that in the PR.

**Comment by nfmohit** [comment]
We had some more discussion about this in Slack [here](https://10up.slack.com/archives/CBKKQEBR9/p1658830012470639?thread_ts=1658820980.475529&cid=CBKKQEBR9) and decided to move this into CR for now.

To address issues 3 and 4 [here](https://github.com/google/site-kit-wp/issues/5528#issuecomment-1192386429), @wpdarren could you open a new GH issue to be looked at by the UX team? It can be also worth mentioning splash screens like [this](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/setup-using-proxy-with-sign-in--start-user-input) as that has a similar structure and looks similar in wider/mobile screens.

**Comment by aaemnnosttv** [comment]
@wpdarren on closer inspection, the current icon in the setup flow is consistent with all other modules so let's keep it at the current size 👍  see https://github.com/google/site-kit-wp/pull/5608#pullrequestreview-1051407059

Back to you for another pass !

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

**Verified:**

- The `SetupCreatePublication` matches the figma design:
  - title - `Create your Thank with Google account`
  - description - `To get started, create an account. Currently available only in the US.`
  - The Button has copy `Create account`
  - The button href is `https://publishercenter.google.com/` which opens up in a new window. 
  - The button has an ariaLabel - "Create your Thank with Google account"

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/180404070-0b650dd5-4abb-4706-a265-62647f16a0db.png)
![image](https://user-images.githubusercontent.com/73545194/180406316-4ad70420-57c1-429c-9b34-042fd1c34395.png)

</details>

**Note:** there are some font type/size differences and these were flagged in this ticket. The response was that what we are seeing is correct, because the figma are focused on GM3, and we've gone with how we display other module splash screens.
