### ISSUE TITLE
Stacked header notices

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5549]
## Bug Description

Asana bug bash issue: https://app.asana.com/0/1202258919887896/1202583202387112 please see Asana task for background and additional comments.

It's possible to encounter multiple stacked notices, as per the screenshot within this task. 

In my case I never dismissed the "Congrats" notice, and then from another admin account disconnected from SK. When revisiting and refreshing the dashboard for admin2, I encounter the module recovery notice below the congrats notice. 

Previous GH issue on this: https://github.com/google/site-kit-wp/issues/4689

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/2a62c8cb-397d-458f-b2ac-ff63e53f6e78)

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
I've been able to reproduce this a couple of times when cancelling the OAuth permissions screen during TwG module setup. Images below:


![image](https://user-images.githubusercontent.com/41326532/191932557-fdfec8d6-9d51-4d93-93d8-361445fa9cfe.png)


![image](https://user-images.githubusercontent.com/41326532/191932607-5f504da3-9331-432a-af2e-853e83e8d7bc.png)

## Steps to reproduce

1. Setup a site and include Analytics (on a site which is valid for TwG)
2. During Analytics setup select the option to create a new property, so no data exists
3. Connect the TwG module
4. During the OAuth permissions screen cancel, rather than granting permissions
5. Stacked notices appear

**Comment by aaemnnosttv** [comment]
This was addressed in https://github.com/google/site-kit-wp/issues/5550

See https://app.asana.com/0/0/1202583202387112/1202599911711587/f for more detail.
