### ISSUE TITLE
Unable to receive access token because of an unauthorized client.

### ISSUE THREAD

**Issue by DeeElla** [google/site-kit-wp#555]
Google Site Kit.. Hello!!
How can I resolve this? What am I missing? Any support would be greatly appreciated.

Many thanks!

**Comment by jamesozzie** [comment]
@DeeElla In order to try and complete setup please attempt the following:
1. Open the Site Kit created project from your [Google Cloud Console](https://console.cloud.google.com/cloud-resource-manager)
2. [Delete](https://i.imgur.com/EoA1edo.png) the project 
3. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
4. Start the Site Kit setup process again from your WordPress dashboard

If that results in the same error please provide some more information on your setup and we can troubleshoot further, the following information would be of use:
- Is the site you are trying to setup a multi site network install?
- Can you share your [Site Health info](https://i.imgur.com/Rtkmsba.png) from your WordPress dashboard?

**Comment by DeeElla** [comment]
Hi there
Thank you for your generous response.
Here's an update!
Been at it all morning. There was an issue as I had another site live which
has been removed.
GA will not verify my website as a different tracking code is being used.
Not sure how I set the original tracking code up as to my knowledge I'm the
only one doing this.
Therefore, I can't connect to search console or SiteKit ;-(
I did however upload Monstor Insights this morning as a shortcut to GA. It
could be that getting in the way?
What are your thoughts?
Extra help would be greatly appreciate. If there is a cost, then please let
me know!
I look forward to hearing from you.
Dee

**Comment by jamesozzie** [comment]
@DeeElla There could be Analytics tracking code added via another plugin, your theme or another implementation method. If you check the source code of your website and look for a "UA-" reference it might give you an indication of how it was implemented. If you are using the amp plugin it could even be implemented in JSON format via the analytics tab. 

There is no need to remove Monster Insights, but maybe temporarily deactivate before attempting to setup the Analytics module from within Site Kit. You will see a previous issue with troubleshooting conflicts on this at #155. 

If you want to share your [Site Health info](https://i.imgur.com/Rtkmsba.png) from your WordPress dashboard we can see if there is anything we notice.

**Comment by jamesozzie** [comment]
@DeeElla Did you have any luck setting up Site Kit along with the Analytics module in the end?
