### ISSUE TITLE
AdSense snippet not enabled by default

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#556]
## Bug Description

The Adsense snippet output should be enabled by default, but controllable via settings.

Currently it is enabled by default in the settings as properly defaults when passing to the JS for Site Kit admin, but any other references to the option are not handled in the same way.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* AdSense snippet should be consistently opted-in by default, unless it's explicitly opted-out.

## Implementation Brief

* Update the `option_` filter in the Adsense module's `register` method to set `useSnippet` to true only if `! isset`.

## Changelog entry

* Fix insertion of AdSense snippet not being consistently enabled by default.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
I'm unclear on how to QA this as I couldn't switch AdSense accounts in the admin; my usual account has no AdSense data but trying to load one with data ended up in a loop:

![2019-09-20 14 28 36](https://user-images.githubusercontent.com/90871/65330719-218c9100-dbb3-11e9-8164-880b91a5ffaf.gif)

Un-assigning myself for now as even with a Google Account with AdSense I don't seem to be able to access this screen. Is this a known bug?

**Comment by aaemnnosttv** [comment]
Actually, I've noticed that same thing with the Switch Google Account link - I'll open an issue for it.

I haven't been able to figure out how to do that manually other than resetting Site Kit :/

**Comment by adamsilverstein** [comment]
I did a few tests and this looks good. I activated adsense with an account that included the domain and got the setup complete message with the toggle defaulting to on:

![image](https://user-images.githubusercontent.com/2676022/65541600-e4821080-deca-11e9-832f-5680410c1873.png)

I checked with an account that had AdSense but not the domain set up:

![image](https://user-images.githubusercontent.com/2676022/65545046-d388cd80-ded1-11e9-8bc9-413da056212c.png)

Checking the source code of the site front end I correctly see the AdSense script snippet inserted (indicating the option is enabled).

**Comment by felixarntz** [comment]
Something was odd in my testing regarding the AdSense flow (not caused by this), so I couldn't test it - but I'll trust @adamsilverstein's QA (plus the code change is simple enough to see it's doing the right thing).

Regarding the issue: I saw the following screen although I was testing on an entirely new site (i.e. I didn't have that domain set up in AdSense yet):
<img width="1485" alt="Screenshot 2019-09-26 at 11 02 58" src="https://user-images.githubusercontent.com/3531426/65674829-7f0a5d00-e04d-11e9-8282-8b731b0c6cdb.png">
Clicking on the blue link led me to AdSense where I could create that domain. This screen probably shouldn't show in that scenario though because it sounds like I don't need to do anything - which I clearly _do_ need to (the domain doesn't even exist yet in AdSense). Any idea / background on this @adamsilverstein?

**Comment by adamsilverstein** [comment]
@felixarntz I left a comment on the PR. I would actually expect the tag to be placed on your site if you have a valid account that has used AdSense somewhere before - is that the case?

The message actually be the correct one although I can see how it is confusing and the link seems wrong. You probably do need to take some action to resolve this - ie manually adding the domain to your account, and I would expect to see something more like:

![image](https://user-images.githubusercontent.com/2676022/65802228-44312380-e138-11e9-9092-30878997c62a.png)

Not certain about this though, so I would like to check with the AdSense team to see if that happens automatically now (it may) and if they can help fix the page that shows when following the link to make it more helpful.

You can also try adding the site into your AdSense account and then repeating the setup flow.
