### ISSUE TITLE
Top content widget: Pageviews and Unique Pageviews table headers overlap at a 601px wide viewport.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5561]
## Bug Description

On the "Top content..." widget, the **Pageviews** and **Unique Pageviews** table headers overlap at a 601px wide viewport.

## Steps to reproduce

1. View the Dashboard with a 601px viewport.
2. Scroll to the "Top content..." widget
3. See the overlapping table headers.

## Screenshots

Version 1.79.0 RC1:
![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/21fb9cef-fcbe-4f6c-972d-b7f2a8b00104)

Notice how the overlap has increased slightly compared to the pre-GM2+ styling.

Version 1.78.0:
![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/d08856ce-b29b-4fce-b64a-d96c24e4a74d)

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: discovered on Chrome
 - Plugin Version: 1.79.0 RC1
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
@techanvil the change here looks rather small but looks like there is definitely room for improvement at this viewport in general. Any ideas how we could better adapt this to smaller viewports?

**Comment by techanvil** [comment]
Hey @aaemnnosttv, having dug into this a bit, the approach I would suggest is to allow the word "pageviews" to be hyphenated to avoid the overflow.

I can see that we have applied CSS hyphenation to the table headers as a general fix to avoid overflowing - as seen here in commit https://github.com/google/site-kit-wp/pull/749/commits/ac63a441cafa554fea3663f5646db02521e53e12.

Looking at the table in other languages it can be seen in action, for example here in German:

![image](https://user-images.githubusercontent.com/18395600/180270608-49043523-b750-4e12-9169-256d3a76d228.png)

Note the overflow having unticked the `hyphen: auto` rule in devtools:

![image](https://user-images.githubusercontent.com/18395600/180270795-821e0ad6-ed0a-45a8-9530-45aae8903926.png)

The problem with the English version is that "pageviews" is not a standard word and the browser doesn't know how to hyphenate it.

The approach I would therefore suggest is to let the browser know that "pageviews" can be hyphenated by inserting a [soft hyphen](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#suggesting_line_break_opportunities) into the word, i.e. `'Page\u00ADviews'`. We could create a utility function to keep the code clean and reusable rather than inlining this funky string. It works as expected - and should gracefully degrade where not supported.

_At 601px:_
![image](https://user-images.githubusercontent.com/18395600/180276014-ad849366-d31e-49b7-9c26-5942f767c0ee.png)

_When the screen is wide enough (827px in this case):_
![image](https://user-images.githubusercontent.com/18395600/180276253-0af3e23b-0cd0-47f0-8c18-08e47f980427.png)

---

I did consider some alternative approaches, for the sake of argument:

1. Reduce the width of the Title column (currently 50%) to allow more space for the metric columns. It would need to be reduced to about 44%. However, modifying the table dimensions seems less than ideal, if it's not strictly necessary.

_Title column width 44%, viewport width 601px:_
![image](https://user-images.githubusercontent.com/18395600/180276829-a759a306-383c-49e1-b518-47849d25f6c7.png)

2. Apply CSS overflow and ellipses rules, and add a tooltip to the headers. The glaringly obvious disadvantage being the text is no longer fully visible and the user would need to interact with the tooltip to read it.

![image](https://user-images.githubusercontent.com/18395600/180277804-f3e7f093-9efc-46a7-aae3-b853aaa1f4fa.png)

3. Simply reduce the font. Another overly drastic measure.

_Font reduced to 12px:_
![image](https://user-images.githubusercontent.com/18395600/180278205-fe198d44-b53a-450c-a5e6-2f3ca9da30e2.png)

There are probably some other tweaks that could be made to the layout, but I think the hyphenation is the cleanest approach and is in keeping with our existing use of CSS hyphenation. I guess the only question is whether there's any concern about the "correctness" of hyphenating "pageviews" as I have proposed.

Interested to hear your thoughts!

**Comment by aaemnnosttv** [comment]
Thanks @techanvil! I had no idea soft hyphens were a thing!

I feel like the problem is rooted in showing more than 2 columns in a relatively small space. That is, if it were just Title and one more metric, it would be fine but we're cramming in a few and the column headings are hard to fit well, especially when you start considering i18n.

I'd be interested to see how feasible it would be to use icons to represent the headings (other than Title). E.g. 

- Pageviews  
![visibility_FILL0_wght400_GRAD0_opsz48](https://user-images.githubusercontent.com/1621608/181838709-4997ee69-67eb-4288-b665-a6f1d9dfd834.png)
- Unique pageviews  
![visibility_off_FILL0_wght400_GRAD0_opsz48](https://user-images.githubusercontent.com/1621608/181838742-d62d6caf-df33-445b-9cd7-045423a344da.png)
- Bounce rate  
![call_missed_outgoing_FILL0_wght400_GRAD0_opsz48](https://user-images.githubusercontent.com/1621608/181838624-29945966-0c1e-46fe-a8e4-dc39eac83aba.png)
- Session duration  
![timer_FILL0_wght400_GRAD0_opsz48](https://user-images.githubusercontent.com/1621608/181838852-d5850bf9-4f00-4797-905c-677ed23db846.png)

These are just ideas from the [icon set](https://fonts.google.com/icons) but then we could also keep the current names as tooltips for accessibility and clarity as to what it means.

**Comment by aaemnnosttv** [comment]
@sebastianmantel any suggestions for what we could do here?

**Comment by sebastianmantel** [comment]
@aaemnnosttv we change the font style of those parameters to 12px [body-small] and that will fix the issue. WDYT?

**Comment by techanvil** [comment]
Closing as this is covered by the more recent #7563, although the findings of this issue will still be relevant.
