### ISSUE TITLE
Upgrade legacy AdSense account and site statuses

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5628]
## Feature Description

With the new and improved AdSense v2 setup flow, we're able to display more accurate information on a user's AdSense account and site statuses. Since #5503 this has been surfaced in the settings as well.

However, users who set up AdSense before the v2 setup flow was released will still have the older statuses in the module settings which prevent us from showing more accurate information about the current state.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense overview widget in the Site Kit dashboard should be adjusted to include a migration for old AdSense account and site statuses, as follows:
    * If the `adsenseSetupV2` flag is enabled but the `accountStatus` or `siteStatus` settings use one of the legacy (V1) statuses, a new component should be included on top of the widget body (i.e. within the `Widget` component, but before the `Overview` component).
    * This component should run the API requests to determine the actual account and site status, similar to the setup. Roughly:
        * Look up the account object based on the current `accountID`.
        * Look up the AFC client for that account and check the account's `state` value, and based on both of these determine whether the `accountStatus` is `ready` or something else, basically a subset of how the V2 `SetupAccount` component does it.
        * Look up the current site within that account and check that site's `state` and `autoAdsEnabled` values, and based on both of these determine whether the `siteStatus` is `ready` or something else, basically a subset of how the V2 `SetupAccountSite` component does.
    * If based on those API requests both the `accountStatus` and `siteStatus` result in `ready`, the two module settings should be updated on the fly, and the component should simply return `null` (render nothing). Otherwise, it should not update the module settings, but render the following:
        * A small inline warning notice (similar to e.g. https://google.github.io/site-kit-wp/storybook/main/?path=/story/global-notices--settings-warning-notice) to inform that AdSense appears to not be fully connected, with message: _You need to redo setup to complete AdSense configuration_
        * A primary CTA button with message _Redo setup_ which does the following on click:
            * Set the `accountSetupComplete` and `siteSetupComplete` flags to `false`.
            * Link to the AdSense setup flow. (From there the necessary logic will run to update the account/site status as needed and guide the user through the missing steps, as usual.)

## Implementation Brief
* Create `StatusMigration` function component. 
    * Get `accountID`, `afcClient`, `site` and `adminReauthURL` using `getAccountID`, `getAFCClient`, `getCurrentSite` and `getAdminReauthURL` selectors of `MODULES_ADSENSE` store. 
    * Determine whether both account and site is in `READY` state using the following. 
        * If either `afcClient` or `site` is `undefined`, set `isReady` as  `undefined`.
        * if either `afcClient.state !== API_STATE_READY`, `site.state !== API_STATE_READY` or, `! site.autoAdsEnabled`, set `isReady` as  `false`.
        * Otherwise `isReady` is `true`. 
    * Have an effect that runs when value of `isReady` changes:
        * If `isReady` is false-y, do nothing and return early. 
        * Otherwise, set the `accountStatus` and `siteStatus` to `ACCOUNT_STATUS_READY` and `SITE_STATUS_READY` using `setAccountStatus` and `setSiteStatus` actions of `MODULES_ADSENSE` store. 
    * Return `null` from the component if `isReady` is `undefined` or `true`. 
    * Otherwise, render the UI with copies described in the AC using `SettingsNotice` and `Button`. 
        * Clicking on the button should do the following:
        * Set `accountSetupComplete` and `siteSetupComplete` flags to false using `setAccountSetupComplete` and `setSiteSetupComplete` actions. 
        * Navigate to Adsense Setup flow using `navigateTo` action of the `CORE_LOCATION` store with `adminReauthURL` url. 
* In `assets/js/modules/adsense/util/status.js`:
    * Define two functions `isLegacyAccountStatus` and `isLegacySiteStatus` that returns `true` whenever passed `{account|site}Status` argument is one of the v1 `{account|site}` status. See [here](https://github.com/google/site-kit-wp/blob/0eb9173f2d96b892bce5c6b5cb6f081916df143e/assets/js/modules/adsense/util/status.js#L19-L47) and check for the v1-only status. 
* In `assets/js/modules/adsense/components/module/ModuleOverviewWidget/index.js`: 
    * Get the `accountStatus` and `siteStatus` using `getAccountStatus` and `getSiteStatus` selectors of `MODULES_ADSENSE` store. 
    * Using the previously created utility functions, determine whether `accountStatus` and `siteStatus` are legacy. 
    * If `adsenseSetupV2Enabled` is `true` and either `status` is legacy, render the `StatusMigration` component above the `Overview` component. 

### Test Coverage

* Add tests for the newly added util functions and component. 

## QA Brief

* Complete AdSense Setup without enabling `adsenseSetupV2` feature flag.
* Ensure both site and account has legacy account setup defined here using the following JS snippets. 
```js
googlesitekit.data.select('modules/adsense').getAccountStatus();; // approved

googlesitekit.data.select('modules/adsense').getSiteStatus(); // added
```
* Enable `adsenseSetupV2` feature flag and go to monetization of the dashboard. 
* If the site is `READY`, there should be no additional UI and the status will get migrated to `ready` for both on the fly (wait a few sec before running the snippets above to check.)
* If the site is not ready, there will be a new UI on top of the Monetization section asking user to redo setup as described in the AC, clicking the CTA should take the user to AdSense setup. 

## Changelog entry

* Add the migration notice to the AdSense overview widget for legacy accounts.

**Comment by felixarntz** [comment]
@aaemnnosttv Is this about sites which already have AdSense connected? Since for sites that still have to go through finishing the setup, I think the statuses should update to the new ones by itself.

Regarding sites with AdSense already connected, this is a tricky one. Of course, one thing we could do is just display the corresponding _new_ "approved/ready/connected" account status and site status for those sites and hope that everything is fine. Or, another approach that would take more effort could be something like this:
* If a site has one of the old "approved/ready/connected" statuses _and_ the AdSense report request returns no data, we could re-introduce something like that old AdSense special "zero data state" box, however with different content.
* In that component, we could then run checks for the AdSense account and site, and if it turns out they are not set up, we could show a notice that "You still need to do something to fully configure AdSense".
* Then there could be a button, which on click deletes the two account status and site status module options (effectively bringing the module back to "not connected" state) and then redirects the user to the AdSense setup flow where they will land in the right place.

cc @marrrmarrr

**Comment by aaemnnosttv** [comment]
@felixarntz, yes this is about updating saved v1 statuses in the AdSense settings. Not sure if sites that aren't connected yet would benefit from this or not but connected sites would primarily benefit since these would have been set up (potentially years ago) and then not touched.

I wasn't thinking we'd do anything in response to report data. Instead, I think we could do the migration on-the-fly, perhaps in the settings-view and settings-edit components. If a v1-specific status is detected, we'd run the necessary queries to "upgrade" the status to determine the current v2 status that we're already doing in module setup. It could probably be a bit simpler as the accountID would already be known.

As an aside, it might be worth thinking about explicitly versioning the schema in the settings in the future.

**Comment by felixarntz** [comment]
@aaemnnosttv For not connected sites that still have to go through module setup, this is no problem anyway as the new status will be detected as soon as they open the module setup again. So migration is only relevant for sites where AdSense is already connected.

However, the problem is that the v1 "connected" statuses for the account and site are too generic and inaccurate to map 1:1 to a v2 status, since in v1 we didn't know a whole lot of things which in v2 are now setup-blocking. We could run the queries like you're saying, but that could lead to the module being not connected anymore when it was connected before. That may be fine, but I think it would be an unexpected user experience to suddenly have the module no longer connected without having done anything.

That's why in my previous comment I suggested to do it only on demand if the report is empty, but most importantly invoked by the user explicitly with a button like I mentioned there.

**Comment by aaemnnosttv** [comment]
@felixarntz thinking about this a bit more, the connected state is based on the `(account|site)SetupComplete` options, [which are already migrated from the v1 `setupComplete` option](https://github.com/google/site-kit-wp/blob/c52372a7d671838094a5dde70d437bd36d4370c4/includes/Modules/AdSense/Settings.php#L118-L123). So as long as the site is already connected, why not migrate the `approved` v1 account and `added` site statuses to v2 `ready`? Then I think we'd only need to run the upgrade for accounts with a `disapproved|graylisted|pending` status, although I would think these wouldn't reach `setupComplete` and thus not connected anyways, correct?

Alternatively, we should be able to safely migrate all the v1-only statuses without affecting the connected state of the module as that is determined by settings which are independent from those statuses. Then, if we later detected a mismatch (i.e. non-`ready` account or site which is marked setup completed), we could flag this to the user and prompt them to restart the setup for the module. Note, there is already some ["legacy account status" migration](https://github.com/google/site-kit-wp/blob/c52372a7d671838094a5dde70d437bd36d4370c4/includes/Modules/AdSense/Settings.php#L111-L116) in place which splits a single value into v1 account and site statuses which should also be accounted or here.

What do you think?

**Comment by felixarntz** [comment]
@marrrmarrr I discussed the approach here earlier today with @aaemnnosttv, and we aligned on what would be the best way to migrate users that are still on V1 statuses. I've captured the plan in the ACs, pending the exact wording for the notice we're envisioning. Please have a look, though it may be helpful to talk through this in person for more context.

**Comment by marrrmarrr** [comment]
@felixarntz I added suggested wording, PTAL and if it LGTY, let's go with this.

**Comment by FlicHollis** [comment]
Hi @felixarntz and @aaemnnosttv following Mariya's update are we good to get this moved to IB? Thanks!

**Comment by kuasha420** [comment]
@techanvil solid suggestion, I've added this point to the IB. Cheers.

**Comment by techanvil** [comment]
Thanks @kuasha420!

IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA update: ⚠️ 

@eugene-manuilov @techanvil tagging you in the absence of Arafat.   

Within the tester plugin I have set AdSense to `Approved` and `Added`. The `adsenseSetupV2` is not enabled.  

I then connect AdSense and all looks initially fine.  When I go to the dashboard though I see a message `Insufficient permissions in AdSense. Your Google account does not have sufficient permissions to access AdSense data, so you won’t be able to see stats from it on the Site Kit dashboard. This service was originally connected by the administrator "muyapotuca3774" — you can contact them for more information.` 

As you can see from the screenshot below, I am logged in as that user. 

I think the issue is, that since the AdSense V2 has been rolled out to 100% a new site by default will have `adsenseSetupV2` enabled because when I run the code in the QAB, the status comes back as 'Ready' and 'Ready'  Any ideas how we can test this with the feature flag disabled and any thoughts on the error message that I am seeing? 

I have tried playing around with the tester plugin but as you can see in Site Health, its showing the feature as enabled. 

![image](https://user-images.githubusercontent.com/73545194/235674137-37b5877b-a119-4290-a19a-f1ec571b4db9.png)

![image](https://user-images.githubusercontent.com/73545194/235672086-598ca9ba-686d-4f28-a51c-3c20d069905d.png)

![image](https://user-images.githubusercontent.com/73545194/235672979-87002b87-d218-4bd8-b970-73f821e4d5dd.png)

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@kuasha420 I am getting a fatal error when enabling `adsenseSetupV2` and clicking on the `monetization` tab on dashboard.  Here are the steps I took to test this:

1. Setup AdSense with `adsenseSetupV2` disabled.  In the tester plugin I set the AdSense status to `approved` and `added` which are the legacy statuses. When I went back to the dashboard, and ran the code in the QAB, the correct status appeared. I went to the dashboard and no problems with the monetization widgets loading. 

![image](https://user-images.githubusercontent.com/73545194/236454024-e41a1bd8-5dff-4796-aaab-771cb054b25d.png)
![image](https://user-images.githubusercontent.com/73545194/236454047-42325c4e-3ada-4fe9-95bd-8e12d4f0abc4.png)

2. I then enabled the `adsenseSetupV2`  feature flag and changed the status of the AdSense settings to `ready` and `ready`.  Then, I went to the dashboard, clicked on the monetization chip. The widgets initially loaded then the error message appears. Here are the screenshots and details of the error message:

```
`Cannot read properties of undefined (reading 'state')

    in StatusMigration
    in div
    in div
    in Widget
    in WithWidgetSlug(Widget)
    in ModuleOverviewWidget
    in WhenAdsenseActive(ModuleOverviewWidget)
    in WidgetRenderer
    in div
    in Cell
    in WidgetCellWrapper
    in div
    in Row
    in div
    in div
    in Grid
    in WidgetAreaRenderer
    in div
    in WidgetContextRenderer
    in DashboardMainApp
    in DashboardEntryPoint
    in RestoreSnapshots
    in ErrorHandler
    in ThemeProvider
    in StrictMode
    in Root`
```

![image](https://user-images.githubusercontent.com/73545194/236454772-92df55a7-ac44-480b-ac31-693e1f522308.png)
![image](https://user-images.githubusercontent.com/73545194/236454790-fa7e14b1-ddd4-4707-b1b9-04949666a075.png)

This is a screenshot of my tester plugin settings

![image](https://user-images.githubusercontent.com/73545194/236454961-ad916adf-e0f3-426c-a415-3aee2b72c35f.png)

**Comment by kuasha420** [comment]
@wpdarren Thank you for your detailed QA report here. The first issue is not due to the changes made here but how the feature flags interact with each other. You need to set "Always Override" in the Tester Plugin and then enable `dashboardSharing` and toggle `adsenseSetupV2` as needed. 

For the second issue, it's a mistake in the code and I'll create a follow up PR fixing this momentarily. Cheers!

**Comment by aaemnnosttv** [comment]
Back to you @wpdarren for another pass 👍

**Comment by kuasha420** [comment]
@wpdarren @aaemnnosttv There's another oversight in the newly created `StatusMigration` component that it doesn't save the changed settings. 

As a result, 

* The `ready` state doesn't get persisted and the migration runs every time.
* When the site is not `ready`, user will get navigated to the setup without `{account|site}SetupComplete` states being saved.

Silly mistake on my part as I wasn't fully familiar with the AdSense(V2) setup flow when I wrote the initial IB. I only caught this while working for an Ad Blocker Detection IB. 

I'll pull this one back from QA and open another follow up PR to address this. 

Cheers.

**Comment by wpdarren** [comment]
@kuasha420 @techanvil  I am not sure if I am being silly here 😄  but.. 

The last part of the QAB:

> If the site is not ready, there will be a new UI on top of the Monetization section asking user to redo setup as described in the AC, clicking the CTA should take the user to AdSense setup.

I’m a bit confused on how to trigger this to test it.

**Comment by kuasha420** [comment]
@wpdarren Thanks for your diligence here. I've addressed all 3 of your concern in the follow up PR. Cheers.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- If the site is `READY`, there is no additional UI and the status gets migrated to ready. I ran the snippets in the QAB to make sure that the correct statuses appeared for account and site. 
- If the site is not ready, there is a new UI on top of the Monetization section asking user to redo setup as described in the AC, clicking the CTA takes the user to AdSense setup.
  - A small inline warning notice appears to inform that AdSense appears to not be fully connected, with message: You need to redo setup to complete AdSense configuration
  - A primary CTA button with message Redo setup which does the following on click
  - Link to the AdSense setup flow. 

details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/9f094f66-3fef-4712-829f-2e6d8f9fd3ee)
![image](https://github.com/google/site-kit-wp/assets/73545194/07854ecf-a604-4521-90ce-9b5f2c032632)
![image](https://github.com/google/site-kit-wp/assets/73545194/0a2eff34-7da4-41f2-9d1e-a5e98b481c58)
![image](https://github.com/google/site-kit-wp/assets/73545194/581025cd-b01b-4f20-91e1-da0d07a2128c)

</details>
