### ISSUE TITLE
Remove no longer used ActivateModuleCTA and CompleteModuleActivationCTA components

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5678]
## Feature Description

Following on from https://github.com/google/site-kit-wp/issues/5148, the `ActivateModuleCTA` and `CompleteModuleActivationCTA` components are no longer in active use and can be removed.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- Confirm that `ActivateModuleCTA` and `CompleteModuleActivationCTA` are not in active use, i.e. they are no longer being rendered by any component.
- If so, remove them and all related, no longer needed code.

## Implementation Brief

**Remove `ActivateModuleCTA` component and its usages**
- Git remove the `assets/js/components/ActivateModuleCTA.js` file.
- Git remove the `stories/activate-module.stories.js` file.
- Git remove the `assets/js/googlesitekit/widgets/components/WidgetActivateModuleCTA.js` file if it was not removed as part of #5148.
- Git remove the `assets/js/googlesitekit/widgets/components/WidgetActivateModuleCTA.test.js` file.
- Remove the usages of the `ActivateModuleCTA` component from the following files:
  * `assets/js/components/adminbar/AdminBarWidgets.js`,
  * `assets/js/components/wp-dashboard/WPDashboardWidgets.js`,
  * `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js`,
  * `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview.js`,
  * `assets/js/googlesitekit/widgets/util/constants.js`,
  * `assets/js/googlesitekit/widgets/util/get-widget-layout.test.js`,
  * `assets/js/googlesitekit/widgets/util/is-inactive-widget-state.test.js`
 
**Remove `CompleteModuleActivationCTA` component and its usages**
- Git remove the `assets/js/components/CompleteModuleActivationCTA.js` file. 
- Git remove the `stories/complete-module-activation.stories.js` file.
- Git remove the `assets/js/googlesitekit/widgets/components/WidgetCompleteModuleActivationCTA.js` file if it was not removed as part of #5148.
- Git remove the `assets/js/googlesitekit/widgets/components/WidgetCompleteModuleActivationCTA.test.js` file.
- Remove the usages of the `CompleteModuleActivationCTA` component from the following files:
  * `assets/js/components/adminbar/AdminBarWidgets.js`,
  * `assets/js/components/wp-dashboard/WPDashboardWidgets.js`,
  * `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js`,
  * `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview.js`,
  * `assets/js/googlesitekit/widgets/util/constants.js`
  * `assets/js/googlesitekit/widgets/util/combine-widgets.test.js`

### Test Coverage

- Update VRT images and E2E tests if necessary.
- Ensure all the existing Jest tests are passing.

## QA Brief

- Perform a brief smoke test to verify widgets still render correctly:
   * Set up Site Kit with a few modules - Analytics and AdSense should suffice.
   * Navigate to the Dashboard and verify the widgets are rendering as expected.
- Check the [special combination widget stories](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global-widgets-widget-area--special-combination-states) in Storybook are working properly.

## Changelog entry

* N/A.

**Comment by techanvil** [comment]
@aaemnnosttv I have added this issue along with the AC, please could you take a look?

**Comment by aaemnnosttv** [comment]
@techanvil this could probably be done in #5148 as well if this is where the last remaining usage is for those as that issue is also about removing unused code. We can follow up with this one if needed but seems potentially unnecessary. Otherwise, this LGTM, we'd just want to mark 5148 as a dependency.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
@hussain-t Can you please provide more information under QAB here apart from the smoke test of whole plugin like if there is any module, component, or functionality can get impact due to the changes introduced under this PR. 
Thank you !

cc @wpdarren

**Comment by wpdarren** [comment]
@mohitwp @hussain-t  looking at this ticket, it seems to be a change related to activating modules and also cancelling the activation. Is this correct?  I feel the QAB is very sparse and we could do with some more direction here, especially since this ticket is only a 7 and a smoke test of the entire plugin is going to take considerably longer.

**Comment by hussain-t** [comment]
@mohitwp @wpdarren, thanks for bringing this up. The PR removes the legacy code. So, there is nothing specific to be tested. However, I have updated the QAB. LMK if that sounds helpful. Cheers!

**Comment by mohitwp** [comment]
### QA Update ✅ 

Verified-

- Verified this using oi.ie site and dev plugin.
- Verified this for zero data states - zero and gathering.
- Verified and compared all widgets data with latest release.
- Verified WP dashboard widgets.
- All widgets are rendering fine.

<details>

![image](https://user-images.githubusercontent.com/94359491/190960082-bdf0354a-5a7c-43fe-a3e0-2b4a88d79095.png)

![image](https://user-images.githubusercontent.com/94359491/190960096-cccb2af8-6ab1-41a5-a267-d0f2c240a9ab.png)

![image](https://user-images.githubusercontent.com/94359491/190960111-523c07eb-1b2b-4e67-a0a9-1a4a56b271eb.png)

![image](https://user-images.githubusercontent.com/94359491/190960134-3f1878dd-b3c6-4535-b8f4-37cf9ad9e88e.png)

![image](https://user-images.githubusercontent.com/94359491/190960149-d2d73546-4d26-402e-9774-b1a6cae9f245.png)

![image](https://user-images.githubusercontent.com/94359491/190960171-b759e226-2f07-4210-8d86-c7d5a3f9b05d.png)

![image](https://user-images.githubusercontent.com/94359491/190960185-5218d560-1382-4f6b-a627-1a51c015cacd.png)

![image](https://user-images.githubusercontent.com/94359491/190960206-ee6a7484-5ac3-4432-9772-6128e1fe2d16.png)

![image](https://user-images.githubusercontent.com/94359491/190960218-e25e9474-cb14-49eb-acad-48149f4604ec.png)

</details>

**Comment by felixarntz** [comment]
## Approval ⚠️ 

@techanvil @hussain-t The PR now adds `RecoverableModules` (and thus a `WidgetRecoverableModules`). I'm not sure why that was decided, but it doesn't make sense to me, and it is also neither part of the ACs nor IB. This has production code / API implications, hence it has to be considered. It may also not in fact work as expected because we pass an array to it rather than a string, which works differently in comparisons in JS. Anyway, the latter is not really my point.

If this was only done to replace the components in unit tests, shouldn't we rather simply remove those unit tests since they are no longer applicable? Having taken a look at #5779, I think some of the unit test modifications there don't make sense and should rather be removed (since the related components were removed as well). We still have coverage for the overall `combineWidgets` logic through `ReportZero`.

cc @aaemnnosttv

**Comment by techanvil** [comment]
Hi @felixarntz, thanks for raising this.

To be clear, the `RecoverableModules` and `WidgetRecoverableModules` components were added via a previous [issue](https://github.com/google/site-kit-wp/issues/5376) and we don't want to remove those. However there is an unwanted addition here of `WidgetRecoverableModules` to `assets/js/googlesitekit/widgets/util/get-widget-component-props.js` that was missed in Code Review.

@hussain-t, would you be happy filing a followup PR here to remove `WidgetRecoverableModules` and updating/removing unit tests that reference it?

**Comment by felixarntz** [comment]
@techanvil Thanks for clarifying, I wasn't aware of that. In that case, I would almost reverse my concern and ask, why _wasn't_ that component included in `getWidgetComponentProps` prior? Apologies as I don't have the full context here, but just want to make sure we're making the right call there.

**Comment by aaemnnosttv** [comment]
> why _wasn't_ that component included in `getWidgetComponentProps` prior?

@felixarntz because `RecoverableModules` is rendered by `WidgetRenderer` rather than the widget itself since we already know it depends on a recoverable module, there's no point in rendering it. Adding it to the widget's component props wouldn't make sense because it would require every single module to implement the same behavior. See https://github.com/google/site-kit-wp/issues/5376 for more context.

**Comment by felixarntz** [comment]
Thanks @aaemnnosttv. Okay, in that case I think we're good to close this one. Thanks everyone for clarifying.
