### ISSUE TITLE
Improve UX for AdSense setup incomplete module message in Settings

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#5693]
## Feature Description

As discussed in our August 15 meeting, currently, when a user sets up AdSense in Site Kit but there is still an issue on the AdSense side that is keeping ads from displaying, the following message displays in Site Kit > Settings > Connected Services:

<img width="862" alt="image" src="https://user-images.githubusercontent.com/12189958/184670506-b188dd46-5700-4845-9510-f48a948ea42e.png">

Clicking "continue module setup" takes the user to a screen that, as part of the AdSense Setup Improvements work, includes details on why AdSense isn't fully set up yet. , this also includes a 

This is confusing to many users as it seems to indicate to them that they did not "complete" the module setup on the Site Kit side and the AdSense code was not placed successfully. However, they have completed setup; they just need to take care of issues on the AdSense side.

Some possible changes to consider:

* Change the "AdSense is not connected" message that displays on Site Kit > Settings > Connected Services to "AdSense needs your attention" or another phrase that doesn't include something specifically about the "connection." Many support users consider the connection to be the successful integration of Site Kit with the service (in this case, AdSense). So when they see "not connected," they think there was a failure in the Site Kit module setup process, which is not the case here.
* Change the "Setup incomplete: continue module setup" message. If it can be longer, something like: "Site Kit has added AdSense code to your site, but AdSense cannot currently display ads. [LINK]Review issues[/LINK]

cc @jamesozzie @adamdunnage @marrrmarrr @felixarntz 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the AdSense section in Settings is closed, replace the current status message "AdSense is not connected" with _"Action required"_ and the alert icon (already displayed now). 
* If the section is expanded, replace the current message "Setup incomplete: continue module setup" with _"AdSense code placed, but no ads displayed yet. Review issues."_  ("review issues" should be the external link). 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment]
@bethanylang @jamesozzie @adamdunnage do these "issues" on the AdSense side mean the person should just wait (e.g. their account is in review), or do they actually need to do something? 
I think the copy here should reflect if an action is required or not.

**Comment by jamesozzie** [comment]
@marrrmarrr Adding to the above, from the AdSense platform, I believe some users were previously stuck in a situation whereby they have used Site Kit to insert their AdSense code, but the AdSense platform was not recognizing this placement if their site was not yet approved. I was not able to recreate this today, from various attempts.

The below is now the experience from the AdSense platform, without a snippet check from what I can see:

![image](https://user-images.githubusercontent.com/41326532/187942517-2e71b35f-6696-4d25-b25f-5c02786c142f.png)

Assuming that there is no longer a check for a valid snippet from the AdSense platform, I don't see any issues. There could be the following improvements:
1. A link to the Site Kit plugin website, within the "_if you use Site Kit_" text.
2. A link to documentation for the "_Make sure you've let Site Kit put code on your site_" text.

**Comment by aaemnnosttv** [comment]
@marrrmarrr the ACs are a bit out of date here I think as we've already changed the status text for unconnected modules to be a CTA button. You can see it here as it is for Analytics and GA4, but the same would apply for any other active but unconnected module:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/1621608/191269791-e5705f03-7975-47c9-bd6e-493b50a27fc2.png">
https://google.github.io/site-kit-wp/storybook/develop/iframe.html?id=settings--connected-services&args=&viewMode=story

**Comment by FlicHollis** [comment]
@aaemnnosttv and @marrrmarrr following on from Bethany's comments above, if we can agree on the AC update then we can prioritise this and add to Sprint 88.
cc @bethanylang and @nfmohit

**Comment by marrrmarrr** [comment]
@aaemnnosttv my understanding of the "Connect Google Analytics 4" chip that we added to the Settings page is that it is for modules which are completely unconnected (i.e. setup hasn't started at all). 
Whereas for this case for AdSense, the setup has been started, but there is an extra action required. Since based on Bethany and James's comments it seems the main confusion comes exactly from this, I think a good solution here would be to surface the exact state with the wording already in the ACs ("action required").

**Comment by jamesozzie** [comment]
Adding to this that I've been testing this today, and I can see room for improvement. 

### Improvement one: A text change when a site hasn't yet been reviewed / approved

At present if an AdSense user uses Site Kit to add a new site to AdSense, the status within the Site Kit settings page will always display the a "_You need to fix some things before we can connect Site Kit to your AdSense account_" message. This isn't really accurate, as their site is pending an AdSense review. Their site may be approved _without_ any changes. I have a [recording of this scenario here](https://recordit.co/x5pL8eot3m), a scenario which is very common.

![image](https://user-images.githubusercontent.com/41326532/198671063-c4f57bc5-f67c-43d5-ac10-d369967989a8.png)

A relatively straightforward improvement here, is to change the text as per the below:

```diff
-   You need to fix some things before we can connect Site Kit to your AdSense account.
+   Your site has not yet been approved for ads by the AdSense team.
```

### Improvement Two: A text change on the CTA button when viewing your AdSense connection status

There is also a possible improvements for the status that appears when viewing the connected services tab, before a user edits their AdSense settings. This isn't as straightforward, as it would require a check each time the "Connected services" screen is accessed. One solution here is to change the wording, so users don't see a "Complete setup" CTA and end up in a loop. An improvement can be viewed in the image below:

![image](https://user-images.githubusercontent.com/41326532/198675834-efd86303-7064-4c1b-8e9e-c2d404ff51e1.png)

### Improvement Three: Modifying the AdSense link if a user revisits their AdSense settings

Finally, a third improvement which would help a lot of users would be to improve the "Review AdSense Account" CTA on the settings screen where a users site is not yet reviewed.

At present it links to the AdSense homepage:
`https://accounts.google.com/accountchooser?continue=https%3A%2F%2Fwww.google.com%2Fadsense%2Fnew%2Fu%2F0%2Fpub-*******%3Fsource%3Dsite-kit&Email=***email*** `

It would ideally direct users to the "Sites" page, so they can easily view their site status:
`https://www.google.com/adsense/new/u/2/pub-*******/sites/my-sites`


 ----------------

It's also very easy to see why users are confused with the set up process. I have the steps to recreate, along with additional comments highlight issues:

1. Set SK on a new site with your Google account (which already has an AdSense account)
2. Connect the AdSense module
3. You'll be asked to "[Add this site to your AdSense account](https://i.imgur.com/jnT8pTQ.png)"
4. You're then directed to the AdSense platform when you can continue to add the site. **It's not clear at this point** if the site is in review, but users would likely click on the "[Request review button](https://i.imgur.com/tqhFaVu.png)"
5. Users then might revisit their Site Kit settings to check the AdSense status, and the status shows that they [need to fix some things](https://i.imgur.com/jwJq0OW.png). **This isn't the case, their site is in review.** 
6. Users then may open a support topic or reach out in the AdSense Help Center. 
7. Users also may click on the ["Review AdSense Account" button](https://i.imgur.com/mr28KZw.png) where they're **directed to the AdSense homepage, which doesn't show their AdSense site status**

@bethanylang I've summarized a few different issues which are very common above. I'm not sure if these can/should also be addressed within this GitHub issue, or if they require further consideration and discussion. We'll need to know the next steps in order to proceed.

**Comment by FlicHollis** [comment]
Thanks so much @jamesozzie, I am assigning back to @marrrmarrr for review.

**Comment by bethanylang** [comment]
@marrrmarrr Adam, James, and I discussed this a bit further in our support sync today and we identified another area for improvement here – outlining it below, but let me know if it would be better on its own. cc @FlicHollis  

This goes back to the same overarching issue that @jamesozzie flagged, where the kind of "pending" state of the AdSense setup in Site Kit can be confusing to users. In this case, none of the settings for AdSense display in Site Kit > Settings > Connected Services > AdSense until the "Setup incomplete" message has been resolved, usually by their site being approved.

This is challenging because the easiest way for users to confirm that SK has placed their AdSense code snippet – a major issue that we see confusion about on the forums – is to go Site Kit > Settings > Connected Services > AdSense and see "AdSense Code: The AdSense code has been placed on your site":

<img width="669" alt="image" src="https://user-images.githubusercontent.com/12189958/199262247-969e8754-3d10-4777-970a-f865c43487d8.png">

However, this does not display in the Settings until the site has been approved, even though the user selects if they want SK to place their code as part of the initial setup process _before_ they have approval.

Ideally, it would be great if that message (and the Let Site Kit place AdSense code on your site toggle when you click Edit) would display from the moment that the AdSense module is first connected, regardless of your site's approval status or other issues. This would allow users to easily verify that their code has been inserted and that that is not an issue blocking next steps for displaying ads.

Let me know if you have any questions!

**Comment by felixarntz** [comment]
@jamesozzie For the situation on "Improvement one" from https://github.com/google/site-kit-wp/issues/5693#issuecomment-1295162491, what are the AdSense account status and AdSense site status values in Site Health?

One thing I notice in that scenario is that the screenshots are technically somewhat mismatched: The Site Kit message refers to the AdSense _account_ requiring some fixes, whereas the AdSense frontend screenshot is for the _site_ being reviewed. I'm curious what the AdSense frontend would display on the account level in this scenario. Nonetheless, there is a potential flaw in Site Kit's logic right now around when that message is shown. Could you please share the concrete AdSense account status value from the situation so that I can assess whether the displayed UI is expected or not then?

**Comment by jamesozzie** [comment]
@felixarntz In the example I had for **_Improvement one_** this was on a site which was likely disapproved on AdSense before.  I may have then removed it from the list of my sites in my AdSense account. This is possibly the reason the site was appearing in SK initially as not having being added, before then ending up in a "You need to fix some things" state, while in AdSense it appeared as "Not reviewed". 

I tested this more with other scenarios today. The outcome I feel is that the there are no mismatching status' between SK and AdSense.

In all cases tested the proposed UX improvements still apply. See below different scenarios tested today:

### A new site being added to an approved AdSense account for the first time 
The behavior and status throughout the SK setup flow is correct and as expected ([recording of set up flow](https://recordit.co/OlyXGN4Kx3)). 

- Status within AdSense: [Getting Ready](https://i.imgur.com/fVbnG5K.png)
- Status within a users SH info: getting-ready
- SK settings screen status: [Not-connected - Setup incomplete - Continue module setup](https://i.imgur.com/K7tcZqv.png)
- SK settings screen - when clicking on "_Complete Module Setup_": [Your site is getting ready](https://i.imgur.com/epufsEe.png)
- Proposed improvement 1 - **Not applicable**. The status shows in SK as getting ready, as it is in AdSense. 
- Proposed improvement 2 - **Applicable**. 
- Proposed improvement 3 - **Applicable**.
- Proposed improvement 4 ([From Bethany's comments](https://github.com/google/site-kit-wp/issues/5693#issuecomment-1298621674) - to display the snippet placement status on the AdSense status screens) - **Applicable**


### A site previously not approved as it requires attention ([needs-attention status](https://i.imgur.com/4ahfNsw.png)) being added _before_ confirming any issues previously resulting in the site not approved were addressed) 

The behavior and status throughout the SK setup flow is correct and as expected. If a user doesn't confirm they addressed any action areas identified by AdSense the status doesn't change to `getting-ready` when checking my SH info and the status on AdSense directly remains as needs-attention ([recording of set up flow](https://recordit.co/9H4tDmBbwt)). 

- Status within AdSense before SK set up: [Needs attention ](https://i.imgur.com/wQSXa3l.png)
- Status within SK  (SH info) after SK set up: [needs-attention](https://i.imgur.com/lSs8Zz3.png)
- Status within AdSense after SK set up: [Needs attention ](https://i.imgur.com/wQSXa3l.png)
- SK settings screen status: [Not-connected - Setup incomplete - Continue module setup](https://i.imgur.com/K7tcZqv.png)
- SK settings screen - when clicking on "_Complete Module Setup_": [Your site isn't ready - You need to fix some things ](https://i.imgur.com/lXfdFDh.png)
- Proposed improvement 1 - **Applicable**.  
- Proposed improvement 2 - **Applicable**. 
- Proposed improvement 3 - **Applicable**.
- Proposed improvement 4 ([From Bethany's comments](https://github.com/google/site-kit-wp/issues/5693#issuecomment-1298621674) - to display the snippet placement status on the AdSense status screens) - **Applicable**

### A site previously not approved as it requires attention ([needs-attention status](https://i.imgur.com/4ahfNsw.png)) being added _after_ confirming any issues previously resulting in the site not approved were addressed) 

The behavior and status throughout the SK setup flow is correct and as expected. If a user does confirm they addressed any action areas identified by AdSense, the status changes to [`Getting ready` in the AdSense platform](https://i.imgur.com/XkHhXFD.png) immediately, and this is reflected if then going into SK and connecting AdSense. ([recording of set up flow](https://recordit.co/Je9cWsNIQQ)). 

- Status within AdSense before SK set up: [Needs attention ](https://i.imgur.com/wQSXa3l.png)
- Status within AdSense after confirming you've addressed any action areas [Getting ready](https://i.imgur.com/XkHhXFD.png)
- Status within SK (SH info) after SK set up: [getting-ready](https://i.imgur.com/qbtXIsb.png)
- Status within AdSense after SK set up: [Getting ready](https://i.imgur.com/XkHhXFD.png)
- SK settings screen status: [Not-connected - Setup incomplete - Continue module setup](https://i.imgur.com/K7tcZqv.png)
- SK settings screen - when clicking on "_Complete Module Setup_": [Your site is getting ready](https://i.imgur.com/epufsEe.png)
- Proposed improvement 1 - **Applicable**.  
- Proposed improvement 2 - **Applicable**. 
- Proposed improvement 3 - **Applicable**.
- Proposed improvement 4 ([From Bethany's comments](https://github.com/google/site-kit-wp/issues/5693#issuecomment-1298621674) - to display the snippet placement status on the AdSense status screens) - **Applicable**

### A site previously not approved as it requires attention ([needs-attention status](https://i.imgur.com/4ahfNsw.png)) being removed from my list of AdSense sites before confirming I addressed any action items 

I did encounter a mismatching of AdSense status here, with the SH info tab showing as `needs-review` although this eventually changed to `getting-ready` after I refresh the SH status for a second time (not evident in the recording). The behavior and status throughout the SK setup flow is correct and as expected. ([recording of experience](https://recordit.co/drWRcXCozd))
- Status within AdSense before SK set up: [Needs attention ](https://i.imgur.com/wQSXa3l.png)
- Status within SK (SH info) after SK set up: Requires-review and eventually [getting-ready](https://i.imgur.com/qbtXIsb.png)
- Status within AdSense after SK set up: [Getting ready](https://i.imgur.com/XkHhXFD.png)
- SK settings screen status: [Not-connected - Setup incomplete - Continue module setup](https://i.imgur.com/K7tcZqv.png)
- SK settings screen - when clicking on "_Complete Module Setup_": [Your site is getting ready](https://i.imgur.com/epufsEe.png)
- Proposed improvement 1 - **Applicable**.  
- Proposed improvement 2 - **Applicable**. 
- Proposed improvement 3 - **Applicable**.
- Proposed improvement 4 ([From Bethany's comments](https://github.com/google/site-kit-wp/issues/5693#issuecomment-1298621674) - to display the snippet placement status on the AdSense status screens) - **Applicable**

**Comment by FlicHollis** [comment]
Hi @felixarntz please could you review @jamesozzie comment when you get a second? 
For now I will remove this from Sprint 88 whilst we clarify ACs and IBs, but as soon as this is ready we can prioritise and add to a sprint. 
cc @bethanylang

**Comment by eclarke1** [comment]
Just a suggestion but it may be worth jumping on a call here to hash this out, screenshare and to cut out some back and forth 😃

**Comment by bethanylang** [comment]
@felixarntz Circling back on this one – maybe worth having a call for all of us, as Em suggests?

**Comment by bethanylang** [comment]
@felixarntz Checking in again here, thanks!

**Comment by jamesozzie** [comment]
Closing this as we've created the following individual issues based on [suggestions within thread](https://github.com/google/site-kit-wp/issues/5693#issuecomment-1295162491):
- **Improvement one**: A text change when a site hasn't yet been reviewed / approved (https://github.com/google/site-kit-wp/issues/8075)
- **Improvement two**: A text change on the CTA button when viewing your AdSense connection status (https://github.com/google/site-kit-wp/issues/5401)
- **Improvement three**: Improvement Three: Modifying the AdSense link if a user revisits their AdSense settings
 (https://github.com/google/site-kit-wp/issues/8076)
