### ISSUE TITLE
Scaffold new `googlesitekit-api` script

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#570]
## Feature Description

Let's introduce a standalone `googlesitekit-api` script that provides the foundational infrastructure to make Site Kit REST API requests. This API layer should be based on existing logic from `data.js`, but be implemented in a way that is decoupled from some of the very specific legacy bits intertwined with `data.js`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The script should expose an object `googlesitekit.api` with the following methods:
    * `get( type, identifier, datapoint, data )`
    * `set( type, identifier, datapoint, data )`
    * `useCache( enable )` (both to set and get; by default, every request should use the cache)
    * `invalidateCache( type, identifier, datapoint )`
* The script should in scope of this issue just define the methods, with their signatures and corresponding docs. Follow-up issues will take care of actual implementation. The PR should therefore be opened against a feature branch.
* All files that are part of the script should be found in `assets/js/googlesitekit/api`, with an `index.js` file as module entry point that exports the main object as default. An additional file `assets/js/googlesitekit-api.js` should exist for the actual entry point that imports the object from `./googlesitekit/api` and exposes it under a `googlesitekit.api` global. This extra step is used to separate the actual implementation from how we expose it. Essentially everything in `assets/js/googlesitekit/api` should be almost as if it was its own package.
* The script should be registered under a `googlesitekit-api` handle in the `Core\Assets\Assets` class. For now, no other script should depend on that script.
* The script should be be added as an external to the Webpack config, so that a script doing `import ... from 'googlesitekit-api'` in the build resolves as `const ... = googlesitekit.api`.

## Implementation Brief

* Create an `assets/js/googlesitekit` and `assets/js/googlesitekit/api` folder for the new code to reside in. Place code in these files and make sure they can be imported within the project.
* In `assets/js/googlesitekit-api.js`, import `assets/js/googlesitekit/api` and expose it globally as `googlesitekit.api`. If the `googlesitekit` global isn't available, throw an error specifying that `googlesitekit` should be loaded to load this file.
* Add webpack external for `'[assets/]js/googlesitekit/api'` that resolves to `googlesitekit.api`

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
As mentioned in #573, I think it's worth discussing whether `getBatch()` should be a separate function or integrated into `get()` (explicitly with an array and/or "behind the scenes" by automatically batching requests).

-----

> The script should in scope of this issue just define the methods, with their signatures and corresponding docs. Follow-up issues will take care of actual implementation. The PR should therefore be opened against a feature branch.

What do you mean _The PR should therefore be opened against a feature branch._? As this PR would define the functions as no-ops and they wouldn't be in-use, would it not be okay to create this branch against develop? The code wouldn't be imported by any other code yet so presumably will not even be included in a production webpack build.

-----

Regarding:

> All files that are part of the script should be found in `assets/js/api`, with an `index.js` file as module entry point that exports the main object as default. An additional file `assets/js/googlesitekit-api.js` should exist for the actual entry point that imports the object from `./api` and exposes it under a `googlesitekit.api` global. This extra step is used to separate the actual implementation from how we expose it. Essentially everything in `assets/js/api` should be almost as if it was its own package.

I have a few issues with this approach to the folder structure:

1. It removes the folder structure for the new `googlesitekit` package. If we have a folder named `assets/js/googlesitekit`, within it we can create `assets/js/googlesitekit/api` and the folder structure will match the global object's `googlesitekit.api`. I think this is a superior developer experience and less confusing.
2. It creates an unneeded file: `assets/js/googlesitekit-api.js`. If our `assets/js/googlesitekit/api/index.js` file export a default object which is used to create `googlesitekit.api`, we don't need the intermediate file `assets/js/googlesitekit-api.js`. I also think the `assets/js/googlesitekit-api.js` is a bit confusing to have to explicitly import in the project, when we can `import { api } from 'googlesitekit';` instead using Webpack configs to do the right thing. Or we could do `import api from 'googlesitekit/api';` if preferred.

What do you think of this approach?

**Comment by felixarntz** [comment]
@tofumatt 
`getBatch()` should definitely remain separate for now. We haven't fully defined yet whether we're going to keep the batching at all, because it most likely ends up worth in overall perceived performance (all requests have to wait until the slowest one has been completed). The only reason to keep it is to limit server load. It's good that you bring that up though, because that leads me to that we shouldn't implement `getBatch()` at all for now. We can re-evaluate once we have usage of our `googlesitekit.api` to see whether there's a need for it. I'll update the ACs to drop this method.

Regarding the branch, yes, theoretically it's fine since it's not used, but still, this is a new feature and won't be ready for consumption after this issue alone is completed, so let's keep it in a separate branch until the functionality is complete for an MVP.

Regarding the structure: I like the suggestion of using `assets/js/googlesitekit/api`, that makes sense. Let's do it.

> we don't need the intermediate file `assets/js/googlesitekit-api.js`

It would never be imported in development code, but it would be an individual Webpack entry point, because we should end up with a file production file `googlesitekit-api.js` that exposes `googlesitekit.api`.

**Comment by tofumatt** [comment]
> It would never be imported in development code, but it would be an individual Webpack entry point, because we should end up with a file production file googlesitekit-api.js that exposes googlesitekit.api. If there is another (cleaner) way to make googlesitekit.api available in a standalone production file, I'm open for suggestions.

Ah, gotcha! That approach makes sense, and I think is straightforward. It'll be good to mark those files with comments explaining their intended use, just so developers don't import them. 😄

**Comment by tofumatt** [comment]
Given these APIs will be public—and especially given they may change over time—it would be nice to adopt an object arguments approach instead of the positional arguments currently used. Consider:

```js
googlesitekit.api.get( TYPE_MODULES, 'search-console', 'matched-sites' );
// vs
googlesitekit.api.get( {
  datapoint: 'matched-sites',
  identifier: 'search-console',
  type: TYPE_MODULES,
} );
```

One approach much more clearly implicitly documents what the code is doing and makes it clearer to both 1st-party and 3rd-party developers what's happening. (I think it already makes clear that our keys could use some thought, but already it looks better to me.)

Most importantly, using an object for arguments allows easier extensibility in the future. If we want to add/remove/change these fundamental APIs, we can do so without adding new positional arguments. For a public API, and especially one this fundamental to the plugin, I think that's a better approach.

What do you think about this approach @felixarntz @aaemnnosttv?

**Comment by felixarntz** [comment]
@tofumatt 
The object makes it more implicit, but also less obvious what you have to pass given the function signature (`api.get( type, identifier, datapoint, data )` vs `api.get( args )`). Another argument for keeping individual arguments is that they each rely on each other. Passing an `identifier` but no `type` will not work right now for example.

There's definitely room to discuss, but we can easily make such changes also in the future if necessary (while maintaining BC for a while). I suggest for now we stay with the design as-is.

**Comment by tofumatt** [comment]
Alright, we'll stick with positional arguments for now!

I think we can still throw errors if required keys are missing (`invariant` is a nice tool for this, see something like https://github.com/mozilla/addons-frontend/blob/master/src/amo/reducers/reviews.js#L169-L183), and docs would help with figuring out what keys are required in the `{ args }` approach (the function signature could even be `get( { type, identifier, datapoint, data } = {}  ) ` to clarify in the code).

There's room to discuss for now, but once the API is "publicised" to third-parties it'd be easier not to have them have to migrate. Anyway, not a big deal. 😄

-----

IB ready for review, the only thing I think should change in the AC is the mapping of `'googlesitekit-api '` to `googlesitekit.api`. I would prefer to keep internal imports consistent with the directory structure of the codebase instead of resembling how they'll look once built. This is a trend in the existing codebase with aliases like `GoogleModules` (https://github.com/google/site-kit-wp/blob/39e8d2de110dd34c8c6711239b3018b41d1545b8/webpack.config.js#L97) that makes it more difficult to find the code that's being imported and doesn't serve an obvious purpose for developers on the project. So I think aliasing `'assets/js/googlesitekit/api'` to `googlesitekit.api` makes more sense. We might want to setup webpack to allow the `assets/` prefix to be omitted, but that's unrelated to the issue.

I think going forward with the JSR we should be improving the import path setup, so I'm starting here 😄. If that sounds good could you update the AC to reflect the module alias I suggested in the IB? After that we'll be set 😄

**Comment by felixarntz** [comment]
@tofumatt 
> So I think aliasing `'assets/js/googlesitekit/api'` to `googlesitekit.api` makes more sense. We might want to setup webpack to allow the `assets/` prefix to be omitted, but that's unrelated to the issue.

Can you clarify what that would look like in the code? Are you saying the code would do something like `import { get } from 'googlesitekit.api'`? My thinking was to use the same approach that Gutenberg is taking and consider every individual JavaScript bundle file is own "package", which I'd argue it actually is, even if we don't distribute them individually on npm or elsewhere. If you understand it like that as well, I'm not sure how `googlesitekit.api` would be a better name than `googlesitekit-api`, especially since the latter would definitely be the name for the script on PHP side (since they always use dashes).

I'm happy to update ACs as needed, but I don't fully understand what you're suggesting I think.

**Comment by tofumatt** [comment]
Ah, sorry! I was a bit unclear.

What I meant to say is that in our webpack build step (at least for production), we'd alias any import of `'assets/js/googlesitekit/api'` to `googlesitekit.api`, but that internally we'd reference `'assets/js/googlesitekit/api'` directly, not an intermediate like `'googlesitekit-api'`. Those intermediates just add a layer between webpack and a developer trying to reference the right file.

So in the plugin we should write:

```js
import { get } from 'assets/js/googlesitekit/api'

// Do stuff...
```

which webpack would compile to:

```js
const { get } = googlesitekit.api;

// Do stuff...
```

in production.

I'm saying we shouldn't use `'googlesitekit.api'` _or_ `'googlesitekit-api'` as the module path in JS. Let's just start using the file paths direction and remove a layer of obfuscation from our internal code.

**Comment by felixarntz** [comment]
IB ✅

**Comment by felixarntz** [comment]
@tofumatt I see you put #572 to "In Progress". Are you planning to cover this one here as part of a single PR? Just a bit confused since this is technically a prerequisite.

Let's make sure we don't overload a PR with too many things.

**Comment by tofumatt** [comment]
Ah, I just started scaffolding out parts of #572 while waiting, but no: the plan is discrete PRs for each issue and nothing too large—I'll have Jest flashbacks otherwise 😆

The logic in each section can be implemented—or at least started on/tests started—before this is ready, but now that this is ready I'll tackle it first so the dependant PRs make more sense 👍

**Comment by felixarntz** [comment]
Keeping this one assigned to myself for now. QA should happen once this plus #571 and #572 have been merged to `develop`.
