### ISSUE TITLE
Implement singular getter, setter and related logic in `googlesitekit-api`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#572]
## Feature Description

Following #570 and #571, let's implement the basic infrastructure methods in the `googlesitekit-api` script to run singular API requests. The batch request method should be implemented via a follow-up issue.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Following #570 and #571, let's implement the basic infrastructure methods in the `googlesitekit-api` script to run singular API requests. The batch request method should be implemented via a follow-up issue.

* The following methods on `googlesitekit.api` (see `assets/js/api`) should be implemented:
    * `get( type, identifier, datapoint, data, { disableCache = false } = {} )`
    * `set( type, identifier, datapoint, data, { disableCache = false } = {} )`
    * `invalidateCache( type, identifier, datapoint )`
* When interacting with cache, the methods should rely on the `cache` implementation in `assets/js/api/cache`.
* Caching should be enabled by default, with the above object property allowing for specific cases to skip the cache.
* There should be solid Jest test coverage for each of the four methods. In order to accomplish that, the `apiFetch` method used should internally be easily exchangeable (by Jest, but not by production code relying on the script).

## Implementation Brief

* Create a `assets/js/googlesitekit/api` file that contains `get`, `set`, and `invalidateCache` methods.
* Create `get( type, identifier, datapoint, data, { disableCache = false } = {} )` and `set( type, identifier, datapoint, data, { disableCache = false } = {} )` methods that allow per-request cache disabling. By default, these methods should use the `assets/js/googlesitekit/api/cache` module implemented in #571 to cache requests for a period of time.
* HTTP requests should rely on/use the `@wordpress/api-fetch` package (https://developer.wordpress.org/block-editor/packages/packages-api-fetch/)
* `invalidateCache` can be implemented in a similar way to existing code in https://github.com/google/site-kit-wp/blob/39e8d2de110dd34c8c6711239b3018b41d1545b8/assets/js/components/data.js#L277-L376

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
Regarding:

> [...] since typically nobody should disable caching on an API request. However, we still want to make it available for special cases.

Are there any instances in the current codebase where the cache is not used for a specific request? If there are specific requests that should not use the cache but it's a rare scenario—and in general the cache should always be used—it would be better to build the ability to ignore the cache into the `get` and `set` methods rather than the "verbose" approach. That way specific requests are more clearly marked as without cache interaction, and I don't think making an API annoying to use is the same as telling developers not to use it 😅

I think it's better to build the disabling of the cache directly into the `get` and `set` methods as options, to reduce the code surface of this library and to more closely align a non-cached request's code with its intent of not caching.

I don't think forcing the developer to add a few extra lines to their code (in a way that will globally disable/enable the cache, which could cause _other_ requests to ignore/use the cache unintentionally) is a way to discourage them from disabling the cache. If anything, simply offering `_disableCache` as a "private" option is fine to me.

I've created an IB that does not use a global cache enabling/disabling option, and instead allows individual requests to opt-out of the cache, as that is the main use-case mentioned for it. If you're okay with this I think we should update the AC to remove the `useCache()` function and adopt an extra `options` argument for the `get` and `set` methods, as I've suggested in the IB.

We already allow a site-wide disabling of the cache by using `?nojscache=1` in the URL, so I'm not sure we need another way to disable it here. That way a third-party piece of code can't globally disable the cache—either intentionally or unintentionally.

-------

That said, I'm starting to wonder about if the API request layer is the right location to be implementing this sort of caching at all. My understanding is the cache exists to improve the UX of much of the site, where requests like the PageSpeed Insights can take several seconds (10s+) to load. Going forward with the JSR, the flow to display that component would be:

```
Load Component
Select Data from Data Store (`wp.data`)
  if data === FOUND:
    return data
  else:
    data = request.get()
    return data
```

We could create a better UX by caching data in the data store layer instead of the HTTP request layer, by loading cached data right away but still dispatching an HTTP request to get _even fresher_ data. So cached data is still loader right away for the user, but new data is fetched in the background and adding to the data store in the background. The UI would load this new data once it was ready, so there is never "stale data" hanging around in the user cache that the user can't clear.

If we implement caching at the request layer there's no straightforward way to load cached data but then continue on with the request if we integrate the API requests and the data store going forward, as is the plan.

I'd love others thoughts on caching as they might be able to provide more context cc @aaemnnosttv @adamsilverstein. Maybe we don't want the API layer using caching long-term, at least. But for now I've left it in the IB.

**Comment by adamsilverstein** [comment]
@tofumatt thanks for the thoughts here. 

> Are there any instances in the current codebase where the cache is not used for a specific request?

All `withData` requests are cached as all current data is only updated daily (there is no today view and date ranges end yesterday). Cache maxAge is on a per-data point basis). Most singular `get` requests are used during the setup flows and these typically don't want to be cached as we want to pick up any changes immediately. We don't cache get requests by default.

> I think it's better to build the disabling of the cache directly into the get and set methods as options, to reduce the code surface of this library and to more closely align a non-cached request's code with its intent of not caching.

This does seem like a more typical pattern. Most requests will be cached, if a certain request needs uncached data it should specify that so its obvious in the code. 

This also matches the current approach except that since we only use the singular `get` call directly during setup where we typically don't want caching it is disabled by default: https://github.com/google/site-kit-wp/blob/develop/assets/js/components/data.js#L412  

> We could create a better UX by caching data in the data store layer instead of the HTTP request layer, by loading cached data right away but still dispatching an HTTP request to get even fresher data.

Generally I agree it may make sense to handle caching in the `wp.data` layer.

In most cases we won't want to re-request data - so far all data is delayed by a day (time ranges end 'yesterday'. so re-requesting the data is not helpful. One basic goals of the plugin is to not increase load or degrade performance when installed.

**Comment by felixarntz** [comment]
@tofumatt 
> I think it's better to build the disabling of the cache directly into the get and set methods as options, to reduce the code surface of this library and to more closely align a non-cached request's code with its intent of not caching.

Makes sense. I've updated the ACs accordingly.

> We could create a better UX by caching data in the data store layer instead of the HTTP request layer, by loading cached data right away but still dispatching an HTTP request to get even fresher data. So cached data is still loader right away for the user, but new data is fetched in the background and adding to the data store in the background. The UI would load this new data once it was ready, so there is never "stale data" hanging around in the user cache that the user can't clear.

That's a great suggestion. Before we decide to go with it, we would need to discuss the UX implications of that. For example, it might be confusing to the user to see stale data which is replaced with new data after e.g. 1 second - whereas seeing a loader is more annoying but it makes sense to the user at least. The other thing (more a detail) that @adamsilverstein already mentioned is that we definitely wouldn't always want to re-request data. We might only want to do that after a certain period where it's likely that the values are stale (e.g. Analytics values probably don't change much from 10 minutes to the next 10 minutes).

Let's discuss this further (I think a separate issue would be great), but for now proceed with the caching in the API layer. There's nothing that prevents us from handling caching in the datastore, even at a later point. This would be internal behavior that we could modify without breaking people's code (e.g. a simple way to change it would be to just disable API caching everywhere in our datastore and instead use its own caching).

Regarding the IB, there's just one thing I think we should change:
> `invalidateCache` can utilise the https://github.com/localForage/localForage-startsWith and https://github.com/localForage/localForage-removeItems plugins to allow for easy, mass-cache-key removal.

We shouldn't introduce dependencies for this type of thing. The code that does this (already today in `data.js`) is just a few lines, and that wouldn't change much with the new API (and its cache). Looking at the library you're suggesting, it does exactly that, but embedded in a much bigger package. Even though only the parts we need would be included in the webpack bundle, something this small and simple doesn't warrant introducing another dependency to me.

**Comment by tofumatt** [comment]
Understanding that a lot of the data doesn't change day-to-day is helpful, thanks @adamsilverstein!

Regarding the "stale data then updated with new data" UX—I thought about that too, though if we were to create some sort of "updating in the background" UI (or even switch from "stale data UI" -> "request" -> "response" -> "loading data w/spinners UI" -> "new data UI") I think it'd be obvious to the user that new data is being fetched.

But it's been clarified to me as well that a big part of the REST API caching is to prevent the _WordPress_ database/API from getting too many requests. Glad to hear the notion of data-layer caching going forward is welcome, but agreed: for now we can transparently cache at this layer and then tweak things in the background as we move to using  persistence in `wp.data`.

-----

I've excluded localForage from the IB, but having dealt with storage APIs directly a lot when writing it, I just worry about edge cases and localStorage's synchronous/main-thread performance. But we aren't doing a tonne or get/set calls so it should be okay.

**Comment by felixarntz** [comment]
IB ✅
