### ISSUE TITLE
Implement `getBatch()` logic in `googlesitekit-api`

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#573]
## Feature Description

Following #570, #571, and #572, let's implement the `googlesitekit.api.getBatch()` method for combining multiple Site Kit REST get requests into a single one. This should be a clean version of `combinedGet()` from `data.js`, without all the legacy clutter intertwined with the Site Kit screen loading process.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `getBatch()` method on `googlesitekit.api` should be implemented.
* The method should be able to be called at any time.
* Every `request` object in `requests` can provide a `callback` that accepts the individual response.
* Regardless of that, the entire promise for all requests should also resolve in the end, returning all responses in an object keyed by the respective `request.key`.
* There should be solid Jest test coverage for the method. Similar to the other methods, the `apiFetch` method therefore needs to be exchangeable with a way to return a mock promise instead.

## Implementation Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
Is there a specific reason to add a separate `getBatch()` method instead of providing a batch request mechanism to the existing `get()` method proposed in #572? That method could take an array of items to batch requests, and might even benefit from optimisations in the future that would automatically batch requests made within a `100ms` period or something like that.

Right now the separate APIs for what is essentially the same task is a bit confusing from an API standpoint, even if the batch request is largely intended to be internally-consumed—which is what I understand.

I wonder if it might be nicer to allow `get()` to consume an array as an argument (an array of `get()` params) and not expose this method as separate?

-----

Regardless of that point, I'm unclear why we want callbacks for each `request` as specified in the AC here:

> Every request object in requests can provide a callback that accepts the individual response.

The main use-case for batch requests, as I understand it, is to request many related pieces of data at once. If the requests can be made and loaded separately, they shouldn't be made with the combined method but handled individually. If the batching of requests is solely a performance optimisation in this case, I think it would be better to optimise individual `get()` calls to be batched automatically within a window instead of the developer intervention.

As we move to a global data store I would discourage the use of callbacks in our APIs as they can be harder to keep track of and are more frustrating to write/test, especially when providing a Promises-based API as well. (I deal with this with localForage a lot as we offer both 😅.)

Since the combined GET request is returned altogether anyway, can we remove the callback requirement and simply have code act on the returned results? We can certainly key each `response` to its `request` params to make this straightforward, but I think it will reduce:

1. the code surface of the API
2. the tests needed to ensure the API works as expected
3. the documentation/usability of the API
4. the consistency in our own code as we use a single API to deal with the requests

**Comment by felixarntz** [comment]
Let's deprioritize this for now. We can solely rely on `googlesitekit.api.get` as a start, and based on previous discussions, maybe we'll never need a `googlesitekit.api.getBatch`.

**Comment by felixarntz** [comment]
Potentially we might not need this - I'm moving to "Revisit Later".

**Comment by felixarntz** [comment]
Closing this for now. If we see a need for batching later, we can reopen.
