### ISSUE TITLE
Settings page mobile view - logo display is incorrect

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5749]
TwG logo should be displayed like in other pages - "Thank with Google" text in one line and both badges in another line

![Logo Display](https://user-images.githubusercontent.com/93320881/186765075-8fcb5073-334c-4a7b-9b9c-3ae2c073b038.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When viewing the Site Kit settings panels on mobile, the "Thank with Google" module name should appear in one line, with the labels in an additional line.
    * This design/layout change should be implemented across the board, so that it would also apply to other modules with labels. The label(s) should only appear in the same line as the module name if they would fit in there without breaking apart the module name across multiple lines, otherwise all labels should appear on the next line.

## Implementation Brief

* In `_googlesitekit-settings-module.scss`, add the following to `.googlesitekit-settings-module__heading`:
    * `flex-wrap: wrap`
    * `row-gap: 12px`

### Test Coverage

* No new tests required.

## QA Brief

* Test the Module Settings page on all browser widths/view ports and verify that "experimental labels" always appear on a separate line when the module title cannot fit on a single line. (TwG and Idea Hub currently have "experimental labels" but Idea Hub is too short to wrap on mobile as well.).

## Changelog entry

* Fix layout for module names when displayed with badges on the Settings page in mobile viewports.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 


- Verified on Chrome, Edge,Firefox and Safari browsers.
- Verified on different view ports using browser and iPhone, iPad and Android mobile and tablet using BrowserStack.
- Settings Page - TWG logo displaying in one line. Verified for connected and not connect more services screen.

<details>

![image](https://user-images.githubusercontent.com/94359491/190970478-e24a6c45-f60e-409b-8457-3444c13383e2.png)

![image](https://user-images.githubusercontent.com/94359491/190970509-a18bdbe5-8ea1-4957-885e-601c17e438e4.png)

![image](https://user-images.githubusercontent.com/94359491/190970539-6357a0cc-757a-48df-9902-489bc60e5733.png)

![image](https://user-images.githubusercontent.com/94359491/190970567-edf32974-8a30-4702-995b-c5a6566770fa.png)

![image](https://user-images.githubusercontent.com/94359491/190970596-d3a0bcea-e18b-4cf9-9e85-bffcdbe94898.png)

</details>

**Comment by aaemnnosttv** [comment]
## Approval ⚠️ 

This one is close but seems to be off regarding this point of the AC:

> The label(s) should only appear in the same line as the module name if they would fit in there without breaking apart the module name across multiple lines, otherwise all labels should appear on the next line.

This is not the case as shown in @mohitwp 's last screenshot above: 
<img width="544" alt="image" src="https://user-images.githubusercontent.com/1621608/191802316-ec0c1600-808e-472d-82f4-be890cc9f68f.png">

On closer inspection, it appears that the badge/labels start wrapping at 1122 px, regardless if they fit or not.

https://user-images.githubusercontent.com/1621608/191802983-8eaa7bba-7468-48ba-8637-2e3ef97c2d05.mp4

cc: @jimmymadon @techanvil

**Comment by asvinb** [comment]
@aaemnnosttv This one is tricky since we are using the grid MDC layout not flex) and we have predefined widths set per breakpoint. So even if it looks like there's room for the labels to fit on one line, actually due to the width of their parent container, they are limited. For e.g:
Here we see that the labels should definitely fit in the available space:
<img width="903" alt="image" src="https://user-images.githubusercontent.com/31818/191936166-905c6f0a-e23a-4094-af08-ff45c3b43466.png">
However when inspecting the grid, turns out that we don't have enough room:
<img width="896" alt="image" src="https://user-images.githubusercontent.com/31818/191936426-001be5d2-ca95-4b1e-ba24-e1447446220d.png">

We can make a few tweaks to the container layout on large screens (961px) where the labels fit all in one line and reduce the width for the CTA. However notice how the `Complete setup for Thank with Google` button is cramped.
<img width="778" alt="image" src="https://user-images.githubusercontent.com/31818/191936633-c4b393de-486c-4ff7-ad9b-30f529ec6f97.png">

I see 2 options:

1. Display the labels consistently depending on viewports and not fit when there's space. For e.g on tablet viewport, the labels will be always below the title and then on large screens the labels are on the same line keeping in mind we might have a long CTA on the right, for e.g `Complete Setup for PageSpeed Insights` and we must have enough room to display it correctly.
2. Refactor the layout to not use MDC grid and instead use flex which will grow and shrink.

Due to the amount of effort needed for #2, I think #1 is the best option

**Comment by aaemnnosttv** [comment]
Thanks @asvinb – this doesn't need to hold up the release, so I'll close this now. Would you please open a follow-up issue with your suggested enhancements?
