### ISSUE TITLE
Include an option to "Edit in publisher Center"

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5755]
For some modules we have an option to "Edit in <module>" 

Include this option for Thank with Google, as an individual publication can be added via a query parameter. Example:
https://publishercenter.google.com/publications/CAow0amZCw/overview

Modules that do have this include Anaytics, AdSense and Tag Manager. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The TwG settings view should be updated to use the following structure, with the layout following Analytics as an example of rows with multiple independent columns of data
	```
	**Publication ID**
	{publicationID}         [Edit in Publisher Center](#)

	**Type**       **Prominence**       **Color**
	Overlay        Low                  Green

	**Post Types**
	Posts

	**Supporter Wall Widget**
	[Add supporter wall](#)
	```
* The TwG settings edit view should be updated to reorder the sections for consistency with the non-edit view by moving the "Supporter wall widget" section to the bottom

## Implementation Brief

- In `assets/js/modules/thank-with-google/components/settings/SettingsView.js`:
    - We are going to move away from the `Grid - Row - Cell` structure that we currently have to a structure similar to the Analytics `SettingsView` component (`assets/js/modules/analytics/components/settings/SettingsView.js`) to match the format mentioned in the ACs.
        - Replace the `<Grid>` component with a `div` containing the classes `googlesitekit-setup-module` and  `googlesitekit-setup-module--thank-with-google`.
		- Each row should be a `div` with the class `googlesitekit-settings-module__meta-items`.
		- Each column should be a `div` with the class `googlesitekit-settings-module__meta-item`.
		- The contents of each column should be as it is.
		- The arrangement of the columns should match the format mentioned in the ACs.
	- In the first row that contains the `Publication ID` setting, add an `Edit in Publisher Center` external link with a structure similar to the `Edit in Analytics` external link in the Analytics `SettingsView` component (`assets/js/modules/analytics/components/settings/SettingsView.js`). To populate its `href` prop, use the `getServicePublicationURL` selector from the `modules/thank-with-google` store with the `publicationID` passed to it.
- In `assets/js/modules/thank-with-google/components/settings/SettingsForm.js`:
    - Re-order the input components to move `<SupporterWall />` setting to the bottom, thus making the order of inputs consistent with the settings view.

### Test Coverage

* No tests need to be added/updated.

## QA Brief

* Ensure that the `twgModule` feature flag is enabled in the tester plugin.
* Activate and complete setup for the Thank with Google module.
* Go to `Settings -> Connected Services` and open the panel for `Thank with Google`.
    * Verify that the order and structure of the settings are according to the ACs.
    * Verify that an `Edit in Publisher Center` exists and opens the current publication URL in a new tab.
    * Click on `Edit` underneath the panel to open the settings edit view for Thank with Google.
        * Verify that the setting for Supporter Wall has been moved to the bottom to make the order of the settings consistent with the settings view (ACs).

## Changelog entry

* Include an option to "Edit in Publisher Center" in the Thank with Google settings view.

**Comment by aaemnnosttv** [comment]
@felixarntz are we expecting URLs to potentially change still (re: #5537) or is that issue about the onboarding flow only?

**Comment by felixarntz** [comment]
@aaemnnosttv My assumption is they won't change for editing a publication, but still might be. It shouldn't really block this though. Once we know what has to be updated we can make sure to cover any URL changes in #5537.

**Comment by aaemnnosttv** [comment]
@felixarntz sounds good 👍 

Another thing I'm noticing is that the layout of the settings view is rather different than all the other modules as TwG currently has two defined columns and the others are more composed of rows of related settings.

For TwG, this might be more consistent to look like this (markdown because formatting/spacing):

```
**Publication ID**
asdfasdfsasdf         [Edit in Publisher Center](#)

**Type**       **Prominence**       **Color**
Overlay    	   Low		            Green

**Post Types**
Posts

**Supporter Wall Widget**
[Add supporter wall](#)
```

Alternatively, the type, (prominence|position), color could be stacked to mirror the layout in setup/edit. What do you think? If you agree, this should probably be a separate issue but it came up because there is no consistent way to add the edit link right now without shifting the entire second column over which is what brought my attention to this. A stepping stone solution here could be to add the link where the supporter wall is, and move that to the bottom.

**Comment by felixarntz** [comment]
@aaemnnosttv The structure you're proposing for the view mode makes more sense to me than the current one as well as it is better aligned with the other modules and overall more logically grouped.

@marrrmarrr What do you think? We could bring this up with the UX team for feedback, but I would agree what Evan proposes makes more sense than the simple two column layout from the Figma designs, which has pretty much zero logical grouping.

**Comment by marrrmarrr** [comment]
@felixarntz @aaemnnosttv I think it's ok to slightly regroup the entities on the settings page as long as it corresponds to the order in which they're shown once the user clicks "Edit" ([this figma screen](https://www.figma.com/file/t5zDpQ28Lo7ZyRcOpGdqgu/TwG?node-id=2343%3A12555)), so the user experience is consistent. 

In this case, this would mean that the colour selection on the Edit screen should be moved to immediately below "Prominence", and the Supporter wall widget should be all the way at the bottom.

**Comment by aaemnnosttv** [comment]
@marrrmarrr I've added AC based on our conversation earlier. If this reads correctly to you then I think we can move forward with it.

**Comment by marrrmarrr** [comment]
@aaemnnosttv 👁️👍

**Comment by aaemnnosttv** [comment]
Thanks @marrrmarrr ! Moving on to IB 👍

**Comment by techanvil** [comment]
Nice work on the IB @nfmohit. Succinct with detail where necessary, a healthy balance! :)

IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@nfmohit I noticed that clicking on 'Edit in Publisher center' navigating user to `https://publishercenter.google.com/` from intermediate URL - `https://publishercenter.google.com/twg/{publicationID}/home` . which shows blank page. When we refresh the page it navigates user to `https://publishercenter.google.com/publications` and shows content on the page.  

It should navigate user to - https://publishercenter.google.com/publications/CAow9aq9Cw/overview

Is this issue from TwG side ?

**Comment by nfmohit** [comment]
Thank you for pointing it out, @mohitwp!

As Felix mentioned [here](https://github.com/google/site-kit-wp/issues/5537#issuecomment-1252874874), the TwG team is still working on the URLs, so for now, we just need to make sure they point to the right URL. You can verify them with the help of Darren's verification here.

Thanks!

**Comment by mohitwp** [comment]
@nfmohit 

Thank you !

 'Edit in Publisher center' link pointing to `https://accounts.google.com/accountchooser?continue=https%3A%2F%2Fpublishercenter.google.com%2Ftwg%2FCAow9aq9Cw%2Fhome&Email` and navigates user to `https://publishercenter.google.com/` which shows blank page and refreshing it shows the content with URL - `https://publishercenter.google.com/publications ` .



There are no details under this ticket regarding the URL's.  So I've question regarding it from the information I found on #5537 .

**Question-1)** 
As per [AC of #5537](https://github.com/google/site-kit-wp/issues/5537#issue-1299365796)
` "Everywhere we link to https://publishercenter.google.com/publications/{publicationID}/overview (see getServicePublicationURL selector), we should change that URL to be https://publishercenter.google.com/twg/{publicationID}/home instead."`

That's why it is showing intermediate URL
`https://publishercenter.google.com/twg/{publicationID}/home` and is this expected ?

**Question 2)** 
Currently, 'Edit in Publish center' link points to `https://accounts.google.com/accountchooser?continue=https%3A%2F%2Fpublishercenter.google.com%2Ftwg%2FCAow9aq9Cw%2Fhome&Email` is it correct ?

![image](https://user-images.githubusercontent.com/94359491/192775154-a0940ef4-6cb4-4cf2-bddb-59ab3849e4e5.png)

Also, attaching screencast of current behavior - cc @wpdarren 


https://user-images.githubusercontent.com/94359491/192775388-b305e215-8453-4a0a-8033-b97dc022240b.mp4

**Comment by nfmohit** [comment]
@mohitwp Yes to both questions, thank you for checking.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified TwG setting edit screen related changes on development server.
- TwG settings view updated as per order mentioned in AC.
- The TwG settings edit view  updated to reorder the sections for consistency with the non-edit view by moving the "Supporter wall widget" section to the bottom.
- Verified that Edit in Publisher Center exists and opens the current publication URL in a new tab.

**Note** : I noticed that clicking on 'Edit in Publisher center' navigating user to https://publishercenter.google.com/ from intermediate URL - https://publishercenter.google.com/twg/{publicationID}/home . which shows blank page. When we refresh the page it navigates user to https://publishercenter.google.com/publications and shows content on the page. This is known issue as As Felix mentioned https://github.com/google/site-kit-wp/issues/5537#issuecomment-1252874874, . 
Also, there are no details regarding where URL should point for that for this I followed the AC of  #5537 and confirmed with Nahid. - https://github.com/google/site-kit-wp/issues/5755#issuecomment-1260813775


<details>

![image](https://user-images.githubusercontent.com/94359491/193024988-d74b50e4-4534-4f33-8066-0c17d7cd721b.png)

![image](https://user-images.githubusercontent.com/94359491/193025055-9749cdf8-e35e-4127-a33c-f6456259acc9.png)

</details>

**Comment by bethanylang** [comment]
:wave: I'm working with the TwG team on our documentation and they let me know yesterday that they have changed the terminology from "Publisher ID" to "Thank with Google ID." Not sure if we want a separate issue to make this change, but noting here and will flag to the PM team for next steps.

**Comment by bethanylang** [comment]
One more change that I just realized – they don't want to use the term "Publisher Center" any longer; it should be "Thank with Google Profile." So to summarize:
- References to "Publisher ID" or "Publication ID" should be changed to "Thank with Google ID"
- References to "Publisher center" should be changed to "Thank with Google profile"

**Comment by FlicHollis** [comment]
Thanks @bethanylang we have moved these changed to a separate ticket here: https://github.com/google/site-kit-wp/issues/5963
