### ISSUE TITLE
Update to AdSense screen for a first-time user just finished the set-up

### ISSUE THREAD

**Issue by OisinOConnor** [google/site-kit-wp#578]
## Feature Description
Update the copy and the link target for the AdSense screen displayed for the following cases:
- a first-time user who just completed AdSense setup.
- a user whose account is in pending state who is connecting to Site Kit

### Current screen copy: 
_We’re getting your site ready for ads_

_This usually takes less than a day, but it can sometimes take a bit longer. After you’ve completed setting up your account, we’ll let you know when everything’s ready._ 
_[Go to your AdSense account to check on your site’s status](url)_

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
* The screen copy should be updated to the following text: 
_Let’s get your site ready for ads_
_After you’ve finished setting up your account, we’ll let you know when your site is ready to show ads. This usually takes less than a day, but it can sometimes take a bit longer. 
[Go to your AdSense account to check on your site’s status or to complete setting up
](url)_

* The link target should contain only the domain of the site, removing any subdomains or subfolders. For example, if Site Kit is installed on blog.example.com, instead of dynamically inserting the exact URL:  
`https://www.google.com/adsense/new/sites?url=blog.example.com&source=site-kit`
trim to the just the domain:  
`https://www.google.com/adsense/new/sites?url=example.com&source=site-kit`

## Implementation Brief

**Based on changes in #427**

`assets/js/modules/adsense/dashboard/adsense-module-status.js`

### Update `ads-display-pending` case
* Update status headline and message according to AC
* Replace usage of `siteUrl.hostname` with root domain
    - Add [`psl`](https://www.npmjs.com/package/psl) for accurately parsing out root domain (accounts for all weird multi-part TLDs)
* Update `tests/e2e/specs/modules/adsense/setup-new-user.test.js`

## Changelog entry

* Always use root domain for AdSense site because subdomains are typically not supported.

**Comment by felixarntz** [comment]
IB tentatively ✅ 

@aaemnnosttv How big is the `psl` dependency when bundled? I'm asking because we used to have another dependency included on the PHP side for a similar purpose, which was blowing up the plugin bundle size to about 10MB (instead of 2MB) because of a massive list of TLDs it included. We should make sure this doesn't happen here as well.

**Comment by aaemnnosttv** [comment]
@felixarntz you can see the impact of adding the package here:  
https://bundlephobia.com/result?p=psl@1.4.0

Most of the size appears to be due to the length of the public suffix list itself. This is lighter weight to include in the plugin than PHP since we can leverage minification and compression. Even without that it's only ~1/8 MB.

**Comment by tofumatt** [comment]
Now that #427 is merged this makes sense to tackle 👍

**Comment by cole10up** [comment]
**Tested and am still seeing container ID**

Setup Analytics, setup Tag manager with container name of 'Container'

Notice:
![image](https://user-images.githubusercontent.com/57115907/69194880-22706f00-0adf-11ea-9e8c-c612983ecfce.png)

See attached latest zip that I tested with.

One thing to note - I did not add the tags to my site as instructed here:
![image](https://user-images.githubusercontent.com/57115907/69194999-6d8a8200-0adf-11ea-8245-587ecf9e850c.png)

[google-site-kit.zip](https://github.com/google/site-kit-wp/files/3866508/google-site-kit.zip)

**Comment by cole10up** [comment]
**Tested**

First time install shows correct copy according to acceptance criteria:
![image](https://user-images.githubusercontent.com/57115907/69210051-5ca53500-0b0e-11ea-8e91-5a045ac8caa3.png)

Selected CTA and navigated to Adsense properly
![image](https://user-images.githubusercontent.com/57115907/69210071-6dee4180-0b0e-11ea-8b30-ead934f1b66d.png)

One thing to note and will review with the team - If you navigate away from the window and back to the adsense setup window, noticed that the page reloads.

Passed QA ✅

**Comment by aaemnnosttv** [comment]
> One thing to note and will review with the team - If you navigate away from the window and back to the adsense setup window, noticed that the page reloads.

The page reloads or the module goes back into a loading state? The module reloading is so that if you navigate away (ie to your AdSense account to take care of things that need updating) when you come back it fetches your account info again, potentially allowing you to proceed if previous blockers have changed.

**Comment by cole10up** [comment]
Ahh ok, thank you for the clarification. It looks like the module goes back into the loading state.
