### ISSUE TITLE
Add default title to supporter wall widget

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5785]
## Feature Description

The supporter wall widget currently has no default title which causes it to be rendered as basic placeholder in the block-based widgets editor. When initially adding the widget, it should have a default title.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The TwG supporter wall widget should receive a default title: **Thank with Google Supporters** which should be a translatable string
* Users should be able to save the widget without any title, the default should only apply if no title is saved (i.e. an empty title is still valid)

## Implementation Brief

- In `includes/Modules/Thank_With_Google/Supporter_Wall_Widget.php`:
    - In the `form` method, before the `title` variable is assigned, update the `$instance` parameter by using `wp_parse_args` to provide a default value (translatable) for the `title` property according to the ACs. Example:
    
        ```php
        $instance = wp_parse_args( $instance, array( 'title' => DEFAULT_TITLE ) );
        ```

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* Using a theme that allows editing widgets (eg. Twenty-Twenty), access Appearance > Widgets (`/wp-admin/widgets.php`)
* Add the "Thank with Google Supporter Wall" widget to a widget area.
* Observe it has a default title "Thank with Google Supporters" and not an empty title.

* Also ensure that if you remove the default title and make the title empty, then save it and reload the widget editor screen—the title should still be empty and not be replaced with the default title.

## Changelog entry

* Add default title to the Supporter Wall widget for Thank with Google.

**Comment by aaemnnosttv** [comment]
@marrrmarrr over to you to define the default title 👍

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
Just noting here that the block-based widget editor still does not enable the preview until the title is modified or editor is reloaded.

https://user-images.githubusercontent.com/1621608/194938899-7734aebe-704c-4726-8068-92531bf0c96b.mp4

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified on Dev environment.
- Supporter wall widget now showing with Default title.
- Saving Widget with default title showing default title in front end.
- If we remove the default title and make the title empty, then save it and reload the widget editor screen—the title is empty and not getting replace with the default title.
- On adding new title instead of default - new title appearing in front end.
- Default title is translatable.
- Users are able to save the widget without any title.

<details>

![image](https://user-images.githubusercontent.com/94359491/195353377-3359ff1c-3c4e-410c-80bc-d2f61c444b4a.png)

![image](https://user-images.githubusercontent.com/94359491/195354177-69ba4d4a-f4c7-44c6-be05-742b93469a7e.png)

![image](https://user-images.githubusercontent.com/94359491/195354483-cc338ab8-ceb2-46da-b40d-bcb0bc536bdc.png)


![image](https://user-images.githubusercontent.com/94359491/195354327-5ff36d5b-eed2-4b99-be05-64b82e09b2c9.png)


Without Title 

![image](https://user-images.githubusercontent.com/94359491/195353898-18aa8d49-c6c7-4e2c-b2b6-b4a283530c2d.png)

Title change -

![image](https://user-images.githubusercontent.com/94359491/195353956-330d16f1-1158-474a-bf2f-b8e9cd9ac783.png)

</details>
