### ISSUE TITLE
Ensure missing edit scope is handled for the "existing property" variant

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5805]
## Feature Description

Following on from https://github.com/google/site-kit-wp/issues/5278, we need to add the same messaging for the "existing property" variant of the `SetupForm` when the option to "Set up a new property" is selected in the dropdown and the _edit_ scope does not exist.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- When displaying the Setup Component in one of the "existing GA4 property" variants, the Analytics _edit_ scope is not present, and "Set up a new property" is selected in the dropdown:
  - An informative message should be shown in the component:
    - _You will need to give Site Kit permission to create an Analytics property on your behalf._

## Implementation Brief

- Once #5278 is complete, refer to its PR and apply similar logic for showing the _You will need to give Site Kit permission..._ message to the "existing property" variant when the selected GA4 property ID is `PROPERTY_CREATE`.

### Test Coverage

* No new tests needed.

## QA Brief

- Ensure `ga4ActivationBanner` feature flag is enabled.
- Ensure UA is connected, but GA4 is not connected in your SK setup.
- To get the "Existing GA4 property" variant, ensure there _is at least one_ GA4 property available in your Google account.
- Ensure the Google use doesn't have an edit scope. If this is impossible to achieve via the Analytics dashboard console, we can trick SK into thinking it isn't granted even if it is by deleting the `wp_googlesitekit_additional_auth_scopes` meta key for your user from the `wp_usermeta` table.
- Ensure an informative message is displayed below the `Create property` CTA (with a "Connect" button) as per the AC.
- Upon clicking the `Create property` CTA, ensure the user is redirected to the OAuth flow and grant access upon the return.
- Ensure the user is landed on the same setup after the successful OAuth flow and grant access.
- For CR, ensure this new [story](https://google.github.io/site-kit-wp/storybook/pull/5808/?path=/story/modules-analytics4-setupbanner--with-property-and-tag) displays the informative message as per the AC.
- For QA, ensure this new [story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-setupbanner--with-property-and-tag) displays the informative message as per the AC.

## Changelog entry

* Show an informative message on the GA4 Activation Banner for the variants of the Setup Banner where a GA4 property does exist, when "Set up a new property" is selected while the edit scope is missing.

**Comment by eugene-manuilov** [comment]
@techanvil the proposed approach to automatically redirect users to oauth flow is inconsistent with the permission scopes granting approach we use everywhere else. We shouldn't check manually whether the user has certain permissions or not, instead we should submit a request to out API and act accordingly to the returned error in the response.

It means that when the user clicks on the "create a new property" button or selects such option from the dropdown, we need to submit the request to the server. If the server returns a permission scope error (we check it using the `isPermissionScopeError` function), then we need to save the selected option and set autosubmit to true. In the same time, the permission scope modal will be shown to the user where they will be informed that they need to provide additional scopes with ability to proceed or cancel. Once the user clicks on the proceed button, they will be redirected to the OAuth page to grant additional permissions. And on return we need to re-submit our request.

The same applies to #5278, we need to rework the approach there to be consistent with how we handle scope errors. Going to assign this ticket back to you and move it to AC for now.

cc @aaemnnosttv 

A few code references:

* Here we set the permission scope error when API returns an error for a request: https://github.com/google/site-kit-wp/blob/a604447afae4cc1b4c3f0760889dd15985af026d/assets/js/googlesitekit/api/index.js#L96-L97
* If there is a permission scope error, we automatically display the permissions modal to ask the user to provide additional permission scopes: https://github.com/google/site-kit-wp/blob/a604447afae4cc1b4c3f0760889dd15985af026d/assets/js/components/PermissionsModal/AuthenticatedPermissionsModal.js#L95-L109
* If a request failed due to the permission scopes error, we don't automatically redirect the user to the OAuth flow, we just save the form and set `autosubmit` to true to make sure we re-submit the form when the user returns back to the page after providing required scopes: https://github.com/google/site-kit-wp/blob/a604447afae4cc1b4c3f0760889dd15985af026d/assets/js/modules/analytics/components/setup/SetupForm.js#L72-L75

**Comment by techanvil** [comment]
Hi @eugene-manuilov, thanks for calling this out. As we have clarified further on Slack, the intention is in fact to avoid showing the permissions modal at all, and navigate directly to the OAuth page when pressing the "Create property" or "Connect" CTA in absence of the _edit_ scope.

@hussain-t has made an update to the PR for #5278 to address this, which has now been merged.

All we still need to do is ensure the _You will need to give Site Kit permission..._ message also shows up for the "existing property" property variant. I have updated the AC/IB for this issue accordingly.

**Comment by eugene-manuilov** [comment]
Thanks, @techanvil. IB ✔️

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@tofumatt 

I verified this ticket using instaWP new site and on another site using elasticpress.io .

I found that QAB is little different from the actual flow.

- In this case of 'Existing GA4 property' - `Connect` button will display instead of `Create propety` button with an drop down select option to either 'Set up new Property' or select from the existing one.
- Also, after successful OAuth flow setup will get complete. User will get navigate to dashboard and get notification that set up is complete. 

I verified this for actual flow and it is working fine. But looking at the QAB just want to make sure that I'm not missing anything.

<details>

![image](https://user-images.githubusercontent.com/94359491/190104076-600b04d4-33ec-4bbe-abb1-7cd3be1bfc42.png)

![image](https://user-images.githubusercontent.com/94359491/190104112-4b41c11a-ba7b-4d17-b1bf-40a94e9ade2c.png)

</details>

cc @wpdarren

**Comment by tofumatt** [comment]
Sorry, yes, that is the actual flow. I think it might be that this QA brief was copied from a similar one and I forgot to mention the button text 😓. The name of the whole CTA is around connecting a property though, maybe that's where it was a bit confusing.

Sounds like the QA is good here, so I'll move this to Approval. I've updated the QA Brief for posterity. 👍🏻

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thank you @tofumatt !

Just wanted to share my comment with all details.

- I verified this ticket using instaWP new site and on another site using elasticpress.io.
- Verified this for google a/c don't have edit scopes and existing GA4 property.
- On successful completion of OAuth flow user navigate to dashboard and GA4 set up gets successfully completed.
- Also verified the [story ](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-setupbanner--with-property-and-tag-no-edit-scope)for informative text.

<details>

![image](https://user-images.githubusercontent.com/94359491/190104076-600b04d4-33ec-4bbe-abb1-7cd3be1bfc42.png)

![image](https://user-images.githubusercontent.com/94359491/190104112-4b41c11a-ba7b-4d17-b1bf-40a94e9ade2c.png)

Before setup-

![image](https://user-images.githubusercontent.com/94359491/190171214-5013344e-df3e-4f73-af74-27c7eeee6e8b.png)

After setup -

![image](https://user-images.githubusercontent.com/94359491/190171336-2b8f56cd-6c32-432e-8ee9-aa2179e92ebf.png)

Setup flow video-

https://user-images.githubusercontent.com/94359491/190171391-12964366-31bb-4a07-98a8-2102f570442e.mp4

</details>
