### ISSUE TITLE
Different Date Formats on Site Kit Dashboard widgets

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#5830]
## Bug Description

Creating this ticket for UX/UI discussion.  Is there a reason why we have two different date formats on the dashboard. In the All Traffic widget we have `MonDD` (i.e. Sep 03)  where in the charts are, i.e. Search traffic widget, the format is `MM/DD/YY` Wondering if the date formats should be consistent? 

## Screenshots

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/c4516b91-c1ae-43eb-83ab-adc0b7c64560)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- All of the charts in Site Kit that display a date axis should use the `MMM d` (e.g. "Sep 3") date format.
- Specifically, that means the line charts in the following widgets:
  - The "All Visitors" widget (this already uses the correct format and can serve as a reference).
  - The "Search traffic over the last x days" widget.
  - The "Performance over the last x days" widget.
  - The "Unique visitors over the last x days" widget on the WP Dashboard.
- The All Visitors widget chart should be updated so it displays the number of date labels using the same logic as the Search Traffic and Performance widgets, providing a consistent look across all SK Dashboard charts.
- For all of these SK Dashboard charts, ensure the date labels don't line-wrap when the viewport is too narrow. In this scenario the number of ticks should be reduced instead. We want to avoid situations like this:

![image](https://github.com/google/site-kit-wp/assets/18395600/be090752-ea47-4ffa-9848-84653de8b57c)

## Implementation Brief

~~_Note that the Google Chart does reduce the number of ticks to avoid overcrowding based on the chart width, so we may be able to leverage the native behaviour for the last AC point._~~

**Changing the date format:**
* Change the `hAxis` format to `'MMM d'` in following files:
  * [assets/js/components/wp-dashboard/chart-options.js](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/wp-dashboard/chart-options.js)
  * [assets/js/modules/adsense/components/module/ModuleOverviewWidget/Stats.js](https://github.com/google/site-kit-wp/blob/7c198f430b8dcf7d6026dddaf2587fd7c14c4c49/assets/js/modules/adsense/components/module/ModuleOverviewWidget/Stats.js)
  * [assets/js/modules/search-console/components/common/AnalyticsStats.js](https://github.com/google/site-kit-wp/blob/f4515de9a855895bc6178324973cee99d593a546/assets/js/modules/search-console/components/common/AnalyticsStats.js)
  * [assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/SearchConsoleStats.js](https://github.com/google/site-kit-wp/blob/7c198f430b8dcf7d6026dddaf2587fd7c14c4c49/assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/SearchConsoleStats.js)
  * assets/js/components/GoogleChart/index.stories.js

**Enforce the chart labels to never wrap in multiple lines and limit items along the x-axis:**

- In the `assets/js/components/GoogleChart/utils.js` within the `if ( chartType === 'LineChart' ) {` condition:
  - Check if `options?.hAxis?.maxTextLines` is defined. If not, set `hAxis.maxTextLines` to 1:
    - `set( chartOptions, 'hAxis.maxTextLines', 1 );`
  - Check if `options?.hAxis?.minTextSpacing` is defined. If not, set `hAxis.minTextSpacing` to 100:
    - `set( chartOptions, 'hAxis.minTextSpacing', 100 );`

- In the [`UserCountGraph` component](https://github.com/google/site-kit-wp/blob/b1450281d7ee93f7334e2041fa26cfe32a5db97f/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/UserCountGraph.js)
  - Remove all existing logic that generates the manual ticks.
  - Create a new variable `ticks`, extract the dates from the `chartData` and remove the first item.
    - const [ , ...ticks ] = chartData.slice( 1 ).map( ( [ date ] ) => date );
  - Pass over the new `ticks` variable to `chartOptions.hAxis.ticks` replacing the old logic.

**Update the existing charts to not pass the first date item as a tick:**
Removing the first item from the ticks, prevents the charts from automatically cutting of the first item and replacing it with an elipsis.

- [WPDashboardUniqueVisitorsChartGA4](https://github.com/google/site-kit-wp/blob/9f5e981e07231087645aee157ae13c222e8897b9/assets/js/components/wp-dashboard/WPDashboardUniqueVisitorsChartGA4.js):
  - Replace the existing logic around ticks
    https://github.com/google/site-kit-wp/blob/9f5e981e07231087645aee157ae13c222e8897b9/assets/js/components/wp-dashboard/WPDashboardUniqueVisitorsChartGA4.js#L115-L122
    Pass all dates except for the first one as ticks:
```
const [ , ticks ] = googleChartData.slice( 1 ).map( ( [ date ] ) => date );
const options = {
	...UNIQUE_VISITORS_CHART_OPTIONS,
	hAxis: {
		...UNIQUE_VISITORS_CHART_OPTIONS.hAxis,
		ticks,
	},
};
```

- [ModuleOverviewWidget/Stats.js](https://github.com/google/site-kit-wp/blob/7c198f430b8dcf7d6026dddaf2587fd7c14c4c49/assets/js/modules/adsense/components/module/ModuleOverviewWidget/Stats.js):
  - Similar to the change on the `WPDashboardUniqueVisitorsChartGA4` update the existing logic around the ticks to not include the first date item.

- [AnalyticsStats](https://github.com/google/site-kit-wp/blob/f4515de9a855895bc6178324973cee99d593a546/assets/js/modules/search-console/components/common/AnalyticsStats.js)
  - Similar to the change on the `WPDashboardUniqueVisitorsChartGA4` update the existing logic around the ticks to not include the first date item.

- [SearchConsoleStats](https://github.com/google/site-kit-wp/blob/7c198f430b8dcf7d6026dddaf2587fd7c14c4c49/assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/SearchConsoleStats.js)
  - Similar to the change on the `WPDashboardUniqueVisitorsChartGA4` update the existing logic around the ticks to not include the first date item.

### Test Coverage

* Update VRT reference images.

## QA Brief

* Set up Site Kit and required modules to be able to access the widgets mentioned in the AC. 
* Ensure that the new date format is showing up consistently across all widgets. all states (gathering, zero data and data available), and all viewports. 
* Verify the storybook stories to double check all is well, and there's no wrapping in the dates. 

## Changelog entry

* Improve the date legend in charts.

**Comment by andreas271828** [comment]
Worse yet, it's all American and not considering the locale or format settings of the Wordpress site.

**Comment by ronnyadsetts** [comment]
See this issue re. localities for the date format:

#1518 https://github.com/google/site-kit-wp/issues/1518

It surely can't be that hard to respect the locality preferences of the end users' site when displaying a date. Either that or use an unambiguous format rather than one that leaves you having to think about it.

**Comment by derweili** [comment]
Google charts automatically reduce the number of ticks based on the available space. So the only setting we to set here it to ensure the labels never wrap. This can be done with the [hAxis.maxTextLines](https://developers.google.com/chart/interactive/docs/gallery/linechart#:~:text=Default%3A%202-,hAxis.maxTextLines,-Maximum%20number%20of) option.

**Comment by tofumatt** [comment]
What is the reason for removing the manual `haxis.ticks` creation in our charts?

If we do that, the number of ticks is quite high. It gets pretty cramped and harder-to-read, especially because if you want the exact date (and year, omitted from the new string, reasonably) you can hover over the chart line.

Here's Google Charts handling the ticks:

![CleanShot 2023-11-29 at 23 15 07](https://github.com/google/site-kit-wp/assets/90871/4b432099-e142-4935-a954-62ced08ab1d8)

Here's our tick creation:

![CleanShot 2023-11-29 at 23 15 19](https://github.com/google/site-kit-wp/assets/90871/8c0589ee-96d5-4564-b273-c1fb3db4fdb0)

**Comment by derweili** [comment]
There is an alternative option to manually setting the ticks. Google charts has an [`minTextSpacing` option](https://developers.google.com/chart/interactive/docs/gallery/linechart#:~:text=hAxis.minTextSpacing). 

Using this, a spacing between the automatic ticks can be defined. If there is not enough space available, some ticks will be hidden.

**Comment by tofumatt** [comment]
@derweili Oh, awesome, okay, that seems better than us manually creating the ticks.

I'll move this back to IB with you but I think we just need to add a `minTextSpacing` to things so we preserve (approximately) the current tick spacing and this can be good-to-go then 🙂

**Comment by techanvil** [comment]
Hi @tofumatt, to answer your question:

> @techanvil Was that point brought up elsewhere? If it's a request from UX that's cool, but the original reduced tick was—if I recall correctly—part of a series of chart UX updates and was meant to reduce noise in that chart 🙂

This is a request from Mariya, following a question from Sigal - here's the relevant [Slack conversation](https://10up.slack.com/archives/C01CA828ZPZ/p1701173396704279?thread_ts=1701020980.747539&cid=C01CA828ZPZ).

It seems to me we should set the same `minTextSpacing` across all of these charts to provide a consistent look, while preventing the ticks from looking too crowded. Even the Search Traffic and Performance charts can look a bit crowded with the default `minTextSpacing` value, so a higher value all round should be an overall improvement.

@derweili, an additional point, not explicitly stated in the AC but to ensure that visual consistency we should make sure that the first tick on the All Traffic chart doesn't get cut off in the way that can be seen in Matt's first screenshot:

![image](https://github.com/google/site-kit-wp/assets/18395600/1c023ea7-871c-470c-8c57-0305ff245e73)

**Comment by derweili** [comment]
I did some more research on the chart library. I don't think there is a ways to fix this using the provded configuration options.

Instead I think we should reuse the logic we already have implemented for the `UserCountGraph` component to limit the ticks. Therefore we could create a custom `useLineChartTicks()` hook, that generates the ticks and subscribes to `resize` event

**Comment by derweili** [comment]
I was unsure where to place the new custom hook in. I know we have a `hooks` folder, but this new hook only makes sense to be used with the `GoogleChart` so I thought placing it next to the `GoogleChart` component makes more sense to me then placing it in the generic hooks folder.

**Comment by techanvil** [comment]
Hey @derweili, if you review this [Slack thread](https://10up.slack.com/archives/C01CA828ZPZ/p1701157783531729?thread_ts=1701020980.747539&cid=C01CA828ZPZ) you'll see that we've been explicitly asked to move away from this existing `UserCountGraph` logic due to the results it gives. Therefore, applying it to all of the graphs would not be the correct approach here.

Actually, I've taken a look and found the `minTextSpacing` option is working OK for me. Could you have applied it to the `UserCountGraph` graph without replacing the tick logic which could explain your odd results?

As to the first tick getting cut off - if we provide a full range of dates for the ticks and remove the first one, that seems sufficient to avoid the problem.

Here's a quick [PoC](https://github.com/google/site-kit-wp/compare/trh/5830-chart-date-ticks-poc) and a video of the results:

https://github.com/google/site-kit-wp/assets/18395600/04908304-6e4d-4024-b221-5f05d0141ab2

If we _do_ want to show the first tick, we can achieve this by increasing the `chartArea.left` value to make room for it. However this means we lose the left-hand alignment of the chart edge to the surrounding context, which we've aimed to avoid to date.

```diff
diff --git a/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/UserCountGraph.js b/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/UserCountGraph.js
index 119b11aeaf..891ebdeaf2 100644
--- a/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/UserCountGraph.js
+++ b/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/UserCountGraph.js
@@ -124,8 +124,6 @@ export default function UserCountGraph( props ) {
 		tick.setDate( tick.getDate() + 1 );
 	}
 
-	chartOptions.hAxis.ticks.shift(); // Get rid of the first tick which may otherwise be cut off.
-
 	// Set the `max` height of the chart to `undefined` so that the chart will
 	// show all content, but only if the report is loaded/has data.
 	if (
@@ -184,7 +182,7 @@ UserCountGraph.chartOptions = {
 	width: '100%',
 	colors: [ '#3c7251' ],
 	chartArea: {
-		left: 7,
+		left: 20,
 		right: 40,
 		height: 300,
 		top: 21,
```

![image](https://github.com/google/site-kit-wp/assets/18395600/19a8e269-ab78-4c13-b862-61456f21e8b0)

Alternatively we could consider moving the Y axis to the left hand of the chart as that should also provide some additional space for the X axis to render.

Anyhow, to move this along, I think we should take the approach of dropping the first tick, we can see how we get on with that and iterate on it from there.

**Comment by derweili** [comment]
I tested the options with the `minTextSpacing` again. Was not able to replicate either. Maybe I had a weird combination of options when trying this yesterday.

Updated IB to not use the manual tick generation but to use the automatic one provided by the Chart library.

The value `100` for `minTextSpacing` seams to replicate a similar behavior to what we currently have.

**Comment by tofumatt** [comment]
@derweili The IB mentions `useLineChartTicks()` in the tests, but I think that can be removed.

Regarding the creation of manual tick marks for `WPDashboardUniqueVisitorsChartGA4` and other places… can Google Charts manage the ticks with `minTextSpacing` everywhere without us actually providing explicit ticks? No worries if not, but given that dimension is already using our **date** data, I'm curious if we could omit the tick generation entirely.

Otherwise looks good. 🙂

**Comment by derweili** [comment]
@tofumatt Google Charts could do this, but this results in the issue @techanvil outlined in [this comment](https://github.com/google/site-kit-wp/issues/5830#issuecomment-1833526209), where the first item get's cut of and replaced with a button and a tooltip.

The trick to prevent this is to remove the first tick. That's why we have to explicitly provide in the ticks.

**Comment by tofumatt** [comment]
Ah, right, sounds good then, thanks for all the investigation on this one! 👍🏻 

IB ✅

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

- Tested on dev environment.
- Verified that All Visitors widget chart updated so it displays the number of date labels using the same logic as the Search Traffic and Performance widgets, providing a consistent look across all SK Dashboard charts.
- Verified that All of the charts in Site Kit that display a date axis which use the MMM d (e.g. "Sep 3") date format.
- Verified zero and gathering data state.
- Verified WP Dashboard.

@kuasha420 I noticed that under viewports having less width 324px and less. The Dates are getting hide and not showing.

![image](https://github.com/google/site-kit-wp/assets/94359491/4a3c0db4-7e2c-4e0b-80c0-cc5cf7586a2a)

![image](https://github.com/google/site-kit-wp/assets/94359491/9e712b7d-3f08-4e9f-a806-33d1c6edd1f7)

**Pass cases-**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/b7a6edb3-74d5-499b-888c-5de8a3d5733c)

![image](https://github.com/google/site-kit-wp/assets/94359491/74577998-b5e6-442b-a5cf-76ea27251b13)

![image](https://github.com/google/site-kit-wp/assets/94359491/ff029291-0cee-4c42-b364-b69c6a766064)

![image](https://github.com/google/site-kit-wp/assets/94359491/1e0ca294-11b6-43c6-9cb3-a3dc7620a805)

![image](https://github.com/google/site-kit-wp/assets/94359491/db3cf6da-cb23-4ea1-98c3-f3c424829239)

![image](https://github.com/google/site-kit-wp/assets/94359491/c56b13b0-b80d-46e8-8ad9-5ee353719250)

![image](https://github.com/google/site-kit-wp/assets/94359491/75291b61-f9d6-4711-b8b7-710e0b9ac198)

![image](https://github.com/google/site-kit-wp/assets/94359491/3e79e712-b494-4079-91c2-1f95c7b05062)

![image](https://github.com/google/site-kit-wp/assets/94359491/c7b1e845-ed76-466f-82b0-2abe99742b90)

![image](https://github.com/google/site-kit-wp/assets/94359491/ee333867-f140-40c2-9b5a-4613539d8fb3)

![image](https://github.com/google/site-kit-wp/assets/94359491/4f702960-147b-45cd-9bfd-c940428b36ec)

</details>

**Comment by mohitwp** [comment]
@kuasha420 Did you get chance to look into this ? Can I move this to execution ?

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@kuasha420 

Tested on dev environment.
**Note** :  I've noticed that "All visitors" widget graph first date is getting cut on viewports having width 338px and less than it. It is a regression due to changes introduced in this ticket because on latest environment "All visitors" widgets date is  not getting cut. 

Let me know if this is quick fix and you want to create follow up issue. For now I created a separate ticket as this is minor issue. 
https://github.com/google/site-kit-wp/issues/8151

**main environment**

![image](https://github.com/google/site-kit-wp/assets/94359491/0b639c95-1d18-492f-bb2c-e2f31a73a4bc)

**Latest environment**

![image](https://github.com/google/site-kit-wp/assets/94359491/e90d7f46-ff17-4a63-9736-6cc362ed0498)
