### ISSUE TITLE
Storybook warnings: Deprecated support for duplicate kinds

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#5878]
## Feature Description
While running `npm run test:visualtest`, there are multiple warnings about duplicate title used in multiple files. Refer to:
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-support-for-duplicate-kinds

```
Browser Console Log 0: JSHandle:Duplicate title used in multiple files; use unique titles or a primary file for a component with re-exported stories.

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-support-for-duplicate-kinds
```

This affects mostly the newly added TwG stories although other stories should not be excluded.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by derweili** [comment]
@asvinb this error does not show up for me anymore. You mentioned TwG stories which have been removed. 
Maybe the other stories have been fixed in the meantime or their titles where duplicates of the TwG stories, which would result in the errors to be fixed, too.

However, could you verify this error is gone for you, too?

**Comment by asvinb** [comment]
@derweili I just checked and you're right, the error no longer shows up. I guess we can close this ticket then @bethanylang @aaemnnosttv
