### ISSUE TITLE
Minor: Spacing for the Learn more about GA4 link on success banner

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5929]
Asana bug bash link: https://app.asana.com/0/1202913874897532/1203046088060645

I'd like to see a space between the sentence above and the learn more about GA4 link. 

![image (9)](https://user-images.githubusercontent.com/93320881/192623224-4f5afb5f-815a-4941-abd9-133ec7210b00.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by asvinb** [comment]
@wpdarren The Learn More link is meant to be inline based on the current implementation. In the screenshot you posted, it dropped to the next line since it does not have enough room to fit within the parent container which itself has a max width of 700px.
<img width="1574" alt="image" src="https://user-images.githubusercontent.com/31818/192766478-534ed4d5-92fa-479e-8142-6e1f976ffc0f.png">

If you resize your browser, this is how the notification will look:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/31818/192766687-929610a0-80f6-409e-a154-831e24e19ae8.png">

While it's possible to have it displayed on another line across all breakpoints, I think we should stick with the current implementation to be consistent with other notifications.

@aaemnnosttv Let me know what you think.

**Comment by wpdarren** [comment]
@asvinb okay, that makes sense, and it is minor, so I am happy to close this or, with whatever you and @aaemnnosttv feel is best.

**Comment by FlicHollis** [comment]
Thanks @asvinb and @wpdarren I will close this ticket and we can open a new one in the future if we deem that necessary.
