### ISSUE TITLE
AdSense connect graphics are loaded regardless of CTA dismissal

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6006]
## Bug Description

The AdSense connect CTA shown at the bottom of the dashboard lazy loads the 3 graphics shown for its slides. Currently, it can be observed that these graphics are being requested by the browser even when the CTA is dismissed and shouldn't be rendered at all.

This seems to be due to a timing issue where it is briefly rendered (triggering these requests) before it is removed again.

## Steps to reproduce

1. Load the dashboard with the AdSense connect CTA dismissed
2. Observe requests in the network console for chunks related to the adsense graphics

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/195936511-3d931ef8-ddf4-4f51-a83a-ee7d51a5df87.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* AdSense CTA graphics should only be loaded on the dashboard when the `adsense-connect-cta` is not dismissed

## Implementation Brief

- In `assets/js/modules/adsense/components/dashboard/AdSenseConnectCTAWidget.js`:
    - Instead of rendering `<WidgetNull />` conditionally, render `<Widget />` containing `<AdSenseConnectCTA />` first if both `adSenseModuleConnected` and `hasDismissedWidget` are explicitly `false` (they return an `undefined` value until resolved, which is falsey. Thus, we need to check if they're `=== false` explicitly).
	- Afterwards, return `<WidgetNull />` unconditionally if the prior return statements are not executed.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

* Load the dashboard with the AdSense connect CTA dismissed
* Observe requests in the network console for chunks related to the AdSense graphics
* `0.js`, `1.js`, `2.js` chunks (files) should not be loaded 

## Changelog entry

* Fix bug that caused AdSense graphics in CTA banner to be loaded when not needed.

**Comment by mohitwp** [comment]
@wpdarren I'm not able to reproduce this issue on latest environment. Can you please check if you are able to recreate this and 0.js, 1.js, 2.js chunks are loading for you ? For me` googlesitekit-modules-adsense-5a9b4bcea7febf15e592.js` file is getting load on latest environment.

<details>

![image](https://user-images.githubusercontent.com/94359491/198274833-77484206-513b-4855-a40d-8e1e1908a520.png)

![image](https://user-images.githubusercontent.com/94359491/198275207-19134d33-1e39-43cb-96df-2485ada73b20.png)

![image](https://user-images.githubusercontent.com/94359491/198275292-f73c7858-fecd-4903-a5a7-79ead08440ed.png)

</details>

**Comment by wpdarren** [comment]
@mohitwp yes, I was also unable to recreate the issue, so its difficult to know if the ticket fixes it. 

@aaemnnosttv is it possible that this can only be seen on a local setup? if not, would you be able to create a screencast?

**Comment by aaemnnosttv** [comment]
@wpdarren @mohitwp – the 0,1,2 js files are only present in a development build, but the issue is not development/local specific, the assets just have different IDs in a production build, (currently 31,32,33 plus a hash) so the QAB should have surfaced this.

I did verify that the issue is fixed though as can be seen here with the current release on the left and the development build on the right but feel free to double check.

<img width="1536" alt="image" src="https://user-images.githubusercontent.com/1621608/199321445-5e09d80a-6bb7-4b91-8a63-7102ccfee939.png">

You can see the JS chunk relates to the AdSense svg graphic here:
<img width="920" alt="image" src="https://user-images.githubusercontent.com/1621608/199321651-7931a062-8436-40c0-a61a-1c7d0eeb98b1.png">

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

Thank you @aaemnnosttv !

- Verified on dev and latest environment.
- On latest environment requests in the network console for chunks related to the AdSense graphics are getting load (31, 32 and 33).
- On dev environment chunks related to the AdSense graphics are not getting load when CTA is dismissed. (31, 32 and 33).

@sashadoes 

**Question** :- Initial issue is resolve now. But, I've noticed that in case when CTA is **not** dismissed then chunks related to the AdSense graphics are getting load on dev. (33.js,34.js and 35.js). Here in this case these files are different from the latest environment. On latest environment (31.js, 32.js and 33.js) chunks files are getting load. Did we changed or removed these files so that 31.js and 32.js files are not getting load in this case ?

Latest - 

![image](https://user-images.githubusercontent.com/94359491/199439513-e00835cb-c464-4c48-98b6-019d9e07f1b7.png)

Dev - 

![image](https://user-images.githubusercontent.com/94359491/199439813-a9619cfe-6a09-4fe3-bdd6-72a7da586764.png)



<details>

![image](https://user-images.githubusercontent.com/94359491/199434718-20a43e97-851c-41c7-8126-955b07ecb618.png)

Dev :- 

![image](https://user-images.githubusercontent.com/94359491/199434939-f2efb919-f09c-4be1-90eb-ad46e7a666ce.png)

![image](https://user-images.githubusercontent.com/94359491/199435049-c14bf518-cb22-4124-9789-0ef03495d175.png)

![image](https://user-images.githubusercontent.com/94359491/199435162-4c1b9787-27e3-41b8-8a5b-502be024dba8.png)

When CTA is not dismissed -

![image](https://user-images.githubusercontent.com/94359491/199436380-d6ab474e-e118-43f5-9b67-8c91b4f90a16.png)

</details>

**Comment by sashadoes** [comment]
Hi @mohitwp. Thanks for your question. 
I have not changed any file load logic within this ticket. 
Looks like the same files have different chanks on dev assuming the dev build is in place. 
I personally do not see any issues.

**Comment by mohitwp** [comment]
### QA Update ✅ 


Thank you @sashadoes. 
> Hi @mohitwp. Thanks for your question. I have not changed any file load logic within this ticket. Looks like the same files have different chanks on dev assuming the dev build is in place. I personally do not see any issues.

- Verified on dev and latest environment.
- On latest environment requests in the network console for chunks related to the AdSense graphics are getting load (31, 32 and 33).
- On dev environment chunks related to the AdSense graphics are not getting load when CTA is dismissed. (31, 32 and 33).
- When CTA is **not** dismissed then chunks related to the AdSense graphics are getting load on dev. **(33.js,34.js and 35.js)**. Here in this case these files are different from the latest environment. On latest environment **(31.js, 32.js and 33.js)** chunks files are getting load. As per Sasha this is just case of having different chunks on dev environment.

<details>

**Latest -**

![image](https://user-images.githubusercontent.com/94359491/199434718-20a43e97-851c-41c7-8126-955b07ecb618.png)

Dev :- 
****
![image](https://user-images.githubusercontent.com/94359491/199434939-f2efb919-f09c-4be1-90eb-ad46e7a666ce.png)

![image](https://user-images.githubusercontent.com/94359491/199435049-c14bf518-cb22-4124-9789-0ef03495d175.png)

![image](https://user-images.githubusercontent.com/94359491/199435162-4c1b9787-27e3-41b8-8a5b-502be024dba8.png)

When CTA is not dismissed -

![image](https://user-images.githubusercontent.com/94359491/199436380-d6ab474e-e118-43f5-9b67-8c91b4f90a16.png)

</details>
