### ISSUE TITLE
Automate plugin deploy to .org repository

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#603]
## Feature Description

Set up a way to automatically deploy the plugin to the .org plugin repository.

* Consider this prebuilt `wordpress-plugin-deploy` GitHub action: https://github.com/marketplace/actions/wordpress-plugin-deploy which takes care of the underlying plumbing.
* Action can be triggered in many ways, including by merging to a specific branch, or whenever a Release is tagged - depending on how we want to manage the .org releases.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a GitHub action which, when creating a new tag (NOT draft tag) takes the ZIP file from the related branch (only support for `master` or `develop` should really be necessary) and deploys it to the wordpress.org plugin repository (SVN URL is `https://plugins.svn.wordpress.org/google-site-kit`).
* Essentially, it needs to take the production build ZIP and put it into the `trunk` directory of the SVN repository. It then needs to run something like the following:
    * `svn ci -m "updated to version v.e.r.s.i.o.n"`
    * `svn copy https://plugins.svn.wordpress.org/google-site-kit/trunk https://plugins.svn.wordpress.org/google-site-kit/tags/v.e.r.s.i.o.n -m "tagged version v.e.r.s.i.o.n"`
* We will likely need to define repository secrets for the WP SVN user name and password. Please include that consideration in the IB and ping @felixarntz to eventually do it.

### Create GitHub Environment

In order to lock down the deployment so only a subset of users can trigger it, we will make use of GitHub Environments and the [Required Reviewers](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#required-reviewers) feature.

As a `google-site-kit` repository admin:

* Following the docs here: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#creating-an-environment
  * Create an environment called `wordpress-plugin-svn`.
  * Assign up to 6 users who will be able to review (trigger) a workflow job.
  * Additionally create the environment secrets `SVN_USERNAME` and `SVN_PASSWORD` with the corresponding SVN credentials for the WordPress Plugin SVN login.

### Extract common action for building release zips:

Within new file `.github/actions/build-zips.yml`:

* Extract the steps from the [**Build Zips**](https://github.com/google/site-kit-wp/blob/c2f2be6e165e3506ff8cae8a55cd899a0f300374/.github/workflows/zips.yml#L27) job as a composite action - see:
  * https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/
  * https://docs.github.com/en/actions/creating-actions/creating-a-composite-action.
https://github.com/google/site-kit-wp/blob/c2f2be6e165e3506ff8cae8a55cd899a0f300374/.github/workflows/zips.yml#L31-L82

Within `.github/workflows/zips.yml`:

* Replace the extracted steps from the **Build Zips** job with a step which calls the `build-zips` action:
```yml
    steps:
      - uses: './.github/actions/build-zips'
```

### Create GitHub workflow

The workflow [.github/workflows/zips.yml](https://github.com/google/site-kit-wp/blob/8ad40511c2d7da06b5628c48be7f193581684c15/.github/workflows/zips.yml) can serve as a reference here.

Within new file `.github/workflows/publish-release.yml`:

* Name the workflow **Publish Release**.
* Set it to trigger on `workflow_dispatch` (i.e., when manually triggered):
```yml
on: workflow_dispatch
```
* Define an optional input called `release_version`:
```yml
inputs:
  release_version:
    description: 'Version'
    required: false
   default: ''
```
* Create a job, `build-zips`, with name `Build Zips`.
  * Set the `environment` for the job to `wordpress-plugin-svn`.
  * Set `runs-on` to `ubuntu-latest` and `timeout-minutes` to `20`.
  * Set the `if` condition to `github.event.ref_type == 'tag' || inputs.release_version != ''`, ensuring the job only runs when triggered for a tag ref, or when the version is manually specified.
  * Create a step which calls the `build-zips` action:
```yml
    steps:
      - uses: './.github/actions/build-zips'
```

* Create a job, `publish-to-svn`, with name `Publish to SVN`.
  * Set `runs-on` to `ubuntu-latest` and `timeout-minutes` to `20`.
  * Set `needs` to `build-zips`.
  * Create a step which downloads the zip artifact - this can be copied from `zips.yml`:
https://github.com/google/site-kit-wp/blob/c2f2be6e165e3506ff8cae8a55cd899a0f300374/.github/workflows/zips.yml#L96-L100
  * Create a step which:
    * Unzips `google-site-kit.zip` into the current directory.
    * Moves the resulting files from their `google-site-kit` dir into the current dir.
    * Removes the zip files and the now empty `google-site-kit` dir.
    * Creates a `.distignore` file, which only contains `.distignore`. This is to ensure the [`.distignore` path](https://github.com/10up/action-wordpress-plugin-deploy/blob/baea4b3d818a0632a6ee6c7aa51c52d668589997/deploy.sh#L53-L58) is followed in the `action-wordpress-plugin-deploy` action (rather than the [`.gitattributes` path](https://github.com/10up/action-wordpress-plugin-deploy/blob/baea4b3d818a0632a6ee6c7aa51c52d668589997/deploy.sh#L58-L93) which [does depend on a Git repo existing](https://github.com/10up/action-wordpress-plugin-deploy/blob/baea4b3d818a0632a6ee6c7aa51c52d668589997/deploy.sh#L86)).
    * In other words, something like this:
```yml
    run: |
      unzip google-site-kit.zip
      mv google-site-kit/* .
      rm -rf google-site-kit *.zip
      echo .distignore > .distignore
```
  * Create a new step which calls the [`action-wordpress-plugin-deploy`](https://github.com/10up/action-wordpress-plugin-deploy) action.
    * `env` should define `SVN_USERNAME` and `SVN_PASSWORD` from `secrets`, and `VERSION` from `inputs`.
```yml
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        VERSION: ${{ inputs.release_version }}
```

### Test Coverage

* N/A

## Changelog entry

* N/A

**Comment by felixarntz** [comment]
Thanks @adamsilverstein for exploring this - that action looks quite promising!

Something I wanna highlight for us to consider is that we'll need a couple extra steps, such as:
* Run `composer update && npm install` before deploying to get the dependencies in.
* Run the same logic that we currently do in `npm run release-zip` (including `npm run build`).

To summarize, we need to make sure all the dependencies are in place before deploying to SVN, but also that we don't deploy more than is needed.

**Comment by felixarntz** [comment]
@aaemnnosttv Some potential inspiration: https://github.com/google/web-stories-wp/blob/main/.github/workflows/plugin-release.yml

**Comment by aaemnnosttv** [comment]
Looks interesting, thanks @felixarntz. One of the things I've been looking into was how to avoid triggering the deploy based on tagging alone (since anyone can push a tag). GitHub Environments are a solution for this and allow [Required Reviewers](https://docs.github.com/en/actions/reference/environments#required-reviewers) which sounds like just what we're looking for:

> Use required reviewers to require a specific person or team to approve workflow jobs that reference the environment. You can list up to six users or teams as reviewers. The reviewers must have at least read access to the repository. Only one of the required reviewers needs to approve the job for it to proceed.

I see now that the web stories release workflow leverages environments as well which is great, although theirs looks like it's doing a fair bit more than we need. Will revisit this soon.

**Comment by eclarke1** [comment]
@aaemnnosttv is this an IB that has to be written by you, or could you be unassigned for someone else to pick up at all? Thanks.

**Comment by aaemnnosttv** [comment]
It could be done by someone else; I'll unassign myself if we're short on actionable IBs right now 👍

**Comment by eugene-manuilov** [comment]
Thanks, @techanvil, but why do we need a new environment for it? Why not to use a simple workflow file that runs for the `release` activity of the [`release`](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#release) event? 

> To ensure a single source of truth for the files that should be included in the plugin:
> * Extract the list of plugin files from bin/release into a new file in the repo root called .plugin-files.
> * Modify bin/release so it reads the list of files from .plugin-files instead of the hardwired list.

Let's call this file `.distignore` since this is what WP CLI uses for its commands.

**Comment by techanvil** [comment]
Hi @eugene-manuilov, thanks for taking a look at this.

> Thanks, @techanvil, but why do we need a new environment for it? Why not to use a simple workflow file that runs for the release activity of the release event?

That's an interesting point. To answer your question, when writing this IB I referred to this AC point:

> There should be a GitHub action which, when creating a new tag (NOT draft tag) takes the ZIP file from the related branch (only support for master or develop should really be necessary) and deploys it to the wordpress.org plugin repository (SVN URL is https://plugins.svn.wordpress.org/google-site-kit).

And, [this comment](https://github.com/google/site-kit-wp/issues/603#issuecomment-824665646) from Evan:

> Looks interesting, thanks @felixarntz. One of the things I've been looking into was how to avoid triggering the deploy based on tagging alone (since anyone can push a tag). GitHub Environments are a solution for this and allow Required Reviewers which sounds like just what we're looking for:

Which in combination pointed me at using a tag to trigger the workflow along with an environment to limit access to it.

However - the `release` event looks like it should be a more elegant solution. I'd be happy to revisit this, do you think we need to update the AC though?

As to your second point:

> Let's call this file `.distignore` since this is what WP CLI uses for its commands.

The new file in question would not be an "ignore" file - more of an "include" file, as it's specifying the list of files to include in the release. The content of the file will be:

```
readme.txt
google-site-kit.php
uninstall.php
dist/assets
dist/config.php
dist/manifest.php
includes
third-party
```

I was debating calling it `.distinclude`, with a nod toward the `.distignore` naming, but I figured that might be a bit confusing, suggesting a relationship between the two files; hence `.plugin-files`, although I am certainly open to suggestion there.

**Comment by aaemnnosttv** [comment]
> Thanks, @techanvil, but why do we need a new environment for it? Why not to use a simple workflow file that runs for the `release` activity of the [`release`](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#release) event?

I suppose we don't need to use an environment for it, but I think we still want to prevent triggering the deployment accidentally (not only limited to certain people). This isn't in the ACs but I think it's worth considering here as this is much more sensitive than the other workflows.

The [referenced workflow from Web Stories](https://github.com/google/site-kit-wp/issues/603#issuecomment-799755715) above only runs manually (`workflow_dispatch`) _and_ uses an environment which is good because it allows for the workflow to be tested without actually deploying.

**Comment by eugene-manuilov** [comment]
> As to your second point:
> 
> > Let's call this file `.distignore` since this is what WP CLI uses for its commands.
> 
> The new file in question would not be an "ignore" file - more of an "include" file, as it's specifying the list of files to include in the release. The content of the file will be:
> 
> ```
> readme.txt
> google-site-kit.php
> uninstall.php
> dist/assets
> dist/config.php
> dist/manifest.php
> includes
> third-party
> ```
> 
> I was debating calling it `.distinclude`, with a nod toward the `.distignore` naming, but I figured that might be a bit confusing, suggesting a relationship between the two files; hence `.plugin-files`, although I am certainly open to suggestion there.

@techanvil, yes, i know that you suggest using it for inclusion, but this is a little bit controversial to approaches used in the software development. Usually, tools use such config files for exclusion to ignore certain files: `.gitignore`, `.eslintignore`, `.dockerignore`, etc. Even the [WP CLI command](https://developer.wordpress.org/cli/commands/dist-archive/) to create distribution archives uses the same approach and allows you to define `.distignore` file to exclude files from archive. I think we need to follow the same approach and use the `.distignore` file which will make our plugin compatible with WP CLI commands and other tools.

**Comment by techanvil** [comment]
> @techanvil, yes, i know that you suggest using it for inclusion, but this is a little bit controversial to approaches used in the software development. Usually, tools use such config files for exclusion to ignore certain files: `.gitignore`, `.eslintignore`, `.dockerignore`, etc. Even the [WP CLI command](https://developer.wordpress.org/cli/commands/dist-archive/) to create distribution archives uses the same approach and allows you to define `.distignore` file to exclude files from archive. I think we need to follow the same approach and use the `.distignore` file which will make our plugin compatible with WP CLI commands and other tools.

Hi @eugene-manuilov, in this particular case I don't think an "ignore" file is the right approach. In fact, I had initially considered attempting a `.distignore` file, however:

* We already do specify the list of files to include for a release, it's just that this list is hardwired into the `bin/release` script. Trying to manage the inverse of this list means we're effectively specifying the list of files for a release in two places, in two different ways (include vs exclude).
* We'd have to remember to update the ignore file any time we added a new filepattern to the repo, putting the maintenance of it out of sync with the include list. Of course we'd also need to ensure any modifications to the include list are then allowed for in the ignore file.

Additionally, to your point about it being a controversial approach - if you consider how the proposed `.plugin-files` include list would be used by `rsync`, it's specifying it as the `--files-from` argument, a standard `rsync` command, which I don't see as being any more contentious than using the `--exclude-from` argument with a `.distignore` file which is what the `wordpress-plugin-deploy` action does... It's just using `rsync` as it's designed...

**Comment by eugene-manuilov** [comment]
@techanvil both approaches have their pros and cons, I would defer it to @aaemnnosttv and @felixarntz to decide what we should use.

> We already do specify the list of files to include for a release, it's just that this list is hardwired into the bin/release script. Trying to manage the inverse of this list means we're effectively specifying the list of files for a release in two places, in two different ways (include vs exclude).

I don't see a problem here. We can always update the `bin/release` script to make use of the `.distignore` file too to avoid maintaining two lists.

> We'd have to remember to update the ignore file any time we added a new filepattern to the repo, putting the maintenance of it out of sync with the include list. Of course we'd also need to ensure any modifications to the include list are then allowed for in the ignore file.

Likewise, we will have to remember to update the inclusion list any time we added a new file to the repo that needs to be added to the plugin archive. We will need to maintain one file anyway.

**Comment by techanvil** [comment]
@eugene-manuilov, all valid points. Let's defer to @aaemnnosttv and @felixarntz to decide the direction on this one...

**Comment by aaemnnosttv** [comment]
@techanvil @eugene-manuilov I'm not sure we need to extract an ignore/includes file here. The files that are included in the release zip are already defined in the release script, so why not generate the zip as usual and then just extract the files into the svn working directory (or otherwise sync them)? Generating a zip isn't particularly expensive so we shouldn't go out of our way to avoid it. Let's not change the way the release zip is generated here if we don't need to.

As to the "polarity" of file selection if such an external list were needed, we only include 8 paths in the release which has needed very few revisions over time. If this were an ignore/exclusion list, it would likely be larger and seems generally more vulnerable to something getting included that shouldn't be. It's also worth noting that the `.distignore` used by wp-cli does not support exclusions in the way most other ignore files do (see https://github.com/wp-cli/dist-archive-command/issues/44).

**Comment by eugene-manuilov** [comment]
> ... so why not generate the zip as usual and then just extract the files into the svn working directory (or otherwise sync them)? ...

@aaemnnosttv there is the [`action-wordpress-plugin-deploy`](https://github.com/10up/action-wordpress-plugin-deploy) action that already automates plugin deployment to wordpress.org repository. I think we could use it instead of creating our own solution for it (actually that's why I was suggesting using `.distignore` initially 😄).

**Comment by aaemnnosttv** [comment]
@eugene-manuilov sure, I think we could use that if it makes sense but even then, that doesn't restrict how we build the plugin for release. We could still build the release zip as we do now, uploading the zip as an artifact, then in a deploy job simply download it and extract the files before the plugin deploy action. We could probably do it a little more efficiently but you get the idea 🙂

**Comment by aaemnnosttv** [comment]
Thanks @techanvil!

> this action depends on using a `.distignore` or `.gitattributes` file to specify files to ignore when copying from `$GITHUB_WORKSPACE` to the SVN repo, so we'd have to be happy switching to an "ignore" approach if we're to use that action. The relevant code is here: [10up/action-wordpress-plugin-deploy@`5c0347b`/deploy.sh#L53-L93](https://github.com/10up/action-wordpress-plugin-deploy/blob/5c0347bceed8220198fc9b8e8147cb87525166f5/deploy.sh#L53-L93)

It uses one of those files yes, but in the absence of either it will create a default ignore to ensure a few sensible defaults are excluded. If we take the approach of sourcing the files from the release zip, there's really nothing to ignore other than the zip file itself, but that could be simply deleted after extracting so in our case I don't think we need to cater for any ignores because the action should be able to run with the workspace prepared with only the files we want to deploy.

> So, in order to progress this:
> 
> * Can we ascertain that taking the "ignore file" approach is out of scope here, or do we want to bring that back in, so as to make use of `action-wordpress-plugin-deploy`?

Shouldn't be necessary I think per above.

> * Which direction should we take, of numbers 1-4 above (or 5, for something new)?

I think I'd prefer to see something using # 1 as a starting point, using `workflow_dispatch`. This is what the Web Stories uses as well (although their workflow does quite a bit more than we would need) https://github.com/google/web-stories-wp/blob/b6d5929118e134953717a73a8206d9d3e79c7351/.github/workflows/plugin-release.yml.

Here's what I'm thinking:

- dedicated workflow
- workflow_dispatch
- build release zip(s)
    - can perhaps define this in a centralized way to not duplicate the steps here as GHA is a bit more flexible now in this regard (see https://github.com/google/site-kit-wp/issues/3969)
- upload zips to release (see https://github.com/google/site-kit-wp/issues/865)
- publish GitHub Release
- (prod env) deploy to wordpress.org
	- deploys same code as was uploaded to release once approved

The only tricky thing there is maybe taking an input for the workflow run to identify the GH Release as we normally create that ahead of time as a draft which I think we would still want to do.

How does that sound?

**Comment by aaemnnosttv** [comment]
Thanks @techanvil,

> 1. You've mentioned uploading the zips to the release, and publishing the release. These steps are outside of the scope of the ACs here - do you want to bring them into this ticket?

Uploading the zips is somewhat outside, so not necessary to do here, but if it isn't much trouble, we do have an issue for it that could be closed if it's easier or more beneficial to do here. I think it would be good to keep a permanent reference to the exact code that was deployed to WP .org. That way we could also ensure the two match if needed.

> 2\. Where you say "deploys same code as was uploaded to release once approved", could you expand on that - what do you mean by approved here?

I was referring to the [Required reviewers](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#required-reviewers) feature of environments that I think we will probably want on the main deploy job. Nothing needs to be done in the workflow for this other than adding the environment on the job, it's an optional a safeguard for running a job that can be configured outside of the file-based configuration.

**Comment by techanvil** [comment]
Thanks @aaemnnosttv. After an initial look I've decided to leave the release related stuff out of this ticket, it looks like it'll require enough work to merit its own issue.

I've updated the IB to follow the other points, notably, a dedicated workflow which is manually triggered and also access controlled via an environment, building the release zip via a common action, and updating SVN via `action-wordpress-plugin-deploy`.

**Comment by aaemnnosttv** [comment]
Thanks @techanvil ! Is this ready for review again?

**Comment by techanvil** [comment]
Hi @aaemnnosttv, yup, it is. Apologies, I realise it should have been moved back to the IBR column, which I've now done. Cheers

**Comment by aaemnnosttv** [comment]
Thanks @techanvil!

> * Set the `if` condition to `github.event.ref_type == 'tag'`, ensuring the job only runs when triggered for a tag ref.

Is this necessary now that it's set to be triggered manually? We probably shouldn't add additional restrictions to allow this to be testable between releases, if needed.

I see that the action somewhat assumes/expects to run on a tag ref, but we can also provide the version manually, which again might be useful for testing (i.e. triggering the workflow but not approving the deploy).

---

Overall this looks great – nice work! Nothing else from me other than the above points.

Any other thoughts/feedback @eugene-manuilov @felixarntz ?

**Comment by felixarntz** [comment]
@aaemnnosttv Just to confirm what I'm understanding from the IB and previous conversation, the proposed workflow would be that someone manually triggers the GH workflow so that the code from a certain branch is built as a ZIP and that is then deployed to SVN right? +1 for decoupling it from GH tagging - that probably would have been simpler, but also have limitations.

I'm wondering (apologies if I missed that point somewhere), how does that tie into GitHub releases? Is it completely decoupled then? I like the idea of decoupling it, but then eventually it would be nice if the same action also created the GitHub tag and release. This way a release would only encompass triggering that one workflow to get both the GH release (which is really just creating a tag with the content of that respective version's changelog within `readme.txt`) and the SVN/wordpress.org release. Maybe initially we could only do the latter to not make things more complicated, but I think eventually the release process should encompass both parts in an automated workflow.

Great work @techanvil @eugene-manuilov so far!

**Comment by techanvil** [comment]
> Thanks @techanvil!
> 
> > * Set the `if` condition to `github.event.ref_type == 'tag'`, ensuring the job only runs when triggered for a tag ref.
> 
> Is this necessary now that it's set to be triggered manually? We probably shouldn't add additional restrictions to allow this to be testable between releases, if needed.
> 
> I see that the action somewhat assumes/expects to run on a tag ref, but we can also provide the version manually, which again might be useful for testing (i.e. triggering the workflow but not approving the deploy).
> 
> Overall this looks great – nice work! Nothing else from me other than the above points.

Thanks @aaemnnosttv - that's a good point, and I've updated the IB to specify an optional `release_version` input which can be used to manually specify the version.

Rather than completely remove the condition you mention, I've modified it to be `github.event.ref_type == 'tag' || inputs.release_version != ''` as we do still need one or the other in order to determine the version.

If you search for "version" on this page it'll highlight all the relevant areas in the IB where I've just made changes.

**Comment by eugene-manuilov** [comment]
Thanks, @techanvil. Nice work. IB looks good to me ✔️.

**Comment by aaemnnosttv** [comment]
> Just to confirm what I'm understanding from the IB and previous conversation, the proposed workflow would be that someone manually triggers the GH workflow so that the code from a certain branch is built as a ZIP and that is then deployed to SVN right?

@felixarntz that's correct, although it would be a specific version that's already tagged rather than a branch. We could enhance it in the future to automate the creation of a release as you said but no need to go that far just yet, so at least for now it's defined in a decoupled way.

@techanvil since we're extracting a composite action for building zips here, it would be nice if we could compose that from other repeatable steps that we use in other jobs too (npm install, etc). I don't recall if GHA supports nesting these but would be nice if we could.

This looks 👍  from me unless there's anything else from @felixarntz ?

**Comment by felixarntz** [comment]
IB ✅  from my end as well

**Comment by FlicHollis** [comment]
Hi @eugene-manuilov as discussed on the sprint planning call I will un-assign you so this can be picked up by another engineer in the next sprint. Thanks!

**Comment by aaemnnosttv** [comment]
@techanvil maybe you'd be interested in picking this up since you worked on the IB?

**Comment by aaemnnosttv** [comment]
See [internal task](https://app.asana.com/0/0/1206195841555766/f) for related GitHub admin.

**Comment by aaemnnosttv** [comment]
## ⚠️ Approval

The new workflow has been added as defined here but there is a bug in the implementation which [prevents it from completing successfully](https://github.com/google/site-kit-wp/actions/runs/7546698648/job/20545191738). We'll address this in a follow-up for the next release.
