### ISSUE TITLE
Implement custom GA events for GA4 activation banner

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#6042]
Several new custom GA tracking events should be implemented to capture user interactions with the GA4 activation banner.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In the first part of the GA4 activation banner (i.e. "reminder banner"):
    * Trigger GA event `view_notification` when the banner notification is shown.
    * Trigger GA event `confirm_notification` when the user clicks "Set up now".
    * Trigger GA event `dismiss_notification` when the user clicks "Remind me later".
    * Trigger GA event `click_learn_more_link` when the user clicks "Learn more about GA4".
    * The event category for all 4 above should be `{viewContext}_ga4-reminder-notification`.
* In the second part of the GA4 activation banner (i.e. "setup banner"):
    * Trigger GA event `view_notification` when the banner notification is shown.
    * Trigger GA event `create_property` when the user clicks "Create property" (i.e. in the scenario where they have no GA4 properties at all).
    * Also trigger GA event `create_property` when the user clicks "Connect" in the alternative scenario while having the dropdown configured to set up a new property.
    * Trigger GA event `connect_property` when the user clicks "Connect" with an existing property selected.
    * The event category for all 4 above should be `{viewContext}_ga4-setup-notification`.
    * **Please ensure:** These events should only be triggered when the user "actively does" these interactions. They must not be triggered after returning from OAuth (to grant the additional scope) when the banner is simply auto-submitting itself.
* In the third part of the GA4 activation banner (i.e. "success banner"):
    * Trigger GA event `view_notification` when the banner notification is shown.
    * The event category should be `{viewContext}_ga4-success-notification`.
* In the Settings screen's module panel list, with the Analytics module active:
   * Trigger GA event `view_ga4_button` when the button "Connect Google Analytics 4" is shown on the Analytics panel header.
   * Trigger GA event `click_ga4_button` when the user clicks that button (to get to the relevant GA panel UI).
    * The event category for the 2 above should be `{viewContext}_module-list`.

#### action: `view_notification`

* Call `trackEvent` with the attributes in the AC with a `useMount` (see `SetupSuccessBannerNotification` for an example).

#### action: `confirm_notification`

* Add a callback function using `useCallback` that calls `trackEvent` with the attributes in the AC. Wrap the `onSubmitSuccess` callback inside this callback function.
* Pass the above callback function to the `onCTAClick` prop of the `BannerNotification` component.

#### action: `dismiss_notification`

* Add a callback function using `useCallback` that calls `trackEvent` with the attributes in the AC. Wrap the `showTooltip` callback inside this callback function.
* Pass the above callback function to the `onDismiss` prop of the `BannerNotification` component.

#### action: `view_notification`

* Create a local state to trigger the event only once.
* Add an effect hook that calls `trackEvent` with the attributes in the AC when the `autoSubmit` is not `true` AND the local state is `false`. Set the local state to `true` after the event is triggered. (see `ThankWithGoogleSupporterWallNotification` for an example).

The below handle click events should be triggered inside the `handleSubmitChanges` callback when the `autoSubmit` is not `true`:

#### action: `create_property` for the first scenario

* Call `trackEvent` with the attributes in the AC when the variant is `NO_EXISTING_PROPERTY`.

#### action: `create_property` for the second scenario

* Call `trackEvent` with the attributes in the AC when `ga4PropertyID` is `PROPERTY_CREATE`.

#### action: `connect_property`

* Call `trackEvent` with the attributes in the AC when `ga4PropertyID` is not `PROPERTY_CREATE` AND the variant is `EXISTING_PROPERTY`.

#### action: `view_notification`

* Call `trackEvent` with the attributes in the AC with a `useMount` (see `SetupSuccessBannerNotification` for an example).

#### action: `view_ga4_button`

* Create a local state to trigger the event only once.
* Add an effect hook that calls `trackEvent` with the attributes in the AC when the `module` is available AND GA4 is _NOT_ connected AND the local state is `false`. Set the local state to `true` after the event is triggered. (see `ThankWithGoogleSupporterWallNotification` for an example).

#### action: `click_ga4_button`

* Call `await trackEvent` with the attributes in the AC inside the `Connect Google Analytics 4` button's `onClick` callback before navigating to the GA4 settings edit page.
* It's a good idea to extract the above inline callback to a named function and pass it to the `onClick` prop.

### Test Coverage

* No new tests are to be added.

## QA Brief

* Verify the different scenarios in the AC.
* Verify no GA events are sent when the banner notification is not rendered.
* Verify no GA events are sent when the `Connect GA4 button` is not displayed on the settings page (when Analytics is disconnected or GA4 is connected ). Also verify this when Analytics is not connected and the regular `Connect Analytics` button is rendered.

## Changelog entry

* Implement custom Analytics events for the GA4 Activation Banner.

**Comment by tofumatt** [comment]
IB ✅ 

I think the IB covers everything accurately, but make sure to check when using `useMount` that the event we're tracking is always appropriate; eg. the banner will actually be shown. I think in this case it's always true, but #6023 has examples of when we call `trackEvent` when we shouldn't. Just something to watch out for 😄

**Comment by felixarntz** [comment]
@jimmymadon @tofumatt Replied in https://github.com/google/site-kit-wp/pull/6096/files#r1012246885.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@jimmymadon I posted regression issue https://github.com/google/site-kit-wp/issues/6048#issuecomment-1303188204 . I'm not sure which which PR causing this issue. Can you please confirm that this regression is not due to the related PR.  ?

- Verified on main branch.
- Verified all listed scenarios in AC - GA events triggering and event category name is as per AC.
- Verified no GA events are sent when the banner notification is not rendered.
- Verified no GA events are sent when the Connect GA4 button is not displayed on the settings page (when Analytics is disconnected or GA4 is connected ). Also verify this when Analytics is not connected and the regular Complete Analytics button is rendered.
- Verified both main and entity dashboard.

<details>

View Notification

![image](https://user-images.githubusercontent.com/94359491/199946882-9e280cbf-3dab-411d-88c0-3b2e53c5490b.png)

![image](https://user-images.githubusercontent.com/94359491/199946922-dbdaf923-e1a9-4389-b6db-956bf7bc2214.png)

Confirm_notification

![image](https://user-images.githubusercontent.com/94359491/199947013-703e7e4b-0e23-4456-8a71-a155fddd96ab.png)

![image](https://user-images.githubusercontent.com/94359491/199947065-28d00600-4772-460a-8a01-07a703e1b03d.png)

Learn More -

![image](https://user-images.githubusercontent.com/94359491/199947133-ef21cfc3-4ba2-40ec-8358-7c5d83c360f4.png)

![image](https://user-images.githubusercontent.com/94359491/199947348-7d297ce0-4c65-49a7-8241-01c444d648bc.png)

Dismiss notification-

![image](https://user-images.githubusercontent.com/94359491/199947616-ecd7d4cc-86e7-406c-be29-bfdd92bd19e9.png)

![image](https://user-images.githubusercontent.com/94359491/199947657-ad649681-7527-4f13-a82c-a66589251e5e.png)

Set Up banner - view notification

![image](https://user-images.githubusercontent.com/94359491/199947786-825d2bf8-db59-4b73-9069-3f5ff25aa18c.png)

![image](https://user-images.githubusercontent.com/94359491/199947842-5911a931-04b6-4e68-8107-b276ca1d73d2.png)

Set Up banner - create property

![image](https://user-images.githubusercontent.com/94359491/199950588-9955312c-5db7-4730-9d91-f23260753bc4.png)


![image](https://user-images.githubusercontent.com/94359491/199947908-299fb192-97b3-4a4e-94bc-497a03c4a54d.png)


https://user-images.githubusercontent.com/94359491/199951040-64ed2027-29cf-4490-a3a0-d43f1c48757d.mp4


https://user-images.githubusercontent.com/94359491/199951110-ebc46937-1b10-4912-bf2f-7380ce03b0e7.mp4

OAuth Set up -


https://user-images.githubusercontent.com/94359491/199951173-1d6f3d2c-abe0-454e-8ff9-12a7fbf863c2.mp4

Success banner - View notification

![image](https://user-images.githubusercontent.com/94359491/199951260-a871de0b-8381-40ad-ba18-24b3e85b523b.png)

![image](https://user-images.githubusercontent.com/94359491/199951329-85def2ff-97d0-4e68-a269-c910e13f4a25.png)

Settings page -

![image](https://user-images.githubusercontent.com/94359491/199951416-d682f335-7fd9-48b0-be6b-aaee0b4f51d9.png)

![image](https://user-images.githubusercontent.com/94359491/199951460-0bd35cfa-16b3-4403-a6d2-f2a3a08e6541.png)

**Comment by mohitwp** [comment]
### QA Status ✅ 

- Verified on main branch.
- Issue reported [here](https://github.com/google/site-kit-wp/issues/6048#issuecomment-1303188204) is resolved now.

- Verified all listed scenarios in AC - GA events triggering and event category name is as per AC.
- Verified no GA events are sent when the banner notification is not rendered.
- Verified no GA events are sent when the Connect GA4 button is not displayed on the settings page (when Analytics is disconnected or GA4 is connected ). Also verify this when Analytics is not connected and the regular Complete Analytics button is rendered.
- Verified both main and entity dashboard.

<details>

View Notification

![image](https://user-images.githubusercontent.com/94359491/199946882-9e280cbf-3dab-411d-88c0-3b2e53c5490b.png)

![image](https://user-images.githubusercontent.com/94359491/199946922-dbdaf923-e1a9-4389-b6db-956bf7bc2214.png)

Confirm_notification

![image](https://user-images.githubusercontent.com/94359491/199947013-703e7e4b-0e23-4456-8a71-a155fddd96ab.png)

![image](https://user-images.githubusercontent.com/94359491/199947065-28d00600-4772-460a-8a01-07a703e1b03d.png)

Learn More -

![image](https://user-images.githubusercontent.com/94359491/199947133-ef21cfc3-4ba2-40ec-8358-7c5d83c360f4.png)

![image](https://user-images.githubusercontent.com/94359491/199947348-7d297ce0-4c65-49a7-8241-01c444d648bc.png)

Dismiss notification-

![image](https://user-images.githubusercontent.com/94359491/199947616-ecd7d4cc-86e7-406c-be29-bfdd92bd19e9.png)

![image](https://user-images.githubusercontent.com/94359491/199947657-ad649681-7527-4f13-a82c-a66589251e5e.png)

Set Up banner - view notification

![image](https://user-images.githubusercontent.com/94359491/199947786-825d2bf8-db59-4b73-9069-3f5ff25aa18c.png)

![image](https://user-images.githubusercontent.com/94359491/199947842-5911a931-04b6-4e68-8107-b276ca1d73d2.png)

Set Up banner - create property

![image](https://user-images.githubusercontent.com/94359491/199950588-9955312c-5db7-4730-9d91-f23260753bc4.png)


![image](https://user-images.githubusercontent.com/94359491/199947908-299fb192-97b3-4a4e-94bc-497a03c4a54d.png)


https://user-images.githubusercontent.com/94359491/199951040-64ed2027-29cf-4490-a3a0-d43f1c48757d.mp4


https://user-images.githubusercontent.com/94359491/199951110-ebc46937-1b10-4912-bf2f-7380ce03b0e7.mp4

OAuth Set up -


https://user-images.githubusercontent.com/94359491/199951173-1d6f3d2c-abe0-454e-8ff9-12a7fbf863c2.mp4

Success banner - View notification

![image](https://user-images.githubusercontent.com/94359491/199951260-a871de0b-8381-40ad-ba18-24b3e85b523b.png)

![image](https://user-images.githubusercontent.com/94359491/199951329-85def2ff-97d0-4e68-a269-c910e13f4a25.png)

Settings page -

![image](https://user-images.githubusercontent.com/94359491/199951416-d682f335-7fd9-48b0-be6b-aaee0b4f51d9.png)

![image](https://user-images.githubusercontent.com/94359491/199951460-0bd35cfa-16b3-4403-a6d2-f2a3a08e6541.png)
