### ISSUE TITLE
Do not output TwG snippet if JSON encoding data fails

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#6064]
This is extremely unlikely to happen, but a Google security review for the TwG launch in Site Kit pointed out that we should not unconditionally render the return value of `wp_json_encode()` in the TwG snippet. Technically, this certainly makes sense, as the return value may be `false`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `wp_json_encode()` usage for the data to include in the TwG JS snippet in the frontend should have its return value checked.
    * If the result is false-y (which should never happen), the value `null` should be passed instead.
    * This way the snippet is still rendered - it may be broken, but that's okay since in that case there clearly would be a problem, and it's more transparent that we still render the snippet than if it wasn't rendered at all.

## Implementation Brief

* In the TwG `Web_Tag::enqueue_twg_script()` method:
    * Before creating the `$twg_inline_script` variable, check the return value of the `wp_json_encode( $subscription )` call.
    * If that return value is false-y (e.g. `! $json_encoded`), instead set it to a string `null`, so that in the JS snippet it becomes the actual `null` type.

### Test Coverage

* N/A

## QA Brief

* It will be impossible to create a scenario which will test the case we are preventing against without changing code. However, we should verify that the TwG snippet/tag is added as normal when TwG is enabled and a supporter wall widget is added to the site.
<img width="652" alt="Screenshot 2022-10-26 at 23 42 56" src="https://user-images.githubusercontent.com/1721319/198152524-8d233560-7d5a-4841-a172-90ed3ecb078a.png">

## Changelog entry

* Do not attempt to render TwG subscription data unconditionally in the frontend if JSON encoding fails.

**Comment by techanvil** [comment]
IB is good, but I am bumping to a 3 as I think testing could push it over that 1 estimate.

IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@jimmymadon I have an observation re the placement of the snippet.  On the screenshot in the QAB I see that it is commented with `Thank with Google snippet added by Site Kit` but when I look at the source code this does not appear. This might be expected because the screenshot was from a code editor, but thought I would check.

This is what I see.

![image](https://user-images.githubusercontent.com/73545194/198420365-ea3ae1a4-14af-4dea-a508-9600fedcd5d8.png)

**Comment by tofumatt** [comment]
@wpdarren Looks like your output is slightly different, possibly because of the site you tested on or the fact that Site Kit was running in production mode when you tested. The comment was probably stripped out by a code optimiser and I notice your quotes are standardised to single-quotes as well.

That shouldn't be an issue, it only matters that the actual JS is output 👍🏻 

I'll move to approval 🙂

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The TwG snippet/tag is added as normal when TwG is enabled and a supporter wall widget is added to the site.  I checked the code and noted an [observation above](https://github.com/google/site-kit-wp/issues/6064#issuecomment-1294254519), which Matthew has confirmed is not an issue. 

![image](https://user-images.githubusercontent.com/73545194/198557994-509ad73c-0bec-4522-89f6-1812254a3d32.png)
