### ISSUE TITLE
Update/finalize the TwG CTA + counter/button placement depending on TwG placement

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#6065]
We need to finalize the placement of the Thank with Google CTA and Thank with Google counter/button placeholder elements loaded by the `twg.js` file, based on these possible scenarios:

* [ ] Dynamic (CTA is floating)
* [ ] Fixed on top of article
* [ ] Fixed below article
* [ ] Fixed below first paragraph

See this Asana task for more context: https://app.asana.com/0/1202629863017211/1203233322721879

Related: #5450

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The TwG counter (`counter-button`) should never be displayed next to the TwG CTA (`twg-button`), i.e. this should be modified from how it is behaving now. The placement setting should primarily apply to the CTA, with the counter being placed as follows:
    * If the TwG placement is static/fixed and above the content, the counter should be displayed below the content.
    * If the TwG placement is static/fixed and below the content, the counter should not be displayed at all.
    * If the TwG placement is static/fixed and below the first paragraph, the counter should be displayed below the content.
    * If the TwG placement is dynamic/floating (in any way), the counter should be displayed statically below the content.
        * This last case is particularly different, since today in that situation Site Kit doesn't display anything inline. Going forward the counter should still be displayed statically below the content in that case (i.e. only the CTA is floating).
* The behavior of the TwG `auto` fixed placement should be updated so that it is the same as "above the content" (not "below the content").

## Implementation Brief
* Using `includes/Modules/Thank_With_Google/Web_Tag.php`,
	* Update `update_the_content` to move the counter (`<div counter-button ...`) as per the AC when TwG placement is static/fixed.
		* Create a new variable `counter_placeholder` which holds the counter markup, including the inline styles, from `cta_placeholder`. The latter should be updated to remove the counter markup.
		* Remove the inline styles for `.googlesitekit-twg-wrapper` since we don't ever have the button and counter side by side.
		* When TwG placement is floating (`! $this->has_static_cta_placement()`), position the counter (or don't render it, depending on conditions) as per the AC.
* Tweak the inline styles if needed to accomodate those changes on the FE.

### Test Coverage
* Update `tests/phpunit/integration/Modules/Thank_With_Google/Web_TagTest.php` to cater for the above changes.

## QA Brief

* Connect and fully configure TwG module.
* Test and verify the placement (or lack thereof) of the TwG Counter for all the Static and Dynamic CTA placements.
    * Make sure it matches with the AC. 
* Also make sure that the populated CTA and Counters looks fine in the FE. 
* Check the HTML to make sure the Snippets are placed correctly and are wrapped by the Site Kit Snippet comments. 

## Changelog entry

* Adjust the Thank with Google counter/button position depending on the placement configuration.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@kuasha420 I am seeing a number of issues which I have detailed below.

1. As you can see from the screencast below, there's a flicker, where the TwG button flashes with a large button in the style of the theme, and then loads as it should. I set the screencast to fast 3G so you can see it in action.  I have noticed that the graphic for the TwG button has been changed (assuming from the .js file side with TwG team) so right now I am unsure if it is this ticket or the change that they have made. 

https://user-images.githubusercontent.com/73545194/198595526-a9c2131a-4803-44ca-aae5-ecaa5444e1f2.mp4

2. Set to Overlay with low and high prominence. The counter isn't placed directly below the content. It's left aligned and looks odd.  Tested this on a few different WordPress themes. 

![image](https://user-images.githubusercontent.com/73545194/198586161-aec32506-9e75-4b29-9084-0d6c25f32b07.png)

3. Set to Fixed and Auto and also Above the content placement. 

The TwG counter is displayed below the content, which from reading the AC appears to be correct, but it isn't placed directly below the content. It's left aligned and looks odd.  In addition, the TwG button is also left aligned rather than directly above the content.  This wasn't the case before so like issue 1. this was changed either by this ticket, or, from the change the TwG team made to the button. 

![image](https://user-images.githubusercontent.com/73545194/198600958-f11131e9-ed48-47c6-ae3f-f1e6d21470a9.png)

4. Set to Fixed and Below the content placement. 

The TwG counter does not appear which is expected.  The TwG button though isn't placed directly below the content. It's left aligned and looks odd. Same as other issues above. 

![image](https://user-images.githubusercontent.com/73545194/198603117-4e536e7a-8dbc-458b-8ed1-11ddedffbee5.png)

5. Set to Fixed and after the 1st paragraph. 

The TwG counter appears below the content which is expected.  Both the TwG button is placed under the first paragraph but both and counter and button are left aligned and looks odd.  Same as other issues above. 

![image](https://user-images.githubusercontent.com/73545194/198606082-a5282c71-f544-4cf0-a086-c027ed7ed558.png)

**Comment by kuasha420** [comment]
@wpdarren Thank you for the thorough QA report. 

I have opened a follow up PR addressing the alignment issues. The flicker and unstyled buttons were already there before this ticket, I think it's on TwG team to fix. Still, if you think it's something worth wider visibility. feel free to create a separate issue or Asana task. 

 The graphics are also changed in the TwG side. 

Cheers.

**Comment by tofumatt** [comment]
Worth noting that if there is a post with a single paragraph, the button and counter _will_ still be placed together, but this is more/less unavoidable unless we start to check the number of blocks in the post, and even that'd be problematic. I'd say best to accept that as a known issue 🙂

**Comment by wpdarren** [comment]
### QA update: ✅ 

**Verified:**

- The placement (or lack thereof) of the TwG Counter for all the Static and Dynamic CTA placements matches with the AC. 
- Also made sure that the populated CTA and Counters looks fine in the FE.
- Tested on desktop and mobile

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/199034600-e9bd7a9f-c7f0-453e-8002-610ab560a941.png)
![image](https://user-images.githubusercontent.com/73545194/199034638-92bede4b-26e6-41a1-ac8e-a94e241215e7.png)
![image](https://user-images.githubusercontent.com/73545194/199034674-ccf83f7f-cefa-49be-b4fc-43d265bc3f04.png)
![image](https://user-images.githubusercontent.com/73545194/199034697-68fc6d51-f3f8-42b1-ab71-c78c39d04c4d.png)
![image](https://user-images.githubusercontent.com/73545194/199034715-22e3866b-eccf-40e7-aac5-3e8f92b7ae70.png)
![image](https://user-images.githubusercontent.com/73545194/199034767-5ba9af9e-192f-4ee0-9dd1-6c9df0b6fdc0.png)
![image](https://user-images.githubusercontent.com/73545194/199034799-9192c56d-17e8-41f9-acb0-222e0713b5d3.png)

</details>
