### ISSUE TITLE
Add Analytics setup/settings logic to determine Google Tag settings

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#6081]
With the new Google Tag logic in place, the Analytics module now needs to determine the Google Tag ID to use whenever the GA4 web data stream / measurement ID changes. Concretely, this could be the case in the module setup, or settings, or the GA4 activation banner logic.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

_If_ the `gteSupport` feature flag is enabled:
* Whenever the GA4 web data stream is set/updated (including when a new one has been just created) in the `modules/analytics-4` store (concretely, the `webDataStreamID` and `measurementID` settings), logic should run to populate the corresponding Google Tag data:
    * The `getGoogleTagContainer( measurementID )` selector from #6079 should be used to identify the Google tag container.
    * This will return a container object, from which the following values need to be stored as module settings (see #6077 which introduced these settings):
        * The `accountId` and `containerId` fields on the object should be stored as `googleTagAccountID` and `googleTagContainerID` respectively.
        * To set the `googleTagID` setting, the following logic should be used (based on the `tagIds` field):
            * If the `tagIds` list contains any tag starting in "GT-", use that one. (If there are multiple "GT-" tags, use any one, e.g. the first one.)
            * Otherwise, if there is any tag ID that is the same as the GA4 measurement ID, use that one.
            * Otherwise, if there is any other tag ID that starts in "G-", use that one.
            * Otherwise, use _any_ tag ID in there (unlikely but possible - this would be a tag ID starting in "AW-").
    * Saving the GA4 module settings should then naturally save those 3 additional settings as well.
* The same logic as above also needs to be implemented on the server-side for the Analytics provisioning callback (concretely in `Analytics_4::handle_provisioning_callback()`) where the new web data stream is being created.
    * Since the same logic is needed on the server and client for different use-cases, potentially this should be implemented in another REST data point that handles all of it, so that the logic happens on the server, but can be triggered on demand from the client.
* From an end user perspective, the above should result in those 3 settings to be set whenever a user goes through the Analytics setup, modifies the GA4 settings, or goes through the GA4 activation banner _with the feature flag enabled_.

## Implementation Brief

Note, taking the direction from the AC to implemented a REST data point to share logic, this IB does not make use of the `getGoogleTagContainer`, rather the container lookup is performed on the server side via the REST data point.

Within `includes/Modules/Analytics_4.php`:

- Create a new protected method `get_google_tag_settings_for_measurement_id`.
  - This should take a `$measurement_id` parameter.
  - Reusing the logic from the REST data points implemented in #6078 (extract this logic to separate methods if needs be):
    - Retrieve the Google Tag container for the measurement ID.
    - Create an array with keys `googleTagAccountID` and `googleTagContainerID` with the values of the container fields `accountId` and `containerId`.
    - Set the `googleTagID` key on this array with the value according to the logic detailed in the AC.
  - Return this array as the method's return value.
- Create a new REST data point, `GET:google-tag-settings`.
  - This should expect a `measurementID` parameter in the request payload.
    - As the data point name is more generic this could be expanded to receive other parameters in future.
  - Call `get_google_tag_settings_for_measurement_id` with the measurement ID and return the result.
  - If an error occurs, return a suitable error status code and message.
- If the `gteSupport` feature flag is enabled:
  - In the `handle_provisioning_callback` method, call `get_google_tag_settings_for_measurement_id` with the web data stream's measurement ID and merge the result into the module settings.

Within `assets/js/modules/analytics-4/datastore/properties.js`:

- Create a fetch data store called `getGoogleTagSettings` for the new `GET:google-tag-settings` data point.
- Add a new action creator generator function `*updateSettingsForMeasurementID`.
  - This should take a `measurementID` parameter.
  - Dispatch `setMeasurementID` with the passed `measurementID`.
  - If the `gteSupport` feature flag is enabled:
    - If `measurementID` is empty dispatch `setGoogleTagAccountID`, `setGoogleTagContainerID` and `setGoogleTagID` with empty strings and return.
    - Otherwise dispatch `fetchGetGoogleTagSettings`, wait for the result, and on success dispatch `setGoogleTagAccountID`, `setGoogleTagContainerID` and `setGoogleTagID` with the respective properties of the result.

Across the codebase:

- Search for all invocations of `setMeasurementID`. At present these are in the following files and all are suitable candidates for replacing with `updateSettingsForMeasurementID`.
  - `assets/js/modules/analytics/components/common/PropertySelectIncludingGA4.js`
  - `assets/js/modules/analytics/components/settings/GA4SettingsControls.js`
  - `assets/js/modules/analytics-4/datastore/properties.js`
  - `assets/js/modules/analytics-4/datastore/settings.js`
- For each `setMeasurementID` call:
  - Verify it's a scenario where the Google Tag settings should also be updated, and replace it with `updateSettingsForMeasurementID`.
  - Ensure that any resulting error is displayed/handled according to the error handling for that scenario.

## Test Coverage

- Add PHPUnit tests for the PHP additions and changes.
- Add Jest tests for the new data store functions.
- Fix any failing tests.

## QA Brief

* No regression should be spotted while `gteSupport` feature flag is not enabled in the following areas of the pluggin:
    * Analytics module setup with GA4.
        * Creating a new property and selecting existing one.
    * Analytics Settings 
        * Changing Analytics and GA4 properties. 
* With `gteSupport` feature flag enabled:
    * The Google Tag Settings should be populated correctly if the property has Google Tag Settings. 
    * Follow the QAB of #6080, if any issue is discovered, follow up here. 

## Changelog entry

* Determine Google Tag settings when configuring Analytics.

**Comment by tofumatt** [comment]
Looks good to me, I think this approach works 👍🏻 

IB ✅

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@kuasha420 AC have below point -

**Comment by kuasha420** [comment]
@mohitwp Nice catch. I think we've implemented it here but a QA:Eng pass would remove all doubt. So, feel free to add the label and proceed accordingly! Cheers.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev.
- Verified the Analytics setup when `gteSupport` feature flag is disabled.
- Tested the Analytics set up with new and existing property.
- Tested the analytics settings view and functionality. 

- When `gteSupport` feature flag is active
- Verified https://github.com/google/site-kit-wp/issues/6080 as steps mentioned under it's QAB.
- Verified tag placement for GA4 is the Google Tag ID, instead of the GA4 measurement ID when `gteSupport` feature flag is active.
- If the `gteSupport` feature flag is disabled, verified that the Google Tag ID is replaced with the fallback GA4 measurement ID.
- Verified below point in AC.

```
To set the googleTagID setting, the following logic should be used (based on the tagIds field):
If the tagIds list contains any tag starting in "GT-", use that one. (If there are multiple "GT-" tags, use any one, e.g. the first one.)
Otherwise, if there is any tag ID that is the same as the GA4 measurement ID, use that one.
Otherwise, if there is any other tag ID that starts in "G-", use that one.
```

- Tested after changing the analytics a/c and property when `gteSupport` feature flag is active and verified the source code. 
- Tested analytics set up.
- Tested analytics set up through GA4 activation banner when GA4 feature flag is active.
- Tested analytics settings.
- Combine tag and change destination at another site and checked that after disconnecting and connecting from same a/c Google tags changes or not.
- I'm not able to generate any condition where gtag starts with AW.

Assigning QA:eng after discussion with @kuasha420 . AC have some technical points which require confirmation from QA:eng

<details>

When getSupport feature flag is not active and analytics is connected.

![image](https://user-images.githubusercontent.com/94359491/217530138-2fa694e0-5d47-4e4e-888a-318a2405e1e1.png)

When getSupport feature flag is active and analytics is connected.

![image](https://user-images.githubusercontent.com/94359491/217533530-6acd43a2-9fe7-4d7c-92e9-319b9d4801e0.png)

![image](https://user-images.githubusercontent.com/94359491/217534122-e04fac8e-f2ec-4319-a619-ec82cf92b1d2.png)


gtag starting with g

![image](https://user-images.githubusercontent.com/94359491/217534054-7cb52dbf-5407-49c2-87be-18287e5f8535.png)

</details>
