### ISSUE TITLE
Encourage users to enable auto-updates on plugin activation

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6092]
## Feature Description

This would be an extension to #5853 which creates a Notification Banner CTA. This issue can add the same CTA to the plugin Activation Banner on the Plugins page.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For users who have just activated the plugin, the `ActivationApp` notice should be modified as shown in the following points only if the conditions mentioned in the ACs for #5853 are met, viz:
    * The auto-updates [feature is only available for WordPress 5.5](https://wordpress.org/support/article/plugins-themes-auto-updates/#enable-auto-updates-for-plugins) and above. 
    * The user should also have the `update_plugins` core capability.
    * [Auto updates for plugins should be enabled - see `wp_is_auto_update_enabled_for_type()` and so should the new user interface elements - see `Disable the auto-update user interface elements`](https://make.wordpress.org/core/2020/07/15/controlling-plugin-and-theme-auto-updates-ui-in-wordpress-5-5/).
* If the above conditions are met, the `ActivationApp` notice should be modified as follows:
    * Title should remain unchanged.
    * Description: _Turn on auto-updates so you always have the latest version of Site Kit. We constantly introduce new features to help you get the insights you need to be successful on the web._ 
    * Primary CTA: _Enable auto-updates_
    * Secondary Link: _Skip to Dashboard_
* Clicking on the `Primary CTA` should enable auto updates and take the user to the dashboard.
* Clicking on the `Secondary link` should simply take the user to the dashboard.
* If auto updates are already enabled, or were enabled using the `Primary CTA` above, then the Banner notification created in #5853 should not be rendered at any time.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jimmymadon** [comment]
@marrrmarrr I've added some preliminary ACs to this issue, but since it involves user facing text, could you please review it?

In #5853, we have already created a Banner notification on the main dashboard to encourage users to enable auto updates. We had originally thought of only modifying the message that appears on the "Plugins page" when activating the plugin - but this would not be sufficient in encouraging existing users who have already activated the plugin. So we decided to definitely go ahead with #5853 and use this issue to explore an additional place to encourage users. Does this sound good?

**Comment by marrrmarrr** [comment]
@jimmymadon how about adding this to the [success banner](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-setupsuccessbannernotification--site) at the end of the setup flow (when the user is redirected back to the SK dashboard)? That way we'll ensure that Site Kit is actually set up and would benefit from the auto updates. 

We could replace the "Connect more services to see more stats. [Go to Settings](http://example.com/wp-admin/admin.php?page=googlesitekit-settings#/connect-more-services)" with the auto-update call to action. I'd suggest changing the primary CTA to be just "Enable" to make it shorter (skipping the "auto update" part) and the secondary one would be "Maybe later" (since they're already on the dashboard).
