### ISSUE TITLE
Property select content shift and loading issue.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#6158]
## Bug Description
Here are 2 related issues-

1. When user access analytics settings in edit mode then first it display placeholder then it shift and display property name + measurement id.  This happens only one time after the page load. To recreate this reload the page again.
2. On main branch measurement id load after delay of few milliseconds. On latest when we reload the page it loads property name and property id together.
3. 
## Steps to reproduce

**Steps : Issue 1**

1. Disconnect GA4 or use site on which only UA property is connected.
2. Go to settings > Open analytics settings >Click on edit option.
3. Notice property select content shift. 

**Steps : Issue 2**

1. Disconnect GA4 or use site on which only UA property is connected.
2.Go to settings > Click on 'Connect GA4 button> it will open analytics settings in edit mode.
3. Now reload the page.
Notice placeholder it will show property name with property id.
or
Go to settings > Open analytics settings >Click on edit option.
Now reload the page.
Notice placeholder it will show property name with property id.

## Screenshots

Issue 1:

https://user-images.githubusercontent.com/94359491/202108403-27ae8e78-0957-4e3e-adaa-55155dfc698c.mp4

Issue 2:

Main-

https://user-images.githubusercontent.com/94359491/202381072-bb6eee4d-12bf-4524-9f27-4017a6046b67.mp4

Latest -

https://user-images.githubusercontent.com/94359491/202381141-52ae61fd-4796-4946-8320-6d759adcbb54.mp4

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GA4 property select dropdown should display the loading state (`ProgressBar`) until the `getWebDataStreamsBatch` selector resolves the resolution.
  * It shouldn't show the GA4 property select dropdown until the result of mapped `measurementIDs` are available to the component.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by hussain-t** [comment]
Thanks, @aaemnnosttv. I have updated the AC to look like "what" should be the result. LMK WDYT?

**Comment by aaemnnosttv** [comment]
Thanks @hussain-t – looking better! I think we can refine this a little more though. It sounds like the property select should simply remain in the loading state until all of the data needed to display its choices have completed loading, is that correct? Let me know if there's more to it than that, but we shouldn't be overly specific about selectors and technical details about their resolution unless it's really relevant. We can include some details as more of a note or link to a specific comment where more information is available if there is a discussion that would provide good context etc.

We also need to consider other related issues which touch the same part of the code base. Right now we have #6293 which is a much higher priority since it's a bug, where as this issue is more of a user experience enhancement. It's possible that this issue could be solved as part of the other though so we should at least wait until the other is done first before moving forward with this one.

This supports my first comment above, which is that the AC should be independent of the technical details, such that if #6293 fixes the content shift, this issue could simply be closed. With more technical AC, or premature IB, it risks undoing important changes.

**Comment by aaemnnosttv** [comment]
Closing this one as it's already been addressed in https://github.com/google/site-kit-wp/issues/6293
