### ISSUE TITLE
Improve inline error notice and retry UX

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#6162]
Follow up to #5494 and #6055: Both the approach using a Retry button and the approach using a Retry link for inline error notices are not right. They both look confusing in the greater UI they're part of, and we need to revise this in a more holistic way. There are two key concerns here:

* If an error happens while rendering the initial UI (e.g. failed requesting necessary data, such as accounts, properties etc.), the entire UI should be replaced with the error message, since in that case it'll either be a broken UI or the wrong UI anyways. In that case, the Retry button should be shown similar to how it is today. Since then there would not be any other UI, it would be clear to the user that they need to click the single primary CTA, the "Retry" button.
* If the error happens while processing a user action (e.g. failed saving data or creating an entity, such as an account, property etc.), the error message should still be displayed inline similar to today. In that case, it **must not** have any Retry button or link though, and rather just be followed by a text like "Please try again". Since the primary CTA that the user originally clicked would still be present in the UI, clicking that is basically the "Retry" anyway.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Retry" button in Inline error notices (mostly via the `ErrorNotice` component) should be handled differently depending on context:
    * If the `ErrorNotice` is displayed within a UI where there is no primary CTA button present, it can be displayed as it is today (primary button). An example would be when something goes wrong in rendering the overall UI so the error notice replaces that entire UI.
    * If the `ErrorNotice` is displayed within a UI where there is already a primary CTA button present, the Retry button should not be displayed. Instead the main error text should just be followed by a "Please try again." text (no link or button). This is because for those situations the error most likely occurred during logic triggered by the user clicking the existing primary CTA button, so that CTA button is already sufficient as a de-facto retry mechanism.
    * Since the `ErrorNotice` component does not have that context itself, this likely should be controlled by a prop and set accordingly anywhere that an `ErrorNotice` (or the `ErrorNotices` wrapper) is used.

## Implementation Brief

* In `ErrorNotice` https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/assets/js/components/ErrorNotice.js#L72
  * Rename `shouldDisplayRetry` to `canRetryError?
  * Add a new `shouldDisplayRetry` to `ErrorNotice` component, with `true` as default value. 
  * Update the conditional of the retry button to check for `canRetryError` and `shouldDisplayRetry`
* In `StoreErrorNotices` https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/assets/js/components/StoreErrorNotices.js#L76
  * Add the same `shouldDisplayRetry` prop and pass it over to `ErrorNotice`.
* In `SetupErrorNotice` https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/assets/js/modules/tagmanager/components/setup/SetupErrorNotice.js#L30
  * Add the `shouldDisplayRetry` prop to the `StoreErrorNotices` and set it to `false`.
* Locate the same `<StoreErrorNotices>` in the setup components for the other modules, add the `shouldDisplayRetry` prop and set it to `false`.
  

### Test Coverage

* For Adsense, Analytics, Tag Manager: add a new story that shows an Error during setup, add the story to VRT scenarios.

## QA Brief

* Run Adsense, Analytics, and Tag Manager setup process 
* Make error appear (eg try to setup from an account with no access to property)
* Retry button should not appear 

## Changelog entry

* Update error notices not to display the retry button if the error doesn't support retries.

**Comment by bethanylang** [comment]
@felixarntz Is this one that you need to work on, or can it be unassigned for someone else to take a look? Thanks!

**Comment by felixarntz** [comment]
@bethanylang Thanks for the ping! Added ACs.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
QA Update: ⚠️ 

@sashadoes the last time we tested the ticket [related](https://github.com/google/site-kit-wp/issues/5494) to this, we had to use the Tweak extension to trigger a warning message so we could test it.  I have spent some time on this and I am unable to trigger the same message to see if the retry button no longer appears. In the QAB, you. mentioned about not giving permission to a property, but I do not think that this applies to this error message.  

Please could you offer some direction on how I can trigger these error messages so I can test this ticket? 

![image](https://user-images.githubusercontent.com/73545194/223363990-73f2369c-6fdc-4f5a-aee8-da8da8cfe42d.png)

**Comment by sashadoes** [comment]
Hi @danielgent. Good question. 
I triggered the error programmatically most of the time. 
Maybe create a Tag Manager account and try to mock on some other step eg. when setup requests Optimize Container ID or similar.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@felixarntz @sashadoes when we tested #5494 before we used an extension to create an error message when setting up Tag Manager.  The retry button appeared there and at the time we said that this ticket would improve that user experience. I have recreated that same scenario to test this ticket because of the AC here:

> If the error happens while processing a user action (e.g. failed saving data or creating an entity, such as an account, property etc.), the error message should still be displayed inline similar to today. In that case, it **must not** have any Retry button or link though, and rather just be followed by a text like "Please try again". Since the primary CTA that the user originally clicked would still be present in the UI, clicking that is basically the "Retry" anyway.

As you can see from the screenshot there is an error message but the retry button is still here. 

![image](https://user-images.githubusercontent.com/73545194/223724326-47ed9c9f-0ad6-4281-b068-df729a2c56ad.png)

I have checked the other error messages that have no CTA and are part of the UI and these are find but for this scenario, I feel I cannot pass this ticket.  What are your thoughts?

**Comment by aaemnnosttv** [comment]
@sashadoes looking at #6679 , there are a few things that still need to be done.

- No changes were made for AdSense (was this intentional?)
- The example Darren gave above uses a different instance than the normal setup form because it's a special no-account case. See https://github.com/google/site-kit-wp/blob/51a68467963d41021720a4b8ce28e8b53ec1db57/assets/js/modules/tagmanager/components/common/AccountCreate.js#L71-L74
- Audit the other instances by searching for `<StoreErrorNotices` and `<ErrorNotice`

**Comment by techanvil** [comment]
This issue is being brought back into definition as it looks like the IB may be incomplete, and we may also want to reconsider an aspect of the AC.

With regard to the IB, it currently only specifies to remove the Retry button for errors in the module setup views. However, there is a question about whether we should also remove the Retry button for the settings views as well, considering these also have a primary CTA.

Additionally, it might be worth reconsidering the AC in regard to the specification to always remove the Retry button if a primary CTA is shown, at the expense of potential retryable errors that occur while showing the page. I would suggest that we could potentially search for a technical solution that retains the retryability of these errors, say by specifying that the Retry button should _only_ be suppressed if the error occurs in response to the CTA press.

**Comment by aaemnnosttv** [comment]
Thanks @techanvil – the changes here have been reverted, let's redo this in a new issue 👍  We can keep most of the initial AC here as a starting point and work on refining that to inform a more comprehensive IB.
