### ISSUE TITLE
Conditionally render GA4 metrics on SK dashboards

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6220]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the `ga4Reporting` feature flag is enabled, the widgets on the SK dashboard should display their GA4 variants (created in previous issues) instead of UA components

## Implementation Brief
* Using `assets/js/modules/analytics/index.js`,
    * Check if the `ga4Reporting` feature flag is enabled via the `isFeatureEnabled` function.
    * If the above is true, render
        * `DashboardAllTrafficWidgetGA4` instead of `DashboardAllTrafficWidget`.
        * `DashboardOverallPageMetricsWidgetGA4` instead of `DashboardOverallPageMetricsWidget`.
        * `ModulePopularPagesWidgetGA4` instead of `ModulePopularPagesWidget`.
* Using `assets/js/modules/search-console/index.js`,
    * Render `SearchFunnelWidgetGA` instead of `SearchFunnelWidget` if `ga4Reporting` feature flag is enabled.

### Test Coverage
* No new tests to be added.

## QA Brief

* Configure Analytics with GA4 and enable ga4reporting.
* Check the SK Dashboard Widget. It should have the  DashboardAllTrafficWidgetGA4, DashboardOverallPageMetricsWidgetGA4, ModulePopularPagesWidgetGA4, and SearchFunnelWidgetGA4 instead of the non-ga4 versions. 

## Changelog entry

* Update Analytics and Search Console widgets to use GA4 versions if the feature flag is enabled for the site.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- With `ga4Reporting` feature flag enabled
  - The `DashboardAllTrafficWidgetGA4`, `DashboardOverallPageMetricsWidgetGA4`, `ModulePopularPagesWidgetGA4`, and `SearchFunnelWidgetGA4` appear on the main/entity dashboard instead of the non-ga4 versions.

For additional testing, I tested the view only dashboard to ensure that the same GA4 metrics were appearing with the feature flag enabled. 

- With `ga4Reporting` feature flag disabled
  - The main/entity dashboard displays the non-ga4 versions.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/223688693-50282121-25a8-421c-9aef-14b7a11d22c6.png)
![image](https://user-images.githubusercontent.com/73545194/223688708-c388e4b2-5889-4816-aeda-dad000a86422.png)
![image](https://user-images.githubusercontent.com/73545194/223688736-f29fb7cf-8b9d-4b77-988d-d31fffbcacf7.png)
![image](https://user-images.githubusercontent.com/73545194/223688771-c536f48e-eb78-4682-a966-878813d23e2e.png)

</details>
