### ISSUE TITLE
Conditionally render GA4 metrics in SK admin bar integration

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6221]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the `ga4Reporting` feature flag is enabled, the module components in the SK admin bar app should display their GA4 variants (created in previous issues) instead of UA components

## Implementation Brief
* Using `assets/js/components/adminbar/AdminBarWidgets.js`,
    * Check if the `ga4Reporting` feature flag is enabled via the `useFeature` hook.
    * If the above is true, render
        * `AdminBarSessionsGA4` instead of `AdminBarSessions`.
        * `AdminBarUniqueVisitorsGA4` instead of `AdminBarUniqueVisitors`.
* Update `assets/js/components/adminbar/AdminBarWidgets.stories.js` to include stories where the above GA4 components are rendered.

### Test Coverage
* No new tests to be added.

## QA Brief

* Configure Analytics with GA4 and enable the `ga4reporting` feature flag.
* Ensure the AdminBar widget should have the `Total Users` and `Total Users` data from GA4.
* Check the newly added stories that render the GA4 widget:
   * [Views > AdminBarApp > AdminBarWidgets > Active: With GA4 Enabled](http://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-adminbarapp-adminbarwidgets--analytics-active-with-ga-4-enabled)
   * [Views > AdminBarApp > AdminBarWidgets > GA4 Widgets Loading](http://google.github.io/site-kit-wp/storybook/develop/?path=/story/views-adminbarapp-adminbarwidgets--analytics-4-widgets-loading)

## Changelog entry

* Conditionally render GA4 metrics in the Site Kit Admin Bar integration.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: 

**Verified:**

When the `ga4Reporting` feature flag is enabled, the module components in the SK admin bar app display their GA4 variants instead of UA components.

  - `AdminBarSessionsGA4` instead of `AdminBarSessions`.
  - `AdminBarUniqueVisitorsGA4` instead of `AdminBarUniqueVisitors`.

![image](https://user-images.githubusercontent.com/73545194/225183289-1c780234-9dae-4bb9-b59e-1197a7b214fa.png)

**Note:** the QAB, references :

`Ensure the AdminBar widget should have the Total Users and Total Users data from GA4.`

@sashadoes I have ignored this since it is incorrect and doesn't reference checking the components. Please ensure that the QAB is more detailed as a less experienced QA might just check the titles on the admin bar UI and not use the React Developer extension to check the components, which is what we should be doing here.

**Comment by aaemnnosttv** [comment]
> **Note:** the QAB, references :
> 
> `Ensure the AdminBar widget should have the Total Users and Total Users data from GA4.`

@wpdarren this is still valid as something to check – that the data presented matches what is in GA4. Checking that the GA4 versions of the components is mostly what this issue is about but we also want to see that it's showing data from GA4 (as it could be that they're using the old UA implementation under the hood). I can see that this is correct, but just wanted to clarify what was being asked here.
