### ISSUE TITLE
Conditionally render GA4 metrics in SK WP dashboard widget

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6222]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the `ga4Reporting` feature flag is enabled, the GA metrics in the SK WordPress dashboard widget (Site Kit Summary) should display their GA4 variants (created in previous issues) instead of UA components

## Implementation Brief
* Using `assets/js/components/wp-dashboard/WPDashboardWidgets.js`,
    * Check if the `ga4Reporting` feature flag is enabled via the `useFeature` hook.
    * If the above is true, render
        * `WPDashboardSessionDurationGA4` instead of `WPDashboardSessionDuration`.
        * `WPDashboardUniqueVisitorsGA4` instead of `WPDashboardUniqueVisitors`.
* Update `assets/js/components/wp-dashboard/WPDashboardWidgets.stories.js` to include stories where the above GA4 components are rendered.

### Test Coverage
* No new tests to be added.

## QA Brief

* Configure Analytics with GA4 and enable `ga4reporting`.
* Check the WP Dashboard Widget. It should have the SessionDuration and UniqueVisitors data from GA4. 

## Changelog entry

* Update the WordPress dashboard widget to use Analytics 4 widgets if they are allowed by the feature flag.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- When `ga4reporting` is enabled. The WP Dashboard Widget has `WPDashboardSessionDurationGA4` instead of `WPDashboardSessionDuration` and `WPDashboardUniqueVisitorsGA4` instead of `WPDashboardUniqueVisitors`.
- When `ga4reporting` is disabled. The WP Dashboard Widget has the non GA4 `WPDashboardSessionDuration` and `WPDashboardUniqueVisitors` variants.
- While it doesn't mention it in the QAB, I also checked the Stories to ensure the same behaviour. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/223124557-a6b9e3d5-1384-4e61-84db-afb4f2d9e57a.png)
![image](https://user-images.githubusercontent.com/73545194/223124601-a702e968-9d50-4cfd-a76a-5cc51c8a1fb2.png)

</details>
