### ISSUE TITLE
Allow editing of Key metrics

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6259]
## Feature Description

All authenticated admins and view only users have the ability to edit their own selection of key metric widgets.

Refer to the [relevant section](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.xjeypmmi533q) in the design doc for further context.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the Key Metrics widget is active for any user (authenticated admin or view-only user), a "Change metrics" link should be created as show in the [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=1375%3A60832&t=bwOtTQ7S3Odzwt7u-0).
* Clicking on the "Change metrics" link should slide out the Metrics Selection Panel created in #6258. In this case (i.e. when editing already selected metrics), the Save CTA button should be modified to "Apply changes" as per the [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=1347%3A35242&t=bwOtTQ7S3Odzwt7u-0).
* The behaviour of the list of widgets should be as per the ["Metrics Selection Panel" flow in Figma.](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=1623%3A58431&t=bwOtTQ7S3Odzwt7u-0)
    * All metrics that were selected when the panel was opened should appear at the top of the list. Once the list is rendered (on panel open/slide-out), it should not be re-ordered unless the panel is closed and opened again. See this comment: https://github.com/google/site-kit-wp/issues/6259#issuecomment-1350056334
    * Deselecting metrics below the minimum 2 should show an error notice and disable the "Apply changes" button.
* Clicking on "Apply changes" should save / update the user selected metrics in the database using the action from #6314.
* If dashboard sharing is enabled, view-only users should be able to change their own metrics. However, the list of available metrics to select should include only those metrics which the user has shared access to.

## Implementation Brief

- Create `assets/js/components/KeyMetrics/ChangeMetricsLink.js`. In this file:
    - Create a new component named `ChangeMetricsLink`.
	- This component should check if any key metrics are available. This can be done by using the `getKeyMetrics()` selector from the `core/user` store (being implemented in #6314).
	- If key metrics aren't available, this component should return `null`.
	- Otherwise, it should render a `Change metrics` link according to the design in Figma.
	- This link should slide out the Metrics Selection Panel (being implemented in #6258) on click.
- We need to extend the Site Kit dashboard widget API in order to display a CTA beside the "widget area" title, in this case, the "Change metrics" link. Here is [a link to the Figma design mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=1375%3A60832&t=Oef9dzcQeN1aEUP6-0) where this CTA/link can be seen. Here is a screenshot showing the CTA/link in question:
![image](https://user-images.githubusercontent.com/20284937/212864653-27706157-8693-4a6e-83ad-e8fa089c576e.png)

	- In `assets/js/googlesitekit/widgets/datastore/areas.js`:
		- Update the `registerWidgetArea` action so that its `settings` object parameter accepts a new optional property named `CTA`, which would ideally be a React component to render such a CTA.
	- In `assets/js/googlesitekit/widgets/register-defaults.js`:
	    - Locate the widget area registration for `AREA_MAIN_DASHBOARD_KEY_METRICS_PRIMARY` (being implemented in #6209).
		- In its `settings` object parameter, add a new property named `CTA` with a value of the new `ChangeMetricsLink` component created above.
- Update the Metrics Selection Panel (being implemented in #6258):
    - Upon opening the Metrics Selection Panel, re-order the list of metrics based on the selected metrics so that the selected metrics are shown first in the list.
	    - Selected metrics can be obtained by using the `getKeyMetrics()` selector from the `core/user` store (being implemented in #6314).
	- Update the Metric Selection Panel footer:
	    - Update the copy of the CTA button from `Save Selection` to `Apply changes` when there are selected metrics available, which can be checked by using the `getKeyMetrics()` selector from the `core/user` store (being implemented in #6314).
	    - When the number of selected metrics in the client side is less than 2:
		    - Disable the CTA button.
	    	- Display an error above the CTA using the `<ErrorNotice />` component that says `Select at least 2 metrics` according to the Figma designs, when the number of selected metrics 

### Test Coverage

- In `assets/js/googlesitekit/widgets/datastore/areas.test.js`:
    - Update test cases to reflect changes to the `registerWidgetArea` action.

## QA Brief

- Set up Site Kit and enable the `userInput` feature flag.
- Verify that a `Change Metrics` link doesn't appear in the KM widget area.
- Click on `I'll pick metrics myself` in the Key Metrics setup CTA notification.
  - Once the metrics selection panel has opened, verify that the footer CTA button says `Save Selection` according to the Figma design.
  - Do not make any changes and close the panel.
- Click on `Get tailored metrics` in the Key Metrics setup CTA notification.
  - Complete the user input questionnaire.
- Once you're back to the SK dashboard, verify that a `Change Metrics` link appears in the KM widget area according to the Figma designs.
  - Verify that clicking on the link opens the metrics selection panel.
  - Verify that the footer CTA button now says `Apply changes`.
  - Verify that the selected metrics show up on the top of the list.
  - Change the selection and save your changes, which should close the panel.
  - Re-open the panel, and verify that the new selection appears at the top of the list.
- Use Dashboard Sharing to share access to Analytics but not Search Console, as a secondary user with the administrator role.
  - Log in as a view-only user.
  - Complete the user input questionnaire for the `Change Metrics` link to appear (if it isn't visible already). Use it to open the selection panel.
  - In the selection panel, verify that only metrics dependent on Search Console are visible, but not Analytics, since the user doesn't have shared access to Analytics.

## Changelog entry

* Update key metrics area to support editing selected metrics.

**Comment by tofumatt** [comment]
> All selected metrics should be ordered at the top of the list.

I think the aim of this is that "All metrics that were selected when the panel was opened should appear at the top of the list, but the order should remain the same afterward". In fact, that's what the Figma mocks show:

<img width="689" alt="CleanShot 2022-12-13 at 23 33 39" src="https://user-images.githubusercontent.com/90871/207468101-ca5dd0af-345c-4858-ad88-4d9588cd152b.png">
<img width="697" alt="CleanShot 2022-12-13 at 23 33 33" src="https://user-images.githubusercontent.com/90871/207468108-0c17500d-1fe9-4e5a-8402-bf24dbb0bd25.png">

But the wording might imply the order should jump around on selection, which would be jarring.

Not a big deal, I've tweaked the ACs as they otherwise look good 👍🏻 

Moving to IB.

**Comment by tofumatt** [comment]
> - We need to extend the Site Kit dashboard widget API in order to display a CTA beside the "widget area" title, in this case, the "Change metrics" link.
> 	- In `assets/js/googlesitekit/widgets/datastore/areas.js`:
> 		- Update the `registerWidgetArea` action so that its `settings` object parameter accepts a new optional property named `CTA`, which would ideally be a React component to render such a CTA.
> 	- In `assets/js/googlesitekit/widgets/register-defaults.js`:
> 	    - Locate the widget area registration for `AREA_MAIN_DASHBOARD_KEY_METRICS_PRIMARY` (being implemented in #6209).
> 		- In its `settings` object parameter, add a new property named `CTA` with a value of the new `ChangeMetricsLink` component created above.

There's a lot of links between the design doc and the Figma mock, and I think some of the links aren't up-to-date and so it's hard to find the actual UI this refers to. Can you include a screenshot or a direct link to a Figma mock so it's easier to see exactly what this refers to?

I wonder if "CTA" is the right term for this component, but since I can't think of a better one I guess it's fine 😄 

I think otherwise this is good, but it would help to have a visual reference for what's being implemented here before moving it to the backlog. Even if the screenshot winds up out-of-date from the Figma mock, it's nice to have as a reference. Or an up-to-date Figma link works too 🙂

**Comment by nfmohit** [comment]
> Can you include a screenshot or a direct link to a Figma mock so it's easier to see exactly what this refers to?

Added, thank you @tofumatt!

Back to you for another go. Thanks!

**Comment by tofumatt** [comment]
Thanks! Looks great 🙂 

IB ✅

**Comment by eugene-manuilov** [comment]
@aaemnnosttv, I approved #7379, assigning this task to you to approve it from your end as well since you also provided feedback.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@nfmohit a few observations that I would love your opinions on. 

1. When you click the `Change Metrics` link, the styling looks close to the GA4 dashboard view label. I think we are getting rid of these when UA is removed, but thought I would raise it. 

![image](https://github.com/google/site-kit-wp/assets/73545194/286d0fad-2ed8-4f34-ab89-8aefa851a90c)

2. On Figma designs for metrics selection panel, the list of metrics appear in the order they do on the KMW widget, so Loyal visitors is first, etc.  As you can see from my screenshot, they appear the other way around. 

![image](https://github.com/google/site-kit-wp/assets/73545194/22b778e2-e2d0-4559-9027-206397f7bd20)

3. I am in the metrics selection panel and I uncheck and select a new metric.  I click on apply changes and the panel disappears and the new metric appears in the KMW widget. What I noticed though is that the `Change Metrics` link is still highlighted like it does when you click on the link. 

![image](https://github.com/google/site-kit-wp/assets/73545194/0da3d588-0383-4658-a63e-5390acb672f8)

4. I am logging in as a `second admin` but I go into view only dashboard.  The `Change Metrics` link appears above the CTA to answer user survey, which I wasn't expecting. When I login as a non admin, i.e. an Editor, on view only dashboard then link does not appear.  Is this expected in both scenarios? 

![image](https://github.com/google/site-kit-wp/assets/73545194/01da9d53-05f4-4e59-a417-fac866c72602)

5. As an non admin role, ie. Editor, I see the CTA to answer the questions, when I click on it though a message appears `Sorry, you are not allowed to access this page.` I know we have a few tickets outstanding related to dashboard sharing, i.e. #7386 so I am wondering if the QAB is correct here?

**Comment by nfmohit** [comment]
Hi @wpdarren.
Thank you for sharing your observations.

> 1. When you click the `Change Metrics` link, the styling looks close to the GA4 dashboard view label. I think we are getting rid of these when UA is removed, but thought I would raise it.

That is correct. The dashboard view indicator will be removed by the time KMW is out.

> 2\. On Figma designs for metrics selection panel, the list of metrics appear in the order they do on the KMW widget, so Loyal visitors is first, etc.  As you can see from my screenshot, they appear the other way around.

I have added a **follow-up PR** #7412 that improves this ordering as you pointed out.

> 3\. I am in the metrics selection panel and I uncheck and select a new metric.  I click on apply changes and the panel disappears and the new metric appears in the KMW widget. What I noticed though is that the `Change Metrics` link is still highlighted like it does when you click on the link.

This is expected. When you close a modal/side sheet for example, the focus will be back to the button/action that opened it. This is similar to how the dashboard sharing settings modal works, by moving the focus back to the button that opens it on close.

> 4\. I am logging in as a `second admin` but I go into view only dashboard.  The `Change Metrics` link appears above the CTA to answer user survey, which I wasn't expecting. When I login as a non admin, i.e. an Editor, on view only dashboard then link does not appear.  Is this expected in both scenarios?

That is odd. The `Change Metrics` link is only supposed to appear when the user has metrics appearing on their dashboard. Are you able to replicate this on multiple sites?

> 5\. As an non admin role, ie. Editor, I see the CTA to answer the questions, when I click on it though a message appears `Sorry, you are not allowed to access this page.` I know we have a few tickets outstanding related to dashboard sharing, i.e. [Hide Key Metrics Setup CTA banner when widget is setup by another Admin or on View Only Dashboard #7386](https://github.com/google/site-kit-wp/issues/7386) so I am wondering if the QAB is correct here?

I have updated the QAB to only test this with an admin user. @jimmymadon shall be able to confirm but I don't think we will be showing the KM CTA to non-admin users.

Thanks!

**Comment by wpdarren** [comment]
### QA Update:  ✅ 

**Verified:**

- A Change Metrics link doesn't appear in the KM widget area when Site Kit / Analytics set up. 
- Once the metrics selection panel has opened the footer CTA button says Save Selection according to the Figma design.
- Completed the user input questionnaire and when back at SK dashboard, a Change Metrics link appears in the KM widget 
  - Clicking on the link opens the metrics selection panel.
  - The footer CTA button now says Apply changes.
- When you change the selection and save your changes, the panel is closed.
- When you re-open the panel, and the new selection appears at the top of the list.
- The issue reported regarding the order of the metrics in the panel is fixed. 
- Dashboard Sharing user has access to Analytics but not Search Console,  metrics dependent on Search Console are visible, but not Analytics, since the user doesn't have shared access to Analytics.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/17da15de-2ff9-44ee-bf2c-8cb46638c421)
![image](https://github.com/google/site-kit-wp/assets/73545194/ca2733e7-b882-48a0-a049-697dd11e210f)
![image](https://github.com/google/site-kit-wp/assets/73545194/9fe8c227-e4e9-451d-9f90-859eb2790c3f)
![image](https://github.com/google/site-kit-wp/assets/73545194/68084793-b220-464c-9d82-539d143f26c6)
![image](https://github.com/google/site-kit-wp/assets/73545194/bc4e157e-5678-4c06-83ff-9783004fd4f5)
![image](https://github.com/google/site-kit-wp/assets/73545194/3cf34466-0c24-4600-b7e2-306601037f94)
![image](https://github.com/google/site-kit-wp/assets/73545194/e7abd6a4-961d-4311-ae58-c974da043c50)
![image](https://github.com/google/site-kit-wp/assets/73545194/ebb58e6d-0dcb-49c7-b4db-94dba18a85ab)
![image](https://github.com/google/site-kit-wp/assets/73545194/07761c7a-7533-454d-9c9c-0ca058869b9f)

</details>

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@nfmohit I have just found an issue while writing up bug bashing instructions. When Analytics is disconnected, the `Change metrics` link appears.  

![image](https://github.com/google/site-kit-wp/assets/73545194/3dbff6a8-eabb-4488-a239-4f30f80b039d)

**Comment by nfmohit** [comment]
Thank you for sharing your observation, @wpdarren.

@jimmymadon, based on #7425, it looks like we'll be allowing users to change their metric selection even if modules aren't connected. In that case, should we be removing the `Change Metrics` link if Analytics is disconnected?

If so, are there any other conditions based on which this link should be removed?

Thanks!

**Comment by nfmohit** [comment]
Sounds fair! Back to you @wpdarren !

**Comment by aaemnnosttv** [comment]
We can address the issue of the change link in this scenario in a separate issue as that was not part of the AC here. 👍
