### ISSUE TITLE
Unable to dismiss competing modals

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6266]
## Bug Description

When a feature tour is triggered at the same time as the insufficient permissions modal, neither one is able to be dismissed using the mouse. The only thing which seems to work is the escape key which then dismisses the feature tour, after which the permissions modal is able to be interacted with as usual.

## Steps to reproduce

1. Setup SK
2. With a different admin, connect AdSense
3. With the first admin visit the dashboard while triggering a feature tour

## Screenshots

https://user-images.githubusercontent.com/1621608/205211960-ba069bb3-b394-4042-88af-aaed1da04632.mp4

In this scenario, the permissions modal was triggered by the `GET:notifications` request for AdSense which happens on the dashboard when connected but this issue is not AdSense-specific.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* It should be possible to dismiss the feature tour OR the permissions modal when one appears on-screen.
  * It would probably be best to hide a feature tour anytime a permissions modal appears on-screen, as the permissions modal is "more important"/"urgent" and having both compete for attention is counter-productive.
  * So ideally, when the permissions modal appears, any active feature tour should be closed (but should be able to appear later, so not permanently dismissed). Focus should be moved to the permissions modal dialog.
  * If that isn't possible, make it so either modal can be interacted with/dismissed.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by zutigrm** [comment]
@aaemnnosttv I can't seem to reproduce this. The repro steps from description seem outdated - since we have shared dashboard, 1 admin can't connect AdSense for another admin today, just shared view. But I tried by invoking the modals through console, tried several scenarios, and it works every time. One other difference from the attached video at that time, is also that permission modal prevents scroll now. 

Here are the videos of the tests:

https://github.com/google/site-kit-wp/assets/10414808/1b61eb03-10c0-4514-9f28-c4294951e38f


https://github.com/google/site-kit-wp/assets/10414808/622201d8-86c2-462f-90ce-78620482e884


https://github.com/google/site-kit-wp/assets/10414808/b8b6033b-cecb-4bf3-b0dd-1a492efdc3b6

**Comment by aaemnnosttv** [comment]
I'm not sure the issue of competing modals is entirely solved, but it seems like the precondition for this happening was addressed in https://github.com/google/site-kit-wp/issues/5497. We can address this in a new issue if/when it comes up again.
