### ISSUE TITLE
External link icon repeats on WP dashboard when used within error CTA

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6279]
## Bug Description

In #5975 we made a change to the link styles within errors. As a result it's made an unintentional change to external links within an error CTA. This appears to only affect external links used outside of the main SK screens.

## Steps to reproduce

1. Connect Analytics
2. Sign into SK as an admin without access to the connected GA property
3. See style flaw in external icon

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/205724404-63c190b2-d53b-4470-a0ea-f8f0d2c65acb.png)

## Additional Context

Introduced in 1.88.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The external link icon should only appear once per icon (as a background image, it should never repeat)

## Implementation Brief

- In `assets/sass/wpdashboard.scss`:
    - Import the `components/global/googlesitekit-cta-link` SCSS file so that styles for the CTA link are included in the WP Dashboard as well.

### Test Coverage

- No tests need to be added/updated.

## QA Brief

- Follow the steps to reproduce and replicate the insufficient permissions error.
- Go to the WordPress Dashboard.
- Verify that the external links' visual issue reported in the issue is fixed.

## Changelog entry

* Fix appearance of links within an error notice on the WP dashboard.

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The external links' visual issue reported in the issue is fixed.
- Also checked to make sure that the Site Kit Dashboard links still display as expected.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/205738844-a97031b8-a9a5-4eaf-82cf-edaa695cd548.png)
![image](https://user-images.githubusercontent.com/73545194/205738858-ab346cdd-e5d4-4ebf-ab2e-f92e375223a5.png)

</details>

**Comment by aaemnnosttv** [comment]
This issue was unnecessary as a new issue as this was a follow-up to https://github.com/google/site-kit-wp/issues/5975
