### ISSUE TITLE
Enforce timeouts in Jest setup and teardown functions

### ISSUE THREAD

**Issue by derweili** [google/site-kit-wp#6294]
## Feature Description

Follow up on #5460
In e2e tests, the jest `beforeEach()` and `beforeAll()` hooks are used to setup modules for the tests. The hooks are async functions that include 30 seconds timeout. If the timeout is reached, the further execution of the hooks is stopped and the tests will be executed. No info about the timeout is logged and  on error is thrown.
No being aware of exceeded timeouts caused #5460 and could cause more errors in the future.

Following changes should be made:

- Throw an error when a timeout is reached in one of the jest hooks
- Implement exceptions for tests that need more time.

More about this can be found in the #5460 discussion 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- If possible, the E2E lifecycle hooks `beforeAll()` / `afterAll()` and `beforeEach()` / `afterEach()` should cause the tests to fail if the timeout is reached.
- However this might not be viable to achieve. Note that there is an existing Jest issue that suggests it might be problematic: https://github.com/facebook/jest/issues/8442
- If we _are_ able to achieve this, and it causes any existing tests to fail, these should be fixed, either by modifying the test itself or by increasing the timeout for the test.
- The above should be investigated, and if possible, implemented.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by derweili** [comment]
@techanvil I just though about if something similar could happen with the `afterEach()` and `afterAll()` hook, too. We may should double check this.

**Comment by aaemnnosttv** [comment]
@techanvil I agree it could be good to consider after hooks as well.

Also, do we know if this is possible?

**Comment by aaemnnosttv** [comment]
Thanks @techanvil – I've created a separate task for some investigation here, currently assigned to you, after which we'll have a better idea as to what (if anything) we can do here.

**Comment by techanvil** [comment]
Hmm, I am not sure if something has changed recently, or if I am missing something, but this appears to be a bit of a non-issue in my testing.

I've tried a number of simple tests while investigating, but to describe in terms of an existing test's setup, relating to the preceding issue #5460, I took `tests/e2e/specs/modules/analytics/amp-validation.test.js` and modified it to contain just one simple test case and a bit of logging:

<details>
<summary>Modified `amp-validation.test.js`, with passing test output.</summary>

```js
/**
 * WordPress dependencies
 */
import { deactivatePlugin } from "@wordpress/e2e-test-utils";

/**
 * Internal dependencies
 */
import {
  activateAMPWithMode,
  setupAnalytics,
  setupSiteKit,
  resetSiteKit,
} from "../../../utils";

const log = (msg) => process.stdout.write(msg + "\n");

describe("AMP homepage validates with Analytics enabled", () => {
  beforeEach(async () => {
    log("START BEFORE EACH");

    await setupSiteKit();
    await activateAMPWithMode("primary");
    await setupAnalytics();

    log("END BEFORE EACH");
  });
  afterEach(async () => {
    await deactivatePlugin("amp");
    await resetSiteKit();
  });
  it("expects 1 + 1 to be 2", () => {
    log("START TEST");

    expect(1 + 1).toBe(2);

    log("END TEST");
  });
});
```

![image](https://user-images.githubusercontent.com/18395600/214579449-3bbe34b4-273a-4e57-8eea-abc4047532d4.png)

</details>

Noting the time to run the test was just over 30 seconds, I then added a timeout that would ensure the `beforeEach` would breach the 100s timeout config that we set in [`bootstrap.js`](https://github.com/google/site-kit-wp/blob/4104893789c1130de061d9cef69cd5eaacae796b/tests/e2e/config/bootstrap.js#L75-L76). Running the test, it does fail due to the timeout.

<details>
<summary>Modified `beforeEach` with timeout, with failing test output.</summary>

```js
beforeEach(async () => {
  log("START BEFORE EACH");

  await setupSiteKit();
  await activateAMPWithMode("primary");
  await setupAnalytics();

  await new Promise((resolve) => {
    setTimeout(resolve, 70000);
  });

  log("END BEFORE EACH");
});
```

![image](https://user-images.githubusercontent.com/18395600/214578831-ad9f2b10-cfcd-4d1f-8d11-c9fa71f4f49c.png)

</details>

I wanted to check if the issue as reported could relate instead to a rejected Promise, so modified the `beforeEach` to instead reject the Promise. Running the test showed it to fail, displaying the rejected value.

<details>
<summary>Modified `beforeEach` with rejected Promise, with failing test output.</summary>

```js
beforeEach(async () => {
  log("START BEFORE EACH");

  await setupSiteKit();
  await activateAMPWithMode("primary");
  await setupAnalytics();

  await new Promise((resolve, reject) => {
    setTimeout(() => reject("ARRGH"), 1000);
  });

  log("END BEFORE EACH");
});
```

![image](https://user-images.githubusercontent.com/18395600/214581441-2edfb163-4e67-419c-a4d5-6fee38831c05.png)

</details>

Note that I tried this with `beforeAll` with the same result. Additionally, testing with the original test cases also had the same outcome.

Further, note that the logging in the test case itself, i.e. `START/END TEST`, is still output, which indicates the tests are still apparently being run, as per the related [Jest issue](https://github.com/facebook/jest/issues/8442). However the tests do fail, which is the main thing.

**Comment by aaemnnosttv** [comment]
Thanks @techanvil – seems like this is a non-issue then, thanks for your thorough investigation!
