### ISSUE TITLE
Restore Unique Visitors chart on WP Dashboard widget

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6355]
## Feature Description

In #6350 we removed the `Unique visitors over the last 28 days` due to the error many users reported  of a broken WP dashboard widget. In #6346, we improved error handling for our Google charts so that an error raised would not crash the entire app. With this in place, we should be well-positioned to re-introduce the chart on the WP dashboard. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Unique visitors over the last 28 days` chart on the WP Dashboard widget (removed in #6350) should be restored

## Implementation Brief

* Revert the changes made in https://github.com/google/site-kit-wp/pull/6354

### Test Coverage

* No new tests required.

## QA Brief

* Ensure that #6346 is merged before testing this issue.
* Verify the `Unique visitors over the last 28 days` chart on the WP Dashboard widget is displayed correctly. 
* Follow the "Steps to reproduce" and verify that the WP dashboard still loads with other SiteKit widgets and the Unique Visitors widget simply throws a Google Chart widget error that looks like the mock in #6346.

## Changelog entry

* Restore Unique Visitors chart on WP Dashboard widget.

**Comment by bethanylang** [comment]
@aaemnnosttv Is this blocked by #6346?

**Comment by aaemnnosttv** [comment]
@bethanylang yes, I've added that dependency now 👍 Thanks!

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ❌ 

@jimmymadon 

I Found one minor issue.
Issue > If we don't force gathering data state and site is in auto gathering state then on WP Dashboard widget showing text "Table has no columns".

Steps -

- Create new site.
- Set up site kit.
- Set up new analytics a/c.
- Site is in gathering state.
- Visit WP dashboard.

![image](https://user-images.githubusercontent.com/94359491/212021019-14c8631e-c860-48f8-a7d6-bc9c103f7c2b.png)

When site is in forced gathering state through tester plugin.

![image](https://user-images.githubusercontent.com/94359491/212021507-4ce11ce5-efef-4423-b9ca-a396aa4155f1.png)

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Verified on dev.
- Issue reported [here](https://github.com/google/site-kit-wp/issues/6355#issuecomment-1379996967) is now resolved.
- Verified title of the widget changed to  "Unique visitors over the last 28 days".
- Verified for zero data states - zero and gathering.
- Verified the data matching the data that is shown in the "All Traffic" Site Kit dashboard widget by default.
- Verified the chart have only have x-axis labels.
- Verified error handling in case of error in widget. Now whole widget area is not getting hide due to error.
   https://github.com/google/site-kit-wp/issues/6346.

<details>

![image](https://user-images.githubusercontent.com/94359491/212251270-2a842e64-c0ef-4ec9-b973-3d1c407f2f0a.png)

![image](https://user-images.githubusercontent.com/94359491/212252383-3f063483-a4e5-46a5-b5d4-da3f3e90056a.png)

![image](https://user-images.githubusercontent.com/94359491/212256641-8643aeb5-4d21-4dea-8119-5e98dc8d62dd.png)

![image](https://user-images.githubusercontent.com/94359491/212257129-e7d68e1c-8fd4-47e0-9220-27465e33255e.png)

![image](https://user-images.githubusercontent.com/94359491/212267244-2bb822a7-4704-41cc-a9d0-109b8ed72496.png)

</details>
