### ISSUE TITLE
On Entity Dashboard the Bounce Rate appears twice in different widgets

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6363]
## Bug Description

On the entity dashboard we have bounce rate data appearing twice. 

The first time is on the `Search traffic` widget and further down the page it appears again on the `Overall page metrics`

See screencast below.

https://user-images.githubusercontent.com/73545194/210379210-0ec7883f-3cb3-43c0-8ca0-2dfd57d8544c.mp4

This appears to have been the case for quite some time so isn't a new regression.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
Thanks for reporting this @wpdarren. This is most likely an oversight when we introduced the widget in #4122. Essentially, Bounce Rate is used in the Search Funnel widget on the entity dashboard because Goals do not exist per-page and the overall page metrics widget mirrors the columns in the Top Content widget on the main dashboard. With GA4 however, Goals are being replaced by Conversions which can be queried as a metric like any other. For this reason, this should no longer be an issue in GA4 and since this isn't breaking anything it probably isn't worth fixing as we're transitioning to focus on GA4.

We'll discuss this with @marrrmarrr when she returns though to confirm.

**Comment by aaemnnosttv** [comment]
Agreed to leave this as is for UA as it will be resolved with GA4.
