### ISSUE TITLE
Remove `standalone.js`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6392]
## Feature Description

Following #6250 and #6237, there will no longer be any practical use for keeping [`util/standalone.js`](https://github.com/google/site-kit-wp/blob/59e9b40c70bf749801f60e88a7caff5967c23369/assets/js/util/standalone.js) as the only remaining  exports have alternative implementations, and we no longer have a need for a separate standalone set of utilities.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `assets/js/util/standalone.js` should be removed entirely
* Uses of its exports should be replaced with suitable alternatives that are already used

## Implementation Brief

* Replace use of `getQueryParameter` with `useQueryArg`
    * Outside of its own tests, it's only used in `SetupSuccessBannerNotification`
* Remove `assets/js/util/standalone.js`

### Test Coverage

* Remove `assets/js/util/test/getQueryParameter.js`

## QA Brief

* Reset Site Kit.
* Connect Analytics.
* After setup is complete verify that you see `Congrats on completing the setup for Analytics` notification. 

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

-- After setup is complete I see the `Congrats on completing the setup for Analytics` notification. 
   - Tested a few different scenarios: 
   - Setting up a new site that currently does not have Site Kit setup with Analytics.  Banner appeared as expected.
   - Next, rather than resetting Site Kit, I disconnected (not reset) and went through the set up process.  The banner appeared as expected. 
   - Using the same site. I connected Site Kit with Analytics. The banner appeared as expected.
   -  This time I reset Site Kit and went through the setup process again.  The banner appeared as expected. 
   - Didn't see any console or network errors. Looks good 👍 

![image](https://github.com/google/site-kit-wp/assets/73545194/5934e0ea-3a25-4aab-aec6-37b079dc1ad3)
