### ISSUE TITLE
PHP Warning - Deprecated

### ISSUE THREAD

**Issue by sviluppomania** [google/site-kit-wp#6441]
Hi,
I encountered this PHP Deprecated Notice, below:

- `Deprecated: stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /plugins/google-site-kit/includes/Core/REST_API/REST_Routes.php on line 69`

Is there a quick solution to these alerts? :-)

Thank you

Best regards

## Additional Context

 - PHP Version:  8.1.13
 - Plugin Version: 1.92.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment]
Hi @sviluppomania thanks for opening this issue. If using PHP 8.1 depreciation notices are not uncommon, with this version still in Beta support for the latest WordPress releases. Such notices are not specific to Site Kit, with more details on WordPress support for PHP versions below:
https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/

Note also that we’re aware of this and such errors can be disregarded, with warnings expected until PHP 8.1 is fully supported in WordPress. They also don’t impact Site Kit set up or functionality. If you find otherwise let me know and we can investigate this further.
