### ISSUE TITLE
Tag Manager stuck in loading state when reloading edit settings page.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6464]
## Bug Description

When editing the Tag Manager settings, upon reloading the page, the Tag Manager section remains in the loading state.

This is because, for some reason, the Tag Manager's `ownerID` is not being set and this causes the `hasModuleOwnershipOrAccess` selector to return `undefined`. This in turn is a condition for showing the `<ProgressBar />`.

Note, I also checked this scenario for Analytics but the problem did not occur.

## Steps to reproduce

1. Set up Site Kit and connect the Tag Manager module.
2. Navigate to the Tag Manager settings and click **Edit**.
3. Refresh the page.
4. See the Tag Manager section open and stuck in the loading state.

## Screenshots

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/db5d0771-fbd8-4d69-bab0-bd30ba86f4bd)

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: any
 - Plugin Version: seen 1.92.0
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When reloading the Tag Manager edit settings page, it should load normally and not remain stuck in the loading state.

## Implementation Brief

* In `useGAPropertyIDEffect()` https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/assets/js/modules/tagmanager/hooks/useGAPropertyIDEffect.js#L31
  * Load tagmanager settings `select( MODULES_TAGMANAGER ).getSettings()`
  * In the `useEffect` only call the `setGAPropertyID()` function if the tagmanger settings are not falsy.
    ```js
	useEffect( () => {
		if ( !! existingSettings && singleAnalyticsPropertyID !== undefined ) {
			setGAPropertyID( singleAnalyticsPropertyID || '' );
    ```

### Test Coverage

* Update failing test which not need tagmanager setting setup.
* Add a test case to `useGAPropertyIDEffect.test.js` to verify `setGAPropertyID` is not called when `select( MODULES_TAGMANAGER ).getSettings()` is falsy.

## QA Brief

* Follow the "Steps to reproduce" from bug description above.
* Verify the tagmanager settings are not stuck in loading state anymore but load the input fields as expected.

## Changelog entry

* Fix bug that caused Tag Manager settings screen to be stuck in a "loading" state.

**Comment by derweili** [comment]
The error is related to the `SettingsEdit` component loading the `useExistingTagEffect` side effect ([here](https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/assets/js/modules/tagmanager/components/settings/SettingsEdit.js#L55-L56))
https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/assets/js/modules/tagmanager/hooks/useGAPropertyIDEffect.js#L31-L42

This side effect triggers an update to the tagmanager datastore which at that time is still empty.

Because other functions which normally would trigger the `fetchGetSettings()` action are executed after the side effect, the settings are not empty anymore, so the `*getSettings()` resolver does not call the `fetchGetSettings()`.
https://github.com/google/site-kit-wp/blob/5b0c5a9cb46a7843ce6e8d8a405e01b445932125/assets/js/googlesitekit/data/create-settings-store.js#L251-L261

Therefore the `useExistingTagEffect()` hook should be update to only call `setGAPropertyID()` if `getSettings()` is not falsy.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@techanvil this is a great find! 

@mohitwp this is a good one to make a note of for when release testing. I'll add a test case for refreshing all settings.

**Verified:**

 - Went through the the steps to reproduce on the latest version, and could.
 - Changed to develop branch and on refresh the loading state does not get stuck anymore. 


https://user-images.githubusercontent.com/73545194/217402243-fb12799f-76dd-47ae-9917-057c595adf89.mp4
