### ISSUE TITLE
Improve UX/UI of error message when creating a new Analytics view in Site Kit settings

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6480]
## Bug Description

Just a minor UX/UI observation. 

Within Site Kit settings for Analytics when you want to create a new view, and the name you give it, is the same as one already created, then an error message appears.  The text colour does not stand out and in other module settings the error messages are red and more prominent.  e.g. Google Optimize, when the use does not enter the correct format.

![error.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/0681bc7e-bda0-4493-8b82-796362e7bf59)

## Steps to reproduce

1. Set up Site Kit with Analytics
2. Go to Analytics settings and create a new view. 
3. By default the same name appears, and when you click in to the field, the message mentioned above appears. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment]
These are actually quite different cases which is why they don't have the same treatment/appearance.

GA does not prevent you from having duplicate names of views, in which case the message is more of a warning/suggestion than an error. We also don't prevent the user from being able to finish the set up here. The input for specifying the view name was added to avoid a duplicate name when creating a new profile in #716, before which, would always create a new view with the same name.

In Optimize, the validation is much more significant in that it requires a valid ID (which is essentially the entire feature) so the two are quite different in that regard and so I think it is this severity which is reflected in each. This is because Optimize doesn't have an API we can query to get a list of options the user can choose from like with other modules.

Closing for now, thanks!
