### ISSUE TITLE
Site Kit setup flow shows incorrect error message when access code expires

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6509]
## Bug Description

When setting up site kit with Analytics and waiting too long on the fourth step, the following error message is shown. 

![Screenshot_20230131_210238](https://user-images.githubusercontent.com/6187401/215958290-75ff4d33-56e3-40ad-9737-1811377dac2b.png)

However, there is no cancel button below. We should put a cancel button that returns user to dashboard or update the message accordingly.  

## Steps to reproduce

1. Setup Site Kit with Analytics
2. Wait in the 4th step of setup flow so the code expires (~15min).
3. Click continue to see the error. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by wpdarren** [comment]
@kuasha420 I have reported this [before on Asana](https://app.asana.com/0/1199555099685093/1201428661290473/f) because it was my understanding that this was a service engineering side issue, rather than something within the plugin.  I agree though it does need fixing but I got the impression that it was low priority.  c.c. @bethanylang

**Comment by aaemnnosttv** [comment]
@wpdarren you're correct – this isn't something we can address in the plugin. Closing this out as there's already a task for addressing it.
