### ISSUE TITLE
Introduce a way to run code when `Setting` changes and use it across the code base 

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6517]
## Feature Description

In general, there has been needs to run some logic and code whenever the values of a `Setting` changes. The most recent example of it is in #5933. We should introduce a standard way to achieve this and refactor the existing code in our code base to make use of the new mechanism. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Google\Site_Kit\Core\Storage/Setting` class should implement a public `on_change` method.
    * It should take a callback function that takes `$new_value` and `$old_value` as parameters.
    * The callback function should be called when the value changes. ie. on both `add` and `update` operations.
    * The method should return a function, calling that will "unsubscribe" from listening to the changes. 
* Instances where the underlying `{add|update_option_**` hooks are used to detect `Setting` changes and run code should be refactored to use the newly introduced `on_change` method across the code base wherever possible.

## Implementation Brief

* There is a [PoC](https://github.com/google/site-kit-wp/compare/poc/setting-on-update) branch as a starting point, which implements the `on_update` method.
  * Rename the `on_update` method to `on_change`
  * Reverse the parameters order in `$callback` in both add and update function, so it will have `old_value`, `new_value` order
* Modify `includes/Modules/Analytics_4.php`:
  * Replace the [current hook](https://github.com/google/site-kit-wp/blob/aa2ab949ebef47554ae931a55847cee3355fef4a/includes/Modules/Analytics_4.php#L162-L175), by subscribing to the new `on_change` method and pass the existing inline function as callback. Optionally this function can be moved as separate method, and referenced as callback.
* In `Google\Site_Kit\Modules\Analytics` class, do the same for [this hook](https://github.com/google/site-kit-wp/blob/aa2ab949ebef47554ae931a55847cee3355fef4a/includes/Modules/Analytics.php#L138-L147)
* Also for `Google\Site_Kit\Modules\Search_Console`, refactor [this hook](https://github.com/google/site-kit-wp/blob/aa2ab949ebef47554ae931a55847cee3355fef4a/includes/Modules/Search_Console.php#L105-L114)
* In `Google\Site_Kit\Core\Modules\Modules`: 
  * Refactor [this hook](https://github.com/google/site-kit-wp/blob/aa2ab949ebef47554ae931a55847cee3355fef4a/includes/Core/Modules/Modules.php#L325-L351), and [this hook](https://github.com/google/site-kit-wp/blob/aa2ab949ebef47554ae931a55847cee3355fef4a/includes/Core/Modules/Modules.php#L353-L410), by combining them into one inline function callback subscribed to the `on_change` method of `$this->sharing_settings`
* Update `includes/Core/Storage/Setting_With_Owned_Keys_Trait.php`
  * Refactor this [hook](https://github.com/google/site-kit-wp/blob/5d79975b00403bdd6a544ea9ec88dd32d9cf6789/includes/Core/Storage/Setting_With_Owned_Keys_Trait.php#L40-L62) to work with `on_change`. Note that `$defaults = $this->get_default()` check in the current function is handled in `on_change` on add, and will be returned as `old_values` param.

### Test Coverage

* Updates shouldn't be needed

## QA Brief

- Set up Site Kit.
- Perform a smoke test and verify everything works well.
- Analytics
  - Set up the Analytics module with a property that has data available.
  - Go to SK settings and create a new property.
  - Go to SK dashboard and verify that Analytics is in a gathering data state.
- Do the same test for Search Console by changing to a new property that is in a gathering data state.
- Perform a smoke test on dashboard sharing and verify that it works well, especially with the PSI module.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
The core functionality is covered by the POC I believe, so the IB should mostly be focused around refactoring to use it. Maybe @zutigrm ?

**Comment by techanvil** [comment]
Hi @zutigrm, thanks for drafting this IB. I have a few thoughts:

- It seems confusing to have an abstraction over `add` and `update` which is actually called `on_update()`. I think it should be called `on_change()` as per the AC (or something else, that doesn't include the word "add" or "update").
- Adding the third parameter to the callback in order to distinguish `add` and `update` (with resulting additional complexity in the callback) is another pointer that the API should be reconsidered.
- I think that instead we should add separate `on_add()` and `on_update()` methods to `Settings` and use them where we have only need to add one specific hook, or have hook-specific logic. We should add `on_change()` that wraps both hooks and invokes the same callback without passing the `$action` parameter.
- The change to `Modules` could then be implemented with a straightforward migration to `on_add()` and `on_update()`. We could also update [`Setting_With_Owned_Keys_Trait::register_owned_keys`]( https://github.com/google/site-kit-wp/blob/5d79975b00403bdd6a544ea9ec88dd32d9cf6789/includes/Core/Storage/Setting_With_Owned_Keys_Trait.php#L40-L62) to use `on_add()`. The remaining changes look good for `on_change()`.
- See as @aaemnnosttv wrote the PoC he might have some thoughts here too.

**Comment by zutigrm** [comment]
@techanvil Thanks for the feedback.

Yes having separate `on_update` and `on_add` methods was my first though also, but since AC is calling only for one method `on_change` I worked around it.

Let see with @aaemnnosttv and @kuasha420 if can the AC  can be amended to allow this split

**Comment by aaemnnosttv** [comment]
> * It seems confusing to have an abstraction over `add` and `update` which is actually called `on_update()`. I think it should be called `on_change()` as per the AC (or something else, that doesn't include the word "add" or "update").
> * Adding the third parameter to the callback in order to distinguish `add` and `update` (with resulting additional complexity in the callback) is another pointer that the API should be reconsidered.

Agreed on both. Regarding the "third parameter" we could always use `current_action` to determine this as well if we really needed to, but my assumption is that we shouldn't actually need to.

> * I think that instead we should add separate `on_add()` and `on_update()` methods to `Settings` and use them where we only need to add one specific hook, or have hook-specific logic. We should add `on_change()` that wraps both hooks and invokes the same callback without passing the `$action` parameter.
> * The change to `Modules` could then be implemented with a straightforward migration to `on_add()` and `on_update()`. We could also update [`Setting_With_Owned_Keys_Trait::register_owned_keys`](https://github.com/google/site-kit-wp/blob/5d79975b00403bdd6a544ea9ec88dd32d9cf6789/includes/Core/Storage/Setting_With_Owned_Keys_Trait.php#L40-L62) to use `on_add()`. The remaining changes look good for `on_change()`.

@techanvil @zutigrm the reason for the abstraction is that multiple times when we wanted to hook into a setting changing, we ran into the edge case where `add` wasn't considered as it is easy to think that setting the initial value is also a change, and so this bit us a few times.

I can't think of a case where we'd specifically only needed to hook into adding or updating an option. I'm not against adding explicit methods for those, but my concern is that it could lead to the same issue where we only listen to one action when we really should be using both. I can see there is some difference in the implementation for the module sharing settings linked above, although even in this case, I think they could be handled by a single function where the POC fills in the default value as the previous.

> * We could also update [`Setting_With_Owned_Keys_Trait::register_owned_keys`](https://github.com/google/site-kit-wp/blob/5d79975b00403bdd6a544ea9ec88dd32d9cf6789/includes/Core/Storage/Setting_With_Owned_Keys_Trait.php#L40-L62) to use `on_add()`

Ideally, I think the owner ID changes would all happen in `pre_update_` filters rather than as a call hooked to a change since these have the risk of invoking some kind of infinite recursion. It's odd that `add_option` doesn't have an equivalent filter for this, but if added via a call to `update_option`, then it would still go through the `pre_update_option_` filter before `add_option` is called so maybe we can still use that 🤔  Internally we always use `update_option` and never call `add_option` directly. I've been thinking that a follow-up to this issue could be to add a similar API for hooking in a filter on the value when changed.

Back to you guys, let me know if you have any other questions!

**Comment by zutigrm** [comment]
@aaemnnosttv Thank you for clarification.

@techanvil I have updated the IB based on the clarifications in Evan's reply. It is expanded to cover modules and owner trait, as well, since they can actually be aplicable there as well after all, with some slight refactoring. 
Although regarding the potential infinite loop caused by these hooks, this is a very good point. We should probably re-visit the overall approach to this at some point.
In the meantime I adapted the `on_change` usage

**Comment by zutigrm** [comment]
@techanvil Thanks, makes sense. IB is updated to reflect the suggestions

**Comment by techanvil** [comment]
Thanks @zutigrm, that's great. IB LGTM :white_check_mark:

**Comment by nfmohit** [comment]
Hi folks! 👋 
I'm working on this issue and have been encountering some problems with fundamentally how we're adding the `on_change` method.

The `on_change` method runs both when an option is added and updated. However, there are some scenarios in the IB where we want it to run only when the option is added and never again when it is updated. For example:

https://github.com/google/site-kit-wp/blob/48446f0a19cf085feb8169a489820d6390302218/includes/Core/Storage/Setting_With_Owned_Keys_Trait.php#L40-L62

Also, using `on_change` in a place where it is not supposed to run on add but only on update [causes some test cases to fail](https://github.com/google/site-kit-wp/actions/runs/7185872043/job/19570039354), which can be worked around, but I'm not sure if that is the ideal route we want to take.

The `update_option` function can also call `add_option` (according to [its source](https://developer.wordpress.org/reference/functions/update_option/#source)), and thus combining both hooks and running them together has the potential to introduce bugs in the future.

What do you think about adding an `on_add` method so that we have this separation of concern, thus also solving these issues?

Please let me know.

@aaemnnosttv @kuasha420 @techanvil @zutigrm

**Comment by techanvil** [comment]
Hi @nfmohit, thanks for the question. The topic has already been discussed a bit in earlier [comments](https://github.com/google/site-kit-wp/issues/6517#issuecomment-1834381508) and we had explicitly taking the direction _not_ to introduce an `on_add()` method at this point.

With this in mind, we should ensure our `on_change()` handlers will work for both add and update in all cases where possible. If we do find a scenario where we explicitly need to only handle one of these actions, we should introduce `on_(add|update)` at that point. As discussed on Slack, I don't think the tests failing are a sign in themselves that we need to change anything, rather we should update those tests to better reflect the expected real-world usage of the relevant option (i.e. adding `propertyID` to the array we're using, as this is always expected to be present for this option).

The IB point about `Setting_With_Owned_Keys_Trait::register_owned_keys` could be worth reconsidering; @aaemnnosttv did flag the concern about it potentially resulting in an infinite loop, we kept the point to migrate it to use `on_change()` with a view to potentially revisit later. However, refreshing on Evan's initial point about it and reviewing the code, we might be better off removing this IB point and adding a separate issue to see if we can remove the `add_option` hook in that method entirely and purely rely on the `pre_update_option` hook. What do you think?

**Comment by nfmohit** [comment]
Thank you @techanvil.

> As discussed on Slack, I don't think the tests failing are a sign in themselves that we need to change anything, rather we should update those tests to better reflect the expected real-world usage of the relevant option (i.e. adding `propertyID` to the array we're using, as this is always expected to be present for this option).

I have actually considered updating the test cases, however, there are some very generic test utilities which also cause failures, but it wouldn't make much sense to pass a `propertyID` there, I think. For example:

https://github.com/google/site-kit-wp/blob/b9c61b60102122e6a661c014bfd9fdb8312af64a/tests/phpunit/includes/OptionsTestTrait.php#L21-L47

For now, I've updated the `on_change` method in `Search_Console` to account for the fact that `propertyID` may not exist, but let's revisit that in CR if needed.

> The IB point about `Setting_With_Owned_Keys_Trait::register_owned_keys` could be worth reconsidering; @aaemnnosttv did flag the concern about it potentially resulting in an infinite loop, we kept the point to migrate it to use `on_change()` with a view to potentially revisit later. However, refreshing on Evan's initial point about it and reviewing the code, we might be better off removing this IB point and adding a separate issue to see if we can remove the `add_option` hook in that method entirely and purely rely on the `pre_update_option` hook. What do you think?

I agree, thank you!

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
-  @nfmohit I set up site kit with analytics a/c property which have data. After that I created new property for the same account. As per QAB when I create new property then Analytics should appear in gathering data state. But, in my test I created 3 new properties but for all of them Analytics appearing in zero data state on main dashboard.

<details>

https://github.com/google/site-kit-wp/assets/94359491/5ed23c4e-072d-4c9c-b8b8-c13ab8aa28e6

</details>

**Comment by nfmohit** [comment]
> ### QA Update ❌
> * Tested on dev environment.
> * @nfmohit I set up site kit with analytics a/c property which have data. After that I created new property for the same account. As per QAB when I create new property then Analytics should appear in gathering data state. But, in my test I created 3 new properties but for all of them Analytics appearing in zero data state on main dashboard.

Hi @mohitwp. As discussed internally, this bug isn't actually caused due to the PR of this issue, but due to a regression in the latest release. Thanks!

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- For the issue reported [above](https://github.com/google/site-kit-wp/issues/6517#issuecomment-1864288922) as per discussion with @nfmohit I created separate ticket - https://github.com/google/site-kit-wp/issues/8023.
- Done smoke testing.
- Verified that for new property SC appears in a gathering data state and verified with Darren that if property have data then gathering data state is not showing.
- To test SC I used tester plugin.
- Performed a smoke test around DS functionality and around PSI widget.
- 

<details>


https://github.com/google/site-kit-wp/assets/94359491/e85efe87-19b3-4452-84bc-443910396311



</details>
