### ISSUE TITLE
Add prerequisites for GA4 Reporting components.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6559]
## Feature Description

This is an issue to break out the commonalities for GA4 Reporting initially implemented in #6216.

Furthermore these need to be updated following the discovery that the GA4 has diverged a bit from UA in how it returns reports with no data, as alluded to in this [comment](https://github.com/google/site-kit-wp/issues/6559#issuecomment-1427804169) below.

These commonalities include the GA4 versions of:
- `isGatheringData()` selector.
- `hasZeroData()` selector.
- `replaceValuesInAnalytics4ReportWithZeroData()` Storybook utility function (could be useful, might as well include it here).

Plus any dependencies of the above.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GA4 versions of the selectors/functions mentioned above should be implemented, along with any dependencies of theirs:
  * `isGatheringData()` selector.
  * `hasZeroData()` selector.
  * `replaceValuesInAnalytics4ReportWithZeroData()` Storybook utility function 

### `isGatheringData()` selector

Following discussion on Slack the logic here is as follows.

- Retrieve a GA4 report, similar to the one UA `isGatheringData()` uses, but using the metric `totalUsers` and dimension `date`.
- Retrieve the GA4 property via the GA4 `getProperty()` selector.
- If the report or property is `undefined`, return `undefined` to indicate the selector is still loading.
- Check if the report has data - use the `isZeroReport()` utility function.
- If the report has data, return `false`.
- If the property is more than two days old (see the `createTime` field), return `false`.
- Otherwise, return `true`.
- Note the execution doesn't have to strictly follow the order above, and can be adjusted for efficiency.

### `hasZeroData()` selector

- Retrieve a GA4 report, similar to the one UA `hasZeroData()` uses, but using the metric `totalUsers` and dimension `date`.
- If the report is `undefined`, return `undefined` to indicate the selector is still loading.
- Check if the report has data - use the `isZeroReport()` utility function.
- Return `false` if the report has data, otherwise `true`.

### `isZeroReport()` utility function

Note that an empty report will take the following shape.

```json
{
  "dimensionHeaders": [
    {
      "name": "date"
    }
  ],
  "metricHeaders": [
    {
      "name": "totalUsers",
      "type": "TYPE_INTEGER"
    }
  ],
  "totals": [{}],
  "maximums": [{}],
  "minimums": [{}],
  "metadata": {
    "currencyCode": "USD",
    "timeZone": "Etc/UTC"
  },
  "kind": "analyticsData#runReport"
}
```

- Update the current GA4 `isZeroReport()` implementation to reflect the fact that an empty report will not have a `rows` property and the `totals` property will be an array containing a single empty object.

### `replaceValuesInAnalytics4ReportWithZeroData()` Storybook utility function

- Update this function to return the passed report transformed to an empty report as detailed above.

### Test Coverage

- Update the tests for the selectors and the `isZeroData()` utility function.

## QA Brief

* Enable the `ga4Reporting` feature flag.
* Make sure to clear session storage and refresh the page between tests.
* Connect a new GA4 property, which has no data yet. Run the `isGatheringData()` and `hasZeroData()` selectors in the JS console.
  * `isGatheringData()` should return `true`.
  * `hasZeroData()` should also return `true`.
* Connect a GA4 property which is at least two days old, but has no site visits associated with it, and run the selectors.
  * `isGatheringData()` should return `false`.
  * `hasZeroData()` should return `true`.
* Connect a GA4 property that does have some visits associated with it, and run the selectors.
  * `isGatheringData()` should return `false`.
  * `hasZeroData()` should also return `false`.

```js
googlesitekit.data.select('modules/analytics-4').isGatheringData();
googlesitekit.data.select('modules/analytics-4').hasZeroData();
```

## Changelog entry

* N/A

**Comment by mohitwp** [comment]
###QA Update ❌ 


@techanvil 

**Case 1** : I created a new site and set up analytics with new GA4 property. Ran both selectors in JS console and getting `false` for both requests in return.

![image](https://user-images.githubusercontent.com/94359491/218421787-41dc310f-d83f-47a4-956e-3c6e9aec102b.png)

**Case 2** : I Ran both request on 1 day older site and which is in zero data state. Again, getting `false` for both requests in return.

![image](https://user-images.githubusercontent.com/94359491/218422069-046365fe-cc5b-4271-8209-0d35750393bc.png)

**Comment by techanvil** [comment]
Hi @mohitwp, thanks for raising this.

I've realised I should have included a couple of extra details in the QAB, which I have now added:

- Enable the `ga4Reporting` feature flag.
- Make sure to clear session storage and refresh the page between tests.

However, I have also discovered there's an issue with the `hasZeroData()` selector and the underlying mechanism by which we determine if a GA4 report is in the "zero data" state, which will need to be resolved, and this will need a bit of investigation and a followup PR to address.

**Comment by tofumatt** [comment]
IB looks good, IB ✅

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@techanvil 

- Tested on dev environment.
- Now I'm getting correct response, but I've noticed strange behavior for the gathering data selector.

**Steps -**
- `ga4Reporting` feature flag is enabled.
- When both search console and analytics are in gathering state. (Fresh site)
- If I run `googlesitekit.data.select('modules/analytics-4').isGatheringData();` in JS console then I'm getting 'Undefined' response for first 2 requests. 
- `Uncaught (in promise) Invariant Violation: propertyID is required.` error for 3rd request.
- Again undefined for 4th request.
- From 5th requests, I'm getting correct response, and it is happening every time I refresh the page.

I'm wondering is this is the another issue or I'm missing something.


<details>

![image](https://user-images.githubusercontent.com/94359491/220079088-59461069-9c1a-4d76-9d2c-151bc2158476.png)


https://user-images.githubusercontent.com/94359491/220079131-65e40aa6-09d8-4b86-abdc-801f37674673.mp4

**Comment by techanvil** [comment]
Hi @mohitwp, thanks for raising this.

The `undefined` response is to be expected - it's a common pattern for our selectors, and indicates that the data is still loading. In this case the correct thing to do is re-run the selector until it returns a non-`undefined` response (unless you are specifically testing for the loading state of course).

Apologies for not including this detail in the IB, however, as mentioned this is a common pattern so you should expect to see the same thing occurring for other selectors when invoking them via the JS console.

However, the JS console error is _not_ to be expected, I will have to take a look at that and raise a followup PR. Thanks for spotting!

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@techanvil 
-Tested on dev.
- Tested all 3 conditions.
- I'm not getting expected response for the below condition - For `isGatheringData()` selector response should be false. But I'm getting 2 also in this case. 
1. Connect a new GA4 property, which has no data yet. Run the isGatheringData() and hasZeroData() selectors in the JS console.
   
![image](https://user-images.githubusercontent.com/94359491/220345983-acfdddd6-02b3-43e7-b896-b72c542901f5.png)


<details>

![image](https://user-images.githubusercontent.com/94359491/220346209-93f6c7ce-48ea-4580-8ccc-da3389ff8d61.png)

![image](https://user-images.githubusercontent.com/94359491/220346235-c643d574-f490-48ac-ac5e-955abee66bf0.png)

</details>

**Comment by techanvil** [comment]
Hi @mohitwp, I'm not sure what's causing this as I can successfully test this case here.

Can you confirm the current GA4 property is definitely more than two days old by examining the `createTime` value for it? This can be achieved in the JS console like so:

```js
googlesitekit.data.select('modules/analytics-4').getProperty(
    googlesitekit.data.select('modules/analytics-4').getPropertyID()
).createTime
```

![image](https://user-images.githubusercontent.com/18395600/220400008-8aed5c5f-ddaf-42ee-a439-ab3cc3650d06.png)

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev.
- Tested all 3 cases mentioned in QAB.

- Connect a new GA4 property, which has no data yet. Run the isGatheringData() and hasZeroData() selectors in the JS console.

`isGatheringData()` should return true.
`hasZeroData()` should also return true.

<details>

![image](https://user-images.githubusercontent.com/94359491/220346235-c643d574-f490-48ac-ac5e-955abee66bf0.png)

</details>

- Connect a GA4 property which is at least two days old, but has no site visits associated with it, and run the selectors.

`isGatheringData()` should return false.
`hasZeroData() `should return true.

<details>

![image](https://user-images.githubusercontent.com/94359491/220525917-34244fdb-8921-4729-9168-1844166a18d3.png)

</details>

- Connect a GA4 property that does have some visits associated with it, and run the selectors.

`isGatheringData()` should return false.
`hasZeroData() `should also return false.

<details>

![image](https://user-images.githubusercontent.com/94359491/220346209-93f6c7ce-48ea-4580-8ccc-da3389ff8d61.png)

</details>

**Comment by felixarntz** [comment]
## Approval ⚠️ 

The implementation here is okay given where we are with our exploration on how the GA4 Data API works. However, I am unsure whether it is indeed the correct approach to recognize "gathering data" and "zero data".

FWIW we should do some comprehensive testing for both UA and GA4 to validate how the APIs handle those scenarios. My _assumption_ (or based on what I remember) is that the difference is the following:
* For "gathering data", the response does not include the `data.rows` property, or it is `null`.
* For "zero data", the response does include the `data.rows` property, but it is an empty array, or all values are 0.

We need to validate whether that is indeed the case for UA (just to make sure our existing code there is still correct), and also whether this is the same in the GA4 reporting endpoint or not.

I am aware of the GA4 problem with the `keepEmptyRows` parameter, but what I'm saying above is essentially that it _could_ be that, at least for this particular concern of determining "gathering data" and "zero data", this problem doesn't matter. If so, we should keep relying on that differentiation rather than the creation time of the property.

Of course we may need to do any potential iteration in a follow up issue, since it's too late before the release - but that's okay since this is not yet going out to anybody.

@aaemnnosttv already started doing some testing. I'll keep this open for now just to collect the findings and from there determining if we need a follow up issue.

**Comment by aaemnnosttv** [comment]
> I am aware of the GA4 problem with the `keepEmptyRows` parameter, but what I'm saying above is essentially that it _could_ be that, at least for this particular concern of determining "gathering data" and "zero data", this problem doesn't matter. If so, we should keep relying on that differentiation rather than the creation time of the property.

@felixarntz We'll see what the results show but at least for UA, once the property is no longer gathering, the `includeEmptyRows` adds rows for the requested date range, even going back before the property was created.

For GA4, zero data isn't something we seem to be able to differentiate based on the report alone because empty rows are excluded entirely, so there does not seem to be an observable difference between no data available yet (gathering) or no data in the requested period. For a fresh property, and one that was created more than a month ago, I can see that the top level `rows` is not in the response at all (even with `keepEmptyRows`).

**Comment by felixarntz** [comment]
@aaemnnosttv I'm still confused by this statement:
> For GA4, zero data isn't something we seem to be able to differentiate based on the report alone because empty rows are excluded entirely, so there does not seem to be an observable difference between no data available yet (gathering) or no data in the requested period.

Based on what you say afterwards, we _can_ identify when it is gathering (`rows` is not in the response at all, similar to how it is for UA). So I would think we have all we need:
* If `rows` is not set, we are in "gathering data" state.
* If the `rows` is set, but is empty or there are only 0s, we are in "zero data" state.
* Otherwise, there is data.

Is that not the case? I still see how for other reasons the new behavior of `keepEmptyRows` is confusing and inconsistent with UA), but based on how I understand what you're saying, I still think we would have all we need to determine those 3 states - or what am I missing?

**Comment by aaemnnosttv** [comment]
> I think this is the issue—even for a property that is over a month old (which is no longer "gathering data", but is in _zero data state_), the `rows` key is missing in the API response.
>
> That means we can't rely on an empty "rows" parameter to know if we're in a gathering data state vs zero data state.

Yes, that is what I was getting at. To me this indicates that the API omits the `rows` property rather than returning an empty array – I think this much was the same in UA, difference is that UA would return rows as soon as it was no longer gathering. Going forward the date-based approach to the gathering state may be the most accurate for GA4 but I will seek more clarification about the best way to determine this.
