### ISSUE TITLE
GA4 settings area shifts after loading completes

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6570]
## Bug Description

When the GA4 property select on the settings edit view is enabled, it first enters a loading state while its choices are loaded. Once complete, it renders the normal select again as usual but there is a shift in its height that happens in the transition.

## Steps to reproduce

1. Load the settings edit view for Analytics with GA4 enabled/connected
2. Refresh the page
3. Observe visual shift when loading completes

## Screenshots

<img width="378" alt="image" src="https://user-images.githubusercontent.com/1621608/217972996-a7de352e-8742-453f-8007-72f30209cffd.png">
<img width="371" alt="image" src="https://user-images.githubusercontent.com/1621608/217973006-9ae78ff3-9469-4e3d-a4b8-8948f12987b0.png">

https://user-images.githubusercontent.com/1621608/217973084-f947eaee-01ad-44e2-ba61-0169b9e0d20e.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics 4 settings area should have a consistent height between loading and loaded states

## Implementation Brief

* In `assets/js/googlesitekit/components-gm2/ProgressBar.js`
  * Add new `smallHeight`, `tabletHeight`, `desktopHeight` properties to the `ProgressBar` component.
  * Similar to how we do it in the [`PreviewBlock` component](https://github.com/google/site-kit-wp/blob/c3f0c6b38a60d7098e5e620d638e6cf765d0e316/assets/js/components/PreviewBlock.js#L54), set the height based on the breakpoint. We don't need props for `width` here.
  https://github.com/google/site-kit-wp/blob/c3f0c6b38a60d7098e5e620d638e6cf765d0e316/assets/js/components/PreviewBlock.js#L49-L73
  * Make sure this logic is placed before the margin calculation and the correct height is used to calculate the `PreviewBlock` margins.
* In `assets/js/modules/analytics-4/components/common/PropertySelect.js`
  * Remove the `height` attribute from `<ProgressBar />`.
  * Use the new `smallHeight` and `desktopHeight` props instead. Set these to
    * `smallWidth`: `80px`
    * `desktopWidth`: `88px`

### Test Coverage

* No test have to be added or changed.

## QA Brief

* Follow the steps to reproduce.
* There will no longer be a layout shift after GA4 Property and WebDataStreams have been loaded. 
* Ensure the correct behavior on all breakpoints (mobile, tablet, desktop etc).
* Additional Testing:
    * As the PR also touches code for the `ProgressBar` placed in `Connected Services` and `User Input` Page, making sure that they perform correctly without any regression would be useful. 
        * In Activate module, check the progress bar on the Analytics module status. ie. [Settings -> Connected Services
](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/settings--connected-services)
        * The top progress bar in User Input page. 

## Changelog entry

* Prevent layout shift in GA4 settings area when the dropdown options finish loading.

**Comment by asvinb** [comment]
IB ✔️

**Comment by asvinb** [comment]
@derweili Regarding setting the height to `80px` and `88px` to the `ProgressBar` component will introduce another UI issue as per the screenshot:
![image](https://user-images.githubusercontent.com/31818/218090090-999f3ab1-7863-485e-a170-f4496f58e1b9.png)

Actually if you look at the code for `ProgressBar`, you'll notice that the value of the `height` [prop is divided by 2](https://github.com/google/site-kit-wp/blob/develop/assets/js/googlesitekit/components-gm2/ProgressBar.js#L34) and then we are using [margin top and margin bottom](https://github.com/google/site-kit-wp/blob/develop/assets/js/googlesitekit/components-gm2/ProgressBar.js#L40) using those values. The height of the progress bar remains the same, we are only adding top and bottom margin to simulate the increased height. So instead of using `height` in the IB, we should use `margin-top` and `margin-bottom`. This leads me thinking whether we should different height props per breakpoint to the component similar to how we do it in the `PreviewBlock` [component](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/PreviewBlock.js#L42-L47). Thus we would have the `height` component (current), `smallHeight`, `tabletHeight` and `desktopHeight` for the small, medium and large breakpoints respectively. This would be better in case we have similar issues in the future instead of having to add a custom class name to each `ProgressBar` and basically duplicating the same CSS properties over. Let me know what you think 👍

**Comment by asvinb** [comment]
Nice, thanks @derweili . I tweaked the IB to fix a typo but IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified GA4 settings area, All modules under connected services and user input settings under admin.
- Verified now visual shift is not occurring when loading completes and Analytics 4 settings area have a consistent height between loading and loaded states.

<details>

https://github.com/google/site-kit-wp/assets/94359491/23cc937d-af09-4722-8a4d-84f501d2274c


https://github.com/google/site-kit-wp/assets/94359491/7b77a602-cfac-4582-bd9b-9996a8c913f8

</details>
