### ISSUE TITLE
jsxBracketSameLine is deprecated

### ISSUE THREAD

**Issue by itsaladin** [google/site-kit-wp#6603]
## Bug Description

jsxBracketSameLine shows this deprecation warning when ending it.

   `jsxBracketSameLine is deprecated.`

## Steps to reproduce

1. Run `npm run watch`
3. See the deprecation notice

## Screenshots
![Screenshot_20230217_034153](https://user-images.githubusercontent.com/37948276/219493547-af3191ea-c285-4683-b59f-10b490521748.png)

## Additional Context

 - PHP Version: 7.4
 - OS: [Arch-based Manjaro]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Prettier should not warn about `jsxBracketSameLine` deprecation while running lint or build related commands that invoke the `prettier` cli. 

## Implementation Brief

* Update `@wordpress/prettier-config` dev dependency to `^2.0`.
* Edit `.eslintrc.json` and force the `usePrettierrc` option to `true` for the `prettier/prettier` rule (which will likely need to be added to the `rules` object). 
    * The `prettier` entry does not need to be added to the `extends` or `plugins` objects.
* Fix any formatting or rule violation due to the aforementioned version bump. 

A POC branch can be found at https://github.com/google/site-kit-wp/tree/infra/6603-jsxbracketsameline-deprecation-warning-on-watch

### Test Coverage

* N/A

### NOTE: This likely only needs technical QA by another engineer or two:

- Update the `@wordpress/prettier-config` via `npm install`.
- Run the `watch` script via `npm run watch`.
- Validate that the `JSXBracketSameLine` deprecation notice no longer appears.
- Validate that JS files are still correctly watched and linting etc applied, or flagged applicable on save.

* 

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
Thanks for opening this 👍

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by zutigrm** [comment]
The issue seem to be deeper then IB suggests. The prettier config including the `@wordpress/prettier-config` seems not to be run in build commands. Checked by updating `@wordpress/prettier-config` to 1.4 and 2.0, and excluding it completely from prettier config.

**Comment by bethanylang** [comment]
Moving back to IB as per @zutigrm and @aaemnnosttv, the IB needs to be revisited as the current plan will not work.

**Comment by 10upsimon** [comment]
@zutigrm (cc @aaemnnosttv ) after following the dependency tree and much trial and error, it appears I am able to fix the issue with the following steps:

1. Update `@wordpress/prettier-config` to version `^2.0`
2. Within `.eslintrc.json` apply the following updates:
    - Add the following to the `rules` property:
    
```
"prettier/prettier": [
    "error",
    {},
    {
        "usePrettierrc": true
    }
]
``` 

There are many packages (mostly dependencies) requiring `eslint-plugin-prettier` (32 to be exact). I noticed that one of the dependency packages of `uuid` (which require as a devDependency in `package.json`) has an _explicit_ version requirement of `3.1.4` for `eslint-plugin-prettier`, hence this is ultimately the installed version according to `package-lock.json`. 

Interestingly, the `usePrettierrc` option (which defines if the `.prettierrc.js` (or `.prettierrc.json`) file must be loaded or not, defaults to `true` in all versions I looked at, with no bugs reported indicating otherwise. My initial hunch is that perhaps `3.1.4` did _not_ set this as true by default, but (at least according to their [README](https://github.com/prettier/eslint-plugin-prettier/blob/v3.1.4/README.md)) it does. They do, however, state the following:

> This plugin works best if you disable all other ESLint rules relating to code formatting, and only enable rules that detect patterns in the AST.

So I am unsure whether some config, buried deep within a dependency, was somehow disabling this. I could not find any installed packages indicating an override.

This fix can be validated by commenting out the `module.exports` block requiring `@wordpress/prettier-config`. This will result in 1000's of formatting errors when running `npm run watch`. Reinstating the line, will rid those errors and also rid us of the `jsxBracketSameLine` deprecation warning when running `npm run watch`.

I've not observed any detrimental behaviour while simply testing the watch against some basic JS files.

@zutigrm I'd love your input here given your initial feedback in the comments above.

I am also noting that this fix _does not_ work when `@wordpress/prettier-config` is retained on the existing version `^1.1.1`.

**Comment by 10upsimon** [comment]
> Lets see if @aaemnnosttv might have additional thoughts on that.

@aaemnnosttv @zutigrm I've updated the IB based on my findings, if you're both happy we can transition this to IBR, thank you.

**Comment by aaemnnosttv** [comment]
Nice work @10upsimon – let's do it 👍

**Comment by tofumatt** [comment]
Awesome, thanks to everyone for the deep-dive on this one 😄 

IB ✅

**Comment by 10upsimon** [comment]
Noting that this likely needs ENG:QA to validate the fixes.

**Comment by aaemnnosttv** [comment]
Verified that the warning is no longer present after running `npm install` and then a build 👍 

Moving to approval 🚀
