### ISSUE TITLE
Dashboard sharing confirmation appears in settings when no roles are shared for module

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6633]
## Bug Description

When a module is shared via dashboard sharing, if another admin with access to that module's entity attempts to change its configured entity, a notice is shown in the footer of the settings edit view to inform the user that by saving they will be sharing the data for this module through their Google account since they will become the new module owner.

This is only relevant for a module which is currently being shared with one or more roles, and of course if the current user is not already the module owner. Currently this notice is being shown even when no shared roles are configured for a module.

## Steps to reproduce

1. Ensure dashboard sharing is enabled, reset any existing sharing settings so that nothing is shared
2. Connect Analytics
3. With a different admin, go to the GA settings, and change the selected UA or GA4 property
4. See the notice

## Screenshots

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/1621608/221046982-d14dc4b0-02e0-4c1e-9c8b-f6412daf21a2.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The notice about granting access to data from {service} via your Google account should only be shown to users who are changing the connected entity of a module when that module is currently being shared with one or more roles

## Implementation Brief

* Within the `/assets/js/components/settings/EntityOwnershipChangeNotice.js`:
    * In addition to `getModuleStoreNames`, destructure the `getSharedRoles` selector as well.
    * When computing `storeNames`, call the `getSharedRoles` selector passing the `currentSlug`.
    * Only add the `storeName` to the `acc` if there are `sharedRoles`.
* The `getSharedRoles` selector above relies on `global._googlesitekitDashboardSharingData` which is not available on the Settings pages. So in `Assets.php`, in the `get_assets()` method, when registering `googlesitekit-settings`, pass the `dashboard-sharing` context instead of the `dashboard` context to the `get_asset_dependencies()` method.

### Test Coverage

* Fix any failing tests.

## QA Brief

* Ensure dashboard sharing is enabled, reset any existing sharing settings so that nothing is shared
* Connect Analytics
* With a different admin, sign in to Site Kit as an Admin using an account that ALSO has access to this GA account, and go to the GA settings, and change the selected UA or GA4 property
* No "By clicking confirm…" notice should appear.

## Changelog entry

* Fix notices about granting view-only access when changing module settings for modules that are not shared with any roles.

**Comment by techanvil** [comment]
Hi @sashadoes, thanks for drafting this IB, however the approach taken is not quite correct.

The concept of a "shared ownership" module is separate to whether the module has been shared with other roles. Shared ownership modules are covered in the [Design Doc](https://docs.google.com/document/d/19OtWe7jXKC6dIUfs6J4gDrXujHgCuXnksxBM1uUWmOQ/edit#heading=h.mei1mnj9uwgh), and specifically only PageSpeed Insights is a shared ownership module now that Idea Hub has been removed.

Instead, in order to check if a module has been shared with any roles, the `getSharedRoles()` selector should be called with the module slug as its argument. If the selector returns a non-empty array then the module has been shared.

There's an additional detail that needs to be considered for the implementation, which is that Dashboard Sharing data is not currently available on the Settings page. This is because the [`googlesitekit-dashboard-sharing-data` asset](https://github.com/google/site-kit-wp/blob/216103df16fe39ae25f85573bcaa6cd93addbc13/includes/Core/Assets/Assets.php#L408-L416) is not presently a dependency of the [`googlesitekit-settings` asset](https://github.com/google/site-kit-wp/blob/216103df16fe39ae25f85573bcaa6cd93addbc13/includes/Core/Assets/Assets.php#L611-L617) which is the main bundle for the [Settings Screen](https://github.com/google/site-kit-wp/blob/216103df16fe39ae25f85573bcaa6cd93addbc13/includes/Core/Admin/Screens.php#L472-L479).

So in order for `getSharedRoles()` to work on the Settings page, `googlesitekit-dashboard-sharing-data` needs to be defined as a dependency of `googlesitekit-settings`. This is probably best managed by updating [`get_asset_dependencies()`](https://github.com/google/site-kit-wp/blob/216103df16fe39ae25f85573bcaa6cd93addbc13/includes/Core/Assets/Assets.php#L295) to allow multiple contexts to be passed in, and then passing `dashboard-sharing` as well as `dashboard` in the call to it that sets up the [`googlesitekit-settings` dependencies](https://github.com/google/site-kit-wp/blob/216103df16fe39ae25f85573bcaa6cd93addbc13/includes/Core/Assets/Assets.php#L615).

**Comment by aaemnnosttv** [comment]
@bethanylang let's try to include this in 1.102, it shouldn't be a big effort and we shouldn't delay it anymore.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified The notice about granting access to data from {service} via your Google account showing to users who are changing the connected entity of a module when that module is currently being shared with one or more roles.
- Tested on both UA and GA4 dashboard.
- Verified when only GA4 is connected.
- Verified when both GA4 and UA are connected.

<details>


https://github.com/google/site-kit-wp/assets/94359491/8281331b-3ab7-474f-80d6-49d9b6f32cc2

</details>
