### ISSUE TITLE
Provide a general solution to prevent errors in widgets from crashing the whole dashboard

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6695]
## Feature Description

In #4837, we have discovered from user provided traces that `Cannot read properties of null (reading '0')` error is originating from `SearchConsoleStats` component. See [here](https://github.com/google/site-kit-wp/issues/4837#issuecomment-1244402632). 

It may be possible to put an error boundary around it to prevent crashing the dashboard. 

**Update**: As per https://github.com/google/site-kit-wp/issues/6695#issuecomment-1631276777, we should provide a more general solution to ensure that an error in an individual widget doesn't crash the entire dashboard, e.g. by adding an error boundary to/around `WidgetRenderer`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If a JavaScript error is thrown by a widget, it should be caught and displayed at the widget level rather than crashing the whole dashboard.
* We should specifically ensure that the error described in #4837 is caught as per the above.
* The error should still be logged with `trackEvent`, the same way the may error handler does (see: https://github.com/google/site-kit-wp/blob/100cd865310876f3e0dad2adabe135756cbc4d1f/assets/js/components/ErrorHandler/index.js#L54-L59)

## Implementation Brief

* Add `assets/js/components/ErrorBoundary.js`
  * Implement the `ErrorBoundary ` component from official documentation - `https://react.dev/reference/react/Component#componentdidcatch`
  * In `componentDidCatch` pass `error` and `info` to the local state, so it can be displayed within the fallback component in case of the error
  * In the `render` method, add a basic markup that can be wrapped within `Widget` container holding the error message in case of an error, combing `error` and `info.componentStack`
  * Ensure `trackEvent` is called with the same data as would be here: https://github.com/google/site-kit-wp/blob/100cd865310876f3e0dad2adabe135756cbc4d1f/assets/js/components/ErrorHandler/index.js#L54-L59
* Update `assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js`
  * Wrap `WidgetRenderer` with new component `ErrorBoundary` 

### Test Coverage

* Perhaps `assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.test.js` can be updated to include the test case for error showing in the widget, by trying to simulate error with wrong data, like maybe feeding some incorrect data (`[1]`) to the `getViewableModules` selector 

## QA:Eng

As the error needs to be generated artificially, we will need an engineer to generate this error and test the error boundary using following steps.

Run `npm run watch` before following steps to generate build files.

1. Go to `assets/js/modules/analytics-4/components/dashboard/DashboardAllTrafficWidgetGA4/index.js`
2. In `DashboardAllTrafficWidgetGA4` function, after this line

```js
  const { Widget, WidgetReportError } = props;
```

Add following code.

```js
	let someTestVar;

	if ( someTestVar.nonExistingProperty ) {
		const test = 124;
	}

```

3. Visit the Site Kit dashboard and go to "Traffic" widget, you will see the error and the component stack.
![image](https://github.com/google/site-kit-wp/assets/20284937/8c0936cf-285d-44b6-8df0-075ad05ec516)

4. Rest of the components in dashboard should be working fine and dashboard does not crashes.

## Changelog entry

* Add error boundary to widgets to prevent errors in an individual widget from crashing the entire dashboard.

**Comment by aaemnnosttv** [comment]
I feel like we should probably add an error boundary to `WidgetRenderer` as we shouldn't let an error in any single widget crash the entire dashboard.

**Comment by nfmohit** [comment]
We have been receiving increasing events of this error occurring in our error logs. We should look into prioritising this. I'll raise this internally as well.

**Comment by tofumatt** [comment]
IB ✅ 

I added a note to the ACs/IB about still calling `trackEvent`, but otherwise looks good 👍🏻

**Comment by nfmohit** [comment]
Hi @zutigrm @tofumatt (as IB author and reviewer)! I'm working on the CR for this issue and it occurs to me, why can't we simply use the `ErrorHandler` component that we already have instead of creating a new `ErrorBoundary` component?

The pre-existing `ErrorHandler` component already provides some nice formatting, allows copying the error contents, and includes a link to contact support.

Here is how the `ErrorBoundary` component looks in the attached PR:
![image](https://github.com/google/site-kit-wp/assets/20284937/2150b133-1e0d-4dca-aaac-db22d4dbc5d0)

Here's how it looks like replace it with the pre-existing `ErrorHandler` component:
![image](https://github.com/google/site-kit-wp/assets/20284937/880a1ba9-17c8-4a6b-bb7d-6e0db28106f1)

The current implementation of `ErrorBoundary` can surely be improved if necessary, but it feels redundant when `ErrorHandler` is already present for the same purpose.

Please let me know what you think, thanks!

**Comment by nfmohit** [comment]
Hi @zutigrm @tofumatt (as IB author and reviewer)! I'm working on the CR for this issue and it occurs to me, why can't we simply use the `ErrorHandler` component that we already have instead of creating a new `ErrorBoundary` component?

The pre-existing `ErrorHandler` component already provides some nice formatting, allows copying the error contents, and includes a link to contact support.

Here is how the `ErrorBoundary` component looks in the attached PR:
![image](https://github.com/google/site-kit-wp/assets/20284937/2150b133-1e0d-4dca-aaac-db22d4dbc5d0)

Here's how it looks like replace it with the pre-existing `ErrorHandler` component:
![image](https://github.com/google/site-kit-wp/assets/20284937/880a1ba9-17c8-4a6b-bb7d-6e0db28106f1)

The current implementation of `ErrorBoundary` can surely be improved if necessary, but it feels redundant when `ErrorHandler` is already present for the same purpose.

Please let me know what you think, thanks!

CC: @ankitrox

**Comment by zutigrm** [comment]
@nfmohit that's a pretty good spot! Thanks, I actually didn;t know we already have that component, which is kinda doing the same as `ErrorBoundry` 🤔  I understood from the issue description/AC that we do not have implementation that catches error on tile level, so I explored a way to add it. It seems we can just use `ErrorHandler` component in this case

**Comment by tofumatt** [comment]
@nfmohit I'm not opposed to re-using the existing component, we'll probably want to customise/tweak the styles a bit to work inside of widgets, but fair point about not creating an entirely new component when all of the logic is similar 👍🏻 

Fine if you do that instead, it's probably better 🙂

**Comment by nfmohit** [comment]
Thank you for the confirmation, folks!

**Comment by ankitrox** [comment]
Thank you @nfmohit 

I've made the necessary changes to the PR and assigning back to you for re-review.

**Comment by hussain-t** [comment]
### QA:Eng Verified ✅ 

- Verified that when an error is thrown by a widget, it is caught and displayed at the widget level, preventing the entire dashboard from crashing.

<details>
<summary>Screenshot</summary>
<br />
<img width="946" alt="Screenshot 2024-06-18 at 8 03 37 PM" src="https://github.com/google/site-kit-wp/assets/24408261/e0bad662-afb1-476c-a342-d3255d70534b">
</details>

- Verified that the `trackEvent` is triggered and accurately logs the relevant error details.

<details>
<summary>Screenshot</summary>
<br />
<img width="989" alt="Screenshot 2024-06-18 at 8 04 20 PM" src="https://github.com/google/site-kit-wp/assets/24408261/026d9490-a442-46d4-9d53-b45842e21987">
</details>

**Comment by aaemnnosttv** [comment]
This is good but how does it work for small widgets? It's better than crashing the whole dashboard of course but we should adjust the display to be more compact since we can't know how much space will be available. We should also show a cleaner user-facing view, similar to what is done in `GoogleChartErrorHandler`.

As for the error reporting, we should also track it differently than the top level error boundary so that we can differentiate between a full app crash and a widget error.

@tofumatt @kuasha420 can you work on creating a follow up to address this in a new issue?
