### ISSUE TITLE
Prevent Analytics report error in SK dashboard with UA not connected

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#6746]
## Feature Description

When the Analytics module is connected only with GA4 but without UA (made possibly via #6737, under the `ga4Reporting` feature flag), visiting the Site Kit dashboard results in a `analytics` `GET:report` failure, possibly from the `analytics` `isGatheringData()` or `isZeroData()` selectors in `ZeroDataStateNotifications`. This needs to be updated to use selectors from the `analytics-4` datastore in the GA4 dashboard view. Here's a screenshot:

![image](https://user-images.githubusercontent.com/20284937/226018070-835c9ef2-bcb5-4fc0-99ce-629547e66b8d.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- `ZeroDataStateNotifications` should be updated to not use selectors from the `analytics` datastore in the GA4 dashboard view, and use them from the `analytics-4` datastore instead.
- In the GA4 dashboard view, with Analytics connected only having GA4 entities and no UA entities, no network request failures should appear in the console.

## Implementation Brief

In `assets/js/components/notifications/ZeroDataStateNotifications/index.js`:
* Check if the dashboard view is `google-analytics-4` using the `isGA4DashboardView` selector from the `analytics` datastore.
* If it is, use the `isGatheringData` and `hasZeroData` selectors from the `analytics-4` datastore instead of the ones from the `analytics` datastore.
* Otherwise, use the selectors from the `analytics` datastore as the current implementation.
* Add stories for the `ZeroDataStateNotifications` component for the GA4 dashboard view.

### Test Coverage

* No new tests are to be added.

## QA Brief

* Connect Analytics to a site with only GA4, not UA. This can be simulated by deleting the `googlesitekit_analytics_settings` option.
* Ensure the `ga4Reporting` feature flag is enabled.
* Ensure the dashboard view is set to `google-analytics-4`.
* To set the dashboard view, run the following command in the console:
```js
googlesitekit.data.dispatch( 'modules/analytics' ).setDashboardView('google-analytics-4')
```
* To save the settings, run the following command in the console:
```js
googlesitekit.data.dispatch( 'modules/analytics' ).saveSettings()
```
* Then refresh the page. You may have to clear the session storage.
* Ensure Analytics is in Zero/Gathering Data state.
* Ensure no report-related network errors are logged in the console.
* Ensure no network requests are made to the `/google-site-kit/v1/modules/analytics/data/report` endpoint; instead, it should be made to the `/google-site-kit/v1/modules/analytics-4/data/report` endpoint.
* Ensure no report-related network errors occur in the `DashboardAllTrafficWidget`, `DashboardOverallPageMetricsWidget` and `ModulePopularPagesWidget` Analytics widgets.

## Changelog entry

* Ensure report requests are only made to the active Analytics module (UA/GA4).

**Comment by tofumatt** [comment]
ACs here are good 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
QA Update: ⚠️ 

@hussain-t I have come across a few issues that I'd like to highlight, but first let me share the steps I took:

1. Set up a new InstaWP site. 
2. Set up Site Kit with Analytics (this created UA and GA4 properties)
3. Set the feature flag to GA4Reporting
4. Switched to GA4 dashboard. Note, I did check that the dashboard was GA4, with the React developers tool.
5. Ran the database command to remove UA property `DELETE FROM iwpef42_options WHERE option_name = 'googlesitekit_analytics_settings';`

When I went to the dashboard  the errors appeared on the widgets `Data error in Analytics. Parameter viewId must be set.`
Along with console errors e.g. `Google Site Kit API Error method:GET datapoint:report type:modules identifier:analytics error:"Parameter viewId must be set."` When I looked at the network, I could see errors for `/google-site-kit/v1/modules/analytics/data/report` endpoint and no entries appeared for `/google-site-kit/v1/modules/analytics-4/data/report`

Please note that this same issue occurred when testing 6742 and I was told that this ticket would fix that. See my comment above this for details. 

This fails the QAB, but because sending it back to Execution, I'd like to make sure the steps I have taken are correct.

**Comment by hussain-t** [comment]
Hi @wpdarren, I have tested it locally and on an InstaWP instance. It works as expected. You will have to clear the session storage and refresh the page. My bad; I should have explicitly mentioned this in the QAB.

https://user-images.githubusercontent.com/24408261/229701700-1238a8cd-fa17-4d66-99b7-d50ae4bd4977.mov

**Comment by wpdarren** [comment]
@hussain-t this is still an issue for me, might be best to jump on a huddle but, I noticed on your screencast that you have data and in the QAB it says `Ensure Analytics is in Zero/Gathering Data state.` 

https://user-images.githubusercontent.com/73545194/229717225-ce3af5d8-b068-48cd-a6d9-5284990850c5.mp4

**Comment by hussain-t** [comment]
@wpdarren I can see your dashboard view is set to UA when the errors occurred. I tried with gathering data state, and it works for me.

https://user-images.githubusercontent.com/24408261/229722898-b071602c-f417-42c1-ac30-b970abbdc97f.mov

**Comment by wpdarren** [comment]
### QA Update: ✅ 

@hussain-t thank you for updating the QAB, this worked! 😄 

**Verified:**

- No report-related network errors are logged in the console.
- No network requests are made to the `/google-site-kit/v1/modules/analytics/data/report` endpoint; instead, it should be made to the `/google-site-kit/v1/modules/analytics-4/data/report` endpoint.
- No report-related network errors occur in the `DashboardAllTrafficWidget`, `DashboardOverallPageMetricsWidget` and `ModulePopularPagesWidget` Analytics widgets.

![image](https://user-images.githubusercontent.com/73545194/229739335-7993c95a-8e4b-4895-8256-b39832380b69.png)
