### ISSUE TITLE
Filtering OAuth credentials does not work with Proxy

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#676]
## Bug Description

As of #666, the Site Kit proxy service will be the default authentication mechanism for using Google APIs. For those who want to use their own GCP credentials (mostly for local development) these are still supported.

Because the UI for providing credentials will be removed, a filter is provided to allow for alternate credentials:
https://github.com/google/site-kit-wp/blob/683fb29c088b452bd841bcbd9f746804f002fb7e/includes/Core/Authentication/Clients/OAuth_Client.php#L775-L787

The problem is that this does not let the user proceed past the first step of the set up (providing credentials) because this is dependent on the `Credentials` class which is option-based.

https://github.com/google/site-kit-wp/blob/683fb29c088b452bd841bcbd9f746804f002fb7e/includes/Core/Authentication/Authentication.php#L547

So currently the only way Site Kit can work with GCP credentials is by filtering the option value itself with the _encrypted_ value of the credentials to use, which is not optimal. Also, this triggers the beta migration notice to appear on every page load as it is triggered by the detection of GCP credentials in the option value.

## Additional Context

As of `feature/auth-proxy` https://github.com/google/site-kit-wp/commit/683fb29c088b452bd841bcbd9f746804f002fb7e

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The JavaScript parameter `isSiteKitConnected` passed via PHP should be determined via the client credentials being present overall, not only inside the option.

## Implementation Brief

See POC https://github.com/google/site-kit-wp/pull/679

## Changelog entry

* Fix OAuth credentials not being handled correctly when not using the authentication proxy.

**Comment by felixarntz** [comment]
@aaemnnosttv Seeing the draft PR, I actually think it'd be safer to move the filter to the `Credentials` class. We cannot change the filter functionality, but we certainly can move it.

In other words, I suggest the following:
* Run the filter first thing in `Credentials::get()`.
* The filter signature should be exactly the same (expect a JSON string).
* If the output is not empty, try JSON-decode it and extract client ID and secret.
* If both client ID and secret were found, return those instead of looking up the DB.

This provides a cleaner solution (move filter to applicable logic), while not breaking backward-compatibility.

**Comment by adamsilverstein** [comment]
I QAed this with the `develop` branch since #666 was merged. Everything worked as expected, moving to Approval. I did notice one issue that deserves some additional testing, noted below.

### Testing Procedure
* Tested locally where we should be able to test the plugin using the OAuth credentials filter.
* Reset plugin.
* Add the following filter  to add credentials:
`add_filter( 'googlesitekit_oauth_secret', function() { return '[JSON from Hen House/App Console]'; } );`
* use the `googlesitekit_site_url` filter to map a domain with live data:
`add_filter( 'googlesitekit_site_url', function() { return [ DOMAIN ]; } );`

* Start the plugin setup flow, notice the expected authentication screen with 4 steps:

![image](https://user-images.githubusercontent.com/2676022/67302611-5fc8e900-f4ae-11e9-9780-ba6a192b327b.png)

* Sign in and go thru verification process (with previously verified domain)

![image](https://user-images.githubusercontent.com/2676022/67302949-eaa9e380-f4ae-11e9-9e0b-41ceb39edf15.png)

* Continue to Dashboard and note that data loads correctly.


### Issues noted
Once issue I noticed when opening my existing local setup - before resetting, I saw a notice:

![image](https://user-images.githubusercontent.com/2676022/67302213-cdc0e080-f4ad-11e9-9375-45e5283521e9.png)

when I clicked on "Reconnect Site Kit" I got an error message:

![image](https://user-images.githubusercontent.com/2676022/67302314-f517ad80-f4ad-11e9-83ea-409c84722457.png)

This may be related to my unusual local configuration and I don't think this blocks this issue passing QA, however I do feel we should try to do more upgrade testing with existing sites using the filter to make sure everything works as expected.
