### ISSUE TITLE
Google Tag settings are not saved when creating a new tag using Set up a new property in Analytics settings

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6767]
## Bug Description

This issue was discovered in Bug Bash by @mohitwp and @techanvil.

When creating a new Google tag as a result of selecting "Set up a new property" in the Analytics settings, upon creation of the property, the Google tag settings can be seen to be set, for example here in the JS console.

![image](https://user-images.githubusercontent.com/12189958/227263077-dce04abe-e261-4c35-a36c-71eafa1eb896.png)

However, refresh the page, and the settings vanish, either having become unset, or not being saved in the first instance:

![image](https://user-images.githubusercontent.com/12189958/227263128-d92af0fe-2cdf-4f00-8ffc-1f031e7b524c.png)

In this situation, there is no Google tag setting so the front-end will use the measurement ID in the gtag.

## Steps to reproduce

- Site up Site Kit with Analytics connected and the `gteSupport` feature flag enabled.
- Navigate to the Analytics settings page, select "Set up a new property" in the GA4 property dropdown, and press **Confirm Changes** (going through the OAuth flow if necessary).
- With the property created, while still on the settings view, call the `getSettings()` selector, where the Google tag settings can be seen to be set. However these do not appear to be persisted in the backend. Note, do not navigate to the Dashboard as this may trigger the Google tag sync.
```js
googlesitekit.data.select('modules/analytics-4').getSettings()
```
- Open the front-end of WordPress in a separate tab and view the source - the measurement ID will be used in the Analytics snippets, rather than the expected Google tag ID.
- Refresh the settings page and check the settings in the JS console again - the Google tag settings will no longer be set.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When GTE support is enabled, upon creating a new property in the Analytics settings page, the corresponding Google tag settings should be persisted.
* The new Google tag ID should be used in the Analytics snippets.
* Refreshing the settings page should show the Google tag settings have been persisted.

## Implementation Brief

* In `assets/js/modules/analytics-4/datastore/settings.js`:
    * Within the `submitChanges` function, add `await` before both the `dispatch` calls to `updateSettingsForMeasurementID`.

### Test Coverage

* No new tests required.

## QA Brief

- Site up Site Kit with Analytics connected and the `gteSupport` feature flag enabled.
- Navigate to the Analytics settings page, select "Set up a new property" in the GA4 property dropdown, and press **Confirm Changes** (going through the OAuth flow if necessary).
- Open the front-end of WordPress in a separate tab and view the source - the tag ID should be the new Google tag ID, not the Measurement ID we would use when GTE is not enabled.
- Refresh the settings page and check the settings in the JS console using `googlesitekit.data.select('modules/analytics-4').getSettings()` - the Google tag just created should be returned.

## Changelog entry

* Fix bug where Google Tag settings were not being saved when creating a new tag via the Analytics Settings page.

**Comment by tofumatt** [comment]
IB ✅

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@tofumatt 

I setup analytics a/c with 'gteSupport' feature flag enabled and "Set up New Property"  under analytics settings view. Now Google tag is getting save when we refresh settings page. 
But I've a question regarding below point mentioned under QAB-
`Open the front-end of WordPress in a separate tab and view the source - the measurement ID should be the new Google tag ID.`

Currently, when `gteSupport` feature flag is enabled and google tag starting with 'GT -'  also available, then that tag appear as Google Tag under source code instead of measurement ID. If we disabled `gteSupport` then only Measurement ID set as a Google Tag ID.  As I remember, this is the logic we are following. 
So, Are we going to set Measurement ID as a new Google ID when gteSupport Feature flag enabled and tag starting with 'GT-' is also available ?

<details>

when 'getSupport' feature flag is enabled -

![image](https://user-images.githubusercontent.com/94359491/229400158-3617ace7-4f07-4d2e-9949-7817724f0adf.png)

When `getSupport` feature flag is disabled

![image](https://user-images.githubusercontent.com/94359491/229400305-1f0016c4-8811-48ed-b7f2-49d8b0bd9ea8.png)

Settings view -

![image](https://user-images.githubusercontent.com/94359491/229400449-89cb418c-592c-4d54-844c-1daedbd10e9f.png)

</details>

**Comment by tofumatt** [comment]
@mohitwp It looks like what is happening there is correct—the GTE tag (eg the `GT-` tag) is being used when GTE Support is enabled.

When it's disabled, the Measurement ID is being used.

I've updated the QA Brief a bit to clarify that—the wording was admittedly a bit confusing 😅

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thank you ! @tofumatt 

- Tested on dev.
- Successfully created new property.
- Google tag settings is getting save when we create new property.
- Refreshing the settings page showing the newly created google tag when we check using `googlesitekit.data.select('modules/analytics-4').getSettings()`

<details>


https://user-images.githubusercontent.com/94359491/229486531-c1bf3a9a-3baa-4fe3-8a41-85e73ad6cb56.mp4

</details>
