### ISSUE TITLE
authentication error, error 403

### ISSUE THREAD

**Issue by srivastava903** [google/site-kit-wp#688]
## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@srivastava903 We will require some additional information in order to troubleshoot. There could be a number of reasons you are encountering this issue, such as a security plugin setting, hosting configuration, caching issue, browser extension or other cause. 

Please provide additional information, such as the following:
- Screenshot of the error
- Any [console errors](https://i.imgur.com/KyLAzgH.png) which may appear
- Your website URL 
- Your [Site Health info](https://i.imgur.com/Rtkmsba.png) from your WordPress dashboard?

**Comment by srivastava903** [comment]
sir my problem is not solved

**Comment by jamesozzie** [comment]
@srivastava903 If you were experiencing issues similar to that in #685 please check and see if there is any update available for the Site Kit plugin from your WordPress dashboard. 

If that does not resolve your issue we will require some more information from your side in order to troubleshoot, information as mentioned above.

**Comment by srivastava903** [comment]
sir my wordpress dashboard is fully updated i check it but problem is same
error 403It appears you don't have
permission to access this page.403 Error. Forbidden.

**Comment by jamesozzie** [comment]
Hi all, Site Kit support is now provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your questions or issues on there if your issue remains. Where we would be happy to assist from there
