### ISSUE TITLE
Chart key date info icon should be moved above the chart

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6910]
## Bug Description

As reported by @techanvil in Bug Bash:

The key date info icon can interfere with the chart data points, and should be moved above the chart as originally specced. See attached video.

![image](https://user-images.githubusercontent.com/12189958/233060781-0a43505a-fdde-4053-bbc3-191d7c5ca5ba.png)

https://user-images.githubusercontent.com/12189958/233060840-10beaa34-3516-4b9c-a330-64d3f05e076a.mp4

See https://github.com/google/site-kit-wp/pull/6822#issuecomment-1501968800 for more details.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "i" icon used by date markers in `LineChart` Google Charts should appear above the chart, not inside it.
* The "i" icon should not collide with any other chart legends, like the "Unique visitors" legend in the Search Funnel Widget:

![CleanShot 2023-04-20 at 19 12 05](https://user-images.githubusercontent.com/90871/233452214-b3fb190c-7bd0-4efc-ac0e-2839c40ee024.png)

## Implementation Brief

The only approach that's workable here, without manually re-implementing all of the Google Chart legends ourselves across the plugin (I don't recommend this approach!) is to find charts that _have_ a legend and modify the positions of the SVG legend elements so they are pushed above the date marker _when a date marker is present_. It's a bit hacky but seems to work reliably and not cause any issues.

* Change the [tooltip style](https://github.com/google/site-kit-wp/blob/543443820abc913a0bfc12ee6481177a8a17e16d/assets/js/components/GoogleChart/index.js#L306) to use a `top` value of <code>`${ Math.floor( chartArea.top ) - iconSize }px`</code>
* Add an instance ID to each Google chart (eg. <code>id={ `googlesitekit-chart-${ instanceID }` }</code>) so we can style the chart
* Add this code to the `addKeyDateLinesToChart` function in the `<GoogleChart />` component to style SVG legends when there is a legend rendered in the chart (which causes three `g` children to be present):

```js
const legendElement = document.querySelector(
			`#googlesitekit-chart-${ instanceID } svg:first-of-type > g:first-of-type > g > g > text`
		)?.parentElement?.parentElement?.parentElement;
		const hasLegend =
			document.querySelectorAll(
				`#googlesitekit-chart-${ instanceID } svg:first-of-type > g`
			).length >= 3;

		if ( hasLegend && legendElement ) {
			legendElement.style.transform = 'translateY(-10px)';
		}
```

### Test Coverage

* No new tests needed as this is a Google Charts component that is difficult to test.

## QA Brief

* Set up Site Kit with GA4 Reporting _not enabled_ and a site that has data.
* Load the All Traffic Widget on the main dashboard.
* In Site Kit settings, change Analytics to show UA data instead of GA4 data.
* Visit the Site Kit dashboard and set the reference date to be near the GA4 cutoff using the browser console with: `googlesitekit.data.dispatch("core/user").setReferenceDate('2023-07-27');`
* The All Traffic Widget's line graph chart's icon should appear above the chart and below the chart legend:
<img width="711" alt="CleanShot 2023-05-05 at 12 26 08" src="https://user-images.githubusercontent.com/90871/236445819-cac05214-df33-4872-84b2-cf4983e08cda.png">

* Scroll down to "Search traffic over the last 28 days" and activate the "Unique Visitors from Search" tab.
* The All Traffic Widget's line graph chart's icon should appear above the chart and below the chart legend:
<img width="1185" alt="CleanShot 2023-05-05 at 12 26 32" src="https://user-images.githubusercontent.com/90871/236445896-e1fba715-8423-4fc5-8421-8e59c1996d4f.png">

## Changelog entry

* Adjust positioning of key date info icon to avoid overlapping other elements.

**Comment by tofumatt** [comment]
Just a note: after IB review, please assign this issue to me as I have a proof-of-concept locally so this will be much faster for me to implement and test—it's also related to another Charts issue for GA4 I'm working on so it makes sense for me to handle both this and #6911.

**Comment by techanvil** [comment]
Hey @tofumatt, this IB is looking good; there are a couple of minor CR-style points I'd make, which I'll add here but then will move this to EB and you can consider them as part of the PR.

It's a pretty minor one, but regarding this snippet:  `parentElement?.parentElement?.parentElement`, I don't think we need these optional chaining operators, as if the `document.querySelector()` call returns an element it implies these `parentElement` properties will all be populated, and these operators add what I think is unnecessary line noise.

Secondly, we might want to "bail early" (in whatever form that may entail) if the `legendElement` doesn't exist rather than proceeding to query the document for `hasLegend`.

Anyway, both are pretty negligible issues that can happily be addressed in the PR.

IB :white_check_mark:

**Comment by mohitwp** [comment]
@tofumatt Just wondering do we need to show chart key date info icon also on Site kit widget under WP dashboard ? 

﻿
![image](https://github.com/google/site-kit-wp/assets/94359491/e3751a79-a6e5-4562-a431-501a5b05174c)

**Comment by tofumatt** [comment]
@mohitwp No, that wasn't part of the design, and while we _could_ include it there, it's already a bit cramped to be adding more info. I think it's fine to leave those icons in the main dashboard for now.

**Comment by tofumatt** [comment]
@mohitwp I think ElasticPress.io should have data for those charts, I recall it's what I used for testing this but I'm not 100% sure.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified The "i" icon used by date markers in LineChart Google Charts appearing above the chart, not inside it.
- Verified The "i" icon not colliding with any other chart legends, like the "Unique visitors" legend in the Search Funnel Widget.


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/0bb36da8-43d8-4178-b84f-fcb6cc645a75)

![image](https://github.com/google/site-kit-wp/assets/94359491/23f7f4f0-cf97-4edf-abe1-07ecb53735a0)

![image](https://github.com/google/site-kit-wp/assets/94359491/e3cc7520-a340-49c0-b688-27b037dc46ff)

</details>

@wpdarren Moving it to Approval because it meets AC. But, can you please have a look one more time with a site having chart data for data points, as you can see in attached screenshot by Tom in description.  Currently, I used oi.ie site, and it's not showing any chart data points under chart.

**Comment by aaemnnosttv** [comment]
LGTM 👍
