### ISSUE TITLE
Removal of permissions to a shared destination should be highlighted to the user

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6917]
## Description

As reported by @techanvil in Bug Bash:

To recreate this scenario, setup a Google tag which points to a shared destination (a property owned by another Google user that has been shared with the current Google user), and use this tag in Site Kit (select that property in Analytics settings).

Then, remove the permission for that property.

When the check for a change in Google tag mapping occurs, no notification is shown to the user, although an error is displayed in the JS console.

![image](https://user-images.githubusercontent.com/12189958/233092335-2a2218f3-f52c-4d81-988e-516dd01ae386.png)

Furthermore, the GA4 dropdowns are blank on the Settings page, with no error or other message displayed to the user, but another error in the console:

![image](https://user-images.githubusercontent.com/12189958/233092378-b105d44f-84b0-4e43-89ba-fdfa508d3038.png)

The tag setting itself is unchanged, with the gtag still added to the source code with the same tag ID.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment]
It turns out the console error seen on the Dashboard is actually a result of [this call](https://github.com/google/site-kit-wp/blob/bfd82b9dac98d7c91769c5f84dd5c70ac54b2981/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/UserCountGraph.js#L112) to `getProperty()` in the All Traffic widget, which handles the error gracefully. Furthermore, in this scenario, once the cached reports expire, the Dashboard will show the usual "Insufficient permissions" error in the widgets (see screenshot below). Therefore, as the user will be notified of the error, which should either prompt them to select a new property, or to restore their permission via the "Request access" error CTA, it doesn't seem necessary to add any additional Google Tag related functionality to the Dashboard to cover this scenario.

![image](https://github.com/google/site-kit-wp/assets/18395600/008cc775-d2a4-48a8-a521-1cee4e431a28)

Additionally, the insufficient permissions error _is_ now shown on the Settings page, so there's nothing that needs doing there either (see also https://github.com/google/site-kit-wp/issues/7360#issuecomment-1812513563):

![image](https://github.com/google/site-kit-wp/assets/18395600/a0b87f2a-9fda-4c9d-b39b-92b57df371e6)

As a result, this issue can be closed.
