### ISSUE TITLE
Match Top Earning Pages notification banner to Figma design

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6956]
## Description

Figma design: https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=1-3&t=zuyx88f5VSH3vbFl-0

Key differences:
1. The icon should be “i” and and not a star
2. Text alignment is off
3. Button isn’t vertically centered
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The GA4 version of the `Top Earning Pages` widget should be updated to match [the Figma design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=1-1168&t=2heHeS7Nbun75Fgi-0) exactly:
  - The icon should be changed to an info, e.g. `assets/svg/icons/info.svg`.
  - Custom CSS class should be assigned to its `<SettingsNotice />` component and styles should be added for it so that the typography and (vertical) alignment of the icon, text, and CTA matches [the Figma design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=1-1168&t=2heHeS7Nbun75Fgi-0).
  - `Earnings` should be removed as a column in the header.
- Any `<SettingsNotice />` component used in the Site Kit dashboard (any context) should not impose a maximum width, and should span the entire available horizontal space.
  - Instead, the text _inside_ these components should have a maximum width so that text does not span the entire length of the screen **when the screen is very wide**. This [preserves the readability of text](https://baymard.com/blog/line-length-readability).

## Implementation Brief

- In `assets/js/modules/adsense/components/dashboard/DashboardTopEarningPagesWidgetGA4.js`:
  - Remove the `Earnings` item from the `tableColumns` array.
  - To the `<SettingsNotice />` component:
    - Pass an `Icon` prop with an SVG component from `assets/svg/icons/info.svg` as value.
    - Pass a new CSS class to the `className` prop.
- In `assets/sass/components/settings/_googlesitekit-settings-notice.scss`:
  - Add the `max-width` of `1098px` to `.googlesitekit-settings-notice` only if it is inside the `#googlesitekit-settings-wrapper` element.
  - The `.googlesitekit-settings-notice__text` and `.googlesitekit-settings-notice__inner-row` selectors should have a `max-width` of `1098px`.
- Create a new SCSS file within `assets/sass/components/adsense` for the Top Earning Pages widget. In this file:
  - Add styles for the CSS class added to `DashboardTopEarningPagesWidgetGA4` `SettingsNotice` so that all the cells are vertically center aligned. Also, make sure the text typography of the notice matches the Figma designs.

### Test Coverage

- Update VRT references if required.
- No other tests need to be added/updated.

## QA Brief

- Set up Site Kit with Analytics and Adsense.
- Switch to the GA4 dashboard view.
- Verify that the Adsense Top Earning Pages widget in the Site Kit dashboard matches the Figma designs linked in the ACs.

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
ACs here are good, just needed a bit of expansion. Added, and moving to IB. 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

- Tested on dev environment.
- Verified design with [Figma](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?type=design&t=wunJDUX7iJWSUwbV-0)
- Verified star icon replace with 'i'.
- Verified earning column is removed.
- Also, tested banner design in mobile view ports.


@nfmohit 

**Suggestion** – In viewports having width between 700 to 800px. The 'i' icon is aligned with the button. Instead of this, can we align button with text without impacting design of other view ports ? 

![image](https://github.com/google/site-kit-wp/assets/94359491/2659e74c-a7dc-40a5-b946-834a226df487)


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/c22aebe6-7a8b-4211-80d6-236431da3c9c)

</details>

**Comment by nfmohit** [comment]
Thank you for your suggestion, @mohitwp!

I have set the columns to all wrap on all viewports under desktop, in a follow up PR #7104. I hope it looks better now.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@kuasha420 @nfmohit 

- Tested on dev environment.
- I verified the banner in viewports having width between 680px to 800px. But I'm getting the same result as I posted [above](https://github.com/google/site-kit-wp/issues/6956#issuecomment-1559056501).
- Did we change banner design for this viewport, as I'm not able to see any changes ?

<details>

Tablet (680-800px)

![image](https://github.com/google/site-kit-wp/assets/94359491/8118faf5-93a9-4c2f-86fd-cdb607ba5c6f)

Mobile view ports (<680px)

![image](https://github.com/google/site-kit-wp/assets/94359491/de58be12-9f70-458e-8d98-88dd738ba8c8)

Desktop 

![image](https://github.com/google/site-kit-wp/assets/94359491/ad9429b4-50cb-4e14-90e0-8c0d74ec5bec)

</details>

**Comment by nfmohit** [comment]
I just took a closer look at the final outcome of PR #7104:
![image](https://github.com/google/site-kit-wp/assets/20284937/fb9006f2-4078-4612-957a-4ff231d8397d)

@mohitwp & @aaemnnosttv please correct me if I’m wrong but I believe the expectation here regarding the responsive behaviour of the notice is that all three columns (icon, text, & action) should be in one row as long as possible. If it is not possible to fit all of them in one row, they all should be stacked over one another, based on [this proposed design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?type=design&node-id=1885-8269&t=qEQ8bOS1WR23htEc-0):
![image](https://github.com/google/site-kit-wp/assets/20284937/e7b00be8-06a2-415b-8800-1686e37379e8)

i.e. we'd want to avoid two columns being on one row, and one stacking under, as reported by @mohitwp [here](https://github.com/google/site-kit-wp/issues/6956#issuecomment-1559056501):
![image](https://github.com/google/site-kit-wp/assets/20284937/485e46a0-c23d-4d18-b949-dd4313d20238)

In #7104 initially, I tried to implement such a solution, but to do so perfectly, we'd have to add styles specific to very particular viewport widths, which I don't think we don't want because those would vary with the amount of text. Hence, I decided to go ahead with a solution where all the columns would reside in a single row for desktop viewports (i.e. above 960 pixels width), but stack on any viewports under 960 pixels width:
![image](https://github.com/google/site-kit-wp/assets/20284937/d33e89ae-1b81-4c0d-acfd-f4f574199162)

In this scenario, what do you folks think would be the appropriate way to proceed?
1. Leave it as it is.
2. Revert back to my initial solution.
3. Find a graceful solution where the columns do not stack when they fit in one row, but when they do stack, they all stack together (I have spent quite a while trying to figure this out, but couldn't).

Thank you!

**Comment by tofumatt** [comment]
@nfmohit Oh, thanks, you're right. That one mobile view way off to the side/end of the designs wasn't at all obvious to me. I had assumed the style was meant to be similar to the desktop version. 😞

I don't have a strong opinion. My first thought is that, generally, you have less width than height on mobile viewports, so giving the text more width by using the design in Figma (eg. the "i" icon is on a line above the text) is good.

But then looking at the actual content no more text really fits in anyhow.

We should probably just do exactly what's in this Figma design specifically (thanks for the link @nfmohit): https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?type=design&node-id=1885-8394&t=XtcXT46Y0WSze7m6-4

Sorry for missing that, I'll move this back to Execution.

**Comment by kuasha420** [comment]
Hmm, admittedly I also missed the mobile Figma design, and interpreted @mohitwp's suggestion as align the button to the text instead of icon which looks better in my opinion. The icon being all lonely in it's own row doesn't sit right with me for some reason, because the icon is somewhat meaningless without the accompanying text. 

However, giving the text as much horizontal space as possible makes sense to me in very very small viewports, so I'm not against the idea. 

Just my two cents.

**Comment by mohitwp** [comment]
>
> @mohitwp & @aaemnnosttv please correct me if I’m wrong but I believe the expectation here regarding the responsive behaviour of the notice is that all three columns (icon, text, & action) should be in one row as long as possible. If it is not possible to fit all of them in one row, they all should be stacked over one another, based on [this proposed design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?type=design&node-id=1885-8269&t=qEQ8bOS1WR23htEc-0):
> 
> ![image](https://user-images.githubusercontent.com/20284937/242434191-e7b00be8-06a2-415b-8800-1686e37379e8.png)
> 
> i.e. we'd want to avoid two columns being on one row, and one stacking under, as reported by @mohitwp [here](https://github.com/google/site-kit-wp/issues/6956#issuecomment-1559056501):
> 
> ![image](https://user-images.githubusercontent.com/20284937/242434283-485e46a0-c23d-4d18-b949-dd4313d20238.png)
> 
> In #7104 initially, I tried to implement such a solution, but to do so perfectly, we'd have to add styles specific to very particular viewport widths, which I don't think we don't want because those would vary with the amount of text. Hence, I decided to go ahead with a solution where all the columns would reside in a single row for desktop viewports (i.e. above 960 pixels width), but stack on any viewports under 960 pixels width:
> 
> ![image](https://user-images.githubusercontent.com/20284937/242434439-d33e89ae-1b81-4c0d-acfd-f4f574199162.png)
> 
> In this scenario, what do you folks think would be the appropriate way to proceed?
> 
> 1. Leave it as it is (first screenshot).
> 2. Revert back to my initial solution (fourth screenshot).
> 3. Find a graceful solution where the columns do not stack when they fit in one row, but when they do stack, they all stack together (I have spent quite a while trying to figure this out, but couldn't).
> 

@nfmohit My expectation is that either we achieve same design as we implemented for mobile. Else if it is not possible  to stack all 3 columns over one another for the viewport (680-700px) then it will be good if we stack button below text and align it with text. Currently, it is aligned with "i" icon.
For example -

![image](https://github.com/google/site-kit-wp/assets/94359491/a188d5cd-5a8a-4e4f-89bb-ea47c5c8ab68)

cc @kuasha420

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified notification banner on all view ports.
- Issue related to banner not showing as per Figma design in view ports having width between 680px to 700px is now resolved.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/b7b5ee64-df4a-4d26-9c45-12c73d165daa)

![image](https://github.com/google/site-kit-wp/assets/94359491/02f473e1-7a73-4063-a02b-d22397e9b72b)

![image](https://github.com/google/site-kit-wp/assets/94359491/c63b71bf-915b-44e5-befe-476edb3b8630)

</details>
