### ISSUE TITLE
GA4 feature tour get dismissed when "Top content over the last 28 days" widget is not loaded.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#7031]
## Bug Description

I've noticed that after loading the main dashboard if user do not scroll down to "Top content over the last 28days" widget and clicks on Ga4 notification banners – Update or Learn button then Ga4 feature tour get trigger. This feature get dismissed when user clicks on next because "Top content over the last 28 days" widget is still loading where feature tour next steps will appear. Posting here if we can enhance user experience in this case.

## Steps to reproduce

1. Set up site kit with 'ga4Reporting' feature flag.
2.  Go to main dashboard. Dashboard view should be UA.
3.  Do not scroll down.
4. Click on 'Update' button under banner.
5. This will trigger ga4 feature tour.
6. Now click on next.
7. Notice feature tour will get dismissed because "Top content over the last 28 days" widget is not loaded.

## Screenshots

https://github.com/google/site-kit-wp/assets/94359491/f06250e2-5e33-44a3-8002-2323ec4fca70

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Feature tours should only be dismissed by the following user interactions:
	* when completing the tour by clicking "Got it"
	* closing the tour by clicking the "X"
* A tour that ends without completing, due to a missing element for a step should not cause the tour to be dismissed automatically

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment]
Thanks for raising this, @mohitwp.

From your description, for the "Update dashboard" case it sounds like the "Top content" widget not being in-view to preload is actually biting us here, contrary to what I thought while implementing #6909. In hindsight I should have tested with network throttling enabled. So it looks like we may need to address the in-view preloadability now after all. I think this should be relatively straightforward, at a guess we'll need to make `useInViewSelect()` aware of the current module slug so it can check if it's currently in the preload state. However we'll need to verify what's going on here - there could be another cause/solution.

However when it comes to the "Learn more" scenario, we aren't able to preload anything there as the widgets are already on the page, although their in-view should be being forced, so maybe it's just taking a while to load.

Maybe we should take a the approach of disabling the CTAs until the widgets are visible... Or we could flip back to @eugene-manuilov's proposal of reorganising the loading state for the widgets, although it would be nice to avoid another reversal.  :thinking:

**Comment by aaemnnosttv** [comment]
I'm not sure this is a P0 since the tour only disappears if the user actions it right away (in which case they probably aren't interested in what it says anyways). We have a similar issue for the dashboard sharing tour here https://github.com/google/site-kit-wp/issues/6703 (also a P0, but again, it's not exactly the same as the dashboard crashing, just a bit unexpected/undesirable experience.)

This is a matter of timing – it doesn't crash going to the second step every time. As @techanvil mentioned, the component is loading while the tour is launched and so it works normally when you take the time to read what the first step says (at least in my experience). 

As such I'm going to downgrade the severity here – particularly since we have persistent "New" badges on all the same points as the tour's steps with tooltips so the user will not miss anything even after dismissing the tour.

One way forward that we could take here would be to simply avoid dismissing a tour when it crashes – tours should only be dismissed by a completion action (clicking "Got it" at the end or closing it "X"). This would result in the user seeing the tour again later, at which point they will either get farther or dismiss it. This would be good to do for all tours, not just this one.

**Comment by aaemnnosttv** [comment]
After further review, I found that the tour will consistently break when going to the second step of the tour, but only from the `SwitchedToGA4Banner` case because it doesn't force the dashboard into view in the same way the `SwitchGA4DashboardViewNotification` does.

I'll follow-up with this detail on https://github.com/google/site-kit-wp/issues/6558 since this is more specific to that issue.

**Comment by aaemnnosttv** [comment]
Closing this out as the issues here related to the GA4 reporting tour specifically will be resolved in a few follow-up PRs to #6558 and #6909. The remaining underlying issue with feature tours has a new issue #7036 specific to that, as it applies to all tours.

**Comment by techanvil** [comment]
Thanks for the investigation and followup here @aaemnnosttv!
