### ISSUE TITLE
Allow specific module settings to be available in a view-only context

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7114]
## Feature Description

Most module settings are not needed on the client side of the SK dashboard as most are only relevant for the initial setup/connection. Reading module settings on the client requires either `SETUP` or `MANAGE_OPTIONS` capabilities as required by the REST route.

With dashboard sharing, only admin view-only users have the necessary capability to access module settings (due to `SETUP` only). This means that all module settings are unavailable to all other view-only users.

While we don't want to loosen the capability required to access all module settings, we should allow specific settings (e.g. `dashboardView`) to be readable on the client in a view-only context.

_Note: [a workaround](https://github.com/google/site-kit-wp/pull/6872/files#diff-fd0d1b4a1cb0416c9df3564b6b7d69870d87563b32b6a187084c8c73f4a141c3) has been implemented for the case of Analytics’ `dashboardView` by passing the initial value through via dashboard sharing settings but the underlying issue has affected other settings as well so we should see about how to allow for more flexibility here._

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* It should be possible for module settings to be able to opt-in to provide a subset of specific keys that are available to users who can view the dashboard, but otherwise lack the capability to manage settings
* The API for accessing these settings on the client should not be changed
* For modules that do not opt-in to this behavior, there should be no change 
* Any workarounds which have been introduced for this purpose should be removed

## Implementation Brief

* A new `Setting_With_ViewOnly_Keys_Interface ` interface should be created that has a single `get_view_only_keys() : string[]` method that returns an array of setting key names (like `get_owned_keys`) that are available
* A new `Setting_With_ViewOnly_Keys_Trait` trait should be created to implement the interface
	* define the required function by the interface `abstract public function get_view_only_keys();`
	* Add the method `get_view_only_settings()`, which returns a subset of the settings keyed by the result of `get_view_only_keys()`. Note that the settings can be assumed to be retrieved via `$this->get()`
* No need for this trait to be used yet, as it will be implemented in later issues where needed, like #7598
* Go to `includes/Core/Modules/REST_Modules_Controller.php` and edit the `modules/(?P<slug>[a-z0-9\-]+)/data/settings` rest route, it needs a slight modification:
  * in the `callback` add for anonymous function to use `$can_manage_options`, and include additional conditional response - which will check if user `! $can_manage_options()` and module opted in to include `get_view_only_settings` method, and add that block  before the current response return:
```php
$settings = $module->get_settings();
if ( $settings instanceof Setting_With_ViewOnly_Keys_Interface &&  !  $can_manage_options() ) {
	return new WP_REST_Response( $module->get_settings()->get_view_only_settings() );
}
```
  * Wrap the current response return in conditional check to see if use do have `$can_manage_options()` permission
  * In the final `else` check if none of above is met, return empty array in the response - so users with view only permissions accessing the module not of the `Setting_With_ViewOnly_Keys_Interface` instance, will not receive any data

  * Then edit the `permission_callback` to check if user either have `VIEW_DASHBOARD` or `VIEW_SHARED_DASHBOARD` permission
* This way read only settings will be exposed to lower capability users, while admins get the full settings.

### Test Coverage

* Add test for new `Setting_With_ViewOnly_Keys_Trait` trait. And maybe include permission check for non admin users calling for read only options in `tests/phpunit/integration/Core/Permissions/PermissionsTest.php` .

## QA Brief

* Ensure that new tests `tests/phpunit/integration/Core/Modules/REST_Modules_ControllerTest.php` and `tests/phpunit/integration/Modules/Analytics_4/Settings_ViewOnly_TraitTest.php`, which cover all scenarios for `view-only` implementation, pass. As well as all other php tests.
* For manual verification if needed, as backup - implement `Setting_With_ViewOnly_Keys_Trait` and `Setting_With_ViewOnly_Keys_Interface` on Analytics 4 settings `includes/Modules/Analytics_4/Settings.php` and add `public function get_view_only_keys()` returning one key of your choice. Then share dashboard for analytics 4 and search console modules with one user, `editor` role for example, and after logging in with that user, print `console.log(googlesitekit.data.select('modules/analytics-4').getSettings())` in the console log, it will send a request to the `settings` endpoint, returning only `view-only` settings. Then print `console.log(googlesitekit.data.select('modules/search-console').getSettings())`, the settings request should return empty array since this module does not have `view-only` implementation. And when you log in as admin, these modules should return full settings list.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
Please assign this to me for IBR – thanks 👍

**Comment by zutigrm** [comment]
@aaemnnosttv `dashboardView` was removed as part of the UA removal issue just recently. Maybe you can suggest another setting that can be exposed in initial implementation in the AC ?

**Comment by aaemnnosttv** [comment]
Thanks @zutigrm! The IB seems to be mostly there, but please avoid adding code snippets as per the guidelines.

> * Go to `includes/Core/Modules/REST_Modules_Controller.php` and edit the `modules/(?P<slug>[a-z0-9\-]+)/data/settings` rest route, it needs a slight modification:
>   
>   * in the `callback` add for anonymous function to use `$can_manage_options`, and include additional conditional response - which will check if user `! $can_manage_options()` and module opted in to include `get_read_only_settings` method, and add that block  before the current response return:

We only want to modify the permissions for the `READABLE` variant of the handler, so I think we can update the check that the user can `VIEW_DASHBOARD` or `VIEW_SHARED_DASHBOARD` – we shouldn't need to do anything else for determining if permissions are satisfied.

In the callback handler, we'd determine which method to call to populate the response with based based on the user's capabilities (i.e. whether or not they can `{$can_manage_options as of today}`), in addition to the `Settings` instance (see below)

> method_exists($module->get_settings(), 'get_read_only_settings')

This is what the interface is for, so if we want to rely on it for any instance of this then let's add it to the interface so that we can simply check `$settings instanceof Setting_With_ReadOnly_Keys_Interface`

> `dashboardView` was removed as part of the UA removal issue just recently. Maybe you can suggest another setting that can be exposed in initial implementation in the AC ?

Correct – There will be other instances for this (e.g. `adsenseLinked` when we add it to GA4), but this should be something we can cover/verify in the unit tests – even if that means we create a dedicated instance for testing it – it shouldn't be blocked by a "real" use in the current module settings.

**Comment by zutigrm** [comment]
@aaemnnosttv thank you for the feedback. I updated IB - lowered the snippets, and included suggested permission check. And added step to return empty array as response if view only user is trying to access `settings` for module that is not opted-in for read only settings.

**Comment by techanvil** [comment]
Hey @zutigrm, I can provide a bit of feedback before @aaemnnosttv takes another look.

- In the spirit of avoiding code snippets in IBs where unnecessary, I think you can further reduce the use of code snippets.
- Instead of the snippet that lists `get_read_only_settings()`, you can instead specify this method name in the description. I'd suggest rewriting the following point, e.g.:
  - ~~Include a method that will take the available settings, and the `read_only_keys` and return only read only settings that view only users will be able to receive:~~
  - Add the method `get_read_only_settings()`, which returns a subset of the settings keyed by the result of `get_read_only_keys()`. Note that the settings can be assumed to be retrieved via `$this->get()`.
- I would suggest that we don't actually need to add the interface/trait to `includes/Modules/Analytics_4/Settings.php` just yet as it won't be used - and I'd imagine it's not going to provide much value to add tests for it to the `Analytics_4` tests at this point. Rather, we should leave the Analytics-specific aspect to be implemented in #7598 (maybe add a note in a comment on that issue), and we can instead add tests for the trait in this issue - we already have PHPUnit tests for a number of traits.

Arguably the final code snippet could be removed and the detail of using `instanceof Setting_With_ReadOnly_Keys_Interface` added to the point above it, but I think this minimal code snippet is OK all things considered.

---

There is, though, one further point, and we might want to get @aaemnnosttv's thoughts on this one.

Having taken a look at this issue again, the same thought I had the first time round has come back, but a bit more fully formed this time.

Essentially, I think the suggested naming of "read only keys" could be a bit confusing. To me, it suggests that we're putting some sort of overarching read-only access control on these particular keys, which could be a bit confusing when seeing their values updated in a non-sharing scenario. And it would require digging into the code to get an understanding that the intent is for them to be accessible when the module is shared.

I would suggest that we modify the naming here, maybe referring to "shareable keys" instead? Or maybe "shareable read only keys" to open up the possibility of adding "shareable writable keys" in the future.

@aaemnnosttv, I know this was originally your proposal for the naming, what do you think about the above?

**Comment by zutigrm** [comment]
@techanvil Thank you. I updated the IB, will wait for input from @aaemnnosttv regarding the `read only` keys naming change, to know how to proceed.

**Comment by aaemnnosttv** [comment]
> Essentially, I think the suggested naming of "read only keys" could be a bit confusing. To me, it suggests that we're putting some sort of overarching read-only access control on these particular keys, which could be a bit confusing when seeing their values updated in a non-sharing scenario. And it would require digging into the code to get an understanding that the intent is for them to be accessible when the module is shared.
> 
> I would suggest that we modify the naming here, maybe referring to "shareable" or "view-only" keys instead? Or maybe "shareable read only keys" to open up the possibility of adding "shareable writable keys" in the future.

@techanvil the naming follows that used for owned keys (`Setting_With_Owned_Keys_Interface`), but perhaps this is different enough that it doesn't need to follow that (it's just a name afterall). As for the terminology, I think "view-only" would be more appropriate rather than "shareable" since this is more about the user's capabilities than sharing, even though that's of course a necessary factor. After some additional thought, I think "view-only" makes more sense in general since that is more clear as to the context it relates to, where as "read-only" could imply that there are some settings that cannot be changed (which wouldn't make much sense if it applied globally). I'll update the AC 👍

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
Moving this to approval since there is nothing to QA yet.
