### ISSUE TITLE
Data Stream ID not showing up in dropdown list

### ISSUE THREAD

**Issue by PasqualePuzio** [google/site-kit-wp#7200]
## Bug Description

We have correctly configured a GA4 property and previously linked a web data stream through the Site Kit plugin. However, everytime we try to edit settings, the data stream we've just created is not showing up, the only option available is to create a new one.

## Steps to reproduce

Just open the settings screen of the Site Kit plugin and try to edit Google Analytics 4 settings.

## Screenshots

<img width="1410" alt="Screenshot 2023-06-23 at 12 39 08" src="https://github.com/google/site-kit-wp/assets/7646303/1aa71301-ce6d-48a0-9db8-44da0d17b02e">

<img width="1370" alt="Screenshot 2023-06-23 at 12 38 16" src="https://github.com/google/site-kit-wp/assets/7646303/4ee3a6b7-b038-454a-a77b-b1029f4ee87a">

<img width="1219" alt="Screenshot 2023-06-23 at 12 38 47" src="https://github.com/google/site-kit-wp/assets/7646303/94d775cd-ec64-482b-9aae-3a7478dd5399">

## Additional Context

- WordPress version: 5.3.3
- PHP Version: 7.4.13
 - OS: Mac OS
 - Browser: Chrome
 - Plugin Version: Latest version
 - Device: MacBook Pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment]
@PasqualePuzio Thanks for getting in touch. Unfortunately we don't provide support via GitHub but we would be more than happy to assist you if you could [open a new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0) with us.

We have also recently had a [similar report](https://wordpress.org/support/topic/site-kit-not-detecting-data-steam-error-requested-entity-already-exists/) to yours recently in the support forum so I would suggest first checking this to see if it provides you with the answers you are looking for. Otherwise we will see you in the support forum, Thanks!
