### ISSUE TITLE
Analytics page blank when attempting to connect

### ISSUE THREAD

**Issue by webspacesau** [google/site-kit-wp#733]
## Bug Description

After updating to RC2 and reauthenticating my Google account, the analytics module was still not connected and needs to be setup again. After clicking to setup I am shown a blank page.

## Steps to reproduce

1. Follow instructions to setup service from either the dashboard or clicking the Analytics option from the settings sidebar.
2. It appears to flash a loading bar for a split second but then stops and a blank page is shown.

## Screenshots

![image](https://user-images.githubusercontent.com/32596056/67731687-c6b54780-fa44-11e9-88c8-eb1cd555376b.png)

## Additional Context

 - PHP Version: 7.3
 - OS: Ubuntu (server), Windows 10 (desktop)
 - Browser: Chrome
 - Plugin Version [e.g. 22] Rc2
 - Device: Windows 10

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@webspacesau Looking at your screenshot I can see you are using an Analytics plugin active, which may be impacting setup. Can you please attempt the steps below in order to get Site Kit connected:
1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate any caching plugins you might have active
3. Temporarily deactivate the Updraft plugin and the Analytics module which you have active
3. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png)

If the above fails to resolve your issue can you please share the following:
- Any [console errors](https://i.imgur.com/KyLAzgH.png) that appear
- Your WordPress [Site Health information](https://i.imgur.com/Rtkmsba.png)
- Any security plugins or software in use (ModSecurity, iThemes, WordFence etc)

**Comment by webspacesau** [comment]
Hi @jamesozzie , which Analytics module/plugin do you see that I have active? As far as I know I am only using Site Kit within WP for Analytics

**Comment by jamesozzie** [comment]
@webspacesau I can see an Analytics [tab](https://i.imgur.com/Vfn9E8Z.png) from the screenshot you shared, maybe that is coming from another plugin you have active, or maybe it is not related to Google analytics. 

Did you have any luck setting up Site Kit after following the other suggestions?

**Comment by webspacesau** [comment]
@jamesozzie Ahh I see what you're seeing, that is the Analytics tab for Woocommerce, not GA related :) I've reinstalled as per your instructions and appears to be working again. Not sure if it was caching relating or due to Updraft. I had only recently re-enabled Updraft after seeing #612 as resolved for rc2.

**Comment by antoniomanco** [comment]
Hello, the latest Google Site-Kit WP update has a serious compatibility issue with the WP-Optimize 3.0.13 plugin that is widely used to optimize high traffic sites. Not only is it about installing or updating Google Site Kit, but both plugins can't work well together. Is there any way to fix this? Thank you

**Comment by aaemnnosttv** [comment]
@antoniomanco please open a new issue regarding the incompatibility with WP-Optimize (including as much detail as possible) and we'll take a look. Thank you!

**Comment by jamesozzie** [comment]
Hi all, Site Kit support is now provided on the WordPress [plugin forum](https://wordpress.org/support/plugin/google-site-kit/), could you post your questions or issues on there if your issue remains. Where we would be happy to assist from there
