### ISSUE TITLE
Implement "+ Add a metric" CTA widget tile

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7336]
## Feature Description

In the case when a user picks their own metrics but selects either 2 or 3 metrics, there will be 2 or 1 empty space(s) in the Key Metrics widget area respectively. These spaces should be 'filled' in by a "+ Add a metric" CTA as per the [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=1955%3A83677&mode=dev).

<img width="1191" alt="Screenshot 2023-07-19 at 14 13 55" src="https://github.com/google/site-kit-wp/assets/1721319/68fba47e-8e73-4500-af7b-bbaa4ba8d9a8">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If only 2 or 3 Key Metric widget tiles are selected by the user, then a new "+ Add a metric" CTA tile should 'fill' up the empty spaces as per the Figma mock.
* The Figma mock shows varying widths for this CTA - however, these CTAs should be the standard "quarter" width and take space for one tile. 
    * If there are 2 metrics selected, there will be two equal width "+ Add a metric" CTA tiles.
    * It there are 3 metrics selected, there will be one "+ Add a metric" CTA tile.
* Clicking anywhere within this tile will have the same effect as clicking on the “Change Metrics” button which will slide out the available list of metrics that can be added by the user.

## Implementation Brief

- Create `assets/js/components/KeyMetrics/AddMetricCTATile.js`. In this file:
  - Export a component with the same name.
  - It should accept a `Widget` component as prop.
  - Using the `Widget` prop component, construct the `Add a metric` widget according to the Figma designs.
  - The entire widget should ideally be a clickable button, clicking on which should open the Metrics Selection Panel.
    - The Metrics Selection Panel is being implemented in #6258.
    - As of now, it uses a `CORE_UI` store key to track the opened state of the panel. To open the panel, it sets the value of [`KEY_METRICS_SELECTION_PANEL_OPENED_KEY`](https://github.com/google/site-kit-wp/blob/67cd6fa19a49c20a9fb459930d7a0df30fe4742c/assets/js/components/KeyMetrics/constants.js#L20-L21) to `true`.
  - The widget should be implemented exactly/as close as possible to the Figma designs.
- In `assets/js/googlesitekit/widgets/register-defaults.js`:
  - Towards the end of the file, check if the `userInput` feature flag is on.
  - If so, register two widgets similar to how it is done for `keyMetricsSetupCTA` (use the same properties, differences are highlighted below).
  - The slugs of the two new widgets can be `keyMetricsAddMetricFirst` and `keyMetricsAddMetricSecond` respectively.
  - Their `Component` property should be the newly created `AddMetricCTATile`.
  - Their `width` property should be `WIDGET_WIDTHS.QUARTER`.
  - Their `priority` property should be `2` (so that they appear after any other key metric widgets).
  - Use the `isActive` property to restrict their visibility.
    - The `isActive` function exposes a `select` as its first parameter, using which you can get the set key metrics (`CORE_USER` `getKeyMetrics` selector).
    - If the selector returns a non-array value, return `false`.
    - Otherwise:
      - For the first widget, return `true` if the length of the returned array is less than 3.
      - For the second widget, return `true` if the length of the returned array is less than 4.

### Storybook

- Add a Storybook story for the `AddMetricCTATile` component.

### Test Coverage

- Add VRT scenarios for the `AddMetricCTATile` component.
- Add test case(s) for the `AddMetricCTATile`, for example, verifying its click handler.

## QA Brief

- Set up Site Kit and enable the `userInput` feature flag.
- When the KM setup CTA notification shows up, click on `I'll pick metrics myself`.
- Select two metrics and save changes.
- Verify that the KM widget area shows two of the new `+ Add a metric` CTA widget tile.
- Click on the widget tile and verify that it opens the Metrics Selection Panel.
- Select one more metric and save changes.
- Verify that the KM widget area now shows one `+ Add a metric` CTA widget tile.
- Select one more metric and verify that you no longer see the CTA widget tile.
- Verify the `Key Metrics / AddMetricCTATile` Storybook story.

## Changelog entry

* Add a Key Metric tile that allows users to add more tiles to the Dashboard.

**Comment by aaemnnosttv** [comment]
@jimmymadon from what I recall there would only be 1 `+` tile since this would open the selection pane for all tiles not just the one clicked for the CTA which would likely be unnecessarily extra effort and less efficient from the user's perspective in the case where 2 are empty. 

Additionally, we probably don't want to allow for the `+` tile to be in between widgets, but always at the end (as in the design). Ideally one of the other metric tiles would expand to a half size in the event that only 2 metrics were selected rather than a double-wide `+` tile.

**Comment by aaemnnosttv** [comment]
SGTM, we can keep the `+` tiles separate for now. I still don't think the layout is launch blocking when there are 2. Perhaps we could change the KMW registrations to allow 1/4 or half so that we'd never have one that was 3/4 wide?

I find it a little odd from a UX perspective that the user is offered the ability to choose 2-4 metrics, but will see a `+` "CTA" if less than 4 are selected. That together with the action being the same as the link which is already present to do the same thing seems like there may be room for improvement.

AC ✅

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@nfmohit as per our chat on Slack. 

While writing up my bug bash instructions I noticed that the 'Add Metric' tile appears underneath the User Input banner CTA even when the user has not completed the questions. The Add Metric Tiles should only appear when KMW is already set up.

![image](https://github.com/google/site-kit-wp/assets/73545194/d491ea73-dd55-43f5-8bbc-cdbaa41e3608)

**Comment by nfmohit** [comment]
Thank you for the observation, @wpdarren. I've added PR #7418 to address this, thanks!

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@nfmohit I have an observation on how these 'Add a metric' tiles appear on dashboard sharing. 

When I have 1 or 2 'Add a metric' tiles on the main dashboard.  I go to Dashboard sharing as a non admin, i.e. Editor, and view the view only dashboard and none of the tiles appear. I was expecting two tiles to appear with data.

I am assuming that this is not expected. 

This is what I see on main dashboard as an Admin
![image](https://github.com/google/site-kit-wp/assets/73545194/fe078a71-3e57-4f83-a732-87805180027f)

This is what I see on view only dashboard as an Editor. No tiles appear. 
![image](https://github.com/google/site-kit-wp/assets/73545194/e289f56c-67b8-4462-a965-2f46d950725f)

**Comment by wpdarren** [comment]
QA Update: ✅ 

**Verified:**

- The KM widget area shows two of the new + Add a metric CTA widget tile.
- The KM widget area now shows one + Add a metric CTA widget tile.
- The Key Metrics / AddMetricCTATile Storybook story.
- Issue [reported above](https://github.com/google/site-kit-wp/issues/7336#issuecomment-1670825812) is fixed.

Note: the issue reported re Dashboard Sharing will be fixed in 7349 as per Jimmy's comment above. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/6374cb18-d762-44e6-ad13-3dd9abde3462)
![image](https://github.com/google/site-kit-wp/assets/73545194/ed52145b-87a2-4509-8125-56d1c21f3ad1)
![image](https://github.com/google/site-kit-wp/assets/73545194/d975d5a9-2717-4019-9f38-5c7067fc861e)

</details>
