### ISSUE TITLE
Accessibility labels for Site Kit links on the admin toolbar

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#7343]
## Bug Description

Review the plugin for any possible accessibility additions for the admin toolbar and where possible any internal links within the plugin dashboard (where possible). 

This was [highlighted by a user in the support forums](https://wordpress.org/support/topic/links-do-not-have-a-discernible-name-12/). 

## Screenshots

**_The Site Kit tab on the admin toolbar_**
<kbd> ![image](https://github.com/google/site-kit-wp/assets/41326532/8359894b-92f5-4542-b342-2266c2c87277)

**_wp-admin menu - Controlled via WP (I don't see any [option to provide additional accessibility features](https://codex.wordpress.org/Administration_Menus) from here)_**
<kbd> ![image](https://github.com/google/site-kit-wp/assets/41326532/e9591153-f5ec-4eee-97c1-f36f64b9c062)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
From my usage in VoiceOver for macOS, there is a description for this link in that the link contains content that is read out by the screen reader:

https://github.com/google/site-kit-wp/assets/90871/8c4d71cf-3815-4afe-807a-bd6de7943700

I'll wait to see what the user in the forums says they're using as a screenreader, but our link is in basically the same format as the other WordPress admin bar links, so if ours isn't being read none of the others would be.

Using a `name=` attribute there wouldn't be appropriate, but an `aria-label` might be. That said, no other item in the menubar uses aria-labels, they just rely on the link content the same as us:

![CleanShot 2023-07-21 at 17 49 24](https://github.com/google/site-kit-wp/assets/90871/0965bfeb-707c-47fe-a526-f304831d38ba)

Not sure the issue here is valid, but I'll wait to see what software the user in the forum is using to try to replicate their issue.

**Comment by jamesozzie** [comment]
@tofumatt Just to let you know that there's been [no update from the user who reported this](https://wordpress.org/support/topic/links-do-not-have-a-discernible-name-12/#post-16997700) when asked about the screen reader in use, nor other mentions of this in the support forums.

**Comment by tofumatt** [comment]
I'm going to close this one as invalid/won't fix, as we do have text/labels for these elements so I don't think anything needs adding/changing here.
