### ISSUE TITLE
Display "Change Metrics" Feature Tour tooltip when widget is setup by another Admin

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7346]
## Bug Description

If Admin1 answers the User Input questionnaire, the Key Metrics widget is considered set-up “site wide” for all other users of the site. The answer to the first question is stored “site-wide”. However, we decided in the design doc that “any other authenticated admin, who has not taken the User Input questionnaire, will be shown the [Setup CTA](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.kgse0j7btyc2) to take the questionnaire. If they dismiss it, the same [Dismissal flow](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.snxtf0ab56zj) will apply.” This means that if Admin2 logs in, they will see both, the Setup Banner CTA and the Key Metric widget tiles as in the attached screenshot which is not good UX! I understand the idea was to get all authenticated admins of the site to answer the questionnaire and we did conclude that if another admin changes the answer to question 1, the Key Metric tiles will change for all users of the site who have not picked their own metrics. But we probably want to think more about the UX/UI here and the flow. We would have to change the banner to say something like “Another admin has already answered questions on your site goals but you can review them…etc”

## Steps to reproduce

1. Login as admin1 and setup the Key Metrics widget by answering the user input questionnaire.
2. Verify that the Key Metric widget is showing some key metric widget tiles for admin1.
3. Now login as admin2. Both the Setup Banner CTA and the widget tiles are displayed.

## Screenshots

<img width="1389" alt="Screenshot 2023-07-21 at 11 05 15" src="https://github.com/google/site-kit-wp/assets/1721319/54d3ac81-368a-4356-8dae-037823fe8ab3">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If any user (authenticated or view-only), other than the admin who "sets up" the Key Metrics widget logs in, they should see a new Feature tour with a single step highlighting the "Change Metrics" link within the Key Metrics widget area when it is first rendered.
* The feature tour should be rendered only once and should be dismissable by either clicking the "X" button in the corner or the `Got it` dismissal CTA.
    * Feature tour title: `Personalize your key metrics`
    * Feature tour text: `Another admin has set up these tailored metrics for your site. Click here to personalize them.` 
    * Feature tour dismiss CTA: `Got it` 
* The first admin to answer the User Input questionnaire or pick their own metrics should be considered as the user who set up the KMW.

## Implementation Brief

* Change the `key_metrics_setup_complete` setting from a boolean to a number (`key_metrics_setup_completed_by_user_id`) that saves the user ID of the admin who set up the KMW/user input questions. The setting is currently saved here:
  * https://github.com/google/site-kit-wp/blob/5c8158f62795d2fe3605426d9982c073787910cc/includes/Core/Key_Metrics/REST_Key_Metrics_Controller.php#L143
  * https://github.com/google/site-kit-wp/blob/5c8158f62795d2fe3605426d9982c073787910cc/includes/Core/User_Input/REST_User_Input_Controller.php#L155
  * Instead of saving `true` we should save the current user ID of the user that first sets up Key Metrics.
  * Update https://github.com/google/site-kit-wp/blob/5c8158f62795d2fe3605426d9982c073787910cc/includes/Core/Key_Metrics/Key_Metrics.php#L90 to continue to return a boolean—`false` if setup is not complete (eg. no user ID is saved) and `true` if setup is complete (eg. a user ID is saved). User IDs are always positive integers, so it's arguably safe to continue casting the number to a boolean.
  * Add the actual user ID to `Key_Metrics.php` `inline_js_base_data` function, eg: `$data['keyMetricsSetupCompletedByUserID'] = $this->key_metrics_setup_completed->get();`
  * Add this new `keyMetricsSetupCompletedByUserID` setting to similar places in the codebase where we use `keyMetricsSetupCompleted` so it is available to selectors.
* Add a new feature tour to `assets/js/feature-tours/shared-key-metrics.js`
  * The feature tour should should target `.googlesitekit-km-change-metrics-cta` and use the content (eg. title, text, dismiss CTA) mentioned in the ACs.
* When `ChangeMetricsLink` mounts, in a `useMount` (or possibly a `useEffect` that calculates once all values are available), check if `keyMetricsSetupCompletedByUserID` mentioned above is both defined and _not_ equal to the current user ID (`select( CORE_USER ).getID()`). If so, trigger the tour by dispatching the `triggerOnDemandTour` action.

### Test Coverage

* No tests are needed for the feature tour, as they can/should be manually QA'd and we don't have feature tour Jest testing infrastructure.
* Add tests to cover the new `keyMetricsSetupCompletedByUserID` setting to ensure it is output by PHP and available to selectors in JS.

## QA Brief

* Setup Site Kit and key metrics
* Share `Analytics 4` and `Search Console` modules with another user
* Log-in as that user
* Verify that new tour is showing on the `change metrics` button, with content as defined in AC

## Changelog entry

* Implement the "Change Metrics" Feature Tour tooltip when widget is setup by another admin.

**Comment by marrrmarrr** [comment]
I'd suggest to remove the banner CTA altogether, and show instead a tooltip on the “Change metrics” link in the top right corner. The text could be something along the lines of “Admin1 has set up these tailored metrics for your site. You can edit the selection from here”, or similar.

**Comment by marrrmarrr** [comment]
@jimmymadon agree, in this case as well Admin1 has set up tailored metrics, even if they haven't answered the questions. So the messaging in this tooltip would still be valid.

**Comment by aaemnnosttv** [comment]
@jimmymadon @marrrmarrr the added tooltip seems perhaps unnecessary because "change metrics" is already quite clear IMO. Also, adding this language introduces some additional complexity so I want to make sure we've considered these:

- We'd likely want to handle the case separately where the admin identified in the tooltip is the current user
- If another admin then changed the selected metrics, I assume we'd want to update the reference in the tooltip to this user to always reflect the last user to change the metrics
    - Particularly for the case where metrics are chosen rather than getting automatic/recommended we'd need to store which user was changing them as we wouldn't be able to infer it from the user input answers which already reference a user.
- It wouldn't be new for new things to show up on the SK dashboard that the user didn't set up themselves (that's always been the case for modules)

The most important thing is that we don't show KMW and the banner simultaneously which should be quite straightforward to address. @marrrmarrr if you feel strongly about the added tooltip, it would probably be better to define that separately as that is more of an informative concern.

**Comment by marrrmarrr** [comment]
Agree that the most important issue here is not to show the banner and the widget simultaneously. Regarding the other corner cases, I don't think we need to show the tooltip after every metric change by every admin, only the first time the affected admin sees this (regardless of whether the metrics were hand-picked or came via the answers). Let's discuss more in the AC meeting.

**Comment by techanvil** [comment]
Hi @tofumatt, thanks for the IB here. A couple of points do stand out -

- As it stands it looks like the IB covers the AC requirement for showing the feature tour on the view-only Dashboard, but it doesn't cover the scenario where an authenticated admin who didn't setup Key Metrics should also see the tour.
- It's not immediately apparent to me how we're going to discern whether the current admin is indeed the same (or not) admin who has setup Key Metrics. It might be worth going into that a bit in the IB.

Also, the final point in the IB is essentially clear but could use a grammatical tweak.

**Comment by techanvil** [comment]
Hey @tofumatt, unfortunately we'd still run into a couple of issues with the IB as specced.

- Saving the user ID as part of the key metrics settings via `saveKeyMetricsSettings()` would cover the case where the user explicitly chooses the key metrics, but not the case where they complete the questionnaire, as the answers are stored as the distinct user input settings - see `saveUserInputSettings()` on the client-side.
  - An additional point to make here, though, is that capturing the user ID would be better done on the server-side, it would be more robust in terms of timing and there's no real need for the client to have to send this bit of data over.
  - It's worth noting we already have the `googlesitekit_key_metrics_setup_completed` setting which is updated in both the `key-metrics` and `user-input-settings` controllers, and serialized to `_googlesitekitBaseData`. It could be worth extending this setting to track the user ID. If so, please take into consideration how we currently do a rough sync of `setKeyMetricsSetupCompleted()` in `saveKeyMetricsSettings()`, this would have to be improved upon to give a more robust sync, with the user ID obviously not being a static value.
- Lastly, as it stands with the `context` being set to just `VIEW_CONTEXT_MAIN_DASHBOARD_VIEW_ONLY`, it still looks like this approach would not support the "authenticated but different admin user" case.

**Comment by tofumatt** [comment]
> An additional point to make here, though, is that capturing the user ID would be better done on the server-side, it would be more robust in terms of timing and there's no real need for the client to have to send this bit of data over.

Ah, that's a good point 😄 Thanks for the suggestions, I've made the changes and this should be a bit better now 🙂 

> Lastly, as it stands with the context being set to just VIEW_CONTEXT_MAIN_DASHBOARD_VIEW_ONLY, it still looks like this approach would not support the "authenticated but different admin user" case.

Oops, right! Fixed that as well 🙂

**Comment by techanvil** [comment]
Thanks @tofumatt, this is most of the way there now. There are a couple of things remaining that we should consider:

- I'm not sure if you spotted this point in my previous comment, but I do think we should address this in some way in the IB; maybe we _don't_ need to do a full sync here (by which I mean syncing the `keyMetricsSetupCompletedByUserID` value as well, which may not be the current user ID) just yet, and can just take into consideration the `keyMetricsSetupCompletedByUserID` may be undefined when the condition for showing the feature tour is checked, but either way it's worth drawing attention to this aspect in the IB. At the very least it would be nice to update the comment to point out that the `keyMetricsSetupCompletedByUserID` _isn't_ synced while `keyMetricsSetupCompleted` is. See the relevant code [here](https://github.com/google/site-kit-wp/blob/3ecad74e033081b37419d60dee4b9667b84aa1d3/assets/js/googlesitekit/datastore/user/key-metrics.js#L137-L142).
> ... please take into consideration how we currently do a rough sync of `setKeyMetricsSetupCompleted()` in `saveKeyMetricsSettings()`, this would have to be improved upon to give a more robust sync, with the user ID obviously not being a static value.

- This is just a point about names, but rather than changing `key_metrics_setup_completed` to store a user ID and then mapping it to `keyMetricsSetupCompletedByUserID` and having to cast to a boolean for the correspondingly named `keyMetricsSetupCompleted`, it would be cleaner to rename the current setting to `key_metrics_setup_completed_by_user_id`. We'd still need to cast it to a bool for `keyMetricsSetupCompleted`, but the option name would be more logical and descriptive.

One last thing - regardless of the naming aspect, I think we should raise the priority of the issue to a P0, because we're changing the definition of this option - something we definitely want to get in before launch! :)

**Comment by tofumatt** [comment]
@techanvil Good points, I've added a note about syncing and renaming the setting. 👍🏻 I've also changed the priority and upped the estimate because of the setting renaming.

**Comment by techanvil** [comment]
Thanks for the updates @tofumatt. There is one last detail though. When syncing the `keyMetricsSetupCompletedByUserID` value in `saveKeyMetricsSettings()`, it's not actually safe to assume that the value will be the ID of the current user, because another user could have setup Key Metrics in the time since the current page was loaded and bootstrapped. So we need to either return the completed-by-user-ID value in the `POST:key-metrics` response (which may not be ideal, but it's doable), or create a new endpoint to retrieve it. Or, consider some alternative approach that avoids needing to sync this, although I'd prefer to see it synced myself.

**Comment by tofumatt** [comment]
Returning the value seems the obvious solution to me because that's where it's needed and would be useful. It would save an additional request and lessen the amount of work needed here, so that's what I'll add to the IB. 👍🏻

**Comment by aaemnnosttv** [comment]
@tofumatt @techanvil Is it necessary to sync `keyMetricsSetupCompletedByUserID` on the client at all if it's only used for a feature tour that would be triggered if another user had set up KMW? That is, if another admin had set up KMW after the current page was loaded, the user wouldn't see the KMW yet, so I'm not sure it offers sufficient utility to justify creating a new endpoint just to fetch it in this scenario. Perhaps I'm misunderstanding it, but keep in mind, we only trigger automatic feature tours as defined here within the first 5 seconds of the page load or so.

If we did need to sync some data, adding a new endpoint for a single field is a bit overkill. We could instead see about adding an endpoint for fetching the base data entirely and perhaps migrating to a preloaded request rather than a global – again, if needed – just my 2c.

**Comment by techanvil** [comment]
Hi @aaemnnosttv, thanks for pointing this out. To be honest, I think I was getting a bit of tunnel vision and hadn't fully considered how the automatic feature tours are shown. Digging in I see they're invoked in an `onMount()` at page load, so we should indeed be able to avoid the additional sync altogether, as we don't need to be concerned about accidentally triggering the survey later on in the journey if the user sets up Key Metrics themselves.

I must admit, revisiting this issue and digging into the survey triggering has made _another_ thought occur to me. Rather than having to reproduce the conditions for determining if the Key Metrics area is visible, we could avoid that, by instead making this an on-demand survey that's triggered when the `ChangeMetricsLink` component is rendered. That would save having to reproduce and maintain this duplicated logic.

Note that if we _do_ take this approach it's possible the user could have just set up Key Metrics, but I think we could still avoid the sync, by determining the logic to be "on `ChangeMetricsLink` mount, if `keyMetricsSetupCompletedByUserID` is defined and is not the current user ID, show the tour".

@tofumatt, what do you think?

**Comment by tofumatt** [comment]
@techanvil That sounds good, I'll amend the IB accordingly 😄

**Comment by techanvil** [comment]
Thanks @tofumatt! I have made an additional small tweak as discussed on Slack, and this IB LGTM :white_check_mark:

**Comment by zutigrm** [comment]
@tofumatt @jimmymadon What should be the `gaEventCategory` for this tour? Currently I have set it as `${ viewContext }_shared_key-metrics`, but let me know if it should be something more specific/different.

**Comment by zutigrm** [comment]
@mohitwp Thank you for bringing this up. I can confirm that this is expected behaviour as Tours were disabled for screens bellow [783px](https://github.com/google/site-kit-wp/issues/2739#issuecomment-804055739) per this [comment](https://github.com/google/site-kit-wp/issues/2739#issuecomment-804106445)

**Comment by mohitwp** [comment]
### QA Update ✅  

- Tested on dev environment.
- Verified that that new tour is showing on the change metrics button, with content as defined in AC.
- Verified that new tour is showing if Analytics is shared with other users.
- Verified that now KMW widget set up banner is not showing to another admin and on view only dashboard.
- Verified that The feature tour is rendered only once and dismissible by either clicking the "X" button in the corner or the Got it dismissal CTA.
- Verified that if admin user first access view only dashboard and after that sign in then 'Feature tour' is not showing again after sign in. It appears only once on view only dashboard in this case.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/0759afc8-c6b6-42e5-a64e-8ba21724810a)

Authenticated Admin View only dashboard view.

https://github.com/google/site-kit-wp/assets/94359491/2eae73ab-cc50-4d9b-b49a-d3507965ac91

Authenticated Admin Sign in view

https://github.com/google/site-kit-wp/assets/94359491/dd3f76cf-dd66-47b6-a116-eae15ec6736a

View only dashboard view

https://github.com/google/site-kit-wp/assets/94359491/b2c610af-4211-428e-be11-9ccc4abad94b


</details>
