### ISSUE TITLE
`PHP Fatal error:  Uncaught Error: Cannot use object of type Google\Site_Kit_Dependencies\GuzzleHttp`

### ISSUE THREAD

**Issue by adamdunnage** [google/site-kit-wp#7356]
## Bug Description

There have been several reports in the support forum over the last week of a PHP fatal error occurring on users sites when they have Site Kit installed and active.

This appears to be found in the users PHP error logs and isn't affecting any of the Site Kit plugin functionality. I will attach users Site Health Information here once we receive it.

We have so far not been able to recreate this but one user confirmed that upgrading their PHP version from 7.4 to 8+ cleared the error message. 

[Example topic](https://wordpress.org/support/topic/php-fatal-error-375/) - [Site Health Information](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNiGKQ6zd_DPJOuGRj1dBso2_Q8mRj0ld0GC1071gUxU-LZLjpbE7t3ixbyRppBPUxk) 

**Other reports:**
https://wordpress.org/support/topic/critical-error-550/ - No Site Health
https://wordpress.org/support/topic/php-fatal-error-376/ - No Site Health
https://wordpress.org/support/topic/uncaught-error-cannot-use-object-of-type-google/ - No Site Health

**Error:**

```
PHP Fatal error:  Uncaught Error: Cannot use object of type Google\Site_Kit_Dependencies\GuzzleHttp\Psr7\Request as array in /.../wp-content/plugins/google-site-kit/includes/Core/Authentication/Clients/OAuth_Client.php:535
Stack trace:
#0 /.../wp-content/plugins/google-site-kit/includes/Core/Authentication/Authentication.php(424): Google\Site_Kit\Core\Authentication\Clients\OAuth_Client->refresh_profile_data(1800)
#1 /.../wp-includes/class-wp-hook.php(308): Google\Site_Kit\Core\Authentication\Authentication->Google\Site_Kit\Core\Authentication\{closure}(Array)
#2 /.../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#3 /.../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /.../wp-content/plugins/google-site-kit/includes/Core/Authentication/Clients/Google_Site_Kit_Client.php(202): do_action('googlesitekit_r...', Array)
#5 /.../wp-content/plugins/google-site-kit/includes/Core/Authentication/Clients/OAuth_Client.php on line 535
```

### Steps to reproduce

_Involves using WP-CLI to modify DB values_

1. Perform basic setup of SK to get to dashboard (or use existing); no specific modules active
1. Once dashboard has completed loading, issue the following commands:  
	> Substitute your username for `{username}` without brackets  
	> Note: the `wp_` prefix below could vary based on your install – use `wp user meta list {username}` to see the values present and update usage below accordingly
	```
	wp user meta patch delete {username} wp_googlesitekit_profile last_updated
	wp user meta set {username} wp_googlesitekit_access_token_expires_in 1
	```
1. Once done, toggle the date range to a different range (i.e. Last 7 days)
1. See report errors in components  
	<img width="451" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/c125c141-1dc8-4b33-8815-5085498f95e5">
1. Refresh the page and everything should load normally including the date range that errored before

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When requesting/refreshing profile data, it should be ensured that the request is always executed without deferral 

## Implementation Brief

The trace above indicates that the error happens when the profile data is triggered to refresh in response to a token refresh that happens during a report data request which can be reproduced in a test. Report requests are made as deferred (as configured on the client) which is why the `$response` would actually be the (yet-to-be-executed) `Request` instance here https://github.com/google/site-kit-wp/blob/7f3f46148ee3693241be662f9438a587949db678/includes/Core/Authentication/Clients/OAuth_Client.php#L532-L535

- Save a reference of the client instance that is being provided to the `People` service class instance, in order to configure it beforehand
- Disable deferred request execution on the instance via `withDefer` method
- Provide the configured client instance to the `People` service class
- Add a `finally` clause to the `try/catch` to call the `restore_defer` callback (returned by `withDefer`) – this is important because we're modifying a shared instance

### Test Coverage

* Add PHPUnit test that exercises the `refresh_profile_data` method with the main client instance pre-configured with deferred execution

## QA Brief

* See steps above to reproduce
	* Due to the changes needed this may need `QA:Eng` or support from an engineer
* The underlying issue is related to when an access token needs to be refreshed on-the-fly in response to a data/report request, otherwise tokens are refreshed proactively on pageload if expired or near expiration

## Changelog entry

* Fix potential PHP error when refreshing profile data on the fly.

**Comment by adamdunnage** [comment]
One previous report we had of this same error was resolved by the user by deactivating and deleting the plugin and wp-content folder. They then re-installed and activated and activated the plugin which cleared the errors from the log.

[Support topic](https://wordpress.org/support/topic/cannot-use-object-of-type-error/)

**Comment by techanvil** [comment]
Hey @aaemnnosttv, nice work tracking this one down and finding a fix.

I'm a bit hesitant about the idea of cloning the client object, though. Considering how a clone can still share references with its original object we could in theory end up in the situation where we change something on the cloned client and it has an unintended effect on the original...

Could we not instead make use of the [`withDefer()`](https://github.com/google/site-kit-wp/blob/54565cc15efa628dd400ed13aa5e012058a47a31/includes/Core/Authentication/Clients/Google_Site_Kit_Client.php#L79) method that `Google_Site_Kit_Client` provides, which looks like it was designed for this sort of scenario?

Or, if I've missed something and we do need an entirely new client instance, could we instantiate a new one instead rather than cloning?

**Comment by aaemnnosttv** [comment]
Thanks @techanvil 

> I'm a bit hesitant about the idea of cloning the client object, though. Considering how a clone can still share references with its original object we could in theory end up in the situation where we change something on the cloned client and it has an unintended effect on the original...

That's a good point, and one that I had thought of although more to avoid lingering changes to the client which is shared elsewhere. In theory, `withDefer` should be perfectly fine here. I guess I felt less trust in that since it's more/less responsible for the issue here in the first place. I think it's essentially an issue of the "defer stack" since this normally runs fine during a cron execution. We recently changed this profile refreshing to be called when a token is refreshed though which will happen on-demand when an API request is made and the current token is either expired or near expiration. All report/data requests are made as deferred requests (which is important for dashboard sharing) and so what happens is
getReport -> execute_data_request -> withDefer(true) -> client->execute() -> (refresh token) ->  `googlesitekit_reauthorize_user` -> refresh_profile_data() -> `$people_service->people->get` : (deferred) `Request` instead of the assumed non-deferred default client 😅

Now that this is more thoroughly understood, using `withDefer` should be fine so long as we restore it at the end as usual 👍 

I'll update the IB accordingly.

**Comment by techanvil** [comment]
Hi @aaemnnosttv, thanks for the context here and for detailing the mildly cold sweat-inducing execution path :smile: 

As you've pointed out, with this more in-depth understanding of things `withDefer` looks like a good approach and this LGTM.

IB :white_check_mark:

**Comment by aaemnnosttv** [comment]
@techanvil I've added steps to reproduce and some points to the QAB. In the future, feel free to merge if the rest is in good shape and assign back to the engineer in QA to add/revise before handing over 👍

**Comment by techanvil** [comment]
Thanks @aaemnnosttv, I'll certainly bear that in mind in future. However, in this case I did want to use the QAB to inform if/how I could give this a quick test during CR, in order to "run the code".

**Comment by techanvil** [comment]
## QA :white_check_mark: 

- First, reproduced the error using the latest release.
- Setup Site Kit on a fresh InstaWP site.
- Cleared `last_updated` and reset token expiry.

![image](https://github.com/google/site-kit-wp/assets/18395600/26cda68e-16aa-4167-959a-a9186fe6d16d)

- Changed the date range, and confirmed the resulting errors.

![image](https://github.com/google/site-kit-wp/assets/18395600/6a616758-1344-4384-918c-c82ce190aaa2)

- Switched to `main`, reinstalled, and cleared the meta again.

![image](https://github.com/google/site-kit-wp/assets/18395600/85064afe-6394-4999-9792-dbbd2f5ec938)

- Changed the date range, confirmed the error does not occur.

![image](https://github.com/google/site-kit-wp/assets/18395600/3b7d957d-064c-4800-992a-eb631d18e4fa)
