### ISSUE TITLE
verification token missing

### ISSUE THREAD

**Issue by breakfastclubkc** [google/site-kit-wp#736]
## verification token missing

I cannot set up my sitekit - it will not verify or tell me what to do to verify it.

## Steps to reproduce
I made a video: https://share.getcloudapp.com/YEuvBgQv

**Comment by jamesozzie** [comment]
@breakfastclubkc  There may be a security, caching or other plugin impacting Site Kit setup. Can you please attempt the steps below in order to get Site Kit connected:
1. Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
2. Temporarily deactivate any caching plugins you might have active, such as WP Optimize
3. Install Site Kit in a new [incognito window](https://i.imgur.com/ALzgiHp.png).

If the above fails to resolve your issue can you please share the following:
- Any [console errors](https://i.imgur.com/KyLAzgH.png) that appear
- Your WordPress [Site Health information](https://i.imgur.com/Rtkmsba.png)
- Any security plugins or software in use (ModSecurity, iThemes, WordFence etc)

**Comment by allanemerson** [comment]
I'm having the same issue as @breakfastclubkc, no caching plugins,  and installing things in an incognito window didn't help.

**Comment by magecmor** [comment]
I'm having the same issue. Can't set up verification token. The step take me to Page Not Found on my site. 

If I add verification token through Google Analytics will it work?

**Comment by lazharichir** [comment]
Same issue on a new site I am setting up from scratch:
- host is BlueHost
- already using Site Kit on that same Google Account with another website (different domain and host)
- tried incognito, tried without any other plugin installed, and it's a very fresh install

**Comment by ernee** [comment]
@breakfastclubkc @allanemerson @lazharichir could you update to the new version 1.0.1? Please let us know if this resolves the issue for you. Thanks!

**Comment by lazharichir** [comment]
@ernee yes works for me now! thanks!
