### ISSUE TITLE
Google analytics 4 dashboard toggle not available 

### ISSUE THREAD

**Issue by androidacy-user** [google/site-kit-wp#7397]
## Bug Description

The Google analytics 4 dashboard toggle listed in the documentation does not show on our website. It forces us to connect a UA property and only shows data for the property - which has no data. 

## Steps to reproduce

1. Setup Google analytics 
2. go to analytics settings 

## Screenshots

![Screenshot_20230803-233726.png](https://github.com/google/site-kit-wp/assets/45006100/af308646-3628-43df-a873-e8f668691ec9)

## Additional Context

 - PHP Version: 8.2
 - OS: Android
 - Browser: Chrome
 - Plugin Version: 1.106.0
 - Device: pixel 7 pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment]
Hi @androidacy-user thanks for opening this topic. Unfortunately, we do not provide support via GitHub. However, we'd be delighted to help you with this over in the support forum. Please [open a new topic](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0) there and we will be happy to look into this for you.

**Comment by bethanylang** [comment]
@androidacy-user Hi there! While there may be a bug here, our support forum is where we work directly with users to get their information and identify any possible issues that may require a code fix before an issue is filed in GitHub. If it turns out that there is a bug here, we can reopen this issue and go from there, but in order to help our support team understand the issue, please [open a support topic](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0) so that they can assist. Thanks!
