### ISSUE TITLE
Creating GA4 with Google Site Kit VS manual creation on GA4 website.

### ISSUE THREAD

**Issue by locksmithunit** [google/site-kit-wp#7401]
Hello, i notice for option to create Google Analytics with the plugin via API through my WordPress site.
But it not set up all the option.

What is better to do?

Manual via:
https://analytics.google.com/

or better to do it via your plugin?
got confused beacuse the plugin not approve all the options you have in manual.

Be happy for help what is the best way.
and if it better to open it via your plugin.

**Comment by adamdunnage** [comment]
@locksmithunit Thanks for opening this GItHub issue. I have spotted that you also [opened a support topic](https://wordpress.org/support/topic/creating-ga4-with-google-site-kit-vs-manual-creation-on-ga4-website/) in the support forum for this which I have since responded to. We don't provide support via GitHub so I will close this issue and continue any further conversation via your support topic, thanks.
