### ISSUE TITLE
Update UA removal date to September 25

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7423]
## Feature Description

To better align with our release schedule and allow for testing sans UA in advance of the KMW release, we've confirmed with @marrrmarrr that UA should be removed from Site Kit beginning with v1.110.0 release on **September 25**.

#6549 set this date for October 1 and it needs to be changed. Note that this change will also affect #6786 (title updated to reflect new date) and #7417.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- [#6549](https://github.com/google/site-kit-wp/issues/6549) implemented some notable changes to the functionality and Analytics-related copy in Site Kit that would only be visible starting on October 1 2023. The targetted date for all the updates made in [#6549](https://github.com/google/site-kit-wp/issues/6549) should be changed to September 25 2023 instead.
- All changes implemented as a part of [#6549](https://github.com/google/site-kit-wp/issues/6549) should be visible and testable starting on September 25 2023, instead of October 1 2023.

## Implementation Brief

* Change `GA4_AUTO_SWITCH_DATE` to `'2023-09-25'`.

### Test Coverage

* Update any VRTs/tests that rely on the previous date.

## QA Brief

* Set up Site Kit with GA4 and UA.
* Set the dashboard view to UA.
* Set the reference date to September 25, 2023, or above using the tester plugin.
* Go to the SK dashboard and ensure all the widgets are displayed with the GA4 version of it.
* Refer to the QAB for https://github.com/google/site-kit-wp/issues/6549 for further test scenarios, substituting the date `2023-09-25` for `2023-10-01`.
* **Note:** There is a known issue with the dashboard sharing modal and the view-only dashboard, which don't change GA4. It will be fixed in #7417 

## Changelog entry

* Update the date that Universal Analytics support is removed from Site Kit to September 25, 2023.

**Comment by techanvil** [comment]
Hi @nfmohit, this AC is somewhat verging on IB territory - it's explaining _what_ we should do, but not spelling out the associated behaviour that we're interested in as a result of changing the date. Although you _have_ linked to the related issue #6549, it would be good to add a bit of detail to save speculation about what the related changes are that should be tested.

I think a brief amendment to explain that we should expect the functionality implemented in #6549 to now be contingent on and testable with the new date should suffice.

Additionally, I would suggest updating the date on the issue #7417 and making that dependent on this issue, so as to save potentially having to test #7417 twice.

We could also bump this to a P0 to make it clear it should be implemented before #7417.

cc @bethanylang

**Comment by techanvil** [comment]
Update: To get ahead of things, I've gone ahead and updated the date in #7417, it and made it dependent on this one.

**Comment by nfmohit** [comment]
Thank you for the kind review, @techanvil. I have updated the ACs to be a bit more directed towards the end goal, but still concise. I have also changed this to be a P0 (CC: @bethanylang).

Please let me know how this looks now, thank you!

**Comment by techanvil** [comment]
Thanks @nfmohit! That looks great.

AC :white_check_mark:

**Comment by tofumatt** [comment]
Mostly marking as a 7 for the QA involved, otherwise this is _quite_ straightforward I think 🤔

**Comment by aaemnnosttv** [comment]
IB ✅ 

Also updated the title to reference the correct version of GA to be removed 😆

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- With UA and GA4 connected and the reference date after September 25, the widgets are displayed with the GA4 version.
- The Dashboard View section is no longer present on the Analytics Settings edit and view pages.
- The Dashboard View indicator chip is no longer present on the Dashboard.
- The "Switched to GA4" notification banner appears when the Dashboard View setting is overridden via setting the date.
- Checked on main and entity dashboard. 
- Checked the appropriate notifications when GA4 is disconnected. 

**Note:** There is a known issue with the dashboard sharing modal and the view-only dashboard, which does not change GA4. It will be fixed in https://github.com/google/site-kit-wp/issues/7417

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/68c88643-0766-476f-a6c7-b04ab82bb357)
![image](https://github.com/google/site-kit-wp/assets/73545194/872cf565-8875-4ac6-ba9e-b9439ac1c1dd)
![image](https://github.com/google/site-kit-wp/assets/73545194/98fcd5cf-81c9-46e4-8d7b-352cef8b01af)
![image](https://github.com/google/site-kit-wp/assets/73545194/c5630b7b-cbce-43a3-8366-11b41fe0924e)
![image](https://github.com/google/site-kit-wp/assets/73545194/5fb218ea-765c-43f4-b0ea-d2a5fc772119)
![image](https://github.com/google/site-kit-wp/assets/73545194/a5a8d342-26e5-4822-a4b4-da277334e89b)

</details>
