### ISSUE TITLE
Clean up apostrophes in plugin text

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7440]
## Feature Description

There are a few places in the plugin where apostrophes (') looks like backticks (`), though I've confirmed they are not backticks. I caught some for the KMW feature ([see here](https://app.asana.com/0/1204713925711993/1205267952490640/f)) but there are others in the plugin that should be changed:

**First page of setup screen**
- "...as well as how to improve and monetize your site's content"

**Dashboard**
- Find out how your audience is growing widget – "Track your site's traffic over time"

**Analytics Settings > Google Ads**
- "If you're using Google Ads, insert your Ads conversion ID if you'd like Site Kit to place the snippet on your site"

**Connect More Services > AdSense**
- "It's free and easy."

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
This is actually… entirely intentional 🙂. It might look a bit odd as a lot of sites/plugins/etc. don't bother doing it, but technically the apostrophe character is

# ’

not

# '

The latter is just a single quote, and _technically_ not the right character to use there. But it gets used all over the web in place of the actual apostrophe character because it's easier to type and a lot of software traditionally doesn't intelligently change it to an actual apostrophe.

But this is an intentional decision throughout our strings, so I think we should close this as a won't fix. Same goes for #7481.
