### ISSUE TITLE
Key Metrics navigation chip not highlighted on CTA load

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7442]
## Bug Description

When the plugin is set up and the Key Metrics Setup Banner CTA is shown, the URL hash is set to traffic and the Navigation chip selected is Traffic instead of the new Key Metrics navigation chip.

This issue was already fixed once before but has resurfaced in a recent PR. Scrolling the page by a single pixel does update the Navigation chip highlight instantly to Key Metrics.

## Steps to reproduce

1. Set up Site Kit with GA4 and the `userInput` feature flag.
2. The Key Metrics Setup Banner CTA will be displayed on the main dashboard.
3. The Key Metrics Navigation Chip is not highlighted and the hash within the URL is set to #traffic instead of key-metrics.

## Screenshots

https://github.com/google/site-kit-wp/assets/1721319/f495a44f-c3fb-4fb7-a385-20a8bda5a7d0

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When we are loading or navigating to the Site Kit Dashboard, if the Key Metrics widget area is rendered, then:
    * The Key Metrics navigation chip should be highlighted by default.
    * The URL hash should be set to #key-metrics by default.
    * If reloading the page while scrolled to a different area, that area's chip should continue to be highlighted as it is now.

Note: This currently does not happen only when the Key Metrics Setup Banner CTA is rendered but works as above when the Key Metric tiles are rendered.

## Implementation Brief

* This is happening due to the `useMount` effect in[ `Navigation`](https://github.com/google/site-kit-wp/blob/afcca51f309aea6db2fd3fadffe53967882959b7/assets/js/components/DashboardNavigation/Navigation.js#L246-L247) component is being run before the `isGatheringData` selectors for Search Console and Analytics 4 being resolved in [`KeyMetricsSetupCTAWidget`](https://github.com/google/site-kit-wp/blob/afcca51f309aea6db2fd3fadffe53967882959b7/assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js#L60-L65) component, thus it returning `WidgetNull` while gathering data state is being resolved. That's why `getDefaultChipID` doesn't consider Key Metrics widget context as active. 
* In `assets/js/components/DashboardNavigation/Navigation.js`:
    * Get gathering data state of both `search-console` and `analytics-4` using the `isGatheringData` selectors of respective modules. 
        * On Authenticated dashboard, check if GA4 is connected before calling `isGatheringData`, falling back to `false` as the value otherwise. 
        * On shared dashboard, Check ensure module is shared before calling `isGatheringData` for both SC and GA4. falling back to `false` as the value otherwise. 
        * See [this](https://github.com/google/site-kit-wp/issues/7442#issuecomment-1689535115) comment for an example. 
    * Wrap `isValidChipID` function in a `useCallback` hook. 
    * Create a ref (ie. `ranOnce`) using `useRef` hook to track whether the effect that initially sets the active Chip has ran, with a default value `false`.
    * Replace the `useMount` with a regular `useEffect` that handles the initial chip selection logic.
        * Return early if `ranOnce.current === true`, or `userInputEnabled && (searchConsoleIsGatheringData === undefined || analytics4IsGatheringData === undefined )`.
        * Otherwise, set `ranOnce.current` to `true` and run the current logic. 

<details><summary>Alternative (rejected) approach</summary>

* Instead of crafting a super complicated fix, we can use the `dataAvailableOnLoad` selectors to solve this issue for 99% of cases where the widget will be shown. 
* In `assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js`.
    * Refactor the `searchConsoleIsGatheringData` and `analyticsIsGatheringData` to check for `isDataAvailableOnLoad` of respective modules first, and return early with `false` when data is available. 
    * Otherwise return the `select` call to `isGatheringData`.
    * For example,
```js
    const searchConsoleIsGatheringData = useSelect( ( select ) => {
        if ( select( MODULES_SEARCH_CONSOLE ).isDataAvailableOnLoad() ) {
            return false;
        }
        return select( MODULES_SEARCH_CONSOLE ).isGatheringData();
    } );
```

</details> 

### Test Coverage

* N/A

## QA Brief

* Load the Key Metrics widget before and after setup. Verify that the Navigation Chip is always highlighted correctly if the widget is rendered on the page.
* Note: The Key Metrics Setup Banner CTA will now show up on the "second" page load after SC and GA4 have left the Gathering Data state. So if Site Kit is setup and GA4 is connected with a site that does have data, the banner will not show immediately when the dashboard is first loaded after GA4 connection. The banner will only be shown when the dashboard is "refreshed/reloaded" from the browser.
* Note 2: Please QA the ACs within #7466 alongside this issue.

## Changelog entry

* Ensure the Key Metrics navigation chip is correctly highlighted on page load.

**Comment by techanvil** [comment]
Thanks @jimmymadon, the AC LGTM, I did however add an additional point to provide a little extra clarity.

**Comment by techanvil** [comment]
Hi @jimmymadon, thanks for drafting this IB.

Unfortunately though, it would seem that with this fix in place, the bug will still occur when the plugin is first setup. Obviously, this is not a great first impression, so I think we'll need to go back to the drawing board on this one...

**Comment by kuasha420** [comment]
@techanvil Thank you for reviewing the previous IB. I've drafted a new IB that solves the problem in all cases. Let me know what you think about this one. Cheers.

**Comment by techanvil** [comment]
Thanks @kuasha420!

IB :white_check_mark:

**Comment by techanvil** [comment]
Hi @jimmymadon, thanks for your proposal here!

So, if I have understood this correctly, essentially we would flip the condition so that the widget only renders if `isDataAvailableOnLoad()` is `true`. That makes sense if we don't have to show the widget until gathering data state is resolved and persisted on a previous page load, as you've described, and would indeed be a much easier to manage solution.

It could be simpler still in the code; rather than naming the variables `analyticsIsGatheringData` etc and then inverting the result of `isDataAvailableOnLoad()` for their value and not calling `isGatheringData()` at all, we should simply name them `analyticsIsDataAvailableOnLoad` (etc), with the result being the unmodified value of the corresponding `isDataAvailableOnLoad()`. Then the conditions for rendering `null` would be `! analyticsIsDataAvailableOnLoad` instead of `analyticsIsGatheringData !== false`.

In other words, because real code can get the point across more clearer than trying to transliterate: :smile:

```diff
diff --git a/assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js b/assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js
index 22bea1820a..4d58277e31 100644
--- a/assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js
+++ b/assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js
@@ -57,11 +57,12 @@ function KeyMetricsSetupCTAWidget( { Widget, WidgetNull } ) {
 	const ctaLink = useSelect( ( select ) =>
 		select( CORE_SITE ).getAdminURL( 'googlesitekit-user-input' )
 	);
-	const searchConsoleIsGatheringData = useSelect( ( select ) =>
-		select( MODULES_SEARCH_CONSOLE ).isGatheringData()
+	const searchConsoleIsDataAvailableOnLoad = useSelect( ( select ) =>
+		select( MODULES_SEARCH_CONSOLE ).isDataAvailableOnLoad()
 	);
-	const analyticsIsGatheringData = useSelect( ( select ) =>
-		select( MODULES_ANALYTICS_4 ).isGatheringData()
+
+	const analyticsIsDataAvailableOnLoad = useSelect( ( select ) =>
+		select( MODULES_ANALYTICS_4 ).isDataAvailableOnLoad()
 	);
 
 	const showTooltip = useShowTooltip( KEY_METRICS_SETUP_CTA_WIDGET_SLUG );
@@ -106,8 +107,8 @@ function KeyMetricsSetupCTAWidget( { Widget, WidgetNull } ) {
 
 	if (
 		isDismissed !== false ||
-		analyticsIsGatheringData !== false ||
-		searchConsoleIsGatheringData !== false
+		! searchConsoleIsDataAvailableOnLoad ||
+		! analyticsIsDataAvailableOnLoad
 	) {
 		return <WidgetNull />;
 	}

```

Is that in line with what you're suggesting? If so, LGTM and let's go for it!

**Comment by techanvil** [comment]
Hi @jimmymadon, code-wise this is great and works well in my testing.

I would suggest an amendment to the QAB, to make it clear that the Key Metrics Setup CTA Widget will now _only_ display once GA4 and SC are determined to not be in the gathering data state, and the page has subsequently reloaded. Otherwise I can imagine this could cause some confusion in QA, and it would also be good just to make this quite explicit and easy to spot when we look back on this issue in future.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@jimmymadon 

- Tested on dev environment.
- Verified key metrics navigation chip are highlighted on CTA load.
- Verified key metrics navigation chip before and after setup.
- Verified Key metrics, chip navigation.
- Verified Key metrics loading state.


@jimmymadon Since, #7466 need to test as a part of this issue. I've noticed that when key metrics is not setup. Then on page load Key metrics set up banner quickly appears and hide 2 times before it shows up. You want to me create separate ticket for this or you would fix it in the same ticket ?


https://github.com/google/site-kit-wp/assets/94359491/42e9e41b-17f5-4f31-b166-8f4347244842

**Comment by mohitwp** [comment]
### QA Update ✅ 


- Tested on dev environment.
- Verified key metrics navigation chip are highlighted on CTA load.
- Verified key metrics navigation chip before and after setup.
- Verified Key metrics, chip navigation.

<details>


https://github.com/google/site-kit-wp/assets/94359491/9ef3349a-7e38-4378-bb9e-5a8139c3cf79


https://github.com/google/site-kit-wp/assets/94359491/fcc344bd-777d-4c87-a14f-e369dd25b8ee

</details>
