### ISSUE TITLE
Create "Pages per visit" key metric widget tile

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7575]
## Feature Description

![image](https://github.com/google/site-kit-wp/assets/20284937/97eda56a-1c63-4574-9969-0ff3bbf08131)
(screenshot for reference - see Figma for latest version)

A new key metric widget tile should be added for "Pages per visit".

See:
1. [Table of metrics in design doc](https://docs.google.com/document/d/1htqStvvyXq_eg5GsHSbdBBgm4Tu_Z6KXsIOBfjWQ5oM/edit?resourcekey=0-Px-yDiCQOTz30DBKllhU3g#heading=h.5u6oy5c2u65e).
2. [List of metrics in PRD](https://docs.google.com/document/d/1UZ2VXOxpsY3GiHgQncZIb73Uy-xVf15MWJi46QkK_X0/edit?resourcekey=0-dB9ROp2h3ZYhqoyYBMTzvw#bookmark=id.usf86uc2bsda).
3. [Figma designs](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60032&mode=design&t=nUObjDPmn7ra177i-4).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- A new component should be created for the "Pages per visit" key metric widget tile and should be displayed within the Key Metrics Widget area if its widget slug is added to the `widgetSlugs` array of key metrics settings.
  - The component should look exactly as its [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60032&mode=design&t=nUObjDPmn7ra177i-4).
  - Its widget slug should be `kmAnalyticsPagesPerVisit` (so that it is consistent with the design doc).
  - The metric tile title should be `Pages per visit`.
  - Its description tooltip should say `Number of pages on average visitors viewed per visit`.
  - This metric should be dependent on the `analytics-4` module, so it should only be rendered in the key metrics widget area if GA4 is connected, otherwise, `ConnectGA4CTATileWidget` should be rendered (similar to existing GA4-dependent metric tiles). It should also not be shown to view-only users who do not have shared access to GA4.
- The following data should be fetched from the [Google Analytics Data API](https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema) for the global date range selected on the Site Kit dashboard:
  - Metrics: `screenPageViewsPerSession` and `screenPageViews`
- Values:
  - The primary value should be the number of page views per session, obtainable using the `screenPageViewsPerSession` metric.
  - The secondary value (`page views`) should be the total number of page views, using the `screenPageViews` metric.
- The percentage change figure (with a red for negative or green for positive highlight) should be calculated based on the 'previous' period before the selected date range, for the primary metric `screenPageViewsPerSession`.
- The metrics & dimensions used in the reports for this tile should be allow-listed for view-only users.
- This metric should be available for selection in the key metrics selection panel only if the `newsKeyMetrics` feature flag is enabled.

## Implementation Brief

* In `assets/js/modules/analytics-4/components/widgets/`, create a new `PagesPerVisitWidget.js` component. This [POC commit](https://github.com/google/site-kit-wp/compare/develop...enhancement/7575-KMW-pages-per-visit-tile)  has already created this component as follows:
    * Use the `NewVisitorsWidget.js` as a starting point and make the following changes.
    * Update `reportOptions` to fetch the `screenPageViewsPerSession` and `sessions` metrics. No other dimensions or metrics are needed.
    * Update the `makeFind` method to only find rows where the `dimensionValues` match a passed `dateRange`.
    * Use this method to compute the `currentPagesPerVisit` and the `previousPagesPerVisit` by extracting the appropriate metric values for the `screenPageViewsPerSession` metric from the `rows` returned from the `report` for `date_range_0` and `date_range_1` respectively.
      * Pass the `currentPagesPerVisit` to the `metricValue` prop of the `<MetricTileNumeric>` component.
      * Pass `currentPagesPerVisit` and `previousPagesPerVisit` to the `currentValue` and `previousValue` props of the `<MetricTileNumeric>` component.
    * Extract the `currentTotalSessions` by extracting the value for the `sessions` metric  from `rows` using the `makeFind` method above with `date_range_0`. 
      * Pass the `currentTotalSessions` within the `subText` prop and update the text as per the AC.
    * Note: Cast all of the above to `Number()` as done in `NewVisitorsWidget`.
    * Update the `title` prop of the `<MetricTileNumeric>` component as per the AC.
* In `assets/js/googlesitekit/datastore/user/constants.js`:
  * Export a new constant for defining the new widget's slug: `KM_ANALYTICS_PAGES_PER_VISIT = 'kmAnalyticsPagesPerVisit'`
  * Add this constant to the `keyMetricsGA4Widgets` array.
* In `assets/js/modules/analytics-4/index.js`:
  * Register the new key metric widget exactly the same as other key metric widgets. However, wrap the registration using the new `newsKeyMetrics` feature flag.
* In `includes/Modules/Analytics_4/Report/Request.php`:
  * Add the `screenPageViewsPerSession` metric to the list of shareable metrics in the `validate_shared_metrics` method.
* Wait for #7472 to be merged and use the same approach in that issue to add the tooltip as per the AC.

### Test Coverage

* Add storybook stories using `NewVisitorsWidget.stories.js` as a starting point and create stories for the Ready, Zero, Loading and Error states. 
    * Add VRT snapshots for the Ready and Zero states.

## QA Brief

* Ensure the new `newsKeyMetrics` feature flag is turned on. 
* Verify that the "Top Returning Visitor Pages" appear in the Metrics selection panel. Select this metric and verify the ACs. Ensure this metric does not appear in the metrics panel if the feature flag above is not enabled.
* Verify the metric works on both, the view-only as well as authenticated dashboards.
* There are no direct comparisons from what I can see in GA4's Admin dashboard. But you can compare values by creating a new "Free-form Blank [Exploration](https://analytics.google.com/analytics/web/?pli=1&authuser=1#/analysis/p285794360/edit/C8b41jIpQPiVm-BeSBRC0Q)" and import the following metrics: Page / Screen -> Views per session and Page / Screen -> Views. Then add these metrics to your exploration under "Values".

## Changelog entry

* Add a new "Pages per Visit" Key Metric tile.

**Comment by tofumatt** [comment]
ACs here are good 👍🏻

**Comment by nfmohit** [comment]
> > The secondary value (total visits) should be the total page views, obtainable using the `screenPageViews` metric.
> 
> @nfmohit I missed this when writing the IB - this will probably have to be `sessions` to determine the number of total visits as we do in the "Visit length" tile. I'll update the AC and IB accordingly as I already am executing this widget. Thanks!

SGTM, thank you @jimmymadon!

**Comment by marrrmarrr** [comment]
@jimmymadon SG, let's just move on average to the end --> "Number of pages visitors viewed per session on average".

**Comment by bethanylang** [comment]
@jimmymadon Quick update needed here: @marrrmarrr got some feedback from the News team that they would like this tile to change the context under the metric from "1,234 total visits" to "1,234 total pages":

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVRxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5f36670dfd706d8a5dc9481e2b05e3ebda673c6b/image.png)

Can you make this update, please? Thank you!

**Comment by marrrmarrr** [comment]
@jimmymadon got the OK from News to proceed with `screenPageViews` -- let's call this "page views" as you suggested.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- A new tile is created for the `Pages per visit` and is displayed when selected from the metrics panel. 
- The tile looks exactly as its [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60032&mode=design&t=nUObjDPmn7ra177i-4).
- The widget slug is `kmAnalyticsPagesPerVisit`
- The metric tile title is `Pages per visit`
- The description tooltip says `Number of pages visitors viewed per session on average` - Please note that the AC is incorrect. This was changed in a comment on this ticket, agreed by Mariya. 
- The tile is dependent on the analytics-4 module and is only be rendered if GA4 is connected.
- The primary value is the number of page views per session
- The secondary value (page views) is the total number of page views.
- The percentage change figure (with a red for negative or green for positive highlight) is calculated based on the 'previous' period before the selected date range.
- The tile is available for selection only if the `newsKeyMetrics` feature flag is enabled.
- The tile, metrics & dimensions used in the reports for this tile are available for view-only users.

**Note:**  there is a small difference in the number of page views but this is due to the reporting tool used to compare the data in the tile to Analytics. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/4c2912aa-27fc-4856-965e-b7d0aff59149)
![image](https://github.com/google/site-kit-wp/assets/73545194/76350b50-8560-4510-ba05-5fdda923e3fa)
![image](https://github.com/google/site-kit-wp/assets/73545194/5e3556b3-df36-48a2-8d8e-1841545f58d0)
![image](https://github.com/google/site-kit-wp/assets/73545194/f2675009-f7e3-475a-aa8c-29654acc1e75)
![image](https://github.com/google/site-kit-wp/assets/73545194/a36182c5-569e-4410-a470-7fe11fc65182)
![image](https://github.com/google/site-kit-wp/assets/73545194/b2c684e7-1e85-4ee4-87f8-441f5b87ece8)
![image](https://github.com/google/site-kit-wp/assets/73545194/d74eaefc-e587-47fe-a67e-34d65acf599a)

</details>
