### ISSUE TITLE
Create "Visits per visitor" key metric widget tile

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7577]
## Feature Description

![image](https://github.com/google/site-kit-wp/assets/20284937/c5241730-1661-4de7-aa71-19be8bbd6851)
(screenshot for reference - see Figma for latest version)

A new key metric widget tile should be added for "Visits per visitor".

See:
1. [Table of metrics in design doc](https://docs.google.com/document/d/1htqStvvyXq_eg5GsHSbdBBgm4Tu_Z6KXsIOBfjWQ5oM/edit?resourcekey=0-Px-yDiCQOTz30DBKllhU3g#heading=h.5u6oy5c2u65e).
2. [List of metrics in PRD](https://docs.google.com/document/d/1UZ2VXOxpsY3GiHgQncZIb73Uy-xVf15MWJi46QkK_X0/edit?resourcekey=0-dB9ROp2h3ZYhqoyYBMTzvw#bookmark=id.usf86uc2bsda).
3. [Figma designs](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60033&mode=design&t=nUObjDPmn7ra177i-4).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- A new component should be created for the "Visits per visitor" key metric widget tile and should be displayed within the Key Metrics Widget area if its widget slug is added to the `widgetSlugs` array of key metrics settings.
  - The component should look exactly as its [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60033&mode=design&t=nUObjDPmn7ra177i-4).
  - Its widget slug should be `kmAnalyticsVisitsPerVisitor` (so that it is consistent with the design doc).
  - The metric tile title should be `Visits per visitor`.
  - Its description tooltip should say `Average number of sessions per site visitor`.
  - This metric should be dependent on the `analytics-4` module, so it should only be rendered in the key metrics widget area if GA4 is connected, otherwise, `ConnectGA4CTATileWidget` should be rendered (similar to existing GA4-dependent metric tiles). It should also not be shown to view-only users who do not have shared access to GA4.
- The following data should be fetched from the [Google Analytics Data API](https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema) for the global date range selected on the Site Kit dashboard:
  - Metrics: `sessionsPerUser` and `sessions`
- Values:
  - The primary value should be the average number of sessions per visitor, obtainable using the `sessionsPerUser` metric.
  - The secondary value (`total visits`) should be the total number of sessions, obtainable using the `sessions` metric.
- The percentage change figure (with a red for negative or green for positive highlight) should be calculated based on the 'previous' period before the selected date range, for the primary metric `sessionsPerUser`.
- The metrics & dimensions used in the reports for this tile should be allow-listed for view-only users.
- This metric should be available for selection in the key metrics selection panel only if the `newsKeyMetrics` feature flag is enabled.

## Implementation Brief

* In `assets/js/modules/analytics-4/components/widgets/`, create a new `VisitsPerVisitorWidget.js` component. This [POC commit](https://github.com/google/site-kit-wp/compare/develop...enhancement/7575-KMW-pages-per-visit-tile) has already created a similar component for the `Pages Per Visit` KMW tile which could be a good starting point instead of using the `NewVisitorsWidget.js`. But if using the `NewVisitorsWidget` as a starting point, then make the following changes:
    * Update `reportOptions` to fetch the `sessionsPerUser` and `totalUsers` metrics. No other dimensions or metrics are needed.
    * Update the `makeFind` method to only find rows where the `dimensionValues` match a passed `dateRange`.
    * Use this method to compute the `currentVisitsPerVisitor` and the `previousVisitsPerVisitor` by extracting the appropriate metric values from the `rows` returned from the `report` for `date_range_0` and `date_range_1` respectively.
      * Pass the `currentVisitsPerVisitor` to the `metricValue` prop of the `<MetricTileNumeric>` component.
      * Pass `currentVisitsPerVisitor` and `previousVisitsPerVisitor` to the `currentValue` and `previousValue` props of the `<MetricTileNumeric>` component.
    * Extract the `currentTotalVisitors` by extracting the appropriate metric values from `rows` using the `makeFind` method above. 
      * Pass the `currentTotalVisitors` within the `subText` prop and update the text as per the AC.
    * Note: Cast all of the above to `Number()` as done in `NewVisitorsWidget`.
    * Update the `title` prop of the `<MetricTileNumeric>` component as per the AC.
* In `assets/js/googlesitekit/datastore/user/constants.js`:
  * Export a new constant for defining the new widget's slug: `KM_ANALYTICS_VISITS_PER_VISITOR = 'kmAnalyticsVisitsPerVisitor'`
  * Add this constant to the `keyMetricsGA4Widgets` array.
* In `assets/js/modules/analytics-4/index.js`:
  * Register the new key metric widget exactly the same as other key metric widgets. However, wrap the registration using the new `newsKeyMetrics` feature flag.
* In `includes/Modules/Analytics_4/Report/Request.php`:
  * Ensure the `sessionsPerUser` metric is added to the list of shareable metrics in the `validate_shared_metrics` method.
* Wait for #7472 to be merged and use the same approach in that issue to add the tooltip as per the AC.

### Test Coverage

* Add storybook stories using `NewVisitorsWidget.stories.js` as a starting point and create stories for the Ready, Zero, Loading and Error states. 
    * Add VRT snapshots for the Ready and Zero states.

## QA Brief

* Ensure the new `newsKeyMetrics` feature flag is enabled / turned on in the Site Kit Tester plugin settings.
* Verify that the "Visits per visitor" widget appears in the Metrics selection panel. Select this metric and verify the ACs. *
* Ensure this metric does not appear in the metrics panel if the feature flag above is not enabled.
* Verify the metric works on both the view-only as well as authenticated dashboards.
* Verify the correct metric values by searching for `Sessions per user` in GA4 dashboard, i.e `Sessions per user last 28 days`, screenshot to follow:

<img width="648" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/e51c39ab-1a54-431e-8bd9-4608201e1982">

* Verify/test the stories, they will appear under `Key Metrics > VisitsPerVisitor`
 

## Changelog entry

* Add the "Visits per Visitor" Key Metric Widget.

**Comment by tofumatt** [comment]
ACs look good, moving to IB 🙂

**Comment by 10upsimon** [comment]
@jimmymadon @nfmohit as raised in [this Slack thread](https://10up.slack.com/archives/CBKKQEBR9/p1695714292792159), I have noticed difference in two key areas of this KMW tile as opposed to others:

- The Figma references the subtext as "total readers" as opposed to "total visitors". Following guidance from @nfmohit (and given that it is in the AC/IB as well) I have made it "Total visitors" to be in line with other KMW tiles.
- Importantly, I am noting a difference in "total visitors" value in this new tile vs an existing one like Loyal Visitors. Upon further inspection, I note that the Loyal Visitors tile uses the `activeUsers` metric whereas the IB for this widget states to use `totalUsers`. I think we need to pick one and stick with it throughout so as not to mislead the user.

I will await a final decision on which metric to use, from either of you @jimmymadon or @nfmohit .

Thank you!

**Comment by 10upsimon** [comment]
Updating as per the continued discussion in [this Slack thread](https://10up.slack.com/archives/CBKKQEBR9/p1695714292792159), which also referenced [a prior Slack conversation](https://10up.slack.com/archives/CFFRMC5DE/p1687451546956519) around active vs total users:

It was discussed that `activeUsers` will be used over `totalUsers` as outlined in this issues IB, to remain consistent with the other metric tiles where the same subText wording is used.

cc @jimmymadon @bethanylang @nfmohit

**Comment by 10upsimon** [comment]
Note to reviewer, there is a known issue with failing PHP 7.4 WP Nightly build PHP tests. [See Slack thread here](https://10up.slack.com/archives/CBKKQEBR9/p1695891206214499).

**Comment by 10upsimon** [comment]
Update on tests, 3 failures with known issues at present:

1. E2E (WordPress Latest) - 1 failure, failing at User Input Settings  which sounds like it's a known issue.
2. E2E (WordPress Nightly) - 8 failures, failing at User Input Settings  and deprecation notices.
3. PHP Tests (PHP 7.4, WordPress Nightly) - Failing at deprecation notices.

**Comment by bethanylang** [comment]
@10upsimon Quick update needed here: @marrrmarrr got some feedback from the News team that they would like this tile to change the context under the metric from "1,234 total visitors" to "1,234 total visits":

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEhxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4f640e42e59615b389b9e2eb35020d0d3ca9fd9a/image.png)

Can you please make this change? Thanks much!

**Comment by 10upsimon** [comment]
Update on tests, 2 failures with known issues at present:

1. E2E (WordPress Latest) - Failing at User Input Settings which sounds like it's a known issue.
2. E2E (WordPress Nightly) - Failing at User Input Settings and deprecation notices.

**Comment by 10upsimon** [comment]
@bethanylang this is back in Code Review after effecting the wording changes you highlighted above.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- A new tile is created for the `Visits per visitor` and is displayed when selected.
- The tile looks as its [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60033&mode=design&t=nUObjDPmn7ra177i-4).
-  Its widget slug is `kmAnalyticsVisitsPerVisitor (so that it is consistent with the design doc).
- The metric tile title is `Visits per visitor`.
- Its description tooltip says `Average number of sessions per site visitor.`
- The metric tile only appears when the analytics-4 module is connected. 
- The primary value is the average number of session per visitor.
- The secondary value (total visitors) is the total number of users.
- The percentage change figure is calculated based on the 'previous' period before the selected date range.
- The tile, metric dimensions are available for view-only users.
- The tile is available for selection in the key metrics selection panel only if the newsKeyMetrics feature flag is enabled.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/8cf23220-d5cb-43e5-b7a6-1b618ff5f00d)
![image](https://github.com/google/site-kit-wp/assets/73545194/8cdc71af-d081-49fa-9176-7c390a557192)
![image](https://github.com/google/site-kit-wp/assets/73545194/de94b1d4-34e6-4c38-9c70-996c62c4e674)
![image](https://github.com/google/site-kit-wp/assets/73545194/761aed23-b822-48df-934d-8ac3539eda5b)

</details>

**Comment by 10upsimon** [comment]
AC's for this issue were update following merge, to accommodate for the changed metric used for the `Total visits` subText value. The metric change from `activeUsers` to `sessions`. The accompanying Slack thread can be found [here](https://10up.slack.com/archives/CBKKQEBR9/p1696498207492979).

**Comment by wpdarren** [comment]
### QA Update: ✅ 

- A new tile is created for the Visits per visitor and is displayed when selected.
- The tile looks as its [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60033&mode=design&t=nUObjDPmn7ra177i-4).
- Its widget slug is `kmAnalyticsVisitsPerVisitor (so that it is consistent with the design doc).
- The metric tile title is Visits per visitor.
Its description tooltip says Average number of sessions per site visitor.
- The metric tile only appears when the analytics-4 module is connected.
- The primary value is the average number of sessions per visitor, obtainable using the sessionsPerUser metric.
- The secondary value (total visits) should be the total number of sessions, obtainable using the sessions metric.
- The percentage change figure (with a red for negative or green for positive highlight) should be calculated based on the 'previous' period before the selected date range, for the primary metric sessionsPerUser.
- The tile, metric dimensions are available for view-only users.
- The tile is available for selection in the key metrics selection panel only if the newsKeyMetrics feature flag is enabled.
- The stories appear under VisitsPerVisitor and work as expected.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/aa4c60d4-6722-4819-a1e2-e160fb4be753)
![image](https://github.com/google/site-kit-wp/assets/73545194/1d8bdbca-eab3-49f5-acf0-09a094a0a3ea)
![image](https://github.com/google/site-kit-wp/assets/73545194/8cf23220-d5cb-43e5-b7a6-1b618ff5f00d)
![image](https://github.com/google/site-kit-wp/assets/73545194/8cdc71af-d081-49fa-9176-7c390a557192)
![image](https://github.com/google/site-kit-wp/assets/73545194/de94b1d4-34e6-4c38-9c70-996c62c4e674)
![image](https://github.com/google/site-kit-wp/assets/73545194/761aed23-b822-48df-934d-8ac3539eda5b)

</details>
