### ISSUE TITLE
Create "Least engaging pages" key metric widget tile

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7579]
## Feature Description

![image](https://github.com/google/site-kit-wp/assets/20284937/1ba8bcc7-66f2-4571-89aa-2a6ff700054f)
(screenshot for reference - see Figma for latest version)

A new key metric widget tile should be added for "Least engaging pages".

See:
1. [Table of metrics in design doc](https://docs.google.com/document/d/1htqStvvyXq_eg5GsHSbdBBgm4Tu_Z6KXsIOBfjWQ5oM/edit?resourcekey=0-Px-yDiCQOTz30DBKllhU3g#heading=h.5u6oy5c2u65e).
2. [List of metrics in PRD](https://docs.google.com/document/d/1UZ2VXOxpsY3GiHgQncZIb73Uy-xVf15MWJi46QkK_X0/edit?resourcekey=0-dB9ROp2h3ZYhqoyYBMTzvw#bookmark=id.usf86uc2bsda).
3. [Figma designs](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60073&mode=design&t=nUObjDPmn7ra177i-4).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- A new component should be created for the "Least engaging pages" key metric widget tile and should be displayed within the Key Metrics Widget area if its widget slug is added to the `widgetSlugs` array of key metrics settings.
  - The component should look exactly as its [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60073&mode=design&t=nUObjDPmn7ra177i-4).
  - Its widget slug should be `kmAnalyticsLeastEngagingPages` (so that it is consistent with the design doc).
  - The metric tile title should be `Least engaging pages`.
  - Its description tooltip should say `Pages with the highest bounce rate (visitors who left without any meaningful engagement with your site)`.
  - This metric should be dependent on the `analytics-4` module, so it should only be rendered in the key metrics widget area if GA4 is connected, otherwise, `ConnectGA4CTATileWidget` should be rendered (similar to existing GA4-dependent metric tiles). It should also not be shown to view-only users who do not have shared access to GA4.
- The following data should be fetched from the [Google Analytics Data API](https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema) for the global date range selected on the Site Kit dashboard:
  - Metrics: `bounceRate` and `screenPageViews`
  - Dimensions: ~`unifiedPagePathScreen` and `pageTitle`~ UPDATE: `pagePath` should be sufficient here. See this [comment](https://github.com/google/site-kit-wp/issues/7584#issuecomment-1731209171).
  - Order by metric: `bounceRate` descending, then `screenPageViews` descending
  - Filter by: `screenPageViews` >= "Median number of `screenPageViews`" (median screen page views can be calculated as part of a separate report).
- Values:
  - It should be a table pattern metric tile, with the `pageTitle` showing up as the first column, and `bounceRate` showing up as the second column (with percentage).
- The metrics & dimensions used in the reports for this tile should be allow-listed for view-only users.
- This metric should be available for selection in the key metrics selection panel only if the `newsKeyMetrics` feature flag is enabled.

## Implementation Brief

* In `assets/js/modules/analytics-4/components/widgets/`, create a new `LeastEngagingPagesWidget.js` component.
  * Use the `PopularContentWidget.js` file as a starting point, then make the following changes:
    * To calculate the `medianPageViews` needed for the filter, create a new `pageViewsReport` with the following options:
    ```javascript
    const pageViewsReportOptions = {
      ...dates,
      dimensions: [ 'pagePath' ],
      metrics: [ { name: 'screenPageViews' } ],
      orderby: [
        {
          metric: { metricName: 'screenPageViews' },
          desc: true,
        },
      ],
    };
    ```
    * Calculate the median by extracting the page views of the page that is at the mid-point (`rowCount / 2`) of the ordered array of rows returned:
    ```javascript
    const medianIndex = parseInt( pageViewsReport?.rowCount / 2, 10 );
    const medianPageViews =
      parseInt(
        pageViewsReport?.rows?.[ medianIndex ]?.metricValues[ 0 ].value,
        10
      ) || 0;
    ```
    * Update `reportOptions` to include the metrics and dimensions as per the AC and filter the metrics by the `medianPageViews`:
    ```javascript
    const reportOptions = {
      ...dates,
      dimensions: [ 'pagePath' ],
      metrics: ['bounceRate',  'screenPageViews' ],
      orderby: [
        {
          metric: { metricName: 'bounceRate' },
          desc: true,
        },
        {
          metric: { metricName: 'screenPageViews' },
          desc: true,
        },
      ],
      metricFilters: {
        screenPageViews: {
          filterType: 'numericFilter',
          operation: 'GREATER_THAN_OR_EQUAL',
          value: { int64Value: averagePageViews },
        },
      },
      limit: 3,
    };
    ```
    * When computing the `columns`, ensure the `bounceRate` is displayed as a percentage (1 = 100%, 0.89 = 89%). Since this is the first in the list of metrics, the field paths within the columns calculation should be the same.
    * Update the `loading` and `error` states to check for the resolution of the additional `pageViewsReport`.
    * Update the `title` and `infoTooltip` props of the `<MetricTileTable>` component as per the AC.
* In `assets/js/googlesitekit/datastore/user/constants.js`:
  * Export a new constant for defining the new widget's slug: `KM_ANALYTICS_LEAST_ENGAGING_PAGES = 'kmAnalyticsLeastEngagingPages'`
  * Add this constant to the `keyMetricsGA4Widgets` array.
* In `assets/js/modules/analytics-4/index.js`:
  * Register the new key metric widget exactly the same as other key metric widgets. However, wrap the registration using the new `newsKeyMetrics` feature flag.
* In `includes/Modules/Analytics_4/Report/Request.php`:
  * Ensure the `bounceRate` and `screenPageViews` metrics are added to the list of shareable metrics in the `validate_shared_metrics` method.

### Test Coverage

* Add storybook stories using `PopularContentWidget.stories.js` as a starting point and create stories for the Ready, Zero, Loading and Error states. 
    * Add VRT snapshots for the Ready and Zero states.

## QA Brief

* Setup Site Kit
* Enable `ga4`, `userInput` and `newsKeyMetrics` feature flags
* Setup key metrics, and select to include `Least engaging pages` metric
* Verify that widget is showing data by displaying pages with highest bounce rates, and looks like in figma design
* Verify that in view only mode widget is listing pages without links

## Changelog entry

* Create "Least engaging pages" key metric widget tile.

**Comment by bethanylang** [comment]
+1 to @techanvil's suggestion!

**Comment by nfmohit** [comment]
Excellent suggestion, updated, thank you @techanvil!

**Comment by techanvil** [comment]
Top stuff, thanks @nfmohit. IB :white_check_mark:

**Comment by techanvil** [comment]
Hi @jimmymadon , this IB is looking good. Maybe a few more code snippets than we tend to use, but it seems reasonable to me in this context. A couple of minor points -

- Regarding the following point in the IB, the `metrics` array in the preceding code snippet actually has `bounceRate` as the second entry, it looks like it should in fact be first?
> Since this is the first in the list of metrics, the field paths within the columns calculation should be the same.

- I'd suggest adding a point to the IB to help clarify the following AC point, for clarity's sake and to help ensure it's not missed:
> The metrics & dimensions used in the reports for this tile should be allow-listed for view-only users.

**Comment by techanvil** [comment]
Thanks @jimmymadon! IB LGTM :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on main environment.
- Verified:
- The component look exactly as its [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60073&mode=design&t=nUObjDPmn7ra177i-4).
- Its widget slug is kmAnalyticsLeastEngagingPages 
- The metric tile title is Least engaging pages.
- Its description tooltip say Pages with the highest bounce rate (visitors who left without any meaningful engagement with your site).
- This metric is dependent on the analytics-4 module, and it rendered in the key metrics widget area if GA4 is connected, otherwise, ConnectGA4CTATileWidget is rendered (similar to existing GA4-dependent metric tiles).
- Verified that widget tile is showing on View only dashboard if analytics is shared.
- Verified that widget tile is not showing on View only dashboard if analytics is not shared.
- Verified that on view only dashboard view only mode widget is listing pages without links

<details>

Main dashboard

![image](https://github.com/google/site-kit-wp/assets/94359491/f12532f8-e040-4487-8b34-aa720029e224)

View only dashboard

![image](https://github.com/google/site-kit-wp/assets/94359491/e20a6580-1fd9-48f4-bf0b-8d788e0f8d2f)

![image](https://github.com/google/site-kit-wp/assets/94359491/9d364db6-e5b3-4992-be69-b43a369eecfa)

![image](https://github.com/google/site-kit-wp/assets/94359491/96825a82-c080-4ded-8d85-dc424a8f99ec)

</details>


 @zutigrm @jimmymadon 

**Question** : I did not find any direct report but using explore tool and with the help of @wpdarren I created report following Acceptance criteria. 

I've notice that in report multiple pages have 50% bounce rate but we are showing only first page in the list then skipping to next page with different bounce rate 33.3. Is this correct or you use different method to verify data ?

![image](https://github.com/google/site-kit-wp/assets/94359491/9aac7c3e-78d9-43a6-a365-93299b38f2f2)

![image](https://github.com/google/site-kit-wp/assets/94359491/c35774fe-e449-467f-a20f-6307b2719dca)

**Comment by zutigrm** [comment]
@mohitwp Thank you for the feedback. The report uses screen page views into the account as well. It takes bounce rate pages based on the median value of page views, which is `3` for `oi.ie` website. If you look into the last column in your screenshot - `Views` You will find that views for mentioned pages with 50% bounce rate bellow `3`, mostly are `2` and `1`, so they are not taken into the account and `metricFilter` is not returning them

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thank you @zutigrm !

- Tested on main environment.
- Verified:
- The component look exactly as its [Figma mock](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273-60073&mode=design&t=nUObjDPmn7ra177i-4).
- Its widget slug is kmAnalyticsLeastEngagingPages 
- The metric tile title is Least engaging pages.
- Its description tooltip say Pages with the highest bounce rate (visitors who left without any meaningful engagement with your site).
- This metric is dependent on the analytics-4 module, and it rendered in the key metrics widget area if GA4 is connected, otherwise, ConnectGA4CTATileWidget is rendered (similar to existing GA4-dependent metric tiles).
- Verified that widget tile is showing on View only dashboard if analytics is shared.
- Verified that widget tile is not showing on View only dashboard if analytics is not shared.
- Verified that on view only dashboard view only mode widget is listing pages without links.
- Verified widget tile data using explore tool and information under AC.

<details>

Main dashboard

![image](https://github.com/google/site-kit-wp/assets/94359491/f12532f8-e040-4487-8b34-aa720029e224)

View only dashboard

![image](https://github.com/google/site-kit-wp/assets/94359491/e20a6580-1fd9-48f4-bf0b-8d788e0f8d2f)

![image](https://github.com/google/site-kit-wp/assets/94359491/9d364db6-e5b3-4992-be69-b43a369eecfa)

![image](https://github.com/google/site-kit-wp/assets/94359491/96825a82-c080-4ded-8d85-dc424a8f99ec)

![image](https://github.com/google/site-kit-wp/assets/94359491/9aac7c3e-78d9-43a6-a365-93299b38f2f2)

![image](https://github.com/google/site-kit-wp/assets/94359491/c35774fe-e449-467f-a20f-6307b2719dca)

</details>
