### ISSUE TITLE
An error occurred: We were unable to send credentials to your WordPress site

### ISSUE THREAD

**Issue by drcrow** [google/site-kit-wp#760]
I get the error message:

"An error occurred: We were unable to send credentials to your WordPress site. Please go back to your site and restart the setup. The following error was returned: No se encontró la ruta que coincida con la URL y el método de la petición"

![g1](https://user-images.githubusercontent.com/5630560/68034077-cebcf380-fc9f-11e9-8413-269ce1de7484.jpg)

Chrome console show this error:

log.js:244 [amp-form] Form submission failed: Error: HTTP error 403​​​
    at $a (https://cdn.ampproject.org/v0.js:27:169)
    at Wa.f.createError (https://cdn.ampproject.org/v0.js:22:257)
    at https://cdn.ampproject.org/v0.js:143:409
    at new Promise (<anonymous>)
    at mg (https://cdn.ampproject.org/v0.js:143:344)
    at https://cdn.ampproject.org/v0.js:144:423
Ya @ log.js:244
f.va @ log.js:299
f.error @ log.js:316
Bc @ amp-form.js:968
(anonymous) @ amp-form.js:954

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* N/A

## Implementation Brief

* N/A

## Changelog entry

* Improve compatibility with sites that have a `http://` website address stored as `home_url`, but actually require HTTPS.

**Comment by felixarntz** [comment]
Thanks for the report @drcrow!

This issue happens because your website address option (`homeurl`) is likely set to a URL starting with `http://`, while your site is actually using HTTPS and redirecting to that protocol.

We just pushed an update to our authentication service that should resolve this for the particular issue you're reporting. However, I'd recommend to properly change your website address option in WordPress to use `https://` to prevent any future related issues with the configuration.
