### ISSUE TITLE
Enhance handling of field data availability in PageSpeed widget

### ISSUE THREAD

**Issue by gilbertococchi** [google/site-kit-wp#7662]
<img width="1146" alt="Screenshot 2023-10-03 at 19 41 54" src="https://github.com/google/site-kit-wp/assets/329023/11e4ddf3-4ecb-4e33-8dab-276af8ff82fb">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Field data unavailable" state on the Field tab should only be shown if all field data metrics are unavailable (currently is shown if _any_ of the main 3 are unavailable)
	* If any metric is available, all field metric rows should be displayed, with any unavailable metrics displayed as below
* For any unavailable metric
	* The row's text color should be gray (consistent with other unavailable/disabled states), including its title, description, and value
	* The value should be represented as `—` with no units
	* The rating should be replaced by "gathering data"
	* The height of the metric should be consistent with its data-available variant
	* The metric title should be appended with an info icon that displays a tooltip on hover (similar to metric tiles):  
	> Field data is still being gathered for this metric and will become available once your site gets sufficient traffic.

## Implementation Brief

* In `assets/js/modules/pagespeed-insights/components/common/FieldReportMetrics.js`:
    * Only render the `div` with `googlesitekit-pagespeed-insights-web-vitals-metrics--field-data-unavailable` classname when all the `largestContentfulPaint`, `cumulativeLayoutShift`, `firstInputDelay` and `interactionToNextPaint` are unavailable. 
    * Pass `isUnavailable` prop to the `ReportMetric` elements checking whether the respective field data is available. ie. ` ! interactionToNextPaint`.
* In `assets/js/modules/pagespeed-insights/components/common/ReportMetric.js`:
    * Implement the `field-data-unavailable` state according to the AC when the `isUnavailable` prop is true. 
        * Add `googlesitekit-pagespeed-report__row--isUnavailable` class to the `tr` and apply appropriate styles.
        * Replace the `displayValue` with `—`
        * Add logic to show  the translatable string `gathering data` inside `div.value__rating`. 
        * Add a `InfoTooltip` on the right side of the `title` with the text from AC. 
             * This should be done in a similar way to how it's done on[ `MetricTileHeader`
](https://github.com/google/site-kit-wp/blob/5aafc62bfa9449790264593dba048da530ee54a7/assets/js/components/KeyMetrics/MetricTileHeader.js#L31-L34)
            * Either a Pagespeed Insight version of the `InfoTooltip` component should be created and used here, or the current `assets/js/components/KeyMetrics/InfoTooltip.js` should be moved to common `assets/js/components` folder, refactored and used in both Key Metrics and here - whichever makes more sense during development. 

### Test Coverage

* Add stories for the partial field data available states in `assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeedWidget.stories.js`. 

## QA Brief

- Set up Site Kit on a site that doesn't have all field data collected (i.e. it has partial data).
- Go to the PageSpeed Insights widget in SK dashboard and verify that rows appear in "In the Field" tab.
- For metrics that don't have data yet, verify that their text is greyed out, and they appear as described in the ACs.
- Verify the `Modules -> PageSpeed Insights -> Widgets -> DashboardPageSpeedWidget -> Partial Field Data Available` Storybook story.

## Changelog entry

* Fixed a bug that prevented displaying of field data unless all fields were available in the PageSpeed Insight widget.

**Comment by gilbertococchi** [comment]
It would be ideal to consider the case where INP (as well as FID) could be undefined in the PSI API JSON response (screenshot below without any "EXPERIMENTAL_TIME_TO_FIRST_BYTE" Object key).

<img width="403" alt="Screenshot 2023-10-03 at 20 28 07" src="https://github.com/google/site-kit-wp/assets/329023/77098c86-e273-459b-bc22-672a42a4ebf6">

**Comment by rviscomi** [comment]
Shot in the dark, but could Site Kit still be referring to the [experimental](https://web.dev/inp-cwv/#evolving-inp) INP value? As of August 8 the field was renamed across Web Vitals APIs.
<img width="802" alt="image" src="https://github.com/google/site-kit-wp/assets/1120896/e77b34cd-52be-4f53-b9f4-68b11c0799fa">

**Comment by felixarntz** [comment]
Thanks @gilbertococchi!

@rviscomi I don't think that's the case, we already look at the non-experimental metric AFAIK. But maybe another check is missing for when the metric is not set.

@aaemnnosttv Could this bug fix be prioritized for one of the next releases?

**Comment by gilbertococchi** [comment]
I think it's assuming that this metric always exist: https://github.com/google/site-kit-wp/blob/91ce4cd17f8d234c5baef2364b62cc641f532e6b/assets/js/modules/pagespeed-insights/components/common/FieldReportMetrics.js#L46

**Comment by bethanylang** [comment]
Hi @gilbertococchi and @felixarntz! We're on a hard deadline for some new features at the moment, but I think we can fit this in to our sprint beginning Oct 23. I'll earmark it for that sprint so you should see updates coming in after that.  :) 

@aaemnnosttv Assigning this over to you for AC.

**Comment by marrrmarrr** [comment]
@aaemnnosttv this mostly LGTM, my only comment is that for the majority of SK sites it's likely field metrics might be in this "gathering data" state for a long time (since few of them are in CrUX) -- should we consider adding some info icon or similar here to explain data will show once there are enough visitors to the site?

**Comment by aaemnnosttv** [comment]
> should we consider adding some info icon or similar here to explain data will show once there are enough visitors to the site?

@marrrmarrr that sounds good to me, I'll update the AC to include an info icon+tooltip for metrics that are in this state 👍

**Comment by aaemnnosttv** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@nfmohit I have an observation on mobile.  The rating text is quite close to the description in some resolutions. For example in my screenshots you can see on the Pixel 5 the `gathering data` and on the iPhone SE the `Good` ratings are close. I realise space is tight on these older mobiles, but thought I would flag it for your thoughts. 


<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/20bc3fd9-f684-451e-9a43-3469deb9cbb4)
![image](https://github.com/google/site-kit-wp/assets/73545194/231553b1-826d-4825-909e-c9f00cce2a31)

</details>


**Verified:**

- Tested on a new site where all field data is unavailable.  The behaviour is the same in that the title `Field data unavailable` and subsequent text appears `Field data shows how real users actually loaded and interacted with your page. We don’t have enough real-world experience and speed data for this page. It may be new, or not enough users with Chrome browsers have visited it yet.` This is matches what I see in Storybook. 
- Tested on a site that doesn't have all field data collected (i.e. it has partial data). 
- All field metric rows are displayed, with any unavailable metrics displayed as below:
  - The row's text color is gray including its title, description, and value.
  - The value is represented as `—` with no units
  - The rating is replaced by "gathering data"
  - The height of the metric is  consistent with its data-available variant
  - The metric title is appended with an info icon that displays a tooltip on hover.
  - The tooltip text is: `Field data is still being gathered for this metric and will become available once your site gets sufficient traffic.`
- Checked on the mobile and desktop tab within Page Speed Insights widget. 
- Tested on desktop and smaller viewports like mobile and tablets. 
- Tested on our supported browsers, Chrome, Safari, etc. 
- Checked the Stories to ensure they are appearing as per the AC. 
Tested on a site that has all the field data available.  Made sure that everything loaded as expected and no UX/UI issues occurred due to the change. 

Note: I do have a few UI observations that are out of scope for this ticket so will create a new one. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/d7b17143-97dd-4218-9ce3-5c6eab4db830)
![image](https://github.com/google/site-kit-wp/assets/73545194/3d0d60c6-7275-4e42-ac2a-2497aa948b9f)
![image](https://github.com/google/site-kit-wp/assets/73545194/4c0dffef-042b-4a6a-8996-c7cde0183b00)
![image](https://github.com/google/site-kit-wp/assets/73545194/20bc3fd9-f684-451e-9a43-3469deb9cbb4)
![image](https://github.com/google/site-kit-wp/assets/73545194/231553b1-826d-4825-909e-c9f00cce2a31)
![image](https://github.com/google/site-kit-wp/assets/73545194/58d10c27-5f04-4234-851e-e2629c31323a)

</details>

**Comment by nfmohit** [comment]
> ### QA Update: ⚠️
> @nfmohit I have an observation on mobile. The rating text is quite close to the description in some resolutions. For example in my screenshots you can see on the Pixel 5 the `gathering data` and on the iPhone SE the `Good` ratings are close. I realise space is tight on these older mobiles, but thought I would flag it for your thoughts.

Hi @wpdarren, thank you for sharing your observation. While I think this is outside the scope of this issue, I've opened a [follow-up PR](https://github.com/google/site-kit-wp/pull/7791) that aims to improve this. Thanks!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Tested on a new site where all field data is unavailable.  The behaviour is the same in that the title `Field data unavailable` and subsequent text appears `Field data shows how real users actually loaded and interacted with your page. We don’t have enough real-world experience and speed data for this page. It may be new, or not enough users with Chrome browsers have visited it yet.` This is matches what I see in Storybook. 
- Tested on a site that doesn't have all field data collected (i.e. it has partial data). 
- All field metric rows are displayed, with any unavailable metrics displayed as below:
  - The row's text color is gray including its title, description, and value.
  - The value is represented as `—` with no units
  - The rating is replaced by "gathering data"
  - The height of the metric is  consistent with its data-available variant
  - The metric title is appended with an info icon that displays a tooltip on hover.
  - The tooltip text is: `Field data is still being gathered for this metric and will become available once your site gets sufficient traffic.`
- Checked on the mobile and desktop tab within Page Speed Insights widget. 
- Tested on desktop and smaller viewports like mobile and tablets. 
- Tested on our supported browsers, Chrome, Safari, etc. 
- Checked the Stories to ensure they are appearing as per the AC. 
- Tested on a site that has all the field data available. Made sure that everything loaded as expected and no UX/UI issues occurred due to the change. 

Note: I do have a few UI observations that are out of scope for this ticket so will create a new one. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/9327723f-0bde-43ee-ae90-943e7778575e)
![image](https://github.com/google/site-kit-wp/assets/73545194/1ae354f2-94c9-49be-8d30-b50e81193901)
![image](https://github.com/google/site-kit-wp/assets/73545194/d7b17143-97dd-4218-9ce3-5c6eab4db830)
![image](https://github.com/google/site-kit-wp/assets/73545194/3d0d60c6-7275-4e42-ac2a-2497aa948b9f)
![image](https://github.com/google/site-kit-wp/assets/73545194/4c0dffef-042b-4a6a-8996-c7cde0183b00)
![image](https://github.com/google/site-kit-wp/assets/73545194/20bc3fd9-f684-451e-9a43-3469deb9cbb4)
![image](https://github.com/google/site-kit-wp/assets/73545194/231553b1-826d-4825-909e-c9f00cce2a31)
![image](https://github.com/google/site-kit-wp/assets/73545194/58d10c27-5f04-4234-851e-e2629c31323a)

</details>
