### ISSUE TITLE
Site Kit excessively attempts to send features requests when not using the proxy service

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#7717]
## Bug Description

When using the legacy setup flow not connected to the proxy (e.g. on a staging/development site), Site Kit still attempts to request the active features endpoint from the service. This is likely because it sees that Site Kit is connected, while missing a check to see whether it is connected _to the service_.

On my staging site this led to excessive unsuccessful requests (up to 25 requests per single WP Admin page load), slowing down response from ~1s to more than 10 seconds.

For now I added this workaround to my site:
```php
if ( wp_get_environment_type() !== 'production' ) {
	add_action(
		'googlesitekit_init',
		static function () {
			remove_all_filters( 'googlesitekit_is_feature_enabled' );
		}
	);
}
```

While it drastically reduces the number of attempted requests, Site Kit still makes some requests, likely because some of the feature checks happening extremely early in the plugin's bootstrap process.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Authentication::filter_features_via_proxy` method should fetch remote features only if the site is connected using proxy. 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment]
@aaemnnosttv @eugene-manuilov Just flagging this one for you to review!

**Comment by eugene-manuilov** [comment]
@aaemnnosttv does AC look good to you?

**Comment by aaemnnosttv** [comment]
I've updated #6015 to address this as part of that issue which will already solve the main problem raised here since it calls for no longer fetching features on-demand and instead always uses the option value. The update to that issue (which is now in the EB) is just a small tweak to guard fetching features if not connected to the proxy, but that's a minor enhancement compared to the main issue here. No need to keep this open as a tracking issue since it's covered by the updated AC.
