### ISSUE TITLE
Metric tiles shift on load

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7763]
## Bug Description

As reported by @aaemnnosttv in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205787987913306/f)):

There is a small layout shift observable between loading and loaded states for some tiles. I have seen it go both ways (shorter to taller, and vice versa) depending on which tiles are present.

https://github.com/google/site-kit-wp/assets/12189958/66edd864-ec68-4793-ab00-44000d4a4f78

https://github.com/google/site-kit-wp/assets/12189958/fbd9dfbb-18bc-4ae8-822c-582d016be9ff

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The key metric tiles in all their states (i.e. loading, error, zero, gathering, and ready) should consistently have the same height.
- The height in between any state shouldn't change to prevent layout shifts.

## Implementation Brief

* Set tiles `min-height` (for desktop) to match the [Figma design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7286-16900&mode=design&t=e44ybybvQD3fvMLc-0), which should be `150px`
* Following the merge of #7769 , in `assets/js/components/KeyMetrics/MetricTileLoader.js`:
  * Adjust the value for `height` prop in `PreviewBlock` components to match the min tile height 
* Tiles should maintain the fluid height on mobile
* Update error state tile for mobile per new [design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273%3A68010&mode=design&t=QIa3v58T8wVKJGBP-1), and other tiles are also having modified [design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7478-15011&mode=design&t=oZDKWppvjrZysPWH-0)
* Ensure loading state on mobile is not causing the tiles to flicker in height. You can use `smallHeight` prop of `PreviewBlock` component, to set unified height for numeric, text and table tiles (by setting it to the expected content height)

### Test Coverage

* Update VRT reference images

## QA Brief

* There should be no layout shift in Desktop/Tablet in various states of KM widgets (ready, loading, error etc). The height should be more or less equal (~150px).
* The error states on mobile should have the new design that is linked in the IB. 

## Changelog entry

* Minimize layout shifts in Key Metric tiles.

**Comment by aaemnnosttv** [comment]
AC ✅

**Comment by techanvil** [comment]
Hi @zutigrm, the IB as you've drafted it covers the desktop view up to a point - although the error states need a bit of additional consideration, because at present they are over 150px in height.

![image](https://github.com/google/site-kit-wp/assets/18395600/10b9cede-47ec-460d-9861-6c59b18d7ce6)

We should be able to bring it down to 150px, in line with the Figma design. It's worth noting that in Figma the height of the Retry button has been reduced a bit to help achieve this.

![image](https://github.com/google/site-kit-wp/assets/18395600/f315742d-04ed-4c68-a416-d726bb1b3bce)

However, an additional area we need to consider is the mobile view. Applying a fixed height of 150px to the widgets would not align with the Figma design where the widgets don't have a uniform height, and even the taller widgets don't have a height of 150px.

![image](https://github.com/google/site-kit-wp/assets/18395600/133b292e-020a-4e1b-99f3-bf333730c051)

It could well be acceptable to make the widgets all 150px height in the mobile view as well, but the AC is somewhat open to interpretation here (we could instead define a fixed height for each widget in the mobile view and ensure the loading state height aligns with that, although would run into trouble with the edit states).

With that in mind, it would be beneficial to clarify the intent of the AC when it comes to the mobile view. @nfmohit, do you know if this has been discussed, and would you be able to clarify this point?

**Comment by nfmohit** [comment]
> With that in mind, it would be beneficial to clarify the intent of the AC when it comes to the mobile view. @nfmohit, do you know if this has been discussed, and would you be able to clarify this point?

Hi @techanvil. I'm afraid, this hasn't been discussed. Since the widgets do not have a uniform height for mobile in the Figma designs, how about we only have the fixed height for higher viewports and let them have a fluid height for mobile?

CC: @sigal-teller

**Comment by zutigrm** [comment]
@techanvil @nfmohit The idea in IB is to have some `min-height` across the devices, but on other thought it should be probably be bit less then `150px` on small devices. Otherwise if we leave it to be fluid on smaller screens, on website with small data, tiles might look like this:

<img width="279" alt="image" src="https://github.com/google/site-kit-wp/assets/10414808/1e4f2cc9-285f-4aae-9e93-bf14674fd8c5">

cc @sigal-teller

**Comment by nfmohit** [comment]
I have raised this internally with Sigal [here](https://10up.slack.com/archives/C01CA828ZPZ/p1699024149266829), and am co-assigning the issue to Sigal as well.

**Comment by techanvil** [comment]
Thanks folks. We could clearly go either way here, so it would be good to get some direction from @sigal-teller on this one.

As mentioned above, it's worth bearing in mind that if we do go for the fluid mobile layout (as per the current Figma design), or even a fixed height that is below 150px, we'll also need to consider what to do about the error state which we only have a design for at 150px so would inherently cause a layout shift in mobile as it stands.

Personally, what with the error state being the unhappy path, I would imagine that we can accept it causing a layout shift in mobile view, if the alternative is to compromise the happy path layout.

Anyhow, let's see what the lay of the land is from the UX side of the fence :)

**Comment by techanvil** [comment]
So, as per the discussion on [Slack](https://10up.slack.com/archives/C01CA828ZPZ/p1699024149266829), the direction we'll take here is to keep the fluid layout for mobile. We should make a best-effort attempt to ensure the loading state does not cause a layout shift in the mobile view, by ensuring the loading height is the same as a given tile height as it generally presents itself (we don't need to cater for hard to reach edge cases).

Sigal has also provided a new [error state design for mobile](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=6273%3A68010&mode=design&t=QIa3v58T8wVKJGBP-1), which will help mitigate the layout shift and should be included as part of this issue:

![image](https://github.com/google/site-kit-wp/assets/18395600/869e786f-79b0-499f-bfcb-4a9573e7770d)

**Comment by techanvil** [comment]
Thanks @zutigrm! IB LGTM :white_check_mark:
