### ISSUE TITLE
Link buttons (like "Edit") should have an updated design for active/focus state

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#7776]
## Bug Description

For context, see: https://app.asana.com/0/0/1205794052980177/1205804485876623/f

The dashed outline that appears around link buttons (for example, "Edit" for the Key Metrics answers in Site Kit > Admin > Settings > Key Metrics) should be updated to a new design, which will be provided by @sigal-teller.

Screenshot of edit button as they currently behave:

https://github.com/google/site-kit-wp/assets/90871/a39bf5d3-0a3e-4355-b856-ca51eb7df297

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Remove the dashed/dotted outline from all link buttons.
* Implement a new design that for the [focus state of stand-alone link buttons](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7332%3A57299&mode=design&t=QI411viBZOUoT3XV-1)
* Implement the new design for link buttons alongside text (they should be styled like [the Source: **Analytics** link in this mockup](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7332%3A57698&mode=design&t=QI411viBZOUoT3XV-1), although this link itself [should not be updated](https://github.com/google/site-kit-wp/issues/7776#issuecomment-1822484050)).

## Implementation Brief

* Modify `assets/sass/components/global/_googlesitekit-cta-link.scss`
  * Match the focus style with the design on:
    * `.googlesitekit-cta-link`
    * `.googlesitekit-cta-link--secondary` 
    * Remove current `outline` styles on `:focus` state
  * Check if `googlesitekit-cta-link--external`, `.googlesitekit-cta-link--inverse`, etc. have overriding style on`:focus` that needs to be adjusted/removed
    * These links usually only add additional icons. via `background-image` (which will be moved to svg icons in #7542 ) and inherit the style from main link `.googlesitekit-cta-link`
      * So when background from design is applied, it is safer to target `background-color` property as general `background` will override the icons if execution on this starts before the inline icons are moved to use svg files
* Check if there is any other standalone button link that needs new `:focus` styling
  * Bear in mind that general `.googlesitekit-plugin a` styling is targeting regular text hyperlinks (like the ones in metric tiles, module widgets, etc), which are not button links

### Test Coverage

* There are stories using these links, but update there shouldn't be needed (unless new css class is introduced), as new styles will be applied there. But just check them to make sure
* Update VRT image references

## QA Brief

Verify the focus styling is correct for the following three buttons:

_The "Change metrics" button on the dashboard:_
![image](https://github.com/google/site-kit-wp/assets/18395600/21fb2568-0f4c-4c16-9ede-b2f062301db7)

_The "X" close button on the KM Selection Panel:_
![image](https://github.com/google/site-kit-wp/assets/18395600/15c850de-1c25-43f6-a658-de9ebc1b56f8)

_The Edit button on the Key Metrics Settings screen:_
![image](https://github.com/google/site-kit-wp/assets/18395600/715b12fc-8d33-4c6f-9018-46b826293889)

## Changelog entry

* Improve styles for some link-styled buttons.

**Comment by sigal-teller** [comment]
@tofumatt Is it possible to create different focus states for different types of components?
I created a [focus state](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7332%3A57299&mode=design&t=QI411viBZOUoT3XV-1) for the teal colored links that will work both on white and gray background, and also when they’re a part of a text (like [here](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7332%3A57698&mode=design&t=QI411viBZOUoT3XV-1)).

In addition we have other elements that require focus state like an entire tile for example. the tile focus state should be different, something like [this](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7345%3A62573&mode=design&t=QI411viBZOUoT3XV-1
)

If it's possible to create different focus states I'll check if there are additional elements

**Comment by tofumatt** [comment]
@sigal-teller It's totally possible to create different focus states for different components 👍🏻.  That said, it would be good to maintain a level of consistency between them (conventionally an outline/border is usually the signifier of focus state on the web/desktop apps, so it's what users expect). But we can alter it depending on the component. That focus state is similar to the one used in the navigation so it makes sense 👍🏻 

Entire tiles would not require focus state, as only interactive elements need a focus state. The tiles themselves a user wouldn't tab through and focus because they don't have any interaction associated with them. The tooltips and links inside do, but those elements would have their own focus state. (Additionally, that subtle of a focus state might be too subtle for users to notice. 😅)

But we can ship that focus state for the buttons—if you have additional focus states you find in the plugin and can report them/create new designs I'll happily file a new issues for them as well 👍🏻 

(A good way to find focus styles would be to open Site Kit and navigate through all interactive elements using the `Tab` key instead of using the mouse. That way you can find all focus styles—including where we might be missing some, which we should fix too! 🙂)

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by techanvil** [comment]
Having picked this up for execution and taken a look, it's evident the IB isn't quite correct.

As defined, the IB will result in the focus state being updated for _all_ usage of the `Link` component. However, `Link` is used in many cases where it's clearly a "link" rather than a "button". For example:

![image](https://github.com/google/site-kit-wp/assets/18395600/d0794f39-ade9-4b7b-bea1-77827606799f)


It seems that we'll want to either add an additional prop to `Link` that indicates its context should be that of a button, or maybe we could introduce a new component, e.g. `TextButton` component for what could be slightly clearer semantics.

I'd be happy enough to make these decisions on the fly, but I'm going to mention it in the standup so thought I'd post a comment here too.

---

There's also a question about the design, on the linked [Figma](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7332%3A57698&mode=design&t=QI411viBZOUoT3XV-1) design for the Analytics source link, the link is missing the external indicator.

_Figma:_
![image](https://github.com/google/site-kit-wp/assets/18395600/4a107ce8-e7d3-457a-837d-63550ecf163e)

_Current design:_
![image](https://github.com/google/site-kit-wp/assets/18395600/2f343202-f5d6-4c2b-92dc-dce7281a412a)

I'm guessing this might an oversight, but it would be good to confirm. @sigal-teller, please can you clarify this one?

**Comment by techanvil** [comment]
An additional point to note is that the Analytics source link referred to in the AC is not a button, it's a regular link so it should not be included in this issue. However, its styling can be applied to link buttons beside text as specified, for example this **Settings** one which is legitimately a button due to its use of `disabled`. I'll tweak the AC to avoid confusion.

![image](https://github.com/google/site-kit-wp/assets/18395600/d5815626-737d-40e5-b089-b1da3c49bedd)

cc @sigal-teller

**Comment by techanvil** [comment]
In the end, I've only added this focus styling to the three cases where the link buttons are clearly standalone buttons and the styling would not impact the alignment of the link.

It turns out that in a number of other cases where we're rendering a `Link` as a `button`, we should in fact be rendering a tertiary Button. I've created a followup [issue](https://github.com/google/site-kit-wp/issues/7912) to address this.

Additionally there are a number of other instances of `Link` rendering a `button` where the focus styling would cause the link to go out of alignment, as a result I've not updated these but will be following up separately with @sigal-teller to clarify how we should tackle them. See this [Slack thread](https://10up.slack.com/archives/C01CA828ZPZ/p1700743125754009) for some additional context.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified focus state for for all 3 buttons mentioned under QAB are updated as per Figma design.
- Verified focus state for edit buttons under admin settings and under set up process.
- Verified focus state. X button.
- Verified focus state for 'Change metrics' button. 


<details>


![image](https://github.com/google/site-kit-wp/assets/94359491/670fc5b6-a14d-438d-b760-88d2dde4b28d)


![image](https://github.com/google/site-kit-wp/assets/94359491/cca81384-fe35-4ca6-9e39-396a6c3300c3)


![image](https://github.com/google/site-kit-wp/assets/94359491/5c6e41e5-06c7-4e67-9bc3-0e13b6519f30)


![image](https://github.com/google/site-kit-wp/assets/94359491/373c9f96-4ce9-44ce-bb0d-664541c06521)

![image](https://github.com/google/site-kit-wp/assets/94359491/11cd3a1c-03c1-447d-a905-e162d5fb6fba)


</details>
