### ISSUE TITLE
GitHub Action for deploying zips (Plugin, Storybook) fails due to collisions.

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#7806]
## Bug Description

![CleanShot 2023-11-01 at 13 48 27](https://github.com/google/site-kit-wp/assets/90871/5d64d0f3-4972-48bf-8671-9540e7ff97b0)

We've seen an issue intermittently that causes plugin and storybook zips not to be deployed.

This causes the tester plugin to not get updates and causes problems QAing new issues.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* GitHub Actions should not cancel when unrelated jobs run (see: https://github.com/google/site-kit-wp/actions/runs/6653018075 / https://github.com/google/site-kit-wp/actions/runs/6645696276 as examples)

## Implementation Brief

I've found a lot of references to the `${{ github.ref }}` variable we use being undefined in many job runs. See:

- https://github.com/orgs/community/discussions/64817
- https://github.com/orgs/community/discussions/64528
- https://github.com/actions/runner/issues/2788

When this is the case, it seems that _all_ jobs matching `storybook-*` and `zips-*` are cancelled by GitHub.

The best solution seems like it's to rely on the event name of the reason the action was run, and use a backup variable when `github.ref` is empty.

* Change the usage of `storybook-${{ github.ref }}` and `zips-${{ github.ref }}` in our Action workflows to `storybook-${{ github.event_name }}-${{ github.ref || 'unknown-ref' }}` and `zips-${{ github.event_name }}-${{ github.ref || 'unknown-ref' }}`
* Merge #7814, then observe the actions output and see if the issue is fixed.
* (This can be moved directly to Code Review after IB Review, and QA can be assigned to @tofumatt as the IB writer for the issue.)

### Test Coverage

* No tests needed.

## QA Brief

* Sadly this needs to be "QA'd in production" by watching the builds and ensuring no actions are cancelled.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
Thanks @tofumatt – I did some testing in a sandbox repo and found that this is probably an issue specifically for jobs that run on `pull_request.closed` – this is because the `github.ref` value for these runs is the same as the `ref` used for a push to the branch (e.g. `refs/heads/master` I assume the target branch - instead of `refs/pull/123/merge`).

The docs for concurrency also note this:
> Ordering is not guaranteed for jobs or runs using concurrency groups, they are handled in the order that they are processed.

Together with this caveat, I think what's happening is that in some cases the `push` job may start first and then get cancelled by the job for the PR closing since they have the same `ref`. Only 2 workflows have this: storybook and zips.

So in light of this, I think including the `event_name` should solve it because the `pull_request.closed` event will still have the same ref as the target branch but be "namespaced" to `pull_request` to prevent the collision 👍 

<details>
<summary>Example contexts</summary>

Opening a PR
```json
{
  "job": "build",
  "ref": "refs/pull/11/merge",
  "head_ref": "aaemnnosttv-patch-4",
  "base_ref": "master",
  "event_name": "pull_request",
  "event": {
    "action": "opened",
  },
  "..."
}
```

Updating an open PR

```json
{
  "job": "build",
  "ref": "refs/pull/11/merge",
  "head_ref": "aaemnnosttv-patch-4",
  "base_ref": "master",
  "event_name": "pull_request",
  "event": {
    "action": "synchronize",
  },
  "..."
}
```

Closing a PR via merge

```json
{
  "job": "build",
  "ref": "refs/heads/master",
  "head_ref": "aaemnnosttv-patch-4",
  "base_ref": "master",
  "event_name": "pull_request",
  "event": {
    "action": "closed",
  },
  "..."
}
```

The `push` from the merged PR

```json
{
  "job": "build",
  "ref": "refs/heads/master",
  "head_ref": "",
  "base_ref": "",
  "event_name": "push",
  "event": {
    "after": "a296c2c5cdc679fa9a3cf5a8372a29ac4902b23d",
    "base_ref": null,
    "before": "32bba8490aebf4b69eca2cf9d1d00127209b1d84",
  },
  "..."
}
```

Publishing a new release with tag (`push.tags: [**]`)

```json
{
  "job": "build",
  "ref": "refs/tags/v1.1",
  "head_ref": "",
  "base_ref": "",
  "event_name": "push",
  "event": {
    "after": "a296c2c5cdc679fa9a3cf5a8372a29ac4902b23d",
    "base_ref": "refs/heads/master",
    "before": "0000000000000000000000000000000000000000",
  },
  "..."
}
```

</details>

As seen above, `github.ref` seems to be present/reliable in all the cases we use but we can see how a collision could happen based on workflow+ref alone.

Let's not worry about an empty `ref` (using a static value for the fallback would have the same problem anyways – it's only [suggested in the docs](https://docs.github.com/en/actions/using-jobs/using-concurrency#examples-using-concurrency-and-the-default-behavior) in order to avoid a syntax error if your group is based on the `ref` only) but let's add the `event_name` as proposed – this should fix the problem 👍 

This is more/less already done in your PR so moving this forward to CR 👍 

IB ✅

**Comment by aaemnnosttv** [comment]
As noted in QAB, this isn't really testable, we'll just need to keep an eye on it.

Moving to Approval.
