### ISSUE TITLE
Allow google analytics on front-end - not just wp-admin

### ISSUE THREAD

**Issue by LukaszJaro** [google/site-kit-wp#785]
Would be nice to be able to display and manipulate the data on the front-end(public facing side) of your site, this way you could do such things as dynamically list most popular posts/pages, top trending pages, most popular search terms, etc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by LukaszJaro** [comment]
Related issues:

#1019 
#1093

**Comment by felixarntz** [comment]
@LukaszJaro Thanks for the feature request. With the goals of Site Kit being primarily around providing insights and suggestions for website performance to site owners and other contributing users, displaying metrics in the public frontend (e.g. as a showcase) doesn't really fit into this.

However, this use-case is certainly relevant, and it could be accomplished by a separate third-party plugin relying on the infrastructure that Site Kit offers to get the data, so that would be an option. For the Site Kit plugin itself, this falls rather out of scope.

**Comment by LukaszJaro** [comment]
That makes perfect sense, forgot about this feature request, when time permits will look into something like this, thank you @felixarntz !
