### ISSUE TITLE
Display a notification when a user goes offline

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8081]
## Feature Description

This issue is a follow-up to #3820 which introduced the foundational infrastructure. See https://github.com/google/site-kit-wp/pull/8033#pullrequestreview-1818998554

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The offline notification in #3820 should be reintroduced
* No requests should be made to Google APIs as part of the checks to determine online status

## Implementation Brief

* [x] Update `includes/Core/Util/Health_Checks.php`, add new route, say `core/site/data/connection-checks`. It should return the text "true".
* [x] In `assets/js/hooks/useMonitorInternetConnection.js`, update `checkInternetConnection` callback function to use `API` from `googlesitekit-api` instead of `apiFetch`. 
  * Make a request using `API.get` to the `connection-checks`, and explicitly pass `useCache` with value `false`
  * Remove `onlineResponse` and it's usage and pass `true` directly to `setIsOnline`, since if entered here, request was successful. Otherwise error will be caught and set to `false`.
* [x] Include [back](https://github.com/google/site-kit-wp/pull/8080/files) the  `useMonitorInternetConnection` to the `DashboardMainApp` and `DashboardEntityApp` components

### Test Coverage

* Update `useMonitorInternetConnection.test.js`

## QA Brief

* Load the SK dashboard 
* Use the [Chrome DevTools Network tab to set the browser status to offline](https://developer.chrome.com/docs/devtools/network#throttle)
* See the notification
* Use the [Chrome DevTools Network tab to set the browser status to online](https://developer.chrome.com/docs/devtools/network#throttle)
* The notification should disappear

## Changelog entry

* Show a notification when the user goes offline.

**Comment by tofumatt** [comment]
Rather than make a new route in Site Kit, and increase traffic to the user's site (which also could be, in theory, not on the public internet), is there any reason not to use something like `captive.apple.com`? It's on the public internet, would mimic the type of response we're looking for, and is already used for this type of feature.

We can ping the WordPress site instead but I figured something online (and something that already exists for this purpose) seems better, plus is less code for us to maintain.

**Comment by zutigrm** [comment]
Hi @tofumatt, the reason why this was switch to backend call in the original implementation as well, was due to the CORS issue with external services, and for better reliability. But I haven't tried with apple due to the comments, that since this is Google plugin, we should not use Apple service endpoint. Although I did try it now, and that endpoint seems to be the only one without CORS issue. But we don't have guarantees it might not change. So for reliability and better control, I suggested doing the REST endpoint. Techically we could switch to Apple endpoint, if you think above concerns might not be the issue

Let me know what you think

**Comment by tofumatt** [comment]
Ah, fair enough.

Using the Apple endpoint I don't really think is an issue, but the CORS issue is an interesting point.

IB ✅

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that the offline notification in https://github.com/google/site-kit-wp/issues/3820 appears when user goes offline.
- Verified that the when user is online then notification do not display.
- Verified that if user switch to offline mode then notification display and when user switch back to online then notification do not appear.


https://github.com/google/site-kit-wp/assets/94359491/061ac819-551f-4358-a06d-cf0653fe3701
