### ISSUE TITLE
Incorrect API key for PageSpeed due to excess spaces

### ISSUE THREAD

**Issue by desrosj** [google/site-kit-wp#81]
## Bug Description

Following the instructions to connect to the PageSpeed API, I was unable to get it working due to excess spaces in my API key.

## Steps to reproduce

1. Click connect near the PageSpeed API on the Site Kit dashboard.
2. Follow the instructions and click the button to get an API key.
3. Click the copy icon to the right of the key to copy.
4. Paste the copied key into the API key field in WordPress.
5. See the connection does not work.

I reset Site Kit on my site and started over. Before I paste the API key, I pasted into a text editor and saw that there was a space before and after the API key. I removed these spaces, copied the new string, pasted it into the field, and the connection worked.

Discussed this with @felixarntz briefly in Slack today as well.

----------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* API key input should strip all whitespace characters from the user-provided input.

## Implementation Brief

* Update `handleAPIKeyChange` in `assets/js/modules/pagespeed-insights/setup.js` to strip whitespace from the input before setting the state.

## Changelog entry

* Update API key input to strip whitespaces automatically

**Comment by jamesozzie** [comment]
I have been testing PSI on a few sites, not just subdomains. This is the errors I get on some occasions:
{"pagespeed-insights::site-pagespeed-mobile::last-28-days::d41d8cd98f00b204e9800998ecf8427e":{"errors":{"403":["The request did not specify any referer. Please ensure that the client is sending referer or use the API Console to remove the referer restrictions."]},"error_data":{"403":{"status":500,"reason":"ipRefererBlocked"}}},"pagespeed-insights::site-pagespeed-desktop::last-28-days::d41d8cd98f00b204e9800998ecf8427e":{"errors":{"403":["The request did not specify any referer. Please ensure that the client is sending referer or use the API Console to remove the referer restrictions."]},"error_data":{"403":{"status":500,"reason":"ipRefererBlocked"}}}}

I also tested resetting Site Kit and delete the app in Cloud Console. Could having 2FA enabled be a contributing cause, I get the notification on my phone to approve access (after already granting within Site Kit)

**Comment by aaemnnosttv** [comment]
@desrosj I believe you're referring to this dialog on https://developers.google.com/web/site-kit/apikey correct?

![get-api-key-dialog](https://user-images.githubusercontent.com/1621608/60804217-aad02200-a185-11e9-8fad-7b751a14efa0.png)

I was able to reproduce this issue using Firefox (1 space before and after), and IE Edge (1 space after), but found that it worked fine using Chrome and Safari with no added whitespace.

This appears to be a browser-related bug with the copy tool on https://developers.google.com/web/site-kit/ 

Since that is out of the scope of this repository, we can focus this issue on ensuring that any whitespaces are removed from the API key input in the SiteKit UI.

**Comment by felixarntz** [comment]
Implementation brief looks good!

**Comment by desrosj** [comment]
@aaemnnosttv Correct! That is the screen I am referring to. I was also using Firefox when I encountered the issue.

**Comment by lucymtc** [comment]
QA looks good

**Comment by marrrmarrr** [comment]
LGTM.
