### ISSUE TITLE
Update compatibility checks

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8101]
## Feature Description

There are a few changes we should make to our compatibility checks that run before connecting SK.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The check for [testing if SK is running on a version of WP below 5.0](https://github.com/google/site-kit-wp/blob/08539d62e44b949588af1dac42719c8292102190/assets/js/components/setup/CompatibilityChecks/index.js#L58) should be removed entirely (this was from when SK supported older versions but some secondary functionality would not work; SK requires WP 5.2 now)
* The [help link](https://github.com/google/site-kit-wp/blob/355c8a14ace9fbf45e20145c854b3d4bc6389e7c/assets/js/components/setup/CompatibilityChecks/CompatibilityErrorNotice.js#L138-L146) for the staging environment cases should be displayed below both variants (it's currently only present in the `installed` case).  
	See [this diff](https://github.com/google/site-kit-wp/pull/7399/files#diff-d8d958cd6817b4841c2da9fdb5fcaa974601e3bd871c2541b3cdbaf1933b82ff) for where it changed

## Implementation Brief

* [x] Remove the `checkWPVersion` functions from `assets/js/components/setup/CompatibilityChecks/checks.js`
* [x] Remove the import and use of `checkWPVersion` from `assets/js/components/setup/CompatibilityChecks/index.js`

* [x] Update the `assets/js/components/setup/CompatibilityChecks/CompatibilityErrorNotice.js` `ERROR_FETCH_FAIL` condition by copying the [object containing the `GetHelpLink`](https://github.com/google/site-kit-wp/blob/355c8a14ace9fbf45e20145c854b3d4bc6389e7c/assets/js/components/setup/CompatibilityChecks/CompatibilityErrorNotice.js#L138-L146) and using `createInterpolateElement` to render both the message and the help link.

### Test Coverage

* 

## QA Brief

* Set up a new staging environment site without the SK helper plugin installed, trigger the `ERROR_FETCH_FAIL` compatibility error and you should see the warning message now includes a help link at the end of the message: `Looks like this may be a staging environment. If so, you’ll need to install a helper plugin and verify your production site in Search Console. [Help Link Here]`.
* The help link title should be "Install" and it should link [here](http://sitekit.10uplabs.com/wp-admin/update.php?action=install-plugin&plugin=google-site-kit-dev-settings&_wpnonce=9d4ecfc5fa).

## Changelog entry

* Improve compatibility checks code, including removing legacy notices for WordPress 4.x users.

**Comment by eugene-manuilov** [comment]
> * Remove the `checkWPVersion` functions from `assets/js/components/setup/CompatibilityChecks/checks.js`
> * Remove the import and use of `checkWPVersion` from `assets/js/components/setup/CompatibilityChecks/index.js`

@benbowler, we also need to remove all that is relevant for the `wpVersion` variable since it is no longer needed. See for reference: https://github.com/search?q=repo%3Agoogle%2Fsite-kit-wp%20wpVersion&type=code

**Comment by benbowler** [comment]
@eugene-manuilov I've looked into this a little more this morning and the `wpVersion` and `getWPVersion` are still used by the `hasMinimumWordPressVersion` function:

https://github.com/google/site-kit-wp/blob/d1aad74674ec14dcc682bb610c32df19f93174c7/assets/js/googlesitekit/datastore/site/info.js#L797-L824

Therefore I believe my original list of references to remove were correct.

**Comment by eugene-manuilov** [comment]
Ah.. ok, I missed that. Then it should be good to go. IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@benbowler I am able to create the message that is in the QAB, but I am seeing a `configure` link rather than a get help link. Please could you tell me what the link text should be and where should it point to?  When I click it, I am taken to the helper plugin settings. Is this expected?

![image](https://github.com/google/site-kit-wp/assets/73545194/55298dca-02fa-457a-be8f-96bfbb29d370)

**Comment by benbowler** [comment]
@wpdarren I re-reviewed the code and QAB and I had it right way around when it was first written. The test state is when the developer plugin is not installed on the staging site. I've added details about what CTA you should see and I've updated the expected text for the alert.

**Comment by wpdarren** [comment]
@benbowler thank you for updating the QAB.  I see the correct message `Looks like this may be a staging environment. If so, you’ll need to install a helper plugin and verify your production site in Search Console.` but the CTA is not as per the QAB. I have an Install (or if its installed but not active, an Activate link appears) link which takes me to install or active the plugin.

In the past (which was a long time ago) to trigger the `ERROR_FETCH_FAIL` compatibility error, I had to use the console and blocked one or all of the `wp-json` network events.  As you can see from my screencast this is what I have done this time. 

Is there another way to trigger `ERROR_FETCH_FAIL`?  Maybe I am doing this part wrong which is why I am not seeing the CTA correctly. What do you think?

https://github.com/google/site-kit-wp/assets/73545194/63d8a062-6487-423a-9d73-da0669626b9b

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@benbowler I have been working a bit more on this ticket and I found that a `learn more` link does appear but only for a second then changes to install.   You can see it on the screenshot below.  The link text does not match the QAB too, but there is something amiss here. 


https://github.com/google/site-kit-wp/assets/73545194/63d29402-ad28-4a91-83b0-b9b2223c7179

**Comment by benbowler** [comment]
Hey @wpdarren, this was another issue with my QAB, sorry.

The "Install" link is correct linking [here](http://sitekit.10uplabs.com/wp-admin/update.php?action=install-plugin&plugin=google-site-kit-dev-settings&_wpnonce=9d4ecfc5fa) as you saw in your videos. I have tested this myself and can confirm this is expected.

The issue with this specific ticket was that I've been writing my QABs without directly running and logging the code which has led to all of this back and forward. I'll make sure for future QABs that I've tested the flow and give more accurate and repeatable steps.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

Thanks @benbowler - yes, for these types of testing it does need a bit of an 'idiots guide' because I aren't an engineer, so rely a bit more direction. Thank you for updating the QAB, this looks good! 

**Verified:**

- Without the SK helper plugin installed, and triggering the `ERROR_FETCH_FAIL` compatibility error you see the warning message now includes a text link at the end of the message: `Looks like this may be a staging environment. If so, you’ll need to install a helper plugin and verify your production site in Search Console.` 
- The link title is "Install" and it links to `/wp-admin/update.php?action=install-plugin&plugin=google-site-kit-dev-settings&_wpnonce=9d4ecfc5fa`

**Note:** there is a flicker of the link text but a user would only notice it if they were on a very slow 3G connection. 

![image](https://github.com/google/site-kit-wp/assets/73545194/f6e6674b-caa1-4867-9e7e-b1c63f1de510)
