### ISSUE TITLE
Implement the dismissal behavior for the Setup CTA Banner

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8133]
## Feature Description

Implement the two-stage dismissal of the Setup CTA Banner. Additionally, show the Settings tooltip on dismissal.

See [setup CTA banner > dismissal](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.swnrr3cq0xh4) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* As described in the design doc, and following the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1956-17850&mode=design&t=XPYgtG6IteZaade4-0):
* When the Setup CTA Banner's **Maybe later** dismissal button is clicked:
  * The banner should be dismissed for two weeks.
  * A tooltip should be shown pointing to the **Site Kit > Settings** WP menu item.
    * The copy should be as follows:
      * Title: _You can always enable groups from Settings later_
      * Description: _The visitors group section will be added to your dashboard once you set it up._
      * Dismissal button: _Got it_
    * See the [Figma design for the tooltip](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1834-32286&mode=design&t=XPYgtG6IteZaade4-0) (please check the copy with Figma, which is the source of truth).
    * This should follow Site Kit's standard pattern of opening the WP menu when necessary in order to correctly target the tooltip.
  * When the banner is next shown after two weeks have passed:
    * The dismissal button should be renamed **Don’t show again**.
    * Clicking the button should show the Settings tooltip again, and permanently dismiss the banner.

## Implementation Brief

_Note, this multiple-dismissal behavior can reuse the infrastructure implemented separately to this feature in GitHub issue #7316, and the Settings tooltip can be implemented using the `AdminMenuTooltip` component._

In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.js`:

* [x] Create a constant variable for the setup CTA widget `AUDIENCE_SEGMENTATION_SETUP_CTA_NOTIFICATION`.
* [x] Return `null` (do not render the component) if the prompt is dismissed permanently using the `isPromptDismissed` selector of the `core/user` store.
* [x] Retrieve the dismissed count for the setup CTA widget using the `getPromptDismissCount` selector of the `core/user` store.
* [x] Get the tooltip visibility state using the `useTooltipState` hook.
* [x] If the tooltip visibility state is true, render the `AdminMenuTooltip` component with the following props:
    * `title` - `You can always enable groups from Settings later`.
    * `content` - `The visitors group section will be added to your dashboard once you set it up.`.
    * `dismissLabel` - `Got it`.
    * `tooltipStateKey` - `AUDIENCE_SEGMENTATION_SETUP_CTA_NOTIFICATION`.
    * See: https://github.com/google/site-kit-wp/blob/131e28d8b3792315dc572551293a0e28702afb1f/assets/js/modules/adsense/components/dashboard/AdBlockingRecoverySetupCTAWidget.js#L212-L229
* [x] Create a callback function `handleDismissClick` similar to the `handleDismissClick` callback function in `AdBlockingRecoverySetupCTAWidget`. See:
https://github.com/google/site-kit-wp/blob/131e28d8b3792315dc572551293a0e28702afb1f/assets/js/modules/adsense/components/dashboard/AdBlockingRecoverySetupCTAWidget.js#L181-L199
* [x] It should mirror the above callback function but with the following differences:
    * [x] The dismiss count check should be less than 1 (instead of 2).
        * [x] If the dismiss count is less than 1, dispatch the `dismissPrompt` action with the `AUDIENCE_SEGMENTATION_SETUP_CTA_NOTIFICATION` constant and `expiresInSeconds` set to two weeks in seconds.
        * [x] Otherwise, dispatch the `dismissPrompt` action with the `AUDIENCE_SEGMENTATION_SETUP_CTA_NOTIFICATION` constant without passing the `expiresInSeconds` option, which will dismiss the prompt permanently.
* [x] Use the `useShowTooltip` hook to invoke the callback to show the tooltip within the `handleDismissClick` callback function. It should be same as in the `AdBlockingRecoverySetupCTAWidget` component.
* [x] Pass the `handleDismissClick` callback function to the `Maybe later` `Button` component's `onClick` prop.
* [x] Update the `Maybe later` button text to `Don’t show again` if the dismiss count is greater than 1. See:
https://github.com/google/site-kit-wp/blob/131e28d8b3792315dc572551293a0e28702afb1f/assets/js/modules/adsense/components/dashboard/AdBlockingRecoverySetupCTAWidget.js#L283-L287

### Test Coverage

* Add a story for the `Don’t show again` button state in the `AudienceSegmentationSetupCTAWidget` storybook stories.
* Add a few basic test coverage for the `AudienceSegmentationSetupCTAWidget` component. It can be similar to the `AdBlockingRecoverySetupCTAWidget` tests.

## QA Brief

* Set up Site Kit and connect it to Analytics.
* Ensure the `audienceSegmentation` feature flag is enabled.
* Visit the dashboard and ensure the Audience Segmentation Setup CTA Banner is shown.
* Click the `Maybe later` button and ensure the tooltip is shown.
* Verify that a POST request is made to the `/core/user/data/dismiss-prompt` endpoint with the payload containing the `audience_segmentation_setup_cta-notification` slug and `expiration` set to two weeks in seconds.
* To test the timeout behavior without waiting for two weeks between testing, run the following command in the browser console:
  ```js
  googlesitekit.data.dispatch( 'core/user' ).dismissPrompt( 'audience_segmentation_setup_cta-notification', {
    expiresInSeconds: 120, // 2 minutes
  } )
  ```
* After two minutes, ensure the banner is shown again with the `Don’t show again` button.
* Click the `Don’t show again` button and ensure the tooltip is shown again.
* Verify that a POST request is made to the `/core/user/data/dismiss-prompt` endpoint with the payload containing the `audience_segmentation_setup_cta-notification` slug and `expiration` set to 0.

## Changelog entry

* Implement dismissal behaviour for the audience groups setup banner.

**Comment by techanvil** [comment]
Unassigning @jimmymadon as he's on his break and this will be picked up by Squad 2.

**Comment by kuasha420** [comment]
IB :white_check_mark:

**Comment by kelvinballoo** [comment]
### QA Update ❌ 

Tested this and results are looking as expected for the AC points ✅ :
- When the 'Maybe later' button is clicked, the tooltip is shown and there is a POST request made to /core/user/data/dismiss-prompt endpoint with the payload containing the audience_segmentation_setup_cta-notification slug and expiration set to two weeks in seconds, which is 1209600:
   <Details>
   <img width="1179" alt="Screenshot 2024-05-29 at 10 59 09" src="https://github.com/google/site-kit-wp/assets/125576926/e011e7d1-1922-4820-b8ac-da89e2e47358">

   <Details>

- After changing the timeout to 2 mins, ensure the banner is shown again with the Don’t show again button after 2 mins.
   <Details>
   <img width="1161" alt="Screenshot 2024-05-29 at 11 05 37" src="https://github.com/google/site-kit-wp/assets/125576926/38af10b9-76d2-4fc0-8fbc-095b8748e61f">
   </Details>

- After clicking 'Don’t show again' button and the tooltip is shown again.
   <Details>
   <img width="666" alt="Screenshot 2024-05-28 at 19 13 38" src="https://github.com/google/site-kit-wp/assets/125576926/49279165-35a0-42e5-8630-7e332f9f51fb">
   </Details>

- A POST request is made to the /core/user/data/dismiss-prompt endpoint with the payload containing the audience_segmentation_setup_cta-notification slug and expiration set to 0.
   <Details>
   <img width="1312" alt="Screenshot 2024-05-28 at 19 42 25" src="https://github.com/google/site-kit-wp/assets/125576926/d34cf605-3161-4b46-a690-ee305fe1e159">
   </Details>

- Verified good on Firefox and Safari browsers.

❌  **The failed areas fall mainly into the visuals of the tooltip and other devices:** ❌ 

**ITEM 1: Tooltip visuals**
- Arrow pointing on our implementation is more vertically centred. On Figma, it's more towards the top.
- 'Got it' button has a dotted line around it but on Figma there is none.
- 'x' icon position alongside the text in our implementation but on figma, it's above.

   <Details>
   Implementation:
   <img width="1312" alt="Screenshot 2024-05-28 at 19 13 11 copy" src="https://github.com/google/site-kit-wp/assets/125576926/7720e9cc-abcf-4c92-8496-8a67fb91c367">

   Figma:
   <img width="553" alt="Screenshot 2024-05-29 at 11 25 26" src="https://github.com/google/site-kit-wp/assets/125576926/34f2172a-3b5f-4498-bbd4-70fb458d2236">

   </Details>

**ITEM 2: Fonts and Margin**
- Title is Google sans Display when it should be sans text.
- Description should have font weight 400 instead of 300
- Margin around not correct. It's 24px instead of 16px"
   
   <Details>
   Description has font weight 400 on Figma. Implementation has it at 300.
   <img width="1077" alt="Screenshot 2024-05-28 at 19 15 39" src="https://github.com/google/site-kit-wp/assets/125576926/a75ea22b-4622-46d2-b66d-c9a35448a38d">
   
   Implemented title is 'Google Sans Display' but on figma, it's Google Sans Text.
   
   <img width="680" alt="Screenshot 2024-05-29 at 11 29 37" src="https://github.com/google/site-kit-wp/assets/125576926/d8804279-d7c2-4125-8e9b-fee04022f1c7">

   Margin on implementation is around 24px on the left hand side. On figma, it's 16px.
   I did not verify all because the 'x' position also plays a part. So it would be good as a general rule to verify all the margins. 
   <img width="1312" alt="Screenshot 2024-05-28 at 19 19 07" src="https://github.com/google/site-kit-wp/assets/125576926/99865373-b77d-4be0-9b28-787fdfde8f0a">
   </Details>

**ITEM 3:**
There is a weird mobile layout behaviour.
Details are below:
<Details>
<img width="268" alt="Screenshot 2024-05-29 at 11 33 52" src="https://github.com/google/site-kit-wp/assets/125576926/016d48e3-5890-410c-bc43-3dab9acfefd6">

Video:

https://github.com/google/site-kit-wp/assets/125576926/ea4d81f4-678f-44f3-b297-fe36113677bf


</Details>

**ITEM 4:**
On Tablet, I could not see the tooltip appearing.
Tested on iPad Air 5 Chrome.
Video is attached for reference below
<Details>
https://github.com/google/site-kit-wp/assets/125576926/32c6dd9e-2d6b-46e6-8bbc-e28d5ac2857b
</Details>

**Comment by hussain-t** [comment]
Hi @kelvinballoo, the Admin Tooltip design is standardized across the plugin. Changing it for this instance would create inconsistencies with other tooltips. The issues you’ve identified are present in other tooltips as well. Regarding the tablet issue, I tested it and was able to see the tooltip. If it does not appear for some reason, it is likely a broader issue affecting all tooltips, which should be addressed separately.


https://github.com/google/site-kit-wp/assets/24408261/82851182-fb55-4f9e-ac57-dc8513ff00f8

https://github.com/google/site-kit-wp/assets/24408261/56cc5133-5d15-46a5-b63d-075b5a9a033e

**Comment by hussain-t** [comment]
@kelvinballoo, I've also tested it on mobile. However, I couldn't reproduce it. Can you try reproducing it with an actual device? If you were able to reproduce it, please create a new issue.

![Screenshot 2024-05-29 at 2 55 43 PM](https://github.com/google/site-kit-wp/assets/24408261/f968ede9-9870-4812-bfc6-64e7d301f4f9)

**Comment by kelvinballoo** [comment]
### QA Update ✅ 
Thanks @hussain-t ,

Noted on the constraints around the tooltip and the behaviour is synonymous across all tooltips.
For the mobile issue, I was able to re-simulate it on an actual mobile and I've raised a ticket here for that : https://github.com/google/site-kit-wp/issues/8764

Other than that, marking this ticket as pass:
for the AC points ✅ :
- When the 'Maybe later' button is clicked, the tooltip is shown and there is a POST request made to /core/user/data/dismiss-prompt endpoint with the payload containing the audience_segmentation_setup_cta-notification slug and expiration set to two weeks in seconds, which is 1209600:
   <Details>
   <img width="1179" alt="Screenshot 2024-05-29 at 10 59 09" src="https://github.com/google/site-kit-wp/assets/125576926/e011e7d1-1922-4820-b8ac-da89e2e47358">

   <Details>

- After changing the timeout to 2 mins, ensure the banner is shown again with the Don’t show again button after 2 mins.
   <Details>
   <img width="1161" alt="Screenshot 2024-05-29 at 11 05 37" src="https://github.com/google/site-kit-wp/assets/125576926/38af10b9-76d2-4fc0-8fbc-095b8748e61f">
   </Details>

- After clicking 'Don’t show again' button and the tooltip is shown again.
   <Details>
   <img width="666" alt="Screenshot 2024-05-28 at 19 13 38" src="https://github.com/google/site-kit-wp/assets/125576926/49279165-35a0-42e5-8630-7e332f9f51fb">
   </Details>

- A POST request is made to the /core/user/data/dismiss-prompt endpoint with the payload containing the audience_segmentation_setup_cta-notification slug and expiration set to 0.
   <Details>
   <img width="1312" alt="Screenshot 2024-05-28 at 19 42 25" src="https://github.com/google/site-kit-wp/assets/125576926/d34cf605-3161-4b46-a690-ee305fe1e159">
   </Details>

- Verified good on Firefox and Safari browsers.
