### ISSUE TITLE
Implement the “partial data” badges

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8142]
## Feature Description

This includes the badge at the top of the Audience Tile and the badge for the “Top content” metric.

See [audience tiles > partial data](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.3ya31fuyk1ts) in the design doc.

Note that as discussed on [Figma](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH?node-id=1261:8985&mode=dev#737075499), the copy for the "Top content" badge tooltip will read as follows:

> Still collecting full data for this timeframe, partial data is displayed for this metric

While, as seen on [Figma](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=2059%3A33155&mode=dev) the badge at the top of the tile's tooltip will read as follows:

> Still collecting full data for this timeframe, partial data is displayed for this group

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* As described in the design doc, and following the Figma design (see the "partial data" badge for both the [audience tile as a whole](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=2059-32538&mode=design&t=XPYgtG6IteZaade4-0), and for the ["Top content" metric](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=3155-16408&mode=design&t=XPYgtG6IteZaade4-0) - and please also check the [mobile designs](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1665-39227&mode=design&t=XPYgtG6IteZaade4-0)):
  * If an audience is determined to be in the “partial data” state, it should show a badge at the top of the tile.
  * If the “Top content” metric is determined to be in the ”partial data” state it should display a badge in line with the metric title. 
    * To determine the “partial data” state, we’ll query a report for the earliest tracked event for the custom dimension used by the metric. For further detail see https://github.com/google/site-kit-wp/issues/8141.
  * In desktop viewports:
    * The audience-level badge will contain an info icon, which will display a tooltip when hovered or tapped. The tooltip will show the following copy: _Still collecting full data for this timeframe, partial data is displayed for this group_
    * The "Top content" metric badge will also provide a tooltip, with the following copy: _Still collecting full data for this timeframe, partial data is displayed for this metric_
  * In mobile viewports, the mobile design should be followed which doesn't provide tooltips and rather renders the above tooltip text inline in the badges.
  * Note that only one instance of the badge should be shown for a given audience; the “Top content” badge should not be shown if the audience itself is in the “partial data” state.
  * Note too that for both audiences and the “Top content” metric, the “partial data” badge should _not_ be shown if the current property itself is in the “partial data” state. This is to avoid showing a “partial data” badge when the entire dashboard is effectively partial data, i.e. when Site Kit and the Audience Segmentation feature were both set up on the same day, as it would be confusing to show the badge when the entire dashboard is in the same state.
  * Please confirm the copy with Figma, which is the source of truth.

## Implementation Brief

* [ ] Create `PartialDataBadgeDesktop` in `assets/js/modules/analytics-4/components/audience-segmentation/dashboard` folder. 
* [ ] It should take the `tooltipTitle` prop which will be of type `propTypes.node`.
* [ ] It should use the `Tooltip` component to show the tooltip text and the children inside it should have `Partial data` translatable string with the info icon as seen in the Figma design.
    * [ ] Style the component to match figma design. Styles should be placed on `assets/sass/components/analytics-4/audience-segmentation/_googlesitekit-partial-data-badge.scss`
* [ ] Create `PartialDataBadgeMobile` in `assets/js/modules/analytics-4/components/audience-segmentation/dashboard` folder. 
* [ ] This should take `content` prop and render it inside a styled `div` as seen in the Figma design for mobile.
* [ ] In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTile/index.js` file:
    * [ ] Add a new `audienceResourceName` prop. 
    * [ ] Get the `propertyID` using the `getPropertyID` selector. 
    * [ ] Get whether the current property is in partial data using the `isPropertyPartialData` selector. 
    * [ ] Get whether the audience is partial data using the `isAudiencePartialData` selector. 
    * [ ] Get whether `googlesitekit_post_type` custom dimension is in partial data using the `isCustomDimensionPartialData` selector. 
    * [ ] Render `PartialDataBadge**` components in appropriate places in the markup when the conditions met. 
        * [ ] If property is in partial data:
            * [ ]  Badges for audience and custom dimension should not be rendered. 
        * [ ] If the property is not in partial data:
             * [ ] If the audience is in partial data: 
                 * [ ] The badge for the whole audience should be rendered.
                 * [ ] The badge for custom dimension should not be rendered. 
             * [ ]  If the audience is not in partial data:
                 * [ ] Only the badge for custom dimension should be rendered (In top content area, see the design for exact placement). 
* [ ] In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTiles.js`
    * [ ] Pass the newly added prop `audienceResourceName` to the rendered `AudienceTiles` elements. 

### Test Coverage

* Add story variants and VRTs for various partial data states. 

## QA Brief

* Go to `Storybook -> Modules -> Analytics4 -> Components -> Audience Segmentation -> Dashboard -> AudienceTile`.
* Verify the new `Audience partial data` and `Top content partial data` story variants and ensure that the behaviour is in line with Figma and the ACs.

## Changelog entry

* Display information about partial data availability in Audience widget area when complete data for the selected date range is not available.

**Comment by kuasha420** [comment]
Added a bit of higher estimate because of the creation of new components which involves lot of viewport dependent styling, which always gets complicated. Cheers.

**Comment by techanvil** [comment]
Thanks @kuasha420. I've made a minor tweak for the type of the `tooltipTitle` prop. This IB LGTM, nice one!

**Comment by nfmohit** [comment]
@techanvil @kuasha420 Quick question: The AC mentions that the tooltip should be shown when the info icon is hovered over, however, the IB implies that it should open when anywhere in the badge is hovered. Which should we go with? From the Figma designs, it does look like the tooltip appears immediately above the info icon.

**Comment by techanvil** [comment]
@nfmohit, thanks, good spot. The tooltip should indeed be triggered when the icon is hovered - this will be consistent with elsewhere, for example the info tooltip for the [Audience Tile](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencetile--ready-with-tool-tip).

In fact, I missed this during the IB review but it looks like we should use the `InfoTooltip` component, as the `AudienceTile` component does, rather than using `Tooltip` directly:

https://github.com/google/site-kit-wp/blob/5d1b1b7de7c52b230b8d3746ac81848f615ca140/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTile/index.js#L74-L82

**Comment by nfmohit** [comment]
Thanks for the confirmation, @techanvil!

**Comment by kelvinballoo** [comment]
### QA Update ❌ 

Tested this and it's looking good overall.
I do have some observations though. They are documented down here:

**ITEM 1:**
I noticed that on Storybook, the tooltip would appear at the bottom instead of the top on Figma.
Can you confirm that this is because of the window spacing that we have above and that by default, it will appear at the bottom?

<Details>
Implementation:
<img width="1312" alt="Screenshot 2024-05-25 at 10 33 22" src="https://github.com/google/site-kit-wp/assets/125576926/0650790d-ee60-492c-be1b-578f9126a707">

Figma:
<img width="450" alt="Screenshot 2024-05-25 at 10 35 50" src="https://github.com/google/site-kit-wp/assets/125576926/95325f95-a822-4707-a682-986236fa2507">

</Details>

________________________________________________________________________________

**ITEM 2:**
The margins around the badge is not consistent with Figma
Refer to the details below.

<Details>
Implementation: 19px at the top and 25px on the side
<img width="532" alt="Screenshot 2024-05-25 at 10 37 41" src="https://github.com/google/site-kit-wp/assets/125576926/ee45818a-6603-446d-af74-9c4e8ba3c6d9">

Figma: 24px at the top and side and 20px on the bottom
<img width="736" alt="Screenshot 2024-05-25 at 10 39 29" src="https://github.com/google/site-kit-wp/assets/125576926/7389908d-4239-42c3-85b6-1f72e9c2f5e0">

</Details>

________________________________________________________________________________

**ITEM 3:**
At the metric level badge on desktop:
- Top margin should be 16px instead of 12px
- Bottom margin should be 14px instead of 10px
- Note that on the details the tooltip popup is on top of the badge and not above placement of tooltip
Details are below

<Details>
**Implementation:**

Top margin is 12px
<img width="1310" alt="Screenshot 2024-05-25 at 10 46 37" src="https://github.com/google/site-kit-wp/assets/125576926/c2c28bbd-fc68-4ec4-86fc-1d0b8d0dfe5c">

Bottom margin is 10px
<img width="1312" alt="Screenshot 2024-05-25 at 10 46 58" src="https://github.com/google/site-kit-wp/assets/125576926/abda64b8-3770-4c25-9903-7e528c595941">

No overlap between tooltip and badge:
<img width="243" alt="Screenshot 2024-05-25 at 10 48 32" src="https://github.com/google/site-kit-wp/assets/125576926/17149075-4028-4fae-a27d-95ee4b44aac7">


**Figma:**
Top margin is 16px
<img width="844" alt="Screenshot 2024-05-25 at 10 44 30" src="https://github.com/google/site-kit-wp/assets/125576926/19d2a37e-ac27-4c28-a6ed-c762d3c2d3ca">

Bottom margin is 14px:
<img width="774" alt="Screenshot 2024-05-25 at 10 44 51" src="https://github.com/google/site-kit-wp/assets/125576926/6670a580-2933-4050-b682-46531185ab81">


Tooltip overlaps with badge:
<img width="354" alt="Screenshot 2024-05-25 at 10 49 49" src="https://github.com/google/site-kit-wp/assets/125576926/ad9a075a-c3f6-4617-88e7-d645d108a314">

<Details>

**ITEM 4:**

Bottom margin should be 12px instead of 16px

<Details>
Implementation:
Margins are 16px top, bottom and sides
<img width="898" alt="Screenshot 2024-05-25 at 10 25 37" src="https://github.com/google/site-kit-wp/assets/125576926/8d49890f-5f25-4948-ab1c-d76e81d1ad8c">


Figma:
Bottom is 12px.
<img width="705" alt="Screenshot 2024-05-25 at 10 52 33" src="https://github.com/google/site-kit-wp/assets/125576926/cbee0c89-d8c5-4a90-b88b-b19c0dbd586a">


</Details>

**Comment by nfmohit** [comment]
Thank you for sharing your observations, @kelvinballoo!

> **ITEM 1:**
> I noticed that on Storybook, the tooltip would appear at the bottom instead of the top on Figma.
> Can you confirm that this is because of the window spacing that we have above and that by default, it will appear at the bottom?

That is correct. I can confirm that the tooltip by default will show up at the top, unless there isn't any space available at the top, in which case, it will appear at the bottom.

> **ITEM 2:**
> The margins around the badge is not consistent with Figma
> Refer to the details below.

We are not changing the dimensions of the tile header here because that is outside the scope of this issue.

If you look at the Figma designs, the tile heading seems to have an inconsistency when it comes to height, for example, in [this mock](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1261-8985&m=dev), the tile header has a height of 72 pixels, while [here](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1046-42007&m=dev), it has a height of 76 pixels. It might be worth raising this inconsistency internally to see if an additional issue is needed to apply the correct dimensions.

Instead of changing the tile header height in this issue, we're simply adding the partial data badge but keeping the height same as it was before so that it doesn't look inconsistent with other tiles that may not have the badge.

> **ITEM 3:** At the metric level badge on desktop:
> 
> * Top margin should be 16px instead of 12px
> * Bottom margin should be 14px instead of 10px
> * Note that on the details the tooltip popup is on top of the badge and not above placement of tooltip
>   Details are below

For the top and bottom margins, I have opened a follow-up PR [#8760](https://github.com/google/site-kit-wp/pull/8760) to increase them.

However, regarding the overlap of the tooltip into the badge, we use our re-usable tooltip component here (and everywhere else) which by principle does not overlap with the host element. I believe it would be wiser to follow the same behavior here for consistency.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 
Thanks @hussain-t ,

Reviewed the top and bottom the partial badge at the metric level and results are looking good:
- 16px at the top
- 14 px at the bottom
   <Details>
   12px + 4 px = 16px at the top:
   <img width="1004" alt="Screenshot 2024-05-29 at 17 50 50" src="https://github.com/google/site-kit-wp/assets/125576926/1d3da8e4-60ed-415e-b014-111ec0e52d2d">

   <img width="1006" alt="Screenshot 2024-05-29 at 17 54 26" src="https://github.com/google/site-kit-wp/assets/125576926/0e0b7925-fd5d-4ddd-b705-9f6e90bde7d9">


   14px at bottom:
   <img width="1300" alt="Screenshot 2024-05-29 at 17 50 38" src="https://github.com/google/site-kit-wp/assets/125576926/25fa323f-d18f-4a88-9ae1-6192953dedf5">

   </Details>

Remaining ACs were tested good.
The new Audience partial data and Top content partial data story variants match Figma closely. There are some bits that are not exactly the same because of consistency across other parts of the website.

<Details>
<img width="1011" alt="Screenshot 2024-05-29 at 17 57 28" src="https://github.com/google/site-kit-wp/assets/125576926/62cc2302-b97b-414e-9d03-09bef0e79004">


<img width="1008" alt="Screenshot 2024-05-29 at 17 57 37" src="https://github.com/google/site-kit-wp/assets/125576926/b0fe9bb2-53f5-4b63-b9a5-30a3d5747018">

</Details>

Moving ticket to 'Approval'
