### ISSUE TITLE
Implement the Selection Panel Info Notice

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8159]
## Feature Description

Implement the info notice will be displayed when the Selection Panel is opened with only one item selected.

See [audiences creation > info notice](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.vm6vp7cnnu2r) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If there is only one audience currently selected, when the Selection Panel is opened it will display a dismissible info notice encouraging the user to add another audience to the selection.
* The notice should disappear when the user selects an additional audience. It should not reappear if the user reduces the selection to a single audience while the selection panel remains open.
* This should be implemented as per the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1046-44966&mode=design&t=9sm6bwApE8GcSrQa-0).
* It will have a **Got it** button for dismissing the notice. Clicking the button will permanently dismiss the notice and it will not be shown again to the current user.

## Implementation Brief

_Note: It could be worth taking a look at the Info Notice component to see if can be refactored for reuse. See https://github.com/google/site-kit-wp/issues/8137._

* [ ] Once #8158 and #8157 are merged.

In `assets/js/modules/analytics-4/components/dashboard/AudienceSegmentation/InfoNotice.js`:

* [ ] Add a new `id` prop to the `InfoNotice` component.
* [ ] Add a new `infoIcon` prop to the `InfoNotice` component.
* [ ] Add the `id` to the `div` element.
* [ ] Render the `infoIcon` prop if it is provided. Otherwise, render the `LightbulbIcon` component.

In the selection panel component, which is being implemented in #8157:

* [ ] Get the selected/configured audiences using the `getConfiguredAudiences` selector.
* [ ] Get the `InfoNotice` dismissible state using the `isItemDismissed` selector using an appropriate `id` value.
* [ ] If only one audience AND the `InfoNotice` is not dismissed, render the `AudienceSegmentation/InfoNotice` component.
* [ ] Pass an appropriate `id` value to the `InfoNotice` component.
* [ ] Extract the info icon from the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1046-44966&mode=design&t=9sm6bwApE8GcSrQa-0) and pass it as the `infoIcon` prop to the `InfoNotice` component.
* [ ] Pass `Got it` as the `dismissLabel` prop.
* [ ] Pass a callback function to the `onDismiss` prop that dismisses the `InfoNotice` using the `dismissItem` action.
* [ ] Pass the below text to the `content` prop:
    ```
    By adding another group to your dashboard, you will be able to compare them and understand which content brings back users from each group
    ```
* [ ] Preferably, create a new component for the selection panel info notice and use it in the selection panel component to keep the code clean and maintainable.

### Test Coverage

* [ ] In case of a new component, create a new storybook file for it.
* [ ] Add a story to the selection panel storybook to show the info notice when only one audience is selected.
* [ ] Add a new story to the `AudienceSegmentation/InfoNotice` storybook to include the new `infoIcon` prop.

## QA Brief

* Set up Site Kit with the `audienceSegmentation` feature flag.
* Connect an Analytics property that has a few audiences created.
* Open the audience selection panel and verify that the notice described in this issue does not show up.
* Select one of the audiences from the list and save your selection.
* Reopen the selection panel and verify that the notice now shows up.
	* Verify that the notice looks and behaves according to the ACs and Figma designs.
* Select more than one audience and resave your selection.
* Reopen the selection panel and verify that the notice disappears.
* Again, select one audience and resave your selection. Re-open the selection panel and dismiss the notice using the "Got it" button. Verify that the notice no longer appears.

## Changelog entry

* Show a notice in the Audience Selection Panel when it's opened with a single audience in the selection.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

I want to verify one scenario.
Should the notice appear if we only select one audience without clicking save or we should have clicked save?
From the QAB and from my gut feel, it should appear when we do the selection.

However, currently it only appears after clicking save.
Video is attached below for reference:

<Details>

https://github.com/google/site-kit-wp/assets/125576926/b2b46cfc-5868-4929-b914-842deb7dabb9


</Details>

**Comment by nfmohit** [comment]
Hi Kelvin.

According to the ACs, the notice should only appear when you have a saved selection of one audience. Please see [this comment](https://github.com/google/site-kit-wp/pull/8881#pullrequestreview-2125354523) in the PR.

Thanks!

**Comment by kelvinballoo** [comment]
### QA update ⚠️ 

Thanks @nfmohit .
I've tested this in more detail and I have a 2 observations:

**ITEM 1:**
I am not sure if this is under the scope for this ticket but currently in terms of visuals, there is a gap between the horizontal lines until the alignment of the button.
This is easier to understand with the detailed screenshots attached below.

<Details>
Figma: No gap
<img width="1201" alt="Screenshot 2024-06-24 at 16 18 15" src="https://github.com/google/site-kit-wp/assets/125576926/4e5c0ebc-75ca-4a62-ae3a-f9b3b7871d7a">

Implementation : Gap exists here:
<img width="1221" alt="Screenshot 2024-06-24 at 16 18 29" src="https://github.com/google/site-kit-wp/assets/125576926/1b53d567-212d-4370-a400-119a163287af">

</Details>

________________________________________________________________
**ITEM 2:**

Again, this could be out of scope for this ticket. Let me know if a new ticket is required for this.
The layout on mobile and tablet is broken. 
2 things to highlight here:
- The 'Top content by pageviews' section goes beyond the screen viewport. I suspect it's due to the long title names which are not truncated on those breakpoints.
- The tile is a single tile but you will see that there is a mark under 'All visitors' denoting as if there are other tabs but this is false. If it's a single tab, there should be no mark underneath. 

Refer to the details below:

<Details>
<img width="339" alt="Screenshot 2024-06-24 at 16 59 47" src="https://github.com/google/site-kit-wp/assets/125576926/2863d851-5e9f-41a8-8a77-e75692ea45ad">



On figma, when there is a single tile, there is no marking under the Tile title:
<img width="243" alt="Screenshot 2024-06-24 at 16 57 40" src="https://github.com/google/site-kit-wp/assets/125576926/760441de-7ace-46b2-93f1-b7404d209abd">

</Details>

**Comment by nfmohit** [comment]
Hi @kelvinballoo, thank you for sharing your observations!

> **ITEM 1:**
> I am not sure if this is under the scope for this ticket but currently in terms of visuals, there is a gap between the horizontal lines until the alignment of the button.
> This is easier to understand with the detailed screenshots attached below.

This is expected. This happens because in smaller height viewports, a scroll bar is added to the audience items area, which pushes this section slightly to the left. As a result, the gap you see is created. Here is a screenshot without a scrollbar:

![image](https://github.com/google/site-kit-wp/assets/20284937/31721814-69e7-4a3f-8d1e-15bfa9c533fc)

> **ITEM 2:**
> 
> Again, this could be out of scope for this ticket. Let me know if a new ticket is required for this. The layout on mobile and tablet is broken. 2 things to highlight here:
> 
> * The 'Top content by pageviews' section goes beyond the screen viewport. I suspect it's due to the long title names which are not truncated on those breakpoints.
> * The tile is a single tile but you will see that there is a mark under 'All visitors' denoting as if there are other tabs but this is false. If it's a single tab, there should be no mark underneath.

This looks odd indeed. However, as you said, this is outside the scope of this issue. Pleaes check if this is already reported and if not, kindly open a new issue.

Please let me know if you have any other questions, thanks!

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks @nfmohit , issue raised under https://github.com/google/site-kit-wp/issues/8930 

I can conclude this ticket is good to. Tested the following:
- With an Analytics property that has a few audiences created, when opening the audience selection panel, the notice doesn't appear.
- After saving one selection and reopening the panel, the notice now shows up.
- The notice looks and behaves according to the ACs and Figma designs.
- When selecting one more audience, the notice disappears.
- When dismissing the notice using the "Got it" button, the notice no longer appears and it won't come back if one audience selection is done and saved again later.

Moving ticket to approval.

<Details>
Upon selecting and saving one audience, the notice appears:
<img width="469" alt="Screenshot 2024-06-25 at 11 36 26" src="https://github.com/google/site-kit-wp/assets/125576926/d8c7e084-9141-433b-a739-bbc5a31f74e4">


When selecting another audience without saving, it will disappear:
<img width="476" alt="Screenshot 2024-06-25 at 11 36 33" src="https://github.com/google/site-kit-wp/assets/125576926/1fc4d93d-8fe3-430a-9fa0-8ca0f3d3e168">


</Details>
