### ISSUE TITLE
Completing Analytics setup with a new profile fails

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#816]
## Bug Description

When setting up Analytics to create a new profile, the setup completes with a success message, and the profile is created, but Analytics does not indicate that it is connected.

When navigating to the Analytics page, you are then prompted again to choose your account, property, and profile (even though these are properly pre-selected). Saving again does connect Analytics.

## Steps to reproduce

1. Set up Analytics using the "New Profile" option
1. See Analytics is not "connected"

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/68417895-eca6be80-019f-11ea-8fd7-41fd2e40446f.png)

Note above that Analytics was just set up, but does not indicate it is connected.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Analytics is properly connected after setup with a new property

## Implementation Brief

Ensure the `internalWebPropertyId` is set after property creation. Currently this is `null` after the setup described above.

See #817 

## Changelog entry

* Fix error that could occur when setting up a new Analytics profile from the module setup.

**Comment by cole10up** [comment]
Tested via Jurassic Ninja WP Version 5.2.4

**Test steps**

1. Kicked off a new site at Jurassic.ninja
2. Installed latest latest Site Kit with this commit and activated it
3. Configured Analytics
![image](https://user-images.githubusercontent.com/57115907/68427756-9fa2f800-015f-11ea-8d7c-ac2343a1f4ed.png)

4. Confirmed Analytics is showing 'Connected' post setup completion
![image](https://user-images.githubusercontent.com/57115907/68431279-ae40dd80-0166-11ea-88e2-03cc0eca0e81.png)


5. Confirmed Analytics is functional after configuration
![image](https://user-images.githubusercontent.com/57115907/68431004-0deab900-0166-11ea-856c-4060896e026a.png)

This is confirmed fixed in QA!
