### ISSUE TITLE
Implement the Settings Section unhappy setup path

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8179]
## Feature Description

Implement the Settings Section unhappy setup path, including errors returned from the OAuth flow.

See [Settings section > setup CTA](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.5dmqdfre5wc) and
[OAuth errors](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.tfz9l0v91tcy) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- Having clicked on **Enable groups** in the Settings section, if an error occurs, whether it's an error returned from the OAuth flow, or from an API call made to create the audiences and/or custom dimension, the Error Modal should be displayed on the Settings screen.
  - If an error is returned from the OAuth flow:
    - The OAuth error variant of the Error Modal should be displayed.
    - It should follow the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1890-23488&mode=design&t=rPamL7stYGR0AGkR-0), with the following copy:
      - Title: _Analytics update failed_
      - Description: _Setup was interrupted because you did not grant the necessary permissions. [Get help]()_
    - The **Retry** button should take the user back to the OAuth flow to retry the setup from that point.
    - The **Cancel** button should close the modal.
    - The default OAuth error notice that Site Kit usually displays when the OAuth flow returns an error should not be shown.
  - If a permission error is returned by one of the API calls:
    - The "insufficient permissions" variant of the Error Modal should be displayed.
    - It should follow the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1890-23292&mode=design&t=rPamL7stYGR0AGkR-0), with the following copy:
      - Title: _Insufficient permissions_
      - Description: _You’ll need to contact your administrator. Trouble getting access? [Get help]()_
    - The **Request access** button should open the URL for the currently connected web data stream in the Analytics UI, allowing the user to request access.
    - The **Cancel** button should close the modal.
  - If any other error is returned by one of the API calls:
    - The generic error variant of the Error Modal should be displayed.
    - It should follow the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1890-23073&mode=design&t=ncplA7YLtzqUq2gL-0), with the following copy:
      - Title: _Failed to set up visitor groups_
      - Description: _Oops! Something went wrong. Retry enabling groups._
    - The **Retry** button should close the modal, retry the failed API call(s) and continue setup from that point.
    - The **Cancel** button should close the modal.
- The _Get help_ links should open the Analytics support page in a new tab, scrolled to the [insufficient permissions](https://sitekit.withgoogle.com/documentation/troubleshooting/analytics/#insufficient-permissions) section.

---

- Note that all copy should be verified with Figma as the source of truth.

## Implementation Brief

_Note that the AC are mostly identical to https://github.com/google/site-kit-wp/issues/8134 and the implementation reuses much of this tickets approach as well as the AudienceErrorModal component._

 * [x] Update `assets/js/modules/analytics-4/components/audience-segmentation/settings/SettingsCardVisitorGroups/SetupCTA.js`:
    * [x] Add new boolean component state `showErrorModal`.
    * [x] Update the use of the `useEnableAudienceGroup` hook to match the `AudienceSegmentationSetupCTAWidget` component, by destructuring the new props `apiErrors` and `failedAudiences`, and adding the new onError callback, setting `showErrorModal` to true:
    https://github.com/google/site-kit-wp/blob/41f0bbaec9736ba334cccc7b469ce1a5e2cdfc71/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.js#L106-L117
    * [x] Conditionally render `AudienceErrorModal` in this component, like so:
    https://github.com/google/site-kit-wp/blob/41f0bbaec9736ba334cccc7b469ce1a5e2cdfc71/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.js#L296-L308
       * [x] Add the required onCancel callback, like so:
       https://github.com/google/site-kit-wp/blob/41f0bbaec9736ba334cccc7b469ce1a5e2cdfc71/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.js#L147-L154
       * [x] Get any error codes to pass to the error modal, like so:
       https://github.com/google/site-kit-wp/blob/41f0bbaec9736ba334cccc7b469ce1a5e2cdfc71/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.js#L156-L160
 * [x] Update OAuth error function to support a custom error redirect URL (based on this draft PR: https://github.com/google/site-kit-wp/pull/9298), to redirect back to the Visitor Groups settings panel if the OAuth flow was triggered from this component.

### Test Coverage

* Add tests for the SetupCTA component testing it's rendering conditions as well as each error condition above ([you can use these tests as a guide](https://github.com/google/site-kit-wp/blob/3919b7e7bd877208b140951362c2fb773006d976/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.test.js#L642-L819)).
* Add new tests for the error redirect URL functionality of the OAuth infrastructure.

### Prerequisites

1. Setup Analytics and enable the `audienceSegmentation` feature flag.
2. Ensure no audiences have been created or configured.
3. Navigate to **Settings > Admin Settings**, and complete the testing here using the Setup CTA in settings:
<img width="883" alt="Screenshot 2024-09-16 at 12 43 28" src="https://github.com/user-attachments/assets/2490457a-39ab-42b7-8119-a1c4796cc5b4">

### Testing the Audience Error Modal Variants

There are three Audience Error Modal variants to test:

1. OAuth error variant.
2. Insufficient permissions error variant.
3. Generic error variant.

### OAuth Error Variant

To simulate the OAuth error variant:

1. **Prepare the Environment:**
   - Delete the `wp_googlesitekit_additional_auth_scopes` entry from the `wp_usermeta` table if it exists. This entry contains the `https://www.googleapis.com/auth/analytics.edit` scope.
   
2. **Trigger the OAuth Error:**
   - Click on the **Enable groups** button in the Admin Settings, Visitor Groups CTA panel.
   - In the OAuth flow, when prompted to grant permissions, cancel the flow.
   - Ensure the OAuth error variant of the Error Modal is displayed.
   - Click the **Retry** button to trigger the OAuth flow again.
   - Complete the OAuth flow and grant permissions.
   - Ensure the setup continues successfully after granting permissions.

*Note: this update introduces changes which could effect other OAuth error flows, so it's worth spending QA time reviewing other OAuth error flows to confirm there are no regressions caused by this work.*

### Insufficient Permissions Error Variant

To simulate the Insufficient Permissions error variant:

1. **Install and Configure Tweak Extension:**
   - Install the [Tweak](https://chromewebstore.google.com/detail/tweak-mock-and-modify-htt/feahianecghpnipmhphmfgmpdodhcapi?hl=en) Chrome extension.
   - Add a new rule to block the `sync-audiences` request:
     - URL: `.*/wp-json/google-site-kit/v1/modules/analytics-4/data/sync-audiences*`
     - Enable the use of regular expression `(.*)`
     - HTTP Method: `POST`
     - Status code: `403`
     - Response payload:
       ```json
       {
         "code": 403,
         "message": "Insufficient Permissions Test Error",
         "data": {
           "status": 403,
           "reason": "insufficientPermissions"
         }
       }
       ```

2. **Trigger the Insufficient Permissions Error:**
   - Click on the **Enable groups** button in the Admin Settings, Visitor Groups CTA panel.
   - Ensure the Insufficient Permissions error variant of the Error Modal is displayed.
   - Click on the **Request access** button and verify the Analytics console opens in a new tab.

### Generic Error Variant

To simulate the Generic Error variant, there are two scenarios:

1. **Other API Errors:**

   * **Simulate Sync Available Audiences API Error:**
     - Add a new rule in the Tweak extension to block the `sync-audiences` request:
       - URL: `.*/wp-json/google-site-kit/v1/modules/analytics-4/data/sync-audiences*`
       - Enable the use of regular expression `(.*)`
       - HTTP Method: `POST`
       - Status code: `500`
       - Response payload:
         ```json
         {
           "code": "internal_server_error",
           "message": "Internal server error",
           "data": { "status": 500 }
         }
         ```

   * **Trigger the Generic Error:**
     - Click on the **Enable groups** button in the Admin Settings, Visitor Groups CTA panel.
     - Ensure the Generic error variant of the Error Modal is displayed.
     - Disable the rule to unblock the request in the Tweak extension.
     - Click the **Retry** button to ensure the setup continues successfully.

## Changelog entry

* Implement the unhappy path for the Settings Section Audience Segmentation setup flow, handling OAuth and API errors by displaying an Error Modal with options to retry, request access, or get help.

**Comment by benbowler** [comment]
Reducing the estimate as this ticket makes use of much of the work in #8134, and it mostly applying this proven approach to a new component.

**Comment by techanvil** [comment]
Hi @benbowler, thanks for drafting the IB. A couple of points:

- There is some additional work required in order to allow the Settings page to be navigated back to in response to an OAuth error. At the moment the error handling is hard baked to redirect to the dashboard or splash screen:
https://github.com/google/site-kit-wp/blob/0e32045bb530d8bd22b5dde634da1510beeefa36/includes/Core/Authentication/Clients/OAuth_Client.php#L651-L655
  - I've put a PoC together of how we could address this: https://github.com/google/site-kit-wp/pull/9298
- We'll also want some test coverage, both for the OAuth related changes, and it would be good to provide test coverage on the JS side too, we do have test coverage relating to the error modal in the [tests for `AudienceSegmentationSetupCTAWidget`](https://github.com/google/site-kit-wp/blob/3919b7e7bd877208b140951362c2fb773006d976/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.test.js#L642-L819) which we're using as a guide.

**Comment by techanvil** [comment]
Thanks @benbowler. The IB LGTM, I've bumped the estimate up to reflect the additional work needed here - the tests could get a bit fiddly in places.

IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested using Tweak extension.


### **OAuth Error Variant**

- If an error is returned from the OAuth flow:
- _Verified that_

- -   Verified that The OAuth error variant of the Error Modal gets display.
- -   Verified it is same as [Figma design} with the following copy:
- -    Title: Analytics update failed
- -    Description: Setup was interrupted because you did not grant the necessary permissions. [Get help.](https://github.com/google/site-kit-wp/issues/8179)
- -    The Retry button take the user back to the OAuth flow to retry the setup from that point.
- -    The Cancel button close the modal.
- -    The default OAuth error notice that Site Kit usually displays when the OAuth flow returns an error not be shown.
- -    Also, verified the OAuth flow error flow for all modules. 
- -    Clicking on 'Get help' link opens  Analytics support page in a new tab,

<details>


https://github.com/user-attachments/assets/775c8fe3-373d-42d8-9ce4-30fa50ebe56c


https://github.com/user-attachments/assets/9e3eae51-745b-4dc5-9d7b-8729d7d40add

</details>


### **Insufficient Permissions Error Variant**

- If a permission error is returned by one of the API calls:

-  _Verified that -_ 

- - The "insufficient permissions" variant of the Error Modal gets display.
- - It  follow the [Figma design], with the following copy:
- - Title: Insufficient permissions
- - Description: You’ll need to contact your administrator. Trouble getting access? [Get help](https://github.com/google/site-kit-wp/issues/8179)
- - The Request access button  open the URL for the currently connected web data stream in the Analytics UI, allowing the user to request access.
- - The Cancel button close the modal.
- - The Get help link open the Analytics support page in a new tab, scrolled to the [insufficient permissions](https://sitekit.withgoogle.com/documentation/troubleshooting/analytics/#insufficient-permissions) section.

<details>

https://github.com/user-attachments/assets/1cf5f0de-4697-475d-84b6-a17c329ef528

https://github.com/user-attachments/assets/6dacade0-840c-4df9-9310-38c3158a7f91

</details>

### **Generic Error Variant**

- If any other error is returned by one of the API calls:
- Verified that
- - The generic error variant of the Error Modal gets display.
- -  It  follow the [Figma design] with the following copy:
- - Title: Failed to set up visitor groups
- - Description: Oops! Something went wrong. Retry enabling groups.
- - The Retry button  close the modal, retry the failed API call(s) and continue setup from that point.
- - The Cancel button close the modal.
- - Disabling the rule to unblock the request in the Tweak extension and Clicking the Retry button continues complete the setup successfully.

<details>


https://github.com/user-attachments/assets/42d4cc00-58e6-48cc-8db4-03f99ce80813


https://github.com/user-attachments/assets/2a53932e-a433-4114-b9e0-71103fe03a28

</details>
