### ISSUE TITLE
Add the Full Width Error Banner (Storybook)

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8230]
## Feature Description

Create the Full Width Error Banner component and add it toStorybook.

See [full width error banner](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.xfl89g3zosvd) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Full Width Error Banner component should be created and stories for it added to Storybook.
* It should be implemented according to the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=2389-25121&mode=design&t=Not6P82XkODjzUiD-0).
* The component should accept a list of errors as a prop.
  * If any of the errors is a permissions error, the "insufficient permissions" variant of the error notice will be shown (as mentioned in the [design doc](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.b9x8clic313y), including a _Get help_ link and a **Request access** buttons.
    * Its _Get help_ link will open the [Analytics insufficient permissions support document](https://sitekit.withgoogle.com/documentation/troubleshooting/analytics/#insufficient-permissions).
    * The **Request access** button will open the URL for the connected web data stream in the Analytics UI, allowing the user to request access.
  * Otherwise, the catch-all variant will be shown which just includes the **Retry** button.
    * Clicking the **Retry** button will retry whatever triggered the errors (i.e. it will invalidate the resolution for the selector associated with the errors).

## Implementation Brief

In the `assets/js/modules/analytics-4/components/dashboard/AudienceSegmentation` directory:

* [x] Create a new file, `AudienceSegmentationErrorWidget.js`, for the Full Width Error Banner component.
* [x] It can follow a similar structure as the `AudienceSegmentationSetupCTAWidget` component.
* [x] It should receive a list of errors as a prop.
* [x] Wrap the body with the `Widget` component and add the `noPadding` prop to it to layout the SVG graphics.
* [x] Within the `Widget` component, use `Grid->Row->Cell` to arrange the error notice and buttons.
* [x] Use the `h3` element for the error notice.
* [x] Export the error SVG from the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=2258-36678&mode=design&t=boHCZPMmP1svtJjc-0) and render it in the component.
* [x] Check for "insufficient permissions" errors using the `isInsufficientPermissionsError` helper function and render the `Insufficient permissions` copy.
* [x] Otherwise, render the `Your visitor groups data loading failed` copy.
* [x] Render the `ReportErrorActions` component with the following props, which will render the error variant-specific buttons appropriately (See `MetricTileWrapper`) :
    * `moduleSlug` - pass the `analytics-4` module slug.
    * `error` - pass the errors.
    * `hideRetryHelpLink` - a boolean prop to hide the `Get help` link if the error is not a permissions error.
    * `GetHelpLink` - Create a new `GetHelpLink` component that renders the `Contact your administrator. Trouble getting access?` copy and the `Get help` link. It should be similar to the `assets/js/components/KeyMetrics/GetHelpLink.js` component.
    * `getHelpClassName` - custom class name for the `Get help` link.
* [x] Adjust the styles that match the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=2389-25121&mode=design&t=Not6P82XkODjzUiD-0).

In `assets/js/components/ReportErrorActions.js`:

* [ ] Add a new boolean prop `hideRetryHelpLink`.
* [ ] Render the `Retry` get help link if `hideRetryHelpLink` is falsy. See:
https://github.com/google/site-kit-wp/blob/7911c0a124cd39bcf0b5a1b98824518510342b56/assets/js/components/ReportErrorActions.js#L130-L148

### Test Coverage

* [x] Add storybook stories for the `AudienceSegmentationErrorWidget` component.
* [x] Add test coverage for the `AudienceSegmentationErrorWidget` component, particularly around the retry logic and different conditions for rendering different sets of copy.

## QA Brief

* Review the [Storybook stories for AudienceSegmentationErrorWidget](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-audiencesegmentationerrorwidget--default) to ensure they align with the provided Figma designs and AC.
* Note that the buttons and links in the error banner are not functional in this PR.
* Default error state [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=2258-36268&mode=design&t=MWOmDiLf03dDQUeW-4).
* Insufficient permissions error state [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=2389-25221&mode=design&t=MWOmDiLf03dDQUeW-4).

## Changelog entry

* Add the Full Width Error Banner for the Audience Segmentation feature as a component in Storybook.

**Comment by tofumatt** [comment]
IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ❌ 

Tested on [Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-audiencesegmentationerrorwidget--insufficient-permissions) and documented my issues below:

**ITEM 1:**
Font weight for 'Retry' button should be 500 instead of 400
Font should be 'Google sans Text' but it's 'Google Sans Display' for the Main title. 
These are applicable for both the default and the permission error states.

<Details>
Implementation: The font weight is currently 400:
<img width="1312" alt="Screenshot 2024-04-28 at 23 32 20" src="https://github.com/google/site-kit-wp/assets/125576926/454264c9-f586-4b2e-a3c7-0d46548cae9b">

Figma: The font weight should be 500.
<img width="1017" alt="Screenshot 2024-04-28 at 23 33 23" src="https://github.com/google/site-kit-wp/assets/125576926/6339ed89-e07f-4e65-8c1c-cbb6557eb989">


</Details>
__________________________________________________

**ITEM 2:**
- Distance between msg and button should be 14px instead of 18px

<Details>
Figma:
<img width="539" alt="Screenshot 2024-04-28 at 23 35 38" src="https://github.com/google/site-kit-wp/assets/125576926/2ec938d9-adb8-4a19-948c-fda245423d2a">

Implementation: The gap is currently at 18px
<img width="1297" alt="Screenshot 2024-04-28 at 23 36 58" src="https://github.com/google/site-kit-wp/assets/125576926/250d4a2a-91db-4262-b4ed-6473dcb0cfac">

</Details>
__________________________________________________

**ITEM 3:**
- The top of the image should be 20px from the top of the block but it's more than that currently. 
- Similarly at the bottom, the gap should have been 20px below the image but it's less than that.
Refer to the details for more details:

<Details>
Figma:
<img width="813" alt="Screenshot 2024-04-28 at 23 39 46" src="https://github.com/google/site-kit-wp/assets/125576926/61a37e39-d75a-4bbb-9495-b82da5288afb">

Implementation:
<img width="1312" alt="Screenshot 2024-04-28 at 23 41 58" src="https://github.com/google/site-kit-wp/assets/125576926/a67e30cb-d1c5-4dbe-a5a9-4d48f7b372e3">

</Details>

__________________________________________________

**ITEM 4:**
Overall button size on Figma is 68 x 32 px
And the Top and bottom margin inside button should be 6px.

If you look at the current implementation, the overall button size is (33.75+16+16) x (8+24+8) = 65.75 x 40px
And the Top and bottom margin inside button is 8px.

<Details>
Figma:
<img width="1013" alt="Screenshot 2024-04-28 at 23 46 27" src="https://github.com/google/site-kit-wp/assets/125576926/3a2b7c7b-a8ae-4ce4-822e-4e39488e279a">

Implementation:
<img width="1310" alt="Screenshot 2024-04-28 at 23 48 34" src="https://github.com/google/site-kit-wp/assets/125576926/f2374088-d9a4-412d-b365-d6e3633806ec">


</Details>
__________________________________________________

**ITEM 5:**
We don't have a design on mobile but I feel that we can set the top and bottom spaces more equal for a better visual?
Currently, the top section is bigger than the bottom.

<Details>
<img width="495" alt="Screenshot 2024-04-28 at 23 54 56" src="https://github.com/google/site-kit-wp/assets/125576926/01d571cd-102d-4b14-b06e-dfae96efe160">


</Details>

__________________________________________________

**ITEM 6:**
There is a very weird behaviour at breakpoint 960px. 
At 959px, the image is at the left.
At 960px, it's at the centre.
At 961px, it's at the right.
While we are transitioning from tablet to desktop, I don't know why we have an odd one at 960px. It feels weird to me.
Let me know if there is a valid reason for this.

<Details>
959px:
<img width="988" alt="Screenshot 2024-04-28 at 23 57 41" src="https://github.com/google/site-kit-wp/assets/125576926/eeba5122-4355-4b0a-b905-85c488dca104">

960px:
<img width="993" alt="Screenshot 2024-04-28 at 23 57 35" src="https://github.com/google/site-kit-wp/assets/125576926/18986b92-3c66-4779-a512-db25af930a76">

961px:
<img width="960" alt="Screenshot 2024-04-28 at 23 57 49" src="https://github.com/google/site-kit-wp/assets/125576926/b72d76e1-edf9-457d-94cd-d3cc984f3400">

</Details>

**Comment by hussain-t** [comment]
Thanks for raising the issues, @kelvinballoo. I've addressed most of the observations in the follow-up [PR](https://github.com/google/site-kit-wp/pull/8638).

>ITEM 1:
Font weight for 'Retry' button should be 500 instead of 400
Font should be 'Google sans Text' but it's 'Google Sans Display' for the Main title.
These are applicable for both the default and the permission error states.

Fixed ✅ 

>ITEM 2:
Distance between msg and button should be 14px instead of 18px

Fixed ✅ 

>ITEM 3:
The top of the image should be 20px from the top of the block but it's more than that currently.
Similarly at the bottom, the gap should have been 20px below the image but it's less than that.
Refer to the details for more details:

Fixed ✅ 

>ITEM 4:
Overall button size on Figma is 68 x 32 px
And the Top and bottom margin inside button should be 6px.
If you look at the current implementation, the overall button size is (33.75+16+16) x (8+24+8) = 65.75 x 40px
And the Top and bottom margin inside button is 8px.

Figma design can be a bit out of alignment with the actual plugin implementation. You can see examples in the plugin. We should keep it consistent with the existing styles.

>ITEM 5:
We don't have a design on mobile but I feel that we can set the top and bottom spaces more equal for a better visual?
Currently, the top section is bigger than the bottom.

Fixed ✅ 

>ITEM 6:
There is a very weird behaviour at breakpoint 960px.

Fixed ✅

**Comment by hussain-t** [comment]
@techanvil, back to you to review the follow-up [PR](https://github.com/google/site-kit-wp/pull/8638). Thanks!

**Comment by techanvil** [comment]
Thanks @hussain-t!

Back to you for another pass, @kelvinballoo.

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Thanks @hussain-t .
Tested good overall.

Need your help to check on item 5.

**ITEM 1:** ✅ 
For both the default and the permission error states:
- Font weight for buttons are now 500
- Font is now  'Google sans Text' for the Main title.
<Details>
</Details>
________________________________________________________________________

**ITEM 2:** ✅ 
Distance between msg and button is now 14px. 

<Details>
<img width="1018" alt="Screenshot 2024-04-30 at 15 06 44" src="https://github.com/google/site-kit-wp/assets/125576926/0a4f730f-ea4e-4417-bc92-d78d74042125">

</Details>

________________________________________________________________________

**ITEM 3:** ✅ 
The top and bottom of the image is now 20px.

<Details>
<img width="1023" alt="Screenshot 2024-04-30 at 15 19 18" src="https://github.com/google/site-kit-wp/assets/125576926/c9caa14e-9d2f-41a7-8324-9f4c68dc14d1">
</Details>

________________________________________________________________________

**ITEM 4:** ✅ 
Noted that we are keeping things consistent with other areas of the plugin. Figma is not consistent for this.

________________________________________________________________________

**ITEM 5:** ⚠️ 
While the bottom and top margin are the same, it does still feel like the previous one.
@hussain-t , could you elaborate on the changes done for this one?

<Details>
<img width="791" alt="Screenshot 2024-04-30 at 15 33 08" src="https://github.com/google/site-kit-wp/assets/125576926/f5915b83-8a69-47d5-85ab-9169f77b702a">

</Details>

________________________________________________________________________

**ITEM 6:** ✅ 
The 960px breakpoint follows that of 959px and that's more consistent.
This is good.

<Details>
<img width="1132" alt="Screenshot 2024-04-30 at 15 35 06" src="https://github.com/google/site-kit-wp/assets/125576926/208f40e0-77f2-4e7e-bc2b-c2302c44e774">

</Details>

**Comment by hussain-t** [comment]
Hi @kelvinballoo,

>ITEM 5: ⚠️
While the bottom and top margin are the same, it does still feel like the previous one.

I have addressed this issue in a new follow-up [PR](https://github.com/google/site-kit-wp/pull/8642). I've also fixed the spacing for the tablet viewport. 

@techanvil, back to you for another review.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

This is looking good on mobile and tablet viewports now.

<Details>
<img width="519" alt="Screenshot 2024-04-30 at 23 14 57" src="https://github.com/google/site-kit-wp/assets/125576926/3a029790-7991-4087-ba48-419624613f1c">

</Details>
<img width="921" alt="Screenshot 2024-04-30 at 23 13 31" src="https://github.com/google/site-kit-wp/assets/125576926/fce74a18-3570-4fde-90fd-d8265af8ac4f">

Moving ticket to Approval.
