### ISSUE TITLE
WP Consent API active tick is squashed at narrow tablet viewports.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8375]
## Bug Description

The circle around the tick that indicates the WP Consent API is active is squashed at narrow tablet viewports.

## Steps to reproduce

1. Install and activate the WP Consent API and navigate to the Consent Mode settings.
2. Set the viewport to a narrow tablet width e.g. 601px.
3. See the circle around the tick is squashed and clipped as per the screenshot below.

## Screenshots

![image](https://github.com/google/site-kit-wp/assets/18395600/9a53a6b9-3b7e-44c6-8b6c-01df3ba25448)

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: any
 - Plugin Version: pre-release 1.122.0
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The circle around the tick as described above should remain a proper circle at all viewport widths.

## Implementation Brief

* [x] Add `min-width: 22px` to the styling for the circle. Alternatively `flex-basis` might be appropriate to use here.

### Test Coverage

* No new tests needed.

## QA Brief

* Run through the steps to reproduce, and verify the tick is no longer squashed.

## Changelog entry

* N/A

**Comment by wpdarren** [comment]
Great spot @techanvil!  I should have noticed that.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that issue is resolve now and now on narrow tablet viewports WP consent API active tick is not appearing squashed.

<details>

Latest -

![image](https://github.com/google/site-kit-wp/assets/94359491/3785c564-0d59-4a5b-a03f-8b64d6def490)

Development -

![image](https://github.com/google/site-kit-wp/assets/94359491/8056dc13-a80b-45e0-a4f5-c88d0e96937e)

</details>
