### ISSUE TITLE
Extend Consent Mode to handle additional consent types out of the box.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8385]
## Feature Description

The initial Site Kit implementation of Consent Mode provides out of the box support for the consent parameters that are detailed in the [GTag reference docs](https://developers.google.com/tag-platform/gtagjs/reference#consent):

- `ad_storage`
- `ad_user_data`
- `ad_personalization`
- `analytics_storage`
- `wait_for_update`

However there are additional parameters documented elsewhere:

- `functionality_storage`
- `personalization_storage`
- `security_storage`

For reference see:
- https://developers.google.com/tag-platform/security/concepts/consent-mode
- https://support.google.com/analytics/answer/9976101#cmp-integrations

As noted in the second link above these are natively supported by numerous CMPs. We should verify their applicability and consider providing direct support for these parameters in Site Kit (i.e. without the user needing to leverage the Consent Mode filters).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Consent Mode module should be updated to support three new data usage consent types via the WP Consent API:
   - `functionality_storage`
   - `personalization_storage`
   - `security_storage`

## Implementation Brief

* [x] Update `includes/Core/Consent_Mode/Consent_Mode.php`, `render_gtag_consent_snippet` function:
   * [x] Add the three new consent types to the `$consent_defaults` array, with the default setting of `denied`.
   * [x] Update the `$consent_category_map` adding two new keys. These categories are based on the [definitions of each consent category here](https://github.com/humanmade/consent-api-js?tab=readme-ov-file#frequently-asked-questions):
      ```
         'functional' => array( 'functionality_storage', 'security_storage' ),
         'preferences' => array( 'personalization_storage' ),
      ```

### Test Coverage

* No additional test coverage required.

## QA Brief

 * Setup Consent Mode and a plugin like Complianz, test that these new consent categories can be approved by the user via a consent banner.

## Changelog entry

* Update Consent Mode to support additional consent types out of the box.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️, however the estimate is too high, i'll change it to 3.

**Comment by mohitwp** [comment]
@benbowler I can see 3 categories Functional , statistics and Marketing under consent banner created by Complianz plugin. Is QAB referring the same categories ? 

![image](https://github.com/google/site-kit-wp/assets/94359491/401c289d-f8ad-48e4-b6ce-8ad2f1b3fa13)

**Comment by benbowler** [comment]
Hey @mohitwp, here's some more detailed instructions on how to test this as it's not obvious from the plugin itself, you need to use the console and/or the GA Debug plugin:

1. Set up your site;
   i. Enable consent mode in the SK Admin Settings
   ii. Install and activate the WP Consent Mode plugin
   iii. Install, activate and set up Complianz plugin banner.
2. Install the GA Debug plugin or similar that lets you view the analytics tracking events
3. Now open a page on the site in an incognito tab, to simulate a new user coming to the site without any existing preferences saved.
4. When the page loads you will see the following GA event:
```
Processing GTAG command: ["consent", "default", {ad_personalization: "denied", ad_storage: "denied", ad_user_data: "denied", analytics_storage: "denied", functionality_storage: "denied", security_storage: "denied", personalization_storage: "denied", ...
```
*This will include the new keys: `functionality_storage`, `personalization_storage` and `security_storage`, all set to `denied`.*
5. When you click accept on the banner, you should see the GA event:
```
Processing GTAG command: ["consent", "update", {analytics_storage: "granted", ad_storage: "granted", ad_user_data: "granted", ad_personalization: "granted", functionality_storage: "granted", security_storage: "granted", personalization_storage: "granted"}]
```
*Again you can see the new keys here which have been updated to `granted`.*

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

- Thank you @benbowler !
- Tested on dev environment.
- Verified that  new keys: `functionality_storage, personalization_storage and security_storage`, all set to denied when banner appears.
- Verified when user click 'Accept' on banner.
- Verified when user click 'Denied' on banner.


@benbowler  I have few question related to my observations -

**Questions-**

1) When I click accept I'm getting separate update entry for the older and new keys not in a single line like you mentioned in QAB . Is this expected ?
2) Older keys `ads personalization , ad storage and analytics storage ` have 'user engagement' event associated with them but new keys don't have this event associated with them . Is this expected ?
3) For older keys two commands are appearing "Processing Command 1" and "Processing command 2" . But new keys update event are getting track under only "Processing Command 1". Is this expected ?
4) In case user click on "Deny" on banner then also  `functionality_storage: "granted", security_storage: "granted",` because both the necessary. It is also expected?

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/ef34f1ff-6a2f-4cb3-a084-0fe71476dce8)

![image](https://github.com/google/site-kit-wp/assets/94359491/555dff9f-ddf2-4e5e-b327-682b5bf0a246)

When user click on 'Deny' button

![image](https://github.com/google/site-kit-wp/assets/94359491/88c9c56a-817b-4adf-a2b5-1f3a1b6c491e)

</details>


**Pass Cases**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/36b76358-7958-483f-a0b2-d39e0f214746)

When user click on Accept


https://github.com/google/site-kit-wp/assets/94359491/4d03539e-b7a0-4e27-aff8-ca7c0952ea06


When user click on Deny

https://github.com/google/site-kit-wp/assets/94359491/fc518a32-1e6d-4d4d-af5c-e33705bd4d7c

</details>

**Comment by benbowler** [comment]
Hey @mohitwp, thanks for your questions. The way the consents are updated varies on the plugin used and that plugins configuration. As long as all of the new consent types are there and able to be updated it doesn't matter if there are in single/multiple events or how those events are strucutured.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that  new keys: `functionality_storage, personalization_storage and security_storage`, all set to denied when banner appears.
- Verified when user click 'Accept' on banner.
- Verified when user click 'Denied' on banner.
- Verified when user clicks on Preferences.

![image](https://github.com/google/site-kit-wp/assets/94359491/36b76358-7958-483f-a0b2-d39e0f214746)

**When user clicks on Accept button on banner**



<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/3a0982d4-038e-41bd-b0db-f15f6d02f458)

![image](https://github.com/google/site-kit-wp/assets/94359491/5b43c457-53dc-4094-95df-c9bb9d8302a7)

![image](https://github.com/google/site-kit-wp/assets/94359491/a514995f-c885-4b8e-88ac-9acad3842d8b)

https://github.com/google/site-kit-wp/assets/94359491/4d03539e-b7a0-4e27-aff8-ca7c0952ea06

</details>

**When User clicks on Deny Button**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/c782744f-efa2-4771-8a5f-432677397d7f)

![image](https://github.com/google/site-kit-wp/assets/94359491/1f6f3647-3593-46fb-a89f-883b1b0d3175)

![image](https://github.com/google/site-kit-wp/assets/94359491/7f4acf4d-cb1d-4bb4-a368-f59730540f11)

https://github.com/google/site-kit-wp/assets/94359491/fc518a32-1e6d-4d4d-af5c-e33705bd4d7c

</details>


**Save Preferences - Personalization storage granted**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/93f27049-e899-498f-8ba1-74a653f0e059)

![image](https://github.com/google/site-kit-wp/assets/94359491/c5baf4e1-ef7d-421a-a23e-ffa0074dd5cc)

</details>

**Save Preferences - Statistics (Personalization storage not granted)**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/4952f512-b106-40b4-b113-ac81cd511cee)

![image](https://github.com/google/site-kit-wp/assets/94359491/71ac940e-a92b-45ff-8231-385aaa8d395f)

![image](https://github.com/google/site-kit-wp/assets/94359491/a6af350d-3d94-4173-be38-959e99e261ca)

</details>

**Save Preferences - Marketing - (Personalization storage not granted)**

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/48f2d7c7-defa-4f72-af63-4815ed3c0536)

![image](https://github.com/google/site-kit-wp/assets/94359491/fdd475bb-c94d-4f4c-8fbc-18362cfd9479)

![image](https://github.com/google/site-kit-wp/assets/94359491/b4089751-c7a9-429b-bc3b-961eec2fac68)

</details>
