### ISSUE TITLE
Replace 00% with a single digit 0% on the All traffic widget

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#8416]
## Bug Description

For sites that connect Analytics that have no data over the selected reporting period, they may encounter a `00% compared to the previous x days` message. 

Replace the double character 00 reference with a single digit, 0. 

## Screenshots

![image](https://github.com/google/site-kit-wp/assets/41326532/961a5975-2124-4ed6-b255-d6b42a0ef8b2)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The change percentage for the All Traffic widget should only show `0%` for a no-change (this is currently formatted correctly but due to bug the change is being output as well appearing as a double zero)

## Implementation Brief

* [ ] Merge https://github.com/google/site-kit-wp/pull/8653

### Test Coverage

* No changes expected (at most VRT may need updating if we have this case captured)

## QA Brief

* Using a site with Site Kit and Analytics connected, set the reference date in the JS console to a date in the future so there's no data: `googlesitekit.data.dispatch( 'core/user' ).setReferenceDate( '2027-01-28' )`
* The text under "All Visitors" should be `0% compared to the previous 28 days`, not `00% compared to the previous 28 days`

## Changelog entry

* Fix bug that caused "00%" to appear instead of "0%" when there was no change in data in Analytics widget.

**Comment by tofumatt** [comment]
IB ✅ and I'll move this right to CR.

**Comment by mohitwp** [comment]
###QA Update ✅ 

- Tested on dev environment.
- Verified that issue is reproducible on latest environment.
- Verified that issue is resolve now and the change percentage for the All Traffic widget  only show 0% .
- Tested for different dates also.

<details>


Latest environment:

![image](https://github.com/google/site-kit-wp/assets/94359491/8e54b576-9de9-4f47-9aa2-a214b4e3bb98)

Development environment:

![image](https://github.com/google/site-kit-wp/assets/94359491/abe18fc3-e4bd-4481-b851-5a459eed4811)

![image](https://github.com/google/site-kit-wp/assets/94359491/41e9dcf7-6e25-49f3-aaea-6f6f23de9c5e)

</details>
