### ISSUE TITLE
Consent Mode defaults not applying regionally

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8444]
## Bug Description

The `region` property of the Consent Mode defaults is named incorrectly as `regions`.

Additionally, the list of regions is incorrect - it includes `UK` where should be `GB`, and also includes `CH` (Switzerland), which Google's EU consent mode policy doesn't apply to.

## Steps to reproduce

1. Setup Site Kit and enable Consent Mode.
2. Navigate to a public page and view the source.
3. Locate the Consent Mode snippet and see the incorrect "regions" property as described above.

## Screenshots

![image](https://github.com/google/site-kit-wp/assets/18395600/4f14e741-2f5e-4366-a9a9-7e9b641ab3d1)

## Additional Context

 - PHP Version: any
 - OS: any
 - Browser: any
 - Plugin Version: 1.123.0
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `region` property of the Consent Mode defaults should be named correctly as `region`
* The list of regions should be updated with the following changes
	* Remove `UK` and `CH`
	* Add `GB`

## Implementation Brief

* [ ] Merge the fix in this PR: https://github.com/google/site-kit-wp/pull/8441

### Test Coverage

* Fix relevant tests (included in PR above).

## QA Brief

* Run through the steps to reproduce and verify the `region` property is set correctly.
* Perform some additional smoke testing of the Consent Mode feature to verify it's working as expected for the defined list of regions.

**Observable behavior in GA / Tag Assistant**

Location specific testing can use a VPN to mimic the behavior.

- With CoMo enabled and no banner enabled
	- Visit the site from a non EEA/UK country – you should see the traffic (consent would be unset)
	- Visit the site from an EEA/UK country – you should not see the traffic (consent should be `denied`)

The changes in this issue (and the bug) are related to the default consent, so no testing with CMP/banners is necessary.

## Changelog entry

* Fix a bug in the regional configuration of Consent Mode which caused defaults to be applied globally.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:** 

- The region property of the Consent Mode defaults should be named correctly as `region`
  - The list of regions are updated with the following changes: Remove `UK` and `CH`, Add `GB`

- With CoMo `enabled` and no banner enabled
  - Visit the site from a non EEA/UK country – I see the traffic
  - Visit the site from an EEA/UK country – I do not see the traffic

I ran through some additional tests:

- With CoMo `disabled`:
  - Visit the site from any country (including a non-EEA/UK country), and I see traffic. 

- With CoMo `enabled` but the Consent API plugin `not installed or activated`.  
  - Visit the site from a non EEA/UK country – I see the traffic
  - Visit the site from an EEA/UK country – I do not see the traffic

![image](https://github.com/google/site-kit-wp/assets/73545194/5f4957b0-5bf5-40a9-922c-9cb92702526e)
![image](https://github.com/google/site-kit-wp/assets/73545194/b5f75a4e-3cb6-41c9-9487-6014d409bfb1)

@mohitwp, please review the AC/QAB and confirm that you agree with my findings above. It's best to clear your cookies between the tests. I tested with a logged in and iogged out.

**Comment by mohitwp** [comment]
### QA Update ✅ 

cc @wpdarren @aaemnnosttv 
It look more time for me to test than I thought because VPN was behaving differently so I tested on multiple VPN's to rule out any issue.

- Tested on main environment.
- Verified all scenarios mentioned under QAB and AC.
- Tested using VPN for different locations.
- **Note** : I noticed that when CoMo enabled without banner/plugin then also some times EEA/UK showing under country listing. But when I checked page view counts it is not increasing. Although, i cleared session and local storage and also cleared cache but analytics shows UK/EEA country under the list. It happens only when I switch from Non EEA country to EEA/UK so this is due to cache and in real time scenario it will work fine. 
- Verified for non EEA countries like US, Japan, Singapore, Australia, India, Russia, Korea.
- Verified for EEA countries like Iceland, Finland, France, Netherlands, Austria,
- Verified regions updated to region.
- Verified GB added , UK and CH removed.


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/50c23b2d-7c0a-4ef3-bd99-5c0938876623)


**CoMo Enabled EEA/ UK country -**

![image](https://github.com/google/site-kit-wp/assets/94359491/dbd6b918-a733-4ed9-b326-07dfb5ffb495)


![image](https://github.com/google/site-kit-wp/assets/94359491/b79e6876-c517-4765-a26f-14d664f97f8a)



**When CoMo is disabled-** 
Tracking all countries including UK and EEA countries

![image](https://github.com/google/site-kit-wp/assets/94359491/9e9fedb1-ce14-45d2-9e86-b994c13f44e2)

![image](https://github.com/google/site-kit-wp/assets/94359491/0dc6b4c5-5934-46e2-bbb2-565c3364f1ec)

![image](https://github.com/google/site-kit-wp/assets/94359491/b769b5a6-1c9b-4b85-8339-a7239bed1906)

![image](https://github.com/google/site-kit-wp/assets/94359491/422d5b13-44cc-48bf-b12d-03cfa6434ce8)


</details>
