### ISSUE TITLE
Create a Custom Stylesheet for Authorize Application Screen Enhancement

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#8503]
## Feature Description

Within the Site Kit codebase, a custom SCSS stylesheet that explicitly targets improving the Authorize Application screen for users with Site Kit activated should be created. This stylesheet will incorporate design elements from Figma to improve the screen's usability and visual appeal.

[Figma Design](https://www.figma.com/file/ntKPstnmguKI70A6xUJQVi/Genesis?type=design&node-id=1-3304&mode=design&t=D8of1w8H4pmBsdvC-4)

For more information, refer to the [Stylesheet Creation](https://docs.google.com/document/d/1AXgDbfk8oMINl3fQZV41rp1r4krA1545MFfLAY7Yt1o/edit?resourcekey=0-yBMc-IpM33SZiT1GIMvgTQ#heading=h.p3iuyb52xiu0) section in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* **SCSS Stylesheet Creation**: A new SCSS stylesheet named `_googlesitekit-authorize-application.scss` must be created and appropriately stored within a `sass/authorize-application` directory newly set up in the Site Kit codebase.
* **Primary Stylesheet Setup**: Another SCSS file named `authorize-application.scss` must be created within the `sass` directory. This file should:
    * Import the `_googlesitekit-authorize-application.scss` stylesheet, ensuring all custom styles are centralized.
* **Webpack Configuration**: The `authorize-application.scss` stylesheet must be added to the Webpack Admin CSS configuration entry to ensure it is compiled and loaded correctly in the admin environment.
* **Note**: The actual enqueueing of this newly created stylesheet will be handled in #8504, focusing on conditional loading within the WordPress admin.

#### Create SCSS Files:

* [x] Set up a new directory, `authorize-application`, within the `sass` directory to organize and manage stylesheets related to the Authorize Application screen enhancements.
* [x] Create a new SCSS file named `_googlesitekit-authorize-application.scss` that will contain all the custom styles specifically for the Authorize Application screen. This file should be stored in a newly created directory at `sass/authorize-application`:
    * [x] Target `.auth-app-card #approve` to apply a `background-color` of `#0B57D0`. This specific style will assist QA in visually confirming the stylesheet's application once it is enqueued by #8504.
* [x] Create a new SCSS file named `authorize-application.scss` in the `sass` directory:
    * [x] This file should import the `_googlesitekit-authorize-application.scss` stylesheet and `config/variables`.

#### Webpack Configuration:

* [x] Modify the `adminCss.config.js` configuration file to include the new `authorize-application.scss` as part of the Admin CSS bundle.

### Test Coverage

* No test coverage is required for this change.

## QA Brief

* No QA steps are required for this change as it is a stylesheet creation task.
* It will be verified in #8504, which will handle conditionally enqueuing the stylesheet in the WordPress admin.

## Changelog entry

* Add stylesheet for Authorize Application screen.

**Comment by hussain-t** [comment]
I've added the AC and IB and have moved directly to IBR.

**Comment by techanvil** [comment]
Hi @hussain-t, as [mentioned on the design doc](https://docs.google.com/document/d/1AXgDbfk8oMINl3fQZV41rp1r4krA1545MFfLAY7Yt1o/edit?resourcekey=0-yBMc-IpM33SZiT1GIMvgTQ&disco=AAABKguwN60), it's a bit confusing to refer to the "Application Passwords" screen, as in fact the screen we are updating is the "Authorize Application" screen.

Please can you amend this issue to refer to the "Authorize Application" screen instead?

When it comes to the filenames, I'll leave that with you to decide whether the top-level file/directory names should be `application-passwords`, but I would say that based on how it's described in the AC, `_googlesitekit-application-passwords.scss` should be renamed to `_googlesitekit-authorize-application.scss`.

Personally I think it would probably make more sense to rename `application-passwords` to `authorize-application` across the board, because I don't think there's any scope to actually amend the actual Application Passwords UI, which is a subsection of a user's Profile screen:

![image](https://github.com/google/site-kit-wp/assets/18395600/86ff8bac-e4e9-47dd-bcda-e19074ca5293)

OTOH, _if_ we're keeping the epic name "Application Passwords" there's an argument these top-level names could remain `application-passwords`. Please take a look, and see what you think.

**Comment by hussain-t** [comment]
Thanks for bringing this up, @techanvil. "Authorize Application" sounds good to me. I've updated the AC and IB accordingly.

**Comment by techanvil** [comment]
The IB LGTM, nice one @hussain-t!

We'll no doubt want to create a SCSS variable for the `#0B57D0` colour, but this can be taken care of at implementation time.

IB :white_check_mark:

**Comment by techanvil** [comment]
@hussain-t I'd imagine we'll want to do it as part of this issue if we're actually introducing the new colour here. It should be pretty evident when it comes to implementation time, either way :)

**Comment by hussain-t** [comment]
Thanks, @techanvil. SGTM 👍
