### ISSUE TITLE
Module settings can be saved with invalid values

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8508]
## Bug Description

In #7533 we changed the way settings are handled when edited in an effort to provide a better experience for situations when the settings hadn't changed which is the default state.

The changes implemented however introduced a bug by allowing for settings to be saved with invalid inputs. This is likely because settings that haven't been changed was a condition that prevented saving.

## Steps to reproduce

1. Edit a connected module's settings
2. Change a setting to be invalid
3. See submit button is not disabled
4. Settings can be submitted and invalid values are saved

## Screenshots

**Settings shows input is invalid, while allowing saving**
<img width="756" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/1b584f6c-8bfc-40e4-a44f-83f6e3319eb2">

**Shows invalid input is saved**
<img width="269" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/383f1b34-760c-4188-8548-7ee8e17ece41">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Module settings should have the button to save changes disabled while the input for any of its settings is invalid
* Settings which have not changed should not be considered invalid, so long as the saved values are valid
* The AC for #7533 should be respected regarding the text and related conditions for module settings submit buttons

## Implementation Brief

* [x] Undo [this change to the `disabled` prop condition](https://github.com/google/site-kit-wp/pull/7700/files#diff-35a209af9b8af36a7078eba599222127fa6ef4c9bdaa8b38b5dfecfdd685a2ceL184) to the setting's `SpinnerButton` (restoring `! canSubmitChanges` and keeping `isLoading`)
* [x] Update `validateCanSubmitChanges` to remove `haveSettingsChanged` as criteria for validity (this is implemented per-module)
* [x] Review module setup components to ensure setup cannot be completed when it shouldn't due to change in `canSubmitChanges` logic 

### Test Coverage

* Update tests for `validateCanSubmitChanges` and `makeDefaultCanSubmitChanges`
* Potentially other updates related to above module setup changes, but not expected

## QA Brief

* Firstly, with the `adsModule` flag **disabled**:
   * Reset and reconnect the Analytics module, confirm that modules settings text fields cannot be saved with invalid values.
    * Save a valid value, then return to the edit page, when the value matches the previously saved value, the CTA button copy should be Save and should be active as specified in the AC of #7533
 * Enable the `adsModule` flag
    * Connect the Ads module, confirm that the module setup and settings cannot be saved with invalid values. 
    * Save a valid value, then return to the edit page, when the value matches the previously saved value, the CTA button copy should be Save and should be active as specified in the AC of #7533
   * Reset and reconnect the Analytics module, confirm that modules settings text fields cannot be saved with invalid values.
    * Save a valid value, then return to the edit page, when the value matches the previously saved value, the CTA button copy should be Save and should be active as specified in the AC of #7533
 * It's important to QA setting up and editing settings *on every module* as this change could prevent set up or editing of settings on any module if those modules validation functions are not updated correctly

## Changelog entry

* Ensure Ads module cannot be saved when settings are invalid.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by tofumatt** [comment]
(Assigning myself as @zutigrm [isn't able to work on this today](https://10up.slack.com/archives/CBKKQEBR9/p1713260034334389).)

**Comment by kelvinballoo** [comment]
### QA Update :x:

Tested on WP 6.5.2 PHP 8.0 and in terms of validation, we are fine overall.
Whenever we have invalid characters, the 'Confirm changes' button is disabled.
<Details>
<img width="498" alt="Screenshot 2024-04-17 at 19 09 20" src="https://github.com/google/site-kit-wp/assets/125576926/54d8a1cc-c152-4ad5-8872-5f1c78cbc720">
</details>

That said, I noticed a few behaviours that I'd like to raise to confirm that all is good:

**ISSUE 1:**
Referencing the QA Brief from #7533 
```
Loading State Check:
Refresh the settings page or navigate away and then return.
The button should be disabled while the entire settings screen is loading
```
I can't find the save button being disabled, unlike Mohit's [recording from that issue](https://github.com/google/site-kit-wp/issues/7533#issuecomment-1784469221).
Here's my video recording: 
<Details>

https://github.com/google/site-kit-wp/assets/125576926/a3344729-b5f8-4691-b6e0-590684113379


</details>
__________________________________________________________________________

**ISSUE 2:**
Referencing the AC from #7533:
```
Changing Settings:
Modify any settings available on the page.
Observe the button text. It should update to "Apply changes".
```
So far we have not implemented the button text as 'Apply changes'. It's 'Confirm changes' instead. 
I believe the latter is the correct way anyway. 
But since it's deviating from the AC there, I just want to raise it to confirm what we have implemented is good.
<Details>
<img width="437" alt="Screenshot 2024-04-17 at 19 07 16" src="https://github.com/google/site-kit-wp/assets/125576926/b2af241c-aef0-4b30-b240-b34c7889ad5e">
</details>
__________________________________________________________________________

**ISSUE 3:**
This is more of a clarification.
I turned off ads module feature and save a conversion ID at the Analytics section.
I noticed that this conversion ID does not appear on the Ads module setup screen after I enable that feature.

A video is attached below but the question is: is that the correct behaviour or we should be porting over whatever was saved from the analytics module?
<Details>

https://github.com/google/site-kit-wp/assets/125576926/459b8c99-b6c2-4469-b9e5-fef41dde2d94


</details>

**Comment by benbowler** [comment]
Hey @kelvinballoo, 

Issue 1: Really great find here! This was a bug introduced by the SAM epic recently, the module name was not updated to `analytics-4` in `assets/js/components/settings/SettingsActiveModule/Footer.js` causing the bug you found. I've fixed this in the [PR here](https://github.com/google/site-kit-wp/pull/8576).

Issue 2: Yes, "Confirm changes" is the current copy choice for saving settings forms as can be seen in [the latest Ads modules designs](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?node-id=1183%3A7078&mode=dev) for example.

Issue 3: I've tagged you in a Slack conversation, to summarise here, this is expected behaviour as in the current implementation the field is only migrated *when you visit the Analytics settings edit page, not the Ads module setup flow.*

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks @benbowler .
Noted on item 2 and 3.

For item 1, I tested it again and the 'Save' button is now disabled when the screen is loading.
Tested this with ads module and off.
Also conducted an overall test that the invalid characters are still being blocked from being saved. 

All is working as expected. Moving ticket to 'Approval'

<Details>

https://github.com/google/site-kit-wp/assets/125576926/69d52738-5021-4f86-b485-6432cebb27a2


</details>
