### ISSUE TITLE
Address remaining reference to legacy `analytics` module slug

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8509]
## Bug Description

https://github.com/google/site-kit-wp/blob/f9a0480c5612f3a6c32e2703a5070792fa7351e9/assets/js/components/settings/SettingsActiveModule/Footer.js#L147-L169

The legacy `analytics` module slug is being referenced in the above component. This should be replaced with `analytics-4`.

See internal discussion [here](https://10up.slack.com/archives/CBKKQEBR9/p1712684918723259).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jimmymadon** [comment]
This issue has been fixed in this [PR](https://github.com/google/site-kit-wp/pull/8576) as part of a QA failure to this [issue](https://github.com/google/site-kit-wp/issues/8508). The code in question here can be refactored based on @aaemnnosttv's comments in this [Slack conversation](https://10up.slack.com/archives/CBKKQEBR9/p1712684918723259). Have created a new issue for this - https://github.com/google/site-kit-wp/issues/8730.
