### ISSUE TITLE
No check for Ads Conversion ID added via GTM

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#8513]
## Feature Description

As reported by @jamesozzie in [Ads Module Bug Bash](https://app.asana.com/0/1206715995671666/1207038519437769/f):

![image](https://github.com/google/site-kit-wp/assets/12189958/955f0899-b9da-4499-a9e8-25fa8425f4cf)

If following the steps to add Ads Conversion tracking via GTM, it's possible to have both a SK inserted tacking ID and a GTM added tracking tag for a site. 

Tested via adding an Ads Conversion Tracking ID manually, on a site that already has the Ads module successfully connected. 

If feasible, add a notice within the Ads module, to mention that an existing tag was found - similar to how we do it for GA. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jimmymadon** [comment]
@jamesozzie (Although the questions below are mainly for @aaemnnosttv )

>If feasible, add a notice within the Ads module, to mention that an existing tag was found - similar to how we do it for GA. 

As mentioned in this (long) [comment](https://github.com/google/site-kit-wp/issues/7989#issuecomment-1915654586), since we moved to GA4, we no longer warn the user when a GTM container contains a "Google Tag (Measurement ID)" that points to the same Web Datastream selected within Google Analytics within the plugin. This functionality was removed from the plugin when we moved from UA to GA4 because:
1. Having 2 duplicated tags inserted on a site do not duplicate the data / events in GA4.
2. Fetching the web datastream connected to a Google Tag is not straightforward based on the current Analytics API. 

Question 1: Are we sure that having the Ads Conversion ID inserted twice onto the site, via GTM and via Ads does not have any unfortunate side effects? 

The only "GTM-GA4" integration we do now is that when GA4 is not connected in the plugin, and if the user connects Tag Manager and selects a GTM container whose current live version has "any valid" Google Tag ID, then we show a message.
This message simply encourages the user to set up GA4 within Site Kit.

<img width="1299" alt="Screenshot 2024-05-22 at 00 30 30" src="https://github.com/google/site-kit-wp/assets/1721319/365c0709-2b2e-4bf8-a483-6c93c0fd6ee5">

Question 2: Do we want to encourage the user to "set up Ads" like above if we do find an Ads Conversion ID in the currently selected GTM container?

**Comment by jimmymadon** [comment]
Sure - @tofumatt and @eugene-manuilov can guide us here too.

**Comment by eclarke1** [comment]
This is the last issue in the Ads Module epic, do we feel this is still needed? If so, can we move it through so we can get the epic closed out please

**Comment by eugene-manuilov** [comment]
> Question 1: Are we sure that having the Ads Conversion ID inserted twice onto the site, via GTM and via Ads does not have any unfortunate side effects?

I think the only way to answer this question is to try it and see whether we get duplicate events tracked when we have conversion tracking enabled via GTM and via Ads. @jamesozzie,  can you try it using your setup?

> Question 2: Do we want to encourage the user to "set up Ads" like above if we do find an Ads Conversion ID in the currently selected GTM container?

@aaemnnosttv, what do you think? I think this question is for you.

**Comment by jimmymadon** [comment]
>Question 2: Do we want to encourage the user to "set up Ads" like above if we do find an Ads Conversion ID in the currently selected GTM container?

On our AC sync yesterday, @aaemnnosttv decided not to at this stage since there is not much value in connecting Ads via just the conversion ID for now.

As for Question 1, @jamesozzie will have a look.

**Comment by binnieshah** [comment]
@jamesozzie please could you review this?

**Comment by jamesozzie** [comment]
@jimmymadon @binnieshah Just to confirm I don't see any double tracking applied or issues with double tracking. 

- [Screenshot of what I see without GTM active](https://i.imgur.com/8Q2VekU.png) (but with conversion tracking enabled via Ads)
- [Screenshot of what I see with GTM active - GTM tab](https://i.imgur.com/lai568o.png) | [GA tab](https://i.imgur.com/6ix9HX4.png)

In these tests I ensured all users are included in reporting within SK. I didn't in this case check various events. Happy to do so if you let me know of any specific events you'd like me to check @eugene-manuilov

**Comment by eugene-manuilov** [comment]
Thanks, @jamesozzie. So, looks like here is nothing to do for us. Going to close this ticket.

**Comment by jamesozzie** [comment]
Sounds good @eugene-manuilov. 

Note that I didn't check any click through from Google Ads directing me to a test website, I don't have Google Ads running for ads sites. Landing on a test website using Site Kit, with a Ads tag placed by both Site Kit and by GTM could potentially result in skewed data, I'm not sure. My tests were basic events, internal and external page clicks. Happy to test further, while I'll also add for discussion in our sync with @aaemnnosttv
