### ISSUE TITLE
Add Main `Conversion_Tracking` Class

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8528]
## Feature Description

Add main `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Tracking` class. See [implementation and class design](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.xbfrer8wvn3z) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Add new class `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Tracking`
* It should define following methods:
  * `get_active_conversion_event_providers` - Retrieves the list of active conversion event providers
  * `register` - Registers scripts of each active provider and sends events to the `googlesitekit_conversion_provider_events` action.

## Implementation Brief

* [x] In `includes/Core/Conversion_Tracking`, create a new class called `Conversion_Tracking`:
  * [x] Add a public static property, `conversion_event_providers` that holds an array map of plugin slug names as keys and their classnames (along with their namespace) as values.
  * [x] Create a public method called `get_active_conversion_event_providers()`:
    * [x] Iterate over the `conversion_event_providers` property. 
    * [x] Instantiate an object of every class in the array map.
    * [x] Call the `is_active` method on every object.
    * [x] If true, add the object reference to an array.
    * [x] Return this array.
  * [x] Create a public method called `register()`:
    * [x] Call the new `get_active_conversion_event_providers()` method and store the list of `active_conversion_event_providers` in an array.
    * [x] Iterating through each of `active_conversion_event_providers` references, call the `register_script()` method on them.
  * [x] In `includes/Plugin.php`, instantiate this new class and call the new `register` method above.

### Test Coverage

* [x] Add PHPUnit tests for the two above methods using mock objects that implement the `Conversion_Events_Provider` interface. 

#### QA:Eng

* Verify php tests are passing
* Ensure no other area is affected

## Changelog entry

* Add the main `Conversion_Tracking` class.

**Comment by eugene-manuilov** [comment]
Thanks, @zutigrm. AC looks okay in general, but there are too many technical details. Better to write acceptance criteria that explain the state of the final result that we want to achieve and let IB writer to define how it should be done. Here are some suggestions:

* Instead of telling that we need to add a new class, better to say that a new class is created with the specific name and in the specific namespace.
* No need to mention which properties the new class should have.
  * I know you defined it in your design doc, but that is not necessarily must be like that. If that property is used just in one method, than there might be not enough sense to keep it as a property and we can just define it as. So, what i am trying to say - we can leave it to IB writer to decide where that information should be held.
* No need to say which steps should be implemented in each method exactly because it looks like IB itself. Just tell what each method does. For example:
  * `get_active_conversion_event_providers` returns a list of active providers.
  * `register` registers scripts of each active provider and sends events to the `googlesitekit_conversion_provider_events` action.
  
I know you may argue that we have a lot of ACs like yours and you will be right, but we discussed it with Tom and Mathew in the past that we should write more agnostic ACs that just define the resulting state of something that we want to achieve in the ticket instead of having technical details of how it should be done.

**Comment by zutigrm** [comment]
@eugene-manuilov Thanks for the feedback. Points taken, I do agree with your suggestion it makes more sense. Since I was seeing a bit technical AC's I though maybe I should have more details as well.

AC updated

**Comment by eugene-manuilov** [comment]
Thanks. AC ✔️

**Comment by tofumatt** [comment]
IB ✅

**Comment by eugene-manuilov** [comment]
No QA is needed here since it has been verify during code review. Moving to the Approval column directly.
