### ISSUE TITLE
Do PHP profiling in preparation of conditional loading and initialization improvements

### ISSUE THREAD

**Issue by ThierryA** [google/site-kit-wp#853]
## Bug Description

We are currently loading and initiating a lot of PHP and JS pretty much unconditionally. Not only we are loading assets unnecessarily in many cases, it also seems that we are making server side API calls on every page load in some cases, for instance if an access token is expired upon every payload. This can be very expensive and even potentially take some user websites down (reported by a few users) if for some reason these requests are constantly failing creating infinite loop.

To better understand what the plugin is doing and fix unconditional loading + avoiding infinite loop, we should start by doing basic PHP profiling.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Deliver a report with PHP profiling to better understand the plugin execution flow and detect potential performance leaks.

## Implementation Brief

Use [Blackfire](https://blackfire.io/) to profile the following page loads locally:

#### Establish baseline (without Site Kit installed) numbers

* Homepage (logged out)
* Homepage (logged in as admin)
* WP dashboard
* WP Edit post

#### Profile with Site Kit

Profile the above baseline cases with Site Kit active in the following states:
* Not set up
* Minimal (complete) set up, no extra modules
* Fully set up with all modules

**Additional cases**

* Site Kit dashboard (no modules)
* Site Kit dashboard (with all modules)
* Search Console module dashboard
* Analytics module dashboard
* AdSense module dashboard

#### Reporting

A report will be compiled with a summary of findings and links to profile data on Blackfire. Data retention on Blackfire varies by plan, but this data should be available for 30 days (Profiler and Premium [plans](https://blackfire.io/pricing), Enterprise offers 90).

## Changelog entry

*

**Comment by tofumatt** [comment]
Especially on the issue of taking down users' websites because of a large number of requests, or repeated requests, I think a solution to the issues of:

1. not having a good idea of which requests are running when/where/why
2. taxing the user's server to make requests to a Google API

is to revisit our use of the server/PHP/WordPress to make our requests to the Google APIs. The WordPress install already has all the credentials needed to make a request to the Google API, so instead of proxying all of our requests through to WordPress's REST API, we could send the relevant credentials down to the user in the JS Store/`googlesitekit` object and have them make the requests directly.

My understanding is that PHP was used because of an existing Google OAuth API library, but I've found what appear to be Google-made JS libraries ([Node](https://github.com/googleapis/google-api-nodejs-client) and [client-side JS](https://github.com/google/google-api-javascript-client) ones) we could use to simplify our request code to the Google API. The latter client even [supports batch requests](https://github.com/google/google-api-javascript-client/blob/master/docs/batch.md).

Given how much of the plugin is already in JS, this could simplify code paths for requests, make it easier to debug/control requests from the bulk of the plugin's code (in JS), and reduce strain on the WP server. Since many WordPress installs are on basic, shared hosting plans, the server becomes a performance bottleneck. Even during testing, the amount of requests that wait between `300ms-1200ms` to go through both WordPress and Google would be sped up.

**Comment by ThierryA** [comment]
Changing this as a tasks as it requires more discovery.

**Comment by ThierryA** [comment]
Follow up on this issue, I updated it to be specifically about PHP profiling before we jump into fixing things.

**Comment by ThierryA** [comment]
@tofumatt your comment makes perfects sense and I think we should definitely explore that in the future. However this is another step further of what this issue is about, right now we need a clearer understanding of our current application on every page load, profiling will considerable help us with that.

**Comment by ThierryA** [comment]
Thanks @aaemnnosttv. I think we should also profile:
- Setting page
- Reset
- Module Setup (I think these are pretty API Requests heavy and it might help us understand why it is throttling in some cases)

> A report will be compiled with a summary of findings and links to profile data on Blackfire. Data retention on Blackfire varies by plan, but this data should be available for 30 days (Profiler and Premium plans, Enterprise offers 90).

Let's see how we benefit from this profiling and we can looking into premium plans afterwards.

@felixarntz anything you would like to add here?

**Comment by aaemnnosttv** [comment]
> I think we should also profile:
> * Settings page
> * Reset
> * Module Setup (I think these are pretty API Requests heavy and it might help us understand why it is throttling in some cases)

Profiling a [scenario](https://blackfire.io/docs/cookbooks/profiling-http-via-browser#profiling-all-requests-level-profiler-premium-enterprise) rather than a page load is likely going to be a bit more complicated and may be worth handling as a separate task as this will increase the size of this one a good deal I think.

For reset in particular, do you think we should test this with a large number of users as well since this has been a problem in the past? What about other environmental factors such as persistent object caching?

**Comment by ThierryA** [comment]
> Profiling a scenario rather than a page load is likely going to be a bit more complicated and may be worth handling as a separate task as this will increase the size of this one a good deal I think.

Sounds good, let's start with the current list and we can look into expending the scope in a separate tasks.

> For reset in particular, do you think we should test this with a large number of users as well since this has been a problem in the past? What about other environmental factors such as persistent object caching?

Specifically curious to see how profiling would help us understand the previous issue. Same as above, we could treat that as a separate task.

**Comment by felixarntz** [comment]
IB ✅

**Comment by ThierryA** [comment]
Removing this issue from the Execution board as we have addressed most performance issues via other tickets. Setting up profiling would be good to revisit at some point.

**Comment by aaemnnosttv** [comment]
Closing in favor of [internal task](https://app.asana.com/0/1185360131189553/1207292676736420/f).
