### ISSUE TITLE
Add plugin integration for WooCommerce

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8553]
## Feature Description

WooCommerce conversion events should be supported in the new conversion event tracking infrastructure.

See [implementation and class design](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.xbfrer8wvn3z) and [plugin specific notes](https://docs.google.com/document/d/1EgwYHDuGLS0VpMov042T_WJaYLZhID3IczIgpw5_0xI/edit#heading=h.pkhe2y37uvhr) section in the design doc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Conversion events from WooCommerce should be tracked and supported by our infrastructure.
* When product is added to the cart, `add_to_cart` conversion event should be tracked.
* When checkout process is completed `purchase` conversion event should be sent

## Implementation Brief

* [x] Add `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Event_Providers\WooCommerce`
  * It should implement `Google\Site_Kit\Core\Conversion_Tracking\Conversion_Events_Provider` interface.
  * Define class property `conversion_provider_slug` with a value, say `woocommerce`
  * It should have following methods:
    * `is_active` - check if `WC_PLUGIN_FILE` constant is defined
      * return `true` if it is
      * otherwise return `false`
    * `get_event_names` - return an associative array contain two values `add_to_cart` and `purchase`
    * `register_script` - Instantiate the `Google\Site_Kit\Core\Assets\Script` class and register the script, leveraging the execution argument for deferring the script. It should return the Script instance.
      * You can see an example of instantiating the `Script` class here https://github.com/google/site-kit-wp/blob/fd7efe4ecb395daf261ecb30547c48688bafe6ed/includes/Core/Assets/Assets.php#L441-L449
      * Use `woocommerce` script as dependency
      * Include `'execution' => 'defer'`
      * For handle name use `gsk-cep-{$this->conversion_provider_slug}`
      * return the `Script` instance 
* [x] Add `assets/js/event-providers/woocommerce.js`
  * Include the WooCommerce specific event listeners that will trigger the event once document is loaded. Events are handled with jQuery so `.on()` listener should be used, examples:
```js
$( 'body' ).on( 'added_to_cart', function() {
   gtag( 'event', 'add_to_cart' );
} );
$( 'body' ).on( 'checkout_place_order_success', function() {
   gtag( 'event', 'purchase' );
} );
```
* [x] Include JS file path in the `conversionEventProviders.config.js` webpack partial added in #8531
* [x] Ensure `yield conversionEventProviders( mode );` is run in the main `webpack.config.js` config (it is commented out while there are no entry points)
* [x] Include the plugin name and class path to the array of main `Conversion_Events` class property added in #8528

### Test Coverage

* You can add basic test coverage for `WooCommerce` class, testing that `get_event_names method `returns correct event names, and `register_script` returns script instance with proper handle. Also `is_active` can be confirmed by defining the plugin constant

## QA Brief

* Install an extension for your browser that lets you track Analytics events
* Enable the `conversionInfra` feature flag for your site
* Install and activate a theme that uses the standard woocommerce scripts on the frontend.
* Install and activate the woocommerce plugin
* Create a new product and go to the shop page.
* Add that product to the cart and ensure that the appropriate event is tracked
* Go to the cart and do checkout. Verify that the appropriate event is tracked as well.

## Changelog entry

* Add support for Analytics events when WooCommerce is connected.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by benbowler** [comment]
Thanks @zutigrm I didn't get as much time as I hoped to work on this ticket today so have un-assigned while I'm out for others to work on.

**Comment by eugene-manuilov** [comment]
IB :heavy_check_mark:

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment.
- Verified when `conversionInfra` feature flag is not enabled.
- Also, verified when  `conversionInfra` feature flag is enabled.
- Tested after installing WooCommerce with Astra theme.
- Tested event tracking for both 'add to card' and 'checkout' activity.


@eugene-manuilov In my test `add_to_cart`  and `purchase` conversion events are not getting track. I'm getting similar response as I'm getting when `conversionInfra` feature flag is not enabled.

<details>


https://github.com/google/site-kit-wp/assets/94359491/4915bc36-4760-4dec-a7e8-2d29d7d93fee

</details>

**Comment by eugene-manuilov** [comment]
@mohitwp, unfortunately, there must be a perfect theme to get it working correctly. The Astra theme doesn't use the `.checkout` class for its checkout form, hence Woocommerce can't track its submission and doesn't know when to trigger its event.

Regarding adding products to the cart, it will work from the shop page since adding products there works using expected markup that is compatible with Woocommerce js. On the single product page, it won't work because it doesn't use js to process when the user clicks on the add to cart button.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

Thanks @eugene-manuilov 

- I tested this on 3 free themes listed on [WooCommerce site ](https://woocommerce.com/product-category/themes/?categoryIds=1600&collections=theme&page=1) Deli, Storefront and Boutique. 
- I added product from shop page as well as from Individual product page.
- In my test `add_to_cart `and `purchase` conversion events are not getting track on alll above 3 themes. I'm getting similar response as I'm getting when conversionInfra feature flag is not enabled. 
- I'm thinking that above 3 themes must be perfect because all are listed on WooCommerce site. 
- Can you please check if these themes are suitable or not for our test ? Also, can you please share if you know any theme on which listed events are getting track.
cc @wpdarren 




<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/6b14234f-8d5d-4992-bb6b-c70111b22437)


https://github.com/google/site-kit-wp/assets/94359491/9b5cd979-f44a-42e8-9ffe-04616f056eec

https://github.com/google/site-kit-wp/assets/94359491/471dc2a1-cc88-4098-9a34-ec4aae119dca

https://github.com/google/site-kit-wp/assets/94359491/80ef1b14-46ee-4ede-b295-94ffbab5399e


</details>

**Comment by mohitwp** [comment]
### QA Update ❌ 

- Tested on dev environment plugin zip file provided by Eugene.
- Verified when `conversionInfra` feature flag is disabled.
- Verified when `conversionInfra` feature flag is enabled.
- Verified when Analytics is connected.
- Verified when both Analytics and ads module are connected.
- Verified when only Ads module is connected.
- Verified when both Analytics and ads module are disconnected but `conversionInfra`  feature flag is enabled.
- Theme - Storefront


@eugene-manuilov For me `'add_to_cart ` event is getting track when I add product into cart from shopping page. But, `purchase` event is not getting track when I complete checkout process. I tested using cash on delivery, stripe credit card and cheque payment options but `'purchase' `event is not getting track.

<details>

**`add to cart` event**

![image](https://github.com/google/site-kit-wp/assets/94359491/ee0e7435-9fc5-4c2d-8ad9-b8b6d9f0f9f2)


**_When `conversionInfra` feature flag is enabled and Ads module is connected._**


https://github.com/google/site-kit-wp/assets/94359491/a73dc834-35aa-43a9-b021-91afd5e7b699


**_When `conversionInfra` feature flag is enabled. Both Analytics and Ads modules are connected._**


https://github.com/google/site-kit-wp/assets/94359491/0edc0fa4-0d93-4921-85c0-51f79236afd0

</details>

**Comment by eugene-manuilov** [comment]
@aaemnnosttv do you mind looking into it?

**Comment by aaemnnosttv** [comment]
Let's leave this for now. We can address it in a follow-up to improve the accuracy. Until then it's behind a feature flag.
