### ISSUE TITLE
Extend Ads settings for PAX

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8562]
## Feature Description

The addition of PAX will require some additional settings such as a separate field for a new conversion tracking ID and the customer/account ID.

Additional settings could be required based on discovery during implementation.

See the [Ads module settings](https://docs.google.com/document/d/1H6iTwTto2hfHwo8TFDsrC90jxH_xtI1Bi7gr0IjYQNI/edit?resourcekey=0-CcuNz7rOBEk7drqrpHsF1g) section of design document for more info.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Ads module (in applicable PHP and JS areas of the code base) should support for the following 2 settings field within the Ads module:
    * `paxConversionID` (a string, can default to empty string)
    * `extCustomerID` (a string, can default to empty string)
* Appropriate actions and selectors should be available within the Ads datastore so these settings values can be created, updated and retrieved.

## Implementation Brief

* [x] Update the file at `includes/Modules/Ads/Settings.php`
    * [x] Add the two new settings fields to the array returned by the `get_default()` method and set the default values to am empty string `''`:
    ```
    		return array(
			'conversionID'    => '',
			'paxConversionID' => '',
			'extCustomerID'   => '',
		);
    ```
    * [x] Add the two new settings fields to the array returned by the `get_owned_keys()` method:
    ```
    		return array(
			'conversionID',
			'paxConversionID',
			'extCustomerID',
		);
    ```
* [x] Update the settings test suite at `tests/phpunit/integration/Modules/Ads/SettingsTest.php`
    * [x] Add the newly added settings to the array of settings within the existing `test_get_default` test 
* [x] Update the file at `assets/js/modules/ads/datastore/base.js`
    * [x] Add the two new settings fields slugs to the `ownedSettingsSlugs` property of the store:
    ```
    ownedSettingsSlugs: [ 'conversionID', 'paxConversionID', 'extCustomerID' ],
    ```
    * [x] Add the two new settings fields slugs to the `settingSlugs` property of the store:
    ```
    	settingSlugs: [
		'conversionID',
		'ownerID',
		'paxConversionID',
		'extCustomerID',
	],
    ```
* [x] Update the file at `assets/js/modules/ads/utils/validation.js`
    * [x] Add two validation methods for the 2x new added fields
        * [x] `isValidPaxConversionID` should contain the same validation pattern as `isValidConversionID`
        * [x] `isValidExtCustomerID` should validate that the value is a string
* [x] Validate that the settings values of the two new settings fields can be successfully set and retrieved from the ads module store, example console check:
```
// Should have successful promise resolution.
googlesitekit.data.dispatch( 'modules/ads' ).setPaxConversionID('AW-98765');

// Should return 'AW-98765'
googlesitekit.data.select( 'modules/ads' ).getPaxConversionID();

// Should have successful promise resolution.
googlesitekit.data.dispatch( 'modules/ads' ).setExtCustomerID('123456789');

// Should return '123456789'.
googlesitekit.data.select( 'modules/ads' ).getExtCustomerID();
``` 

### Test Coverage
* Extend existing tests within the following files to cater for the 2x new settings:
    * `assets/js/modules/ads/utils/validation.test.js`
        * Add tests that assert the correct behaviour of the validation functions added in `assets/js/modules/ads/utils/validation.js`

* 

## QA Brief

* Setup and connect the `Ads` module
* Navigate to Site Kit > Settings
* Open the browser console
* Set values for the two new settings fields using the following console snippet:
```
// Set PAX Conversion ID.
googlesitekit.data.dispatch( 'modules/ads' ).setPaxConversionID('AW-00000');

// Set PAX Ext Customer ID.
googlesitekit.data.dispatch( 'modules/ads' ).setExtCustomerID('A-1111111');
```
* Validate that the same values are returned when getting the values using the following console snippet:
```
// Should return 'AW-00000'.
googlesitekit.data.select( 'modules/ads' ).getPaxConversionID();

// Should return 'A-1111111'.
googlesitekit.data.select( 'modules/ads' ).getExtCustomerID();
```
* Apply the changes so that they are persisted in the database using the following console snippet:
```
googlesitekit.data.dispatch( 'modules/ads' ).submitChanges();
```
* Reload the page
* Fetch the values in console again and validate that they have been persisted using the following console snippet:
```
// Should return 'AW-00000'.
googlesitekit.data.select( 'modules/ads' ).getPaxConversionID();

// Should return 'A-1111111'.
googlesitekit.data.select( 'modules/ads' ).getExtCustomerID();
```

## Changelog entry

* Add Ads settings for PAX.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by 10upsimon** [comment]
@aaemnnosttv (cc @tofumatt ) noting that during EX I noticed that we had missed the requirement of updating the existing settings suite at `tests/phpunit/integration/Modules/Ads/SettingsTest.php`. I added this to the EB and executed on it during execution. TY.

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@10upsimon For the last Case 4 : After reload for first request in console I get "undefined". For the second request persisted value appears. Is this expected ?

![image](https://github.com/google/site-kit-wp/assets/94359491/f5477f43-2830-4858-a5ac-5e07fe55d12b)




- Tested on dev environment.
- Verified all scenarios mentioned under QAB with the help of snippet.


<details>


 **_Case 1: Set values for the two new settings fields using the console snippet:_**

![image](https://github.com/google/site-kit-wp/assets/94359491/bd96143e-0f2b-4b40-a9e6-81d7d9d94bb7)

![image](https://github.com/google/site-kit-wp/assets/94359491/75376f0d-821c-4170-b9f5-a23d1c4e6f8c)

**_Case 2: Validate that the same values are returned when getting the values using the  console snippet:_**

![image](https://github.com/google/site-kit-wp/assets/94359491/8318322b-571f-4387-ba0d-4ec7867ec6a2)

![image](https://github.com/google/site-kit-wp/assets/94359491/175f9b5a-826f-4edf-b5f0-13076670d0c0)


**_Case 3: Apply the changes so that they are persisted in the database using the console snippet:_**

![image](https://github.com/google/site-kit-wp/assets/94359491/63fb540b-dcbf-40ed-936f-3b3ab01e6b13)

**Case 4: Reload the page
Fetch the values in console again and validate that they have been persisted using the console snippet:**

![image](https://github.com/google/site-kit-wp/assets/94359491/43bf12ec-c256-43c2-b851-ebe1186dd57f)

**_With Different values_**

![image](https://github.com/google/site-kit-wp/assets/94359491/14ee6963-d7d6-47ec-b587-a962e9648f1b)

![image](https://github.com/google/site-kit-wp/assets/94359491/a76a25b5-7fed-4f79-8d47-0e67469e5a87)

**_Submit Changes:_**

![image](https://github.com/google/site-kit-wp/assets/94359491/88bb4e30-4f42-4aa1-966b-7b2373633f04)

**_After Reload:_**

![image](https://github.com/google/site-kit-wp/assets/94359491/5ca98064-261b-4d0d-b5bb-09dca67a4e4d)

</details>

**Comment by 10upsimon** [comment]
@mohitwp as discussed in Slack, the Ads settings pane has to be expanded during testing or the settings are not immediately available, hence they're only becoming available after the first request in your case, when the settings pane is not yet expanded.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified all scenarios mentioned under QAB with the help of snippet.

<details>


 **_Case 1: Set values for the two new settings fields using the console snippet:_**

![image](https://github.com/google/site-kit-wp/assets/94359491/bd96143e-0f2b-4b40-a9e6-81d7d9d94bb7)

![image](https://github.com/google/site-kit-wp/assets/94359491/75376f0d-821c-4170-b9f5-a23d1c4e6f8c)

**_Case 2: Validate that the same values are returned when getting the values using the  console snippe- Tested on dev environment.
- Verified all scenarios mentioned under QAB with the help of snippet.


<details>


 **_Case 1: Set values for the two new settings fields using the console snippet:_**

![image](https://github.com/google/site-kit-wp/assets/94359491/bd96143e-0f2b-4b40-a9e6-81d7d9d94bb7)

![image](https://github.com/google/site-kit-wp/assets/94359491/75376f0d-821c-4170-b9f5-a23d1c4e6f8c)

**_Case 2: Validate that the same values are returned when getting the values using the  console snippet:_**

![image](https://github.com/google/site-kit-wp/assets/94359491/8318322b-571f-4387-ba0d-4ec7867ec6a2)

![image](https://githubt:_**

![image](https://github.com/google/site-kit-wp/assets/94359491/8318322b-571f-4387-ba0d-4ec7867ec6a2)

![image](https://github.com/google/site-kit-wp/assets/94359491/175f9b5a-826f-4edf-b5f0-13076670d0c0)


**_Case 3: Apply the changes so that they are persisted in the database using the console snippet:_**

![image](https://github.com/google/site-kit-wp/assets/94359491/63fb540b-dcbf-40ed-936f-3b3ab01e6b13)

**Case 4: Reload the page
Fetch the values in console again and validate that they have been persisted using the console snippet:**

![image](https://github.com/google/site-kit-wp/assets/94359491/43bf12ec-c256-43c2-b851-ebe1186dd57f)

**_With Different values_**

![image](https://github.com/google/site-kit-wp/assets/94359491/14ee6963-d7d6-47ec-b587-a962e9648f1b)

![image](https://github.com/google/site-kit-wp/assets/94359491/a76a25b5-7fed-4f79-8d47-0e67469e5a87)

**_Submit Changes:_**

![image](https://github.com/google/site-kit-wp/assets/94359491/88bb4e30-4f42-4aa1-966b-7b2373633f04)

**_After Reload:_**

![image](https://github.com/google/site-kit-wp/assets/94359491/5ca98064-261b-4d0d-b5bb-09dca67a4e4d)

</details>
