### ISSUE TITLE
Extend Ads settings edit view for PAX

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8564]
## Feature Description

Once new settings are added (see #8562 ), the Ads module's settings edit view should be extended to display them as readonly values as most/all of these are not intended to be user-editable.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

**When the `adsPax` feature is enabled**

* The current Ads module's `<SettingsForm>` component should include read-only views of the settings obtained from the PAX app as part of #8562:
    * `paxConversionID`
        * Label to read "Conversion Tracking ID"
        * Value to be obtained using the applicable datastore selector
        * Show "None" when value is an empty string
    * `extCustomerID`
        * Label to read "Customer ID"
        * Value to be obtained using the applicable datastore selector
        * Show "None" when value is an empty string
    * The above two settings values are to render within the existing `<SettingsForm>` component of the Ads module, example below:
![Site Kit by Google Settings ‹ sitekit 10uplabs com — WordPress 2024-04-18 at 11 43 34 AM](https://github.com/google/site-kit-wp/assets/72872375/633eb87d-af3c-477f-9380-4a7cd7c7c3c2)
    * Because only read-only values are present (similar to PageSpeed Insights module edit view), the "Save" and "Cancel" CTA elements should not appear. Instead, only a "Close" CTA button that exits "Edit" mode should appear when editing. _Note: this isn't possible because of how the settings screens work, see: https://github.com/google/site-kit-wp/issues/8564#issuecomment-2066535413_
 * It should be possible to disconnect Ads from the edit module screen, as before.

## Implementation Brief

* [ ] Edit the file at `assets/js/modules/ads/components/settings/SettingsEdit.js`
    * [ ] Import the `SettingsView` component as this will be used to fall back to for PAX onboarded users, as they should not be able to edit the non PAX `Conversion Tracking ID` field:
    ```
    import SettingsView from './SettingsView';
    ```
    * [ ] Create constants to hold the values for `paxConversionID` and `extCustomerID` values:
    ```
    	const paxConversionID = useSelect( ( select ) =>
		select( MODULES_ADS ).getPaxConversionID()
	);

	const extCustomerID = useSelect( ( select ) =>
		select( MODULES_ADS ).getExtCustomerID()
	);
    ```
    * [ ] Within the conditional `viewComponent` assignments following the definition of `let viewComponent;`, add a new `else if` condition following the current `isAdBlockerActive` condition and require that `viewComponent` be set to `SettingsView` if `paxConversionID` or `extCustomerID` values are present, as this indicates a PAX onboarded user:
    ```
    ...
    	} else if ( paxConversionID || extCustomerID ) {
		viewComponent = <SettingsView />;
    ...
    ```

### Test Coverage

* Add/update Storybook tests so that scenarios for PAX onboarded settings edit views are catered for.

## QA Brief

* Set up and connect the Ads module
* Navigate to Site Kit > Settings > Ads
* In the console, unset values for the existing conversion ID and set values for the PAX settings:
```
googlesitekit.data.dispatch( 'modules/ads' ).setConversionID('');
googlesitekit.data.dispatch( 'modules/ads' ).setPaxConversionID('AW-98765');
googlesitekit.data.dispatch( 'modules/ads' ).setExtCustomerID('C-98765');
```
* Validate that the PAX fields now render in the settings view as below:

<img width="1355" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/4a3ef42c-5506-4e53-b476-916d6dab99da">

* When editing the settings, the read only settings should remain, and no setting should be editable
* Saving or cancelling should have the same effect, the settings form should simply revert to the standard settings view component, as per the below image:

![Screen Recording 2024-04-29 at 11 54 19 AM](https://github.com/google/site-kit-wp/assets/72872375/016eb1ac-c1ba-409d-8367-a5bfd01d0f0c)

## Changelog entry

* Update Ads settings edit view with PAX-specific alternate when connected via PAX.

**Comment by 10upsimon** [comment]
@aaemnnosttv I am noting that in the IB I stated the following:

> Because only read-only values are present (similar to PageSpeed Insights module edit view), the "Save" and "Cancel" CTA elements should not appear. Instead, only a "Close" CTA button that exits "Edit" mode should appear when editing.

However, in testing and exploration I noticed that if the `SettingsEditComponent` is present with a valid component during module registration, the "Save" and "Cancel" CTA's will always be present. Only if I remove the `SettingsEditComponent` prop at registration time, or pass it `false` will it fall back to a ready only state like we have for PSI.

I assume though, that this is fine? Functionality ultimately will be as follows:

https://github.com/google/site-kit-wp/assets/72872375/0f03e218-ab5b-4f6f-98e7-58ef27337d36

**Comment by aaemnnosttv** [comment]
> However, in testing and exploration I noticed that if the `SettingsEditComponent` is present with a valid component during module registration, the "Save" and "Cancel" CTA's will always be present. Only if I remove the `SettingsEditComponent` prop at registration time, or pass it `false` will it fall back to a ready only state like we have for PSI.

That's a good find, I forgot that we had that for PSI and that it was handled automatically like that. We could conditionally _not register_ a `SettingsEditComponent` like we do for PSI in this situation 🤔  If anything it should at least be fine for the MVP. The challenge is that module settings are not directly accessible when registering the module. So with that in mind, the current IB would solve that problem.

IB ✅ !

**Comment by 10upsimon** [comment]
@tofumatt I realised I incorrectly linked 2 PR's to this issue. The correct one is https://github.com/google/site-kit-wp/pull/8636

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

Tested on dev environment.
Verified when `adsPax` feature flag is enabled.
Verified when `adsPax` feature flag is not enabled.

@10upsimon 
- As per AC - `Because only read-only values are present (similar to PageSpeed Insights module edit view), the "Save" and "Cancel" CTA elements should not appear. Instead, only a "Close" CTA button that exits "Edit" mode should appear when editing.` 
But, currently close button is not appearing. Is this expected ?

- Also, I'm not getting same behaviour as per shared screencast in the QAB. On clicking 'Cancel' button ( I'm not getting save button) 'Conversion Tracking ID' and 'Customer ID' gets hide and Ads module conversion tracking ID starts showing.



https://github.com/google/site-kit-wp/assets/94359491/b3474bff-4d57-49af-a610-1d1a86251f2f

**Comment by 10upsimon** [comment]
@mohitwp I think this could be a result of the values being re-set as the component re-renders. Can you perhaps try persist the changes before testing:

```
googlesitekit.data.dispatch( 'modules/ads' ).setConversionID('');
googlesitekit.data.dispatch( 'modules/ads' ).setPaxConversionID('AW-98765');
googlesitekit.data.dispatch( 'modules/ads' ).setExtCustomerID('C-98765');
```

Then

```
googlesitekit.data.dispatch( 'modules/ads' ).submitChanges();
```

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified when adsPax feature flag is enabled.
- Verified when adsPax feature flag is not enabled.
- As discussed in slack close button will not part of the this ticket. AC is also updated now - `Because only read-only values are present (similar to PageSpeed Insights module edit view), the "Save" and "Cancel" CTA elements should not appear. Instead, only a "Close" CTA button that exits "Edit" mode should appear when editing. Note: this isn't possible because of how the settings screens work, see: https://github.com/google/site-kit-wp/issues/8564#issuecomment-2066535413
- `
- Verified that `paxConversionID` and `extCustomerID` two settings read only values are getting render within the existing <SettingsForm> component of the Ads module as per AC.
- Verified that it possible to disconnect Ads from the edit module screen, as before.


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/fac9cf1c-ad58-4037-be78-cbed8ab01d69)


https://github.com/google/site-kit-wp/assets/94359491/5ab8ab9c-88b6-4746-b2af-8c6062f57392


https://github.com/google/site-kit-wp/assets/94359491/e0d48009-a834-4278-96a5-032432f0217f


<.details>
