### ISSUE TITLE
Console Error In Connected Services Tab When Ads Module Is Not Active

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8592]
## Bug Description

We are requesting for Ads module settings endpoint before module is active, so we have a console log error on connected services page (when Analytics tab is open - no previously saved Ads conversion ID, and Ad blocker active)
<img width="1412" alt="image" src="https://github.com/google/site-kit-wp/assets/10414808/d20c849c-0d2d-44d7-a5a7-c11a4a418886">

## Steps to reproduce

1. Setup Site Kit with `adsModule` feature flag enabled
2. Connect Analytics
3. Go to the settings page
4. Make sure you have Ad blocker enabled
5. Expand the analytics tab, see the console error

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
I just tested this out and released this is happening because we're legitimately making these requests, but the Ad Blocker is tricking the WP Fetch API we use into thinking it's offline.

There's no fix for this; these requests _are_ failing when Ad Blockers are enabled and it's worth surfacing that to the console.
