### ISSUE TITLE
Use login hint when requesting additional scopes

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#867]
## Feature Description

The [authorization parameters](https://developers.google.com/identity/protocols/OAuth2WebServer#creatingclient) for OAuth support a `login_hint` for cases where the user that should be used is known ahead of time. This parameter should be used as soon as it is available via user's stored `Profile` data so that we can guide the user to use the same Google account they signed up with the first time.

![image](https://user-images.githubusercontent.com/1621608/68957890-a53db500-07d3-11ea-99d6-d8428ac2463e.png)

This should be set on the `Google_Client` each time before new scopes are requested based on the email returned by `Profile::get()['email']`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When a user that has already authenticated with Google is redirected to OAuth / proxy flow again (e.g. to grant new scopes access), the user should by default use the same Google account originally used (via `login_hint` parameter).

## Implementation Brief

* Remove `OAuth_Client` as a dependency of `Profile`
    - Remove `Profile::retrieve_google_profile_from_api` and call in `get`
* Request and set `Profile` data in `OAuth_Client::authorize_user` after auth token is set/updated
    - Most of this can be kept from the old `retrieve_google_profile_from_api`, however things related to timestamp/expiration can be removed
* Set login hint if available

## QA Brief

Using a browser where you have signed into multiple Google accounts:

* From a clean state install and set up Site Kit (minimum needed)
* See that your Google email and photo are shown in the top right of Site Kit screens
* Activate a module that requires additional scopes, such as Analytics
* See that the Google screen prompts you to "Choose an account" with the same Google account that was used during the initial set up displayed/pre-selected
* Again, see that your chosen Google email and photo are shown in the top right of Site Kit screens

## Changelog entry

* Use OAuth `login_hint` parameter to indicate that the user should use the same Google account across all modules.

**Comment by felixarntz** [comment]
@aaemnnosttv I wonder whether we should revamp the `Profile` class overall. I think determining whether it should do a query based on whether the `OAuth_Client` is provided is a bit too clever coding. Given how all the other similar classes work, I think we should consider removing the querying logic entirely from `Profile` (and thus also the `OAuth_Client` dependency) so that it only allows getting and setting the option value, like the other similar classes do.

I think it'd be more reliable to call the People API to fetch that data at certain designated points instead of "randomly" when obtaining the value. For example, whenever `OAuth_Client::authorize_user()` has obtained a new access and refresh token, this would be a good point to make that call.

**Comment by aaemnnosttv** [comment]
@felixarntz I agree, I don't think `Profile` should rely on `OAuth_Client`.

> For example, whenever OAuth_Client::authorize_user() has obtained a new access and refresh token, this would be a good point to make that call.

I think this is much better, since the Profile should always reflect the authorized user.

It shouldn't be too much more work, just requires moving somethings around. I'll update the IB now.

**Comment by felixarntz** [comment]
IB ✅

**Comment by tofumatt** [comment]
When selecting "Use another account" I see:

![2019-12-16 20 13 34](https://user-images.githubusercontent.com/90871/70939664-994a4a80-2040-11ea-8ed7-608360b05356.gif)

It seems I'm forced to sign in with a user in the same domain as my account. This is on a brand-new Jurassic Ninja site.

If that's intentional I guess this works, but I wasn't able to sign into another Google account. Trying to sign in by creating an account then falling back to "sign in instead" yields:

![2019-12-16 20 15 09](https://user-images.githubusercontent.com/90871/70939762-d6aed800-2040-11ea-9602-4812dceb011c.gif)

@aaemnnosttv is that intentional? If so this is good, but I'm not sure.

**Comment by aaemnnosttv** [comment]
My mistake @tofumatt - this is expected, I just misunderstood how "Use another account" works. Looks like you're restricted to accounts with the same domain as the address used for the login hint. As mentioned before, this isn't really something that is supported (switching google accounts after the initial authentication) so this is not a problem 😄 

This step in the brief was only intended to show that authenticating refreshes the profile info. I'll update the QAB.

**Comment by tofumatt** [comment]
QA ✅

Account photo/info is always there, looks good!
