### ISSUE TITLE
Remove G Site Kit icons on dashboard metabox and screen option

### ISSUE THREAD

**Issue by ThierryA** [google/site-kit-wp#877]
## Bug Description

The G Site Kit icon is rendered on the dashboard metabox and screen option which does not adhere to WordPress Standards. Instead, only "Site Kit" or "Site Kit by Google" text should be rendered.

## Steps to reproduce

1. Go to 'Dashboard'
2. Click on 'Screen option'

## Screenshots

![Screenshot 2019-11-19 at 10 03 01](https://user-images.githubusercontent.com/3581402/69132354-2f2b9d80-0ab4-11ea-8381-38bed0301d77.png)

![Screenshot 2019-11-19 at 10 03 11](https://user-images.githubusercontent.com/3581402/69132348-2c30ad00-0ab4-11ea-9fc4-cca88bfb322f.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For the screen option, display plain text: "Site Kit Summary" instead of the current image. 
* For the dashboard metabox, display plain text: "Site Kit Summary" instead of the current image.
* For the lefthand nav menu, decrease icon width to 16px

## Implementation Brief

* Change https://github.com/google/site-kit-wp/blob/6cc90cccb72fea847915012ca9a223c6088990f6/includes/Core/Admin/Dashboard.php#L118 to remove the text SVG and use text instead (it should read "Site Kit Summary"
* Adjust size of icon in https://github.com/google/site-kit-wp/blob/6cc90cccb72fea847915012ca9a223c6088990f6/includes/Core/Admin/Screen.php#L132 to be 16px high/wide

## Changelog entry

* Update usage of G icon in admin menu, dashboard widget and screen options to align better with WordPress admin UI.

**Comment by TomMuc1** [comment]
perfect :) thanx! and in addition I would really recommend to reduce the 'G' logo in the sidebar to keep the line spacing provided by wordpress as other respected plugin authors do.
<img width="173" alt="Bildschirmfoto 2019-11-19 um 10 18 06" src="https://user-images.githubusercontent.com/31601862/69133596-731fa200-0ab6-11ea-93ca-9a35f1a13d93.png">

**Comment by ThierryA** [comment]
> perfect :) thanx! and in addition I would really recommend to reduce the 'G' logo in the sidebar to keep the line spacing provided by wordpress as other respected plugin authors do.

Yep, will be reduced to 16px

**Comment by felixarntz** [comment]
IB ✅

**Comment by cole10up** [comment]
This is verified. The G is now 16 x 16 on the left nav. Also confirmed the copy states 'Site Kit Summary' as well as removing the G logo from Screen options

![image](https://user-images.githubusercontent.com/57115907/69281810-d1738000-0b9d-11ea-8722-9d61036e9bbd.png)

Passed QA ✅

**Comment by TomMuc1** [comment]
yes. but you can still clearly see that there is a bug with an additional blank line under the 'g' in the page bar. the distance from 'sitekit' to 'posts' is much too big.

**Comment by cole10up** [comment]
Do you mind if I create a separate bug for this spacing?

**Comment by TomMuc1** [comment]
feel free if you're paid on a per bug basis :)

**Comment by cole10up** [comment]
Ahah! What an incentive that would be! "Broken in Netscape Navigator 6" ;)

I'll get this bug in and reference it in this ticket for you.

**Comment by tofumatt** [comment]
That spacing is not a bug; it's an intentional menu separator in the WordPress Admin. There is one used to separate out site-wide sections like the WP Dashboard, Site Kit, and Jetpack and content-type sections like Posts, Media, Pages, and Comments. There's another after the content-type sections for things like Appearance and Settings. Those have always been there and aren't the result of our icon:

<img width="339" alt="Screenshot 2019-11-20 22 22 17" src="https://user-images.githubusercontent.com/90871/69283528-803aaf00-0be4-11ea-892b-cedfc09b6e6c.png">
<img width="336" alt="Screenshot 2019-11-20 22 22 03" src="https://user-images.githubusercontent.com/90871/69283532-80d34580-0be4-11ea-97fe-df096ae3e33c.png">
<img width="697" alt="Screenshot 2019-11-20 22 21 39" src="https://user-images.githubusercontent.com/90871/69283533-80d34580-0be4-11ea-9caa-eb86aad91cc7.png">

**Comment by cole10up** [comment]
Thanks for checking on that!

**Comment by ThierryA** [comment]
> ok. but then 'site kit' should definetly not show up under 'site-wide'. even if google thinks 'be loud - be on top' ...

Thanks for sharing your opinion @TomMuc1 . We have a user-first approach, in fact that is what matters the most to us. Looking at the various sections in the admin bar, the "site-wise" section is typically used for Hubs, Dashboards etc. Site Kit totally falls under this category given that it provides site-wise insights and dashboards. From a user perspective, it wouldn't make sense to have it in the post types list, settings or else section.

With that said, menu ordering preferences is very personal and thankfully, anyone is free to either re-order it via the code or [use a free plugin](https://wordpress.org/plugins/) allowing to customize admin menu order according to each and everyone preferences 😉

**Comment by TomMuc1** [comment]
is it a 'user first approach' or a 'google first approach'? if you look at the two oversized colorful icons that you have thankfully removed, you'll think of the second rather than the first. many other statistics plugins have decided to use the lower part of the page - but of course there are others who said 'main thing high up'. what is - rightly - today the biggest criticism of google worldwide is its encroachment in many ways. but surely that's a question you have to decide for yourself ...

cheers
tom

**Comment by TomMuc1** [comment]
the logo fits now. thanx!
<img width="159" alt="Bildschirmfoto 2019-11-22 um 11 21 49" src="https://user-images.githubusercontent.com/31601862/69418189-774bf980-0d1a-11ea-99c1-039e107cafce.png">
