### ISSUE TITLE
Add RRM module settings

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8793]
## Feature Description

The module settings required for Reader Revenue Manager should be added both in the server-side and datastore, including their validation. The module setting values should also be made available in the Site Kit debug information.

This issue should also be responsible for adding the `is_connected` and `on_deactivation` methods for the `Modules\Reader_Revenue_Manager` class, where the module is considered connected when the `publicationID` module setting is set, and all the module settings are deleted on deactivation.

- [See relevant section in the design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#heading=h.qvzw9wudpy41).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Module settings for the Reader Revenue Manager module should be added in both the server and client sides.
* The module settings that should be added are:
	* `publicationID` (string); Default: Empty string; Owned setting.
	* `publicationOnboardingState` (string); Default: Empty string.
	* `publicationOnboardingStateLastSyncedAtMs` (integer); Default: 0 (zero).
* Necessary validation should be implemented for the added module settings.
* Connection logic should be implemented for the module so that it is considered connected with the `publicationID` module setting set.
* All module settings should be deleted when the module is disconnected.

## Implementation Brief

* [x] Create `Google\Site_Kit\Modules\Reader_Revenue_Manager\Settings` in `includes/Modules/Reader_Revenue_Manager/Settings.php` file. 
    * [x] The class should extend from `Module_Settings` and implement `Setting_With_Owned_Keys_Interface`
    * [x] This class should use the `Setting_With_Owned_Keys_Trait` trait. 
    * [x] Define `OPTION` constant with the value  `googlesitekit_reader-revenue-manager_settings`
    * [x] Define `register` function which calls `parent::register()` and `$this->register_owned_keys()` (provided by the trait) to register the owned keys. 
    * [x] Define `get_owned_keys` function that returns an array with the owned key defined in the ACs. ie. `publicationID`.
    * [x] Define `get_default` function with the keys and default values  defined in the ACs. 
    * [x] Define `get_sanitize_callback` to ensure that the types of the settings fields are verified before saving. 
* [x] In `includes/Modules/Reader_Revenue_Manager.php`:
    * [x] In the `Reader_Revenue_Manager` class implement `Module_With_Deactivation`, `Module_With_Owner` and `Module_With_Settings` interfaces. 
        * [x] Use  `Module_With_Owner_Trait` and `Module_With_Settings_Trait` traits. 
        * [x] Define `setup_settings` function that  returns a new instance of `Google\Site_Kit\Modules\Reader_Revenue_Manager\Settings`.
    * [x] Define `is_connected` function that returns false if `publicationID` is not set (ie. the default empty string). Otherwise return `parent::is_connected()`. 
    * [x] Define `on_deactivation` function that deletes the module settings. 
* [x] In `assets/js/module/reader-revenue-manager/datastore/base.js`:
    * [x] Pass the newly added settings slugs in the `createModuleStore` call. 
* [x] In `assets/js/module/reader-revenue-manager/datastore/settings.js`:
    * [x] Add/update validation logic for the newly introduced settings fields. 

### Test Coverage

* Implement tests for newly added settings class using `SettingsTestCase` in `tests/phpunit/integration/Modules/Reader_Revenue_Manager/SettingsTest.php`
* In `tests/phpunit/integration/Modules/Reader_Revenue_ManagerTest.php`:
    * Implement `Module_With_Settings_ContractTests`.
    * Add test coverage for connection and deactivation logic. 
* Add Jest test coverage for newly added settings and validation. 

## QA Brief

There's no UI to test the feature as of now.

### Testing publicationID setting

1. Run the following command in browser console.

```js
  googlesitekit.data.select( 'modules/reader-revenue-manager' ).getSettings();
```

It should give the following object.

```js
  {
      publicationID: "",
      publicationOnboardingState: "",
      publicationOnboardingStateLastSyncedAtMs: 0
  }
```

2. Run following command in browser console.

```js
  googlesitekit.data.dispatch( 'modules/reader-revenue-manager' ).setPublicationID('ABCDEFGH');
  googlesitekit.data.dispatch( 'modules/reader-revenue-manager' ).saveSettings();
```

This should update the settings on server.

3. Refresh the page and run following command in browser.

```js
  googlesitekit.data.select( 'modules/reader-revenue-manager' ).getSettings();
```

It should give following output

```js
  {
      publicationID: "ABCDEFGH",
      publicationOnboardingState: "",
      publicationOnboardingStateLastSyncedAtMs: 0
  }
```

### Testing publicationOnboardingState setting

1. Run the following command in browser console.

```js
  googlesitekit.data.select( 'modules/reader-revenue-manager' ).getSettings();
```

It should give the following object.

```js
  {
      publicationID: "ABCDEFGH",
      publicationOnboardingState: "",
      publicationOnboardingStateLastSyncedAtMs: 0
  }
```

2. Run following command in browser console.

```js
  googlesitekit.data.dispatch( 'modules/reader-revenue-manager' ).setPublicationOnboardingState('ONBOARDING_ACTION_REQUIRED');
  googlesitekit.data.dispatch( 'modules/reader-revenue-manager' ).saveSettings();
```

This should update the settings on server.

3. Refresh the page and run following command in browser.

```js
  googlesitekit.data.select( 'modules/reader-revenue-manager' ).getSettings();
```

It should give following output

```js
  {
      publicationID: "ABCDEFGH",
      publicationOnboardingState: "ONBOARDING_ACTION_REQUIRED",
      publicationOnboardingStateLastSyncedAtMs: 0
  }
```

### Testing publicationOnboardingStateLastSyncedAtMs setting

1. Refresh the page and run the following command in browser console.

```js
  googlesitekit.data.select( 'modules/reader-revenue-manager' ).getSettings();
```

It should give the following object.

```js
  {
      publicationID: "ABCDEFGH",
      publicationOnboardingState: "ONBOARDING_ACTION_REQUIRED",
      publicationOnboardingStateLastSyncedAtMs: 0
  }
```

2. Run following command in browser console.

```js
  googlesitekit.data.dispatch( 'modules/reader-revenue-manager' ).setPublicationOnboardingStateLastSyncedAtMs( Math.floor( Date.now() / 1000 ) );
  googlesitekit.data.dispatch( 'modules/reader-revenue-manager' ).saveSettings();
```

This should update the settings on server.

3. Refresh the page and run following command in browser.

```js
  googlesitekit.data.select( 'modules/reader-revenue-manager' ).getSettings();
```

It should give following output, note that timestamp will vary.

```js
  {
      publicationID: "ABCDEFGH",
      publicationOnboardingState: "",
      publicationOnboardingStateLastSyncedAtMs: 01720542503 // This can vary.
  }
```

### Connection logic should be implemented for the module so that it is considered connected with the publicationID module setting set.

1. Activate the module.

2. Run the following command in browser console. Remember to replace publicationID value with your publication ID in publisher center. It can be found in publisher center URL.

```js
  const settings = {
    publicationID: "CAow6J6vDA",
    publicationOnboardingState: "ONBOARDING_STATE_UNSPECIFIED",
    publicationOnboardingStateLastSyncedAtMs: Date.now()
  };

  googlesitekit.data.dispatch('modules/reader-revenue-manager').setSettings( settings );
  googlesitekit.data.dispatch('modules/reader-revenue-manager').saveSettings();
```
Refresh the page.

3. Go to `Site Kit > Settings > Reader Revenue Manager`, it should show as conneected. This is because publication ID is set.

### All module settings should be deleted when the module is disconnected.

1. Once above step for connecting the module is done. Run following command in browser console. It may give you `undefined` at first run, so run it second time again as request may not have fulfilled for the first time.

```js
 googlesitekit.data.select('modules/reader-revenue-manager').getSettings();
```

It will give you an object something like

```json
{
    "publicationID": "CAow6J6vDA",
    "publicationOnboardingState": "ONBOARDING_STATE_UNSPECIFIED",
    "publicationOnboardingStateLastSyncedAtMs": 1721316244959,
    "ownerID": 1
}
```

Notice that this contains values for all the properties.

2. Now, disconnect the module and activate it again, but do not run connect steps mentioned above. Run this command again (may have to run twice)

```js
 googlesitekit.data.select('modules/reader-revenue-manager').getSettings();
```

Note that the values for the properties should be empty string and for `publicationOnboardingStateLastSyncedAtMs` it shuld be zero.

```json
{
    "publicationID": "",
    "publicationOnboardingState": "",
    "publicationOnboardingStateLastSyncedAtMs": 0
}
```

## Changelog entry

* Add Reader Revenue Manager module settings infrastructure.

**Comment by nfmohit** [comment]
IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

Tested this as per the ACs and these are working as expected:
- **Testing publicationID setting**
   <Details>
   <img width="1312" alt="Screenshot 2024-07-16 at 22 08 57" src="https://github.com/user-attachments/assets/1b2e8d20-1803-4db9-8414-32d2d16bf1e0">
   </Details>
   
- **Testing publicationOnboardingState setting**
   <Details>
   <img width="1312" alt="Screenshot 2024-07-16 at 22 12 23" src="https://github.com/user-attachments/assets/ae6d699a-fed7-46e9-9923-2fc5f07fc805">
   </Details>

- **Testing publicationOnboardingStateLastSyncedAtMs setting**
   <Details>
   <img width="1311" alt="Screenshot 2024-07-16 at 22 18 34" src="https://github.com/user-attachments/assets/5381dc83-0b35-48cd-b486-07c67298d8f1">
   </Details>
   
- The above tests were done without SK being set up but with the feature flag for RRM on. I set up SK and the results were consistent.

- I also tested with the feature flag off and the scripts would have errors and this is expected
   <Details>
   <img width="1094" alt="Screenshot 2024-07-16 at 22 19 51" src="https://github.com/user-attachments/assets/65a4ffe0-12ba-496e-bf94-fb9e0066adf5">
   </Details>

QUERY ⚠️ 
The main things I wanted to double confirm are whether we should do any other particular tests to validate those points from the ACs:
- Necessary validation should be implemented for the added module settings.
- Connection logic should be implemented for the module so that it is considered connected with the publicationID module setting set.
- All module settings should be deleted when the module is disconnected.

Based on my understanding, the QAB steps do not address those AC points but I could be wrong.

**Comment by ankitrox** [comment]
@kelvinballoo 

> Necessary validation should be implemented for the added module settings.

We have got it covered via the test case [here](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/reader-revenue-manager/datastore/settings.test.js#L54-L84)

> Connection logic should be implemented for the module so that it is considered connected with the publicationID module setting set.

Added in QAB

>  All module settings should be deleted when the module is disconnected.

Added in QAB

**Comment by kelvinballoo** [comment]
### QA Update ✅  

Tested this as per the ACs and these are working as expected:
- **Testing publicationID setting**
   <Details>
   <img width="1312" alt="Screenshot 2024-07-16 at 22 08 57" src="https://github.com/user-attachments/assets/1b2e8d20-1803-4db9-8414-32d2d16bf1e0">
   </Details>
   
- **Testing publicationOnboardingState setting**
   <Details>
   <img width="1312" alt="Screenshot 2024-07-16 at 22 12 23" src="https://github.com/user-attachments/assets/ae6d699a-fed7-46e9-9923-2fc5f07fc805">
   </Details>

- **Testing publicationOnboardingStateLastSyncedAtMs setting**
   <Details>
   <img width="1311" alt="Screenshot 2024-07-16 at 22 18 34" src="https://github.com/user-attachments/assets/5381dc83-0b35-48cd-b486-07c67298d8f1">
   </Details>
   
- The above tests were done without SK being set up but with the feature flag for RRM on. I set up SK and the results were consistent.

- I also tested with the feature flag off and the scripts would have errors and this is expected
   <Details>
   <img width="1094" alt="Screenshot 2024-07-16 at 22 19 51" src="https://github.com/user-attachments/assets/65a4ffe0-12ba-496e-bf94-fb9e0066adf5">
   </Details>

- **Connection logic should be implemented for the module so that it is considered connected with the publicationID module setting set.**
   After running the script and reloading the page, the RRM module is now connected.
   <Details>
   <img width="1214" alt="Screenshot 2024-07-19 at 11 28 06" src="https://github.com/user-attachments/assets/b3099df9-8dfd-4507-a432-9de8caddf4a6">
   </Details>

- **All module settings should be deleted when the module is disconnected.**
   Before disconnecting the module, the property settings are available.
   <Details>
   <img width="1215" alt="Screenshot 2024-07-19 at 11 28 32" src="https://github.com/user-attachments/assets/3a52e13d-e447-468f-9662-004639f37a9f">
   </Details>
   
   After disconnecting the module, the settings are empty :
   <Details>
   <img width="1212" alt="Screenshot 2024-07-19 at 11 30 21" src="https://github.com/user-attachments/assets/4aaeeef3-35aa-4fa1-97d7-63434589d286">

   </Details>

**Comment by ankitrox** [comment]
@kelvinballoo Property positioning in the object does not matter. 

```
   {
       "publicationID": "CAow6J6vDA",
       "publicationOnboardingState": "ONBOARDING_STATE_UNSPECIFIED",
       "publicationOnboardingStateLastSyncedAtMs": 1721316244959,
       "ownerID": 1
   }
```

OR

```
   {
       "ownerID": 1,
        "publicationOnboardingStateLastSyncedAtMs": 1721316244959,
         "publicationOnboardingState": "ONBOARDING_STATE_UNSPECIFIED",
       "publicationID": "CAow6J6vDA",
   }
```

Both are equal and okay.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Tested this as per the ACs and these are working as expected:
- **Testing publicationID setting** ✅ 
   <Details>
   <img width="1312" alt="Screenshot 2024-07-16 at 22 08 57" src="https://github.com/user-attachments/assets/1b2e8d20-1803-4db9-8414-32d2d16bf1e0">
   </Details>
   
- **Testing publicationOnboardingState setting** ✅ 
   <Details>
   <img width="1312" alt="Screenshot 2024-07-16 at 22 12 23" src="https://github.com/user-attachments/assets/ae6d699a-fed7-46e9-9923-2fc5f07fc805">
   </Details>

- **Testing publicationOnboardingStateLastSyncedAtMs setting** ✅ 
   <Details>
   <img width="1311" alt="Screenshot 2024-07-16 at 22 18 34" src="https://github.com/user-attachments/assets/5381dc83-0b35-48cd-b486-07c67298d8f1">
   </Details>
   
- The above tests were done without SK being set up but with the feature flag for RRM on. I set up SK and the results were consistent. ✅ 

- I also tested with the feature flag off and the scripts would have errors and this is expected ✅ 
   <Details>
   <img width="1094" alt="Screenshot 2024-07-16 at 22 19 51" src="https://github.com/user-attachments/assets/65a4ffe0-12ba-496e-bf94-fb9e0066adf5">
   </Details>

- **Connection logic should be implemented for the module so that it is considered connected with the publicationID module setting set.** ✅  
   After running the script and reloading the page, the RRM module is now connected.
   <Details>
   <img width="1214" alt="Screenshot 2024-07-19 at 11 28 06" src="https://github.com/user-attachments/assets/b3099df9-8dfd-4507-a432-9de8caddf4a6">
   </Details>

- **All module settings should be deleted when the module is disconnected.** ✅ 
   Before disconnecting the module, the property settings are available.
   <Details>
   <img width="1215" alt="Screenshot 2024-07-19 at 11 28 32" src="https://github.com/user-attachments/assets/3a52e13d-e447-468f-9662-004639f37a9f">
   </Details>
   
   After disconnecting the module, the settings are empty :
   <Details>
   <img width="1212" alt="Screenshot 2024-07-19 at 11 30 21" src="https://github.com/user-attachments/assets/4aaeeef3-35aa-4fa1-97d7-63434589d286">

   </Details>
   
   Moving ticket to Approval.
