### ISSUE TITLE
Implement RRM `getPublications()` selector

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8794]
## Feature Description

The `getPublications()` selector should be implemented for the Reader Revenue Manager module that should interact with the `GET:publications` REST endpoint and return a list of publications. 

- [See relevant section in the design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#bookmark=id.9bqgtkjartaf).
- This selector will be quite similar (if not the same) to the [TwG getPublications() selector](https://github.com/google/site-kit-wp/blob/1.89.0/assets/js/modules/thank-with-google/datastore/publications.js).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `getPublications()` selector should be added to the Reader Revenue Manager module data store.
* This selector should fetch the `GET:publications` REST endpoint (being implemented in [#8791](https://github.com/google/site-kit-wp/issues/8791)) to return the list of available publications for the site.

## Implementation Brief

- [x] Create `assets/js/module/reader-revenue-manager/datastore/publications.js`. This would be a data store to fetch the publications.
  - [x] Add this store in `Data.combineStores` in `assets/js/module/reader-revenue-manager/index.js` added in #8786
  - [x] Use `createFetchStore` to create the publication store (`getPublicationStore`). This should use `GET:publications` endpoint (being implemented in #8791) to return the list of available publications for the site.
  - [x] `baseName` for the store `getPublications`.
  - [x] Base initial state (`baseInitialState`) should have the `publications` property which would be `undefined` initially and will be set to the list of publications. It should be array of publication objects.
  - [x] In `reducerCallback` inside `createFetchStore`, set the `publications` property in `state`.
  - [x] Create a `baseResolvers` object.
    - [x] Add `*getPublications` generator inside it. It should call `getPublications` selector. If it is undefined, it will yield the result by calling `getPublicationStore.actions.fetchGetPublications`
  - [x] Create `baseSelectors` object.
    - [x] Add `getPublications` which should return `state.publications`.
- [x] Use `Data.combineStores` and pass the following
  - [x] `baseInitialState` as `initialState`
  - [x] `baseActions`, `reducer` as empty object.
  - [x] Set `resolvers` and pass `baseResolvers`.
  - [x] Set `selectors` and pass `baseSelectors`.

### Test Coverage

- [x] Add tests for `publications` data store. We can use `fetchMock` to mock the API calls.

## QA Brief

* Activating the `rrmModule` feature flag and the Reader Revenue Manager module.
* Run the following command in browser console.

```js
googlesitekit.data.select( 'modules/reader-revenue-manager' ).getPublications();
```

* This will trigger a request to `google-site-kit/v1/modules/reader-revenue-manager/data/publications` endpoint.
* It should return an empty array or array of publication objects depending on whether the publications are setup in the account associated with the site URL, with 200 response code.

## Changelog entry

* Add Reader Revenue Manager data store functionality to list available publications.

**Comment by nfmohit** [comment]
IB ✅

**Comment by nfmohit** [comment]
Hi @ankitrox . About the IB, I've removed the requirement of only including the `publicationID` and `displayName` properties in the publication object. Ideally, it should include all properties that the API returns. Sorry for not noticing that earlier. I hope that's okay. Thanks!

**Comment by ankitrox** [comment]
HI @nfmohit ,

That completely makes sense. In fact I realised this yesterday when I was working on #8837 

Thank you for making that change.

**Comment by ankitrox** [comment]
I've created the PR: https://github.com/google/site-kit-wp/pull/8950 for this issue, but keeping this issue in Execution because its dependencies #8786 #8791 are yet to be merged. 

Once merged, the base branch for this PR needs to be changed to `develop` and test everything and move this to CR.

**Comment by kelvinballoo** [comment]
### QA Update:

I've had an initial test and here are the results and queries:

- I've created the site and triggered the script in browser console and it rightly pulled nothing as there was no Publications. The request was made with 200 status ✅ 
   <Details>
   <img width="1262" alt="Screenshot 2024-07-15 at 19 02 02" src="https://github.com/user-attachments/assets/3744da40-5c1b-45ae-9a22-18669d0a2e23">
   
   <img width="1264" alt="Screenshot 2024-07-15 at 19 02 41" src="https://github.com/user-attachments/assets/70ceef92-68f9-4207-9ae0-c775c10115ec">
   
   </Details>

- After the first script execution, I went ahead to create a publication for the website and triggered the script again.
   However, this round, there was no request made to the publications endpoint. 
   And also, the publication was not retrieved. I would assume we should have triggered and pulled the new publication.
   Could you review whether any fixes is required here? ⚠️ 
   
   <Details>
   Publication is not retrieved:
   
   <img width="508" alt="Screenshot 2024-07-15 at 19 24 02" src="https://github.com/user-attachments/assets/224c17e8-6a0e-4b94-a12e-1a05659da6bb">


   https://github.com/user-attachments/assets/02aeff5a-3b3b-4a03-8448-b133e9c8ffba


   </Details>
   

- One thing to flag is after setting up the RRM module, at the module settings, it shows: "Complete setup for Reader Revenue Management"
   Question is: is that expected currently due to the implementation is not complete yet or it should have been successful? ⚠️ 
   <Details>
   <img width="1271" alt="Screenshot 2024-07-15 at 18 59 19" src="https://github.com/user-attachments/assets/6456c9c4-54bd-494f-bb64-ef7cc716c6e5">
   </Details>

**Comment by ankitrox** [comment]
>- After the first script execution, I went ahead to create a publication for the website and triggered the script again.
   However, this round, there was no request made to the publications endpoint. 
   And also, the publication was not retrieved. I would assume we should have triggered and pulled the new publication.
   Could you review whether any fixes is required here? ⚠️ 
 
`getPublications` is a selector which queries the API only when the data is not available. When we trigger the script for the first time, data is gathered from the API and is available for subsequent runs, so it will not call the API further.

We have a separate [ticket](https://github.com/google/site-kit-wp/issues/8797) where `maybeSyncPublicationOnboardingState` selector will periodically sync and update the publications in the database.

>One thing to flag is after setting up the RRM module, at the module settings, it shows: "Complete setup for Reader Revenue Management"
Question is: is that expected currently due to the implementation is not complete yet or it should have been successful?

Yes, this is expected! The reason for that is we do not have the #8800 ready yet, but you can refer to #8796 IB where step 2 would help to resolve this issue.

```js
  const settings = {
    publicationID: "CAow6J6vDA",
    publicationOnboardingState: "ONBOARDING_STATE_UNSPECIFIED",
    publicationOnboardingStateLastSyncedAtMs: 0
  };

  googlesitekit.data.dispatch('modules/reader-revenue-manager').setSettings( settings );
  googlesitekit.data.dispatch('modules/reader-revenue-manager').saveSettings();
```

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

- I've created the site and triggered the script in browser console and it rightly pulled nothing as there was no Publications. The request was made with 200 status ✅ 
   <Details>
   <img width="1262" alt="Screenshot 2024-07-15 at 19 02 02" src="https://github.com/user-attachments/assets/3744da40-5c1b-45ae-9a22-18669d0a2e23">
   
   <img width="1264" alt="Screenshot 2024-07-15 at 19 02 41" src="https://github.com/user-attachments/assets/70ceef92-68f9-4207-9ae0-c775c10115ec">
   
   </Details>

- I've also created another side and created a publication for it. After running the script in browser console, it rightly pulled the publication with the proper endpoint with 200 status. ✅ 

   <Details>
   <img width="1312" alt="Screenshot 2024-07-17 at 17 10 57" src="https://github.com/user-attachments/assets/1ce69523-73db-480f-9528-68e01a4cc65f">
   
   <img width="1312" alt="Screenshot 2024-07-17 at 17 11 16" src="https://github.com/user-attachments/assets/fc9df80a-d12c-4d41-a103-110ce3bdddd1">


   </Details>
   
 Moving ticket to Approval.
