### ISSUE TITLE
Implement RRM `findMatchedPublication()` action

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8795]
## Feature Description

The `findMatchedPublication()` action should be implemented for the Reader Revenue Manager module that finds a matching publication from the list of all publications based on the following criteria:

> - If there is no publication in the list, it will return null early as there is no publication to select.
> - Otherwise, if there is only one publication in the list, it will return that publication.
> - Otherwise, if there is more than one publication in the list, it will return one as follows:
>   - It will prefer a publication that has completed setup (i.e. its onboardingState property is ONBOARDING_COMPLETE) and return that publication.
>   - Otherwise, it will just return the first publication in the list.

- [See relevant section in the design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#bookmark=id.aczji1onkgv3).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `modules/reader-revenue-manager` data store should have a `findMatchedPublication()` action added, that finds a matching publication from the list of available publications based on the following criteria:
	* If there is no publication in the list, it should return null early as there is no publication to select.
	* Otherwise, if there is only one publication in the list, it should return that publication.
	* Otherwise, if there is more than one publication in the list, it should return one as follows:
		* It should prefer a publication that has completed setup (i.e. its onboardingState property is `ONBOARDING_COMPLETE`) and return that publication.
		* Otherwise, it should just return the first publication in the list.

## Implementation Brief

In `assets/js/module/reader-revenue-manager/datastore/publications.js`:

* Add a new action, `findMatchedPublication()` that finds a matching publication with the following logic:
    * Get the list of all publications from the `getPublications` selector.
    * Return `undefined` if the publications have not been loaded yet.
    * If there is no publication in the list, return `null`.
    * If there is only one publication in the list, return that publication.
    * If there is more than one publication in the list, return one as follows:
        * Find a publication that has completed setup (i.e., `publication.onboardingState` property is set to `ONBOARDING_COMPLETE`) and return that publication.
        * Otherwise, return the first publication in the list.

### Test Coverage

* Add test coverage for the new action `findMatchedPublication()` in `assets/js/module/reader-revenue-manager/datastore/publications.test.js`.

## QA Brief

* Follow the QAB from [#8791](https://github.com/google/site-kit-wp/issues/8791) to create new publications.
* Enable "Add code to your site" within the survey setup for the publications created above for the publications to be fetched in Site Kit. Please refer to the "Note" in this [comment](https://github.com/google/site-kit-wp/issues/8791#issuecomment-2219949538).
![Screenshot 2024-07-23 at 4 52 47 PM](https://github.com/user-attachments/assets/1c7f0827-feca-4fe9-8315-9353b9124c85)
* Clear the browser session storage and run the following command in the browser console:
```js
await googlesitekit.data.dispatch('modules/reader-revenue-manager').findMatchedPublication()
```
* Verify that the action returns the expected publication based on the AC above.
* For any reason the publications are not fetched, we can simulate by providing the publications mock data.
* To verify the action returns `null` when there are no publications, run the following command in the browser console:
```js
googlesitekit.data.dispatch('modules/reader-revenue-manager').receiveGetPublications( [] )
await googlesitekit.data.dispatch('modules/reader-revenue-manager').findMatchedPublication()
```
* To verify the action returns the only publication when there is only one publication, run the following command in the browser console:
```js
let publications = [
    {
        "publicationId": "IJKLMNOP",
        "publicationPredicates": {
            "businessPredicates": {
                "supportsSiteKit": true,
                "canSell": true
            }
        },
        "verifiedDomains": "example.com",
        "displayName": "Test Publication 1",
        "onboardingState": "ONBOARDING_COMPLETE"
    }
]
googlesitekit.data.dispatch('modules/reader-revenue-manager').receiveGetPublications( publications )
await googlesitekit.data.dispatch('modules/reader-revenue-manager').findMatchedPublication()
```
* To verify the action returns the publication that has completed setup when there are multiple publications, run the following command in the browser console:
```js
let publications = [
	{
		"publicationId": "PQRSTUV",
		"publicationPredicates": {
			"businessPredicates": {
				"supportsSiteKit": true,
				"canSell": false
			}
		},
		"verifiedDomains": "example.com",
		"displayName": "Test Publication 2",
		"onboardingState": "PENDING_VERIFICATION"
	},
	{
		"publicationId": "IJKLMNOP",
		"publicationPredicates": {
			"businessPredicates": {
				"supportsSiteKit": true,
				"canSell": true
			}
		},
		"verifiedDomains": "example.com",
		"displayName": "Test Publication 3",
		"onboardingState": "ONBOARDING_ACTION_REQUIRED"
	},
	{
		"publicationId": "QRSTUVWX",
		"publicationPredicates": {
			"businessPredicates": {
				"supportsSiteKit": false,
				"canSell": true
			}
		},
		"verifiedDomains": "example.com",
		"displayName": "Test Publication 4",
		"onboardingState": "ONBOARDING_COMPLETE"
	}
]
googlesitekit.data.dispatch('modules/reader-revenue-manager').receiveGetPublications( publications )
await googlesitekit.data.dispatch('modules/reader-revenue-manager').findMatchedPublication()
```
* To verify the action returns the first publication when there are multiple publications and none of them have completed setup, run the following command in the browser console:
```js
let publications = [
    {
        "publicationId": "PQRSTUV",
        "publicationPredicates": {
            "businessPredicates": {
                "supportsSiteKit": true,
                "canSell": false
            }
        },
        "verifiedDomains": "example.com",
        "displayName": "Test Publication 2",
        "onboardingState": "PENDING_VERIFICATION"
    },
    {
        "publicationId": "IJKLMNOP",
        "publicationPredicates": {
            "businessPredicates": {
                "supportsSiteKit": true,
                "canSell": true
            }
        },
        "verifiedDomains": "example.com",
        "displayName": "Test Publication 3",
        "onboardingState": "ONBOARDING_ACTION_REQUIRED"
    },
    {
        "publicationId": "QRSTUVWX",
        "publicationPredicates": {
            "businessPredicates": {
                "supportsSiteKit": false,
                "canSell": true
            }
        },
        "verifiedDomains": "example.com",
        "displayName": "Test Publication 4",
        "onboardingState": "PENDING_VERIFICATION"
    }
]
googlesitekit.data.dispatch('modules/reader-revenue-manager').receiveGetPublications( publications )
await googlesitekit.data.dispatch('modules/reader-revenue-manager').findMatchedPublication()
```

## Changelog entry

* Add Reader Revenue Manager data store functionality to find a matching publication.

**Comment by nfmohit** [comment]
IB LGTM 👍 ✅

**Comment by kelvinballoo** [comment]
### QA Update ⚠️ 

I've tested this and here are the results:

- I was able to test for 0 publications and it would return null.
   <Details>
   <img width="1312" alt="0 Publication" src="https://github.com/user-attachments/assets/0daea869-87cc-4627-899b-96f67a2db17f">

   </Details>
- I tested with 1 Publication and it would return accordingly.
   <Details>
   <img width="1312" alt="1 Publication" src="https://github.com/user-attachments/assets/358f0daa-f514-4c7e-a3b8-bc8b6293a632">

   </Details>

-  The problem I am having is with multiple publications and how to define 'ONBOARDING STATE = COMPLETED' in the RRM platform. ⚠️ 
   - I set up 3 publications
      - One without checking the 'Add to site' checkbox in the RRM platform
      - One adding all the checkboxes in the RRM platform but without proceeding it there
      - One with all checkboxes in RRM platform and proceeded it  
         - I am assumed this would set the onboarding state to 'Completed' but in vain
   - When I ran the script, the publication 3 comes up but with onboardingstate as 'ONBOARDING ACTION REQUIRED'
      <Details>
     
      <img width="1257" alt="Screenshot 2024-07-18 at 15 25 09" src="https://github.com/user-attachments/assets/d71bad2a-f6a8-4206-b3be-0907f44e805d">

     </Details>
   - ⚠️  There are to main things I want to unpick from here:
      - How do I get an onboarding action completed in the RRM platform?
      - Per the AC, if there are no publication with complete onboarding, the first publication on the list would return.
      My question is, how do I validated which one is the first publication? How do I verify the API list?

**Comment by hussain-t** [comment]
Hi @kelvinballoo,

As we discussed during our call, the Google service API is returning only a single publication despite multiple publications. This may be due to a configuration issue in how the publication was created within the RRM console or the API needing more time to sync the data. However, this is outside the scope of this issue and is not an issue from Site Kit.

You can mock the data directly in your browser console to test the behavior with multiple publications. You can copy the mock JSON data from [this file](https://github.com/google/site-kit-wp/blob/d3b0e3507c8cc01e6f31ea42c8750c65421ecbb3/assets/js/modules/reader-revenue-manager/datastore/__fixtures__/publications.json) and use it with the `receiveGetPublications` action. This will allow the data to be available for testing in the `getPublications` selector.

Run the following command in the browser console:
```js
googlesitekit.data.dispatch( 'modules/reader-revenue-manager' ).receiveGetPublications(mockJsonData);
```

Replace `mockJsonData` with the actual mock data you copied. This should help you simulate and test multiple publications.

cc: @wpdarren @nfmohit

**Comment by wpdarren** [comment]
@hussain-t thanks for the explanation, I just want to highlight one point. 

> the Google service API is returning only a single publication despite multiple publications. This may be due to a configuration issue in how the publication was created within the RRM console or the API needing more time to sync the data. However, this is outside the scope of this issue and is not an issue from Site Kit. 

While I realise this is an API issue, shouldn't we be flagging this with someone?  The AC says we have to test with multiple publications, and that's hard to do if the API is not functioning as expected. 

That aside, I am going to look at this ticket and sync with @kelvinballoo  when I have looked at it.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@hussain-t I am wondering if the issue we're having here is linked to the problem I am seeing on #8796 where when `googlesitekit.data.select('modules/reader-revenue-manager').getPublications();` is run, no publications are appearing. I have run the code in the QAB on this ticket, `await googlesitekit.data.dispatch('modules/reader-revenue-manager').findMatchedPublication()` and the response is still `null`.   I have two publications created. 

![image](https://github.com/user-attachments/assets/21088132-e3df-4ed5-a883-f3eb5d853bb6)
![image](https://github.com/user-attachments/assets/0a9ea561-e600-40af-92ec-37d72f5ff422)

**Comment by hussain-t** [comment]
Hi @wpdarren, I see the results when executing the browser console action.

![Screenshot 2024-07-23 at 4 16 07 PM](https://github.com/user-attachments/assets/e15e46fe-1657-4399-b369-faf992513bdb)

As explained [here](https://github.com/google/site-kit-wp/issues/8795#issuecomment-2236355890). The publications weren't being fetched from the API call. The action returns `null` because the publications API's result is an empty array.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@hussain-t thank you for the additional QAB instructions! 

When I run `await googlesitekit.data.dispatch('modules/reader-revenue-manager').findMatchedPublication()` if no publication is created then `null` appears ✅  and if I have just one publication then that appears ✅  

My publication has 3 set up, and I have set up RRM / Survey with code on site for each one. 

The issue is when I have 2 or more publications, only one publication appears. 

![image](https://github.com/user-attachments/assets/7e66d375-c1ae-4439-83b8-8c14e6546a08)

I run the mock code in the QAB for more than one publication and only 1 publication appears. 

I am assuming all 4 should have appeared? 

![image](https://github.com/user-attachments/assets/2fb5d8d8-1e2d-44ae-9f7c-bbd32c6fe5dd)

**Comment by hussain-t** [comment]
Hi @wpdarren, it seems you misunderstood the `findMatchedPublication` action with the `getPublications` selector.

- `getPublications` - returns the list of all the publications
- `findMatchedPublication` - find the matched **ONLY ONE** publication based on the criteria.

I hope that clears your concerns.

**Comment by wpdarren** [comment]
@hussain-t in the QAB on this ticket it mentions `findMatchedPublication` in all of the code examples.  I found the correct code for more than one publication and now see them all as expected.  

### QA Update: ✅ 

**Verified:**

The modules/reader-revenue-manager data store has a findMatchedPublication() action added, that finds a matching publication from the list of available publications based on the following criteria:
- If there is no publication in the list, it returns `null` as there is no publication to select.
- If there is only `one publication` in the list, it returns that publication.
- If there is more than one publication in the list, it returns one as follows:
  - It prefers a publication that has completed setup and returns that publication.
  - Otherwise, it returns the first publication in the list.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/6ad72810-0474-4580-9702-518b29d2f2f6)
![image](https://github.com/user-attachments/assets/cdb775cc-91c0-4d7c-aea2-07c4cd9b5ca6)
![image](https://github.com/user-attachments/assets/8ae0e536-de3d-4656-a971-20dba0efdc17)

</details>
