### ISSUE TITLE
Implement RRM `syncPublicationOnboardingState()` action

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8796]
## Feature Description

The `syncPublicationOnboardingState()` action should be implemented for the Reader Revenue Manager module that syncs the value of the `publicationOnboardingState` module setting with the publication's onboarding state in the API.

- [See relevant section in the design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#bookmark=id.7kpe9zaisjmg).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `syncPublicationOnboardingState()` action should be implemented for the `modules/reader-revenue-manager` data store that syncs the value of the `publicationOnboardingState` module setting with the publication's onboarding state in the API if a publication is connected to the module.
* This should also update the `publicationOnboardingStateLastSyncedAtMs` module setting to the current time, in the form of the number of milliseconds elapsed since the epoch (using `Date.now()` for example).
* If the `publicationOnboardingState` module setting is updated from any other non-empty state to `ONBOARDING_COMPLETE`, as a side effect, the publication approved overlay notification (being implemented in [#8843](https://github.com/google/site-kit-wp/issues/8843)) should be displayed.
* The `syncPublicationOnboardingState()` action should be dispatched whenever the [`getPublications()` selector](https://github.com/google/site-kit-wp/issues/8794) is resolved.

## Implementation Brief

In `assets/js/modules/reader-revenue-manager/datastore/publications.js`:

* [x] **Define the `*syncPublicationOnboardingState()` action with the following logic:**
    * [x] Load the modules using the `getModules()` selector.
    * [x] Check if the `reader-revenue-manager` module is connected using the `isModuleConnected` selector.
    * [x] If the module is not connected, return early.
    * [x] Load the module settings using the `getSettings()` selector of the `modules/reader-revenue-manager` data store.
    * [x] Retrieve the `publicationID` module setting using the `getPublicationID()` selector.
    * [x] If `publicationID` is not set, return early.
    * [x] Use the [`getPublications()` selector](https://github.com/google/site-kit-wp/issues/8794) to obtain the publications data.
    * [x] Find the publication matching the `publicationID` module setting in the publications data.
    * [x] Compare the `onboardingState` of the matched publication with the `publicationOnboardingState` module setting.
    * [x] If they differ, update the `publicationOnboardingState` module setting with the new value from the API i.e. the `onboardingState` of the matched publication using the `setSettings()` action.
    * [x] Update the `publicationOnboardingStateLastSyncedAtMs` module setting with the current time using `Date.now()` using the `setSettings()` action.
    * [x] Save the updated settings using the `saveSettings()` action.
    * [x] If the `publicationOnboardingState` module setting changes to `ONBOARDING_COMPLETE` from any other non-empty state, set the `UI_KEY_SHOW_RRM_PUBLICATION_APPROVED_NOTIFICATION` key in the `core/ui` store to display the `<PublicationApprovedOverlayNotification>`. (Note: This key may be different during the execution phase of [#8843](https://github.com/google/site-kit-wp/issues/8843).)
* [x] **Dispatch the `syncPublicationOnboardingState()` action:**
    * [x] Dispatch the `syncPublicationOnboardingState` action within the `*getPublications()` resolver.

### Test Coverage

* Add test coverage for the `syncPublicationOnboardingState` action.

## QA Brief

**Note 1**: Ensure that you have publications setup in publisher center. Refer QAB of this issue on how to setup publications. Also, there should be atleast two publications setup for testing this.

**Note 2**: Ensure that "Custom Site URL" is NOT set in "Tester Settings" (Site Kit by Google Tester plugin).

1. Activate the module.
2. Run the following command in browser console. Remember to replace publicationID value with your publication ID in publisher center. It can be found in publisher center URL.

```js
  const settings = {
      publicationID: "CAow6J6vDA",
      publicationOnboardingState: "ONBOARDING_STATE_UNSPECIFIED",
      publicationOnboardingStateLastSyncedAtMs: 0
    };

    googlesitekit.data.dispatch('modules/reader-revenue-manager').setSettings( settings );
    googlesitekit.data.dispatch('modules/reader-revenue-manager').saveSettings();
```
refresh the page.

3. This will set the publication data in settings. Note that current value of onboarding state is `ONBOARDING_STATE_UNSPECIFIED` and `publicationOnboardingStateLastSyncedAtMs` is zero. This can be verified using following command in browser console.

```js
googlesitekit.data.select('modules/reader-revenue-manager').getSettings();
```

4. Now, run following command in browser console. This will trigger a request to publications endpoint to publisher centre. Let that request complete. For the first time, it will output `undefined`. Once request gets completed and then running the same command will output the publication data.

```js
 googlesitekit.data.select('modules/reader-revenue-manager').getPublications();
```

5. Run the command

```js
 googlesitekit.data.select('modules/reader-revenue-manager').getSettings();
```

notice that `publicationOnboardingState` and `publicationOnboardingStateLastSyncedAtMs` must have changed from the previous values to reflect the current onboarding state of the publication and the timestamp in milliseconds which should be the current time.

## Changelog entry

* Add infrastructure for synchronizing the onboarding state of a publication in the Reader Revenue Manager module.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@ankitrox I have a few observations that I would like to run by you. 

1.  When I run `googlesitekit.data.select('modules/reader-revenue-manager').getPublications();` I see `undefined` but when I run it a second time, I do see a response. 

- Should it take two runs of the command for the API to provide us with the publication data?
- I don't see any mention of the publication name or ID, when the command is run a second time. The expected behaviour of this command isn't included in the QAB, so I wasn't sure.  Is this correct? See screenshot below. 

![image](https://github.com/user-attachments/assets/03c9e647-5b68-4f4a-a6fa-878a1ad99593)

2.  The QAB says this after running  `googlesitekit.data.select('modules/reader-revenue-manager').getSettings(); `

> notice that publicationOnboardingState and publicationOnboardingStateLastSyncedAtMs must have changed from the previous values to reflect the current onboarding state of the publication and the timestamp in milliseconds which should be the current time.

The ouput is the same as when I ran the same command previously. 

![image](https://github.com/user-attachments/assets/170b5b22-6268-4f9a-acc4-c9b635c4fa35)

Please could you clarify the two points above. Thank you!

**Comment by ankitrox** [comment]
Thank you @wpdarren for testing this and raising your queries. Please find the answers below to the questions.

>When I run googlesitekit.data.select('modules/reader-revenue-manager').getPublications(); I see undefined but when I run it a second time, I do see a response.
Should it take two runs of the command for the API to provide us with the publication data?
I don't see any mention of the publication name or ID, when the command is run a second time. The expected behaviour of this command isn't included in the QAB, so I wasn't sure. Is this correct? See screenshot below.

I have amended the description in QAB regarding this command. When the command is run for the first time, it will output `undefined` as the request is yet to be resolved. Once the request is successful and after that we run the same command, it will output the publication data.

> The ouput is the same as when I ran the same command previously.

I see that there are no publications fetched from the API. So you will need to create couple of publications as mentioned in QAB. Also, note that when running the first command given in QAB instructions, you must replace the publication ID with the one you created in publisher centre.

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@ankitrox I am still seeing the same behaviour as mentioned above.   

You can see on the screenshot all of he commands that I have run.  I have two publications. Used the correct ID. 

1. No publication data appears when I run `googlesitekit.data.select('modules/reader-revenue-manager').getPublications();`
2. When I run googlesitekit.data.select('modules/reader-revenue-manager').getSettings();
 in step 5, the data appears as step 3. 

Could you confirm if you see the same on your side? 

![image](https://github.com/user-attachments/assets/df7c50ea-3cd6-4408-ae6a-d66e57db24be)

**Comment by hussain-t** [comment]
@wpdarren, you see results for `getSettings` because you have set the settings using the `setSettings` action and saved it.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Running the commands provided the data in the QAB including the publications. 

![image](https://github.com/user-attachments/assets/347efc67-6fc8-4f24-bdc6-81574135045e)
