### ISSUE TITLE
Show custom setup screen to second WP admin

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#881]
## Feature Description

Due to permissions and identity requirements, each WP admin needs to complete the Site Kit setup on their own. 
However, we show the same setup site screen to all WP users, regardless whether it's the first person to set up the plugin or other admins. Let's show a customised screen to make it easier for each admin to understand what's expected to happen. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When an admin clicks on the Site Kit menu in the left nav after another admin has already set up the plugin, display a setup page with the following customised text: 

Heading: "Sign in with Google to configure Site Kit"
Text: "To use Site Kit, sign in with your Google account. The Site Kit service will guide you through 3 simple steps to complete the connection and configure the plugin." 
Button: "Sign in with Google" 

## Implementation Brief

* Conditionally render alternate copy in `setup-proxy.js` if `isResettable` (credentials are present) but was not just disconnected/revoked as this has its own messaging

## Changelog entry

* Update wording on setup screen for secondary users to clarify they need to connect their account, but not set up the plugin.

**Comment by aaemnnosttv** [comment]
@marrrmarrr this is a great idea. As for the wording, I have a few suggestions for your consideration that I think might be an improvement.

> Heading: "Another admin for your site has already installed Site Kit"

I'm not sure if "installed" is the right word here, as that much is known by the screen's existence 😄. I think the main thing to communicate here is that in order to use Site Kit (and have access to data), they need to sign in with Google. They of course also need to be a verified site owner, and delegate access, and add the site to Search Console which is all more/less done for them by the proxy. 

Suggested heading: **Sign in with Google**

> Text: "To use the plugin, you'll need to set up Site Kit with your own account. Site Kit Service will guide you through 3 simple setup steps."

Suggested variation:
"To use Site Kit, sign in with your Google account and then our Site Kit service will guide you through 3 simple steps to complete the connection."

> Button: "Start setup"

It might be more accurate to say "Sign in with Google" since this flow is more about connecting the user rather than setting up Site Kit (as is more accurate for the first admin), which to me implies things like options, settings, or other choices. It would also be more verbally consistent with the suggested messaging above.

Let me know what you think!

**Comment by marrrmarrr** [comment]
> @marrrmarrr this is a great idea. As for the wording, I have a few suggestions for your consideration that I think might be an improvement.
> 
> > Heading: "Another admin for your site has already installed Site Kit"
> 
> I'm not sure if "installed" is the right word here, as that much is known by the screen's existence . I think the main thing to communicate here is that in order to use Site Kit (and have access to data), they need to sign in with Google. They of course also need to be a verified site owner, and delegate access, and add the site to Search Console which is all more/less done for them by the proxy.
> 
> Suggested heading: **Sign in with Google**

Agree it's better to have the biggest fontsize text communicate the main action. I would also add what the result will be so they understand why we're asking them to do this: 
"Sign in with Google to configure Site Kit"  
> 
> > Text: "To use the plugin, you'll need to set up Site Kit with your own account. Site Kit Service will guide you through 3 simple setup steps."
> 
> Suggested variation:
> "To use Site Kit, sign in with your Google account and then our Site Kit service will guide you through 3 simple steps to complete the connection."

The second admin could in theory activate modules that the first one didn't, e.g. if they have access to AdSense on the site they could connect that as well. I agree "setup" doesn't match the intent, since they're the second person doing this, so perhaps "configure" is a good option with enough sense of action (: 

"To use Site Kit, sign in with your Google account. Site Kit service will guide you through 3 simple steps to complete the connection and configure the plugin."

> 
> > Button: "Start setup"
> 
> It might be more accurate to say "Sign in with Google" since this flow is more about connecting the user rather than setting up Site Kit (as is more accurate for the first admin), which to me implies things like options, settings, or other choices. It would also be more verbally consistent with the suggested messaging above.
> 
> Let me know what you think!

Button change sounds good. I'll update the ACs with all this. Thanks again for the thoughtful suggestions!

**Comment by aaemnnosttv** [comment]
Much better I think! Thanks @marrrmarrr 😄

**Comment by felixarntz** [comment]
IB ✅

**Comment by aaemnnosttv** [comment]
@marrrmarrr I think "service" probably should not be capitalized in "Site Kit Service" since this it isn't the actual name/title of the site. What do you think?

Also, regarding the description text it might read a bit more naturally to say "The Site Kit service" rather than starting the sentence with "Site Kit service".

Additionally, I feel like the same suggestions we applied to the AC here would also be an improvement to the instructions for the default headline and text verbiage for the first admin. Maybe this should be a separate issue but it's a very small change.

Default heading
> The Site Kit plugin is active but requires setup

Suggested heading
**Sign in with Google to set up Site Kit**

Default text
> Site Kit Service will guide you through 3 simple setup steps.

Suggested text
**The Site Kit service will guide you through 3 simple setup steps.**

The default button text "Start setup" is still good and should stay the same 😄

**Comment by marrrmarrr** [comment]
Both of these SGTM!

**Comment by cole10up** [comment]
**Tested**

Added 2 new Admins. Validated copy for 2nd admin setup screen:
![image](https://user-images.githubusercontent.com/57115907/70685913-a1c90c80-1c5f-11ea-8aa4-182acb8ef799.png)

**Question:** Should the reset button be present for 2nd Admin initial setup?

After clicking reset, user is sent initial admin setup screen.

![image](https://user-images.githubusercontent.com/57115907/70686047-f4a2c400-1c5f-11ea-9d8f-82b35eb716d3.png)

During one of my tests I also saw a Server error validating my domain here. It was intermittent but I captured it and will watch for this going forward.

https://drive.google.com/file/d/1lIuIhu1cvp0RgHQ4g_VhjFecwne832CA/view

Please review.

**Comment by aaemnnosttv** [comment]
> Question: Should the reset button be present for 2nd Admin initial setup?

Yes. This button will display as long as Site Kit has client credentials saved which are independent of user access 👍

**Comment by cole10up** [comment]
Thanks @aaemnnosttv 

Passed QA ✅

**Comment by marrrmarrr** [comment]
👁👍

**Comment by Buildbetter** [comment]
Why need to sign, what is benefits of this – all administrators of the site do add their own google profiles to see statistics?
Why need to authenticate WordPress plugin in their PERSONAL Google PROFILES?
