### ISSUE TITLE
2nd tile has no data

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#8921]
## Bug Description

While testing the audience segmentation epic, I noticed that the 2nd tile doesn't come with value at all. 
It is always 0, even if it actually should have data.
Refer to the screenshots further down where I swapped the positions of an audience where there was a tile with numbers.

## Steps to reproduce

1. Set up 2 tiles under audience segmentation
2. The 2nd tile will be 0 for the first 4 parameters (even if they should have data)
3. You can swap the tile order to verify this. To swap, it's just a matter of unselecting the one you want second, save and reselect again.

## Screenshots

When 'All Visitors' is in position 1, there is data for the first 4 lines with 5.9K visitors, etc... :
<img width="1306" alt="Screenshot 2024-06-20 at 19 18 23" src="https://github.com/google/site-kit-wp/assets/125576926/9c4316dc-8ead-4354-893b-383300b4f956">

When the same tile is swapped in position 2, there is no data. It's worth noting that the analytics figures at the bottom are showing accordingly.
<img width="1304" alt="Screenshot 2024-06-20 at 19 23 34" src="https://github.com/google/site-kit-wp/assets/125576926/ee0383d5-e457-439c-af46-c3ce0879e2ed">

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Audience Tiles should show the correct data for the audiences.
* Specifically, the tile in the second position should not show zero data when there is in fact data.

## Implementation Brief

- [ ] In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget.js`
  - [ ] Collect the current metric values and previous metric values in `currentMetricValues` and `previousMetricValues` respectively by looking up the rows by their `audienceResourceName` and `dateRange` dimensions.
  - [ ] Update [these metrics](https://github.com/google/site-kit-wp/blob/97816cc39b6cda34e459a863b2ec857608e48b45/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget.js#L373-L411) by looking into `currentMetricValues` and `previousMetricValues` with their corresponding indexes.

Note: We can use https://github.com/google/site-kit-wp/pull/8997 as a starting point which covers the proposed fix.

### Test Coverage

* Add the story for the scenario where we do not have the comparison data available.

## QA Brief

* Setup Site Kit with Analytics module
* Enable groups
* Go through `Steps to reproduce`
* Verify that data is showing correctly now

## Changelog entry

* Update segmentation tiles to properly display non-empty data.

**Comment by techanvil** [comment]
Note: I tested this out, with intermittent results. In my initial testing the bug only occurred when the first tile was in the zero data state. However, I tried it again while reviewing Question 3 in this [comment], and found the bug occurred while the first tile did have data.

**Comment by ankitrox** [comment]
Hi @kelvinballoo ,

Thank you for reporting this issue.

1. This seems to be a special case. We are trying to compare the data for last 28 days, but as we can see that `New Visitors`  and `Returning Visitors`  audiences are created only on 20th June, 2024.
2. So essentially Google Analytics 4 does not have data for last 28 days to compare. If I change it to 14 days, we have the data to compare which is expected.
3. Specifically for `New Visitors`  and `Returning Visitors`, this issue will get addressed in #8144 for which we already have the ticket.

@techanvil Please let me know if we should handle this edge case for user created audiences. I think this should get addressed because user created audience can be created at later point and may get added in audience tile, so instead of showing the zero data in rows, we can display the current metrics value and partial data badge (which is already there). 

@kelvinballoo  Please look at [this screencast](https://www.loom.com/share/f10722273ffc4f0fb3523b01cd67bcf6?sid=2ed9dc9a-bfeb-4dcf-93be-e11eff53ccda) which shows the above mentioned scenario in SK dashboard.

**Comment by techanvil** [comment]
Hi @ankitrox, as you've pointed out this issue can also occur with user-created audiences that we don't have the special-case handling for. So we do need a general fix for this issue. It's not confined to new/returning audiences only.

**Comment by techanvil** [comment]
IB :white_check_mark:

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified that the Audience Tiles showing the correct data for the audiences.
- Verified the tile in the second position are not showing zero data when there is in fact data.

<details>

_Latest environment_

![image](https://github.com/user-attachments/assets/a892ac93-4386-4b47-8020-596a3263a864)

_main environment_

![image](https://github.com/user-attachments/assets/ea3c25fb-a596-4a9e-9c3b-168e9599610d)

![image](https://github.com/user-attachments/assets/b9b19aae-3880-4972-8a06-2d7a00331f22)

![image](https://github.com/user-attachments/assets/80fdd502-d90e-4268-a75a-8124cf9a6ba6)

![image](https://github.com/user-attachments/assets/d3e9582d-f805-45b4-8df4-0f5ead55fbb9)

</details>
