### ISSUE TITLE
Include async attribute in Subscribe with Google script tag

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9055]
## Feature Description

It would be nice to include the async attribute for the script tag which references the Subscribe with Google script, in order to more closely align with the example provided on the Publisher Center

![image](https://github.com/user-attachments/assets/4b2579a0-695e-4554-a711-6a82813d6ac3)

At present we don't include the attribute:
![image](https://github.com/user-attachments/assets/3f533e06-5f56-4f5f-86dc-ed966bd3bb3b)

This is non-essential and raised as a P1.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For WordPress versions 6.3+ (i.e. versions with native support for the `async` attribute in registered scripts), the script tag which references the Subscribe with Google script should have the `async` attribute set.

## Implementation Brief

- Within `includes/Modules/Reader_Revenue_Manager/Web_Tag.php`:
  - Add a call to `wp_script_add_data()` for the script with the key `'strategy'` and value `'async'`.
  - Modify the call to `wp_add_inline_script()` to pass the position `'before'`.
https://github.com/google/site-kit-wp/blob/e47bad259554273f4a3712f505a75633747b8c3f/includes/Modules/Reader_Revenue_Manager/Web_Tag.php#L85
- See the [comments below](https://github.com/google/site-kit-wp/issues/9055#issuecomment-2251191163) for more details.

### Test coverage

* Add PHPUnit test coverage for the above changes in `tests/phpunit/integration/Modules/Reader_Revenue_Manager/Web_TagTest.php`.

## QA Brief

* Using the tester plugin, turn on the `rrmModule` feature flag.
* Set up Site Kit with the Reader Revenue Manager module.
* Go to the site's front end and view its page source.
* Observe the script added by RRM and verify that the script with the source https://news.google.com/swg/js/v1/swg-basic.js includes the `async` attribute.

## Changelog entry

* Add the `async` attribute to the Subscribe with Google script tag.

**Comment by aaemnnosttv** [comment]
It's worth noting that the current implementation of the RRM web tag is not compatible with WP core's application of deferred script strategies due to its use of an inline "after" script. [See the explanation here](https://make.wordpress.org/core/2023/07/14/registering-scripts-with-async-and-defer-attributes-in-wordpress-6-3/#:~:text=Inline%20scripts%20that%20are%20registered%20in%20the%20after%20position%20(the%20default%20for%20wp_add_inline_script())%2C%20however%2C%20will%20affect%20the%20final%20loading%20strategy%20of%20a%20main/parent%20script%20if%20said%20main/parent%20script%20has%20an%20async%20or%20deferred%20eligible%20strategy).

As for the implementation of the strategy itself, this can be set in a backwards-compatible way [as "data"](https://make.wordpress.org/core/2023/07/14/registering-scripts-with-async-and-defer-attributes-in-wordpress-6-3/#:~:text=The%20simplest%20way%20to%20prevent%20this%20interoperability%20problem%20is%20to%20pass%20the%20strategy%20via%20a%20different%20means%20than%20the%20%24args%20param%20to%20wp_register_script()%20or%20wp_enqueue_script()%20functions.) which can then be handled in a central way to apply the attribute. FWIW the inline script could be changed to be "before" which would not break the behavior but it would prevent this side effect of affecting the effective strategy.

IMO, the application of `async` here could be seen as a progressive enhancement rather than an important behavior to back-port to all supported versions of SK; I'd be okay to not do this and rely on the core feature only given that the vast majority of our users are on recent major versions of WP unless the cost of back-porting was particularly minimal.

**Comment by techanvil** [comment]
Thanks @aaemnnosttv, that's very useful.

@ankitrox, I can see you've already got an IB drafted here, but as Evan has pointed out, the current implementation where the inline script is in the default `after` position will prevent the `async` attribute from being applied when using the core API. We should also use the strategy-as-data approach for backward compatibility.

I'd also agree that it makes sense to take a progressive enhancement approach here, the backport is _fairly_ minimal but it would still be nice to avoid the extra code if we don't really need it. I have therefore updated the AC to reflect this.

@ankitrox, please can you revise the IB accordingly? It's essentially going to boil down to this change:

```diff
diff --git a/includes/Modules/Reader_Revenue_Manager/Web_Tag.php b/includes/Modules/Reader_Revenue_Manager/Web_Tag.php
index 2f52b078c5..5b7398c6eb 100644
--- a/includes/Modules/Reader_Revenue_Manager/Web_Tag.php
+++ b/includes/Modules/Reader_Revenue_Manager/Web_Tag.php
@@ -82,7 +82,8 @@ class Web_Tag extends Module_Web_Tag {
 
 		// phpcs:ignore WordPress.WP.EnqueuedResourceParameters.MissingVersion
 		wp_register_script( 'google_swgjs', 'https://news.google.com/swg/js/v1/swg-basic.js', array(), null, true );
-		wp_add_inline_script( 'google_swgjs', $swg_inline_script );
+		wp_script_add_data( 'google_swgjs', 'strategy', 'async' );
+		wp_add_inline_script( 'google_swgjs', $swg_inline_script, 'before' );
 
 		wp_enqueue_script( 'google_swgjs' );
 	}
```

**Comment by techanvil** [comment]
As Ankit has unassigned this, I've gone ahead and updated the IB myself.

**Comment by nfmohit** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ✅ 

The script added by RRM with the source `https://news.google.com/swg/js/v1/swg-basic.js` includes the `async` attribute.

![image](https://github.com/user-attachments/assets/7ef6815e-8baa-4010-b157-ffa8d4740f2f)
