### ISSUE TITLE
Blocked Aria hidden console error on dropdowns

### ISSUE THREAD

**Issue by kelvinballoo** [google/site-kit-wp#9142]
## Bug Description

This surfaced on https://github.com/google/site-kit-wp/issues/8839
Whenever the publications have already been retrieved and I click on the dropdown, there is a console error.
This does not only apply to the RRM module but actually any module that has a dropdown.
It was seen on the Analytics and Search console module as well.

## Steps to reproduce

1. Set up SK
2. Open dev Console
3. Go to any SK module with a dropdown and click on the dropdown

## Screenshots

<img width="1245" alt="Screenshot 2024-08-05 at 17 35 15" src="https://github.com/user-attachments/assets/e8c72cfa-3dc8-44d7-a8b5-bd54fef60c2f">

<img width="1240" alt="Screenshot 2024-08-05 at 18 24 49" src="https://github.com/user-attachments/assets/0402ba3a-edc5-4ff4-b2a7-4793204823d0">

## Additional Context

 - PHP Version: 8.0
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.32.0
 - Device: Macbook Pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment]
It looks like this is happening on _every_ Material dropdown in the plugin.

If so, this is an upstream fix that isn't actually straightforward; we would need to update our version of the Material UI React libraries we're using.

I think possibly #7239, but certainly #7133 would solve this. But I don't think we can fix this issue ourselves (since we aren't the ones specifying those aria attributes on interaction).

It's a legit issue, but I think we're best to mark it as won't fix for now, since we can't fix it and it's not actionable/fixed by another issue.
