### ISSUE TITLE
Creation of `Top cities driving leads` ACR KMW

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#9154]
## Feature Description

One of the identified metric tiles for the ACR epic is `Top cities driving leads`. Details of this metric tile are as follows:

- **Description**: Cities making the most contact form submissions. Tile should combine counts from both `contact` and `submit_lead_form` events, if present, otherwise, it will use the data for events that are present.
- **Events**: `submit_lead_form`, `contact`
- **Metrics**: `generate_lead`, `submit_lead_form`, and` contact` events count
- **Dimension**: `city`
- **Order**: Descending
- **Purpose**: Inform users of the most active cities submitting the lead form on the website so they can make informed decisions.
- **Type**: Tabular

### Figma Design 
[Top cities driving leads](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1953-23424&t=StMacPaWHh4k5rtt-0) within **_ACR metrics_** section of design

### Widget Preview
<img width="300" alt="image" src="https://github.com/user-attachments/assets/fcccc9ff-2bd9-45de-b44a-2920c8a15d92">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `Top cities driving leads` ACR widget is introduced to the existing list of widgets available within KMW
    * Said widget presents visually as per the Figma design: [Top pages driving leads](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1953-23424&t=StMacPaWHh4k5rtt-0) within **_ACR metrics_** section of design (screenshot below)
    * <img width="300" alt="image" src="https://github.com/user-attachments/assets/fcccc9ff-2bd9-45de-b44a-2920c8a15d92">
    * Said widget retrieves and displays the top 3 cities ordered by `generate_lead`, `submit_lead_form` and `contact` event count ordered by city, with cities listed on the left, and total event counts from each city to the right
    * Said widget will display the following tooltip text when the information icon is hovered over (within the widget tile): "Cities driving the most contact form submissions"
    * Said new widget will not render any output if the `conversionReporting` feature flag is not enabled, until such time that the feature flag is removed in a future issue
    * Said new widget will not be displayed if none of the above listed event names are present

## Implementation Brief

* [ ] Update `assets/js/googlesitekit/datastore/user/constants.js`
  * Include new constant, say `KM_ANALYTICS_TOP_CITIES_DRIVING_LEADS`, holding a string `kmAnalyticsTopCitiesDrivingLeads` 
* [ ] Update `assets/js/components/KeyMetrics/key-metrics-widgets.js`
  * Add a helper function, for example `shouldDisplayWidgetWithConversionEvent` (if not included already), that will use the selector implemented in #9132 to check if `this.requiredConversionEventName` is present in the returned array, alongside the presence of `conversionReporting` feature flag. It can work similarly like `shouldDisplayWidgetWithCustomDimensions`
  *  Register new widget for `KM_ANALYTICS_TOP_CITIES_DRIVING_LEADS`
    * Use "Top cities driving leads" for `title`
    * Use "Cities driving the most contact form submissions" for `description` and `tooltip`
    * Include new property `requiredConversionEventName`, and assign it an array value containing following event names: `submit_lead_form`, `contact` and `generate_lead`
    * In `displayInList` pass the helper function `shouldDisplayWidgetWithConversionEvent`
* [ ] Add `assets/js/modules/analytics-4/components/widgets/TopCitiesDrivingLeadsWidget.js`
  * You can use `assets/js/modules/analytics-4/components/widgets/TopCitiesWidget.js` for example, as a starting point 
  * Include `showWidget` const which should value of `isKeyMetricActive` or if no event is present in the inline data (the condition used in `shouldDisplayWidgetWithConversionEvent` helper function), so this const can be used to return `WidgetNull` and prevent report requests if conditions are not met. You can see example usage of this const in `assets/js/modules/analytics-4/components/widgets/PopularProductsWidget.js`
  * In `reportOptions`:
    * Use `city` and `eventName` for dimensions
    * Use `eventCount` metric
    * Include `dimensionFilters` for `eventName` dimension. Use `inListFilter` for `filterType` and for the `value` include the detected event name by cross-referencing the `recentEvents` inline data returned from selector implemented in #9132 with - `['submit_lead_form', 'contact', 'generate_lead']`. In case both `contact` and `submit_lead_form` are detected, use only `submit_lead_form`, to cover the cases where users have both Popup Maker and Contact Form 7 plugins installed, as both events would be tracked, making them duplicate.
      * You can see an example of how is `inListFilter` filter used in `assets/js/modules/analytics-4/components/widgets/TopRecentTrendingPagesWidget.js`
  * Render the result showing city from `city` dimension and count from returned values of `eventCount` metric

### Test Coverage

* Add stories for the new widget

## QA Brief

* Setup Site Kit with Analytics module
  * Contact Aleksej for access to the website with ACR data
* Verify that in key metrics selection panel `Top cities driving leads` widget is not available
* Enable `conversionReporting` feature flag
* Go to key metrics selection panel and choose `Top cities driving leads` tile
* Verify it widget is showing data, and matching the figma design
* Go to analytics settings - switch to different account/property, and verify that `Top cities driving leads` widget is not available (since widget will only be visible on property that has ACR data)

## Changelog entry

* Add the new `Top cities driving leads` widget.

**Comment by eugene-manuilov** [comment]
> * Said widget makes use of the `MetricTileTable` component to facilitate layout of said top 3 pages, matching the design

@10upsimon, similar to #9153, AC looks good but this point is not needed. I'll remove it and move this task to IB.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@zutigrm I have two observations. 

1. I enabled the `conversionReporting` feature flag and added the `Top cities driving leads` metric tile. I then went and disabled the feature flag and assumed that the tile would no longer appear, but it does. When I look in the metrics selection though it does not appear which is expected.   Should the tile be removed and replaced with the icon to select a new metric within the Key metrics widget? 

Linked to this, when you click on the metrics selection panel, it says 4 are selected, but actually there's only 3. So, it's still including the `Top cities driving leads` metric. 

https://github.com/user-attachments/assets/32a187b0-cd3f-428f-90fa-a4251ddfe950

2. In the list of cities, I see `[Not set]` - for the other Key metric tiles for city and country,  we saw this appearing and chose to filter it because it's not very useful for the user. Interested in your thoughts. 

![image](https://github.com/user-attachments/assets/93972ac1-cd29-4d37-905d-1186a120b609)

**Comment by zutigrm** [comment]
@wpdarren Thanks for your observation.

Regarding the
> In the list of cities, I see [Not set] - for the other Key metric tiles for city and country, we saw this appearing and chose to filter it because it's not very useful for the user. Interested in your thoughts.

I was considering this, but we do filter `not set` only for custom dimensions, since we add them, these are core metrics, and we do not filter this out in in any core metrics, like this one:
<img width="519" alt="image" src="https://github.com/user-attachments/assets/45f90afd-e171-4638-9905-3beb02a7432e">

> I enabled the conversionReporting feature flag and added the Top cities driving leads metric tile. I then went and disabled the feature flag and assumed that the tile would no longer appear, but it does. When I look in the metrics selection though it does not appear which is expected. Should the tile be removed and replaced with the icon to select a new metric within the Key metrics widget?

I was considering this also should it be hidden in the metrics itself, but since feature flag is enabled/disabled only during development, I didn't see an occurrence in real usage where users would be able to switch this, as once it rolled out, the feature will be available to them (always on). But let me check with @jimmymadon if he remembers how we handled key metric widgets initially, did we need to disable them in the widget area as well, when feature flag is disabled?

**Comment by jimmymadon** [comment]
@zutigrm @wpdarren 

> I was considering this, but we do filter not set only for custom dimensions...

Actually, we have decided to filter out all Not Set values for all Key Metrics. This has been discussed on one of our AC Team Review meetings. We have an [issue](https://github.com/google/site-kit-wp/issues/7884) for this. 

>since feature flag is enabled/disabled only during development, I didn't see an occurrence in real usage where users would be able to switch this, as once it rolled out, the feature will be available to them (always on)

This is correct and makes sense! When we rolled out the feature first, the whole Key Metrics widget area was wrapped in the feature flag and not individual tiles (as far as I remember). 
However, it might be safer to wrap the new tiles with the feature flag, just in case we do a roll out but then something goes wrong and we decide to switch off the feature. This usually never happens. However, this possibility is the main reason we introduce any feature to a "few" users first and then slowly roll out to more people. So being consistent would be ideal here.

**Comment by zutigrm** [comment]
@jimmymadon Thank you, makes sense to me. @wpdarren I will update both points in a follow-up

**Comment by zutigrm** [comment]
@wpdarren Follow up only includes filtering for not set dimension value. The removal of metric tile when feature flag is disabled will not be a quick implementation, as even we hide the widget, it will shift the layout to 3 available metrics and value saved in the DB will still be there. I will need to consult with @aaemnnosttv on this this week, as it will be a bit more complicated, we would need to build additional fallback mechanism only for the feature flag, or "hack" the saved value in some way to remove ACR metrics, so if the effort is justified, I will open the follow up issue to take care of this and it will affect all ACR tiles.

**Comment by wpdarren** [comment]
### QA Update: ⚠️  

@zutigrm  this passes the QAB, but I did some additional testing around switching the Analytics account/property to one that does not have any ACR data.  I noticed that the `Top cities driving leads` metric does not appear in the selection panel, but the tile still appears in the key metrics widget and nothing loads because the data doesn't exist.  

You see a continuous loading animation for this tile.  Do you feel this is related to the previous issue where it remains when the feature flag is disabled. 

![image](https://github.com/user-attachments/assets/43ad180a-b808-4d1d-adc5-6a6b183cef86)

**Verified:**

- In selection panel `Top cities driving leads` widget is not available with conversionReporting feature flag disabled.
- The` Top cities driving leads` tile appears in the selection panel. 
- The widget is showing data, and matches the figma design
- When switch to different account/property, the `Top cities driving leads` widget is not available in the selection panel since it is only be visible on property that has ACR data. 

![image](https://github.com/user-attachments/assets/8f62acb7-7390-45bf-97f5-0be4383242ff)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- In selection panel `Top cities driving leads` widget is not available with conversionReporting feature flag disabled.
- The` Top cities driving leads` tile appears in the selection panel. 
- The widget is showing data, and matches the figma design
- When switch to different account/property, the `Top cities driving leads` widget is not available in the selection panel since it is only be visible on property that has ACR data. 
- Retested the scenario where the admin changes the Analytics account to one that has no ACR date. On the key metrics widget the new tile appears with a notice that there's no data. I looked in the selection panel and it appears there so that the user can deselect it and choose another metric. 
- Checked that I was able to deselect the new tile and select another metric. No errors appeared on the front end of on the console. Looking good! 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/8f62acb7-7390-45bf-97f5-0be4383242ff)
![image](https://github.com/user-attachments/assets/f1cb8178-a4b8-415f-86a8-eff0e890cb69)
![image](https://github.com/user-attachments/assets/53e3892e-e004-41f1-aa39-d8c1518ae8c7)

</details>
