### ISSUE TITLE
Refactor the `ZeroDataNotification` to use the new lighter `Notification` component.

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#9184]
## Feature Description

This issue focuses on refactoring the `ZeroDataNotification` using the new `Notification` wrapper component along with the newly introduced layout component in #9071.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Refactor the `ZeroDataNotification` to use the new `Notification` wrapper component introduced in #9071.
* The refactoring should use a relevant "layout" component and other "common" components following the pattern introduced in #9071.
* The rendering and behaviour of the `ZeroDataNotification` should remain the same, i.e. all existing GA events should be fired and the design/links should work as before.

## Implementation Brief

* [x] In `assets/js/components/notifications/ZeroDataNotification.js`
  * [x] Check the `assets/js/components/notifications/GatheringDataNotification.js` for the example 
  * [x] Remove usage of `BannerNotification` component
  * [x] Include 2 new props - `id` and `Notification`
  * [x] Wrap the component with `Notification` component passed as the prop 
  * [x] The existing `NotificationWithSmallSVG` can be reused. Refactor this notification to allow the usage of only the `Dismiss` component.  
  * [x] Use new components from `assets/js/googlesitekit/notifications/components/common/` to assemble the notification using the existing props used to for `BannerNotification`. 
  * [x] A new `LearnMoreLink` component can append the Learn more link required in the description.

### Test Coverage

* No new tests required but ensure the existing stories and tests work.

## QA Brief

* Test the Zero Data Notification thoroughly.
    * Test the GA tracking event for view-notification when the notification is rendered. 
    * Click on the Learn more link and test the appropriate GA event (click_learn_more) is fired.
    * Click on the `Remind me later` button and test the dismissal. Ensure the notification is correctly dismissed - a new item will appear in the `wp_googlesitekitpersistent_dismissed_items` record in `wp_usermeta` in the database.
* Test when any other notification, say any other `SetupSuccessBannerNotification` or the `GatheringDataNotification` is active - they should take precedence over the Zero Data notification.
* Follow the QAB for #9071 as the code for this issue touches the code from that issue as well.

## Changelog entry

* Refactor the ZeroDataNotification to use the new lighter Notification component.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ❌ 

Tested on dev environment.

@jimmymadon 

**Issue 1:** 
1>Set up SK without Analytics.
2>On main dashboard 'Search console is in gathering data state' notification is showing.
3>Now set up analytics and select account and property which is in zero data ste.
4> After successful setup user navigates to Main dashboard.
5> On main dashboard 'Search console is in gathering data state' notification is showing. Click on 'See more services' CTA. It will dismiss the gathering data notification.
4> Now refresh the main dashboard and Open entity dashboard in new tab and open one more main dashboard  in a new tab and again refresh.
5> In this case Zero data notice for analytics is not showing. 
**Expected** - Zero data notification for analytics should appear when gathering data notification gets dismiss on main dashboard.

**Issue 2>** If the zero data notification is not dismissed and the user opens the dashboard in a new tab or window, the zero data state notification does not appear on the first load. The user must refresh the page for the notification to appear. This behavior is observed on both the main and entity dashboards. However, this issue does not occur with the gathering data state notification.

<details>


https://github.com/user-attachments/assets/66f1bc71-8b42-41a9-9df7-46908c508581

</details>

**Comment by jimmymadon** [comment]
@mohitwp 

Issue 1 and Issue 3 are current behaviour already (on the last release). So this behaviour is fine.

Issue 2: I am not able to reproduce this. I tried this when SC is in Zero Data and when Analytics alone is in Zero data, and in both cases, the notification appeared immediately after module set up without requiring a page load or refresh. Could you please create a screencast (with the URL bar present as well always). Even if this was the case, I feel this also won't be a release blocker as it is minor and can be fixed in the next release. 

Thank you!

c.c. @aaemnnosttv

**Comment by mohitwp** [comment]
### QA Update ✅

- Thank you @jimmymadon for confirmation on point 1 and 3.
- I'm able to reproduce issue number 2. I shared the screencast also. But, this issue is not a blocker so created a new ticket https://github.com/google/site-kit-wp/issues/9227


- Tested on main environment.
- Verified multiple 'view notification' events are not getting track for 'main-dashboard-zero data notification'.
- Verified zero data notification for both SC and Analytics module.
- Verified the GA tracking event for view-notification when the notification is rendered.
- Verified clicking  on the Learn more link open URL in a new tab and the appropriate GA event (click_learn_more) is fired.
- Verified clicking on the Remind me later button dismiss the notification.
- Verified the notification is correctly dismissed - a new item appear in the wp_googlesitekitpersistent_dismissed_items record in wp_usermeta in the database.
- Verified when any other notification, any other SetupSuccessBannerNotification is active - they take precedence over the Gathering Data notification.

<details>

![image](https://github.com/user-attachments/assets/bca56546-ddb8-4254-8415-26b226967dc8)

![image](https://github.com/user-attachments/assets/066fb3b6-62f7-4ac8-90f3-302de33a5384)

![image](https://github.com/user-attachments/assets/605467df-b0e4-4bf8-ae00-5961018626d8)

![image](https://github.com/user-attachments/assets/23017470-176c-4a72-86e1-76317ea1a5b2)

</details>
