### ISSUE TITLE
Can't set up SiteKit, Error claiming I'm not logged in on my site

### ISSUE THREAD

**Issue by neverything** [google/site-kit-wp#921]
## Bug Description

When setting up SiteKit, I activated the plugin and was ready to go. When I click on the start setup button, it takes me to the screen to set stuff up and when I click "Sign in with Google" I get the following error message:

> An error occurred: We were unable to send credentials to your WordPress site. Please go back to your site and restart the setup. The following error was returned: Du bist aktuell nicht angemeldet.

The last sentence is in German and means "You are currently not logged in".

I am logged in to both, my site and my Google account. I disabled ad blockers and tried it in both Chrome and Firefox.

## Steps to reproduce

1. Go to WP Admin > Site Kit > Dashboard
2. Click on Start Setup
3. Click on Sign in with Google
4. Error appears: An error occurred: We were unable to send credentials to your WordPress site. Please go back to your site and restart the setup. The following error was returned: Du bist aktuell nicht angemeldet.

## Additional Context

 - Browser: Chrome and Firefox
 - Plugin Version: 1.1.1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@neverything Thanks for reporting, the issue is with your hosting provider blocking incoming API requests on your site. Future releases of the plugin should provide workarounds for this, but in the meantime you can contact your hosting provider. If you want further support you can submit such support requests on the [WordPress support forum](https://wordpress.org/support/plugin/google-site-kit/) for the plugin, where we are now providing general support.

**Comment by neverything** [comment]
Thanks @jamesozzie will check with my hosting company. Looking forward to the future releases 💯
