### ISSUE TITLE
AdSense: Setup loop for existing users with approved site

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#936]
## Bug Description

For existing AdSense users with approved accounts there is a setup loop which results in users not having Auto Ads code inserted into their sites. 

[Video of issue](https://recordit.co/YyTmczCnmL)

The same issue is reported from the WordPress support forums [here](https://wordpress.org/support/topic/associating-adsense-to-site-kit-loops-but-never-connects/). 
There are no console errors, and no error header responses. 

- Tested on clean WordPress install
- No additional plugins active
- Domain is approved and served ads previously

## Screenshots

![YyTmczCnmL](https://user-images.githubusercontent.com/41326532/69947170-001a2080-14e5-11ea-8610-ed84aa4df53c.gif)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When AdSense is set up correctly, user should reach confirmation dialog indicating code will be placed on the site (with a toggle to opt out)

![image](https://user-images.githubusercontent.com/2676022/70174790-cedf5300-1692-11ea-9375-ded24e861a5c.png)

If user toggles, shows this: 

![image](https://user-images.githubusercontent.com/2676022/70174824-ddc60580-1692-11ea-918c-cd3e7a7e2838.png)

* Clicking the "Continue" button takes the user to the AdSense module page, where the current data is visible

![image](https://user-images.githubusercontent.com/2676022/70175023-339aad80-1693-11ea-8eaa-a729b16bf565.png)

## Implementation Brief

* 

## Changelog entry

*

**Comment by OisinOConnor** [comment]
Might be related to https://github.com/google/site-kit-wp/issues/891

**Comment by adamsilverstein** [comment]
Hi @jamesozzie and thanks for the bug report!

Since this is still an issue, I'd like to get some more debugging details. 

Looking at the website, I DO see the AdSense code, so perhaps something is wrong in your AdSense account? For example the site might be flagged for some reason. Can you double check by logging into your AdSense account and checking the domain under "Sites" for any errors or warnings? Check the site matches exactly and that you have AutoAds enabled for the domain (I realize these worked previously -  this is a double check)

If you don't find an issue there, can you please follow these steps:

1. Deactivate the AdSense service under Site Kit -> Settings ->AdSense -> Edit -> Disconnect AdSense from Site Kit -> Disconnect (this step clears all settings)
2. Reactivate AdSense service: Site Kit -> Settings -> Connect more services
3. Monitor [network traffic ](https://developers.google.com/web/tools/chrome-devtools/network) in devtools, filtering by responses to "wp-json"

Disconnect:
![image](https://user-images.githubusercontent.com/2676022/71269042-92a32800-230b-11ea-908d-507e21636e0f.png)

Network requests during setup:
![image](https://user-images.githubusercontent.com/2676022/71269158-e281ef00-230b-11ea-9508-791d5282975d.png)

**Question**: do you get the `setup-complete` request? 

* **If so**, this indicates a successful connection to your AdSense account. In this case, try refreshing and recording the wp-json network requests again, its possible you have a "Zero Data" state.

* **If not**, the connection is failing for some reason, please examine the requests and the "preview" tab to check the server responses, looking for any errors. I suspect the domain test may be failing based on your screen recording, what is the response from the `urlchannels` request? Is your domain listed? 

You can provide screenshots here, however please be sure to remove/blur any personal information like your account id and client id (as in my screenshot)!

**Comment by jamesozzie** [comment]
@adamsilverstein Thanks for the follow up. No longer an issue from my side, maybe 1.1.3 provided a fix once #891 was resolved.
