### ISSUE TITLE
Expand the logic of the `ACRNotificationCTAWidget` component for existing KMW users with manual set up

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9372]
## Feature Description

The `ACRSubtleNotification` component logic should be expanded so it surfaces in the dashboard within key metrics widget area for the users who have setup KMW manually, once ACR events are detected. CTA should open selection panel

FIgma design can be found [here](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1965-16637&node-type=frame&t=Jv59rveRss6eCqpE-0)

Refer to the [Subtle banner notification for detected events](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.4vc3htg11p6z) section of the design doc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Following the implementation in [9371](https://github.com/google/site-kit-wp/issues/9371) `ConversionReportingSettingsSubtleNotification` component is updated to show/surface:
  * If key metrics were setup using manual selection 
  * And initial set of conversion events have been detected
* Said component should match the [figma design](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1965-16637&node-type=frame&t=Jv59rveRss6eCqpE-0)
* Clicking the `Maybe later` CTA should dismiss the banner
* Clicking the `Select metrics` CTA should open the selection panel
* Check the [Subtle banner notification for detected events](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.4vc3htg11p6z) section of the design doc

## Implementation Brief

* [x] Update `ConversionReportingNotificationCTAWidget` component
  * Banner should render if:
    * `isUserInputCompleted` selector from `CORE_USER` store is `false`
    * And `isKeyMetricsSetupCompleted` is `true`
    * And `getDetectedEvents` Analytics setting value is not an empty array 
    * Following above conditions, include the CTA variation/callback:
      * `Maybe later` CTA callback should behave in a same way as implementation in [9371](https://github.com/google/site-kit-wp/issues/9371)
      * `Select metrics` CTA callback should open Selection panel https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/components/KeyMetrics/ChangeMetricsLink.js#L48
* [x] In `ConversionReportingSettingsSubtleNotification` component 
  * Include two props: `ctaLabel` and `ctaCallback` 
  * Apply `ctaLabel` and `ctaCallback` to the primary button, and move existing `Add metrics` label and it's callback to the `ConversionReportingNotificationCTAWidget` to be used as a props for `ConversionReportingSettingsSubtleNotification` component following the initial conditions used for that banner variation.

### Test Coverage

* Update tests for `ConversionReportingNotificationCTAWidget` (basic coverage added in [9344](https://github.com/google/site-kit-wp/issues/9344)), to verify that banner is showing when conditions are met, and not showing otherwise for example. Also tests for new CTA's variation and their callbacks

## QA Brief

* Enable the `conversionReporting` feature flag and setup site kit with the Analytics module enabled.
* Use the tweak Chrome extension to return `true` for a `POST` request to `.*/wp-json/google-site-kit/v1/modules/analytics-4/data/clear-conversion-reporting-new-events?.*`.
* **Scenario 1:**
   * Set up Key Metrics without going through the user input questionnaire, to do this click on the `
Select your own metrics` link in the key metrics setup CTA, then select metrics.
   * Trigger detection of a new events such as `add_to_cart`.
   * The banner *should* render.
* **Scenario 2:**
   * Follow the step from Scenario 1.
   * Setup the key metrics, and select *some* of the metrics [which the ACR work would add](https://github.com/google/site-kit-wp/blob/19b37bcf2e67b9e4a4f86c7d001b8dd94af1814b/assets/js/modules/analytics-4/datastore/conversion-reporting.js#L278-L296), in this case there are no new metrics to add.
   * Trigger detection of a new events such as `add_to_cart`.
   * The banner *should* render.
* **Scenario 3:**
   * Follow the step from Scenario 1.
   * Setup the key metrics, and select *all* metrics [which the ACR work would add](https://github.com/google/site-kit-wp/blob/19b37bcf2e67b9e4a4f86c7d001b8dd94af1814b/assets/js/modules/analytics-4/datastore/conversion-reporting.js#L278-L296), in this case there are no new metrics to add.
   * Trigger detection of a new events such as `add_to_cart`.
   * The banner should *not* render.

* *Testing the banner:**
   * The above scenarios will render the "Select metrics" variant of the banner (Rather than the Add metrics variant created in #9371) above the Key Metrics section on the dashboard.
      * Clicking "Select metrics" should open the key metrics selector panel and dismiss the banner.
      * Clicking "Maybe later" will dismiss the banner.

*Note:* You can also trigger detected events by dispatching the following actions from the developer console:
```
await googlesitekit.data.dispatch('modules/analytics-4').setDetectedEvents(['add_to_cart']) 
await googlesitekit.data.dispatch('modules/analytics-4').receiveConversionReportingInlineData({newEvents: ['add_to_cart'], lostEvents: []})
```

## Changelog entry

* Ensure Analytics Conversion Reports notification appears for users who set up Key Metrics manually.

**Comment by 10upsimon** [comment]
@zutigrm AC ✅ Moving to IB

**Comment by eugene-manuilov** [comment]
Thanks, @zutigrm, mostly looks good to me.

> * Ensure that conditions apply only when component is shown outside of `VIEW_CONTEXT_SETTINGS` context

Which conditions? The ones from the next point? Plus instead of using negative statement we should explicitly say for which context it should be displayed. In other words, instead of `component is shown outside of ... context`, we should say `component is shown in A, B, C, D context`.

**Comment by zutigrm** [comment]
Thanks @eugene-manuilov I updated IB to list the contexts

> Which conditions? The ones from the next point?

I expanded on this sentence to clarify that it should apply for conditions in next points

**Comment by eugene-manuilov** [comment]
@zutigrm ok, since we updated #9371, we need to update IB for this ticket as well. Instead of adding conditions to the notification component, we need to update the widget to render different notifications based on aforementioned conditions. I think we can probably re-use the notification component from #9371 because it has similar content, right?

**Comment by zutigrm** [comment]
@eugene-manuilov Thanks, updated.

> I think we can probably re-use the notification component from https://github.com/google/site-kit-wp/issues/9371 because it has similar content, right?

Yes that's the idea, that component will be reused and just conditions would be expanded

**Comment by zutigrm** [comment]
@eugene-manuilov THanks, IB updated

**Comment by eugene-manuilov** [comment]
Thanks, IB ✔

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 
Hi @benbowler , referring to the QAB where it mentions about setting up the Tweak extension.
I am not 100% clear on its usage and when is it being triggered. Can you clarify on that?
Also, what are the data to be filled for the response payload, request payload and status code?

<Details>

![Image](https://github.com/user-attachments/assets/c8408b0e-fbc0-46dd-85c0-1e0554e054ce)

</Details>

**Comment by zutigrm** [comment]
@kelvinballoo To chip in here, since you have the tester plugin I sent you, you won't need to use tweak, surfacing the callout by forcing the events will suffice, since once you click on it it will be dismissed without usage of extensions

**Comment by kelvinballoo** [comment]
### QA Update ⚠  

**ITEM 1:** ⚠ 
When clicking on 'Maybe Later' (Dismiss), the banner will disappear as expected.
However, after reloading the page, the banner reappears. Is it because of the tester plugin functionality? Or we need to build a logic that after it's dismissed, it won't re-appear again? 

Similarly when we click on 'Select metrics', the banner will disappear. However, after reloading the page, it will re-appear.

Unless these will be tackled under a separate ticket?

<Details>
Dismiss button:

https://github.com/user-attachments/assets/b569a6f8-1665-4e86-a56e-c92d52608fdb

Select metrics scenario:

https://github.com/user-attachments/assets/efeb640e-7913-48af-a3f2-d960310372fa


</Details>

_____________________________________________________________________________________


**ITEM 2:** ⚠ 
The margin above the banner is supposed to be 12px based on Figma.
In our implementation, it's 24px.

<Details>
Figma:

![Image](https://github.com/user-attachments/assets/0a834dc7-a145-423f-b467-4d53ce8b6de5)

Implementation:

![Image](https://github.com/user-attachments/assets/78ed70f0-fc68-4834-b9e3-ee2b898bcbff)

</Details>

_____________________________________________________________________________________

**ITEM 3:** ⚠ 
Let's say we have the following scenario: 
- Some metrics are not selected. The banner will appear.
- All the metrics related to the particular event are now checked.
- The banner disappears accordingly.
- The thing now is that if I uncheck one of the metrics, the banner will resurface again. 
I assume that's not expected. Are we handling this in a separate ticket?

<Details>

https://github.com/user-attachments/assets/3be67366-facc-428b-a931-c0bf9664c148

</Details>



_____________________________________________________________________________________

Tested the following and they were as expected: ✅ 
- Scenario 1 - Select metrics banner appears accordingly
   <Details>

   https://github.com/user-attachments/assets/3b478e5a-10c6-4f34-a67c-89413c3d280e

   </Details>

- When clicking on Select metrics, the panel selection will appear accordingly.
   
   <Details>

   https://github.com/user-attachments/assets/a66e8945-77a7-4ecf-a664-fb0343838a31

   </Details>

- Scenario 2 - The banner appears again when not all the metrics were selected.

   <Details>
   
   https://github.com/user-attachments/assets/3c6fc5f3-7b25-4573-9bcc-0fb95c612186


   </Details>

- Scenario 3 - If all the relevant metrics are selected, the banner will not appear.
   <Details>

   https://github.com/user-attachments/assets/7c2c99e8-c516-4b8f-ae7b-1cc4769c8550

   </Details>

- Tested other scenarios pertaining to purchases and leads (contact, generate lead, submit lead form).
   Behaviours are similar as above.

   <Details>

   https://github.com/user-attachments/assets/1c2ff58a-0eaf-429d-bf48-baacb4efcebe

   https://github.com/user-attachments/assets/ce457962-568b-4390-b9ac-1362a49a2830

   </Details>

**Comment by zutigrm** [comment]
@kelvinballoo thinking more about item 3, it is better if we dismiss the banner, since even after several days, or week + if user deselect the item, banner will re-appear if not dismissed, which would be a bit confusing. We will have new badges appearing next to the metrics, but still yeah, let's dismiss this.

@benbowler We can update https://github.com/google/site-kit-wp/blob/548bf6b5e11b200b4928fe0eeab5ed4f35c478e2/assets/js/components/KeyMetrics/MetricsSelectionPanel/Footer.js#L144 callback to run same check we use for banner to appear, and if it is false and there are `newEvents`, invoke the dismissal action

**Comment by zutigrm** [comment]
@kelvinballoo After checking the item 2, we have unified margin on all widget area headers which is 24px. For consistency doesn't seem like something we should change, in the Figma, spacing differs only for this scenario of notification showing, and by default without notification it seems to be mistakenly reduced in Figma. We can omit this one from changing.

I have opened a follow up issue (#9870) for item 3 since it is not scoped as part of this issue which only works on adding the callout variation, and so we can properly define this new change.
