### ISSUE TITLE
Add new resolver to the conversion reporting datastore partial to retrieve detected and lost events from inline module data

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9379]
## Feature Description

Conversion reporting datastore partial should be updated to include new resolver which would retrieve detected and lost events from inline module data (implemented in #9342), and pass them to an action which should receive passed data and store them to the state.

See [Implementation - Datastore Partial ](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.7e6inft5e4wy) section of the design doc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* New resolver `getConversionReportingEventsChange` is added to the `conversion-reporting` datastore partial
  * It retrieves inline data implemented in #9342
  * It passes the new and lost events as an object to the `receiveConversionReportingInlineData` action
* New action `receiveConversionReportingInlineData` is implemented, which yields passed object to the reducer
  * Reducer should store this data in the state under `detectedEventsChange` property
* New selectors `hasNewConversionReportingEvents` and `hasLostConversionReportingEvents` are added
  * They should extract their respective events from `detectedEventsChange` state property by using `getConversionReportingEventsChange` selector

## Implementation Brief

* [ ] Update `assets/js/modules/analytics-4/datastore/conversion-reporting.js` 
  * Add the initial state object, containing `detectedEventsChange`, `undefined` by default
  *  Add `getConversionReportingEventsChange` resolver
    * Retrieve the values from `newEvents` and `lostEvents` from Analytics inline module data like `global._googlesitekitModulesData?.[ 'analytics-4' ]?.newEvents`, etc.
    * Group them under one object and pass it to the `receiveConversionReportingInlineData` action
    * You can check an example in `assets/js/googlesitekit/datastore/site/info.js`, or any other datastore partial resolving inline data.
  * Add `receiveConversionReportingInlineData` action
    *  It should extract `newEvents` and `lostEvents` from the passed argument, and yield them as an object to the reducer. Then in the reducer, update `detectedEventsChange` object in the state to hold `newEvents` and `lostEvents` as properties
  *  Add `getConversionReportingEventsChange` selector
      * It should return value from the state `state.detectedEventsChange`
  * Include `hasNewConversionReportingEvents` and `hasLostConversionReportingEvents` selectors
    * They should use `getConversionReportingEventsChange` selector to retrieve the inline data (or resolve it if not yet available), and then extract their respective properties from the returned value. You can add a helper function to extract the correct property, like for example, how it is used in `info` datastore https://github.com/google/site-kit-wp/blob/d0f81d38c89d89c1b0d39e861a56ca67d40c238f/assets/js/googlesitekit/datastore/site/info.js#L38-L43 and then invoke it here in each selector passing either `newEvents` or `lostEvents` for the argument

### Test Coverage

* Update `assets/js/modules/analytics-4/datastore/conversion-reporting.test.js` to include test coverage for new resolver, action and selectors

## QA Brief

* Setup Site Kit with Analytics module and `conversionReporting` feature flag enabled
* Paste this snippet in the console `await googlesitekit.data.select('modules/analytics-4').getConversionReportingEventsChange()`
  * Initially it will output `undefined`
  * On the second attempt it will resolve the data and output `{newEvents: Array(0), lostEvents: Array(0)}`
  * Note: when feature flag is disabled, this selector will still be accessible but will return `undefined` for both `newEvents` and `lostEvents`
* Paste this snippet in the console `await googlesitekit.data.select('modules/analytics-4').hasNewConversionReportingEvents()`
  * Same as above, firs call will output `undefined`, afterwards should show `false`
  * Also same applies regarding the feature flag, when disabled selector will still work, but always return `undefined` value
* Paste the snippet `await googlesitekit.data.select('modules/analytics-4').hasLostConversionReportingEvents()`
  * It should behave same as `await googlesitekit.data.select('modules/analytics-4').hasNewConversionReportingEvents()` above
* Paste this snippet: `await googlesitekit.data.dispatch('modules/analytics-4').receiveConversionReportingInlineData({newEvents: ['contact'], lostEvents: ['purchase']})`
  * Then afterwards, without reloading, test the previous three snippets:
    * `await googlesitekit.data.select('modules/analytics-4').getConversionReportingEventsChange()` should return whole object passed above: `{lostEvents: ['purchase'], newEvents: ['contact']}`
    * `await googlesitekit.data.select('modules/analytics-4').hasNewConversionReportingEvents()` should return `true`
    * `await googlesitekit.data.select('modules/analytics-4').hasLostConversionReportingEvents()` should return `true`

## Changelog entry

* Add support for lost events to Conversion Reporting events datastore.

**Comment by eugene-manuilov** [comment]
AC ✔️

**Comment by 10upsimon** [comment]
@zutigrm IB ✅ , moving to EB.

**Comment by tofumatt** [comment]
Assigning this to myself to get this moved through and unblock other issues 🙂

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 

Going through the QAB, I have a couple of things to highlight:

**ITEM 1:**
- Pasted the snippet 
   `await googlesitekit.data.select('modules/analytics-4').hasNewConversionReportingEvents()`
   
   First call outputs undefined, afterwards we are expecting it to show empty array []
   However, instead of showing empty array, it's returning as 'False' ❌  
   <Details>

   ![Image](https://github.com/user-attachments/assets/3bc0d04d-4f28-4788-ab8d-00acc88877fd)

   When feature flag is off, it always returned undefined value, this is expected.
   ![Image](https://github.com/user-attachments/assets/f2afc321-f1f7-4528-9ea1-4e9412b60742)

   </Details>

___________________________________________________________________________

**ITEM 2:**
- Pasted the snippet 
  ` await googlesitekit.data.select('modules/analytics-4').hasLostConversionReportingEvents()`
   
   We are expecting it to behave the same as It should behave same as .hasNewConversionReportingEvents() above.
   Indeed, it behaves the same but given that it returns false instead of empty array, this needs to be double-checked. ⚠ 
   <Details>

   ![Image](https://github.com/user-attachments/assets/a7ef98e7-be91-455c-9507-963d376f4fb5)
   
   When feature flag is off, it always returned undefined value. This is expected. 
   ![Image](https://github.com/user-attachments/assets/4e7741bf-2e0c-4670-aa92-fe2ee8e7c057)

   </Details>


___________________________________________________________________________

**ITEM 3:**
- Pasted the snippet: 
 `  await googlesitekit.data.dispatch('modules/analytics-4').receiveConversionReportingInlineData({newEvents: ['contact'], lostEvents: ['purchase']})`
Then afterwards, without reloading, I tested the 3 snippets:
   - getConversionReportingEventsChange() - returns whole object passed above: {lostEvents: ['purchase'], newEvents: ['contact']} ✅ 
   - hasNewConversionReportingEvents() - we are expecting it to return only newEvents value, in this case ['contact'] but it's returning as 'true' ❌ 
   - hasLostConversionReportingEvents()- we are expecting it to return only lostEvents value, in this case: ['purchase'] but it's returning as 'true' ❌ 

      <Details>

      ![Image](https://github.com/user-attachments/assets/cbf3feae-3a91-4752-afda-41a2ce7e94d6)

      </Details>


______________________________________________________________________________

Other than that .getConversionReportingEventsChange() worked well:

- Pasted the snippet
   `await googlesitekit.data.select('modules/analytics-4').getConversionReportingEventsChange()`
   Initially, it outputs undefined ✅ 
   On the second attempt, it will resolve the data and outputs {newEvents: Array(0), lostEvents: Array(0)}

   <Details>

   ![Image](https://github.com/user-attachments/assets/cfd08889-105c-4f8b-9a63-d3dedc3ce8c3)

   </Details>

   When feature flag is disabled, returns undefined for both newEvents and lostEvents
   <Details>

   ![Image](https://github.com/user-attachments/assets/2555134e-18cd-4bb7-b857-41a8bf7aa56d)

   </Details>

**Comment by zutigrm** [comment]
@kelvinballoo Thanks for you observations. Sorry about that, I update QAB now, we changed in the last CR round, what you see is correct output, `hasNewConversionReportingEvents` and `hasLostConversionReportingEvents` return `true`, or `false`, or `undefined`, they will not return arrays any more

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks @zutigrm , going through the new QAB, everything is checking out.
Moving ticket to **Approval.**

- getConversionReportingEventsChange() worked well:

   - Pasted the snippet
   `await googlesitekit.data.select('modules/analytics-4').getConversionReportingEventsChange()`
   Initially, it outputs undefined ✅ 
      On the second attempt, it will resolve the data and outputs {newEvents: Array(0), lostEvents: Array(0)} ✅

      <Details>
 
      ![Image](https://github.com/user-attachments/assets/cfd08889-105c-4f8b-9a63-d3dedc3ce8c3)

      </Details>

      When feature flag is disabled, returns undefined for both newEvents and lostEvents
      <Details>

      ![Image](https://github.com/user-attachments/assets/2555134e-18cd-4bb7-b857-41a8bf7aa56d)

      </Details>

___________________________________________________________________________


- hasNewConversionReportingEvents() worked well:
   - Pasted the snippet 
     `await googlesitekit.data.select('modules/analytics-4').hasNewConversionReportingEvents()`
   
      First call outputs undefined, afterwards it returns 'False' ✅ 
      When feature flag is off, it always returned undefined value, this is expected. ✅
      <Details>

      ![Image](https://github.com/user-attachments/assets/3bc0d04d-4f28-4788-ab8d-00acc88877fd)

      When feature flag is off, it always returned undefined value, this is expected.
      ![Image](https://github.com/user-attachments/assets/f2afc321-f1f7-4528-9ea1-4e9412b60742)

      </Details>

___________________________________________________________________________

- hasLostConversionReportingEvents() worked well:
   - Pasted the snippet 
     ` await googlesitekit.data.select('modules/analytics-4').hasLostConversionReportingEvents()`
   
      We are expecting it to behave the same as .hasNewConversionReportingEvents() above.
      Indeed, it behaves the same. First call is undefined, followed by 'False' ✅ 
      When feature flag is off, it always returned undefined value. ✅ 
      <Details>

      ![Image](https://github.com/user-attachments/assets/a7ef98e7-be91-455c-9507-963d376f4fb5)
   
      When feature flag is off, it always returned undefined value. This is expected. 
      ![Image](https://github.com/user-attachments/assets/4e7741bf-2e0c-4670-aa92-fe2ee8e7c057)

      </Details>


___________________________________________________________________________

- .receiveConversionReportingInlineData worked well:
   - Pasted the snippet: 
    `  await googlesitekit.data.dispatch('modules/analytics-4').receiveConversionReportingInlineData({newEvents: ['contact'], lostEvents: ['purchase']})`
Then afterwards, without reloading, I tested the 3 snippets:
      - getConversionReportingEventsChange() - returns whole object passed above: {lostEvents: ['purchase'], newEvents: ['contact']} ✅ 
      - hasNewConversionReportingEvents() - returns as true ✅ 
      - hasLostConversionReportingEvents()- returns as true ✅

      <Details>

      ![Image](https://github.com/user-attachments/assets/cbf3feae-3a91-4752-afda-41a2ce7e94d6)

      </Details>
