### ISSUE TITLE
Ads PAX Beta - Update Initial Ads Setup Screen, Remove Manual AW-ID Input & Auto Trigger PAX Application

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#9426]
## Feature Description

For users enrolled in the Beta phase of the Ads PAX integration (those using the mini plugin), the Ads module setup flow should disallow for manual AW-ID input and enter immediately (and automatically) into the PAX application setup flow, simulating the current scenario where a user (with the `adsPAX` feature enabled) would click the "Create an account" CTA button.

![Site Kit by Google Dashboard ‹ sitekit 10uplabs com — WordPress 2024-09-27 at 11 20 36 AM](https://github.com/user-attachments/assets/c305976d-6a12-4bd1-b70c-58cb9f00c1dd)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For users enrolled in the Beta phase of the Ads PAX integration (those making use of the mini plugin):
    * The ability to manually input an AW-ID should be removed, and the entire settings field along with its label and the preceding instructional paragraph should be removed. 
    * The PAX application flow should be triggered automatically on the initial setup screen of the Ads module, not via the existing "Create an account" CTA, therefore this CTA should be removed, along with the "additional permissions text", essentially taking the user to the OAuth flow immediately (or triggering the PAX app if the oAuth role is already granted)
* Both of these changes should only be effected when the `adsPAX` feature flag is enabled

## Implementation Brief

* [x] Within the file at `assets/js/modules/ads/components/setup/SetupMainPAX.js`
    * [x] Add `ProgressBar` to the import statement for `'googlesitekit-components'`, this will represent a loading state for cases where the oAuth scope is not yet granted and the background processes are preparing for redirect
    * [x] Import `useFeature` from `hooks/useFeature` in order to conditionally perform actions based on the presence of the `adsPAX` feature flag
    * [x] Before the return statement of the component itself, defined a const that checks for the presence of the `adsPAX` feature flag, i.e `const isAdsPaxEnabled = useFeature( 'adsPax' );`
    * [x] Following the above, implement a `useEffect` hook as the last item before the return statement, after the above.
    * [x] Define the `useEffect` hook deps as `[ isAdsPaxEnabled, createAccount ]`
    * [x] Within the function body of the `useEffect` hook:
        * [x] If `isAdsPaxEnabled` is truthy, execute/call the `createAccount()` function, this will simulate the scenario of a user clicking the `Create an account` CTA
    * [x] Immediately after the implementation of the `AdBlockerWarning` component line:
        * [x] Conditionally render an instance of the `ProgressBar` component `isAdsPaxEnabled && ! showPaxAppStep`, we do not want the progress bar to render when the PAX app is expected to load, it has it's own loading state wrapper
        * [x] Change the conditional checks around the rendering of the `<Fragment>` containing the manual ID input controls to only render if `! isAdsPaxEnabled`, this will remove said input controls (and surrounding markup) for PAX beta users

### Test Coverage

* No test updates are required.

## QA Brief

* **Enable** the `adsPAX` feature flag.
  * Go to the "Connect more services" tab of the settings.
  * Click on the "Setup Ads CTA" - instead of seeing the settings screen to add and Ads Conversion ID you will immediately be sent to the OAuth flow.
* **Disable** the `adsPAX` feature flag.
  * Go to the "Connect more services" tab of the settings.
  * Click on the "Setup Ads CTA" - confirm you can still save your Ads Conversion ID to setup the Ads module.

## Changelog entry

* Disallow manual Ads Conversion ID entry when using the Partner Ads Experience.

**Comment by 10upsimon** [comment]
> Let's clarify what exactly should happen

@zutigrm it should disappear entirely, I will clarify.

**Comment by zutigrm** [comment]
Thanks @10upsimon AC ✅

**Comment by tofumatt** [comment]
IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 

Hi @benbowler , this is working fine overall. One scenario to confirm :
- Let's say a user doesn't have the feature enabled and he keys in and saves the AW ID. 
- If the featured is then enabled, the AW ID that he keyed in will remain. There won't be any oAuth flow.
- This will remain until the person disconnects the Ads module and reconnects it. Only then there will be an oAuth flow.
To me this is the correct flow and it's working as expected. Just wanting to double confirm.

The following were verified good ✅ :
- When we enable the adsPAX feature flag and click on the "Setup Ads CTA" - instead of seeing the settings screen to add and Ads Conversion ID we are directly sent to the OAuth flow. Going through the flow until the end, the AW ID is properly displayed at the module screen. There is no manual input for AW-ID or CTA to 'Create an account'
   <Details>

   https://github.com/user-attachments/assets/971d8838-bc99-4930-a7f9-ba41222c7845

   </Details>

- When we disable the adsPAX feature flag and click on the "Setup Ads CTA", we can key in and save an Ads Conversion ID to setup the Ads module.

   <Details>

   https://github.com/user-attachments/assets/cd4c36fc-bbcc-4991-a8ae-c45a585b2315

   </Details>

**Comment by benbowler** [comment]
Hey @kelvinballoo, the flow you mentioned is expected. As participants in the PAX pilot are guided through the setup process, I believe this flow is appropriate as most users will be enabling for the first time or can be guided to disconnect and reconnect after installing the pilot plugin.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks for the confirmation @benbowler .
This is good to move to Approval.

The following were verified good ✅ :
- When we enable the adsPAX feature flag and click on the "Setup Ads CTA" - instead of seeing the settings screen to add and Ads Conversion ID we are directly sent to the OAuth flow. Going through the flow until the end, the AW ID is properly displayed at the module screen. There is no manual input for AW-ID or CTA to 'Create an account'
   <Details>

   https://github.com/user-attachments/assets/971d8838-bc99-4930-a7f9-ba41222c7845

   </Details>

- When we disable the adsPAX feature flag and click on the "Setup Ads CTA", we can key in and save an Ads Conversion ID to setup the Ads module.

   <Details>

   https://github.com/user-attachments/assets/cd4c36fc-bbcc-4991-a8ae-c45a585b2315

   </Details>
