### ISSUE TITLE
Introduce new `googlesitekit.api` layer for datapoint access with caching

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#953]
## Feature Description

This issue is the overarching issue for tracking #570, #571, and #572.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `googlesitekit-api` script should be registered in WordPress that, when enqueued, exposes a `googlesitekit.api` layer.
* See individual issues for more details.

## Implementation Brief

* N/A

## Changelog entry

* Introduce new `googlesitekit.api` layer for accessing Site Kit datapoints with reliable caching.

**Comment by tofumatt** [comment]
This is in the TODO column and assigned despite having no implantation brief. I’m guessing this happened by mistake so I’m moving this back to IB 😅

**Comment by tofumatt** [comment]
Oh, sorry, I guess maybe as a tracking issue we don’t want to do that. I’ll leave it here, I guess it’s just a bit of an outlier issue 😁

**Comment by felixarntz** [comment]
@tofumatt Can you open a PR to merge `js-refactor` into `develop` for this one?

**Comment by aaemnnosttv** [comment]
## QA

✅ Adds `googlesitekit.api` when enqueued.

![image](https://user-images.githubusercontent.com/1621608/72416548-98135700-377f-11ea-846f-eaf5a757ced0.png)

⚠️ The script handle of `googlesitekit-api` is inconsistent with the rest of our scripts, which use snake case rather than kabob case. The exception here are `sitekit-` scripts but we should standardize on one convention for all of them unless there is some reason why they should be different. The current handle is consistent with the AC for this issue though.
