### ISSUE TITLE
Add lost events banner variation

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9578]
## Feature Description

When events are lost - not detected in the last 90 days CRON sync, a banner should be surfaced to notify users that some data has not been detected for a long time.

[Figma designs](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2493-13432&node-type=frame&t=vQeH1P2OKGqFJqeG-0)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When lost events are detected, new banner variation should appear in the KMW section matching the [Figma designs](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2493-13432&node-type=frame&t=vQeH1P2OKGqFJqeG-0)
  * Lost event(s) should match the currently selected KMW, if there is no KMW associated with the lost event(s) currently on the dashboard, banner shouldn't be shown 
* If new events detected banner is showing ([9371](https://github.com/google/site-kit-wp/issues/9371)), lost events banner should appear above it, they shouldn't be mutually exclusive
* Clicking on `Got it` CTA should dismiss the banner
* Clicking `Select metrics` CTA should open KM selection panel

## Implementation Brief

* [ ] Add `assets/js/components/KeyMetrics/LostEventsSubtleNotification.js`
  * Use `ACRDashboardSubtleNotification` (implemented in [9371](https://github.com/google/site-kit-wp/issues/9371)) as a starting point
  * It should accept `onDismissCallback` and `onSelectMetricsCallback` props
  * Replace the icon, background color and content matching the [Figma designs](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2493-13432&node-type=frame&t=vQeH1P2OKGqFJqeG-0)) 
  * Include the `Got it` CTA, and on click invoke `onDismissCallback` prop
  * Include `Select metrics` CTA and invoke  `onSelectMetricsCallback` callback
* [ ] Update `assets/js/components/KeyMetrics/ACRNotificationCTAWidget.js`
  *  Check if there are lost events detected using `hasLostConversionReportingEvents` selector from Analytics module datastore
      * Then conditionally render `LostEventsSubtleNotification` above the `ACRDashboardSubtleNotification`
  * Include `onDismissLostEvents` callback function, and dispatch `dismissLostConversionReportingEvents` action from analytics datastore. Pass it as `onDismissCallback` prop of `LostEventsSubtleNotification`
  * Include `onSelectMetrics` callback function - if not included already by another banner issue - that should open the selection panel https://github.com/google/site-kit-wp/blob/79b4417581b1cca3d718f7e55127681e6e05fc6f/assets/js/components/KeyMetrics/ChangeMetricsLink.js#L48 and dismiss the banner, using `onDismissLostEvents`
    * Pass it as `onSelectMetricsCallback` prop of `LostEventsSubtleNotification`
* Tailored metrics with lost events - not present in `detectedEvents` GA4 setting, should remain visible on dashboard when lost, only banner should be surfaced. For this purpose include new setting to the analytics module - `historicallyDetectedEvents` and store all detected events here, by appending them in array, unline `detectedEvents` that is set every time when sync happens 

### Test Coverage

* Update tests for ACRNotificationCTAWidget (basic coverage added in [9344](https://github.com/google/site-kit-wp/issues/9344)), to verify that banner is showing when conditions are met, and not showing otherwise for example. Also test for new CTA's variation and verifying that it updates the UI state which will trigger the opening of selection panel, etc.

## QA Brief

* Setup Site Kit with Analytics module
* Setup metrics (tailored or manually) with ACR events detected (contact @zutigrm for under the counter tester plugin since it is not released yet). 
* Then force lost event, through plugin or simply using this snippet `await googlesitekit.data.dispatch('modules/analytics-4').receiveConversionReportingInlineData({newEvents: [], lostEvents: ['CONVERSION_EVENT_NAME']})`
  * Force `contact` event as detected
  * For example setup KMW using tailored metrics with `publish_blog` site purpose as an answer
  * On the dashboard force `contact` as lost event, verify banner is showing
* For manual selection, you can include single ACR metric, like any of the `* driving leads` metric and use the same approach as above, force `contact` event using plugin or snippet, and verify banner is showing

## Changelog entry

* Add notification banner when event data has been missing for ninety days.

**Comment by 10upsimon** [comment]
@zutigrm AC ✅  Moving to IB.

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue?

**Comment by 10upsimon** [comment]
@zutigrm this LGTM, moving to EB.

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 

Hi @zutigrm , I am using the tester plugin you sent me on 27 November but I can't get the lost event banner to show up. I also tried the script.

Need your guidance on this one.

Refer to the attached video.

<Details>

https://github.com/user-attachments/assets/266e94dd-e47b-4a3d-ba7d-0c4d5dc51722

</Details>

**Comment by zutigrm** [comment]
Hi @kelvinballoo , to be able to see the banner, you need to have metrics for that events previously in use. So for tailored metrics - setting tailored metrics force detection of `contact` event in this case. Metrics will be setup with leads metrics included, afterwards, force the lost events using same event - `contact`, then banner will appear

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 

Hi @zutigrm , I tried to force the new events by enforcing contact for 
**Force Analytics detected events** and **Analytics detected new events**.
Actually after setting up SK and the tailored metrics, I was already getting the lost event banner.
I was not expecting that.

Also, there is an issue whereby there is a white space with a '0' below the banner.
Details are attached.

<Details>
white space with a '0' just below the banner:

![Image](https://github.com/user-attachments/assets/e7128d05-8f0e-458e-b363-39a33435f8cd)

Video of setup:

https://github.com/user-attachments/assets/d99828e9-b608-421d-adf7-112d7133c0df


</Details>

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 

Here are some observations:

**ITEM 1:**
Hi @zutigrm , I managed to go through the steps you outlined in the video through slack.
I understand how to use the tester plugin now and the banner showed up.

However, similar to my previous comment,  there is an issue whereby there is a white space with a '0' below the banner.
Details are attached.

<Details>

![Image](https://github.com/user-attachments/assets/5483014f-2e08-4b79-8f79-8f2532b8f6ea)


https://github.com/user-attachments/assets/1b7b4910-20cb-48c6-ae53-23ef5272c2ea


</Details>

_____________________________________________________________________________

**ITEM 2:**
The colour of the 'i' icon is not the same when compared to Figma.

<Details>

Figma: It's brownish

![Image](https://github.com/user-attachments/assets/f0b56fc8-e47a-4859-8f24-bd17871c9fa9)

Implementation: It looks more black.

![Image](https://github.com/user-attachments/assets/9f775dd3-7763-4c8b-bf7f-582ab4acca8c)

</Details>

_____________________________________________________________________________

**ITEM 3:**
I did the scenario where there are new metrics + lost of old metrics.
Both banners appear but it looks weird.
- The banners stick to each other
- There is a white space at the corners

<Details>

![Image](https://github.com/user-attachments/assets/449605aa-7d62-4331-8d08-0f5bb4773f29)

https://github.com/user-attachments/assets/cf090e1d-ee14-44ba-aea2-dc4fa820858d

</Details>

_____________________________________________________________________________

**ITEM 4:**
This is more of a confirmation needed.
For manual selection, am I right to say that there would be no checking of the ACR being associated with a 'Site purpose', because the user doesn't select it, unlike when getting tailored metrics. 

Can you confirm?

_____________________________________________________________________________

Other than that, the following were verified good ✅ 
- If there is no KMW associated with the lost event(s) currently on the dashboard, banner isn't be shown.
   <Details>

   https://github.com/user-attachments/assets/ef4fff7b-31d1-4689-8288-f778ff4146e2

   </Details>

- Clicking on Got it CTA dismisses the banner
   <Details>
   
   https://github.com/user-attachments/assets/cf090e1d-ee14-44ba-aea2-dc4fa820858d

   </Details>

- Clicking Select metrics CTA opens KM selection panel

   <Details>

   https://github.com/user-attachments/assets/ce2818d1-a1d9-438b-a6b6-7dbd6d99e182

   </Details>

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks @zutigrm .
Noted on ITEM 4.
I'll test ITEM 1 and 3 under https://github.com/google/site-kit-wp/issues/9373.

**ITEM 2** was verified good. The icon colour is now as expected.
<Details>

![Image](https://github.com/user-attachments/assets/dde8c109-92eb-4d41-8dd9-7625745e4321)

</Details>

____________________________________________________________

Other items were verified good ✅ :
- If there is no KMW associated with the lost event(s) currently on the dashboard, banner isn't be shown.
   <Details>

   https://github.com/user-attachments/assets/ef4fff7b-31d1-4689-8288-f778ff4146e2

   </Details>

- Clicking on Got it CTA dismisses the banner
   <Details>
   
   https://github.com/user-attachments/assets/cf090e1d-ee14-44ba-aea2-dc4fa820858d

   </Details>

- Clicking Select metrics CTA opens KM selection panel

   <Details>

   https://github.com/user-attachments/assets/ce2818d1-a1d9-438b-a6b6-7dbd6d99e182

   </Details>
