### ISSUE TITLE
After change any Service settings, it should clear sessionStorage

### ISSUE THREAD

**Issue by ivankristianto** [google/site-kit-wp#96]
## Bug Description

After change any service settings from the Site Kit admin settings, it still show the old data from the cache

## Steps to reproduce

1. Go to Site Kit admin settings
2. Change Analytics property and profile
3. Go back to Site Kit dashboard screen
4. It still show the old data

## Expected behavior
It should fetch the latest/new data based on the new settings.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* Clear session storage after modifying module settings to prevent outdated cache responses.

## Acceptance criteria

* Main dashboard and product subreports should show data related to the relevant account/property immediately after the user makes changes in the settings. 

## Implementation Brief

`SettingsModules` component handle the confirm button action in `handleButtonAction`.
When success (no error thrown), call `clearAppLocalStorage()` function to clear local and session storage.

**Comment by ivankristianto** [comment]
## Implementation Brief

`SettingsModules` component handle the confirm button action in `handleButtonAction`.
When success (no error thrown), call `clearAppLocalStorage()` function to clear local and session storage.

**Comment by felixarntz** [comment]
Implementation brief looks good!

**Comment by adamsilverstein** [comment]
Note: I tested this on commit `a5e335a3b23f7a4342829988be9fcab279880dd2` (after the merge) since currently develop settings editing isn't working correctly. 

Worked well in my testing, moving to the "Approval" column.

### Testing steps
* Configure Analytics & visit Dashboard
* open chrome debug console->Application->Local Storage - verifying browser storage cache of all dashboard data
* go to Settings and edit the analytics module configuration
* change any settings value and save (testing with multiple views on the same domain easiest)
* note that App session storage has been cleared
* return to dashboard page and validate: new wp-json rest api requests for the analytics data + new data from the changed selection is now showing
