### ISSUE TITLE
Update SiwG "Get your Client ID" link and login URLs

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#9621]
## Feature Description

The "Get your Client ID" URL should be updated to the new SiwG-specific URL for Site Kit.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The URL used for the "Get your Client ID" link button in Sign in with Google setup should be updated to  
`https://developers.google.com/identity/site-kit` with the following URL-encoded parameters:
	- `appname`: The display name of the Google Cloud project: use site title
	- `sitename`: The display name of the site: use site title
	- EDIT ~~`siteurl`: The home URL of the site (front page root): use home URL (not reference URL)~~
	- `siteorigin`: The origin of the site root URL (scheme+hostname only)
	- `supportemail`: The email for support with the app: use the Google address of the user setting up SiwG (i.e. module owner)
* Ensure users are sent to the above "Get your Client ID" URL for project creation using the AccountChooser so that projects are created in the same Google account as the user signed in within Site Kit

## Implementation Brief

* [x] Crate`assets/js/modules/sign-in-with-google/datastore/service.js`
  * Add `getServiceURL` selector
    * Wrap it with `createRegistrySelector` and retrieve following data:
      * `siteName` using `getSiteName` selector from `CORE_SITE` store
      * `homeURL` using `getHomeURL` selector from `CORE_SITE` store
      * `supportEmail` using `getEmail` selector from `CORE_USER` store
    * Define new constant `serviceURL` and assign it value of `https://developers.google.com/identity/site-kit`
    * Construct an object with keys listed in AC and pair them with the data extracted above
    * Construct the URL by passing the above object to the `addQueryArgs` using `serviceURL` as the first parameter, and object as the second
    * Use the resulting URL  as the parameter for the `getAccountChooserURL` selector from `CORE_USER` store, and return the result
* [x] Update `assets/js/modules/sign-in-with-google/components/setup/SetupForm.js`
  *  Use the new `getServiceURL` selector from SiWG module store to retrieve the URL and use it in the `Button` component, replacing the existing `href` URL

### Test Coverage

* Add coverage for new datastore functionality

## QA Brief

* Go to Site Kit Settings and try to set up SiWG. 
* Copy the link of the `Get Client ID URL` button on the form and paste it inside an online URL decoder to check the new params are as per the AC. Note that 2 of the params (siteurl and supportemail) are "double" encoded, i.e. they will still be encoded after decoding once. This is expected.
* Click on the link and check that the auto filled entries on the Sign in with Google GCP app page are all correct and can be used to create a client ID as before.

## Changelog entry

* Update "Get your Client ID" link in Sign in with Google setup.

**Comment by aaemnnosttv** [comment]
Thanks @zutigrm – I actually meant to put this into IBR but no problem. In light of new developments on the external side, I've made an update to the AC. The main change is that we'll no longer be passing a `redirecturi` to the external project provisioning service. See also #9677 which I just opened although I think this issue can happen in parallel since this one is more about changes to the setup.

I've also removed the point about changing the action parameter, as this is already happening/done in https://github.com/google/site-kit-wp/pull/9577/files#diff-5d9448f7515540d9d39cb7f666fd5dc594af902a96aef39a181a6de355263e3aR58

> * Add public static method `get_google_login_url`
I'd suggest calling this `get_auth_url` since the prefix is redundant being on the "SiwG" class :) It also probably doesn't need to be static since it will only be used internally as of #9677

> Update `Google\Site_Kit\Core\Assets\Assets::get_inline_base_data`
> * In `$inline_data` add new item to the array: `loginURL`, with value of `Google\Site_Kit\Modules\Sign_In_With_Google::get_google_login_url()`

I don't think this will be necessary now since we'll only need the login endpoint in PHP when rendering the button.

> Add `getLoginEndpointURL` selector
> * Wrap it with `createRegistrySelector` and retrieve following data:
>   
>   * `siteName` using `getSiteName` selector from `CORE_SITE` store* `homeURL` using `getHomeURL` selector from `CORE_SITE` store* `supportEmail` using `getEmail` selector from `CORE_USER` store* `redirecturi` using newly created selector `getLoginURL` from `CORE_SITE` store
> * Define new constant `loginEndpointURL` and assign it value of `https://developers.google.com/identity/site-kit`

There seems to be some confusion here, but at the least, it's confusing to have very similarly named selectors for different things. The login endpoint is what we mean by the URL constructed from `wp_login_url` that login requests will be sent to.  The `developers.google.com/identity/site-kit` based URL is really the SiwG module's "service URL" similar to other modules, so we can follow that pattern here as those all use AccountChooser URLs as well.

All in all, I think it will be substantially smaller to do so the estimate should be able to come down as well.

**Comment by zutigrm** [comment]
@aaemnnosttv Thanks, I update the IB following the feedback and AC change.

> Add public static method get_google_login_url
I'd suggest calling this get_auth_url since the prefix is redundant being on the "SiwG" class :) It also probably doesn't need to be static since it will only be used internally as of https://github.com/google/site-kit-wp/issues/9677

Since we no longer need login URL within the scope of this issue, I removed this part, as it can be done in the referenced issue if needed.

**Comment by aaemnnosttv** [comment]
Thanks @zutigrm 

IB ✅

**Comment by aaemnnosttv** [comment]
@tofumatt @jimmymadon we need to make a very small change to this issue as it isn't worth creating a new one over. I'll tweak the AC accordingly but essentially the only change is as follows

```diff
- siteurl: The home URL of the site (front page root): use home URL (not reference URL)
+ siteorigin: The origin of the site root/home URL
```

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that link of the `Get Client ID URL` button decoded as per AC.
- Verified that the auto filled entries on the Sign in with Google GCP app page are all correct and can be used to create a client ID as before.

<details>


![Image](https://github.com/user-attachments/assets/afa04a9d-2ecd-49fe-a81f-ae3e63ff8a4b)



![Image](https://github.com/user-attachments/assets/fca1a38c-2f8a-4ae6-b4c3-8e7d16776139)

</details>
