### ISSUE TITLE
Raw code being displayed on the front end plugins page after user activates SK for the first time

### ISSUE THREAD

**Issue by cole10up** [google/site-kit-wp#964]
## Bug Description

After user installs and activates Site Kit for the first time, notice on the plugins page the following:

![image](https://user-images.githubusercontent.com/57115907/70576485-e4a2bb80-1b5d-11ea-9dee-19e63b244d0b.png)

## Steps to reproduce

1. Pull latest develop zip from repo (below)
[google-site-kit.zip](https://github.com/google/site-kit-wp/files/3947543/google-site-kit.zip)

2. Start a new Jurassic Ninja instance: https://jurassic.ninja/
3. Upload, install and activate the plugin

## Screenshots

![image](https://user-images.githubusercontent.com/57115907/70576595-2fbcce80-1b5e-11ea-8fba-b27e215a52c5.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should be able to be uploaded, installed and activated properly without raw code being displayed

## Implementation Brief

* Remove `wp_kses_post()` around activation notice content again. This content should be properly escaped in the method where it is generated. For the simple case where that content is just a string, it is already escaped just a few lines above the line in question.

## QA Brief

* Deactivate and reactivate Site Kit.
    * Ensure plugin activation notice contains un-escaped `<script>` in the notice's html
* Uninstall Site Kit and install a pre-1.0 version and perform basic minimal setup (only step 1 - setting credentials - is necessary for testing here)
    * Upgrade to the version from this issue's PR
    * Ensure plugin migration/upgrade notice contains un-escaped `<script>` in the notice's html

## Changelog entry

* N/A

**Comment by tofumatt** [comment]
I encountered this as well on a _new_ site (Jurassic Ninja) that I'd never activated. With a local site I didn't see the error. I think this could be an escaping error, but I'm checking it now 😄

**Comment by tofumatt** [comment]
Looks like this is caused by https://github.com/google/site-kit-wp/commit/f5795b77ca8e04d9b709699c936b02214997a5e9#diff-4ac2714ea3636bda42f3097087752880, but I'm checking its parent commit just to be sure. Wrapping the content output by notices in `wp_kses_post` is causing the `<script>` tags to be removed, but `wp_kses_post` doesn't strip out the content _inside_ the `<script>` tag, just the tags themselves, so we get all the JS appearing inline.

**Comment by tofumatt** [comment]
Changing `wp_kses_post()` to use:

```php
echo wp_kses( $content, array(
				'a' => array(
					'class' => array(),
					'href' => array(),
					'id'  => array(),
					'rel' => array(),
				),
				'div' => array(
					'class' => array(),
					'id'    => array(),
				),
				'h3' => array(
					'class' => array(),
					'id'    => array(),
				),
				'label' => array(
					'class'  => array(),
					'for'    => array(),
				),
				'path' => array(
					'class' => array(),
					'd'     => array(),
					'fill'  => array(),
				),
				'script' => array(
					'async' => array(),
					'src' => array(),
					'type' => array(),
				),
				'svg'    => array(
					'class'   => array(),
					'viewBox' => array(),
				),
			) );
```

to ensure everything in https://github.com/google/site-kit-wp/blob/39027a54539a11ddde18a1850ea67941391f9162/includes/Core/Util/Activation.php#L159-L307 can be output still results in some content being cutoff:

<img width="1223" alt="Screenshot 2019-12-11 at 00 29 31" src="https://user-images.githubusercontent.com/90871/70580917-4dfdeb00-1bad-11ea-9fcd-28f8dd2c5540.png">

Using `wp_kses` might not be appropriate there—it's not clear to me why we use it there aside from passing VIP coding standards, as I would have thought any input would have been sanitised earlier. Maybe I'm missing something though 😢

At any rate, removing `wp_kses_post` and outputting `$content` directly there fixes the problem, so that's the cause of the bug.

**Comment by felixarntz** [comment]
This is a regression from #900 as @tofumatt already noticed, so we don't need a changelog message here. Preferably this could have been handled in that issue, but since the relation wasn't clear at first, let's track it via this one.

**Comment by aaemnnosttv** [comment]
CR ✅ 

I added a basic QA Brief as well covering two of the important notices we show. There are two others I found but they all use the same callback method for the content so they shouldn't be necessary to check (they're also more complicated to reproduce).

**Comment by cole10up** [comment]
**Tested**
Testing the PR for the initial install and activation looks good.

![image](https://user-images.githubusercontent.com/57115907/70636227-ffbb0d00-1be9-11ea-92ff-ac1280fc0386.png)

Deactivating and reactivating looks good.

Installing pre1.0 beta build and upgrading looks good as well
[google-site-kit.beta-1.0.3-release.zip](https://github.com/google/site-kit-wp/files/3951594/google-site-kit.beta-1.0.3-release.zip)

Pre-beta install
![image](https://user-images.githubusercontent.com/57115907/70639091-cfc23880-1bee-11ea-9a25-7e0d23eae66c.png)

Worked with @aaemnnosttv to upgrade the host to the latest develop zip
[google-site-kit.zip](https://github.com/google/site-kit-wp/files/3951572/google-site-kit.zip)

Looks good:
![image](https://user-images.githubusercontent.com/57115907/70642613-5deced80-1bf4-11ea-939b-462488eb7026.png)

Completed the setup without error:
![image](https://user-images.githubusercontent.com/57115907/70642775-aefce180-1bf4-11ea-8aa5-c8a3cfd11c38.png)

Passed QA ✅
