### ISSUE TITLE
Implement First-Party Mode Setup Banner with Enable and Dismiss Options

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9647]
## Feature Description

Develop a new `FirstPartyModeSetupBanner` component to notify users about First-party mode and guide them in enabling it. This banner will briefly explain the benefits of First-party mode and include options to enable the feature or permanently dismiss the banner.

For more details, refer to the [Design Doc](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.3d28075u80ju) and the [Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=2-1283&m=dev).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A First-Party Mode Setup Banner should notify users about the feature, providing an option to enable First-party mode and an option to dismiss the banner permanently.
* Banner Display Conditions:
    * The banner should appear if:
        * Either the Analytics or Ads module is connected.
        * First-party mode is currently disabled.
        * Both the `isFPMHealthy` and `isScriptAccessEnabled` server requirements are met.
    * The banner should not display if either the FPFE health check or script access checks fail.
* Banner Content:
    * Title: "Get more comprehensive stats by collecting metrics via your own site"
    * Description: "Enable First-party mode (beta) to send measurement through your own domain - this helps improve the quality and completeness of Analytics or Ads metrics. Learn more"
    * Learn More: Once the support documentation is ready, a link to the First-party mode documentation will be provided.
* Banner Actions:
    * The banner should include:
        * "Enable First-party mode": A button to activate the feature.
        * "Maybe later": A button to permanently dismiss the banner.
    * Enabling First-party mode should update the First-party mode settings in the database.
    * Dismissal Logic:
        * Once dismissed, the banner should not reappear for the user.
        * Display a tooltip informing users that they can enable First-party mode later in the Analytics or Ads settings screens.
* The banner should be implemented using the new notifications API.
* The Figma design should be the source of truth for the banner's content and styling.

## Implementation Brief

- [x] Use `notifications.registerNotification` method to to register the notifications from within `assets/js/googlesitekit/notifications/register-defaults.js`.
  - Pass the slug as `first-party-mode-setup-cta-banner` along with following object.
  - `Component` should be `FirstPartyModeSetupBanner` as explained below.
  - `priority` should be `320`.
    - The Sign In With Google banner's [priority](https://github.com/google/site-kit-wp/blob/44e0928b0a835d95e89bbe6225132aca5a4cd1d0/assets/js/modules/sign-in-with-google/index.js#L102) should be adjusted to `330` to appear after this one.
  - `areaSlug` should be `NOTIFICATION_AREAS.BANNERS_BELOW_NAV`.
  - `groupID` should be `NOTIFICATION_GROUPS.SETUP_CTAS`.
  - `viewContexts` should be `VIEW_CONTEXT_MAIN_DASHBOARD`.
  - `isDismissible` should be set to `true`.
  - In `checkRequirements` method, do the following.
    - Use the `isModuleConnected` selector from `CORE_MODULES` selector to check whether Analytics-4 or Ads module is connected or not.
    - Use `getFirstPartyModeSettings` selector from `core/site` store to retrieve the FPM settings.
    - It should return true only if all of the following conditions are met:
      - Either the Analytics or Ads module is connected.
      - First-party mode is currently disabled. Use `isFirstPartyModeEnabled` implemented in #9628
      - Both the `isFPMHealthy` and `isScriptAccessEnabled` server requirements are met. Use `isFPMHealthy` and `isScriptAccessEnabled` from #9628

- [x] Create a new component `FirstPartyModeSetupBanner` inside `assets/js/components/notifications/FirstPartyMode`.
  - This component will receive two properties `id` which is the slug passed in above step `first-party-mode-setup-cta-banner` and `Notification` component.
  - Use `useShowTooltip` function and pass `first_party_mode_setup_cta-notification` to check whether to show the toolip. This will return a function which should be called from within onDismiss handler mentioned below. Assign this to a `showTooltip` constant. `showTooltip` function will be used within the `onDismiss` callback mentioned below.
  - Use `useTooltipState` hook to check if the tooltip should be shown, pass the id argument which we received to the hook. If this is set to true, the tooltip should be returned using the `AdminMenuTooltip` component as can be [seen here](https://github.com/google/site-kit-wp/blob/440dcd6e8289a8776acc60ecb3c13f99bfd0ac5a/assets/js/modules/reader-revenue-manager/components/dashboard/ReaderRevenueManagerSetupCTABanner.js#L153-L170) for `ReaderRevenueManagerSetupCTABanner` component.
  - Create a onClick handler `onCTAClick` within the component. This should be async handler which will do the following things.
    - Dispatch an action `setFirstPartyModeEnabled` to set it as enabled and call `saveFirstPartyModeSettings` to save the settings.
    - Once that is done, call the `dismissNotification` action from `CORE_NOTIFICATIONS` store and pass `id` to it.
  - Wrap the `NotificationWithSVG` within `Notification` component and pass following props.
  - Pass the `title` and `description` props according to AC.
  - Learn more link will be implemented separately in #9699
  - In `actions` (for `ActionsCTALinkDismiss` components) prop pass following. Note that `onDismiss` and `dismissOptions` props are the new ones which we need to add to the component and explained below.
    - `id` should be the `id` which is received as prop.
    - `className` as `googlesitekit-setup-cta-banner__actions-wrapper`
    - `ctaLabel` as `Enable First-party mode`.
    - `dismissLabel` as `Maybe later`.
    - `onCTAClick` would be `onCTAClick` function defined previously.
    - `onDismiss` should call the `showTooltip` function.
    - `dismissOptions` pass `skipHidingFromQueue` property as `true`.
    - Following changes will need to be made to `ActionsCTALinkDismiss` component.
       - It should accept two new props namely:
         - `onDismiss`: This would be a function which will be further passed to `Dismiss` component.
         - `dismissOptions`: This will be an object which should be spread into the `dismissNotification` action's options object within the `handleDismiss` function. We need to pass `skipHidingFromQueue: true` in `dismissOptions` so that the component isn't immediately unmounted upon dismissal, thus allowing the tooltip to be rendered. Pass this to `Dismiss` component.
    - In `Dismiss` component, `dismissOptions` should be spread into the `dismissNotification` action's options object. 
  - Export the SVG image for `FirstPartyModeSetupBanner` from [figma](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=34-998&node-type=frame&m=dev) and pass it as `SVG` prop to the `NotificationWithSVG` component.
  - As the `FirstPartyModeSetupBanner` component will not be unmounted immediately we need to check whether the banner has been dismissed previously using `isItemDismissed` selector and passing id to that one. If its dismissed, skip rendering the banner.

### Test Coverage

1. Add stories for the setup banner component.
2. Add tests for the setup banner component where we need to consider different scenarios where banner should (or should not) display.
3. Fix any existing failing tests.

## QA Brief

1. Activate Site Kit and make sure that Analytics-4 or the Ads module is active and connected. Also, `firstPartyMode` feature should be enabled.

2. Go to Site Kit dashboard and run the following command in browser console.

```js
  await googlesitekit.api.get('core','site','fpm-server-requirement-status', undefined, { useCache: false });
```

this will set the `isFPMHealthy` and `isScriptAccessEnabled` flags in database to `true`.

3. Refresh the Site Kit dashboard, you should be able to view the FPM setup banner on screen. Make sure that the design is as per the figma and is consistent with the banners across Site Kit.

4. Clicking the `Maybe later` will dismiss the banner permanently and will display a tooltip as shown in Figma.

5. Clicking the `Enable First-party mode` button will enable the first party mode flag `isEnabled` in settings and save the settings. You will see a POST request to `/core/site/data/fpm-settings` in browser network tab. Once the feature is enabled and setting is saved, it will dismiss the banner; there would be another POST request to `/core/user/data/dismiss-item` endpoint to dismiss the banner.

6. If both Analytics-4 and Ads module are not connected, banner should not get displayed.

## Changelog entry

* Add the First-party mode setup banner to let users know about the feature and enable it from the dashboard.

**Comment by techanvil** [comment]
Hey @hussain-t, these AC LGTM. However, while reviewing a couple of things have occurred to me that should be captured in separate issues and maybe in the design doc:

- We should dismiss this banner when a user toggles the FPM switch in the settings screen, like we do with the Consent Mode switch for [example](https://github.com/google/site-kit-wp/blob/b94493bb2883b6c91615b05c63629a1b27b70bf7/assets/js/components/consent-mode/ConsentModeSwitch.js#L74-L95).
- It would be worth adding an issue for updating the "Learn more" link as this issue could well be implemented before the link is determined.

**Comment by hussain-t** [comment]
Thanks for spotting it, @techanvil. I will add them to the design doc and create separate issues.

**Comment by nfmohit** [comment]
Update: This issue is under consideration by @hussain-t  to determine if using the Notifications API is the wisest approach here, as we identified that the API does not support showing the tooltip once it is dismissed. We will either have to add the tooltip to a separate component within `DashboardMain` (which I recommend), or use the legacy notification rendering approach.

CC: @ivonac4 @techanvil @ankitrox

**Comment by jimmymadon** [comment]
@nfmohit @hussain-t The notifications API currently supports callbacks for dismissals as well as custom logic within a React component. We already have a reusable `useShowTooltip` hook, so we can easily make this work with the new infrastructure.

**Comment by nfmohit** [comment]
> The notifications API currently supports callbacks for dismissals as well as custom logic within a React component. We already have a reusable `useShowTooltip` hook, so we can easily make this work with the new infrastructure.

Thank you @jimmymadon. I understood that part. The only difference here is that the tooltip would need to be composed in a separate component instead of the notification component, as the notification component gets dequeued when it is dismissed. Is that right?

**Comment by nfmohit** [comment]
> We do have a `skipHidingFromQueue` option on dismissal for allowing the notification component to not be removed immediately (but to be removed on future page loads).
> 
> [site-kit-wp/assets/js/googlesitekit/notifications/datastore/notifications.js](https://github.com/google/site-kit-wp/blob/6e316b867c27bfde321a8b142bf155aa732f3d8c/assets/js/googlesitekit/notifications/datastore/notifications.js#L131)
> 
> Line 131 in [6e316b8](/google/site-kit-wp/commit/6e316b867c27bfde321a8b142bf155aa732f3d8c)
> 
>  	 * @param {number} [options.skipHidingFromQueue] Optional. A boolean value if notification should not be removed from the queue immediately.

Ah, that's very helpful, thanks @jimmymadon !

**Comment by nfmohit** [comment]
Excellent work, thank you for drafting the IB, @ankitrox! Please take a look at my comments below:

> * Use `notifications.registerNotification` method to to register the notifications from within the `ads` and `analytics` module.

- As this is not a module-specific notification, shouldn’t it be registered within `assets/js/googlesitekit/notifications/register-defaults.js` instead?
- Also, `isDismissible` should be set to true.

> * Use `useShowTooltip` function and pass `first_party_mode_setup_cta-notification` to check whether to show the toolip. This will return a function which should be called from within onDismiss handler mentioned below. Assign this to a `showTooltip` constant.

The IB does not mention where to use the `showTooltip` variable, or anything about how the tooltip would be composed and rendered.

The `useTooltipState` hook should be used to see if the tooltip should be shown, and if so, the tooltip should be returned using the `AdminMenuTooltip` component. You can take a look at how this is done within the `ReaderRevenueManagerSetupCTABanner` component.

> * In `actions` prop pass following:
>
>   * `id` should be the `id` which is received as prop.* `className` as `googlesitekit-setup-cta-banner__actions-wrapper`* `ctaLabel` as `Enable First-party mode`.* `dismissLabel` as `Maybe later`.* `onCTAClick` would be `onCTAClick` function defined previously.

Did you mean to use the `ActionsCTALinkDismiss` component in the `actions` prop? If so, there are a few additional changes that we need to make:

1. The `ActionsCTALinkDismiss` component should accept an `onDismiss` prop (similar to `onCTAClick`), which should be passed into the `Dismiss` component. This is necessary so that we can trigger the `showTooltip` function when the notification is dismissed.
2. The component shouldn't unmount immediately upon dismissal, so that the tooltip can be rendered. This can be done in the following way:
	i. The `assets/js/googlesitekit/notifications/components/common/Dismiss.js` component should accept an object prop, say `dismissOptions`, which should be spread into the `dismissNotification` action's options object within the `handleDismiss` function. This is necessary to pass `skipHidingFromQueue: true` to the `dismissNotification` action dispatch, so that the component isn't immediately unmounted upon dismissal, thus allowing the tooltip to be rendered.
	ii. The `ActionsCTALinkDismiss` component should accept a `dismissOptions` prop which should be passed into the `Dismiss` component.
	iii. Also, since the `FirstPartyModeSetupBanner` component won't get unmounted immediately, a check should be added before rendering the `Notification` component to ensure that it only renders when not dismissed.

Please let me know if you have any questions, thank you!

**Comment by ankitrox** [comment]
Hi @nfmohit ,

Thank you for reviewing the IB and providing your valuable insights into this.

Your suggestions are valid and I have modified the IB to accommodate those including the changes to `ActionsCTALinkDismiss` component by accepting new props.

Assigning this to you for another review.

**Comment by jimmymadon** [comment]
@ankitrox @nfmohit I just had a quick glance at the IB and adding a couple of pointers:

When registering the notification, use `groupID: NOTIFICATION_GROUPS.SETUP_CTAS`. This will ensure that this setup CTA renders separately from the default notification queue which speeds up the rendering. The priority will depend on whether this banner should be shown before or after the Sign in with Google banner which has priority 320. I've asked @marrrmarrr in this [slack message](https://fueled10up.slack.com/archives/CFFRMC5DE/p1732219946670699) to confirm what the order should be here.

**Comment by nfmohit** [comment]
Thank you @jimmymadon!

The IB looks largely good to me right now, thank you @ankitrox. The only last updates we'd need to make are adding the `groupID` parameter and updating the `priority` parameter as [Jimmy mentioned above](https://github.com/google/site-kit-wp/issues/9647#issuecomment-2492190212). Let's wait for Mariya's confirmation on the order to ensure what the priority should be on this one.

Thank you!

**Comment by nfmohit** [comment]
Thank you @techanvil! IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@ankitrox as per our conversation on Slack.   If you just have Analytics connected then the CTA banner does not appear.   If you connect Ads alone, or, with Analytics then the CTA does appear (assuming because Ads is connected).

**Comment by techanvil** [comment]
Back to you for another pass, @wpdarren.

**Comment by techanvil** [comment]
Sorry @wpdarren and @ankitrox, this needs a minor copy tweak as per this [Slack thread](https://fueled10up.slack.com/archives/C077DB69US2/p1733331164980559), "Analytics and Ads" should be changed to "Analytics or Ads".

@ankitrox, please can you raise a PR for this change?

**Comment by techanvil** [comment]
Back to you @wpdarren!

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- The First-Party Mode Setup Banner appears and was checked the Banner Display Conditions:
  - The banner appears only if either the Analytics and/or Ads module is connected.
  - First-party mode is disabled.
  - Both the isFPMHealthy and isScriptAccessEnabled server requirements are met.
- I checked the banner content:
  - Title: `Get more comprehensive stats by collecting metrics via your own site`
  - Description: `Enable First-party mode (beta) to send measurement through your own domain - this helps improve the quality and completeness of Analytics or Ads metrics.`
- I checked the banner actions:
  - The banner includes: `Enable First-party mode`: A button to activate the feature. Enabling First-party mode updates the First-party mode settings in the database. I went to the settings and could see the feature is successfully enabled. 
- I checked the dismissal logic on the`Maybe later`: A link to permanently dismiss the banner.  
  - Once dismissed, the banner does not reappear for the user.
  - Displayed a tooltip informing users that they can enable First-party mode later in the settings screens.
- Compared Figma design for the banner's content and styling.


<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/9616b57f-5dd5-46f0-bb35-93ebec90370e)
![Image](https://github.com/user-attachments/assets/f05f6a2a-f0a6-46d5-b2ae-7a62c4f59233)
![Image](https://github.com/user-attachments/assets/a7f91128-6871-4241-b184-35b9475fc496)
![Image](https://github.com/user-attachments/assets/1a4159e5-bcf6-41b2-8b20-cc8d17019a43)

</details>

There are a few notes to add to this testing because we're still engineering and not all of the AC points are met. 

1. The `Learn more` link is not currently appearing.  This will be a known issue on the bug bash board. 
2. The subtle success notification when the user has clicked on the `Enable First-party mode` CTA button is currently not appearing.
3. The QAB mentions `If both Analytics-4 and Ads module are not connected, banner should not get displayed. ` but it should be when either module is connected, so tested for all scenarios. 

We have tickets for both of these observations going through engineering.  cc @kelvinballoo FYI.
