### ISSUE TITLE
Group Measurement Toggles Together on Settings Screen

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9651]
## Feature Description

Following the updated designs, consolidate all measurement-related toggles into a unified group within the Analytics and Ads settings screens for improved organization and user experience.

For details, refer to the [Design Doc](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.9j8sokx66s0f).

#### Analytics

[Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=57-5010&node-type=frame&m=dev)

![Image](https://github.com/user-attachments/assets/b16b1bee-4c9a-4e1a-96b3-7749ca40fae9)

[Figma variant](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=27-2086&m=dev)
The Enhanced Measurement control is [enable-only](https://github.com/google/site-kit-wp/issues/7706). When Enhanced Measurement is already enabled for the selected data stream the EM control is non-interactive and will be displayed as follows:

![Image](https://github.com/user-attachments/assets/e7bc126f-5ad2-44bd-95b4-39cd1cb17bdc)

#### Ads

[Figma design](https://www.figma.com/design/udlPW35VZ0EDnSbRxYOGMj/First-party-mode?node-id=110-1594&m=dev)

![Image](https://github.com/user-attachments/assets/bfb9e696-2bfd-4808-9ff7-3c9e437cc1e8)

**Note:** This grouping can be implemented before the First-party mode toggle is available. The FPM toggle is being implemented in [9649](https://github.com/google/site-kit-wp/issues/9649) and will be added to the group once it is developed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The Ads settings edit screen should be updated to include an **Improve your measurement** section.
  - The **Enable enhanced conversion tracking** control should be moved to this new section. The control should retain its current behaviour.
- The Analytics settings edit screen should be updated to include an **Improve your measurement** section.
  - The **Enhanced measurement** and **Enable enhanced conversion tracking** controls should be moved to this new section.
  - Both controls should retain their current behaviour.
  - Notably, **Enhanced measurement** is an enable-only control: when enhanced measurement is already enabled for the selected data stream, the label will change to "Enhanced measurement is enabled for this web data stream". In a change from the current implementation, the switch should be replaced with a tick as per the Figma design.
- For both modules:
  - The copy for the **Enable enhanced conversion tracking** switch should be amended as follows:
    - Label: _Enhanced conversion tracking_
    - Description: _To track the performance of your campaigns, Site Kit will enable enhanced conversion tracking. [Learn more]()_
  - The new section should follow the appropriate Figma designs as linked in the Feature Description.

## Implementation Brief

- [x] Create a component `SettingsGroup` in `assets/js/components/settings`. The common styles for the component must be added in `assets/sass/components/settings`, it should have its own style (scss file).
  - It should accept the `title` and `children` props.
  - It should return a `div` with className like `googlesitekit-settings-module__group` wrapped around title and children.
  - The title should be the `h4` element.
  - After title, render the children.

- [x] In `assets/js/modules/ads/components/settings/SettingsForm.js`
  - Import the `SettingsGroup` component.
  - Pass the title to `SettingsForm` component as `Improve your measurement`.
  - Wrap `SettingsGroup` component around `ConversionTrackingToggle` component and `FirstPartyModeToggle` component (will be implemented in #9649 ), so that these will be passed as `children` prop.

- [x] In `assets/js/modules/analytics-4/components/settings/SettingsForm.js`
  - Import the `SettingsGroup` component.
  - Import the `SettingsEnhancedMeasurementSwitch` component.
  - Pass the title to `SettingsForm` component as `Improve your measurement`.
  - Wrap `SettingsGroup` component around `SettingsEnhancedMeasurementSwitch` component, `ConversionTrackingToggle` component and `FirstPartyModeToggle` component (will be implemented in #9649 ), so that these will be passed as `children` prop.
  - Pass `hasModuleAccess` prop to `SettingsEnhancedMeasurementSwitch` component.
  - `SettingsEnhancedMeasurementSwitch` component must be removed from `SettingsControls` in `assets/js/modules/analytics-4/components/settings/`.

- [x] Update the copy for `Enable enhanced conversion tracking` control to the one shown in Figma design.

- [x] `SettingsEnhancedMeasurementSwitch` is enable only control and switch would not appear once it is enabled, in such case when it is enabled once:
  - Import `assets/svg/icons/tick.svg` in `SettingsEnhancedMeasurementSwitch`.
  - Render the svg inside `p` tag wrapped in a span with the class name `googlesitekit-settings-enhanced-measurement-enabled-icon`
  - Apply height and width to the svg element.
  - Apply background color to span as per figma designs.
  - Make sure to add necessary spacings and border radius to match the figma designs. A reference of `SettingsCardConsentMode` [story](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/consent-mode-settingscardconsentmode--default) which uses same tick svg.

### Test Coverage

* Add tests for `SettingsGroup` component.
* Update VRTs.

## QA Brief

1. Setup the Site Kit plugin with Analytics and Ads module as connected.

2. Go to Site Kit > Settings > Analytics, `Edit` the analytics settings. It will open the Settings Edit screen of the Analytics.

3. Ensure that `Enhance Measurement` and `Enhanced Conversion Tracking` toggles are present in the new section as depicted in Figma Designs (links in AC).

4. Ensure that the toggle functionality is intact. Enabling/disabling the toggle should retain the state.

5. Go to Site Kit > Settings > Ads, `Edit` the ads settings. It will open the Settings Edit screen of the Ads module.

6. Ensure that `Enhanced Conversion Tracking` toggle is present in the new section as depicted in Figma Designs (links in AC).

**Note:** First-party mode toggle will be added separately in #9649

## Changelog entry

* Group measurement toggles together on the settings screen in the Ads and Analytics module edit sections.

**Comment by hussain-t** [comment]
AC ✅

**Comment by nfmohit** [comment]
Thank you for drafting the IB, @ankitrox !

> In `assets/js/modules/ads/components/settings/SettingsForm.js`
> 
> 
> * Move the entire `div.googlesitekit-settings-module__meta-item` at the bottom, just before closing tab of `div.googlesitekit-ads-settings-fields`.
> * Add one more `div` with class `googlesitekit-settings-module__measurement_toggles` immediately inside `div.googlesitekit-settings-module__meta-item` and then add rest of the components inside this div.
> * Add a heading `h4` with the text `Improve your measurement`.
> * ...
> * Add the styles in `assets/sass/components/ads/_googlesitekit-ads-settings.scss`.

> In `assets/js/modules/analytics-4/components/settings/SettingsForm.js`
> 
> 
> * Add a `div` with class `googlesitekit-settings-module__measurement_toggles` before `AdsConversionIDSettingsNotice` component, all other components must be wrapped inside this div.
> * ...
> * Add the styles in `assets/sass/components/analytics-4/_googlesitekit-analytics-settings-module.scss`.

As the group section has the same structure and styling, instead of building it in two different places, why don't we create a common component, say `SettingsGroup` in `assets/js/components/settings` with its own heading and stylesheet?

> * Move the entire `div.googlesitekit-settings-module__meta-item` at the bottom, just before closing tab of `div.googlesitekit-ads-settings-fields`.
> * Add one more `div` with class `googlesitekit-settings-module__measurement_toggles` immediately inside `div.googlesitekit-settings-module__meta-item` and then add rest of the components inside this div.

We generally consider `div.googlesitekit-settings-module__meta-item` to be the container of a single setting field, i.e. we should not make the group a child of this component. Instead, the `SettingsGroup` component described above should be the top-level element, or at best a descendent of the top-level element (e.g. `div.googlesitekit-ads-settings-fields`).

Last but not the least:

1. Please add an instruction to update the copy of the **Enable enhanced conversion tracking** switch for both modules.
2. Please add an estimate to the issue.

Please let me know if you have any questions, thank you!

**Comment by ankitrox** [comment]
Thank you @nfmohit . I've updated the IB as per the feedback, please let me know if there is anything else you want me to address or if it's looking fine.

**Comment by nfmohit** [comment]
Thank you, @ankitrox, for updating the IB according to my feedback. It looks great! There's just one little finding:

> * Import the `SettingsForm` component.

I believe you meant to say `SettingsGroup` component. As it is a very small change, I'll update it and move the issue to EB. Thank you!

**Comment by nfmohit** [comment]
IB ✅

**Comment by nfmohit** [comment]
I'm unassigning myself from this one as I won't be able to finish it before I come back next week.

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 

Tested and here are some issues to highlight:

### ITEM 1:
Check mark looks different in current implementation compared to figma.

<Details>
Figma: Notice how the joints are curved.

![Image](https://github.com/user-attachments/assets/3757233a-8381-4593-88d0-37ed03f6f28b)

Implementation: The joints are straight in this case

![Image](https://github.com/user-attachments/assets/8068abfb-31bd-45ec-82c8-5c63cf3108a2)


</Details>

____________________________________________________________________________________________

### ITEM 2:

Line doesn't appear on figma

<Details>
Figma:

![Image](https://github.com/user-attachments/assets/04300c77-041a-4380-b7c4-e13ad65232a7)

Current implemenation:

![Image](https://github.com/user-attachments/assets/1ec5950f-0456-4ba0-85a2-bacc0b4ce144)

</Details>
____________________________________________________________________________________________

### ITEM 3:

On mobile breakpoint:
- the checkmark looks squished
- The 'Enhanced Measurement' description is not aligned with the title.
- There is some space there that could be used. The text could essentially be moved to the left. I've highlighted this in blue.

<Details>

![Image](https://github.com/user-attachments/assets/3c46e15d-ee27-44fb-aead-b64b8f1aa224)


</Details>

____________________________________________________________________________________________

### ITEM 4:

Icons feel close to the texts.
On Figma, the spacing should be 9px. In implementation, it's 6px.

<Details>
Figma:

![Image](https://github.com/user-attachments/assets/bb7070e7-0aec-4000-a45a-23fa2c870e1b)

Implementation:

![Image](https://github.com/user-attachments/assets/fc258af7-f1a0-4424-ad2c-4126a0b2fc26)


</Details>

____________________________________________________________________________________________

### ITEM 5:

There was a conversation of whether the description texts should be below the icons/toggles rather than the Titles, to align with other parts of the screen.
Should we do that?

Details attached:

<Details>

![Image](https://github.com/user-attachments/assets/0c356314-0a2d-46d0-ac81-a4a96661df38)

</Details>

**Comment by ankitrox** [comment]
Thanks @kelvinballoo for reporting the issues. However; as we [discussed](https://fueled10up.slack.com/archives/C077DB69US2/p1733222915561089?thread_ts=1733164544.377789&cid=C077DB69US2) we will only focus on point 2 and 3 of the reported issues as others are there to maintain the consistency.

For point no. 3, I understood that there is some concern for unused space on left hand side of the toggle, but I think we should keep as is because this is padding and it needs to be consistent across RHS and LHS.

CC: @techanvil

**Comment by techanvil** [comment]
Thanks @ankitrox! As discussed, the idea is for the description text to use the full width in phone viewports, this has been addressed in the PR.

Back to you for another pass, @kelvinballoo.

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Thanks @ankitrox , @techanvil .
Noted on Item 1, 4 and 5 that won't need fixing.

Retested as follows for the issues highlighted:
**ITEM 2:**
There is no more line appearing just above the grey section.

<Details>

![Image](https://github.com/user-attachments/assets/6b7a436a-b5a5-4a7d-86fb-17e2fc71d375)

</Details>

**ITEM 3:**

On mobile breakpoint:
- the checkmark no longer looks squished
- The 'Enhanced Measurement' description is not aligned with the title.
- The text was moved to the left. 

<Details>

![Image](https://github.com/user-attachments/assets/0684f3e2-a4ea-44a9-9858-e2ef445fd5b8)

</Details>

____________________________

Other than that, the following were verified good:

- The Ads settings edit screen includes an Improve your measurement section.
- The Enable enhanced conversion tracking control is moved to this new section. The control retains its current behaviour.
- The Analytics settings edit screen includes an Improve your measurement section.
- The Enhanced measurement and Enable enhanced conversion tracking controls have been moved to this new section. Both controls retain their current behaviour.
- Notably, Enhanced measurement is an enable-only control: when enhanced measurement is already enabled for the selected data stream, the label will change to "Enhanced measurement is enabled for this web data stream". The switch is replaced with a tick as per the Figma design.
- For both modules:
   - The copy for the Enable enhanced conversion tracking switch is "Enhanced conversion tracking"
   - Description: To track the performance of your campaigns, Site Kit will enable enhanced conversion tracking. Learn more
- The new section follows Figma designs as linked in the Feature Description.

<Details>
Desktop, mobile and tablet viewports tested:

![Image](https://github.com/user-attachments/assets/363585c6-b14a-47fd-9c22-eb954a96cc7a)

![Image](https://github.com/user-attachments/assets/20255d82-18c8-4a1a-96b6-c919fcbca653)

![Image](https://github.com/user-attachments/assets/abddfdbf-b1dc-4393-9dc9-da5cc14d803b)

![Image](https://github.com/user-attachments/assets/ba6189db-ad48-4da4-8676-36d6baa140ea)

![Image](https://github.com/user-attachments/assets/541f0a10-9024-4000-8089-3a4eec173d73)

![Image](https://github.com/user-attachments/assets/a4b6517e-417e-489e-96e2-cad7c7213796)


</Details>

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@ankitrox I noticed in the Analytics settings view, the title highlighted is `Enhance Measurement `- I feel it should be `Enhanced Measurement ` — when you edit the Analytics settings it does say Enhanced Measurement  and also on the Figma designs.  So I feel this is a bug that we should fix for this release. I have moved it back to Execution. 

While the ticket is related to the FPM epic, within the 1.142.0 release this change will go out to users for this particular field. 

![Image](https://github.com/user-attachments/assets/94ea7e7a-1c5c-40bc-aee3-6dd324ce53ca)

**Comment by hussain-t** [comment]
@wpdarren, back to you for another pass.
