### ISSUE TITLE
GCP project is created using the wrong Google account

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9717]
## Bug Description

From the SiWG bug bash. Asana ticket can be found [here](https://app.asana.com/0/1208661003027471/1208796022161139/f).

GCP project is created using the browser logged in Google account as opposed to the SK connected Google account.

When using a deep link to the GCP page to create a project, pass the users email so the logged in browser Google account isn't user (as it may not match the SK connected email). 

A user started off a journey to create a GCP project with a specific Google account (sk connected), but the credentials created are based on a different Google account. This can result in client / authorization errors as per the below:

![Image](https://github.com/user-attachments/assets/4e386201-fd7a-4ff0-b4a6-2fa10e0adbd4)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

A note here: this link currency uses the account switcher but said feature is not supported by Google Cloud links, seemingly.

* The "Get your Client ID" button/link should direct users to `https://developers.google.com/identity/site-kit`, but with the current Site Kit user selected.
  * Because the account chooser does not work on this site, the `authuser` query param may be used if it can support the user's ID. Or a similar param should be supplied, to ensure the Site Kit user and the user interacting with `https://developers.google.com/identity/site-kit` is the same.

![Image](https://github.com/user-attachments/assets/1c2e143f-1104-42c3-ab0c-fc167e401b3e)

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by benbowler** [comment]
I spent some time looking into this today, the `authuser` query variable supposedly supports an email address on some Google products (source being Stack Overflow). However, I could only get the index of the user to work on this developer.google.com site.

<details>
<summary>Details</summary>
<br>
Index based values work, `authuser=0`:
![Image](https://github.com/user-attachments/assets/b4212877-2c67-4387-b421-d6bca62330f2)
`authuser=1`:
![Image](https://github.com/user-attachments/assets/e9613a51-5a33-461a-90b6-29812f02dfe1)
However passing and email here does not work, eg. `authuser=benbowlermusic@gmail.com`:
![Image](https://github.com/user-attachments/assets/218a27ed-6617-4909-b3ca-72ed12749900)

</details>

This means that we don't have a solution because we don't know which order (or if the user has even logged in to the account with their WP user email). We need to check on the Google side if they have either 1. an undocumented query param we can use or 2. they can add one for us to allow us to control this feature.

---

I also tried alternatives such as taking the user to the auth page with a continue param set but this still selected the first logged in user: `https://accounts.google.com/ServiceLogin?service=classroom&passive=true&Email=benbowlermusic@gmail.com&continue=https://developers.google.com/identity/site-kit`

---

Unlike in the comments in the Asana ticket, I was able to change the user I had logged in in developer site, however after switching user I wasn't taken back to the credentials page:

![Image](https://github.com/user-attachments/assets/b95cac4f-64a2-4451-a47d-4fe58eb62f7c)
![Image](https://github.com/user-attachments/assets/d4c0eea2-c3f4-4111-9a39-e74cb6a88113)

This makes user switching pretty bad UX here as the user will have to find the previous page again after changing their Google accounts.

**Comment by benbowler** [comment]
Updating here, the [account chooser](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/accountchooser--account-chooser) does work for this: `https://accounts.google.com/accountchooser?continue=https%3A%2F%2Fdevelopers.google.com%2Fidentity%2Fsite-kit&Email=benbowlermusic%40gmail.com`, rather than the `/ServiceLogin` endpoint I was trying. So we can be G2G with that approach, lmk if you want me to write the IB too or you can @tofumatt

**Comment by tofumatt** [comment]
@benbowler I just went through the flow on my site and everything seems to be working fine 🤔

@aaemnnosttv mentioned it was working for him as well: https://fueled10up.slack.com/archives/C0788NZMLF2/p1732725083939069

Seems we don't actually need this anymore, right? 🤔

**Comment by benbowler** [comment]
@tofumatt you and @aaemnnosttv are right, I retested this today, the link takes you to the account related to the Google account you setup SK with. I'll close the ticket.
