### ISSUE TITLE
Update direct script tag output to use `wp_print_inline_script_tag()`

### ISSUE THREAD

**Issue by westonruter** [google/site-kit-wp#9725]
## Bug Description

The `Consent_Mode` class is rendering JavaScript directly without the use of `wp_print_inline_script()`:

https://github.com/google/site-kit-wp/blob/440dcd6e8289a8776acc60ecb3c13f99bfd0ac5a/includes/Core/Consent_Mode/Consent_Mode.php#L232-L243

This is problematic because other plugins do not have the opportunity then to filter the attributes being added to the `script` tag. For example, if a site wants to enable [Strict CSP](https://web.dev/articles/strict-csp) (see [example plugin](https://gist.github.com/westonruter/c8b49406391a8d86a5864fb41a523ae9)), they aren't able to add the `nonce` attribute to this `script` tag. This is also problematic for plugins like Web Worker Offloading from Performance Lab as it isn't able to supply the `type="text/partytown"

## Steps to reproduce

1. Enable consent mode in Analytics
2. Observe attributes added via `wp_inline_script_attributes` are not reflected in the consent mode JS

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All script tags which are output directly via echo or templating should use `wp_*_inline_script_tag` functions instead
	* This use must be backwards compatible with WP 5.2 

## Implementation Brief

* [ ] Finish and merge https://github.com/google/site-kit-wp/pull/9726

### Test Coverage

* No changes needed

## QA Brief

* This issue changed the way JS is output to the page for Consent Mode defaults and update handling, and the SiwG button
* Basic testing of these features to make sure they work as before 

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment]
Thanks @westonruter! There is at least one more instance aside from Consent Mode with `Sign_In_With_Google.php` – should we update this to address both?

Beyond that, it's worth noting our minimum supported version of WP is 5.2, but as I'm sure you know, these script functions weren't added until 5.7. The good news however is that we have this function via a backport we added in `BC_Functions` which are available as static methods there, but it will only use the internal implementation if the global function isn't present. This means we should be able to use this to accomplish what you want here for folks on newer versions of WP since our backport is from before even the `wp_inline_script_attributes` filter was added 😄 

I'll rename this to address both going forward and add some AC so we can pick up the rest in CR.

**Comment by westonruter** [comment]
Good to know. Curious why is the minimum supported version so old? Looking at the stats, WP 5.6 has 0.8% market share.

**Comment by westonruter** [comment]
> There is at least one more instance aside from Consent Mode with `Sign_In_With_Google.php` – should we update this to address both?

That would be nice, although I don't believe its directly relevant for what is needed by https://github.com/WordPress/performance/pull/1686 which is to offload these gtag to Partytown.

**Comment by westonruter** [comment]
I went ahead and amended the PR with 42898caeb06f6dcc0fd1c8e62fd1556f94c4b1dc to also apply the change to `Sign_In_With_Google.php`.

**Comment by aaemnnosttv** [comment]
Thanks @westonruter, moving this into CR 👍

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified complete Consent mode functionality and it is working fine.
