### ISSUE TITLE
Implement Periodic Server Requirements Health Checks Using WP-Cron Job

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9768]
## Feature Description

Introduce periodic server requirement health checks for First-party mode to ensure it remains functional and responsive to any changes in server configurations. This will proactively detect and handle any issues that might impact the feature’s functionality.

The health checks will validate server configurations and update the First-party mode settings accordingly. If the checks fail, the feature will automatically revert to the default setup.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A periodic WP-Cron job should be implemented to perform server requirement health checks for First-party mode every hour.
* The health checks should include:
	* FPFE Health Check: Validate connectivity to the FPFE `/healthy` endpoint (e.g., https://G-1234.fps.goog/mpath/healthy).
	* Direct PHP Script Access Check: Verify access to the proxy script (`fpm/measurement.php`) via an HTTP request with the `healthCheck` query parameter.
	* The cron job should update the `googlesitekit_first_party_mode` settings based on the health check results:
	    * If either the FPFE health check or script access check fails:
	        * Set `isFPMHealthy` or `isScriptAccessEnabled` to `false` in the settings.
	        * Automatically disable First-party mode, reverting to the default configuration.
	    * If both checks pass:
	        * Ensure `isFPMHealthy` and `isScriptAccessEnabled` are set to `true`.

## Implementation Brief

* [x] Create a new file `includes/Core/Tags/First_Party_Mode/First_Party_Mode_Cron.php` modelled on `includes/Core/Remote_Features/Remote_Features_Cron.php`:
   * The `CRON_ACTION` const should be `googlesitekit_cron_first_party_mode_healthchecks`.
   * The schedule interval should be `time() + HOUR_IN_SECONDS`.

* [x] Update `includes/Core/Tags/First_Party_Mode/First_Party_Mode.php`:
   * Create a new method `healthcheck` which:
      * Runs the same health checks as the `fpm-server-requirement-status` REST endpoint:
         https://github.com/google/site-kit-wp/blob/0f39b60f6f0ebb57f0f462b0998182b293a36ac2/includes/Core/Tags/First_Party_Mode/REST_First_Party_Mode_Controller.php#L137-L139
      * Update all First-Party Mode settings using `$this->first_party_mode_settings->merge`.
   * Create a new private class value which accepts `First_Party_Mode_Cron` called `$cron`.
   * Update `__construct`, set `$this->cron` to a new instance of `First_Party_Mode_Cron` passing `array( $this, 'healthcheck' )`.
   * Create a new method `on_admin_init` [modelled on `Remote_Features_Provider`](https://github.com/google/site-kit-wp/blob/0f39b60f6f0ebb57f0f462b0998182b293a36ac2/includes/Core/Remote_Features/Remote_Features_Provider.php#L129-L134).
   * Update `register`, adding an action to call `$this->on_admin_init()` on `admin_init`.
 
* [x] Update `includes/Core/Util/Uninstallation.php` to clear the `First_Party_Mode_Cron::CRON_ACTION`.

### Test Coverage

* Create new test coverage for the `First_Party_Mode_Cron` class.

## QA Brief

1. Install [Advanced Cron Manager](https://wordpress.org/plugins/advanced-cron-manager/) plugin and activate.

2. Activate Site Kit and make sure that either Analytics or the Ads module is active and connected. Run the following command.

```js
  googlesitekit.data.select( 'core/site' ).getFirstPartyModeSettings();
```

the output would be (considering that the test site is a fresh install) like:

```js
    {
        "isEnabled": null,
        "isFPMHealthy": null,
        "isScriptAccessEnabled": null
    }
```

3. Visit the Site Kit dashboard. Now, go to `Tools > Cron Manager`. In the list of cron jobs, `googlesitekit_cron_first_party_mode_healthchecks` should be available.

4. Click `Execute now` for the job and let it complete, there would be a message `Event "googlesitekit_cron_first_party_mode_healthchecks" has been executed` once the job is completed.

5. Refresh the Site Kit dashboard and run following command.

```js
  googlesitekit.data.select( 'core/site' ).getFirstPartyModeSettings();
```

the output should be like 

```js
    {
        "isEnabled": null,
        "isFPMHealthy": true,
        "isScriptAccessEnabled": true
    }
```

6. Now, run following command to enable FPM

```js
  googlesitekit.data.dispatch('core/site').setFirstPartyModeEnabled( true );
  googlesitekit.data.dispatch('core/site').saveFirstPartyModeSettings();
```

Run,

```js
  googlesitekit.data.select( 'core/site' ).getFirstPartyModeSettings();
```

the output should now be

```js
    {
        "isEnabled": true,
        "isFPMHealthy": true,
        "isScriptAccessEnabled": true
    }
```

7. Update the `fpm/measurement.php` file. The following code should be update from

```php
  echo 'ok';
  exit;
```

to 

```php
  echo 'NOT ok';
  exit;
```

save the file on server.

8. Refresh the Site Kit dashboard, run the cron again manually from Advanced cron manager screen as stated previously.

9. Refresh the Site Kit dashboard and run following command.

```js
  googlesitekit.data.select( 'core/site' ).getFirstPartyModeSettings();
```

the output should be like 

```js
    {
        "isEnabled": true,
        "isFPMHealthy": true,
        "isScriptAccessEnabled": false
    }
```

## Changelog entry

* Add periodic server requirement health checks for first-party mode.

**Comment by techanvil** [comment]
AC ✅

**Comment by nfmohit** [comment]
Nice work on the IB, thank you @benbowler!

> * [ ] Update `includes/Core/Util/Uninstallation.php` to clear the `Conversion_Reporting_Cron::CRON_ACTION`. 

I believe you meant `First_Party_Mode_Cron::CRON_ACTION`, so I've updated that accordingly. Please let me know if that's incorrect.

IB ✅

**Comment by hussain-t** [comment]
Hi @benbowler, @nfmohit, regarding this point:

>If either setting is false, set `isEnabled` to false.

We should keep the `isEnabled` to remain `true` while setting the other properties (`isFPMHealthy` or `isScriptAccessEnabled`) to `false` if their respective checks fail. This is because we want to retain the information that First-party mode was enabled but has been interrupted and rolled back due to server configuration failures.

---
>Create a new method `healthcheck` which:
Runs the same health checks as the `fpm-server-requirement-status` REST endpoint:

An implementation detail, but it's worth noting that [these checks](https://github.com/google/site-kit-wp/blob/35b887b3a3dd346f50a6ee2fdb71ff5f1e4069ff/includes/Core/Tags/First_Party_Mode/REST_First_Party_Mode_Controller.php#L137-L145) can be extracted into a reusable method.

cc: @techanvil

**Comment by nfmohit** [comment]
Thank you @hussain-t !

In that case, I'll remove the part about changing `isEnabled` in the IB.

CC: @ankitrox since you're working on this in Execution.

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 

Hi @ankitrox , few observations/queries:

**ITEM 1:**
First sound I executed `googlesitekit.data.select( 'core/site' ).getFirstPartyModeSettings();` on a fresh install, I was expecting the following based on the QAB:
```
    {
        "isEnabled": null,
        "isFPMHealthy": null,
        "isScriptAccessEnabled": null
    }
```
That said, I got it as null, true, true as per the screenshot attached below.
Is there any concern here?
<Details>

![Image](https://github.com/user-attachments/assets/4f3fa94c-72c5-4794-9b9f-7c58cf73660d)

</Details>


**ITEM 2:**

For the part of the QAB where we are to update the `fpm/measurement.php` file, could you elaborate on the steps of where to amend that. 
I am using instawp and I have access to the DB editor but there are so many tables and thus, I am unsure where to amend it.

**Comment by ankitrox** [comment]
@kelvinballoo Thanks for checking this.

> ITEM 1:

Actually, this behaviour is expected because when we setup the fresh site, there is no cron job scheduled. Thus a job is [scheduled and run instantly](https://github.com/google/site-kit-wp/pull/9808/files#diff-5db947a8f631ec61f030229e77716d8375ac81d157aa7b16df83c05d9b72a590R58) which changes these flags in settings.

> ITEM 2:

This is a simple change in `wp-content/plugins/google-site-kit/fpm/measurement.php` file. If you are not sure about how to do that, we can ask anyone from engineering to test this point.

Please let me know if you have any further queries.

Thank you.

**Comment by kelvinballoo** [comment]
### QA update ⚠ 

Thanks @ankitrox , noted on this. I was able to verify the fpm measurement file in instawp after you gave the address.

One item to verify:
On the last step:
After we have updated the file, executed the cron job, and executed the **getFirstPartyModeSettings()** script,
I saw the attached uncaught error.
Does that warrant any fixes.

<Details>

![Image](https://github.com/user-attachments/assets/fb9f8f33-9ae7-44ce-99a2-3556d9ef2459)

</Details>
________________________________________________________

Other than that, the following were verified good, executed as per QAB:
- Activated Site Kit and made sure that either Analytics or the Ads module is active and connected. 
   After running the command:
   `googlesitekit.data.select( 'core/site' ).getFirstPartyModeSettings();`

   The output is null, true, true and is as expected per latest check with Ankit. 

   <Details >

   ![Image](https://github.com/user-attachments/assets/c0a578e2-80e4-4877-9c65-2036e40a0158)

   </Details>

- Under Tools > Cron Manager, googlesitekit_cron_first_party_mode_healthchecks is available.
   After executing the job and let it complete, the message "googlesitekit_cron_first_party_mode_healthchecks" appears.
   It executes hourly.
   <Details>

   ![Image](https://github.com/user-attachments/assets/24917b88-091e-4583-8aa4-98c296a9efc1)
   
   https://github.com/user-attachments/assets/3e086789-cf4a-4b63-a5d5-8fad05d5ffaf

   </Details>

-  After refreshing the Site Kit dashboard and running the following command:
   `googlesitekit.data.select( 'core/site' ).getFirstPartyModeSettings();`
   The result is null, true, true.

   <Details>

   ![Image](https://github.com/user-attachments/assets/aaa68de6-80d7-4947-a489-8de6be09f224)

   </Details>

- Now, after running following commands to enable FPM:
   googlesitekit.data.dispatch('core/site').setFirstPartyModeEnabled( true );
   googlesitekit.data.dispatch('core/site').saveFirstPartyModeSettings();
   The results become true, true, true.

   <Details>

   https://github.com/user-attachments/assets/718773b7-02d4-4e8c-ab03-6a9558188e2d

   </Details>

- After updating the fpm measurement file to 'NOT ok', executing the CRON and refreshing dashboard, the results are true, true, False
   <Details>

   https://github.com/user-attachments/assets/f6ca71be-65ca-480f-96d8-fc998b66a8f9

   </Details>

**Comment by kelvinballoo** [comment]
### QA update ✅ 

Confirmed with @ankitrox that the highlighted error is only because of Advanced cron manager, nothing related to Site Kit. As such, I will proceed with to Approval.

The following were verified good, executed as per QAB:

- Activated Site Kit and made sure that either Analytics or the Ads module is active and connected. 
   After running the command:
   `googlesitekit.data.select( 'core/site' ).getFirstPartyModeSettings();`

   The output is null, true, true and is as expected per latest check with Ankit. 

   <Details >

   ![Image](https://github.com/user-attachments/assets/c0a578e2-80e4-4877-9c65-2036e40a0158)

   </Details>

- Under Tools > Cron Manager, googlesitekit_cron_first_party_mode_healthchecks is available.
   After executing the job and let it complete, the message "googlesitekit_cron_first_party_mode_healthchecks" appears.
   It executes hourly.
   <Details>

   ![Image](https://github.com/user-attachments/assets/24917b88-091e-4583-8aa4-98c296a9efc1)
   
   https://github.com/user-attachments/assets/3e086789-cf4a-4b63-a5d5-8fad05d5ffaf

   </Details>

-  After refreshing the Site Kit dashboard and running the following command:
   `googlesitekit.data.select( 'core/site' ).getFirstPartyModeSettings();`
   The result is null, true, true.

   <Details>

   ![Image](https://github.com/user-attachments/assets/aaa68de6-80d7-4947-a489-8de6be09f224)

   </Details>

- Now, after running following commands to enable FPM:
   googlesitekit.data.dispatch('core/site').setFirstPartyModeEnabled( true );
   googlesitekit.data.dispatch('core/site').saveFirstPartyModeSettings();
   The results become true, true, true.

   <Details>

   https://github.com/user-attachments/assets/718773b7-02d4-4e8c-ab03-6a9558188e2d

   </Details>

- After updating the fpm measurement file to 'NOT ok', executing the CRON and refreshing dashboard, the results are true, true, False
   <Details>

   https://github.com/user-attachments/assets/f6ca71be-65ca-480f-96d8-fc998b66a8f9

   </Details>
