### ISSUE TITLE
Add full URL to Analytics dashboard

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#98]
## Feature Description

It would be great to see the full URL on hover in the Analytics dashboard rather than just the page titles. In some cases websites feature the same page titles for some of their URLs, in particular websites with a large inventory of content with auto generated sub-pages. 

## Proposed solution
Add a full URL on hover of the page title. Or alternatively add the full URL below the page title. 

![uidrBdWHhaE](https://user-images.githubusercontent.com/41326532/60498595-d13a1d00-9cae-11e9-99ec-0db86905b4e0.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The list of the most popular pages on the Analytics module page should also include the URL path for each page instead of only the page title (the same way this is in the popular pages widget in the Site Kit dashboard or WordPress dashboard widget).
* This should be updated in the legacy version of the widget as well as the refactored version (see #2068).

## Implementation Brief
* Using `/assets/js/components/DetailsPermaLinks.js`
	* Add a new prop, `serviceURL`: String and having `null` as default value.
	* The `googlesitekit-display-block` class name should only be applied to the first link if `serviceURL` is null, else the external icon will be aligned to the far right of the link.
	* The `href` of the first link should display `serviceURL` if it's not null, else display `detailsURL`.
	* The `external` prop of the first link should be true if `serviceURL` is not null, so that the external icon is displayed.
* Using `/assets/js/modules/analytics/components/module/ModulePopularPagesWidget/index.js`,
	* Update the first item of the `tableColumns` array to use the `DetailsPermaLinks` instead of the `Link` component, passing the `title`, `url` as the `path` prop and `serviceURL`.
* The changes from the previous bullet point should be applied to the legacy component as well, i.e `/assets/js/modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetTopPagesTable.js`.

### Test Coverage
* N/A

### Visual Regression Changes
* Visual changes should be noted for the above components.

## QA Brief

* on the top pages table of the Analytics dashboard check that:
  * the title links are being displayed by the 'DetailsPermaLinks' component
  * a full URL is displayed on hover of the page title or below the page title.

## Changelog entry

* Update popular pages list tables on the Analytics module dashboard to be consistent with the same components on the main Site Kit and WordPress dashboards.

**Comment by tofumatt** [comment]
IB ✅

**Comment by johnPhillips** [comment]
QA ✅

- **The title links are being displayed by the 'DetailsPermaLinks' component** ✓
I can see that the `DetailsPermaLinks` is being rendered. It produces two links: the title of the page, which points to the Analytics report for that page, and the URL to the page itself, which points at the page itself.

- **A full URL is displayed on hover of the page title or below the page title.** ✓
Hovering over the page title does not display anything (not sure what was meant / expected here - some sort of tooltip?), but the URL is definitely displayed below the page title. 

- **The list of the most popular pages on the Analytics module page should also include the URL path for each page instead of only the page title** . ✓
Verified that the page URL is displayed below the page title. 

- **This should be updated in the legacy version of the widget as well as the refactored version** ✓
Verified that the legacy versions both on the dashboard and the module page have been updated.

**Screenshot:**

![Screenshot 2021-04-23 at 17 02 31](https://user-images.githubusercontent.com/2470911/115899052-3481da00-a456-11eb-8168-8a928fe5acd1.png)

**Comment by johnPhillips** [comment]
Forgot to assign myself before QAing this 🤦
