### ISSUE TITLE
Multiple users connecting

### ISSUE THREAD

**Issue by billzyfem** [google/site-kit-wp#982]
## Feature Description

This was a deal breaker on using Google Site Kit which is super disappointing as it has potential..  When the admin connects everything up, it should be the setting that rolls across the entire site.  Not just for one user, clients complained it wasn't setup and they found it daunting to start clicking setting buttons and so forth.  

In all other GA plugins, the admin connects it all, then the features roll to all the uses without being able to affect the authorisation of GA.  Other plugins hide the main settings after they are initially set which forces admins to reconnect it if they decide to make changes.

Until this is fixed the plugin is unusable.  Good for developers, bad for clients.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Thanks a lot for your feedback!

This kind of data sharing has come up a few times and it's definitely an interesting use case. However, we need to make sure to get it right, as data sharing may be sensitive.

Please follow #6 for any updates on this matter.

**Comment by gounder** [comment]
Different teams maybe looking at the website back-end and reports being used by a marketing team. If this feature is left open in the back-end of WordPress. It might not be visible to someone who is reviewing who has access to the data from Google Search Console and/or Google Analytics. They might be removing access from Google but the sensitive data maybe visible through WP Dashboard.

My point is if someone needs to get access to the reports their authorization should at the level of Google Search Console and Google Analytics both of which use an email id and not just gmail ids (AFAIK). 

The flow could be improved though...
So I setup Site Kit by  logging in to the clients admin username and gmail id during deployment of the website we developed, now that I have the SEO contract I have my own admin username on the account, through which I signed and connected my own google account for which I had the necessary permissions. but the flow felt like I was resetting up Site kit instead of simple validation that I have access for Google Search Console and Analytics. Also glad to report that both the client and my wp user accounts show the dashboard correctly.
